### ISSUE TITLE
Define multicast support

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1001]
Multicast support was dropped from the 1.0 release.  The issue dealt with how a provider determines if an fi_addr is a unicast or a multicast address.  We need to define how multicast is integrated into the APIs.  Does it reuse fi_ops_msg?  Use a new set of ops?  Do multicast addresses get inserted into an AV?  Is there a special multicast AV?  Is multicast an AV attribute?  Do we add join/leave operations to fi_ops_cm instead?  etc.

**Comment by shefty** [comment]
Initial proposal:
Add join/leave calls to cm_ops.  Not sure if calls are sync or async.
Add insert_mcast call to av_ops.  AV configured with FI_MULTICAST for support.

**Comment by shefty** [comment]
Update - a UDP provider is being developed.  Once that provider is in place, we will have the ability to introduce and implement a multicast interface.  (UD QP support is not implemented for the verbs provider, and I'm not sure that the other providers support multicast.)

**Comment by shefty** [comment]
Proposal:

- Define FI_MULTICAST /* (1ULL << 5) */
- Use as EP capability bit if EP should support multicast.
- Specify as av_attr::flag when creating AV that will accept multicast addresses
- Set FI_MULTICAST flag when inserting multicast address into an AV
- (or require provider to distinguish)
- Multicast transfers use existing interfaces, where applicable

In theory, this would support a reliable multicast implementation by requesting FI_MULTICAST with an RDM EP, if any provider ever actually supported such a thing.

These changes could go in separate from an ABI update.

**Comment by goodell** [comment]
This sounds workable to me, especially if part of this process involves developing a prototype of the support in the UDP provider.

If it can work for the UDP provider, it will probably work for usnic.

**Comment by shefty** [comment]
Attempting to define something that works with the AV is causing issues, since the EPs that should be associated with the multicast address may not be known at the time the address is inserted.  Anyway, here's my latest thoughts that I will work from (writing them down in case I get distracted before I can complete the patch):

FI_MULTICAST is a capability bit.
Add CM::join()/leave() operations.
Join() returns an fi_addr_t that is selected by the provider.
Join completion is written to a bound EQ.
FI_MULTICAST op flag is used by the app when transmitting to the multicast address.
Completions set FI_MULTICAST flag for data received from multicast group.

The op flag is needed for the provider to distinguish between a multicast fi_addr_t and an AV fi_addr_t.  Theoretically, any operation can be a multicast operation (multicast RMA anyone?  tagged messages?).  Yeah, there's no use case, but at least the API doesn't prevent it.  Multicast is separate from the EP type, which would allow reliable multicast using an RDM EP.
