### ISSUE TITLE
sock_trigger.c is missing

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1011]
A build on master results in:

```
make  all-am
make[1]: Entering directory `/home/jsquyres/git/libfabric'
make[1]: *** No rule to make target `prov/sockets/src/sock_trigger.c', needed by `prov/sockets/src/src_libfabric_la-sock_trigger.lo'.  Stop.
```

**Comment by jsquyres** [comment]
@patrickmacarthur also notes that other problems emerged from PR #1009: see https://github.com/ofiwg/libfabric/pull/1009#issuecomment-99075069

**Comment by shefty** [comment]
PR was reverted.  Waiting for a fix from @jithinjosepkl to re-merge

**Comment by jithinjosepkl** [comment]
Oops, sorry. will add it now.
