### ISSUE TITLE
Provide link to official release directory from github web pages

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#1026]
When I download v1.0.0 and examine README I see some things that make we wonder if this is a release or a snapshot.

1) There are "@DATE@" and "@VERSION@" strings in the first few lines.

2) "Building" section implies ./configure exists and works in non-git releases - but it does not exist

3) When I run ./autogen:
```
$ ./autogen.sh 
+ autoreconf -ivf
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I config
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:72: error: possibly undefined macro: AC_PROG_CC_C99
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:4451: error: possibly undefined macro: AS_CASE
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

So v1.0.0 is D-O-A for me.

-Paul

**Comment by shefty** [comment]
> When I download v1.0.0 and examine README I see some things that make we
> wonder if this is a release or a snapshot.

What link did you download?  Note that github automatically generates a tar file of the git tree for all tags added to the git tree.  This tar file is not an official release.

- Sean

**Comment by PHHargrove** [comment]
I visited http://ofiwg.github.io/libfabric/ and near the bottom clicked "get the code".
That took me to https://github.com/ofiwg/libfabric where I clicked the Releases tab and then selected v1.0.0.

I do not see any other way to download releases from either the github.io or github.com sites.

-Paul

**Comment by shefty** [comment]
That's just an auto-generated tar file of the git tree that github creates.  Try using this link:
http://downloads.openfabrics.org/downloads/ofi/
We need to provide a link from the web page as to where the official releases are kept.

**Comment by goodell** [comment]
> 3) When I run ./autogen:
> `[...]`

@PHHargrove what version tuple of the autotools are you using when you see these errors?  It's possible that we just have an incorrect `AC_PREREQ` value (or `AM_INIT_AUTOMAKE` version argument).

**Comment by PHHargrove** [comment]
@goodell here are the versions I was trying:

autoconf (GNU Autoconf) 2.59
automake (GNU automake) 1.9.6
libtoolize (GNU libtool) 1.5.22

**Comment by goodell** [comment]
```
$ cd ~/git/autoconf
$ git log --reverse -S AC_PROG_CC_C99 | head -n 1 | cut -c 1-120
3271f21 Patch from Roger Leigh (with some minor changes) as follows: * NEWS: New macros AC_PROG_CC_C89, AC_PROG_CC_C99. 
$ git describe --contains 3271f21
AUTOCONF-2.59c~516
$ git log -1 AUTOCONF-2.59 --pretty=tformat:'%h  %aN  %cD'
99a48ad  Akim Demaille  Thu, 6 Nov 2003 09:32:24 +0000
$ git log -1 AUTOCONF-2.59c --pretty=tformat:'%h  %aN  %cD'
f9f8eee  Ralf Wildenhues  Wed, 12 Apr 2006 21:24:56 +0000
```
So it looks like `AC_PROG_CC_C99 didn't appear until autoconf 2.59c, which came *after* 2.59.  So we probably need to update the minimum required version to be 2.60.  I wouldn't be surprised if it actually needed to be even later than that for some other reasons we haven't hit yet.

There's already an automake 1.11 version requirement in the `configure.ac`, so you'll need to upgrade more than just autoconf if you want to autogen yourself on this machine.
