### ISSUE TITLE
prov/rxm: multiple rdma_reject: Invalid argument (-22) warnings

### ISSUE THREAD

**Issue by jakemoroni** [ofiwg/libfabric#10359]
Hello,

I have noticed that several warnings will be intermittently printed during high rank count MPI alltoall benchmarks when running with rxm/verbs. In my case, it starts to become really prevalent when benchmarking alltoall with 512 ranks over 8 nodes (64 PPN). With a lower number of ranks, it may still happen a few times, or sometimes not at all.

Example:
`libfabric:48900:1724184456::ofi_rxm:cq:rxm_handle_error():803<warn> fi_eq_readerr: err: Connection refused (111), prov_err: Unknown error -28 (-28)
libfabric:48868:1724184456::ofi_rxm:cq:rxm_handle_error():803<warn> fi_eq_readerr: err: Connection refused (111), prov_err: Unknown error -28 (-28)
libfabric:48506:1724184456::verbs:ep_ctrl:vrb_msg_ep_reject():325<warn> rdma_reject: Invalid argument (-22)
libfabric:48506:1724184456::ofi_rxm:ep_ctrl:rxm_reject_connreq():629<warn> fi_rejectInvalid argument (-22)
libfabric:47227:1724184456::verbs:ep_ctrl:vrb_msg_ep_reject():325<warn> rdma_reject: Invalid argument (-22)
libfabric:47227:1724184456::ofi_rxm:ep_ctrl:rxm_reject_connreq():629<warn> fi_rejectInvalid argument (-22)
libfabric:47445:1724184456::ofi_rxm:cq:rxm_handle_error():803<warn> fi_eq_readerr: err: Connection refused (111), prov_err: Unknown error -28 (-28)
libfabric:47213:1724184456::verbs:ep_ctrl:vrb_msg_ep_reject():325<warn> rdma_reject: Invalid argument (-22)
libfabric:47213:1724184456::ofi_rxm:ep_ctrl:rxm_reject_connreq():629<warn> fi_rejectInvalid argument (-22)`

That said, these warnings do not appear to affect functionality; the test will still complete successfully.

- Are these warnings normal?
- Are there some parameters that I should adjust to reduce them (besides disabling warning logs)?

Looking through the code, it seems that this behavior may be somewhat expected, but I am unsure about the "Invalid argument" warnings to rdma_reject.

**Comment by nikhilnanal** [comment]
The messages look like a normal case where peers are trying to connect to each other simultaneously while only one the connection request succeeds and the other gets rejected.

**Comment by j-xiong** [comment]
The "connection refused" error is normal. The "invalid argument" error returned from rdma_reject() looks suspicious. 

BTW, the "connection refused" error is logged sparsely -- at most one log per 2 seconds for each process.  It could be much more if regular logging is used.

**Comment by jakemoroni** [comment]
I did some digging into the `rdma_reject` "invalid argument" error and was able to reproduce at least one scenario that could cause it.

Basically, it can occur if you call `rdma_reject` on a connection attempt that has already been withdrawn by the client, so the connection request no longer exists.

The sequence of events would be:

- Client attempts to connect
- `RDMA_CM_EVENT_CONNECT_REQUEST` event is received by server and queued for processing
- Client disconnects
- `RDMA_CM_EVENT_DISCONNECTED` event is received by server and queued for processing
- Server begins processing the `RDMA_CM_EVENT_CONNECT_REQUEST` event but decides to reject the connection, perhaps because one already exists(?)
- `rdma_reject` call fails because the disconnect event was already received, but is still sitting in the queue

If this is indeed what is happening, then maybe it is a non-issue. I'm not sure if this type of race is avoidable even in the most simple RDMA CM async usage pattern. There's always a chance that the client can cancel the connection between when the `RDMA_CM_EVENT_CONNECT_REQUEST` event is received and when the `rdma_reject` call is made.
