### ISSUE TITLE
Data transfer function return types confusing

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#1038]
As per closed issue #153, it was decided to keep the return types of the data transfer functions as ssize_t for "future extensibility."  This makes the man pages a little confusing (ssize_t in the prototypes, but fi_errno in RETURN VALUE).  This could be alleviated with a small explanation.  That said, not all functions that return fabric errnos (e.g., fi_getinfo()) return ssize_t type, so if "future extensibility" means possibly larger than int errno values, it seems like all functions that return fabric errnos should use ssize_t (or a typedef of it).

**Comment by shefty** [comment]
At this point, the function return values are set until we create libfabric 2.0.  Data transfer and read type calls return ssize_t.  Other functions return int.  The functions that return ssize_t were defined to match with the POSIX socket/file calls (send, read, recv, write, etc.)  This allows those functions to return a number of bytes, if the interfaces ever support streaming operations or can complete partial transfers.
