### ISSUE TITLE
usnic: fix fi_av_close memory leak

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#1039]
Bug originally spotted by @xuywang and reported in email:

> According to fi_av man page, fi_av_close should free any memory allocated for resolved addresses. See below
>
> **fi_av_remove**
> 
> fi_av_remove removes a set of addresses from an address vector. All resources associated with the indicated addresses are released, and no future references to either the mapped address (in the case of FI_AV_MAP) or index (FI_AV_TABLE) are allowed.
> 
> The use of fi_av_remove is an optimization that applications may use to free memory allocated with addresses that will no longer be accessed. Inserted addresses are not required to be removed. **fi_av_close will automatically cleanup any resources associated with addresses remaining in the AV when it is invoked.**
> 
> 
> I didn’t find there is any code in usdf_av_close()  that does the check and free memory.

The AV code could also use a scan for other memory allocation bugs.  It looks to me like `usdf_am_remove` is casting `fi_addr` to a `usd_dest*` instead of casting `*fi_addr`, which looks like a bug to me.

**Comment by bturrubiates** [comment]
This happens because we do not have an internal data structure tracking the data being handed out upon `fi_av_insert`. All associated resources are removed in a call to `fi_av_remove`, but not upon `fi_av_close`. This can be fixed by adding a data structure to track inserted items. Fix coming for 1.4.

**Comment by bturrubiates** [comment]
Fixed by #2397.
