### ISSUE TITLE
usnic: fi_tx_attr::inject_size is not being set nor checked

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#1044]
All of the endpoint types are reporting `inject_size` of `0` in the TX attributes, even though RDM and MSG both support 64-byte inject sizes.  Furthermore, I don't think any of the endpoint creation, etc. routines are checking that the user-requested value is within the provider's limit.

**Comment by zakattacktwitter** [comment]
Hi, inject_size is being reported and used by the verbs provider. That said, it has some bugs. The current code does not consider the size of the header along with the message size, triggering crashes when trying to send. For example my setup reports 74 bytes for inject_size, but if I send a msg between 33 bytes and 74 it will crash, anything 32 bytes and below is successfully injected and anything above 74 works fine.

Been meaning to post a pull request with this fix but haven't had time. Hope this helps.

**Comment by bturrubiates** [comment]
@zakattacktwitter This issue is specifically for the usnic provider, I've opened an issue for you. It's #1079.

**Comment by bturrubiates** [comment]
This issue can be closed.
