### ISSUE TITLE
fi_tostr_order doesn't properly handle FI_ORDER_NONE

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1053]
I don't know if this is intended behavior but the output of the fi_info test can't output FI_ORDER_NONE. I just noticed this. The definition for `IFFLAGSTR` is: 
```c
#define IFFLAGSTR(flags, SYM) \
        do { if (flags & SYM) strcatf(buf, #SYM ", "); } while(0)
```
But the definition for FI_ORDER_NONE is: 
```c
#define FI_ORDER_NONE           0
```
Should the definitions for FI_ORDER_* just all be bumped up one?

**Comment by jsquyres** [comment]
What's our ABI / backwards compatibility policy?  I'm guessing we can't change the FI_ORDER_* values until a later version (e.g., 1.x -> 2.x, or 1.0.x -> 1.1.x, at the earliest)...?

**Comment by goodell** [comment]
`FI_ORDER_NONE` should be `0`.  It indicates the absence of any flags, not really a flag in and of itself, right?  In other words, if you changed `FI_ORDER_NONE` to have its own non-zero value then this code would make even less sense than it currently does `FI_ORDER_NONE | FI_ORDER_RAR`.

If you dislike how it is displayed by `fi_info`, we could look at changing that output formatting, but I think it's best the way it currently is.

**Comment by bturrubiates** [comment]
Okay. The other values have a textual representation so I figured this one would too but was confused when it didn't display anything.
