### ISSUE TITLE
RFC: move fi_info from fabtests to libfabric

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1064]
libibverbs has ibv_devinfo (and friends), which is quite useful in determining what devices are available on a system.  It also functions as a de facto 1st-level diagnostic (i.e., lots of things have to be configured and running properly just to see the devices listed in ibv_devinfo).

Libfabric needs something similar to be installed by default (not in a 2nd package with "tests" in the name that is almost guaranteed not to be installed by default on distros).

I suggest the following (comments welcome):

* Move fi_info from fabtests to libfabric
* The default output of fi_info should be (significantly) shortened to show the available endpoints and a few key attributes of each
    * The current giant/verbose output can be displayed if "-v" is used on the command line
* The registered configuration variables can also be displayed, along with their help strings (perhaps only in the "-v" output)

**Comment by shefty** [comment]
After carefully considering this for 3 minutes, I agree with this proposal.  This would also give us a mechanism to display the environment variables.

**Comment by pmmccorm** [comment]
+1 from me too. I think I opened an issue about printing shorter output by default. I have it about half done in a local branch.

**Comment by bturrubiates** [comment]
Sounds like a good idea.

How will this affect the rest of fabtests? Do you think it would be worthwhile to add an option in the fabtests parsing logic to output the "devinfo"? If that's a consideration then we should consider picking some other switch (not `-v`).

**Comment by shefty** [comment]
Ben, can you clarify what you meant?  Moving fi_info should not affect any other fabtests.  Were you asking for all tests to produce the same output as fi_info?

**Comment by pmmccorm** [comment]
The way I had it in my local branch is: --version will print out fabtests/api version info and -v prints out the complete output.

Please comment on issue fabtests 260 with how the short format should look.

**Comment by bturrubiates** [comment]
@shefty 
Yeah, let me try to clarify. Currently, `fi_info` functions as a diagnostic test. This functionality only lives in `fi_info` and can't be invoked from any other tests. Since `fi_info` is becoming a bit more special purpose and the functionality is becoming more accessible, it could be added as common functionality (rather than making `fi_info` special with a `-v`). I guess I was thinking of a situation where `fi_info` isn't present, but other tests are (which sounds unlikely).

**Comment by shefty** [comment]
The proposed change was to always make fi_info available (ships with libfabric itself).  I don't think anyone was suggesting that it be more focused, only that the default output be reduced some.

Fi_info mostly uses the string print functions exported by libfabric, which any test could use.  I don't think I'm still quite following your thinking yet.

**Comment by bturrubiates** [comment]
Nevermind, that's alright Sean. It probably doesn't make sense.

It's the difference between: 
```
$ ./fi_info -v
```

and 

```
$ ./fi_info -z
$ ./fi_ud_pingpong -z
```

Where `-z` is some common flag to output the diagnostic information.
