### ISSUE TITLE
OFED 3.18 installation issue on PPC

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1065]
libfabric does not install on PowerPC.  As I understand the problem, the PSM provider depends on the PSM RPM, which is not available on PPC.  As I'm not an RPM expert, I don't know how to resolve this problem.  We want libfabric on PPC, but need to disable the requirement for the PSM provider on that platform.

**Comment by shefty** [comment]
tagging @j-xiong on this issue

**Comment by j-xiong** [comment]
I think it is a good idea to move provider specific requirement to provider configure script. We did encounter similar issue before in a customised build where we had to remove the dependence on ibverbs,  rdmacm, etc.

**Comment by shefty** [comment]
@j-xiong are you saying that you agree with #1069 and that that change will fix the issue?

**Comment by j-xiong** [comment]
I agree with the general idea of #1069. However, as discussed there, the specific changes are still debatable. We don't necessarily need the provider specific script to define the names of the rpm dependencies -- the names can still be defined in the main spec.in file, but can be turned on/off by variables set in the provider specific script. Patrick's suggestion of turning on/off the dependencies as a whole also works. It's just nicer to be able to control individual dependencies.

**Comment by shefty** [comment]
I was able to get the actual build error:

Running  LDFLAGS=' -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64
-mcpu=power7 -mtune=power7 -m64 -g -O2 -L/usr/lib64' CFLAGS=' -O2 -g -pipe
-Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7
-mtune=power7 -m64 -g -O2' CPPFLAGS=' -O2 -g -pipe -Wall
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7
-mtune=power7 -m64 -g -O2' CXXFLAGS=' -O2 -g -pipe -Wall
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong
--param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mcpu=power7
-mtune=power7 -m64 -g -O2' FFLAGS=' -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2
-fexceptions -fstack-protector-strong --param=ssp-buffer-size=4
-grecord-gcc-switches   -m64 -mcpu=power7 -mtune=power7 -m64 -g -O2' LDLIBS='
-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64
-mcpu=power7 -mtune=power7 -m64 -g -O2 -L/usr/lib64' rpmbuild --rebuild 
--define '_topdir /var/tmp//OFED_topdir' --define 'dist %{nil}' --target ppc64
--define '_prefix /usr' --define '_exec_prefix /usr' --define '_sysconfdir
/etc' --define '_usr /usr'
/tmp/ofed/OFED-3.18-20150608-2241/SRPMS/libfabric-1.0.0-1.src.rpm
warning: user vlad does not exist - using root
warning: group vlad does not exist - using root
warning: user vlad does not exist - using root
warning: group vlad does not exist - using root
error: Failed build dependencies:
        infinipath-psm-devel is needed by libfabric-1.0.0-1.ppc64
Installing /tmp/ofed/OFED-3.18-20150608-2241/SRPMS/libfabric-1.0.0-1.src.rpm
Building target platforms: ppc64
Building for target ppc64

**Comment by pmmccorm** [comment]
Can we just make infinipath-psm compile on ppc64 ?

**Comment by shefty** [comment]
This has been fixed in either the 1.1 or 1.1.1 release.
