### ISSUE TITLE
libfabric build error on Xeon Phi in OFED 3.18

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1066]
Somewhat related to #1065.  The PSM provider fails to build on Xeon Phi platforms.  The issue is that the PSM library is renamed on Xeon Phi, versus Xeon.  (I have no idea why.)  At the very least, we need to disable PSM on Xeon Phi, so that it doesn't break the build.  Ideally, the provider needs to handle the renamed library.

**Comment by jsquyres** [comment]
Can you provide the name of the PSM library on both platforms?  I.e., lib[foo].so

**Comment by pmmccorm** [comment]
See: http://bugs.openfabrics.org/bugzilla/show_bug.cgi?id=2544

**Comment by shefty** [comment]
tagging @j-xiong on this issue
