### ISSUE TITLE
Wrong error string returned by fi_strerror for FI_ECRC, FI_ETRUNC, FI_ENOKEY, and FI_ENOCQ

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#1086]
If errnum is one of FI_ECRC, FI_ETRUNC, FI_ENOCQ, or FI_ENOKEY, the returned error string will be incorrectly returned as the code for FI_EOTHER, or 'Unspecified error'. The FI_ERRNO_MAX variable just needs to be updated. 

This could be addressed in a number of different ways. 
* The FI_ERRNO_MAX value could just be updated, but then this problem could occur again in the future if a new error code is introduced but FI_ERRNO_MAX isn't updated. 
* The FI_* specific values that aren't mapped to existing codes (FI_* > FI_EOTHER), could be placed in an enumeration in the fi_errno.h file. If new errors are added, they could be added before FI_ERRNO_MAX and no one would need to worry about updating FI_ERRNO_MAX.

Example: 
```C
enum {
    FI_EOTHER = FI_ERRNO_OFFSET, /* Unspecified error */
    FI_ETOOSMALL,                /* Provided buffer is too small */
    FI_EOPBADSTATE,              /* Operation not permitted in current state */
    FI_EAVAIL,                   /* Error available */
    FI_EBADFLAGS,                /* Flags not supported */
    FI_ENOEQ,                    /* Missing or unavailable event queue */
    FI_EDOMAIN,                  /* Invalid resource domain */
    FI_ENOCQ,                    /* Missing or unavailable completion queue */
    FI_ECRC,                     /* CRC error */
    FI_ETRUNC,                   /* Truncation error */
    FI_ENOKEY,                   /* Required key not available */
    FI_ERRNO_MAX
};
```

The following code was pulled from src/fabric.c:
```C
#define FI_ERRNO_MAX	FI_ENOCQ

static const char *const errstr[] = {
	[FI_EOTHER - FI_ERRNO_OFFSET] = "Unspecified error",
        /* snip */
	[FI_ENOCQ - FI_ERRNO_OFFSET] = "Missing or unavailable completion queue",
	[FI_ECRC - FI_ERRNO_OFFSET] = "CRC error",
	[FI_ETRUNC - FI_ERRNO_OFFSET] = "Truncation error",
	[FI_ENOKEY - FI_ERRNO_OFFSET] = "Required key not available",
};

const char *DEFAULT_SYMVER_PRE(fi_strerror)(int errnum)
{
	if (errnum < FI_ERRNO_OFFSET)
		return strerror(errnum);
	else if (errnum < FI_ERRNO_MAX)
		return errstr[errnum - FI_ERRNO_OFFSET];
	else
		return errstr[FI_EOTHER - FI_ERRNO_OFFSET];
}
```

**Comment by hppritcha** [comment]
How is this issue related to #1088?

**Comment by hppritcha** [comment]
reopening, no idea why it was closed by @jsquyres

**Comment by jsquyres** [comment]
Oy, sorry -- I apparently put the wrong issue number in my commit message.  Sorry. :frowning:

**Comment by jsquyres** [comment]
Oh, now I see -- I incorrectly *referred* to this issue from #1088.  And #1088 is closed.  But *this* PR never got closed.
