### ISSUE TITLE
Clarification of behavior of mode bits 

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1093]
When verifying the attributes for `tx_attr` and `rx_attr` a provider might want to make sure that the required mode bits are set. 

Something like: 
```c
if ((hints->tx_attr->mode & REQ_MODE) != REQ_MODE)
		return -FI_ENODATA;
```

The `fi_info` test (that is now moved...) doesn't seem to set `tx_attr->mode` which results in `-FI_ENODATA` from the provider. Is this expected behavior, or is it a flaw of the application? 

I searched before asking to see if this had been discussed and stumbled upon PR #714. 

If `hints->tx_attr->mode` is set to `0` then this could mean that the app either didn't bother setting the value, or the app doesn't support any of the modes. So it's difficult to distinguish correct behavior in this case.

@shefty @goodell

**Comment by shefty** [comment]
Hmm... I see 2 reasonable options here:

1 Ignore tx/rx attr mode bits on input to fi_getinfo.

2. If tx/rx attr mode bits are 0, use the fi_info mode bits

**Comment by bturrubiates** [comment]
Well, doesn't the provider need to make sure they can support the tx/rx attr mode bits?

If it's 0 isn't it still valid for an application to not support any of the mode bits?

**Comment by shefty** [comment]
> Well, doesn't the provider need to make sure they can support the tx/rx
> attr mode bits?

Mode bits are a requirement on the app, not the provider.  A provider can always clear mode bits.

**Comment by goodell** [comment]
> Mode bits are a requirement on the app, not the provider.  A provider can always clear mode bits.

I think Ben's point was that if the provider has required modes (e.g., `FI_LOCAL_MR`), then the provider is obligated to check that the app set that bit in the passed in mode hints and return `-FI_ENODATA` if the app did not.  So in some sense the absence of certain mode bits can end up being a requirement on the provider, and the provider may not always be able to support that requirement.

**Comment by shefty** [comment]
And to restate, the options that I see for the provider are:

1.  Ignore tx/rx attr mode bits on input to fi_getinfo.
2.  If tx/rx attr mode bits are 0, use the fi_info mode bits.

or, I guess, also:

3. Check mode bits from fi_info + rx_attr + tx_attr, but only if rx_attr and tx_attr are provided.

**Comment by shefty** [comment]
FWIW, the verbs provider uses option 2.  If rx/tx attr mode = 0, the mode checks are done using fi_info mode.

**Comment by goodell** [comment]
> And to restate, the options that I see for the provider are:

Sure, and those are the two options that we see as well, with a preference for (2), I think.  But I think we should settle on one or the other for all providers, since this (hypothetically) affects how applications should be written.

**Comment by shefty** [comment]
I agree.  Is everyone in agreement with option 2?

**Comment by bturrubiates** [comment]
Sure, option 2 works. I was just wondering whether the ambiguity between not being set and being set to 0 would be an issue.

**Comment by shefty** [comment]
I think the man pages need to be updated to reflect whatever option we select.

**Comment by sayantansur** [comment]
Option 2 works for me: "If tx/rx attr mode bits are 0, use the fi_info mode bits."

**Comment by hppritcha** [comment]
another vote for option 2.

**Comment by goodell** [comment]
Sounds like consensus to me.

@bturrubiates Will you fix the man pages either in a separate commit in PR #1094 or as a separate PR?

**Comment by shefty** [comment]
I have an update that I'm about ready to push for comments

**Comment by shefty** [comment]
See #1100
