### ISSUE TITLE
Add fork support for new connections

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#11]
From the OFIWG F2F, there was a request to allow an application to indicate that a new connection request would be handed off to another process (forked or otherwise). The idea is that the provider could arrange its data structures accordingly, so that the new connection could successfully be migrated to another process.

**Comment by jsquyres** [comment]
What would be nice is if, upon fork, all handles in the child go stale -- any attempt to use them would (safely) return an error.

**Comment by shefty** [comment]
This is 6 years old with no action.  Closing
