### ISSUE TITLE
Convert remaining environment vars to use new fi_var.h API

### ISSUE THREAD

**Issue by pmmccorm** [ofiwg/libfabric#1106]
Specifically the FI_LOG_* set.

I have a patch in my local tree that does some of this work.

Issue encountered: if we use the "core" provider to register the variables all their names will be changed from FI_LOG_* to FI_CORE_LOG_*

If this is not OK then an additional internal-only API might need to be added to keep the original names.

**Comment by shefty** [comment]
I would like to keep the original names. :/

**Comment by j-xiong** [comment]
Could the "core" provider be treated differently so that it generates "FI_XXX" instead of "FI_CORE_XXX"? After all "core" is not really a provider. This way we can keep the API unchanged.

**Comment by j-xiong** [comment]
And if NULL is used instead of "core" the checking could be a little bit easier.

**Comment by pmmccorm** [comment]
I thought of that too: if provider is NULL or "core" or (some special case) treat it slightly differently and register it as FI_XXX.

Benefits: use existing API. easy change.
Drawbacks: possible to abuse, API is not as clean.

I vote for this solution.

**Comment by shefty** [comment]
I vote for handling this as a special case.
