### ISSUE TITLE
FI_LONG_DOUBLE size

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#1124]
The OFI man pages say that FI_LONG_DOUBLE and FI_LONG_DOUBLE_COMPLEX correspond to the IEEE 754 defined values.

However, neither IEEE 754, nor C doesn't seem to define the storage sizes of these types. From the gcc man page. Long double w/ 128b storage may be used for Quad precision ops.

Somebody should also inspect FI_DOUBLE_COMPLEX sizes. I couldn't find anything on those in the gcc man pages.

```
   -m96bit-long-double
   -m128bit-long-double
       These switches control the size of "long double" type.  The i386 application binary interface specifies the size to be 96 bits, so -m96bit-long-double is the default in 32-bit mode.

       Modern architectures (Pentium and newer) prefer "long double" to be aligned to an 8- or 16-byte boundary.  In arrays or structures conforming to the ABI, this is not possible.  So specifying -m128bit-long-double aligns "long double" to a 16-byte
       boundary by padding the "long double" with an additional 32-bit zero.

       In the x86-64 compiler, -m128bit-long-double is the default choice as its ABI specifies that "long double" is aligned on 16-byte boundary.

       Notice that neither of these options enable any extra precision over the x87 standard of 80 bits for a "long double".

       Warning: if you override the default value for your target ABI, this changes the size of structures and arrays containing "long double" variables, as well as modifying the function calling convention for functions taking "long double".  Hence they
       are not binary-compatible with code compiled without that switch.

   -mlong-double-64
   -mlong-double-80
   -mlong-double-128
       These switches control the size of "long double" type. A size of 64 bits makes the "long double" type equivalent to the "double" type. This is the default for 32-bit Bionic C library.  A size of 128 bits makes the "long double" type equivalent to
       the "__float128" type. This is the default for 64-bit Bionic C library.

       Warning: if you override the default value for your target ABI, this changes the size of structures and arrays containing "long double" variables, as well as modifying the function calling convention for functions taking "long double".  Hence they
       are not binary-compatible with code compiled without that switch.
```

**Comment by shefty** [comment]
I don't believe we ever settled on a satisfactory solution for how to handle this, which I'm guessing doesn't exist. anyway.  What do the applications need in terms of documentation to make the atomic definitions useful?

**Comment by jeffhammond** [comment]
Does OFI provide a way to query the storage size of types?  The MPI and Fortran 2008 analogs - at least at runtime - are `MPI_Type_size` and `STORAGE_SIZE`, respectively.  I think it would also be fine if the OFI header provided this information via a preprocessor macro if it is known at compile time.

As long as the compiler/processor and OFI agree on the implementation, I think things will be ok.  But what if OFI wants to have `sizeof(long double)` be 16 because of alignment, whereas the compiler only uses 12?

Honestly, I think `long double` is completely disgusting and would rather see us specify a fixed-width 128b floating-point type that supports no less than 64b but potentially 80b, 106b or 128b of numerical precision, which correspond to extended double, double double and quadruple precision, respectively.

If we have a fixed-width type that is bigger than C's `long double`, then the OFI application (e.g. MPI) will may have to copy into temporary storage, but there are a variety of contexts in which this will have no discernible overhead.

**Comment by shefty** [comment]
I created a patch that defined FLOAT32, FLOAT64, FLOAT128, etc.  But we already have a release of the software with providers making use of the C types float, long double, ... So, these would need to be new definitions.

I can extend the atomic interface with a call that is equivalent to MPI_Type_size (who in the world is deciding on the upper/lower case characters in MPI and can we flog them?)  I can either add an alignment call as well, or just define that variables must be aligned to the next 'natural' boundary.  I.e. a 96-bit variable is aligned to a 16-byte boundary on a 64-bit processor.  (I will need to verify that this is normally true in practice.)

**Comment by jeffhammond** [comment]
@shefty The MPI C interface is mixed case so that it cannot conflict with the Fortran interface functions of the same name, which have compiler-specific casing that may be all-upper or all-lower.  The wisdom of this approach is clear when comparing to OpenMP, which _requires_ compiler support to not generate symbol conflicts between e.g. `omp_num_threads` in C and `omp_num_threads` in Fortran when using the IBM XLF compiler (because it generates lower-case symbols with no trailing underscores).

Whether or not you can flog Bill Gropp is not clear to me ;-)

**Comment by shefty** [comment]
Proposal:

Add

int  (*datatype_size)(struct fid_ep *ep, enum fi_datatype datatype)

to struct fi_ops_atomic.  At best, this provides a minimal sanity check that the data type sizes are the same between a provider and the app.  I could not find any way to extract out the format of a floating point data type used by the compiler.

**Comment by sayantansur** [comment]
Can this be against a domain or fabric object? I'm wondering if it needs to be on the endpoint object.

**Comment by shefty** [comment]
It's probably per provider, which matches better with a domain.  The fi_ops_atomic, which are the best fit, are associated with an EP.

**Comment by sayantansur** [comment]
Hate to say it, but does this belong in getinfo()? Ultimately, the app wants a provider that matches its definition of the datatype.

**Comment by shefty** [comment]
That approach seems ugly as sin.  It's best aligned with the atomic valid() calls, with more explicit data type formats specified, and long double deprecated.

**Comment by sayantansur** [comment]
Yea, it is ugly :-) But I think adding this to the EP is also weird. This at best a per provider attribute.

Adding to per EP is expensive for connection oriented apps (not that they can scale as well as the unconnected ones).

**Comment by shefty** [comment]
The atomic valid calls are per EP.  IMO, it makes sense to mirror that functionality, as this is really just some sort of extension to the atomic valid calls.

**Comment by sayantansur** [comment]
Ok, yea this is probably the least weird place to put in after all. I'm on board.

**Comment by shefty** [comment]
A year later and this is still a mess.  :)  So... I think the immediate problem is limited only to LONG DOUBLE.  Both the size and alignment for long double are not standardized.  To top this off, I don't know how a provider figures out what definition it even has to work with.  I haven't been able to find out how this can be extracted from the compiler.

New call idea:
```c
int get_format_const(..., enum fi_datatype type, void *arg, size_t size);
```
This is used to retrieve a constant long double value that the app can use in a comparison against its version of the constant to see if the library agrees with its interpretation.  I hope this will catch all alignment and precision errors if we pick the correct constant.  An example use is:
```c
#define FI_LONG_DOUBLE_CONST 1.99999999999999999L
long double fivar, myvar = FI_LONG_DOUBLE_CONST;
ret = get_format_const(..., FI_LONG_DOUBLE, &fivar, sizeof(fivar));
if (ret || fivar != myvar)
    error
```
I'm not sure how feasible this would actually be.

**Comment by sayantansur** [comment]
I wonder if anything is necessary at all, given that this has yet to be shown as a real problem. It could very well be that only a vanishingly small number of superhero type programmers use long double.

Can we get away with a warning in the man pages like the GCC man page lists?

>        Warning: if you override the default value for your target ABI, this changes the size of structures and arrays containing "long double" variables, as well as modifying the function calling convention for functions taking "long double".  Hence they are not binary-compatible with code compiled without that switch.

**Comment by shefty** [comment]
Adding a warning is definitely an easy way out.  :)  I'm fine kicking the can down the road, since I can't fixing this requires adding new functions.

**Comment by jeffhammond** [comment]
Another path forward would be to use the external32 definition from MPI, which says that "long double" is 16 bytes, although that text also says it is big-endian, which I do not favor.

See MPI-3.1 Section 13.5.2 for details.

**Comment by shefty** [comment]
At some point this was added to the man pages for long double atomics:

```
  A double-extended precision floating point value (IEEE 754).
  Note that the size of a long double and number of bits used for
  precision is compiler, platform, and/or provider specific.
  Developers that use long double should ensure that libfabric is
  built using a long double format that is compatible with their
  application, and that format is supported by the provider.  The
  mechanism used for this validation is currently beyond the scope of
  the libfabric API.
```
which is as good as any solution that we have discussed.
