### ISSUE TITLE
Provide free pool abstraction

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1135]
There are a couple of places where providers maintain free pool of objects.  Provide a common abstraction for free pool use, to reduce duplicate code.

Please list anywhere free pools are used, so that they can be addressed.

PSM - event queue (psmx_eq.c)
sockets - RX progress entries (sock_rx_entry.c)

**Comment by goodell** [comment]
The current usnic provider implementation of `EP_RDM` and `EP_MSG` moves `usdf_rdm_qe`/`usdf_msg_qe` elements between free/posted queues (e.g., `rx_free_rqe`).  Not sure how closely this matches up with the sort of free pool you are envisioning.

**Comment by shefty** [comment]
Fixed by util_buf_pool
