### ISSUE TITLE
When are completion flags valid?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1142]
The CQ entries allow flags to convey the type of operation that completed.  The value of a provider setting these flags is unclear relative to their cost.  For example, in order to set the flags, a provider may need to run through a series of branches.

We need to understand which flags are important for an app.  For example, do apps only need to distinguish between transmits versus receives?  How do we handle providers that cannot supply all flags without tracking the original request?

**Comment by goodell** [comment]
Notes from today's concall:
- Open Question: Are all providers required to support all CQ completion formats?
- If not all CQ completion formats must be supported, how do we allow applications to find out at getinfo time that the CQ creation will fail if certain formats are requested?
- Sayantan and I noted the potential of adding overhead for tracking send tags if using offload tagged messaging hardware that doesn't report the send tag in a hardware-generated completion.

**Comment by shefty** [comment]
The fi_provider.7 man page indicates which CQ formats providers must support.  Though it seems fairly trivial for a provider to support all formats -- even if the fields are left unused.

Tag values are defined only for receive operations.

The reporting of completion flags is currently implied as mandatory by the man pages.  We still need to decide if this is an application requirement and its impact to providers.  E.g. a provider may not naturally report the operation as part of its completion semantics.  If apps can live without this, then we need some mechanism to disable completion flags partially or completely, with only a couple of exceptions, such as FI_MULTI_RECV.

**Comment by shefty** [comment]
See #1394 and #1399 -- those are not directly related, but deal with the CQ and may require a coordinated solution.

**Comment by shefty** [comment]
See #1255 for another CQ related issue

**Comment by shefty** [comment]
Proposal:

Define FI_NOTIFY_FLAGS_ONLY mode bit
When set on an EP, only the following flags are returned in completions:

- FI_REMOTE_READ | FI_RMA  (if FI_RMA_EVENT cap set)
- FI_REMOTE_WRITE | FI_RMA  (if FI_RMA_EVENT cap set)
- FI_REMOTE_CQ_DATA
- FI_MULTI_RECV

CQ attributes will be updated with caps and mode bits as part of an ABI bump.

**Comment by sayantansur** [comment]
Looks like a reasonable approach to me. Still need to think it through a bit.

**Comment by sayantansur** [comment]
Just clarifying, unless FI_RMA_EVENT is set, we don't have to set any flags at all, other than FI_REMOTE_CQ_DATA and FI_MULTI_RECV?

**Comment by shefty** [comment]
Yes, see https://github.com/ofiwg/libfabric/pull/2444/commits/a14a6876f58f1205b9f35b59671d95bd4a220d61

**Comment by sayantansur** [comment]
👍 I also want 🍟 with that!
