### ISSUE TITLE
More than 2 process to connect, how to setup connections

### ISSUE THREAD

**Issue by svalat** [ofiwg/libfabric#1173]
Hello,
I'm trying to use libfabric on top of PSM, and, based on the rdm_ping_pong from fabtest I'm not sure to understand the semantic to interconnect more than 2 processes with the RDM approach (I'm ok with the MSG one for sockets and verbs by using a passive endpoint).
      - Need I create an active endpoint for each targeted process ?
      - In this case how I differentiate the endpoint on the source side as we do not provide target ? (May I just wait connection to them and then check with which node it is connected)
      - Can we start more than one "listen" at a time on the source side with the RDM mode ?
      - Or just i need to use address vector do connect the endpoint to multiple target ?

In the same idea I'm asking myself, how to setup connections with more than one process per node. Usage of port/service seams inefficient with the rdm_ping_pong test (with PSM, not sockets) ? When I launched two of them (source) on the same host and another one (remote) on another, I cannot choose which process to join on the source node, it always connect to the last started one.

Suggestion : might be good to get a similar example in fabtest for example with a ring between three processes.

Thanks,
Sebastien Valat.

**Comment by shefty** [comment]
> - Need I create an active endpoint for each targeted process ?

RDM only uses active endpoints.  Each process should allocate at least 1 (typically only 1) active endpoint.

> - In this case how I differentiate the endpoint on the source side as we
> do not provide target ? (May I just wait connection to them and then check
> with which node it is connected)

RDM does not use the connection interfaces (i.e. connect, listen, accept).  You need to insert the address of each target process into an address vector before trying to send to it.  How you exchange the addresses of each process is an exercise left up to the programmer.  :)  Basically, think of RDM similar to using UDP sockets.

> Suggestion : might be good to get a similar example in fabtest for example
> with a ring between three processes.

Yes - we need a test that supports > 2 nodes.  It's simply a matter of time needed to develop that tests.  There are pending examples that make use of a resource manager for this, but are still undergoing development.

**Comment by svalat** [comment]
Hi,
thank you for the answer, it is more clear to me now, but in that case I don't understant the FI_SOURCE trick into rdm_ping_pong. Why shoult I use some endpoints as source and some other not ?

I try to initiate all of them (one for each process) without FI_SOURCE and setup AV to link all of them, but I get some errors on connextion from some nodes (typically on half of them. It seems to be those who does send as first step, recv node are waiting as expected). (I'm currently use this test with the socket provider).

**Comment by shefty** [comment]
FI_SOURCE indicates that the address being specified <node, service> refers to a local address.  Without FI_SOURCE, the address is assumed to be a remote address.  When a remote address is specified, the local routing tables are used to identify which specific source address should be used when communicating with the destination.

The use of FI_SOURCE really depends on how the app is using the endpoint.  If you have a client-server app, the server will often specify a source address to use, while the client will specify the server's address as the destination to talk to.  It doesn't matter if the client-server app communicates using unconnected or connected endpoints.  If the app is more of a peer-to-peer app, then the peers will often all use FI_SOURCE.

**Comment by svalat** [comment]
Ok I get it working like this, tank you.
