### ISSUE TITLE
Add support for AF_IB to verbs provider

### ISSUE THREAD

**Issue by vtolstov** [ofiwg/libfabric#1175]
fi_getinfo does not resolve addressed like rdma_getaddrinfo. Also I need to resolve node not only by ip address and hostname ,but also by guid.

**Comment by shefty** [comment]
Updated issue description to reflect work that needs to be done.  If you think this update is wrong, let me know.

**Comment by vtolstov** [comment]
@shefty no problem, this description fine.

**Comment by a-ilango** [comment]
PR #1185 fixes this issue.
