### ISSUE TITLE
Mac should not try to build True Scale provider by default

### ISSUE THREAD

**Issue by jeffhammond** [ofiwg/libfabric#1177]
If I configure with no variables set (`mkdir build && cd build && ../configure && make`), I get the following error on my Mac laptop:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       prov/truescale/src/psm/src_libfabric_la-psm_am.lo
In file included from ../prov/truescale/src/psm/psm_am.c:35:
In file included from ../prov/truescale/src/psm/psm_user.h:45:
In file included from ../prov/truescale/src/psm/include/ipath_user.h:61:
../prov/truescale/src/psm/include/ipath_common.h:44:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^
1 error generated.
make[1]: *** [prov/truescale/src/psm/src_libfabric_la-psm_am.lo] Error 1
make: *** [all] Error 2
```

If instead I do `../configure --disable-truescale`, the build is clean.  It seems that `asm/types.h` is not available on Mac.

In any case, I don't now that True Scale supports Mac anyways, so it seems silly to build this included provider.

Alternatively, please do a configure test for `asm/types.h` as part of determining whether or not to build the True Scale provider.

I have the full `config.log` that I can send out-of-band if necessary.  Github won't let me attach it here.

**Comment by shefty** [comment]
@jithinjosepkl @j-xiong - I thought that the upstream code built fine on MAC without needing to disable the PSM provider.  Is this not the case in general?

**Comment by jithinjosepkl** [comment]
Yes, thats the case. PSM provider gets disabled at configure time.

```
configure: *** Configuring psm provider
checking psm.h usability... no
checking psm.h presence... no
checking for psm.h... no
configure: psm provider: disabled
```

May be @jeffhammond's system has psm.h?
Or should we not even try to check for psm on OS-X?

**Comment by j-xiong** [comment]
Although the issue has been closed, I still want to ask: why the "truescale" provider exists in the first place? We have the "truescale" provider with embedded psm in an internal repo, but  the ofiwg libfabric tree only has the "psm" provider.
