### ISSUE TITLE
Avoid excessive explicit library dependencies

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#118]
Patrick made the observation (https://github.com/jsquyres/libfabric/commit/3774e3bc1c289706a27a4d737f5314e36ab66ece#commitcomment-7881669) that providers created as DSOs are linked against everything in $LIBS, which is a bit redundant.

Additionally, libfabric should not be forced to link against libraries that DSO providers require.

Jeff volunteered to take inspiration from OMPI configury to fix this problem.

Probably want to wait until #112 is merged in, and also after https://github.com/jsquyres/libfabric/commit/3774e3bc1c289706a27a4d737f5314e36ab66ece and https://github.com/jsquyres/libfabric/commit/64f0c680e243f27e29481e5c509812824618fa07 are rebased / merged in, too.

**Comment by shefty** [comment]
Is it okay to close this issue?

**Comment by pmmccorm** [comment]
I thought this was fixed.
