### ISSUE TITLE
Cleanup logging format

### ISSUE THREAD

**Issue by pmmccorm** [ofiwg/libfabric#1191]
Remove the logging of  `__LINE__` and maybe `__FUNCTION__` from most or all of the logging levels output format.

Looking at current log output:

```
$ FI_LOG_LEVEL=debug ~/local/bin/fi_info
libfabric:core:core:fi_param_define_():226<info> registered var provider
libfabric:core:core:fi_param_get_():275<info> variable provider=<not set>
libfabric:core:core:fi_param_define_():226<info> registered var provider_path
libfabric:core:core:fi_param_get_():275<info> variable provider_path=<not set>
libfabric:core:core:fi_ini_dir():319<debug> opening provider lib /home/pmmccorm/local/lib/libfabric/libverbs-fi.so
libfabric:core:core:fi_register_provider():125<info> registering provider: verbs (1.0)
```

The line numbers don't mean anything to customers or even developers, the function names are only meaningful to developers and should only be logged on the higher leg levels (ie warn). So right now they just add a lot of noise to the log output.

Line numbers should always accompany a file name. If we wanted to have these on the debugging level we could use a variant of gcc's well understood format:

```
libfabric:core:core:src/log.c:138:fi_getinfo_():<debug>  
```

Additionally the man pages should be updated to state that the output format of the logging is outside of the API and can change.

**Comment by j-xiong** [comment]
Could "core:core:" also be simplified to "core:"?

**Comment by shefty** [comment]
One 'core' represents the provider, which in this case is the libfabric core itself.  The other 'core' represents the subsystem, which is also the core (initialization or control operations).

**Comment by pmmccorm** [comment]
@j-xiong That same thought crossed my mind. I think it would be less redundant.

**Comment by sungeunchoi** [comment]
:+1: 

FYI, we added pid and a thread id to the logging message in the gni provider and found those very useful for debugging.  There's additional overhead (accessing tls), so it is controlled by NDEBUG.

**Comment by pmmccorm** [comment]
@sungeunchoi That does sound useful-- what format did you print out?

**Comment by sungeunchoi** [comment]
Since I didn't want to mess with the non-gni specific formatting, I added at the beginning of the formatted message in square brackets as [pid:tid], e.g.,:

    libfabric:gni:ep_ctrl:_gnix_vc_schedule():1177<info> [41454:3] Scheduled VC (0x6fcbe0)
    libfabric:gni:ep_ctrl:_gnix_nic_next_pending_vc():1208<info> [41454:3] Dequeued VC (0x6fcbe0)
    libfabric:gni:ep_data:_gnix_vc_push_tx_reqs():1331<info> [41454:1] TX request processed: 0x68d620
    libfabric:gni:cq:_gnix_cq_add_event():299<info> [41454:1] Added event: 4e3dda1a

It's not that pretty, but gets the job done.
