### ISSUE TITLE
tagged and non-tagged on one endpoint?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#1196]
Can an application create an endpoint that has both tagged and non-tagged API sets enabled?

Looks like it could be confusing for both app and provider in case the usage of both are intermingled. e.g. if app posts non-tagged recv A, and tagged recv B. Upon arrival of a message, which receive does it match?

I couldn't find any mention of this in the man pages. Although I would think this wasn't allowed by default.

Comments?

**Comment by shefty** [comment]
I don't see any reason why this should be restricted.  An incoming buffer would match whatever receive that corresponds with the send operation.  I.e. tagged receive matches tagged send.  Msg receive matches msg send.

If a provider cannot support this, they don't respond to apps that ask for both msg and tagged ops on the same EP.

**Comment by sayantansur** [comment]
OK, I guess I was confused that apps might want to post a tagged receive (possibly with all ignore bits) and expect a non-tagged message to match that? That sounds like a non-sensical use case.

I'm closing this.
