### ISSUE TITLE
Does it make sense to use FI_SELECTIVE_COMPLETION on receive when using EP_DGRAM?

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1197]
I can't think of a valid use case for selective receive completions on dgrams. Adding support for this in the `usnic` provider would add unnecessary overhead. Is this something that providers can just skip? If so, should it be documented in the man pages? 

@shefty

**Comment by shefty** [comment]
Couldn't the provider just have different code paths in use, and select the proper one dynamically?  Or just not support this capability?

That said, I can't think of a reason for selective completions on datagram EPs.  It doesn't seem useful.  We can bring this up in the ofiwg tomorrow and see if anyone can think of a valid use case.

**Comment by bturrubiates** [comment]
So we never spoke about this in the call. I don't think it makes much sense on dgram. If within the API, I think I'll just leave the current `usNIC` behavior of returning `-FI_ENOTSUPP` when attempting to bind with flags `(FI_RECV | FI_SELECTIVE_COMPLETION)`.

**Comment by shefty** [comment]
I think that's fine.  We can either document this restriction or just wait until some app wants to do it.  Then we'll know it's important -- maybe...

**Comment by shefty** [comment]
Closing this.  I think the current usnic behavior is acceptable.  I can have the UDP provider match this.
