### ISSUE TITLE
Empty queues still need locking

### ISSUE THREAD

**Issue by fweimer** [ofiwg/libfabric#1206]
Commit 969591cd58b36bd639cfe60820cbd8a0ef2c9320 is incorrect. You absolutely have to synchronize on empty lists as well, otherwise you have a data race and the behavior is undefined according to the C11 memory model.

**Comment by goodell** [comment]
I agree here.  @j-xiong?

**Comment by j-xiong** [comment]
I don't think there is issue here. If the list is being updated to be no-empty while the check returns empty, the list will be processed next time the function is called. If the list is being updated to be empty while the check returns non-empty, the list empty test is performed again inside the synchronized section so the correctness is not affected.

**Comment by fweimer** [comment]
@j-xiong, you still need to use atomics (relaxed should be fine) to load and store the list pointers, otherwise it's undefined behavior and will interfere with testing with tools such as Thread Sanitizer and Helgrind.

**Comment by j-xiong** [comment]
My point is that this specific unguarded list-empty check works fine even if the value of the loaded pointer is undefined. I agree testing tools may not be advanced enough to identify this as non-issue.

**Comment by goodell** [comment]
@j-xiong, I think @fweimer's point (and definitely my point) is that this constitutes **undefined behavior** from the C standard's perspective, which doesn't mean "uncertain but always reasonable", it means "all bets are off and the compiler can generate nonsense code".  For example, if you've ever violated C's strict aliasing rules, turned on optimization, and omitted `-fno-strict-aliasing` from your compile line, you might have run into one of these bugs that seems like the computer is doing something impossible.  Writing racy code (from the C standard's perspective) is almost always a bad idea, even if it seems to be working at the moment under current limited testing.

**Comment by j-xiong** [comment]
Point taken. I will revert this commit first and try to find other ways to achieve similar goal.
