### ISSUE TITLE
prov/sockets/src/sock_av.c:sock_av_open() does not release resources on error path

### ISSUE THREAD

**Issue by fweimer** [ofiwg/libfabric#1208]
Code excerpt from `sock_av_open()`:

		_av->shared_fd = shm_open(_av->name, flags, S_IRUSR | S_IWUSR);
		…
		if (ftruncate(_av->shared_fd, table_sz) == -1) {
		…
		}
		
		_av->table_hdr = mmap(NULL, table_sz, PROT_READ | PROT_WRITE, 
				      MAP_SHARED, _av->shared_fd, 0);
		if (attr->flags & FI_READ) {
			if (_av->table_hdr->size != _av->attr.count) {
				ret = -FI_EINVAL;
				goto err;
			}
		} else {
			_av->table_hdr->size = _av->attr.count;
			_av->table_hdr->stored = 0;
		}

		if (_av->table_hdr == MAP_FAILED) {
			SOCK_LOG_ERROR("mmap failed\n");
			shm_unlink(_av->name);
			ret = -FI_EINVAL;
			goto err;
    …
    err:
	free(_av);
	return ret;

`_av->name` and `_av->fd` are not released (and potentially other struct fields).

**Comment by shantonu** [comment]
Thanks for catching the problem! Please review if the changes look alright.
