### ISSUE TITLE
FI_MORE retraction / flushing

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#1218]
It occurred to me recently there may be cases where FI_MORE is being used in a send loop, and then circumstances change such that there actually is no more to send.  A provider that is using FI_MORE for optimization may then be in a situation where the "flush" action of send-without-FI_MORE is needed to actually initiate a transfer, but there is no way to initiate this flush without sending a new packet, and there may be nothing to send.  

Three approaches I can see for this:
- programmer error - only use FI_MORE if you know for certain a non-FI_MORE will follow
- implicit flush via fi_send (or receive or ...) with specific params (0 len, special len, null buffer ...)
- new explicit flush API call, new flag e.g. FI_NO_MORE_NO_MORE_NO_MORE_HIT_THE_ROAD_JACK

**Comment by sayantansur** [comment]
I would vote for the implicit behavior, although that would imply some sort of checking of state in the case where there are no flags. Could make implementation a little trickier.

**Comment by shefty** [comment]
The simplest case is that the app must provide one call that doesn't use FI_MORE.  Though I can see how that would cause minor difficulties for the app.  In any case, this must always work and be a viable solution.

I don't like the idea of overriding the APIs to have special meaning based on the flags used with some previous call.  FI_MORE allows chaining together different calls (send, RMA write, atomic, etc.) which makes an implicit model non-intuitive to use and difficult to implement.  A dedicated call for this seems a better option.

A dedicate 'end of transfers' call could be paired with a 'start of transfer' call, which would imply the FI_MORE flag.

**Comment by rfaucett** [comment]
The Hippocratic performance oath applies here - we should not do anything to impact regular critical path.  This makes a separate call attractive to me, but given that FI_MORE is intended purely as a performance boost, I'm not sure I like adding an additional call (start_of_transfer) as a requirement to get the benefit.  

Though... the more I think about it, the more I like doing away with FI_MORE entirely and moving to Sean's start/end_transfer_block calls.  For a provider that does not do FI_MORE, these would just be no-ops, and they allow a cleaner interface for the user to delineate transfer blocks, allowing the FI_MORE-style optimizations to be done by the provider.  This model does better than "solving" the problem I brought up, it defines it away...

**Comment by shefty** [comment]
Proposal (based on discussion):

Add
int (*start_transfers)(struct fid_ep *ep);
int (*end_transfers)(struct fid_ep *ep);
to fi_ops_ep

This does not require an ABI bump and can be added when convenient.

**Comment by bturrubiates** [comment]
> Add
> int (start_transfers)(struct fid_ep *ep);
> int (end_transfers)(struct fid_ep *ep);
> to fi_ops_ep

Is this intended to be used solely when multiple messages are being posted? e.g.

```
start_transfers()
for transfer in transfers:
    fi_send()
end_transfers()
```

And all queued up transfers would take effect?

**Comment by shefty** [comment]
Yes, but it is only a hint to the provider, which would allow it to optimize access to hardware.

**Comment by hppritcha** [comment]
This is an excellent idea.  The gni provider could definitely make use of it.
@sungeunchoi

**Comment by shefty** [comment]
I spent some time considering this in more detail.  There are a couple of concerns. First, having return values for start_transfers and end_transfers doesn't seem particularly useful.  For example, if end_transfers fails, what exactly is an application supposed to do?  What does the failure indicate?  This can be 'fixed' by converting both to void functions.

A bigger concern is that either start/end are no-ops or their use would add checks into all fast path calls.  From the viewpoint of the provider, it does not know if, for example, send() will be called by itself or surrounded by start/end calls. The result is that send() must be written to call start/end internally if start has not been called by the app.

I think we need more input on how apps could use such a feature, along with a prototype of how a provider could implement it.  I'm leaving this issue open, but removing it from trying to target the ABI update release.

**Comment by sungeunchoi** [comment]
The UGNI library's *chained transactions* map well to FI_MORE, so we met with Cray's Programming Environments developers about their current use of chained transaction.  We also asked them to review the current FI_MORE definition and the proposals in this issue.  For their current uses of chained transactions, the last chained message can always be identified.  So while they didn't have any issues with the proposed API changes above, an API change isn't necessary for their current uses.

**Comment by shefty** [comment]
No movement to change anything in the API has been made for 4 years.
