### ISSUE TITLE
Missing error report with bad IOV address for socket

### ISSUE THREAD

**Issue by svalat** [ofiwg/libfabric#1225]
Hi,
I'm currently testing my code with the socket layer for RMA I get a strange thing which took me 2 days to debug. I missed the (mr_mode == FI_MR_SCALABLE) while starting from the msg_rma.c example from fabtest. So I provide the bad remote address to fi_writedata function.

The issue is that I don't get an error, the message is just lost staying in infinite loop on the two side, waiting on send/recv queues. I only find my mistake by using environment variable  `FI_LOG_LEVEL=Debug`. Thank to this I get the error in logs. 

On emitter side (see first two line warnings) : 
```
libfabric:sockets:domain:sock_mr_verify_key():273<warn> MR check failed
libfabric:sockets:ep_data:sock_pe_process_rx_write():728<warn> Remote memory access error: 0x76eec0, 128, 1
libfabric:sockets:ep_data:sock_pe_progress_pending_ack():404<debug> Connection 0x76f600 grabbed by 0x7ffff7ff8330
libfabric:sockets:ep_data:sock_comm_send():132<debug> buffered 40
libfabric:sockets:ep_data:sock_pe_discard_field():128<debug> Remaining for 0x7ffff7ff8330: 128
libfabric:sockets:ep_data:sock_pe_discard_field():130<debug> Discarded 128
libfabric:sockets:ep_data:sock_pe_discard_field():134<debug> Discard complete for 0x7ffff7ff8330
libfabric:sockets:ep_data:sock_comm_send_socket():73<debug> wrote to network: 40
libfabric:sockets:ep_data:sock_pe_release_entry():170<debug> progress entry 0x7ffff7ff8330 released
libfabric:sockets:ep_data:sock_pe_progress_rx_pe_entry():2018<debug> [0x7ffff7ff8330] RX done
```

On waiting side : 
```
libfabric:sockets:ep_data:sock_pe_handle_error():528<debug> Received error for PE entry 0x7ffff7ff8330 (index: 127)
```

The mistake is on my side but I think the error must have been reported to me on the emitter side (at least) ? Am I wrong ?

**Comment by jithinjosepkl** [comment]
The initiator side is notified in MR check failures.  The error entry is written to the CQ (bound with a FI_WRITE flag). So if the application reads the CQ, then it should get the error.

Also, if you run with FI_LOG_LEVEL=warn, you should get only the warnings.

**Comment by jithinjosepkl** [comment]
But, it will not hurt to have an additional warning message at the initiator side. I can put this in.

**Comment by svalat** [comment]
Hum, should be good.
Maybe I made a mistake but I don't get an error reported on the CQ that is the point I want to tell. My code was looping on it trying to read entries without getting anything I just get -FI_EAGAIN for any checks. I was expecting to get the error reported.

Extract of my waiting code if I made a mistake : 
```c
                       //get cq entry
			ret = fi_cq_read(queues[i], &comp, 1);
			
			//if get one
			if (ret > 0) {
				context = getContext(comp);
				break;
			} else if (ret < 0 && ret != -FI_EAGAIN) {
                               //===> I never get here but i suppose it must at some point
				if (ret == -FI_EAVAIL) {
					LIBFABRIC_CQ_FATAL_ERROR("fi_cq_read",queues[i]);
				} else {
					LIBFABRIC_CHECK_STATUS("fi_cq_read", ret);
				}
			}
```

**Comment by svalat** [comment]
You can reproduce quicly with fabtest streaming/msg_rma, just replace == by != on the line checking FI_MR_SCALABLE. You will see, the code is blocking without reporting any error on the CQ.

**Comment by jithinjosepkl** [comment]
I see the issue. In the provider code, I report this error up only if the endpoint is bound with FI_WRITE. It should work for FI_SEND (or FI_TRANSMIT) as well. I will get this fixed. 

Thanks for checking this. :+1: 

Binding the CQ using FI_SEND|FI_WRITE should give you the error report for now (just temporarily, in case you need to check).
