### ISSUE TITLE
sock_av_insertsym string processing hardening

### ISSUE THREAD

**Issue by fweimer** [ofiwg/libfabric#1226]
With the fix in #1221, it is clear that the `sprintf` calls discussed in #1209 are not actually dead code. `sock_av_insertsym` should make sure that the buffers for `sprintf` are large enough and that nothing bad happens if the input strings are empty. It looks like the loop at https://github.com/ofiwg/libfabric/blob/dcae2b32cf6f6268698629cd7e05c7851555555a/prov/sockets/src/sock_av.c#L382 could access characters before the start of `node` if `node` points to an empty string.

**Comment by jithinjosepkl** [comment]
Thanks, good point. Will get this updated.
