### ISSUE TITLE
prov/verbs: fi_ibv_getinfo should not return error other than -FI_ENODATA

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#1235]
In the function fi_ibv_getinfo(), lower level errors are returned directly to the caller, causing the user process to terminate. This function should only return 0 for success or -FI_ENODATA on error to allow other providers to be discovered.

**Comment by a-ilango** [comment]
I'll take a look at this.

**Comment by a-ilango** [comment]
It makes sense to return -FI_ENODATA when there is a provider failure. I need some clarification though.
@shefty, fi_getinfo man page says the following:
>RETURN VALUE
>
>fi_getinfo() returns 0 on success. On error, fi_getinfo() returns a negative value corresponding to fabric errno. Fabric errno values are defined in rdma/fi_errno.h.

Also, the following errors are mentioned in the page:
>ERRORS
>
>FI_EBADFLAGS
>The specified endpoint or domain capability or operation flags are invalid.
>FI_ENOMEM
>Indicates that there was insufficient memory to complete the operation.
>FI_ENODATA
>Indicates that no providers could be found which support the requested fabric information.

Does it mean fi_getinfo can return only any of the above 3 errors?

**Comment by shefty** [comment]
Ideally, there would be an exhaustive list of possible failure codes.  I would not assume that the list is complete, but new codes should be listed if they can be returned.  Please be sure that any errors that are discarded also result in a log message.

**Comment by a-ilango** [comment]
@j-xiong I think the provider should return any fatal errors like FI_ENOMEM. For all other errors, FI_ENODATA can be returned along with a log message. That works?

**Comment by j-xiong** [comment]
That sounds reasonable, other providers would probably not work either with errors like FI_ENOMEM.  However, I would not consider FI_EBADFLAGS as fatal error -- different providers may accept different set of flags -- unless this error means the flags are completely garbage that not acceptable to any provider.

**Comment by shefty** [comment]
I agree.  Only the framework itself should return something like FI_EBADFLAGS.

**Comment by a-ilango** [comment]
Sounds good. I'll send a patch soon.
