### ISSUE TITLE
buffered_recv_size?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#1240]
We have defined a rx_attr field called total_buffered_recv. This defines the total amount of buffering a provider is required to provide for the endpoint.

Do we need another field called buffered_recv_size (or similar) that indicates the maximum size of a single message that can be buffered? Otherwise it is unclear if a single message of size total_buffered_recv can occupy the entire buffer.

Typically, MPI libraries define a cross product of eager sized messages that can be buffered and the total number of buffered messages.

**Comment by shefty** [comment]
Proposal:

Add new field to fi_rx_attr as suggested.  This would be part of an ABI bump.

**Comment by goodell** [comment]
:+1:

**Comment by sayantansur** [comment]
:+1:

**Comment by bturrubiates** [comment]
:+1:

**Comment by shefty** [comment]
If we add a new field to fi_rx_attr -- max_buffered_msg -- how will this be used by the apps?  Will an app assume that messages larger than this will not be buffered?  If so, will they implement their own rendezvous protocol for transfers larger than this?  Is that the intent here?

Are we looking at 2 maximums here: max size of all buffers + max number of messages buffered?  With the actual limit based on whichever is hit first?  I'm not sure how to expose this without requiring a specific implementation.

**Comment by sayantansur** [comment]
You're right. We need to inspect the need for this a little closer. Under the current definition of total_buffered_recv, the provider can internally perform rendezvous-based communication.

When I filed this, I was concerned about whether the application can assume that one large message is buffered. However, the concern is mitigated by the fact that applications can never really observe the internal buffer, other than by posting a receive.

Maybe we don't need this at all?

**Comment by shefty** [comment]
I understood the intent, but I'm having trouble coming up with a 'fix' that hits me as an actual improvement.  Even if we re-work all of the attributes as part of an ABI change, I'm not sure that anything I'm coming up with is obviously better.

**Comment by sayantansur** [comment]
Another thing to consider is that whether we should remove this altogether in favor of the application asking for FI_RM_ENABLED? What do we gain by having the application specify the exact amount of buffering it needs? Presumably, it can post the receives if it knows the buffering it needs ;-)

**Comment by shefty** [comment]
I could totally get on board a change that simplifies the API for the user.
