### ISSUE TITLE
`fi_cq_attr` cannot be queried?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#1255]
It looks like there's no way to interrogate libfabric to find the provider's recommended values for `fi_cq_attr`.  For example, there's no good way to ask what the max/default number of CQ entries is (the `fi_cq_attr::size` field).  I sort of expected there to be an `fi_cq_attr` structure linked to from an `fi_info` structure returned by `fi_getinfo`, but I can't seem to find such a connection.

@shefty Am I missing something obvious here?

**Comment by goodell** [comment]
A weak solution to this would be to allow apps to create CQs and then query the resulting attributes.  A stronger one would be to update the `fi_info` structure to somehow incorporate a pointer to an `fi_cq_attr` structure.

**Comment by goodell** [comment]
@bturrubiates points out out-of-band that a similar issue potentially exists for `fi_eq_attr`, `fi_poll_attr`, `fi_wait_attr`, and `fi_cntr_attr`, though probably not all of those attribute structure types have fields that are reasonable to query.

**Comment by shefty** [comment]
It's not that easy to provide EQ/CQ/etc. attributes with fi_info.  fi_info corresponds to a the attributes of a single endpoint.  EQs/CQs/etc. are intended to be shared among endpoints.  I'm guessing that the only real attribute of interest is the CQ size value.  A value of 0 may be used to allow the provider to select an optimum value.

You're correct that there's no way to know the maximum size that a CQ may have.  (This also isn't possible for other resources, included EPs.)  Personally, I'd like to avoid that if possible.  Sizes may be increased by using software mechanisms, and dumb apps written in Texas that think 'bigger is better' will just waste resources.

I need to think about this one more.  An app may need to know not just the size of a CQ, but the number of EPs that can be attached.  I think an app can safely assume that the CQ size >= EP size.

**Comment by shefty** [comment]
Proposal:

Add fi_cq_attr to fi_info.  New caps and mode bit fields will be added to fi_cq_attr that will make this necessary.

I don't think wait, poll, or eq attributes need to be part of fi_info.  There hasn't been a request to modify fi_cntr_attr, but it may make sense to mirror the new cq_attr fields in cntr_attr.  I need to look into that more.

**Comment by goodell** [comment]
> Proposal:
> 
> Add fi_cq_attr to fi_info. New caps and mode bit fields will be added to fi_cq_attr that will make this necessary.

Works for me.

**Comment by bturrubiates** [comment]
> Add fi_cq_attr to fi_info. New caps and mode bit fields will be added to fi_cq_attr that will make this necessary.
> 
> I don't think wait, poll, or eq attributes need to be part of fi_info. There hasn't been a request to modify fi_cntr_attr, but it may make sense to mirror the new cq_attr fields in cntr_attr. I need to look into that more.

:+1:

**Comment by shefty** [comment]
I've started looking at how to implement this.  My proposal of adding fi_cq_attr to fi_info has issues, in part because Rx and Tx contexts could go to separate CQs, requests may be configured to not generate completions, counters may be used instead, etc.

Is there a real application requirement driving this request?

**Comment by shefty** [comment]
After 4 years, it's safe to say there's not a strong app requirement for this.
