### ISSUE TITLE
fi_domain_attr has a struct fid_domain embedded

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1261]
In working through how to map the libfabric "classes"/structures to java classes @nrgraham23
noticed that the ```struct fi_domain_attr```  has an embedded ```struct fid_domain```.

The same also applies to the ```struct fi_fabric_attr```.

Is there a reason for this?

From a java perspective this is particularly confusing as it seems to imply that an instance of class
```FiDomainAttr``` has an embedded ```FiDomain``` object associated with it.

@shefty

**Comment by goodell** [comment]
IIRC, the intent is that you can set the `fi_domain_attr::domain` field to point to an existing domain when calling `fi_getinfo` to request info be returned only for a particular domain.

Yeah... looking at fi_domain(3) I see this:
```
   domain
       On input to fi_getinfo, a  user  may  set  this  to  an  opened  domain
       instance  to  restrict  output  to  the  given  domain.  On output from
       fi_getinfo, if no domain was specified, but  the  user  has  an  opened
       instance  of  the  named  domain,  this will reference the first opened
       instance.  If no instance has been opened, this field will be NULL.
```

**Comment by hppritcha** [comment]
thanks, forgot about that.  Closing this issue.
