### ISSUE TITLE
/usr/include/rdma is shared with kernel-headers

### ISSUE THREAD

**Issue by opoplawski** [ofiwg/libfabric#1277]
The Fedora kernel package also installs files into /usr/include/rdma:
~~~~~
$ rpm -ql kernel-headers | grep rdma
/usr/include/rdma
/usr/include/rdma/ib_user_cm.h
/usr/include/rdma/ib_user_mad.h
/usr/include/rdma/ib_user_sa.h
/usr/include/rdma/ib_user_verbs.h
/usr/include/rdma/rdma_netlink.h
/usr/include/rdma/rdma_user_cm.h
~~~~~
Are you aware of this?  Is this intentionally the same location?  It's not a big deal but we tend to like only one package to own a directory.  I just want to make sure that both projects are aware of this so at to not conflict in the future by having the same filename in the directory.

**Comment by shefty** [comment]
include/rdma was selected as the target install directory for header files at the request of the RedHat RDMA maintainer (versus include/fabric e.g.).  It aligns with the install directory for libibverbs, librdmacm, libibumad, libibmad, etc.

**Comment by opoplawski** [comment]
Great, thanks for the info.
