### ISSUE TITLE
Issues with running fi_ubertest on psm provider

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#1279]
I'm facing some issues with running fi_ubertest on the psm provider. I have made some updates (such as adding FI_CONTEXT, etc.) to the test to enable it to run on psm. The changes are available at https://github.com/a-ilango/fabtests/tree/ubertest_psm.

Issue 1:
There is a significant amount of time spent in the function psmx_domain_close after each "sub-test" in fi_ubertest. This makes the entire test take more time to complete.

Issue 2:
I believe PSM provider uses an out of band communication for name resolution. (psmx_name_server, psmx_resolve_name). The way fi_ubertest is structured, the client calls fi_getinfo before the server opens its fabric. Since psmx_name_server is called in fi_fabric on the server side, I saw the following error on the client side:
`libfabric:psm:core:psmx_resolve_name():200<info> couldn't connect to f012-ib0:64331`

I fixed this by making the client wait till the server opens its fabric(https://github.com/a-ilango/fabtests/commit/b1822a479e812d04c8f913a448d6e808f8cb7dca). But I'm not sure if this has to be fixed in the test or the provider.

Issue 3:
I also see the following logs at the start of second "sub-test" onwards:
`libfabric:psm:core:psmx_name_server():133<info> couldn't listen to port 64331. try set FI_PSM_UUID to a different value?`
Do I need to set FI_PSM_UUID to a different value after each "sub-test" as the log suggests? fi_ubertest does close the EP and fabric after each-subtest. I'm assuming the name server is shutdown when the fabric closes.

@j-xiong , @shefty

**Comment by j-xiong** [comment]
1) there is 1 second delay when closing the domain.  This is to work around a PSM bug. You can set FI_PSM_DELAY (or FI_PSM2_DELAY for psm2 provider) to 0 to eliminate the delay. 

2) I would say it's much easier to do that in the test. The main purpose of the name server is to support fabtest. We can't let the client wait for the server to come up for applications that doesn't rely on the name server at all.

3) Does all the sub-tests run within the same process?  If that's the case I do see issue here since the name server thread is not destroyed with the fabric object.  Let me come up with a fix for that.

**Comment by shefty** [comment]
To use FI_CONTEXT properly, you need an fi_context structure for every call that may be outstanding.  You can't reuse the same fi_context until the operation associated with the old one completes.  The other fabtests have this same issue, which I'm working to address.  FI_CONTEXT basically requires some sort of fi_context queue/circular array for anything other than a very basic pingpong test that doesn't post more than one receive at a time.

**Comment by shefty** [comment]
For issue 2, I agree that the test needs to be updated somehow.  Ideally, the ubertest should not require name resolution (outside of what it uses for sockets communication).  So, rather than having the client wait for the server to open the fabric, let's work to avoid it needing the provider name server feature.

**Comment by a-ilango** [comment]
>1) there is 1 second delay when closing the domain. This is to work around a PSM bug. You can set FI_PSM_DELAY (or FI_PSM2_DELAY for psm2 provider) to 0 to eliminate the delay.

I tried this but I still see significant delay (> 1 second). The following are the times taken to run the test in both cases:
With FI_PSM_DELAY=0
```real 6.18
user 5.95
sys 0.11```
Without setting FI_PSM_DELAY:
```real 8.17
user 4.94
sys 0.12```

This are the times I get for running the same test with sockets provider:
```real 0.15
user 0.03
sys 0.03```

Time measurements where done using the "time -p" command.

>3) Does all the sub-tests run within the same process? If that's the case I do see issue here since the name server thread is not destroyed with the fabric object. Let me come up with a fix for that.

Yes, they run within the same process.
>To use FI_CONTEXT properly, you need an fi_context structure for every call that may be outstanding. 

If you are already working on this for other fabtests, may be that code can be shared to use it in fi_ubertest.
>So, rather than having the client wait for the server to open the fabric, let's work to avoid it needing the provider name server feature.

Yeah, the ubertest already uses sockets for exchanging names. So when running it on psm provider, we can disable the name resolution by setting FI_PSM_NAME_SERVER to 0.

**Comment by j-xiong** [comment]
> I tried this but I still see significant delay (> 1 second).
It could be that psm_ep_close just takes that long for this specific test

> Yeah, the ubertest already uses sockets for exchanging names. So when running it on psm provider, we can disable the name resolution by setting FI_PSM_NAME_SERVER to 0.
Or you can just ignore the log message if the name server is not used.

**Comment by shefty** [comment]
Maybe we can add a 'configure_provider' call that both the client and server can invoke prior to running, where we can specify these provider specific settings.

**Comment by a-ilango** [comment]
> It could be that psm_ep_close just takes that long for this specific test

Any ideas as to why? I just found out this problem is present in other tests too. Using FI_PSM_DELAY=0 on both server and client:
```
[arun@f013 stage]$ FI_PSM_DELAY=0 time -p simple/fi_rdm -f psm f012-ib0
Sending message...
Send completion received
real 1.13
user 1.00
sys 0.02
```
compared to sockets:
```
[arun@f013 stage]$ time -p simple/fi_rdm -f sockets f012
Sending message...
Send completion received
real 0.11
user 0.00
sys 0.00
```

> Or you can just ignore the log message if the name server is not used.

Agreed. If the name server isn't too much of a overhead, we can ignore the logs.

**Comment by j-xiong** [comment]
> Any ideas as to why? I just found out this problem is present in other tests too.

That's just how psm works. The "graceful" closing protocol for psm endpoints can take a lot of time. Currently the timeout for this period is set to 120 seconds. I think I can add a parameter for this setting and if it is 0 it will go directly to the "abrupt" closing procedure, which should complete rather quickly.

**Comment by a-ilango** [comment]
Thanks. That would be very useful.

**Comment by shefty** [comment]
Are we okay to close this?

**Comment by j-xiong** [comment]
I thinks so. Also there is the new parameter FI_PSM_TIMEOUT / FI_PSM2_TIMEOUT for controlling the "timeout" of graceful endpoint closing.

**Comment by a-ilango** [comment]
@j-xiong Thanks, I'll run fi_ubertest against latest libfabric and report back.

**Comment by a-ilango** [comment]
@j-xiong I'm still seeing a delay. Can you please check?

```
[arun@f013 ~]$ FI_LOG_LEVEL=info FI_PSM_DELAY=0 FI_PSM_TIMEOUT=0 time -p fi_rdm -f psm f012
...
libfabric:psm:core:fi_param_get_():290<info> read int var delay=0
libfabric:psm:core:fi_param_get_():290<info> read int var timeout=0
...
Sending message...
Send completion received
real 1.13
user 1.00
sys 0.03
```

**Comment by j-xiong** [comment]
See PR #1409

**Comment by j-xiong** [comment]
No really making difference for this specific test case (fi_rdm).

With the latest changes, setting FI_PSM_TIMEOUT=0 can successfully skip the "graceful" ep closing step. In general the "forced" closing is faster than the "graceful" closing, and some times can be much faster. Unfortunately the time to finish a "forced" closing is still in the range of seconds.

We have to live with the 1+ second delay observed here. But hopefully it's less likely to get into higher range.
