### ISSUE TITLE
FI_TAGGED on verbs provider

### ISSUE THREAD

**Issue by danghvu** [ofiwg/libfabric#1280]
What is FI_TAGGED and any plan to support it on verbs provider ?
Apparently, the MPICH3 requires this to use "verbs" on infiniband device (nemesis/netmod/ofi)

**Comment by shefty** [comment]
FI_TAGGED indicates support for the tagged interface calls.  See fi_tagged.h.  And, yes, there are plans to support it with the verbs provider, likely in the 1.2 release, which is slated for Q4 of this year.

**Comment by danghvu** [comment]
I found that the verbs provider is now having `FI_TAGGED`, is it recommended ? The queue implementation for tagging interface seems to be not thread-safe isn't it although `FI_THREAD_SAFE` is specified in the threading model ?

**Comment by shefty** [comment]
No - the tagged support in the verbs provider is not recommended at this time.  It is experimental and still under active development.

**Comment by shefty** [comment]
tagged interfaces over verbs RDM EPs should work
