### ISSUE TITLE
what to do with the fi_addr_t returned by fi_cq_readfrom()?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#1283]
Some internal discussion at Cisco led to the question: what is the lifecycle for the `fi_addr_t *src_addr` (output) parameter to `fi_cq_readfrom`/`fi_cq_sreadfrom`?  How long is `*src_addr` valid?  Only as long as the corresponding AV is bound to the endpoint that generated this completion?  Is the caller of `fi_cq_readfrom` also obligated to call `fi_av_remove` after it's done using `*src_addr`?

I ask because the usnic provider's current `EP_DGRAM` implementation of `fi_cq_readfrom` essentially calls `fi_av_insert` under the hood to create the `fi_addr_t` that is returned, which to me indicates that `fi_av_remove` should be called by the application.  But the usnic provider isn't necessarily doing the right thing (we've been inadvertently noncompliant/naughty in the past).

cc: @bturrubiates, @shefty

**Comment by shefty** [comment]
I would expect that the lifetime is controlled by the application, with it calling fi_av_remove() when it is no longer needed.

**Comment by goodell** [comment]
OK, I think we can live with that.  It's a little slower than I would like, but it's a rational choice.
