### ISSUE TITLE
FI_RMA_EVENT and FI_REMOTE_WRITE

### ISSUE THREAD

**Issue by disprosium8** [ofiwg/libfabric#1300]
Do any of the providers implement this?  I didn't see any examples in fabtest and I can't get my CQs to generate REMOTE_WRITE events.  Perhaps I'm missing something.

My current checklist:
1) FI_RMA_EVENT cap is set
2) "local" CQ is set with FI_SEND | FI_WRITE | FI_TRANSMIT, works great
3) "remote" CQ is set with FI_RECV | FI_REMOTE_WRITE, never get CQ event for corresponding fi_writes
4) CQs are bound before enabling EP.
5) Memory regions are registered with FI_WRITE | FI_READ | FI_REMOTE_WRITE | FI_REMOTE_READ
6) Testing with psm and sockets providers with same behavior.

The target memory is being written to, I can poll on it.  It's just that the destination buffer is rarely written in order so I need some remote completion notification to know when to proceed.  Any ideas?

**Comment by disprosium8** [comment]
btw, is there a user list where these questions would be more appropriate to ask?  I see the ofiwg mailing list but that doesn't seem like the right target either.

**Comment by shefty** [comment]
The ofiwg mailing list works fine for questions like this.

**Comment by jithinjosepkl** [comment]
rdm_rma_simple example in fabtests use FI_RMA_EVENT and FI_REMOTE_WRITE, which works with psm and sockets. Can you check if there is something different here?

**Comment by shefty** [comment]
The fabtest uses a counter.  The issue is asking about using a CQ.

**Comment by jithinjosepkl** [comment]
Ah, yes. Just checked it.

**Comment by j-xiong** [comment]
The PSM provider would generate a CQ entry if the write comes with immediate data. I can't find the basis in the current man page, but I believe when that part was implemented it was defined that way.

**Comment by shefty** [comment]
That implementation is consistent with IB.

**Comment by shefty** [comment]
The man pages are unclear on this behavior.  See fi_ep_bind:

FI_REMOTE_WRITE
    Increments the specified counter whenever a successful RMA write or atomic operation is initiated from a remote endpoint that targets the given endpoint. Use of this flag requires that the endpoint be created using FI_RMA_EVENT.

This suggests that FI_RMA_EVENT only works for counters, and not CQs.  But the fi_getinfo page says that it should work for both.

**Comment by shefty** [comment]
After huddling and checking the providers, the intent was to restrict FI_RMA_EVENT to updating counters only.  This matches the existing provider implementations.  (Write with CQ data is handled separately.)  The reference to the CQ in fi_getinfo is from an older definition, where CQ events were also handled.  However, apps were only requesting updates to counters, and CQ support results in a more significant performance hit on some providers.  So, for the initial release we wanted to only define this use case for counters, knowing that it wouldn't be difficult to extend the API.

For your app, you can either use RMA write with CQ data, use a counter instead, or follow the RMA write by a send.  Obviously, this feature was intended to avoid the write with send scenario.  Do these options work for your app?

**Comment by disprosium8** [comment]
Yes, I'll end up needing the CQ data anyway, so that's perfect.  I was just confused about the current RMA event usage so thanks for the quick clarification.  Will try fi_writedata() soon and hopefully all will be clear.

On a semi-related note, are there any plans to include a uGNI provider?  There a CQ can be associated with a registered memory segment and RMA completions generated irrespective of immediate data. I imagine the current FI_RMA_EVENT feature could be extended there. I also noticed that the fabric interface to the MR keys is bound by a uint64_t, whereas a uGNI MDH is two 64b values.  Just a thought.

**Comment by shefty** [comment]
There is development work ongoing for a uGNI provider.  (At least there's an active libfabric fork for it.)  I do not know the details of when it may be ready, or how they plan on handling the MR key issue.  But I'm not familiar with the uGNI interface.

**Comment by disprosium8** [comment]
I'll have to look for that.  Has there been any interaction with the openucx.org efforts, which apparently claims to subsume libfabric?  I have no experience with their interface yet, however.  I am certainly appreciating libfabric, especially since I can now avoid having to write ipath/psm and more sockets code. I arrived too early to miss the ibverbs and ugni trap though.  Anyway, sorry to clutter this issue, will move any further discussion to the list.

**Comment by shefty** [comment]
We are aware of UCX.  However, UCX was developed between an exclusive set of developers, using a closed source development process.

**Comment by hppritcha** [comment]
UCX is on github and available for download.  to contribute one has to complete a contributors agreement much like open mpi.  As long as you org. doesnt have difficult to work with lawyers thar should not pose a problem.

**Comment by shefty** [comment]
It is available _now_, but was completely developed in a close source environment.  Open dump != open source.  There was no attempt to engage the community or encourage broad participation.  The participants were well aware of the libfabric effort, participated in libfabric, and still decided to create an alternative.

**Comment by disprosium8** [comment]
FWIW, I found the UCX presentation to be rather dry. ;)  Wrapping up this issue, I see FI_REMOTE_WRITE CQ events when using fi_writedata, and I get back the correct immediate data I sent for both psm and sockets providers.  Thanks.

**Comment by shefty** [comment]
I will update the man pages to clarify the issue wrt CQ events and RMA write without CQ data.

**Comment by shefty** [comment]
Updated man page and opened new issue to track feature request to support CQ events.
