### ISSUE TITLE
completion level to support MPI synchronous send

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#1328]
MPI defines a synchronous send operation. Synchronous sends do not complete until the message matches a receive operation on the far side. The intent of this is to allow applications ensure they are not dependent on internal buffering. Some applications use this for point-to-point synchronization as well.

Looking at MPI that targets the tagged OFI APIs, it looks like a completion level that matches this could be beneficial. MPIs are currently emulating this above OFI by reserving tag bits and implementing their own protocol.

Other tag matching APIs have generally defined synchronous sends. It might be useful for OFI to also define one.

FI_MATCH_COMPLETE?

@jsquyres @hppritcha @mblockso @charlesarcher @afriedle-intel

**Comment by shefty** [comment]
Any solution needs to be more general than something that only supports MPI tag matching synchronous send semantics.

From the description, this sounds more like an application level acknowledgement.  You're trying to tie the provider completion model based on activity required by the target application, with that activity potentially coming hours or days after the fact -- really, the provider has no idea.  That's a HUGE impact on the provider.

**Comment by sayantansur** [comment]
I haven't thought of what the semantics of this could be outside of the tag API, or the what the provider implications would be.

However, for tagged API, the implementation for providers is straightforward. Nearly any provider that implements the tag API will have to implement the rendezvous protocol underneath (to prevent large tagged messages that aren't matched yet from consuming large amounts of buffer space at the remote side). The provider could just map match_complete to the rendezvous protocol and be done with it. Various MPIs have employed this mapping for years ...

**Comment by shefty** [comment]
Nothing about the API should assume or require a specific implementation.  A provider may implement a rendezvous protocol, but is under no requirement to do so.  This completion model wouldn't be restricted to such a rendezvous protocol anyway.  An app could use it with an 8 byte message, which would be buffered entirely by the remote provider.  This proposal would require such a provider to not only buffer the data, but also be able to generate a send (ack) when posting a receive.  And the sender would need to track this request as pending for what could be a very, very, very long time.

Consider if this is the only message that the sender transmits.  It would now need to send ping messages occasionally, just to ensure that the target hasn't died.

We already have FI_DELIVERY_COMPLETE, which states that the initiator side no longer has to track the request.  Why isn't that enough?  Why should it care if the target has bothered collecting the data?  What if the remote side cancels the receive and drops the packet?

**Comment by sayantansur** [comment]
Yes, providers can implement this in weird ways :-) But they don't need to, right?

Even a small message send can be sent using the rendezvous protocol. The implementation of this protocol requires a handshake within the provider at the least.

FI_DELIVERY_COMPLETE says: "Indicates that a completion should not be generated until an operation has been processed by the destination endpoint(s). A completion guarantees that the result of the operation is available."

When applied to the msg or tagged APIs what does it mean? The data is in target's memory? If the sender dies and the receiver posts a receive, will that succeed?

**Comment by shefty** [comment]
> FI_DELIVERY_COMPLETE says: "Indicates that a completion should not be
> generated until an operation has been processed by the destination
> endpoint(s). A completion guarantees that the result of the operation is
> available."
> 
> When applied to the msg or tagged APIs what does it mean? The data is in
> target's memory? If the sender dies and the receiver posts a receive, will
> that succeed?

The result of the operation is "available".  It does not define (intentionally) if the target process must take some action in order to retrieve the result, such as posting the buffer needed for it to see the result, walking to the mailbox, or checking their PO box.  From the viewpoint of the sender, it is done with the request and no further action is required.  Basically, the fault domain of the request is entirely in the hands of the target.

**Comment by sayantansur** [comment]
Thanks, yea this is reasonable for FI_DELIVERY_COMPLETE. Although, this is different from the synchronous send mode in MPI.

**Comment by mblockso** [comment]
Another problem with MPI sync sends using OFI is asynchronous progress. The OFI provider may enable asynchronous progress, but if MPI needs to implement a "synchronous send" protocol then the ACK for the sync send will only be issued when the target rank reads the completion queue and sees that a sync send matched a previously posted tagged receive. 

If the target rank is in a compute phase then the origin rank will be blocked. Is there a possibility of deadlock here? I'm not sure, but it smells fishy.

Of course, the MPI implementation could spin up its own progress thread to handle this .... but wouldn't it be nicer if the provider async progress engine handled it by implementing 'FI_MATCH_COMPLETE'?

**Comment by shefty** [comment]
I am personally inclined to reject this request and state that this is an application level problem.  If an app disables internal buffering, then FI_DELIVERY_COMPLETE seems sufficient.  If an app wants internal buffering, well, then they get what they ask for and need to deal with that outcome.

**Comment by sayantansur** [comment]
The only OFI application that I know of that wants this is MPI, and it cannot afford to turn off buffering. MPI needs FI_RM_ENABLED as well.

We can close this for now and revisit it later if you want.

**Comment by mblockso** [comment]
I'm more concerned with the implications for asynchronous progress.  Am I wrong here?  It seems to me that MPI implementations will need a progress thread - outside of libfabrics - if they want full asynchronous progress. Without another thread, don't we need to drive MPI progress with application threads?

**Comment by shefty** [comment]
I'm more concerned that nothing does this.  If the initial message gets buffered by the provider and is acked, then who is going to send the ack-ack when the message is finally retrieved?  That is some undefined protocol message and requires a double ack by the receiver.  Really, this is like asking for buffering followed by saying but not really.

**Comment by mblockso** [comment]
Nothing does ... what? synchronous sends? I don't understand .. it is in the MPI standard and MPI applications use them.

I also don't understand the double-ack problem by the receiver. The first ack would only be sent after the tagged send is matched. I guess the message could be buffered at the receiver before the match (and ack), but so what? After the match the (potentially) buffered message would be copied into the final receive destination.

Maybe you are thinking about a rendezvous type of flow?  If so, then the ack would only be delivered after the data has been copied out of the source buffer at the origin. In an eager (single packet) type of flow where the entire source buffer is copied out along with the match information (the message size is less that the "buffered receive" size in ofi-speak?) then the ack is delayed until the match where normally (for FI_DELIVERY_COMPLETE) the ack would be delivered when the message is received by the provider.

**Comment by sayantansur** [comment]
The MPI synchronous send is often this is used by MPI apps/collectives to ensure that their messages don't consume data buffers on the remote side. This can be useful at scale when you really want to make sure you're not overwhelming the receiver.

Maybe we want to define this differently? Maybe all we want is to say: Send this message, but don't consume buffer on the other side if the side is not ready for it.

**Comment by shefty** [comment]
> Maybe we want to define this differently? Maybe all we want is to say:
> Send this message, but don't consume buffer on the other side if the side
> is not ready for it.

This is an entirely different matter, and we may actually be able to get somewhere with this.  :)

This is equivalent to a NOBUFFER option applied to the transfer.  I can actually think of how this might be implemented.

**Comment by sayantansur** [comment]
I'll ping the MPI folks to ensure that this definition satisfies synchronous send. One oddball case is when MPI_Ssend is called with zero bytes. Maybe MPI can just work around this if we define the flag like this.

Here's the bit from synchronous send from the MPI standard.

> A send that uses the synchronous mode can be started whether or not a matching receive was posted. However, the send will complete successfully only if a matching receive is posted, and the receive operation has started to receive the message sent by the synchronous send. Thus, the completion of a synchronous send not only indicates that the send buffer can be reused, but it also indicates that the receiver has reached a certain point in its execution, namely that it has started executing the matching receive. If both sends and receives are blocking operations then the use of the synchronous mode provides synchronous communication semantics: a communication does not complete at either end before both processes rendezvous at the communication. A send executed in this mode is non-local.

**Comment by sayantansur** [comment]
Discussed this with Charles and Sean here. It appears my definition doesn't really satisfy the MPI requirement and is really something different. Lets revisit this later when we have a stronger case for resource savings. Currently MPI is implementing it OK.

**Comment by mblockso** [comment]
Ok .. but what about the progress aspect? Am I wrong about it, or do we just not care that much? :)

**Comment by sayantansur** [comment]
So if we don't define this in OFI, it keeps OFI providers simple since they can provide auto progress without a thread or entity that sends the second "matched ack".

As regards to progress of MPI itself, I believe there is no really defined progress model in MPI for 2 sided. One must make calls into MPI to make progress.
