### ISSUE TITLE
Replace fi_bind with per class fi_*_bind calls

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#133]
There's only a single bind call, associated with the base class, not individual bind calls.

**Comment by goodell** [comment]
Should the `fi_bind` call be gone now?  I still see it in the implementation and in some parts of fabtests.  I can remove it if so, I just want to make sure that I understand the conclusion of the various GH issues that cover this topic.

**Comment by shefty** [comment]
Yes, the fi_bind call should be removed.
