### ISSUE TITLE
Query max supported value in fi_info

### ISSUE THREAD

**Issue by jithinjosepkl** [ofiwg/libfabric#1331]
For fields like inject_size, an app can only request for a particular value, and the fi_info call will fail if the requested size is larger than max supported value. But there is no way we can get the maximum value supported (without calling fi_info multiple times).

Should we add something like FI_MAX_SUPPORTED to pass in as hints value and get the max value supported by provider?

**Comment by sayantansur** [comment]
This could get confusing fast if applied to all the variables. Max supported may not mean a value that is optimal.

It is the application's choice whether to follow a code path where it works for specified set of flags/values, or whether it queries libfabric to see what is supported.

I think we should leave this as is and work with the applications to have better query of libfabric.
