### ISSUE TITLE
prov/sockets: segfault in FI_ATOMIC_READ amo with FI_INJECT flag set

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#1333]
I am calling `fi_fetch_atomic()` with the FI_ATOMIC_READ amo and encountered a segfault when I have the FI_INJECT flag set on the tx endpoint. 

`fi_fetch_atomic()` calls `sock_ep_atomic_readwrite()` which does the following:

```C
407     if(op == FI_ATOMIC_READ)
408         msg_iov.addr = NULL; 
```

Eventually the following happens (from prov/sockets/src/sock_atomic.c):

```C
171     src_len = 0;
172     if (flags & FI_INJECT) {
173         for (i=0; i< msg->iov_count; i++) {
174             sock_tx_ctx_write(tx_ctx, msg->msg_iov[i].addr,
175                       msg->msg_iov[i].count * datatype_sz);
176             src_len += (msg->msg_iov[i].count * datatype_sz);
177         }
178     } else {
179         for (i = 0; i< msg->iov_count; i++) {
180             tx_iov.ioc.addr = (uintptr_t) msg->msg_iov[i].addr;
181             tx_iov.ioc.count = msg->msg_iov[i].count;
182             sock_tx_ctx_write(tx_ctx, &tx_iov, sizeof(tx_iov));
183             src_len += (tx_iov.ioc.count * datatype_sz);
184         }
185     } 
```

When FI_INJECT is set, `sock_tx_ctx_write()` will be called with msg->msg_iov[i].addr as the buffer, which is hard coded to NULL, and in turn causes a segfault in memcpy.

**Comment by shefty** [comment]
FI_INJECT with atomic read doesn't make sense.  We should document this as an invalid usage.

**Comment by agontarek** [comment]
Since the FI_INJECT flag is a default flag being set, it would preclude the endpoint from issuing an atomic read via `fi_fetch_atomic()`. Couldn't the provider just ignore the FI_INJECT flag for FI_ATOMIC_READ?

**Comment by jithinjosepkl** [comment]
Or, we could update the provider to return an error (-FI_EINVAL)?

**Comment by shefty** [comment]
I think we just ignore the flag, specifically for defaults.  That way the default op_flags set for the endpoint are valid.

**Comment by jithinjosepkl** [comment]
Ok, makes sense for default flags. I will update the provider.

**Comment by agontarek** [comment]
Just to be clear, the reason I stumbled upon this behavior is that the amo operands can reside on the stack. My interpretation of the ofi manpage is that these buffers need to remain valid until a completion event occurs for the amo:

> The call fi_atomic transfers the data contained in the user-specified data buffer to a remote node.
...
> Unless the endpoint has been configured differently, the data buffer passed into fi_atomic must not be touched by the application until the fi_atomic call completes asynchronously.

The operands on the stack could become invalid before the completion event happens. The FI_INJECT flag seems to get around this problem since the provider will be responsible for maintaining the data buffers. I think that FI_INJECT should be honored for every amo other than FI_ATOMIC_READ.

**Comment by agontarek** [comment]
This patch fixed the segfault. My test case is working as expected. Thanks!

**Comment by jithinjosepkl** [comment]
Thanks for verifying, its merged now.
