### ISSUE TITLE
CI test failure after PR #1366

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1378]
Failure seems unrelated to PR, but at least we know the timeout fixes work!

https://travis-ci.org/ofiwg/libfabric/jobs/85591580

 name:   fi_scalable_ep -f sockets
  result: Fail
  time:   92
  server_stdout: |
  client_stdout: |
    fi_send(): simple/scalable_ep.c:296, ret=-111 (Connection refused)

This could be a timing issue with the test.

**Comment by jithinjosepkl** [comment]
Yes, looks like a timing issue. If the client is executed before starting the server, we will hit this error.

**Comment by shefty** [comment]
Doesn't the script insert a 1 second delay between starting the server and the client?

**Comment by jithinjosepkl** [comment]
Yes, the script has a 1s delay. Hmm, that should prevent client getting executed before server.
