### ISSUE TITLE
FI_ASYNC_IOV limit

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1393]
The man pages state that a 'large' number of IOVs may require that the app keep the IOV around until the operation completes.  However, the value for large is not specified.  The assumption is that any use of the *msg() calls require that the app keep the IOV around.  However, since the *msg() calls are the easiest way to override the default flag settings, this can be burdensome, especially if only a single IOV is used.  We need a way to specify the lower limit for when an IOV must be kept by the app.

**Comment by shefty** [comment]
Proposal:

Add async_iov_limit field to fi_tx/rx_attr.  This would be part of an ABI bump.

**Comment by goodell** [comment]
:+1:

**Comment by sayantansur** [comment]
:+1:

**Comment by shefty** [comment]
To add to the discussion, is async_iov_limit better as tx/rx attributes, or as a domain attribute?  I'm leaning to the latter, but that assumes that the additional flexibility of having this per tx/rx isn't needed...

**Comment by sayantansur** [comment]
Seems to me that the main requirement was to have an entry point that allows easy overriding of the flags, when using only one IOV.

Why don't we create such an entry point? Looking at the sendv() type calls, I'm not sure why they can't just use the sendmsg() instead? Can we change sendv() to take flags?

In terms of optimizations, a call like send_with_flags() can be optimized pretty well in FABRIC_DIRECT mode with the usage of inlining + link time optimization.

**Comment by shefty** [comment]
FI_ASYNC_IOV is a mode bit, not a flag.  The issue is that as defined the app must keep all iov's around, even if the provider does not need them.  For example, the send call takes the buffer and size as parameters, so any provider must be able to cache at least 1 iovec.  There's no reason why the provider could not cache sendv or sendmsg calls if iov_cnt = 1.  The simple solution is to only require an async iov if more than 1 iov is specified.  A more complex solution is to only require an async iov once a threshold has been crossed.
