### ISSUE TITLE
FI_CONTEXT with CQs

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1394]
Some endpoints (such as those supporting tagged operations) may require FI_CONTEXT, while others may not.  However, this can result in a difficulty for providers when processing completions.  A provider may not know if a completion is associated with an FI_CONTEXT or not.  As a result, the provider could be forced to always require a context from the app.

One solution is to require that the provider separate these endpoints into different domains.  The drawback of that is that the addressing data, memory registrations, etc. would be duplicated.  An alternative is to limit the type of endpoints that a CQ may be associated with.

We need to understand the scope of this issue, which seems likely to hit providers that have at least partial hardware support, and if there is a reasonable solution for it.

**Comment by shefty** [comment]
Proposal:

Add caps and mode fields to fi_cq_attr.  Link fi_cq_attr from fi_info.  This would be part of an ABI bump.

**Comment by goodell** [comment]
I think this makes sense, though we'll have to hammer out the details still.

**Comment by shefty** [comment]
A relatively simple (but also restrictive) proposal is to add the following to EP/TX/RX mode bits:

FI_PRIVATE_COMP
If set, indicates that the EP will have dedicated completion queues and/or counters.  A CQ or counter may only be associated with a single endpoint if it has been configured with FI_PRIVATE_COMP.

FI_RESTRICTED_COMP
If set, indicates that the EP will only share completion queues and/or counters with EPs that are of the same type and have the same set of capabilities.

By default, a provider will assume that completion objects will be shared among different types of endpoints (for compatibility).  No changes are made to the CQ/counters attributes or fi_info -- the provider will need to determine the correct behavior when binding to the EP based on the above flags.  It's possible that we only need FI_RESTRICTED_COMP to address the problem captured by this issue.

This proposal can be expanded somewhat if needed, for example, by defining FI_PRIVATE_CQ / FI_PRIVATE_CNTR mode bits instead.  One potential limitation with this approach is that the provider does not know if the TX and RX attributes will be bound to the same CQ.  Maybe there's a way to capture that with other flags?

**Comment by goodell** [comment]
I'm ok with `FI_RESTRICTED_COMP`, I think we could even already make minor use of it in usnic.  Do we have current hardware that would benefit from `FI_PRIVATE_COMP`?

**Comment by shefty** [comment]
I'm not sure there's an application use case for FI_PRIVATE_COMP, but it looks like a reasonable use for RDM or DGRAM EPs.  I can think of _potential_ optimizations if the provider can assume that all completions relate back to a single EP -- e.g. maybe better locking, address lookups, etc.  But will providers actually code for this?

In general, I want a limited solution that's easy for apps to use.  I see a trade-off defining options that providers don't currently use, versus phasing in changes that require applications to update later.  Basically I haven't decided either way if I'm in favor of adding FI_PRIVATE_COMP, versus only FI_RESTRICTED_COMP.

**Comment by goodell** [comment]
Notes from today's call:

- @sayantansur suggested switching from using mode bits (where the default is willy-nilly CQ-to-EP bindings are possible, yielding worse performance for some use cases/providers) to using capabilities (where the default would have more restrictions but better performance for common use cases).  I'm in favor of this switch.
- The proposed `FI_RESTRICTED_COMP` restrictions ("only share completion queues and/or counters with EPs that are of the same type and have the same set of capabilities") might not be quite right, or might need to be broken out.  The concern is around the use case of having multiple EPs with the same EP type but different capabilities (e.g., tagged and RMA) but sharing the same CQs.
- We didn't get to discussing `FI_PRIVATE_COMP` on the call, this still needs further discussion.

**Comment by goodell** [comment]
Discussion on today's call led to the following consensus:

- Add a blanket restriction to the man pages that CQs/counters can only be shared between EPs of the same type (DGRAM/RDM/MSG).  Capability and mode bits for the EPs do not affect CQ/counter sharing in normal operation.  This is currently ambiguous in the man pages.
- Add `FI_RESTRICTED_COMP` as a *mode* bit to the API to allow the application to indicate that it further will only share CQs/counters between EPs with the same set of mode and capability bits (in addition to the blanket restriction on EP type).
- If we ever decide that sharing CQs/counters between different endpoint types (DGRAM/RDM/MSG) is desirable enough to support in the API, in a later release we can add a new *capability* bit for providers that want to support it (`FI_MIXED_COMP_EP_TYPE` or whatever) or altogether drop the restriction and explicitly call out the mixed type support.  It's much harder to add the restriction later if we make mixed EP type sharing the default.

@sayantansur do you have a little time to make a PR with the man page updates?

**Comment by sayantansur** [comment]
Thanks for the summary. Yea, I will make a PR soon. It is just that I can use a "little time" for many things :-/

**Comment by sayantansur** [comment]
One minor wrinkle is that at CQ creation time, we still don't know whether this CQ will be associated with EPs that will have operations using FI_CONTEXT or not. That means, the CQ poll routines that get set during fi_cq_open() need to be able to deal with both situations, and then at run time check the type again.

This is obviously micro-optimization, but it would be nice if we could deduce during CQ creation what type of FI_CONTEXT usage it will have.

One idea is to add a `mode` bits field in `struct fi_cq_addr`. The application would then be required to pass in the mode bit FI_CONTEXT to both `fi_getinfo` and `fi_cq_open` call.

This would get rid of the additional mode bit FI_RESTRICTED_COMP that is currently proposed, as the application is now aware of what type of CQ it can attach EPs to.

Thoughts?

**Comment by shefty** [comment]
A CQ can defer setting function pointers until the first EP is bound to it.

I'm still looking at how to associate the CQ attributes with fi_info, but that's ending up as a non-trivial link.  I've also thought about adding mode/cap bits to the CQ attributes, but that has compatibility problems that would need to be addressed.  (The api_version may work for that.)

One problem I see is that the provider must be able to specify what mode bits are required of an EP on return from fi_getinfo.  Those bits are dependent on how that EPs completion mechanisms will be shared.  FI_RESTRICTED_COMP is a very restrictive way of indicating how that sharing may occur.  The EP completion sharing is what I was trying to capture.

**Comment by sayantansur** [comment]
> A CQ can defer setting function pointers until the first EP is bound to it.

That's great, solves the problem I was talking about. Maybe it needs to be clarified in the man pages though, currently, there is no such restriction. I can submit a PR.

I'll think about the FI_RESTRICTED_COMP further to see if there are better ideas.
