### ISSUE TITLE
Provide mechanism for receiver to learn source address

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1399]
See issue #275 for a more detailed discussion.  Opening a new issue to filter the discussion and work with the current API.

It is possible for an application to receive data from a peer endpoint, the address of which has not been inserted into the local AV.  In many cases, the provider will have the source address of the peer available as part of the original message or completion data.  There is no way defined for providing that data to an application.

**Comment by shefty** [comment]
Proposal:

The CQ will return -FI_EAVAIL if a completion is not associated with a source address that has been inserted into the corresponding AV.  The error information will be FI_EADDRNOTAVAIL, with the error data referencing the source address.  The application may insert the returned source data into an AV.

This may be defined as required behavior if FI_SOURCE is set for the CQ.  An app would need to check the libfabric version number to determine if this feature is available. Alternatively, the app must request this feature through a new flag.

**Comment by goodell** [comment]
Your proposal works for me.  I think a new (capability?) flag feels a bit better to me.  This also allows us to add support for this behavior on a per-provider basis instead of requiring a big-bang upgrade.

**Comment by sayantansur** [comment]
How does the CQ know that the address has not been inserted into the AV? Would it have to scan the AV to know whether a fi_addr is available or not?

**Comment by shefty** [comment]
> How does the CQ know that the address has not been inserted into the AV?
> Would it have to scan the AV to know whether a fi_addr is available or
> not?

It requires a lookup into the AV to convert the source address into an fi_addr_t, which should already be part of supporting FI_SOURCE.

**Comment by sayantansur** [comment]
Yea, this sounds reasonable. Wondering if this lookup function could be exposed to the app, since the providers supporting FI_SOURCE need to be implementing this functionality anyways.

**Comment by shefty** [comment]
> Yea, this sounds reasonable. Wondering if this lookup function could be
> exposed to the app, since the providers supporting FI_SOURCE need to be
> implementing this functionality anyways.

I'm not sure how useful exposing this would be.  It requires that the app deal directly with the fabric specific addressing.
