### ISSUE TITLE
Sockets provider fills in tag field in CQ entry for tsends

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#1420]
According to the man page the tag field only applies to received messages, but the sockets provider fills it in for sends also.  It seems that the MPICH netmod might rely on this incorrect behavior.

@charlesarcher @jithinjosepkl

**Comment by charlesarcher** [comment]
MPICH shouldn't be inspecting the tag field for send completions.  Can you point me to the offending code in MPICH?  I can take a look.

**Comment by sungeunchoi** [comment]
@kim-mcmahon is looking at the MPICH side of this, so she may be able to shed some more light (FYI she's booked the rest of the day).  Based on some logs I have, the last message is:

      PE 0: Entered MPID_nem_ofi_finalize: gl_data.rts_cts_in_flight=2

**Comment by sungeunchoi** [comment]
Oh and I should point out that this is with the GNI provider (that doesn't set tag for tsend).  We haven't had a chance to try with a modified sockets provider, but this all worked when we used to set it for tsend in the GNI provider. That's why I said it *might* rely on it earlier.  Don't want to send you on a wild goose chase.

**Comment by charlesarcher** [comment]
I did a quick inspection of the code and didn't see anything obvious.

**Comment by sungeunchoi** [comment]
Thx for taking a look @charlesarcher

**Comment by jithinjosepkl** [comment]
Thanks @sungeunchoi  for the report. I will update sockets-provider to not fill-in tag info during send-completion. But, I don't think MPICH netmod inspects the tag field in send-completion.

**Comment by sungeunchoi** [comment]
Thanks Jithin.  I think we're realizing now that we made a mistake in our bisection of commits.  Sorry for the bother on your end.
