### ISSUE TITLE
sockets: rx_ctx_bits value doesn't agree with manpage

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#1437]
When using the sockets provider, providing a `rx_ctx_bits` value according to the manpage results in incorrect addressing with `fi_rx_addr()`. The fi_av manpage states:

> Receive Context Bits (rx_ctx_bits)
>      The receive context bits field is only for use with scalable endpoints. It
> indicates the number of bits reserved in a returned fi_addr_t, which will be
> used to identify a specific target receive context. See fi_rx_addr() and
> fi_endpoint(3) for additional details on receive contexts. The requested
> number of bits should be selected such that 2 ^ rx_ctx_bits >= rx_ctx_cnt for
> the endpoint.

With the sockets provider, this formula needs to be:

`2 ^ rx_ctx_bits >= MAX(rx_ctx_cnt, tx_ctx_cnt) `

I am not sure if this is a manpage issue, or a bug in the sockets provider.

**Comment by shefty** [comment]
I'm not understanding what the actual issue is here.

**Comment by jithinjosepkl** [comment]
Also, we should not be considering tx_ctx_cnt in rx_ctx_bits.

**Comment by agontarek** [comment]
I am using scalable endpoints. I have 3 tx contexts and 2 rx contexts. If I use a `rx_ctx_bits` value of 1, I get incorrect addressing from `fi_rx_addr()`, but a `rx_ctx_bits` value of 2 results in correct addressing. I will try to get a stand alone reproducer.

**Comment by shefty** [comment]
The rx_ctx_bits value comes from the provider.  It's not something the app supplies.

**Comment by agontarek** [comment]
Got it. Thanks. Closing the issue.

My confusion was over the wording of `fi_av_open` in the manpage. My interpretation was that I needed to fill in the `rx_ctx_bits` field for the `fi_av_attr` I provide. 

After the `fi_av_open` call, will the `fi_av_addr` be updated with the correct `rx_ctx_bits` value?

**Comment by jithinjosepkl** [comment]
I think the app can request for a specific value rx_ctx_bits in fi_av_open(). Just that the requested number of bits should be selected such that 2 ^ rx_ctx_bits >= rx_ctx_cnt for the endpoint. For fi_rx_addr(), app should use this value itself. @shefty - is this correct?

The scalable_ep.c example in fabtests uses rx_ctx_bits in this way. Currently this uses 2 bits for rx_ctx_bits. I modified it to use 1 bit, and it still works fine.

@agontarek - Are you facing any issue with the scalable_ep example? Or is it with some other use case? Just wanted to make sure we are not overlooking any issues (if any) in the sockets-provider.

**Comment by agontarek** [comment]
@jithinjosepkl The issue I am running into is with another use case. I changed my use case to leave the rx_ctx_bits field as 0, use the value returned in the fi_av_attr after fi_av_open, and didn't encounter incorrect addressing. If I find time, I can modify the scalable_ep.c example to mimic what I am doing and see if things fail there.

At the very least, if this is indeed optional, the manpage should be updated to show the intent. As it stands, it reads as if this is a required value.
