### ISSUE TITLE
Multi-threading model on RDM ?

### ISSUE THREAD

**Issue by svalat** [ofiwg/libfabric#1481]
Hi,
I want to use multiple thread for usage of PSM via libfabric, so using RDM mode. In this mode what is the good approach to use multiple threads.

1) Might require some locks or the two can be done in parallel without locking ?
   - One thread to send
   - On thread to test queue
2) Is it possible to setup more than one endpoint per process in RDM and attached part or the remote targets to each one or it is required to use only one endpoint per process ?
  - X threads managing Y targets

In MSG mode I guess that the good approch is to manage Y endpoint per thread and it is fine.

Thanks for the answer.

**Comment by shefty** [comment]
@j-xiong will know the best usage for the PSM provider

**Comment by j-xiong** [comment]
For PSM the best practice is to use only one endpoint and only one thread. That being said, multiple endpoints can be created but only one can be used for "target". One thread for sending and one thread for testing the completion is generally allowed w/o lock. However, the performance is going to be less optimal compared to the single thread method.

**Comment by j-xiong** [comment]
For PSM2 the endpoint limitation has been removed, but signle thread is still the recommendation.

**Comment by svalat** [comment]
Thank you very much for the answer
