### ISSUE TITLE
man: Description of Max RMA Ordered Size in fi_endpoint(3)

### ISSUE THREAD

**Issue by Pgrun** [ofiwg/libfabric#1482]
As near as I can tell, Max RMA Ordered Size controls the relative order in which the data for disjoint RMA (or Atomic) operations is placed on the fabric.  But it does not control the placement of data in memory at the destination (that is controlled by FI_ORDER_DATA).

Current man page says, 
"The maximum ordered size specifies the delivery order of transport data into target memory for RMA and atomic operations."

I think this should actually say,
"The maximum ordered size specifies the order in which data for disjoint RMA (or Atomic) operations is transmitted to the receiver."  

The text could be further clarified by saying,
"For an RMA write operation, the receiver is at the responder end.  For an RMA read or Atomic operation, the receiver is at the requester end."

**Comment by shefty** [comment]
The man pages include this as part of the description:
```
Data ordering refers to the access of target memory by subsequent operations. When back to back RMA read or write operations access the same registered memory location, data ordering indicates whether the second operation reads or writes the target memory after the first operation has completed. Because RMA ordering applies between two operations, and not within a single data transfer, ordering is defined per byte-addressable memory location. 
```
I believe this sufficiently covers the meaning behind RMA ordered size.  The definition deals the the access of the data at the target memory region, and not the order that data is transmitted.  Data can be sent and arrive in any order, as long as the access of the target location is ordered correctly wrt the initiator of the requests.
