### ISSUE TITLE
Add new debug log levels

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1505]
See PR #1472.

The request is for something like FI_LOG_DEBUG_1, FI_LOG_DEBUG_2, ... to allow turning up debug log levels, but only in the debug build.

**Comment by shefty** [comment]
@evgeny-leksikov

**Comment by pmmccorm** [comment]
See also #1191

**Comment by shefty** [comment]
Closing this.  The current debug level combined with subsystem details seem sufficient for most use cases, and provider developers don't seem keen on writing more debug messages than necessary.  :)
