### ISSUE TITLE
No --with-psm configure option?

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#1506]
In order for configure to locate my PSM header and libs I needed to append
```
   CPPFLAGS=-I/usr/local/Infinipath/include LDFLAGS=-L/usr/local/Infinipath/lib64
```
to the configure command line.

I was expecting something like a `--with-psm=` configure option or some environment variable to do the equivalent.   However, if such a thing exists it is not described in the `configure --help` output.

NOTE: it looks like my PSM is too old to support this provider anyway.  So, this is not any sort of priority for me.

**Comment by j-xiong** [comment]
The "--with-xxx" option has been merged with "--enable-xxx" option. You can use "--enable-psm=path-to-psm-installation".

**Comment by PHHargrove** [comment]
Thanks, that worked.
The "configure --help" output does not explain this, nor does README.
So this issue is now a request to clarify the documentation.

-Paul

**Comment by jsquyres** [comment]
@j-xiong Github pro tip: if you put "Fixes #X" in the commit message on the PR, it'll auto-close github issue number X.  E.g., "Fixes #1506" would have closed this issue when the PR was merged.

**Comment by jsquyres** [comment]
#1519 was merged that fixed this issue.

**Comment by j-xiong** [comment]
@jsquyres Thanks for the tip.
