### ISSUE TITLE
redundant configure options for mxm provider

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#1523]
The mxm provider handles "--enable-mxm", "--with-mxm", "--with-mxm-include" and "--with-mxm-lib" options in its local configure script. However, all these functionalities have been covered by the FI_PROVIDER_SETUP macro which is also used by the mxm provider. This macro uses an enhanced "--enable-xxx" option for both the "--enable--xxx" and "--with-xxx" semantics. See config/fi_provider.m4 for details.

**Comment by shefty** [comment]
@alexander-sannikov is maintaining the mxm provider

**Comment by shefty** [comment]
Fixed with PR #1543
