### ISSUE TITLE
add verbs provider builds to Travis CI

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#1538]
Right now our [Travis CI instance](https://travis-ci.org/ofiwg/libfabric) only builds the `sockets` provider.  We should strive to build as many other providers as possible, even if we can't run network tests on them, including the `verbs` provider.  This would have caught an issue in PR #1524, obviating #1537.  Looks like there was previously an aborted attempt at this in PR #1360.

Since we are using the container-based infrastructure, we can't easily just `apt-get install libibverbs-dev librdmacm-dev` and call it a day.  Instead it seems like we can either:

1. Install from source (as was attempted in #1360); or
2. Use the [`apt:` stanza](https://docs.travis-ci.com/user/apt/) in our [`.travis.yml`](https://github.com/ofiwg/libfabric/blob/master/.travis.yml).

The problem with (2) is that it requires the relevant packages to be on [the Travis whitelist](https://github.com/travis-ci/apt-package-whitelist/).  To that end, I've initiated the process of having these packages evaluated for inclusion in the whitelist.  You can see the issues that I've opened for this here: https://github.com/travis-ci/apt-package-whitelist/issues/created_by/goodell.  But this might take a while, so pursuing (1) is probably what we should do in the short run.

**Comment by shefty** [comment]
PR #1360 never fully worked for some reason.  But we should be able to just call git clone and install the 2 libraries that we need.  We can build the psm and usnic providers as well, even though vendor testing will likely find issues there fairly quickly.
