### ISSUE TITLE
man: fi_ep_bind flags FI_TRANSMIT vs FI_SEND

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#1550]
The v1.1.1 fi_endpoint(3) manpage states that the FI_TRANSMIT flag and FI_SEND flag may be used interchangeably:

> FI_TRANSMIT
>     Directs the completion of outbound data transfer requests to the specified completion queue. This includes send message, RMA, and atomic operations. The FI_SEND flag may be used interchangeably.

This generates confusion since the FI_SEND flag states that it only applies to messages, not RMA/atomic operations, and only applies to counters:

> FI_SEND
>     Increments the specified counter whenever a successful message is transferred over the endpoint. Sent messages include both tagged and normal message operations.

**Comment by shefty** [comment]
FI_SEND and FI_TRANSMIT are the same value. The definitions above are correct with respect to the actual functionality being described. I.e. when bind an EP to a CQ, you can have 1 CQ on the transmit sid, which covers all outbound transfers (messages, RMA, atomnics).  When binding an EP to a counter, the counters are more refined.  In that case FI_SEND/FI_TRANSMIT only results in counting sent messages.

**Comment by agontarek** [comment]
Can an error be generated when attempting to bind a cq with counter specific flags and vice-versa?

**Comment by shefty** [comment]
Yes - invalid bindings should result in an error.  I haven't checked the providers to confirm this, but if they don't I would mark them with bugs.
