### ISSUE TITLE
sockets: return error when fi_ep_bind() is called with invalid flags

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#1552]
When calling fi_ep_bind(), the provided flags have different meanings if the fid refers to a CQ or counter. If counter specific flags are used in conjunction with a CQ fid, and vice-versa, an error should be generated.

**Comment by shefty** [comment]
@shantonu @jithinjosepkl - sock_ctx_bind() should check for invalid flags and fail if any are set.

**Comment by shantonu** [comment]
Ok, I'm looking into it.
