### ISSUE TITLE
verbs: RAI_FAMILY does not exist in all versions of libibverbs

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1553]
I don't know when RAI_FAMILY was introduced, but it does not exist in all versions of libibverbs (e.g., see the libibverbs that comes in trusty/debian: https://travis-ci.org/open-mpi/ompi/builds/96276899).

The verbs provider needs to configure-check for this constant.  If it's not found, the verbs provider either needs to not use this constant, or disable itself if this constant is absolutely needed for correct functionality.

**Comment by jsquyres** [comment]
Ping: @ddurnov @evgeny-leksikov

**Comment by evgeny-leksikov** [comment]
This is dependency from librdmacm. @jsquyres, will it be fixed by #1544? Or we need another check during configure execution?

**Comment by jsquyres** [comment]
Nope, it's unrelated to #1544.  We need a configure check for it.

**Comment by evgeny-leksikov** [comment]
Interesting, this constant was used in libfabric v1.1.1, why it is exposed only now? Could you provide version of librdmacm used there? Compilation is broken on the constant usage, not include header. It means librdmacm is available in the system.
@a-ilango @shefty

**Comment by jsquyres** [comment]
According to https://travis-ci.org/open-mpi/ompi/builds/96298036

* libibverbs 1.1.7utuntu1

I don't know if that includes librdmacm or not...?

**Comment by jsquyres** [comment]
Oh I found it: librdmacm 1.0.16

**Comment by evgeny-leksikov** [comment]
Indeed, the constant is defined in 1.0.17

**Comment by jsquyres** [comment]
Not sure why it fails, but it does.

Sent from my phone. No type good.

On Dec 11, 2015, at 8:21 AM, evgeny-leksikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Indeed, the constant is defined in 1.0.17

-

**Comment by a-ilango** [comment]
The RAI_FAMILY flag is needed to support AF_IB addresses in the node parameter for fi_getinfo. I think the best way to go about this might be to drop AF_IB support if older version of librdmacm is used. Let me come up with a fix for this. I have to find how to do this. Does this issue need to be fixed urgently?

**Comment by jsquyres** [comment]
Does it need to be there for v1.2?

Sent from my phone. No type good.

On Dec 11, 2015, at 10:38 AM, arun ilango <notifications@github.com<mailto:notifications@github.com>> wrote:


The RAI_FAMILY flag is needed to support AF_IB addresses in the node parameter for fi_getinfo. I think the best way to go about this might be to drop AF_IB support if older version of librdmacm is used. Let me come up with a fix for this. I have to find how to do this. Does this issue need to be fixed urgently?

-

**Comment by a-ilango** [comment]
I think the code to detect and drop AF_IB support would not be needed in 1.2. As you said before we can add configure logic to disable verbs provider if it cannot find RAI_FAMILY defined. That would be needed for 1.2 to prevent compilation issues. I'm hoping that would be a quick fix. Let's also wait what Sean has to say on this.

**Comment by shefty** [comment]
Let's go with disabling the verbs provider if this constant is not found and require a newer version of librdmacm rather than deal with working around it.
