### ISSUE TITLE
usnic: Maximum 16 connections on FI_EP_MSG?

### ISSUE THREAD

**Issue by wavesoft** [ofiwg/libfabric#1587]
I am working on a [libfabric transport for nanomsg](https://github.com/wavesoft/nanomsg-transport-ofi/) and I was using the connection oriented, `EP_MSG` endpoints, currently testing the `usnic` provider. I am using the `libfabric-1.1.1` release and I encountered some problems with the socket shutdown, as mentioned in #1567 , but I kept testing my early prototypes. 

Soon another problem came up: Since the connections were never closed, I tried to see the limit of the concurrent connections the `EP_MSG` endpoint can support. I was surprised to see that after 16 connections (which means on the 17th connection) I get the following error:

```
Error on fi_enable(): src/transports/ofi/hlapi.c:606, ret=-12 (Cannot allocate memory)
```
It seems that `fi_enable` returns `-FI_ENOMEM`. This always occurs after my 16th retry, which looks like a limit of concurrent connections. It's true that I encountered a similar problem with 32 connections on the `socket` provider.

Therefore I am curious... is this parameter configurable? Or is this a hard limit somewhere?

**Comment by bturrubiates** [comment]
Hmm, I don't think the `usNIC` provider ever intentionally returns `-FI_ENOMEM`. That might mean that an actual call to `malloc` is failing. I skimmed through the provider code and I didn't see any hard limits. @rfaucett might be able to say more about that.

Did you install from source, and are you able to recompile? It might be useful to try configuring with `--enable-debug` to capturing some of the log output to determine what call is failing.

**Comment by wavesoft** [comment]
Good point. I will check the size of the memory regions that I allocate. Could it be that the NIC hardware has some limit on the buffer it can manage?

**Comment by goodell** [comment]
I suspect you are running out of WQs/RQs/CQs.  Your usNIC VFs are probably only configured for 32 WQs/RQs each (or 16/32 CQs each, depending on how you're mapping CQs-->EPs).  You can check this with the `/opt/cisco/usnic/bin/usd_devinfo` utility that came with your Cisco drivers in the `usnic_tools` package.  It will give some output like this:
```
usnic_0:
        Interface:               eth6
        MAC Address:             24:57:20:77:10:00
        IP Address:              10.200.2.121
        Netmask:                 255.255.255.0
        Prefix len:              24
        MTU:                     9000
        Link State:              UP
        Bandwidth:               10 Gb/s
        Device ID:               UCSC-PCIE-CSC-02 [VIC 1225] [0x0085]
        Firmware:                (REDACTED)
        VFs:                     32
        CQ per VF:               16
        QP per VF:               16
        Interrupts per VF:       2
        Max CQ:                  512 
        Max CQ Entries:          65535
        Max QP:                  512
        Max Send Credits:        4095
        Max Recv Credits:        4095
[...]
```

These lines are the relevant ones:
```
        CQ per VF:               16
        QP per VF:               16
```

For uninteresting reasons, the current `EP_MSG` support in the `usnic` provider ends up using two QPs (a WQ+RQ pair) per libfabric EP.  The CQs map 1:1 between hardware CQs and libfabric CQs.

The "right" fix for this would be to use shared endpoints (see the [fi_endpoint(3)](http://ofiwg.github.io/libfabric/v1.1.1/man/fi_endpoint.3.html) man page), but the `usnic` provider doesn't yet support this feature.

**Comment by goodell** [comment]
Depending on which Cisco VIC model you have and what other usNIC use cases you have, you could increase the current QP limits by a significant factor, which would at least push out the point at which you hit the `ENOMEM` case.

**Comment by wavesoft** [comment]
@goodell - You are right. Thanks for pointing this out! In my case `usd_devinfo` reports the following, which makes sense:
```
	VFs:                     16
	CQ per VF:               6
	QP per VF:               6
```

**Comment by goodell** [comment]
Strange though, 6 QPs per VF doesn't match up with running out of resources on the 17th connection.  It sounds more like you are creating a new libfabric "domain" (which maps to a usNIC VF) for each connection.  That's not exactly an invalid usage model, but it's not one that I would expect, since it would prevent other processes on the same machine from being able to use usNIC features while your process is running and using all the VFs.
