### ISSUE TITLE
usnic: EP_RDM performance and data integrity suffer in the presence of congestion or packet loss

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1621]
Drops or malformed packets can result in deadlock or corrupted data when using the `EP_RDM` implementation in the `usNIC` provider. The increase in traffic and performance is related to a bug in the `NAK`/`ACK` processing code.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
