### ISSUE TITLE
Why is libfabric.pc in both the libfabric and libfabric-devel RPM?

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1630]
@patrickmacarthur @pmmccorm I notice this morning that the libfabric.pc file is in both the libfabric and libfabric-devel RPM.  This is apparently permissable (which is news to me!) -- rpm must be smart enough to figure out that this one file that has the exact same contents between two RPMs effectively needs to be ref counted.

But it seems a little weird: should we be installing the .pc file for the non-devel RPM?  I.e., what's the use case for having it in the non-devel RPM?

**Comment by pmmccorm** [comment]
It should just be in the -devel package.

**Comment by jsquyres** [comment]
I would think so to -- I just wanted to make sure there was no non-obvious use case for wanting it in the main package.  Sounds like: "no".
