### ISSUE TITLE
Do we need a 1.2.1 release?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1640]
See #1631 - regarding versioning.
@goodell @jsquyres @pmmccorm @bturrubiates 

I haven't had time to do this, but started looking at it today.  To date, we have:

* v1.0.0: --version-info 1 (which I think is a synonym for "1:0:0")
* v1.1.0: --version-info 2:0:1
* v1.1.1: --version-info 2:0:1
* v1.2.0: --version-info 2:0:1

From reading the libtool versioning data, it seems that it is most important to increment current (C.0.0) -- since that could indicate that APIs were removed, age (0.0.A) is of next importance -- new APIs were added, with revision (0.R.0) updates seeming of relatively minor importance -- yeah the code changed.  V1.0 and v1.1 are okay.  v1.1.1 and v1.2 are already out and missed updating the revision.  But... does this *really* matter?  In particular, since v1.1.1 was off as well, I think fixing this in either a 1.2.1 or 1.3 release in a couple of months should be sufficient. Updating the libtool revision number seems like a minor issue that isn't worth justifying another release.

**Comment by bturrubiates** [comment]
In #1631 @jsquyres stated:
> Unfortunately, this should have been done for the v1.2.0 release (i.e., the v1.2.0 release will incorrectly overwrite a prior installed v1.1.1 library).

Is that an issue we care about?

**Comment by goodell** [comment]
@shefty wrote:
> But... does this really matter?

Probably not much.  Especially if we really didn't add any new public APIs in the v1.1.1-->v1.2.0 transition (I haven't taken the time to verify this though).

@bturrubiates said:
> In #1631 @jsquyres stated:
> 
> > Unfortunately, this should have been done for the v1.2.0 release (i.e., the v1.2.0 release will incorrectly overwrite a prior installed v1.1.1 library).
>
> Is that an issue we care about?

I'm not sure I fully understand the scenario he's talking about there.  Two libfabric versions installed from RPM or similar package will conflict in the headers and man pages, so they won't be able to be installed at the same time anyway.  And users who are installing from source will have related problems if they are installing two different versions to the same `--prefix`.

**Comment by shefty** [comment]
Luckily, I believe that all new APIs were added between v1.0 and v1.1.  The v1.2 release simply added new providers.  I.e. only the revision number should have been updated.  But I don't understand what the revision number really tells an app.

**Comment by goodell** [comment]
It's just a tie-breaker for the linker.  I.e., "when the interfaces otherwise match, use the library with the newest (numerically highest) revision."  But that only matters if multiple versions of the library are installed in the library search path, which pretty is rare IMO.

**Comment by jsquyres** [comment]
@goodell The scenario I am referring to is when you have two different libfabric RPMs installed.  In the RHEL conventions, for example, you'll just have the `.so` libraries in the main RPM, and have a separate `-devel` RPM for the headers, etc.  So it's possible to have both `libfabric-A.B.C` and `libfabric-D.E.F` RPMs installed.  And you might have applications linked against the two different versions of the `libfabric.so`.  In this case, incrementing the Libtool shared library version number is pretty important (i.e., you wouldn't want the `libfabric-A.B.C` RPM and the `libfabric-D.E.F` RPM to install a libfabric.so with the same exact filename).

Granted, that's likely not a common case -- but the whole point of the Libtool shared library version numbers is to allow situations like this.  We should either do it correctly or we shouldn't do it at all.

**Comment by jsquyres** [comment]
@shefty I think this is more a question for the packagers.  Who should we ask at Red Hat / SLES / OpenHPC / ...?

I agree that we can't re-issue v1.2.0 -- this fix would only be for v1.2.1 or beyond.

I think only the timing is the question (i.e., do a v1.2.1 release in the near future because of this issue, or just wait until v1.2.1/v1.3.0 comes out organically and contains a proper update for the library shared version).  Right?

**Comment by shefty** [comment]
Yes, the question is whether this is significant enough to warrant a new release NOW that only fixes this problem, versus waiting until March.  It doesn't seem so.  I care because it throws off internal validation on the v1.2 package.

FWIW, I checked libibverbs, and it only reports a single digit version (1).  So I'm not sure anyone would be too concerned.  I think the distros use their own installation scripts (possible derived from what we provide).

**Comment by jsquyres** [comment]
I think I'm *minorly* in favor of doing a 1.2.1 *now*, but I won't be heartbroken if we don't.

I'm curious as to what you mean by "it throws off the internal validation on the v1.2 package."  Can you explain?

And FWIW: If Libibverbs is reporting `--version-info X`, where `X` is a single digit, they're doing it wrong.

**Comment by shefty** [comment]
Intel teams have pulled in the v1.2 package into their larger product packages for testing.

I agree that libibverbs is reporting the version wrong.  My point is that it has been wrong for at least 10 years and no one has cared yet.  So the impact of us waiting 2 months doesn't seem like a big deal.  Nothing mentioned so far is calling out this bug as highly critical, show-stopper to me.

**Comment by jsquyres** [comment]
Ok.
