### ISSUE TITLE
Move gni buddy allocator into common code

### ISSUE THREAD

**Issue by jithinjosepkl** [ofiwg/libfabric#1663]
Please see #1661

**Comment by jithinjosepkl** [comment]
@e-harvey - Please assign to yourself.

**Comment by e-harvey** [comment]
I cannot assign myself.  I think I need to be added as a contributor first.

**Comment by goodell** [comment]
@jsquyres can you help us out here?

**Comment by jsquyres** [comment]
Just curious: is @e-harvey an Intel employee?

**Comment by jsquyres** [comment]
Looks like someone beat me to it -- @e-harvey should have an email waiting to accept an invitation into the ofiwg Github organization.  Once accepted, the issue can be assigned to him.

**Comment by shefty** [comment]
I added him.  I don't think he's an Intel employee.  He may be an intern at the labs, but that's completely a guess.

**Comment by e-harvey** [comment]
Hi Sean and Jeff.  Yes, I'm a student intern at LANL.
