### ISSUE TITLE
usnic: Unexpected memcpy on usdf_msg_hcq_progress

### ISSUE THREAD

**Issue by wavesoft** [ofiwg/libfabric#1669]
I am profiling some benchmarks [testing my OFI transport for nanomsg](https://github.com/wavesoft/nanomsg-transport-ofi/), trying to achieve a zero-copy for the path between Application and NIC. I succeeded to do so on the _sending_ path, but it seems to be a `memcpy` on the _receiving_ path, that seems to come from libfabric.

_(Note: I am sending and receiving quite big messages = 20~50Mb)_

I am not sure if I have configured something wrong, but here is what I see on kcachegrind:

<img width="267" alt="screen shot 2016-01-27 at 13 20 38" src="https://cloud.githubusercontent.com/assets/883486/12613527/a1f65390-c4fa-11e5-8cac-1ca264abb483.png">

The code path that reaches to that point is the roughly the following:
```c
// Allocate buffer
size_t max_size = ...
void * buf = malloc( max_size );

// Create CQ
struct fi_cq_attr cq_attr = {
	.wait_obj = FI_WAIT_NONE,
	.format = FI_CQ_FORMAT_DATA,
	.size = fi->tx_attr->size
};
cq = /* Create CQ & Bind */

// Register MR with the endpoint
struct ofi_mr mr;
uint64_t access_flags = FI_RECV | FI_RECV | FI_REMOTE_WRITE;
int requested_key = 3;
fi_mr_reg( /* ep */ , buf, max_size, access_flags, 0, requested_key, 0, &mr, NULL );

// Post receive buffers
void *desc = fi_mr_desc( &mr );
fi_recv(  /* ep */, buf, max_size, desc, /* remote_fi_address */, /* rx_context */ );

// Wait for CQ event
struct fi_cq_data_entry entry;
while (1) {
	ret = fi_cq_read( cq, &entry, 1 );
	/* .. exit if (ret > 0), handle errors ... */
}
```

Would it be something that I am doing wrong? Or is this an optimisation feature that will come on the future version of the library?

**Comment by goodell** [comment]
`EP_MSG` and `EP_RDM` are currently implemented in software for the `usnic` provider.  Supporting true zero copy on RX for them will require firmware enhancements in the future.  I don't have a firm ETA for you on that, unfortunately.  Sorry if that wasn't clear from our earlier discussion :-/

**Comment by wavesoft** [comment]
Ah, I see. I thought it was only for the CQ-Related code, not for the Rx/Tx...
No problem, I will wait for an update then!

**Comment by goodell** [comment]
closing for now, we'll make sure to ping you when real zero-copy becomes an option
