### ISSUE TITLE
what's the deal with fi_av_open  and FI_AV_UNSPEC (sockets)

### ISSUE THREAD

**Issue by roblatham00** [ofiwg/libfabric#1671]
Consider some code like this:

     if (opts.dest_addr) {
        /* client */
        /* explicitly define version; don't use FI_MAJOR_VERSION or
         * FI_MINOR_VERSION.  */
        FI_CHECK(fi_getinfo(FI_VERSION(1,1), opts.dest_addr,
                opts.dest_port, 0, hints, &fi));
    /** slide 69 **/
    } else {
        /* server */
        /* node and service parameters are local addresses */
        FI_CHECK(fi_getinfo(FI_VERSION(1,1), opts.src_addr,
                opts.src_port, FI_SOURCE, hints, &fi));
    }
    ...
    fi_fabric(fi->fabric_attr, &fabric, NULL);
    fi_domain(fabric, fi, &domain, NULL);
    ...
    struct fi_av_attr av_attr = {};
    /* use av type optimal for provider */
     av_attr.type = fi->domain_attr->av_type;
    av_attr.count = 1;

    fi_av_open(domain, &av_attr, &av, NULL);

when I do this, the `av_attr` has 'av_type = FI_AV_UNSPEC', because this is my laptop and I guess sockets doesn't have a favorite kind of address vector?

but `sock_verify_av_attr()` gets angry at `FI_AV_UNSPEC` and returns `FI_EINVAL`

**Comment by shefty** [comment]
@jithinjosepkl 

Is 'fi' in the above example the output from fi_getinfo?

**Comment by roblatham00** [comment]
Yes.  I updated the code fragment with more context.  sorry for the omission.

**Comment by jithinjosepkl** [comment]
sock_verify_av_attr() shouldn't get angry with AV_UNSPEC. I will keep him calm.

**Comment by shefty** [comment]
AV_UNSPEC should not be allowed as input into fi_av_open.  That part seems correct.  What seems wrong is that fi_getinfo is returning that value as part of the domain_attr.

**Comment by jithinjosepkl** [comment]
Hmm, ok. av_type is not specified in domain_attr. (defaults to FI_AV_UNSPEC). Will update it.

But, Is there a reason why we shouldn't allow apps to pass in FI_AV_UNSPEC in av_open()?

**Comment by shefty** [comment]
Well, it's not documented as a valid type for fi_av_open.  :)  We could let the provider pick which option in the open call and report it back to the user.  But it seems cleaner to let fi_getinfo report that, rather than deferring the choice

**Comment by jithinjosepkl** [comment]
Yes, I noticed that in the av man page, and I was just wondering why :) May be that is the reason I didn't allow FI_AV_UNSPEC in sock_av_verify_attr.

Agree that it is cleaner to report av_type as part of fi_getinfo(). I will update it.

**Comment by goodell** [comment]
> What seems wrong is that fi_getinfo is returning that value [`FI_AV_UNSPEC`] as part of the domain_attr.

So what should a provider return if either option is supported with equal provider preference?  Presumably `FI_AV_TABLE` because I think application code written to work with `FI_AV_MAP` should work with an `FI_AV_TABLE` provider implementation but the opposite isn't necessarily true.

Sounds like some user might get confused by this though (e.g., "But I want `FI_AV_MAP` and it says it only supports `FI_AV_TABLE`!").

**Comment by shefty** [comment]
The provider can return whichever, but I agree that FI_AV_TABLE is the more generic choice.  However, the app has indicated that it doesn't care and will work with both.  I didn't follow how the user might get confused.  If they want AV_MAP, they should ask for it, not AV_UNSPEC.

**Comment by goodell** [comment]
> I didn't follow how the user might get confused. If they want AV_MAP, they should ask for it, not AV_UNSPEC.

You're right, there shouldn't be a way, I got something mixed up in my sequence of events.

**Comment by shefty** [comment]
After more discussion, we believe that the man pages are defining the correct behavior.  A domain can be opened with FI_AV_UNSPEC, but an AV cannot.  The changes to the sockets provider need to be reverted.

**Comment by jithinjosepkl** [comment]
@roblatham00 - Pasting a snippet from fi_domain man page for additional clarification.

Applications that require the use of a specific type of address vector should set the domain attribute av_type to the necessary value when calling fi_getinfo. The value FI_AV_UNSPEC may be used to indicate that the provider can support either address vector format. In this case, a provider may return FI_AV_UNSPEC to indicate that either format is supportable, or may return another AV type to indicate the optimal AV type supported by this domain.

**Comment by jithinjosepkl** [comment]
@shefty - Should we relax the attribute check for av_type = AV_UNSPEC in av_open()? Provider can return back the av_type using the type field in attr, and let app know about the av_type.

This will allow providers a way to pick the preferred AV_type.

**Comment by shefty** [comment]
That seems reasonable.

**Comment by roblatham00** [comment]
Then your tutorial needs a patch, but I don't know where the sources for it
are.

**Comment by shefty** [comment]
I think with merge #1685, the tutorial should be okay.  fi_av_open works with FI_AV_UNSPEC.
