### ISSUE TITLE
Should fd's be signaled by being marked as readable?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1674]
This is the current text regarding fd wait objects (EQ, CQ, wait sets):

File descriptor wait objects must be usable in select, poll, and epoll routines. However, a provider may signal an FD wait object by marking it as readable, writable, or with an error.

However, an fd may always be writable.  If an app tries to wait on an fd using POLLOUT, the wait may always return immediately.  Should we require signaling to mark the fd as readable?  I believe this is how the providers currently work.

**Comment by bturrubiates** [comment]
I'm having trouble coming up with a good argument for the use of POLLOUT.

:+1: to requiring the signaling marking the fd as readable. I think if anything it helps provide consistency in the API. All of the providers seemingly currently implement it that way and all of the fabtests making use of poll/epoll use POLLIN.
