### ISSUE TITLE
usnic: Post receive buffers once, receive 2 RX CQ events?

### ISSUE THREAD

**Issue by wavesoft** [ofiwg/libfabric#1693]
I see a weird behavior that does not really match what I am expecting to see (but this might be because I haven't understood something, so please bear with me in this case)...

On a usnic, `EP_MSG` endpoint, using `libfabric-1.2.0` I am:

1.  Posting my receive buffers using the: `fi_recv( endpoint, buffer, size, desc, addr, rx_context )`
2.  Waiting for a CQ event on a CQ bound with the `FI_RECV` flag on the endpoint
3.  Processing the data, and then calling (1) again.

That's because I assume that after the CQ event the 'new' receive buffers must be posted again, right?
However in my test set-up I sporadically see a second CQ event shortly after the first... and some times the message size reported by the CQ event is double the size of the message I sent!

Any ideas/suggestions?

_NOTE:_ There might be a thread-unsafe operation involved in this (`fi_recv` might be called by one thread, while another polling thread is receiving the CQ events). However even when I tried to call `fi_recv` from the polling thread but the problem persists. I am not sure if this could be the source of this problem?

**Comment by bturrubiates** [comment]
> That's because I assume that after the CQ event the 'new' receive buffers must be posted again, right?

That sounds correct. 



> However in my test set-up I sporadically see a second CQ event shortly after the first... and some times the message size reported by the CQ event is double the size of the message I sent!

So you're getting one that is the correct size, and one that is 2 * correct size at the receiver?

**Comment by wavesoft** [comment]
> So you're getting one that is the correct size, and one that is 2 * correct size at the receiver? 

Yes, that's correct.

Some additional info: I tried to ignore this message and let my program continue, and I realized that this only happens a few times in the beginning of the reception (right after `fi_connect`). In the same time it seems that the other end (the one doing `fi_listen`/`fi_accept`) has managed to successfully send a couple of messages (`fi_send` + waiting for a `FI_TRANSMIT` CQ event).

Depending on message size the remote end seems to squeeze a few thousand messages (when message size = 1kb) or just 1-2 messages (when message size = 32Mb).

Again, I am not sure if it's me doing something wrong.. any pointers?

**Comment by bturrubiates** [comment]
> Again, I am not sure if it's me doing something wrong.. any pointers?

I haven't seen this behavior and at the moment I can't think of why it would be happening. Do you think you could come up with a small reproducer that I could use to track this down?

**Comment by wavesoft** [comment]
I tried to scale it down to a simple nanomsg example, but I can't seem to reproduce the problem, so it's not much of a help : https://gist.github.com/wavesoft/ad795da73fd315c5a752

What I am really running is a [FairMQ Sampler](https://github.com/FairRootGroup/FairRoot/blob/master/fairmq/devices/FairMQBenchmarkSampler.cxx) and a [FairMQ Sink](https://github.com/FairRootGroup/FairRoot/blob/master/fairmq/devices/FairMQSink.cxx), which are some sample binaries that come with the default build of [FairMQ](https://github.com/FairRootGroup/FairRoot/tree/master/fairmq)... now, if you want to test this you will need to install [FairRoot](https://github.com/FairRootGroup/FairRoot) (FairMQ is part of it), that can quite tricky and thus I am not really sure if it worth spending the effort.

However after this experience it looks that FairMQ does something and causes this behaviour. From the top of my head I would say that something is not thread-safe or FairMQ `fork()`s somewhere after having nanomsg/libfabric initialised? 

For reference here is what I see (including backtraces from all threads) from the two nodes : https://gist.github.com/wavesoft/bf08d3b4e6e706425e57

The message `OFI: WARNING: Rx Buffer Overrun!` is displayed when an RX CQ event arrives unexpected.

**Comment by bturrubiates** [comment]
> I tried to scale it down to a simple nanomsg example, but I can't seem to reproduce the problem, so it's not much of a help : https://gist.github.com/wavesoft/ad795da73fd315c5a752

> What I am really running is a FairMQ Sampler and a FairMQ Sink, which are some sample binaries that come with the default build of FairMQ... now, if you want to test this you will need to install FairRoot (FairMQ is part of it), that can be quite tricky and thus I am not really sure if it worth spending the effort.

I'll try taking a look at the example and I'll also investigate setting that stuff up so I can help with debugging. Is the test involved high traffic? One thing I could think of is checking the debug output, but it can be quite verbose and useless if there are lots of messages flying around. It also requires re-compiling with `--enable-debug`.

**Comment by bturrubiates** [comment]
@wavesoft 

Can you see if this is still a problem on master as well? I couldn't reproduce this one.

**Comment by wavesoft** [comment]
I chose to refactor my code and pay more attention on thread safety, so unless I finish the new version and test it in production I cannot know. However since I am not sure what's really the culprit behind this issue you can close it and if I face it again with the new version I will open it again.

**Comment by bturrubiates** [comment]
> I chose to refactor my code and pay more attention on thread safety, so unless I finish the new version and test it in production I cannot know. However since I am not sure what's really the culprit behind this issue you can close it and if I face it again with the new version I will open it again.

Okay, that sounds good. Thanks! :tada:
