### ISSUE TITLE
fi_av_insert should report errors like every other routine

### ISSUE THREAD

**Issue by roblatham00** [ofiwg/libfabric#1705]
I'm sure there was a good reason for making `fi_av_insert()` report errors in a way different from every other libfabric routine.  Sorry, I''m just a dumb user of this library.  Besides, who checks return values?

fi_av_insert() has semantics  similar to posix write(2): you can ask it to insert N items but it might return fewer.  write(2) has the luxury of an errno.  In fi_av_insert's case, returning fewer means something went wrong, but how does the user figure out *what* went wrong? 

fi_av_insert should return an error code suitable for fi_strerror.  I don't have a satisfactory solution for the "how many succeeded" information -- it could take an additional output parameter where it can report how many `av`s were successfully inserted, but I'm not excited about that approach.   Could a routine be added to allow one to query the `fid_av` object ?

**Comment by shefty** [comment]
There was a very long discussion on the return value for fi_av_insert.  It differs from other calls in that it processes multiple insertions through a single call.  In the case of a failure, there is no guarantee that there's a single error code to return.  Theoretically, each address inserted could fail for a different reason, and there's no requirement that addresses be processed in the order that they are entered.  (AV insertion is designed this way to improve scalability.)  Applications can determine which addresses failed and the reason why by calling fi_av_insert as an asynchronous operation.  There's no way to provide this information in a general way using a synchronous call.  Support for a blocking fi_av_insert was added for ease of use, at the cost of losing error information.

I did not follow the request to query the fid_av object.

**Comment by roblatham00** [comment]
thanks for the background info. 

yeah, wuerrying the fid_av object is probably a dumb idea.  was thinking of some way the environment could report to the user what happened.  this would require something like an "array of errno for the last operation" attached to the fid_av_object.    I'm probably thinking about this in a too-MPI kind of way.

**Comment by shefty** [comment]
A non-programmatic option is to enable warning log messages for libfabric or the AV.
