### ISSUE TITLE
CQ/EQ error handling

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1723]
The size of the CQ/EQ isn't clearly defined. Does an error event count against the size of an EQ? Say I have a queue of size 1024, does that allow for 1024 entries _and_ 1024 errors? Or does that only allow for 1024 total entries including both errors and events?

This also effects the error handling since events can be inserted into the queues asynchronously. If a queue becomes overrun, then it should generate an error entry stating that the queue has been filled. What happens on asynchronous events after this error has been generated? Do all subsequent events get dropped, or does it override previous events? What should the app expect in this situation?

@shefty @jsquyres

**Comment by shefty** [comment]
The intent is to define the size as the total number of entries.  Error entries are treated as a conceptual queue, not a real one.

We cannot dictate what happens on a queue overrun without dictating the implementation.  What is defined is resource management.  If enabled, the provider is responsible for avoiding queue overruns.  If disabled, the app must ensure this by restricting the number of possible events that could be written to the queue.

We can define a queue overrun event, but even the generation of that places a burden on the implementation.  I can envision hardware not being able to detect this.  If so, is this something that software could always detect?

**Comment by jsquyres** [comment]
@shefty The situation came up in an application here at Cisco -- the usNIC BTL in Open MPI erroneously overran the EQ by issuing too many fi_av_insert()s.  I have since fixed OMPI to do not that any more -- but the question remains: how is a user notified of an EQ overrun?  It seems like a reasonable thing to report -- even if the purpose is to tell developers, "hey, dummy, you overran your EQ -- fix your app!"

**Comment by bturrubiates** [comment]
> The intent is to define the size as the total number of entries.  Error entries are treated as a conceptual queue, not a real one.

That's good to know. I think that should be clarified in the man pages. The error entries are manipulated using a separate interface so they almost feel as if they're an entirely different queue in the implementation. 

> We cannot dictate what happens on a queue overrun without dictating the implementation.  What is defined is resource management.  If enabled, the provider is responsible for avoiding queue overruns.  If disabled, the app must ensure this by restricting the number of possible events that could be written to the queue.

So if resource management is enabled, then the provider basically has to keep track of the worst case number of events something could generate and not allow posting/inserting if it deems that the worst case could result in an overrun?

**Comment by jsquyres** [comment]
@shefty When you say:

> The intent is to define the size as the total number of entries. Error entries are treated as a conceptual queue, not a real one.

Does that mean that if you define an EQ queue size of X, I can only do (X/2) fi_av_inserts() that are asynchronous, because each one of them may enqueue both an error event *and* a non-error event?

**Comment by shefty** [comment]
I guess the first thing to figure out is how one could report an EQ overrun.  As long as an EQ overrun can be detected by the provider, it can report the overrun using a made-up EQ event.  I just don't know if IB/iWarp HW can detect EQ overruns.  (They do detect CQ overruns.)

With RM enabled, yes, the provider needs to ensure that queues will not overrun.  Although I would exempt a provider from needing to ensure that a reasonable malloc call in the future will not fail.  But, as an example, the UDP provider reserves a CQ entry when posting a send.

With RM disabled, an app needs to take care to avoid overrunning the EQ, but we haven't gotten to a generic event subscription mechanism yet.  That will present a problem.  Jeff, in the case you mentioned, the app is probably dead in the water once it gets a single failure, let alone having x/2 failures.  So I don't know that it will care about an EQ overrun once so many failures have been reported.

**Comment by jsquyres** [comment]
@shefty Not necessarily. For example, Open MPI was using `fi_av_insert()` to determine reachability of peers -- it would either get back an address or an FI_ADDR_NOTAVAIL.  In libfabric-speak, getting FI_ADDR_NOTAVAIL is an error (and therefore requires both an error EQ entry and a non-error EQ entry), but to Open MPI, it just means "try some other route / network / etc. to get to that peer."

**Comment by jsquyres** [comment]
@shefty So is the answer to this: libfabric does not define what happens when an EQ is overrun?

**Comment by shefty** [comment]
I would go with defining it as fatal to the EQ, with all future EQ reads reporting an error.

**Comment by jsquyres** [comment]
@shefty Sounds reasonable to me.

@bturrubiates Do you want to adjust usnic to behave accordingly?

**Comment by bturrubiates** [comment]
> I would go with defining it as fatal to the EQ, with all future EQ reads reporting an error.

Is there an option for recovery? 



> @bturrubiates Do you want to adjust usnic to behave accordingly?

Sure

**Comment by shefty** [comment]
> Is there an option for recovery?

How can you recover?  Events were lost.

**Comment by bturrubiates** [comment]
> How can you recover?  Events were lost.

Well, it sounds like you're suggesting effectively disabling the queue. You stated 'all future EQ reads reporting an error', but there isn't a defined error event for this scenario. If an app attempts to read the error that the EQ is reporting, then what is the expected behavior?

**Comment by shefty** [comment]
Yes, I'm suggesting disabling the queue having fi_eq_read() return something like -FI_EOVERFLOW or -FI_EFATAL.  No event, the queue has been overrun and should be considered corrupted.

That doesn't mean that a provider couldn't return whatever events were queued before the overrun occurred, provided that they weren't corrupted.  But once returning -FI_EOVERRUN, the queue is dead, Jim, dead.

**Comment by bturrubiates** [comment]
> Yes, I'm suggesting disabling the queue having fi_eq_read() return something like -FI_EOVERFLOW or -FI_EFATAL.  No event, the queue has been overrun and should be considered corrupted.

Whenever we encounter a situation where we can't enqueue anymore, then we set the state of the queue to disabled. All writes after that fail with `-FI_EOPBADSTATE` and the reads will continue returning events as normal until empty where it will return `-FI_EOPBADSTATE`.

For queues configured with an FD the enqueue itself may succeed, but the write/notify of the FD fails. In this case, rollback the queue and disable it. The return status will reflect the failure with a `-FI_EIO`. After this the queue will behave as expected from the disabled state (`-FI_EOPBADSTATE` on writes and final read).

@shefty How does that sound? If we agree, I can update the relevant man pages.

**Comment by shefty** [comment]
> Whenever we encounter a situation where we can't enqueue anymore, then we
> set the state of the queue to disabled. All writes after that fail with -
> FI_EOPBADSTATE and the reads will continue returning events as normal
> until empty where it will return -FI_EOPBADSTATE.

This may not work with a HW based EQ.  Once the queue is overrun, it is corrupted and older events may be lost.  The overrun may only be detected by software when reading from the queue, not by the hardware before writing to it.

We need to make sure that we don't define a behavior that cannot be met without requiring a specific implementation of an EQ.

**Comment by bturrubiates** [comment]
> This may not work with a HW based EQ.  Once the queue is overrun, it is corrupted and older events may be lost.  The overrun may only be detected by software when reading from the queue, not by the hardware before writing to it.

Alright, so what this suggests to me is that it might be up to the provider to define the validity of the existing events in this situation.

> We need to make sure that we don't define a behavior that cannot be met without requiring a specific implementation of an EQ.

I agree.
