### ISSUE TITLE
Rename "sockets" provider "tcp"?

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1751]
Now that there is a "udp" provider, should the "sockets" provider be renamed "tcp"?

**Comment by bturrubiates** [comment]
:+1:

**Comment by rfaucett** [comment]
No, because it will not inter-operate with a sockets TCP program.  A provider named "tcp" would imply a user-space implementation of the TCP stack,

**Comment by bturrubiates** [comment]
> No, because it will not inter-operate with a sockets TCP program. A provider named "tcp" would imply a user-space implementation of the TCP stack,

Doesn't that depend on the way the name is interpreted? The "verbs" provider isn't an implementation of verbs.

**Comment by jsquyres** [comment]
@rfaucett Fair enough; the 'udp' provider's DGRAM does interop with a POSIX UDP-based application.  But it won't interoperate with RDM and MSG.

**Comment by shefty** [comment]
The name of the provider and the name of the protocol are somewhat independent.  The UDP provider also exports UDP as a protocol.  When MSG and RDM support are added, those will come under a different protocol.  The provider name in that case _could_ change.  I would branch predict that it will -- maybe 'utility' provider or 'util-udp'?  We should figure out what to name the provider when it's a layering of utility functions over an existing provider.

I thought about renaming the sockets provider, but I don't think we want to do that as applications may already be coded to select or check for the sockets provider by name.

**Comment by jsquyres** [comment]
On February 16, 2016 at 12:51:18 PM, Sean Hefty (notifications@github.com) wrote:
> The name of the provider and the name of the protocol are somewhat independent. The UDP
> provider also exports UDP as a protocol. When MSG and RDM support are added, those will
> come under a different protocol. The provider name in that case _could_ change. I would
> branch predict that it will -- maybe 'utility' provider or 'util-dup'?

Ok.  I only mention this because of the dichotomy of "udp" vs. "sockets".  I agree we need a better naming scheme; it would probably be good to lock that in sooner rather than later (i.e., so that a huge number of users don't get used to the old name such that you can't change it -- Open MPI has an "openib" component for exactly this reason).  I think you point out exactly this same issue below...

> We should figure
> out what to name the provider when it's a layering of utility functions over an existing
> provider.

Does that matter?  E.g., I don't really intend to rename the usnic provider if it uses some of the util functionality.

> I thought about renaming the sockets provider, but I don't think we want to do that as applications
> may already be coded to select or check for the sockets provider by name.

I'm not a fan of udp->util-udp because UDP will be only one of the protocols that it speaks (e.g., RDM and MSG won't be FI_PROTO_UDP).

Maybe "udp" could be renamed to:

- util
- basic
- emulated
- tyrannosaurus
- ...?

--
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by shefty** [comment]
> Does that matter?  E.g., I don't really intend to rename the usnic
> provider if it uses some of the util functionality.

I'm referring to a provider that layers over OFI to provide extended functionality.  For example, Jithin is working on an RDM over UD EP implementation.  The UD EP can come from the UDP provider or verbs provider (once IB UD support is added).  The RDM piece doesn't care, nor does it require changes to the underlying providers to just work.  What do we call that provider?  Maybe it just reports the same name as what it's layered over.

**Comment by jithinjosepkl** [comment]
I was thinking of calling it as "rdmx". But we may want it to have a dgram tag as well. May be "rdm-dgram"?

**Comment by jsquyres** [comment]
I don't quite understand... this is to be a new provider that includes FI_EP_DGRAM and FI_EP_RDM functionality?

I don't think the type of endpoint(s) supported should be in the provider name, should they?

**Comment by jithinjosepkl** [comment]
No, this is for a provider that supports RDM endpoint, that is implemented over OFI FI_EP_DGRAM endpoints.

**Comment by jsquyres** [comment]
What's the use case for this?  Is it for providers that do not support FI_EP_RDM themselves?  If so, wouldn't it be less confusing to have those providers support FI_EP_RDM directly (even if they choose to layer themselves over util/ functionality)?  E.g., we're currently evaluating whether we'd want to ditch usnic's emulated RDM / MSG functionality for something in util when the back-end usNIC hardware doesn't support it natively.

**Comment by jithinjosepkl** [comment]
Yes, this is for providers that do not support FI_EP_RDM. Providers can implement these themselves too, but the downside is that every provider (that do not have the capabilities) will have to do this. Whereas the emulated RDM provider does it for all.

The idea is to reuse features available in the util-provider and to provide RDM support over DGRAM endpoints. I hope to add new features to util-provider as the emulated provider is being implemented.

**Comment by shefty** [comment]
From the original question, I think we need to leave the name of the provider as is, or we risk breaking users that rely on accessing the provider by name.
