### ISSUE TITLE
Provider maximum resources parameters missing

### ISSUE THREAD

**Issue by moshevolo** [ofiwg/libfabric#1757]
There are few oarameters that are missing in the capabilities:
Maximun number of tags
Max number of triggered operations
Max number of unexpected headers
Max number of counters

**Comment by sayantansur** [comment]
Max tags -> fi_ep_attr::mem_tag_format
Max number of triggered ops -> I believe this is covered by EAGAIN usage model. Not sure if fi_tx_size_left() etc. applies or not. IMHO EAGAIN model is sufficient for MPI.
Max unexpected headers -> This is not exposed, and that was a conscious choice. The functionality should be available through FI_RM_ENABLED.
Max number of counters -> I believe this can be added to fi_domain_attr. There is a cq_cnt, ep_cnt, and maybe it is reasonable to have ct_cnt as well.

**Comment by shefty** [comment]
This is somewhat of a side note, but I agree with Sayantan on EAGAIN.  The size_left functionality is proving to be unimplementable in certain situations without a significant amount of overhead.

As for the max number of triggered ops, I can envision a use case for it as input into the provider.  Currently, the provider has no way of knowing how many an application may want to queue, other than using the basic EP tx/rx size values.  This may be sufficient input, however.  For example, we don't break the size down by max rma reads, max rma writes, max tagged sends, max msg sends, etc.  Too many attributes just becomes noise.

Note that we've tried to avoid terms like 'max'.  Instead, we've tried to report the 'optimal' number based on the application request and system defaults.  Max values tend to be abused and result in inefficient application implementations.

**Comment by moshevolo** [comment]
Sayantan,

fi_ep_attr::mem_tag_format describe the tag format but not the total number
of tags the provider supports.
fi_tx_size_left may apply to triggered ops if they are all on a same
queue... not sure if this sufficient

Moshe

**Comment by sayantansur** [comment]
> The mem_tag_format optionally begins with a series of bits set to 0, to signify bits which are ignored by the provider.

If the leading n bits are 0, then the max tag supported is 2^(64-n).

Re. the triggered ops, why isn't EAGAIN model sufficient? See Sean's comments on fi_tx_size_left().

**Comment by moshevolo** [comment]
The mem_tag_format can be used the way you wrote but I refer to potential HW limit where there

are limited number of tags that can be stored in HW. That number would be much smaller…

 

Even with EAGAIN model there is still fi_tx_size_left which tells a minimum number of operation that would

not return EAGAIN. Sean is correct of course that we do not want max_ on every type message. triggered though

could be argued to be a special type message which is not executed simply in order. Thus there might be HW resources

associated with those and thus it would make sense to the total outstanding triggered ops the HCA supports.

 

Moshe

**Comment by sayantansur** [comment]
Regarding the tags, I'm not still 100% clear as to what limit you're asking about. Are you talking about the outstanding tag queue depth. This is the queue a tag matching provider has to maintain for posted receives for example.

I don't know how to implement fi_tx_size_left() in several different types of fabrics. A provider that doesn't support fi_tx_size_left() can just return ENOSYS. However, this could lead to the app failing if the app doesn't handle EAGAIN.

@shefty Not sure how to address this. Does there need to be something in libfabric to handle EAGAIN vs. fi_tx_size_left() model?

**Comment by shefty** [comment]
I don't know how to handle the size_left call either.  My inclination wants to deprecate the call.  It just can't easily be implemented in many cases without significant overhead, and can restrict implementations.  Not all provider software has that level of control over resources.

**Comment by shefty** [comment]
The 1.5 API deprecates the size_left() API.  The only model exposed is now EAGAIN.  All other options imply a specific hardware implementation.  In fact, size_left() was added because the endpoint size field also implied a hardware implementation, and size_left() was an attempt to work around that.

cntr_cnt was added as a domain attribute.
