### ISSUE TITLE
Need fork support

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1763]
This is a general issue about what to do for fork support.  Specifically, the verbs provider does not handle users calling fork.  Doing so requires either setting an environment variable or calling ibv_fork_init.

There is overhead to always assuming that an application will call fork.  Should libfabric expose some sort of control option or capability that an app can use to indicate that fork support is required?

We need input from at least one other provider on whether it can handle fork and how.

**Comment by hppritcha** [comment]
The GNI provider handles fork via a special cow-support feature (which i believe uses i/o mmu notifier support in the kernel) which is added to Cray Linux.  A device driver can use this feature to help deal with COW problems associated with memory registered with the NIC's I/O MMU.  An application can specify whether it wants a complete copy of private regions of parent that were registered with the NIC, or no-copy, or copy of only the first and last pages of the region.

**Comment by shefty** [comment]
For GNI, then it expects the application to notify the provider/driver that it intends to use fork, plus provide additional details regarding page handling?

**Comment by hppritcha** [comment]
Not explicitly if the partial copy is good enough.  That's the default policy used by craypich (Cray mpi) and I think Cray shmem.  That should be the same for the GNI provider.  Experience with ISVs apps indicated the partial copy policy covered most cases.  This policy tended to add little to fork overhead.  Some problematic apps needed full copy.  For those apps a craypich/Cray shmem env variable had to be set.  I think we have an open ops method on the domain for gni provider to handle this.  If not we will add one.

Hpc hats should be removed for this one.  Having weird issues with fork is not good for data center app,  or even no hpc mpi apps.  I think most of the fork problems cray had to deal with were with isv apps that used popen etc a lot.

**Comment by goodell** [comment]
FWIW, whatever we decide on that works for verbs should work for usnic as well.

To Howard's observation:
> Hpc hats should be removed for this one. Having weird issues with fork is not good for data center app, or even non hpc mpi apps.

To the extent it's possible for us to avoid weird restrictions, I totally agree.  Though HPC is a key client for libfabric, I would really like to see adoption in other areas as well and issues like this tend to make non-HPC folks look at us like we are crazy.

**Comment by shefty** [comment]
Here are a few options:

1. Support fork by default.  Allow apps to disable it.  Gives bad performance out of the box, but works with more apps.
2. Disable fork by default.  Allow apps to enable it.  Better performance, but more work for non-HPC apps, which as a group I would generally consider as less sophisticated than HPC apps.
3. Build time configure option.  Still need default behavior.

Unless we go with a build option, I'd hate to say this, but an environment variable seems like the best option.  A lot of apps may call fork indirectly.  For this discussion, 'supporting fork' just means not crashing.  There's no expectation that fabric resources be usable by child processes.

**Comment by jsquyres** [comment]
FWIW, I think it's fine to have MPI implementations and other HPC-oriented libraries to disable fork support (i.e., enable it by default in order to gain traction in a larger application base).

**Comment by goodell** [comment]
I prefer option (1) with the environment variable override (`$FI_I_PROMISE_NOT_TO_FORK`? :wink:).

> For this discussion, 'supporting fork' just means not crashing. There's no expectation that fabric resources be usable by child processes.

Agree on this.

**Comment by bturrubiates** [comment]
> Support fork by default. Allow apps to disable it. Gives bad performance out of the box, but works with more apps.

This sounds like the best option. It would need to be very clearly stated to avoid complaints. What's the expected interface for disabling it? Would this be a new capability?

**Comment by shefty** [comment]
@a-ilango - can you look at enabling fork support by default for the verbs provider?

@evgeny-leksikov - would this cause any issues with you?

**Comment by evgeny-leksikov** [comment]
> Gives bad performance out of the box

How I can check expected performance? Is setting of env variable IBV_FORK_SAVE enough?

**Comment by a-ilango** [comment]
@shefty Sure, I can take look into it.

**Comment by shefty** [comment]
> How I can check expected performance? Is setting of env variable IBV_FORK_SAVE enough?

Yes

**Comment by evgeny-leksikov** [comment]
@shefty I do not see any performance deviations from this variable on my system. So, I have no objections.
