### ISSUE TITLE
segfault in fi_getinfo

### ISSUE THREAD

**Issue by tschuett** [ofiwg/libfabric#1769]
I have the sockets, verbs, and psm providers and the following code leads to a segfault

``` cpp
struct fi_info *info;
struct fi_info *hints = fi_allocinfo();

hints->src_addrlen = 8;

int res = fi_getinfo(FI_VERSION(1,0), NULL, 0, 0, hints, &info);
assert(res == 0);
```

in fi_ibv_fi_to_rai. For the memcpys, it doesn't check whether  [src,dest]_addrlen != 0 and [src,dest]_addr == NULL. It should also check whether  [src,dest]_addrlen are correct (16?).

**Comment by sayantansur** [comment]
It might be helpful if the framework did some basic error checking before passing on the getinfo call to the providers.

**Comment by shefty** [comment]
The framework does some, which could be expanded.  The utility code adds more checks, and all providers should begin migrating to use that.

**Comment by shefty** [comment]
This is invalid input, and has not been a real issue for apps in the 4 years that this was opened.
