### ISSUE TITLE
Eliminate any environment variables

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#177]
Environment variable support is basically the same as supporting a function API.  Once exposed, there will be an expectation that it is supported moving forward.  See if we absolutely need to support any environment variables.

**Comment by sayantansur** [comment]
Can we have one environment variable that specifies a config file name? That way it is still pretty handy to have a per job setting.

One problem I've faced with env vars is that while I can set one (or a few) easily, it is not easy to know all variables that are set for a given run. Maybe all users don't care about this, but in a world with many conflicting variables, setting one or a few is not a good idea per se.

**Comment by shefty** [comment]
My preference is to replace most environment variables with config files.

**Comment by hppritcha** [comment]
Could we retain the FI_LOG_LEVEL, FI_LOG_PROV, and FI_LOG_SUBSYS too?  

Otherwise I vote for the config file approach for other parameters.  Here I would caution about
allowing too many parameters in.  I work on another project where the number of somewhat documented parameters has really gotten out of control - there are 100s of them.  Just maintaining and deprecating, and documenting deprecation, etc. can become a big overhead.

I would think that "parameters" should typically be something that the direct consumer of the
libfabric API can select via either the existing attributes structures, or in the case of something
provider specific, via methods returned by ```ops_open```.  The direct consumer of the libfabric API
can then provide means specific to their software for adjusting libfabric parameters.

**Comment by shefty** [comment]
> Could we retain the FI_LOG_LEVEL, FI_LOG_PROV, and FI_LOG_SUBSYS too?

I think these are perfect candidates for environment variables.  TIME_TO_SPIN_BEFORE_SLEEPING - not so much.

**Comment by jsquyres** [comment]
Per discussion on the call today, the proposal is now:

```c
/* Registers an environment variable for use with libfabric.
 *
 * Example: fi_register_envvar("usnic", "FOO", "Very important help string");
 *
 * This registers $FI_USNIC_FOO.  The provider name should either be "core" or match an
 * existing provider's name (i.e., be lower case).  The resulting env variable name will be all
 * upper case.  The help string cannot be NULL or empty.
 */
int fi_register_envvar(const char *provider_name, const char *var_name, const char *help_string);

/* Get the value of an env var.
 *
 * This call is basically a wrapper around getenv(), but can also check for that env var in a config
 * file (the config file value would have a higher precedence than the results of getenv()).
 * It will also check to ensure that the env variable name was previously registered via
 * fi_register_envvar().
 */
const char *fi_get_envvar(const char *name);
```

**Comment by shefty** [comment]
Looks good

**Comment by jsquyres** [comment]
FWIW: I forgot about the "it can/could also read from a file" aspect of the "get" function.  I think that makes the "get" function worthwhile.  I might actually drop "env" from the function names -- we can treat them as libfabric configuration variables; they happen to be exposed/settable via the environment and/or a config file.

**Comment by pmmccorm** [comment]
What about taking a "struct fi_provider" vs a const char* to match the logging calls and to ensure that environment vars always are either core or some provider?

**Comment by jsquyres** [comment]
Sure (we do something similar in Open MPI for registering configuration variables).

What would core variables pass for the (struct fi_provider*) parameter -- NULL?  If so, I'm good with that.

**Comment by shefty** [comment]
The core uses an fi_provider structure that allows it to plug into the calls (e.g. log messages) the same as providers.  This avoids needing any special handling between the core and a provider.  See fabric.c.

**Comment by jsquyres** [comment]
Perfect.

**Comment by jsquyres** [comment]
See PR #1055 for how this worked out.

**Comment by jsquyres** [comment]
Future comments can be made on #1055.
