### ISSUE TITLE
Travis build on Linux broken

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1773]
```bash
if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    git clone git://www.openfabrics.org/~shefty/librdmacm.git
fi

Cloning into 'librdmacm'...
fatal: unable to connect to www.openfabrics.org:
www.openfabrics.org[0: 69.55.231.73]: errno=Connection refused
```

@shefty Is `librdmacm` still located  there?

**Comment by shefty** [comment]
> if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
>     git clone git://www.openfabrics.org/~shefty/librdmacm.git
> fi
> 
> Cloning into 'librdmacm'...
> fatal: unable to connect to www.openfabrics.org:
> www.openfabrics.org[0: 69.55.231.73]: errno=Connection refused
> 
> @shefty <https://github.com/shefty>  Is librdmacm still located there?

It is still there, but the server is being replaced.  I moved the librdmacm.git tree to github under the ofiwg project last week when the OFA server went down.

**Comment by bturrubiates** [comment]
> It is still there, but the server is being replaced.  I moved the librdmacm.git tree to github under the ofiwg project last week when the OFA server went down.

Oh okay, should I submit a pull request to update the Travis configuration file so it pulls from Github instead?

**Comment by shefty** [comment]
Please -- update to https://github.com/ofiwg/librdmacm.git

**Comment by bturrubiates** [comment]
Will do.
