### ISSUE TITLE
Verbs provider fails to build on OFI build machine

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1799]
The verbs provider is failing to build on Ubuntu 14.04.4, which is the new OS installed on flatbed.openfabrics.org (it used to be a RHEL server).

It looks like this version of Ubuntu installs librdmacm 1.0.16.

The current verbs provider configure.m4 looks for the "riowrite" symbol in librdmacm, which doesn't seem to exist in librdmacm 1.0.16.  But I noticed that this symbol is not used anywhere in the verbs provider, so I made the following change:

```patch
diff --git a/prov/verbs/configure.m4 b/prov/verbs/configure.m4
index 8564f22..87665eb 100644
--- a/prov/verbs/configure.m4
+++ b/prov/verbs/configure.m4
@@ -25,7 +25,7 @@ AC_DEFUN([FI_VERBS_CONFIGURE],[
               FI_CHECK_PACKAGE([verbs_rdmacm],
                                [rdma/rsocket.h],
                                [rdmacm],
-                               [riowrite],
+                               [rdma_create_qp],
                                [],
                                [$verbs_PREFIX],
                                [$verbs_LIBDIR],
```

This allows it to get past configure, but then compilation fails because RAI_FAMILY is not found in the rdmacm header files.

Can someone figure out a way forward here?  I.e., either decide that you don't care about not building on Ubuntu 14.04.4 (and, in this case, no longer get Coverity coverage of the verbs provider), or adjust the verbs provider to be able to build with this assumedly older version of librdmacm.

**Comment by shefty** [comment]
Can't we just install a newer version of the librdmacm on the system?

**Comment by jsquyres** [comment]
That seems to be the version that ships with Ubuntu 14.04.4; the OS itself doesn't provide an update.  So I guess there's three choices:

1. If you care about customers with Ubuntu 14.04.4 LTS (which is the "long term support"), then update libfabric to be able to handle this older version of librdmacm.  I don't know the verbs provider's caring level about Ubuntu/Debian.
1. Skip building the verbs provider.  This doesn't seem like a good idea.
1. Install a new librdmacm somewhere.  This would work, but doesn't address the first bullet.

If people don't care about Ubuntu, then the 3rd option is probably the best one.

**Comment by a-ilango** [comment]
The decision to add this check in configure was made in #1553 . If we plan to go with option 1, verbs provider would need to drop support for AF_IB addresses if RAI_FAMILY is not defined. That check would have to be added in the provider to make sure it builds fine.

**Comment by jsquyres** [comment]
@a-ilango You could disable this functionality of RAI_FAMILY isn't available (i.e., check for it via configure).

**Comment by shefty** [comment]
The verbs provider could add the missing define (#define AF_IB 27) if it is not available.  This would avoid the code needing to change.  Use of AF_IB can fail anyway, if not supported by the kernel.  You may need to ifdef out the include for infiniband/ib.h based on the build options.

**Comment by a-ilango** [comment]
@shefty if the OS doesn't have the version of rdmacm that has AF_IB defined, how likely is it for the kernel to not have it either? Are the kernel rdmacm support and user rdmacm library updated in lockstep? If not, may be we just need to throw an error if the app tries to use AF_IB and it is not defined.

**Comment by shefty** [comment]
The problem is that you can't even build until it has been defined.  :)  So you either need to check for the define and #ifdef the code that tries to use it, or just define it.

The kernel and user space libraries are not in sync.  If the librdmacm does not know about AF_IB, it will throw an error if it sees af_family = 27.  I don't think the value will even make it to the kernel.  So from the perspective of libfabric, adding the missing define is probably sufficient and avoids needing the #ifdef the code.

**Comment by a-ilango** [comment]
Okay. I'll add the #define for AF_IB if it isn't defined already. Will submit a PR soon.
