### ISSUE TITLE
Generate web versions for alias man pages.

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1807]
See #1796 for the discussion.

**Comment by bturrubiates** [comment]
@jsquyres @shefty 

I looked into this a little bit more since it would be nice to have it fixed for the next release. How do the man pages currently get placed into the `gh-pages` branch? Is that manual? So I see a couple of options: 

1. We could symlink the alias pages (like `fi_ep.3.md` -> `fi_endpoint.3.md`). This isn't ideal if we care about things like caching and search engines. 
2. Using the ruby gem `jekyll-redirect-from` we can specify redirect points in the markdown files. So in `fi_endpoint.3.md`:

    ```
    ---
    redirect_from: "v1.2.0/man/fi_ep.3.html"
    ---
    ```

    This would respond with an HTTP 301 anytime `fi_ep.3.html` is requested and serve `fi_endpoint.3.html`. You can read more about `jekyll-redirect-from` [here](https://help.github.com/articles/redirects-on-github-pages/).

Do either of these sound like something we want to do?

**Comment by jsquyres** [comment]
For master, the web pages are currently put into the gh-pages branch via a cron script run on the flatbed.openfabrics.org server.  

* [The cron script is here](https://github.com/ofiwg/libfabric/blob/master/config/cron-run-all-md2nroff.pl). 
* [The crontab line that fires it is here](https://github.com/ofiwg/libfabric/blob/master/config/ofiwg-bot%40flatbed-crontab.txt).

For each release, we copy the master man page dir into the release man page dir (on gh-pages) manually.

So -- to be clear -- we're talking here on this issue about the auto-generation of man pages from master via cron.

IIRC. all the man pages that nroff-redirect to other man pages (e.g., `fi_tostr.3` contains a single line, `.so man3/fi_fabric.3`) were created manually.  If the current script can find those and generate relevant `.md` files that do a ruby/gem redirect to the right html file, that sounds great.

**Comment by bturrubiates** [comment]
> IIRC. all the man pages that nroff-redirect to other man pages (e.g., fi_tostr.3 contains a single line, .so man3/fi_fabric.3) were created manually. If the current script can find those and generate relevant .md files that do a ruby/gem redirect to the right html file, that sounds great.

It doesn't need to create anything, just needs to add the `redirect_from` line to the right `.md` file. Actually, is there any problem with just adding the `redirect_from` to the jekyll front matter on each `.md` file? It's simpler, but anytime we add an alias we would have to add a  `redirect_from` line on the appropriate `.md` file.

**Comment by shefty** [comment]
While this is nice to have, I don't consider it a requirement for the 1.4 release.  Removed milestone

**Comment by shefty** [comment]
The current web pages appear to be working fine without creating a hoard of redirecting pages.
