### ISSUE TITLE
Skipping CI for some changes

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#1818]
Travis CI has a skip build option for changes that may not require it. e.g. Editing a man page entry. To skip a build one just needs to add the text "[ci skip]" in the commit message.

Is this something that would be of interest to us?

More info at https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by shefty** [comment]
I gave this some thought, and given that the majority of our PR are to code itself, I don't think it's worth worrying about those changes causing a new travis test run.  Plus, we often see that those runs result in a failure, which means that there are errors in the code that weren't caught by a previous run.

**Comment by a-ilango** [comment]
Thanks. That makes sense. I'm closing this issue.
