### ISSUE TITLE
Calling fi_cq_read with a NULL buf pointer and count of 0

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1824]
While looking through the utility code I noticed [this](https://github.com/ofiwg/libfabric/blob/b3beebec25d981311dafd6df15049e3cc11f9f19/prov/util/src/util_poll.c#L94) line in the utility poll implementation. It seems to assume that a call to `fi_cq_read` with a `NULL` buffer pointer and a count of `0` will return `-FI_EAGAIN` if there is nothing to read and `FI_SUCCESS` if there is. Am I interpreting that correctly? 

The issue here is that with the current implementation of the usNIC provider, a return value of `FI_SUCCESS` from such a call does not suggest anything about the state of the queue. If it should be returning `FI_SUCCESS` only upon  an entry being available, then I can update appropriately. This could still work, but it would mean that if a provider didn't follow that behavior then poll would have false positives.

I think it is also useful to document this in the man pages. This seems to be used in place of a call to `fi_cq_read` with `FI_PEEK` set (since this isn't part of the API, should it exist?).

@shefty @goodell

**Comment by shefty** [comment]
See fi_util.h.

/*
 * Completion queue
 *
 * Utility provider derived CQs that require manual progress must
 * progress the CQ when fi_cq_read is called with a count = 0.
 * In such cases, fi_cq_read will return 0 if there are available
 * entries on the CQ.  This allows poll sets to drive progress
 * without introducing private interfaces to the CQ.
 */

This was done to avoid needing a separate call to handle the case of driving progress.  I intentionally did not document this in the man pages.  In this case, the return value is 0, indicating the 0 completions were returned, and not FI_SUCCESS.  0 is not a valid documented return code for fi_cq_read.

**Comment by bturrubiates** [comment]
> This was done to avoid needing a separate call to handle the case of driving progress. I intentionally did not document this in the man pages. In this case, the return value is 0, indicating the 0 completions were returned, and not FI_SUCCESS. 0 is not a valid documented return code for fi_cq_read.

Oh right, thanks. That clears things up for me. :+1:
