### ISSUE TITLE
FI_EP_DGRAM - what primary capabilities should be supported by a provider

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1841]
We've implement FI_EP_DGRAM in gni provider.  Currently the plan is to support  FI_MSG, FI_RMA, FI_TAGGED, and FI_ATOMIC primary capabilities.  Its not clear from the man pages whether or not there are suppose to be restrictions on the primary capabilities for FI_EP_DGRAM.

Are there?

**Comment by shefty** [comment]
There's not any intent to restrict what could be implemented using DGRAM EPs, but I really don't think it makes sense to support anything other than MSG.  There definitely aren't any plans to have anything other than that as part of the general utility framework.  I have a hard time imagining an application use case for DGRAM RMA or atomics.

**Comment by hppritcha** [comment]
Okay.   Perhaps  this should be pointed out in the fi_endpoint man page.
