### ISSUE TITLE
Non-x86 support

### ISSUE THREAD

**Issue by opoplawski** [ofiwg/libfabric#1842]
libfabric 1.2.0 fails to build on non-x86 platforms with:
~~~~~
In file included from prov/verbs/src/ep_rdm/verbs_rdm.h:37:0,
                 from prov/verbs/src/verbs_rma.c:38:
prov/verbs/src/ep_rdm/verbs_utils.h:50:23: fatal error: xmmintrin.h: No such file or directory
~~~~~
Is there any desire to support non-x86 platforms, or should I limit the Fedora package to x86?

**Comment by shefty** [comment]
There is no intent to restrict libfabric to x86 only.  The verbs RDM support will likely be replaced by a more generic utility RDM provider (under development).  At the very least, if the verbs RDM cannot be made to work on non-x86 platforms, it should simply be disabled, not break the build.

**Comment by shefty** [comment]
@evgeny-leksikov @a-ilango - Can someone please take a look at this?  Ideally, a non-x86 version of whatever the code needs should be added.

**Comment by evgeny-leksikov** [comment]
Sure, I'll see. It shouldn't be a problem.

**Comment by opoplawski** [comment]
Works great, thanks.
