### ISSUE TITLE
Port does not always get auto-assigned

### ISSUE THREAD

**Issue by joerns** [ofiwg/libfabric#1857]
I am trying to setup a passive endpoint. I want the port number to be auto-assigned, so I set the `service` parameter to `fi_getinfo` to `"0"`:

     fi_getinfo(FI_VERSION(1, 0), address, "0", FI_SOURCE, hints, &socket->fi)

When I set address to 127.0.0.1 the port gets auto-assigned, but not when I set the address to 0.0.0.0. 

Here is a test program: https://gist.github.com/joerns/c9a25e9b9e1fab3ea92b

Which has the following output:

    $ ./nameinfo
    endpoint = 127.0.0.1:56006
    endpoint = 137.138.90.204:0

The second time the port number (via `fi_getname`) is 0.

**Comment by joerns** [comment]
This only seems to happen with the sockets provider, with the verbs provider it seems to be fine:

    $  FI_PROVIDER=verbs ./nameinfo
    endpoint = 127.0.0.1:40664
    endpoint = 0.0.0.0:56187

**Comment by shantonu** [comment]
I was able to reproduce the issue with sockets provider. I'll take a look into it. Thanks!

**Comment by shantonu** [comment]
Can you please verify if the issue is resolved with the following branch? https://github.com/shantonu/libfabric/tree/pr/sockets-getinfo

**Comment by joerns** [comment]
I can confirm that your patch works here. Thanks a lot for the quick fix!

**Comment by shantonu** [comment]
Thanks for verifying. Now the fix the merged to master branch.
