### ISSUE TITLE
Why are the creation / addition of resources to poll sets and wait sets different?

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1861]
From http://ofiwg.github.io/libfabric/master/man/fi_poll.3.html, it looks like:

* Poll sets:
  * You create a poll set with `fi_poll_open` and close it with `fi_close`.
  * You add a CQ or counter to the poll set with `fi_poll_add` and remove it via `fi_poll_del`
* Wait sets:
  * You create a wait set with `fi_wait_open` and close it with `fi_close`.
  * You add a CQ/EQ to a wait set by passing flags in to CQ/EQ creation

Why is there asymmetry in adding / removing fabric descriptors to poll sets vs. wait sets?  I.e., why is there no `fi_wait_add` / `fi_wait_del`?

**Comment by shefty** [comment]
Poll sets are likely software constructs.  Wait sets may be associated with some sort of hardware or kernel resource, which needs to be known at the time the EP is created.

**Comment by jsquyres** [comment]
@shefty Hmm.  The man page is a bit misleading then: the man page says that both poll sets and wait sets are "optimized".

From an API point of view (i.e., I'm a user who doesn't care about whether it's a software or hardware resource), the asymmetry is weird.

If it has to be this way, it would probably be good to explain the rationale for this asymmetry in the man page.

**Comment by shefty** [comment]
Poll sets are a progress related helper abstraction.  Wait sets are not.  A CQ/EQ is limited to a single wait set.  They can be associated with multiple poll sets.  I think you're trying to find a symmetry where none is expected to exist.
