### ISSUE TITLE
Add fi_*_pingpong to libfabric

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1871]
# Short version

I propose that we move the `fi_*_pingpong` tests from fabtests to libfabric.

# More detail

In terms of customers getting libfabric installed and verified, we currently have a single tool in libfabric: `fi_info`.  And it actually does a nice job: for you to get output from `fi_info`, a whole lot of things have to go right in the control path.

But it would also be good for customers to actually be able to verify the data path, too.  libibverbs has the `ibv_*_pingpong` executables for this purpose.

Indeed, RHEL splits libibverbs into 3 RPMs:

* libibverbs
* libibverbs-devel
* libibverbs-utils: the `ibv_devinfo` (analogous to `fi_info`) and `ibv_*_pingpong` executables are in here

SLES does something similar.

Specifically: I think that libfabric should contain both `fi_info` for verifying control path issues (this is already done) and `fi_*_pingpong` for verifying data path issues (this is what I'm proposing).  I'm *guessing* that the distros would do something similar with their libfabric RPMs that they have done with their libibverbs RPMs.

I am willing to make libfabric/fabtests PRs for this (in time for v1.3.0), but wanted to take the community's temperature on this before doing so.

**Comment by sayantansur** [comment]
I like this idea. This is the first thing I do on a system to see if I installed it correctly.

**Comment by shefty** [comment]
Personally, I like the current breakdown between libfabric and fabtests.  It makes it much easier to test things like backwards compatibility, and ensure that changes don't break apps.

There are too many options for how the interfaces can be used for a user to determine much from running a simple ping-pong test.  For example, there are 4 RDM pingpong tests just to test the interface in a slightly different way.  This could easily be done for the other EP types.  And the tests still don't handle things like atomics or RMA.  It also makes it harder to share code between the pingpong tests and other tests.

**Comment by jsquyres** [comment]
I'm not looking for be-all/end-all pingpong tests in libfabric.  I'm just looking for basic pingpong tests -- something to verify that data can actually flow.  I'd even be willing to write a stripped down/simplified `fi_ud|rdm|msg_pingpong` test to put into libfabric.  Perhaps it doesn't have to share code with fabtests at all.

**Comment by shefty** [comment]
I wouldn't object to having a set of very simple tests, and I think developers would like to see them.  But when you get into "here's a test that uses counters", "here's one that calls inject", ...  Anyway, it really comes down to what is simple.  Pingpong?  Hello world?  And what the parameters into the test are.  Even UD pingpong isn't a simple test when it comes down to it.  But if you want to add 1-3 simple tests to libfabric, I’m okay with that.

**Comment by jsquyres** [comment]
I've made progress on this, but it's not going to be finished in time for v1.3.0 (i.e., this upcoming weekend).  Moving to v1.4.0.
