### ISSUE TITLE
variable sized FI_CONTEXT

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#1890]
This is more of a question. I love fi_context, as it acts as a scratch pad for any per transaction internal tracking. Some, if not all, apps are OK carrying this struct around, since typically they have to carry around some information anyways due to use of a non-blocking API.

Currently, the structure has a fixed static definition. What do folks think of a variable run time size definition? The idea is that the provider could tell the app the size of the context structure it desires?

I'm assuming we would need two variables - one for the regular context struct and the other for the triggered context.

I spoke with @charlesarcher today, and he said probably MPICH/libfabric could probably deal with this.

Thoughts?

**Comment by shefty** [comment]
2 sizes seem like overkill - unless you want to separate between Tx and Rx.  I can't imaging latency being an issue with triggered ops, such that a provider couldn't just allocate one from a pool.

Variable sized fi_context seems equivalent to FI_MSG_PREFIX.  I don't know how hard using msg prefix is for most apps.  But that also brings up the point that FI_MSG_PREFIX could fulfill the same role as a variable sized context.

Increasing the size of fi_context would be trivial if done with the ABI bump.

**Comment by sayantansur** [comment]
Yes, need to think about the FI_MSG_PREFIX. I know that folks sometimes use FI_MSG_PREFIX with IOVECs to discard the prefix buffer. Is that legal with libfabric? Does the programmer have to maintain a different buffer for prefixes for different transactions?

Regarding triggered, discussions with the collectives folks revealed that they would actually want to reuse the triggered command often, maybe only bump the threshold counter up between iterations.

**Comment by shefty** [comment]
The downside of msg prefix is that it would likely require using an iovec.

**Comment by goodell** [comment]
> Currently, the structure has a fixed static definition. What do folks think of a variable run time size definition? The idea is that the provider could tell the app the size of the context structure it desires?

What's the motivation here?  Just to ratchet down slightly the amount of memory consumed by using libfabric?  Or are you looking to store a lot more information than can currently be stored in the context space (currently 4 pointers worth)?

> Does the programmer have to maintain a different buffer for prefixes for different transactions?

You can't post two receives which share identical/overlapping prefix regions, so if I'm understanding your question correctly then the answer is "yes".

Remember that the primary use case for `FI_MSG_PREFIX` is for applications that already send/recv a header and don't care about enlarging that header slightly so that hardware like usNIC can transmit more efficiently.  So for applications that don't already send a header of their own, using prefix is going to feel a bit more awkward/forced.  But I agree with @shefty that prefix could be used very similarly to `FI_CONTEXT`.

**Comment by sayantansur** [comment]
> What's the motivation here? Just to ratchet down slightly the amount of memory consumed by using libfabric? Or are you looking to store a lot more information than can currently be stored in the context space (currently 4 pointers worth)?

My motivation is to allow providers that may need to store more be able to declare their requirements. Especially when the provider needs just a little bit more, like 5 ptrs worth.

> So for applications that don't already send a header of their own, using prefix is going to feel a bit more awkward/forced.

Agreed.

**Comment by shefty** [comment]
My main concern with using prefix is the performance impact of forcing the use of iovecs.

After more thought, my preference is a single sized fi_context, with a static size preferred over a dynamic size.  Though I'm not sure if dynamic support is that difficult on apps.  We could also do dynamic with a defined maximum size.  I do not want to get into different sized contexts based on which call is being made or how a specific call is made.

**Comment by sayantansur** [comment]
> We could also do dynamic with a defined maximum size.

I like this approach.

I agree that single sized context is sufficient.

**Comment by shefty** [comment]
This was discussed in the OFIWG meeting on 6/28/16.  The note from that meeting is that FI_CONTEXT may be linked to FI_ASYNC_IOV.  The PSM/PSM2 and usnic providers are currently okay with the current definition.  To avoid internal allocations, they would need a significantly larger fi_context, one that would allow storing an iovec.  So, we need to find the 'sweet' spot that won't waste memory and avoids internal allocations for most (not all) operations.  The other feedback is that the general consensus is that fi_context should be fixed sized, not variable per provider.

This may change how we approach the solution.  Similar to how FI_MSG_PREFIX could somewhat be used as a replacement for FI_CONTEXT, so could an extra iovec with FI_ASYNC_IOV enabled.

**Comment by hppritcha** [comment]
I did some investigation of whether the GNI provider's internal request structure could somehow be refactored to fit (at least partially) in 64 bytes, but it doesn't look practical.  I'd say for GNI provider this larger context wouldn't help.

**Comment by shefty** [comment]
The original issue mentioned different sizes for normal operations versus triggered ops.  There will be an update soon on how triggered ops are exposed to the apps, which will effectively increase the context size for those level of operations.  Is a larger size context for normal operations still needed?

**Comment by shefty** [comment]
Bringing the topic of having a larger fi_context back up, so we can close on this.  The triggered ops (aka deferred work requests) were modified, so I'd like to remove those from the discussion.  I need to know if there is a provider need for moving from a 4-pointer sized context to 8.

**Comment by sayantansur** [comment]
Do you mean to say that the triggered ops contexts are now orthogonal to the normal provider requested one?

**Comment by mblockso** [comment]
The bgq provider *requires* a 64B context. This default smaller sized fi_context is why the bgq provider only supports FABRIC_DIRECT (so the fi_context struct can be redefined).

**Comment by shefty** [comment]
Thanks @mblockso - that's the information I'm looking for.

@sayantansur - The expanded triggered ops use struct fi_deferred_work now, but that includes fi_context, which is the same.  But the entire fi_deferred_work must remain valid.
