### ISSUE TITLE
wrong FI_MINOR_VERSION for libfabric-1.2

### ISSUE THREAD

**Issue by HonggangLI** [ofiwg/libfabric#1895]
FI_MINOR_VERSION should be 2 for libfabric-1.2, not 1.

```
<mock-chroot>sh-4.3# rpm -ql libfabric-devel | grep .h$ | xargs grep FI_MAJOR_VERSION 
/usr/include/rdma/fabric.h:#define FI_MAJOR_VERSION 1

<mock-chroot>sh-4.3# rpm -ql libfabric-devel | grep .h$ | xargs grep FI_MINOR_VERSION 
/usr/include/rdma/fabric.h:#define FI_MINOR_VERSION 1

<mock-chroot>sh-4.3# rpm -q libfabric 
libfabric-1.2.0-1.fc25.x86_64
```

**Comment by jsquyres** [comment]
Looks like that was missed in making the v1.2.0 tarball.  Doh.

It's correct for the upcoming v1.3 tarball, however.

I also added a note to [the Release Procedures wiki page](https://github.com/ofiwg/libfabric/wiki/Release-procedures) to ensure to update `fabric.h`.

**Comment by jsquyres** [comment]
More specifically: I'm unaware of plans to make a v1.2.1 release -- I believe the fix will be to wait for the v1.3.0 tarball.

**Comment by HonggangLI** [comment]
What is the URL pointer for v1.3.0?

**Comment by jsquyres** [comment]
v1.3 has not been released yet; it is expected by the end of March or beginning of April (i.e., quite soon).

Nightly tarballs after the v1.2 tarball can be found here (none are marked "v1.3.0" yet -- they're just marked as "after v1.2.0"): http://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/

**Comment by jsquyres** [comment]
@HonggangLI Actually, looking at the "nightly tarballs" dirs on the web site, I see that they have become a bit of a confusing mess.  :frowning:  I'm going to clean them up.

Here's a link to the latest tarball (as of last night): http://www.openfabrics.org/downloads/ofiwg/nightly_tarballs/v1.2.x/fabtests-1.2.0.169.g1d7d6e9.tar.bz2

**Comment by jsquyres** [comment]
Version 1.3.0 has been released, which fixes this issue: https://github.com/ofiwg/libfabric/releases/tag/v1.3.0
