### ISSUE TITLE
Prepare MXM provider for v1.3.0 release

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1907]
Please complete by 31 Mar 2016:

* [x] Update `NEWS.md` for your provider
* [x] Update `fi_<your provider>.7.md`
* [x] Update `AUTHORS` to ensure all authors who have committed to your provider are listed (i.e., if they show up in `git log`, list them in `AUTHORS`)
* [x] Update your provider in the [v1.3.0 Provider Feature Matrix wiki page](https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.3.0)

* [Using the RC tarballs](http://www.openfabrics.org/downloads/ofi/) (**NOT** a git clone!), compile fabtests v1.3.0 with libfabric v1.3.0
  * [x] Verify that all relevant tests pass with your provider
  * [x] ABI check: Change your `LD_LIBRARY_PATH` to point to a libfabric v1.2.0 installation (installed from [libfabric v1.2.0 release tarballs](http://www.openfabrics.org/downloads/ofi/)).  Verify that all relevant tests pass with your v1.2.0 provider.

* [ ] Update entries for your provider on #1905

**Comment by shefty** [comment]
@evgeny-leksikov

**Comment by jsquyres** [comment]
@evgeny-leksikov Can you please accept the github invitation to the ofiwg organization?  It shows that it sent you an invitation a while ago.

**Comment by jsquyres** [comment]
@evgeny-leksikov If you've lost the email, you can accept the ofiwg organization invitation at https://github.com/ofiwg

**Comment by evgeny-leksikov** [comment]
@alexander-sannikov could you verify the compliance with the checklist?

**Comment by alexander-sannikov** [comment]
@evgeny-leksikov sure, I'll check it shortly.

**Comment by alexander-sannikov** [comment]
@jsquyres 
1, 2) NEWS.md and fi_<your provider>.7.md - no updates required.
4) v1.3.0 Provider Feature Matrix wiki page - is updated

**Comment by jsquyres** [comment]
@alexander-sannikov I just invited you to the ofiwg Github org.  When you accept the invite, I can assign the issue to you (and then I think you'll have the write perms that will enable you to tick off the items in the checklist).

**Comment by jsquyres** [comment]
@alexander-sannikov Actually, I think once you accept the invite, you can re-assign the issue to yourself (I have to step AFK for about 2 hours -- I don't think you'll need to wait for me).

**Comment by alexander-sannikov** [comment]
I've recheck MXM provider. It requests [https://github.com/ofiwg/fabtests/pull/494](https://github.com/ofiwg/fabtests/pull/494) patch in fabtests. 
MXM provider is ready for 1.3 release.

**Comment by jsquyres** [comment]
@alexander-sannikov Sweet; thank you.  Can you tick off the last items in the original bug report (e.g., ensure `AUTHORS` is updated, ensure #1905 is updated, etc.), and close this issue when they're all done?

**Comment by alexander-sannikov** [comment]
@jsquyres I'm not able to edit #1905

**Comment by jsquyres** [comment]
@alexander-sannikov Ah, ok.  I'll do it for you -- from your statements, I assume that `AUTHORS` is all up to date, then.  Thanks.

**Comment by alexander-sannikov** [comment]
@jsquyres Thank you! Sure, major autors are listed in `AUTHORS` or `prov/mxm/AUTHORS`
