### ISSUE TITLE
Prepare PSM2 provider for v1.3.0 release

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1909]
Please complete by 31 Mar 2016:

* [x] Update `NEWS.md` for your provider
* [x] Update `fi_<your provider>.7.md`
* [x] Update `AUTHORS` to ensure all authors who have committed to your provider are listed (i.e., if they show up in `git log`, list them in `AUTHORS`)
* [x] Update your provider in the [v1.3.0 Provider Feature Matrix wiki page](https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.3.0)

* [Using the RC tarballs](http://www.openfabrics.org/downloads/ofi/) (**NOT** a git clone!), compile fabtests v1.3.0 with libfabric v1.3.0
  * [x] Verify that all relevant tests pass with your provider
  * [x] ABI check: Change your `LD_LIBRARY_PATH` to point to a libfabric v1.2.0 installation (installed from [libfabric v1.2.0 release tarballs](http://www.openfabrics.org/downloads/ofi/)).  Verify that all relevant tests pass with your v1.2.0 provider.

* [x] Update entries for your provider on #1905

**Comment by j-xiong** [comment]
All done.

The failure of the new "fi_rdm_shared_av" test is expected. It should be treated the same as "NotRun".

**Comment by jsquyres** [comment]
@j-xiong It doesn't look like you ticked off the PSM / PSM2 entries on #1905.  I'll do that for you.
