### ISSUE TITLE
Prepare verbs provider for v1.3.0 release

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#1913]
Please complete by 31 Mar 2016:

* [x] Update `NEWS.md` for your provider
* [x] Update `fi_<your provider>.7.md`
* [x] Update `AUTHORS` to ensure all authors who have committed to your provider are listed (i.e., if they show up in `git log`, list them in `AUTHORS`)
* [x] Update your provider in the [v1.3.0 Provider Feature Matrix wiki page](https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.3.0)

* [Using the RC tarballs](http://www.openfabrics.org/downloads/ofi/) (**NOT** a git clone!), compile fabtests v1.3.0 with libfabric v1.3.0
  * [x] Verify that all relevant tests pass with your provider
  * [x] ABI check: Change your `LD_LIBRARY_PATH` to point to a libfabric v1.2.0 installation (installed from [libfabric v1.2.0 release tarballs](http://www.openfabrics.org/downloads/ofi/)).  Verify that all relevant tests pass with your v1.2.0 provider.

* [x] Update entries for your provider on #1905

**Comment by a-ilango** [comment]
Heads up: I'm seeing an issue in the libfabric release build for verbs provider which I had missed in my testing as I had the --enable-debug option set. I'm currently looking into this issue.
@shefty

**Comment by a-ilango** [comment]
I have a PR #1933 that should resolve the issue.

**Comment by jsquyres** [comment]
#1933 has just been merged.

**Comment by jsquyres** [comment]
@a-ilango Are #1921 and #1934 also needed for v1.3.0?

**Comment by jsquyres** [comment]
Also, @a-ilango, have you done the ABI check with the verbs provider?

**Comment by jsquyres** [comment]
#1934 has been merged.  @hppritcha is making a new PR to rebase #1921 to fix the conflicts (because we're assuming that @a-ilango is in a timezone where it's already the weekend).

**Comment by a-ilango** [comment]
@jsquyres I have done the ABI check and verified that fabtests 1.2 runs fine with LD_LIBRARY_PATH set to libfabric 1.3rc1. The description in the task list is incorrect (spoke with @shefty  regarding this).

**Comment by jsquyres** [comment]
@a-ilango Thank you! (yeah, I realized I wrote the ABI check backwards about a day after I wrote them all, and didn't go back and fix them :frowning: )

**Comment by jsquyres** [comment]
Ok, all the docs have been updated, then, and the ABI checks are done, so I'm closing this issue.  The last remaining issue is @hppritcha making a new PR to rebase #1921, and that can proceed independently.
