### ISSUE TITLE
usnic: Move CQ creation from bind to open

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1919]
The creation of the CQ was placed in the bind call rather than the open call because it is not known at the time of calling open which type of endpoint the CQ will be used for. The usNIC provider handles the emulated and non-emulated endpoint cases differently. This design choice has worked but been problematic in a number of instances (such as #1918).

Proposed solutions:
- Create the CQ up front as if it were a hard CQ and destroy and reallocate later if bound to an emulated endpoint. 
- Create the CQ and modify the size if bound to an emulated endpoint. This requires re-allocating the descriptor ring.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
