### ISSUE TITLE
verbs/RDM fails basic Open MPI hello_c test

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1931]
The verbs/RDM fails a basic Open MPI hello_c test. I suspect this is because the test actually doesn't do enough communication between ranks connections to get fully established before the job enters `MPI_Finalize`.  I could work around the resulting segfaut by applying the patch at this [gist](https://gist.github.com/hppritcha/192958c477bf1157f7bed6c50ea40720)

Its probably not the right fix, but otherwise I can't get basic Open MPI tests like hello_c and ring_c to work using the verbs provider.  The Open MPI is using the ofi mtl.

**Comment by hppritcha** [comment]
@shefty 
@evgeny-leksikov

**Comment by hppritcha** [comment]
sorry use the patchfile at this gist instead (==) not (>=)

https://gist.github.com/hppritcha/7e61492cc9288da656842d3a9c998158

**Comment by evgeny-leksikov** [comment]
@hppritcha could you check this https://github.com/ofiwg/libfabric/pull/1944, it works on my system.

**Comment by shefty** [comment]
This is a 4 year old issue that is almost certainly resolved, or used some deprecated code.  Open MPI and rxm;verbs have been in use for a while now.
