### ISSUE TITLE
Add documentation for providers and relocate data structures

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1946]
- [ ] Add information and documentation about data structures and common code available to the providers and document in a markdown file (enhance `docs/providers`).
- [ ] Move available data structures to something like `include/data/<datastructure>.h`
- [ ] Reference the provider documentation in the `fi_provider` man page.

**Comment by shefty** [comment]
I don't see these as requirements for a release.  Removing milestone.

Enhancing the documentation would be nice, but I don't see a compelling reason to move data structures around, or separating them from the APIs that use them.

docs/providers is intended to provide pointers and necessary documentation.  It doesn't need to be exhaustive.  Can you please provide specific details on what should be added to that documentation?
