### ISSUE TITLE
prov/verbs: intermittent hangs at finalize with osu_barrier using Open MPI

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#1947]
The osu_barrier test shows periodic failures at job termination when run on four ranks. 

The signature is that all but rank 0 can sometimes exit, while rank 0 hangs around long enough for srun to detect that the other processes have already exited.  Note this may have something to do with the way srun times the exit of processes.

To reproduce the test using Open MPI master (3.0.0a1) on a slurm system use the following config options for building Open  MPI:

```
./configure --with-libfabric=PATH_TO_LIBFAB_INSTALL  --with-pmi --with-slurm
```

then when using srun to launch the job:

```
export OMPI_MCA_pmix=s1
srun -n 4 --exclusive ./osu_barrier
```

I noticed that if one replaces the MPI_Reduce calls at the end of the code with MPI_Allreduce, the hang problem disappears.

The problem is intermittent and make take several (5-6) runs before you see the hang.

**Comment by jsquyres** [comment]
@evgeny-leksikov Did you ever have a chance to look at this?
@hppritcha Do you know if this is this still happening?

**Comment by evgeny-leksikov** [comment]
@jsquyres  Not yet but I recently got access to the slurm installation, so I'll check soon. Anyway, I'm not sure I have enough time to fix it in this release if it's still reproducible. I think the milestone can be changed for 1.5.
@hppritcha could you check the current state? there were several fixes for init/finalize phases.

**Comment by jsquyres** [comment]
@hppritcha Did this get resolved via the coll/sync module?

**Comment by hoopoepg** [comment]
@hppritcha
hi, could you check this issue on latest master? we bit updated finalization of EP and it should not hang now

thank you
