### ISSUE TITLE
prov/verbs: build breakage on PPC

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1948]
CC     prov/verbs/src/src_libfabric_la-verbs_rma.lo
/bin/sh ./libtool --silent --tag=CC   --mode=compile gcc -std=gnu99
-DHAVE_CONFIG_H -I.  -I./include -D_GNU_SOURCE -DSYSCONFDIR=\"/etc\"
-DRDMADIR=\"@rdmadir@\" -DPROVDLDIR=\"/usr/lib64/libfabric\"  -D__LIBUSNIC__
-DWANT_DEBUG_MSGS=0 -DHAVE_LIBNL3=0  -I./prov/usnic/src/usnic_direct    -g
-Wall  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64
-mcpu=power7 -mtune=power8 -c -o prov/verbs/src/src_libfabric_la-verbs_rma.lo
`test -f 'prov/verbs/src/verbs_rma.c' || echo './'`prov/verbs/src/verbs_rma.c
In file included from prov/verbs/src/ep_rdm/verbs_rdm.h:37:0,
                 from prov/verbs/src/verbs_rma.c:38:
prov/verbs/src/ep_rdm/verbs_utils.h:50:23: fatal error: xmmintrin.h: No such
file or directory
 #include "xmmintrin.h"
                       ^
compilation terminated.
  CC     prov/verbs/src/ep_rdm/src_libfabric_la-verbs_av_ep_rdm.lo
/bin/sh ./libtool --silent --tag=CC   --mode=compile gcc -std=gnu99
-DHAVE_CONFIG_H -I.  -I./include -D_GNU_SOURCE -DSYSCONFDIR=\"/etc\"
-DRDMADIR=\"@rdmadir@\" -DPROVDLDIR=\"/usr/lib64/libfabric\"  -D__LIBUSNIC__
-DWANT_DEBUG_MSGS=0 -DHAVE_LIBNL3=0  -I./prov/usnic/src/usnic_direct    -g
-Wall  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions
-fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64
-mcpu=power7 -mtune=power8 -c -o
prov/verbs/src/ep_rdm/src_libfabric_la-verbs_av_ep_rdm.lo `test -f
'prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c' || echo
'./'`prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c
make[1]: *** [prov/verbs/src/src_libfabric_la-verbs_rma.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from prov/verbs/src/ep_rdm/verbs_rdm.h:37:0,
                 from prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c:36:
prov/verbs/src/ep_rdm/verbs_utils.h:50:23: fatal error: xmmintrin.h: No such
file or directory
 #include "xmmintrin.h"

**Comment by evgeny-leksikov** [comment]
I checked the line numbers, looks like this is a build of libfabric without this patch https://github.com/ofiwg/libfabric/pull/1844

**Comment by jsquyres** [comment]
@evgeny-leksikov @shefty Is this issue moot?

**Comment by evgeny-leksikov** [comment]
@jsquyres I don't have a PPC to check it definitely but looks like this issue is already fixed.
