### ISSUE TITLE
prov/sockets: cleanup of uninitialized resources when closing endpoint

### ISSUE THREAD

**Issue by plebioda** [ofiwg/libfabric#1958]
If an endpoint is closed without attempting to connect a file descriptor = 0 is closed.

It is closed [here](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_ep.c#L630).

The following patch for fabtests helps reproducing this.
This is not **real** reproduction but it looks like this is absolutely valid. Right ?

```
diff --git a/common/shared.c b/common/shared.c
index 6b7e530..9431fe8 100644
--- a/common/shared.c
+++ b/common/shared.c
@@ -327,6 +327,12 @@ int ft_alloc_active_res(struct fi_info *fi)
                return ret;
        }
 
+       ret = fi_close(&ep->fid);
+       if (ret) {
+               FT_PRINTERR("fi_close", ret);
+               return ret;
+       }
+
        return 0;
 }
```

**Comment by shantonu** [comment]
I have added a check to address this issue. Can you please verify if #1964 resolves it?

**Comment by plebioda** [comment]
Yes I can confirm it helps.

**Comment by shantonu** [comment]
Thanks!
