### ISSUE TITLE
adjust output for fi_info

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1974]
Response from a user:

> Since we are asking users to tell us the fabric/domain that they want to use, it would be helpful if the fi_info tool is better about showing what's what in the short output. Presently we get something like:
> 
> ```
sockets: en0
  version: 1.0
  type: FI_EP_MSG
  protocol: FI_PROTO_SOCK_TCP
> ```
> 
> A normal user may not be able to identify what "sockets" or "en0" refers to.  It would be helpful to change the formatting so that this is clearer (e.g. more like the verbose output).  It would be helpful to also include domain name and src_addr values in the short output, if users will need to use these values for fabric selection.

The issue here is that some users need to identify specific information about which provider/fabric/domain that they want to use.  The request is to adjust the fi_info default output to provide this level of data.

***EDIT: Fixed the markdown to show the quoting***

**Comment by shantonu** [comment]
Does this look alright? @jdinan 
provider: sockets
    fabric: 192.168.33.0
    domain: eth1
    version: 1.0
    type: FI_EP_MSG
    protocol: FI_PROTO_SOCK_TCP

**Comment by jdinan** [comment]
:+1:

**Comment by jsquyres** [comment]
From fabric(7):

> fi_fabric - Fabric Domain
> A fabric domain represents a collection of hardware and software resources that access a single physical or virtual network. All network ports on a system that can communicate with each other through the fabric belong to the same fabric domain. A fabric domain shares network addresses and can span multiple providers. libfabric supports systems connected to multiple fabrics.
>
> fi_domain - Access Domains
> An access domain represents a single logical connection into a fabric. It may map to a single physical or virtual NIC or a port. An access domain defines the boundary across which fabric resources may be associated. Each access domain belongs to a single fabric domain.

To me, these definitions imply that the fabric should be eth1 and the domain should be 192.168.33.0 -- not the other way around, mainly on the rationale that Linux IP interfaces can have multiple IP addresses bound to them.  I.e.:

- Fabric: Linux IP interface.  It's a collection of hardware and software resources that access a single physical [or virtual] network.
- Domain: IP address.  It's a single logical connection to the fabric.

I.e., the "eth1" fabric name may show up multiple times with different IP addresses/domains.

**Comment by jdinan** [comment]
What that have seems correct to me:

"eth1" is "a single physical or virtual NIC" (domain) and "192.168.33.0" is a network address, which is "a single physical or virtual network" (fabric).  The test seems to be that it doesn't have to be same domain (eth1) at all nodes, but it does have to be the same fabric (network address).

**Comment by jsquyres** [comment]
Ah -- I totally missed the fact that the address was .0, meaning that it is a network address (not a specific IP address).  As such, the name should probably really be "192.168.33.0/24".

With that interpretation, I think I'm ok with this:

```
provider: sockets
  fabric: 192.168.33.0/24
  domain: eth1
  version: 1.0
  type: FI_EP_MSG
  protocol: FI_PROTO_SOCK_TCP
```

If we all agree that this is a good format, @goodell, @bturrubiates, and I might well be amenable to updating the usNIC provider to match this kind of format:

* Current: fabric=`usnic_X`, domain=NULL
* We could update to: fabric=`a.b.c.d/e`, domain=`usnic_X`

**Comment by jdinan** [comment]
+1

**Comment by jsquyres** [comment]
All that being said, should fabric(7) be updated to include some text about @jdinan's "test":

> The test seems to be that it doesn't have to be same domain (eth1) at all nodes, but it does have to be the same fabric (network address).

That would seem like a useful clarification about this model.

Also, there might be some other text cleanup that could be useful.  For example, fi_fabric(3) has language describing the "fabric" argument as a "Fabric domain", which seems... misleading.

**Comment by jsquyres** [comment]
BTW -- just because I want to keep spamming everyone's inbox -- should we try to get all the providers to do this kind of format?

```
provider: PROVIDER_NAME
  fabric: NETWORK_ADDRESS
  domain: INTERFACE_NAME
...
```

**Comment by shefty** [comment]
I just sent this in an internal email, but I think the best option for IPv4 fabric names are:

"127.0.0.0/8"        -- loopback
"10.0.0.0/8"
"172.16.0.0/12"
"192.168.0.0/16"
"Internet"           -- all other IP addresses

This would better support routing between subnets.  I don't know how you tell if two private subnets (e.g. 192.168.1.0/24 and 192.168.2.0/24) cannot reach each other.

**Comment by jsquyres** [comment]
That seems... odd.  E.g., not all 10.x.y.z addresses are /8.

Why wouldn't you put the actual network address?

I don't think you can reasonably make any conclusions about route-ability based on the fabric or domain name.

**Comment by shefty** [comment]
> That seems... odd. E.g., not all 10.x.y.z addresses are /8.

The intent is to capture the address range, not the local subnet mask.

> Why wouldn't you put the actual network address?

This allows two processes on different subnets to see that they are on the same 'fabric', rather than having different fabric names, different domain names, yet still be able to reach each other.

Yes, it also means that the processes could see the same fabric name, but not be able to talk.  But since they can't talk, they wouldn't know that they have the same fabric name.  :)

It would help if we consider the type of topology data that we might report for a 'fabric'.

**Comment by jsquyres** [comment]
1. Reporting a CIDR notation that does not necessarily correspond to the network interface on which you'll be sending / receiving is quite confusing.
1. The names have nothing to do with reachability.  You mentioned one case (multiple 10.x.y.z/8 addresses not being able to reach each other), but there are others (e.g., a 10.x.y.z/8 might well be able to reach a 192.168.x.y/24 -- yes, /24, not /16 -- 192.168 is defined to be a collection of /24's, not a single /16).

These names -- just like the individual network or IP addresses -- have nothing to do with reachability.  It is a mistake to try to use them that way.

**Comment by shefty** [comment]
We can call the fabric name anything, the question is what is *useful*?  IMO, a fabric name is more useful if it is the same for all nodes that will communicate as part of a single job.  Using fabric name = subnet address, I see trade-offs either way.

**Comment by jsquyres** [comment]
It's not a bad thing to have a common token across peers who can reach each other.  But without prior knowledge, there's really no way to determine that during an `fi_getinfo()` (i.e., before a peer has been specified).

I think you're asking the right question, though: what is *useful*?

I think that what is *useful* is for users/apps to be able to know what network interface(s) they will be using.  They will have to determine reachability themselves.

How about an alternate:

```
provider: PROVIDER_NAME
    fabric: NETWORK_ADDRESS[,NETWORK_ADDRESS2[,NETWORK_ADDRESS3[...]]]
    domain: INTERFACE[,INTERFACE2[,INTERFACE3[...]]]
...
```

Where, in the case of IP networks, the NETWORK_ADDRESS would be a CIDR notation (like 192.168.3.0/24) and INTERFACE could be either the interface name (e.g., `eth1`) or the specific IP address -- I keep waffling between which would be better.

If a provider represents a bonded interface, it can provide a comma-delimited list of either/both, as relevant.

**Comment by goodell** [comment]
>  IMO, a fabric name is more useful if it is the same for all nodes that will communicate as part of a single job.

This is a very HPC-centric view ("a single job").  libfabric should also serve the needs of more general networking programs that need high performance.

I agree that answering the question of "is my peer's fabric reachable from this fabric" would be very useful.  But that doesn't mean it's *feasible* for us to answer that in a meaningful way without either some administrator-installed configuration or an external service/daemon (like DNS or an MPI process manager).

It seems like trying to map classless IP addresses back into some sort of classful taxonomy is going to be nearly useless at best and extremely confusing to users at worst ("Hey, I thought I was using a 10.x.0.0/16 network but this says 10.0.0.0/8... What gives!").

**Comment by shefty** [comment]
The source address works to select a local interface.  The domain name is also usable, going with something like domain name = eth0.  I am HPC-centric for the fabric name because I envision it being used to distinguish between parallel networks, but for that to work, the name has to be consistent across nodes.  That is, I want the fabric name to do something that I can't already do with the domain name.

For our test clusters, having the fabric name match the network address would work well (better than my proposal above even), but then our clusters are small.

In any case, we're training the application developers to support filtering on multiple options (fabric name and/or domain name and/or provider name and/or source address).

**Comment by jsquyres** [comment]
Pattern matching on IP addresses and string names has nothing to do with reachability.  Here's some more examples:

* With large enough ethernet clusters, even HPC networks are L3
* Some customers even like to have each 42U rack be a different island of L3 (e.g., 10.x.y.z/28)
* With multiple network interfaces, you can have multiple different 10.x.y.z interfaces on a single server (for different/unreachable subnets)

Without a priori knowledge, determining reachability is not possible without actually trying to make a connection.

I think the only useful thing you can get out of the fabric/domain name is to know what local interface(s) you will be using.  Reachability will have to be determined separately.

**Comment by shefty** [comment]
Okay, here's what I think would work:

* Map fabric name to the local network address.  (This is what Shantonu has implemented.)
* Add support for more complex pattern matching on names. (This is future work.)

Combined, this should work well in most environments.  On small clusters, the fabric name can be used as a filter.  On larger clusters, the fabric name requires some form of pattern matching.

**Comment by jsquyres** [comment]
Just to be pedantic to make sure we're clear on what we're agreeing...

1. For sockets, fabric will be of the form `a.b.c.d/e`, which reflects the actual network address of the underlying interface.
1. For sockets, domain will be the interface name (e.g., `eth1`).

Is that right?

In the general case, if other providers follow this convention, should they provide comma-delimited lists if the provider represents a bonded interface?

**Comment by shefty** [comment]
correct

**Comment by jsquyres** [comment]
Cool.  We'll do this in usnic, too (but probably not for a little bit -- it's an excellent exercise for a new person we have coming on to the team in a few weeks...).

**Comment by shantonu** [comment]
Thanks everyone for the clarification! I have submitted the PR for Sockets provider.
