### ISSUE TITLE
limit op_flags to send/receive only

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#1981]
The man pages state that op_flags can be set for send, receive, read, or write.  No provider supports setting the op_flags (at least correctly!).  Op flags are specified during EP creation through the tx/rx attributes.  Adding read/write flags complicates the implementation.  Require FI_SEND and/or FI_RECV as part of the fi_control flags.

Also clarify that the fi_alias sets the op_flags the same as calling fi_control SETOPSFLAG.

Check the PSM and GNI providers, which are acting on FI_SETFIDFLAG, which isn't defined in the man pages.  (And I can't remember what it was for...)

**Comment by j-xiong** [comment]
Isn't read/write considered tx operations? It makes sense to have default op flags such as FI_COMPLETION and FI_INJECT apply to read/write operations.

**Comment by shefty** [comment]
When an EP is created, an app can specify op_flags for all tx and all rx operations separately.  According to the man pages, if fi_control SETOPSFLAG is called, the app can specify send op flags, separately from write op flags separately from read op flags.  For a provider, this means maintaining 4 set of op_flags.  The proposal is to only allow changing the op_flags for all tx operations.

More precise granularity can be achieved using fi_alias, and limiting specific types of transfers to only reads or writes, for example.

**Comment by j-xiong** [comment]
That makes sense. Thanks for the clarification. 

As for why the PSM provider acts on FI_SETFIDFLAG instead of FI_SETOPFLAG, my guess is that when fi_control was initially implemented in the provider only FI_SETFIDFLAG was defined.

**Comment by shantonu** [comment]
What about FI_GETOPSFLAG? Do we need to specify which op_flags (rx/tx) we want to get and pass as an argument? @shefty

**Comment by shefty** [comment]
That's a good point, yes, that makes sense.

**Comment by shantonu** [comment]
PSM and sockets provider are updated based on the manpage update. Can we close this?
