### ISSUE TITLE
prov/sockets: fi_accept fails on binding TCP socket

### ISSUE THREAD

**Issue by plebioda** [ofiwg/libfabric#2008]
I have a question regarding the passive endpoint listener on sockets provider using FI_MSG interface.
As far as I understand the sockets provider implementation the passive endpoint binds an UDP socket on specified port and binds a TCP socket on the same port when connection request arrives, is that right ?

The problem I have is that from time to time the fi_accept on server side fails with -22 error code. After debugging I came out that the sock_conn_listen() function fails in sock_ep_cm_accept() because it cannot bind an address to the TCP socket. It happens because I have a separate TCP connection which has been allocated the same port number (on client side).

The issue can be easily reproduced using nc and fi_msg from fabtests:
```
$ nc -l 7636 &
$ nc localhost 7636 &
$ netstat -atnp | grep nc
tcp        0      0 127.0.0.1:7636          127.0.0.1:35454         ESTABLISHED 26630/nc        
tcp        0      0 127.0.0.1:35454         127.0.0.1:7636          ESTABLISHED 26642/nc
$ ./simple/fi_msg -b 35454 &
$ ./simple/fi_msg -p 35454 localhost &
fi_accept(): simple/msg.c:80, ret=-22 (Invalid argument)
```

In my application the fabric's listener port is allocated dynamically and sent to the client using separate socket connection. Since my separate socket connection utilizes TCP the dynamically allocated UDP port happens to be the same and in result binding the TCP port in sockets provider in fi_accept fails.

In the example above I would rather expect that binding the port 35454 fails since it is already in use by another connection but it succeeded and the fi_accept failed.

Is that a bug or something wrong with my app ?

I can prepare some minimal example which reproduces this issue if that would help.

**UPDATE**:
It seems that the following patch fixes the issue:
```
diff --git a/prov/sockets/src/sock_conn.c b/prov/sockets/src/sock_conn.c
index 5005881..026f825 100644
--- a/prov/sockets/src/sock_conn.c
+++ b/prov/sockets/src/sock_conn.c
@@ -295,7 +295,7 @@ int sock_conn_listen(struct sock_ep_attr *ep_attr)
                return -FI_EINVAL;
        }
 
-       if (!sock_fabric_check_service(domain->fab, atoi(listener->service))) {
+       if (1 /*!sock_fabric_check_service(domain->fab, atoi(listener->service))*/) {
                memset(listener->service, 0, NI_MAXSERV);
                ((struct sockaddr_in *)ep_attr->src_addr)->sin_port = 0;
                port = NULL;

```

**Comment by shefty** [comment]
@jithinjosepkl maintains the sockets provider.  He's returning from a long vacation, but I'm sure he'll take a look at this within the next few days when he gets time.

Thanks for the pointer where the problem may reside!

**Comment by jithinjosepkl** [comment]
Thanks @shefty :), Yes, back from a long vacation.

@plebioda - Trying to figure out if this is an app/provider issue. Can you check the port number while creating the server side endpoint (before calling fi_accept()). It seems to me that this port is set to the same port as the client.

Btw, forcing the provider to reset the port information (the one in patch) will result in ignoring the src port number. But, if the ep has no src port specified, it should just pick a random port. That's why I would like to check this. A reproducer will help as well.

Also, the fabtest failure on specifying the same port for server and client is expected, right (when run on same node)? The failure happens in fi_accept(), because thats the place where we bind the TCP socket to the src port.

**Comment by plebioda** [comment]
@jithinjosepkl  Yes, the fabtest failure I mentioned is expected, but I would expect that it fails on binding the specified port number by passive endpoint - not in fi_accept.

I wrote this example to show that even if the passive endpoint binds a valid port number the fi_accept can fail. This is unfortunately also true if the passive endpoint allocates a port number dynamically and then sends the port number to a client - using other connection. When client attepmts to establish a connection the fi_accept fails because binding the TCP socket on the same port number fails.

IMHO there is a wrong assumption that the TCP connection can be always established on the same port number as the UDP port number. That's why I forced dynamic allocation of TCP port in my patch.

I didn't mean to fix the issue with my patch but to show that if the TCP port is always allocated dynamically there is no problem.

I wrote a simple app which reproduces the issue:
https://gist.github.com/plebioda/11b3b9227c4354b84239c0dc80fe5ddd

Let me explain how it works:

1. The server side listens on a TCP port 7636 on a regular socket for incoming connection (let's call this an Out-Of-Band connection).
2. After establishing the OOB connection the server creates a passive endpoint and dynamically allocates a port number. The port number is retrieved using fi_getname function.
3. The server starts listening on the passive endpoint.
4. Server sends the port number to the client using OOB connection.
5. The client receives the port number and connects to the server using fi_connect on received port number.

If you run the app in a loop the fi_accept fails sometimes (on some systems it is really rarely but on others it happens all the time in my automatic tests) if there is any TCP connection with the same src port as the passive endpoint's UDP socket's port. The TCP connection can be in either ESTABLISHED or TIME_WAIT state (the latter is more frequent in my case).

```
client $ while ./fi_sock localhost; do true; done
```
```
server $ while ./fi_sock; do true; done
sock port 53149 fabric port 56423
sock port 53150 fabric port 36364
sock port 53151 fabric port 53149
fi_accept: Unknown error -22
port 53149 state TIME_WAIT inode 0
```

The *sock port* is a dest port number of the OOB connection (since the client runs on localhost this port is a src port in some connection and the bind in fi_accept fails).

The *fabric port* is dynamically allocated by passive endpoint which is sent to the client.

**Comment by plebioda** [comment]
After few attempts I get the following error:
```
server $ while ./fi_sock; do true; done
...
sock port 34884 fabric port 34884
fi_accept: Unknown error -22
port 34884 state ESTABLISHED inode 25040075
```

Which means that passive endpoint dynamically allocated the same port number as the OOB connection.

**Comment by jithinjosepkl** [comment]
@plebioda - Can you please try with PR #2021? This assigns new port for every new MSG endpoint.

**Comment by plebioda** [comment]
Yes, it helps. Thanks !

**Comment by jithinjosepkl** [comment]
Thanks!
