### ISSUE TITLE
Check libfabric 1.3.0 build/install

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2015]
The following problem was reported to me from a user.

Yes, I did ./configure --prefix=/tmp/foo and then make install - in /tmp/foo/lib I have libfabric.1.2.0. 

Also, in src/libfabric.la that is created after running make I see:

```
# Names of this library.
library_names='libfabric.so.1.2.0 libfabric.so.1 libfabric.so'
```

And if I remove --silent from Makefile, I can see (output trimmed to be more readable):

```
  CCLD     src/libfabric.la
libtool: link: gcc -std=gnu99 -shared  -fPIC -DPIC  <a lot of stuff removed>   -lrt -lrdmacm -libverbs -lnl -lm -lpthread -ldl  -O2 -Wl,--version-script=./libfabric.map   -Wl,-soname -Wl,libfabric.so.1 -o src/.libs/libfabric.so.1.2.0
libtool: link: (cd "src/.libs" && rm -f "libfabric.so.1" && ln -s "libfabric.so.1.2.0" "libfabric.so.1")
libtool: link: (cd "src/.libs" && rm -f "libfabric.so" && ln -s "libfabric.so.1.2.0" "libfabric.so")
```

Our build system builds libfabric on a clean images and the issue is reproducible there, so my environment looks ok. 

***EDIT: Added verbatim blocks***

-----Original Message-----
> In the meantime I’ve noticed something bizarre. I’ve downloaded libfabric
> 1.3.0 sources from here:
> https://github.com/ofiwg/libfabric/releases/download/v1.3.0/libfabric-
> 1.3.0.tar.gz.
> 
> 
> 
> I do:
> 
> ./autogen.sh
> 
> ./configure
> 
> ./make

Did you run make install?

> And in src/.libs I get the following binaries:
> 
> 
> 
> -rw-r--r-- 1 jzielins user 6724354 May  9 04:07 libfabric.a
> 
> lrwxrwxrwx 1 jzielins user      15 May  9 04:07 libfabric.la ->
> ../libfabric.la
> 
> -rw-r--r-- 1 jzielins user     977 May  9 04:07 libfabric.lai
> 
> lrwxrwxrwx 1 jzielins user      18 May  9 04:07 libfabric.so ->
> libfabric.so.1.2.0
> 
> lrwxrwxrwx 1 jzielins user      18 May  9 04:07 libfabric.so.1 ->
> libfabric.so.1.2.0
> 
> -rwxr-xr-x 1 jzielins user 3350853 May  9 04:07 libfabric.so.1.2.0
> 
> 
> 
> I guess it should be libfabric.so.1.3.0?

**Comment by bturrubiates** [comment]
I could be wrong, but I think that's expected. The numbers on the end of the shared library don't necessarily correspond to the release version, they're part of libtools weird versioning scheme.

@jsquyres You probably know more about this.

**Comment by jsquyres** [comment]
Correct: the numbers of the shared library filename are part of the GNU Libtool `current:revision:age` numbering scheme; they do not relate to the Libtool package version.  See https://www.gnu.org/software/libtool/manual/libtool.html#Versioning for more detail.

**Comment by jsquyres** [comment]
Sorry: typo in my last reply:

> ... they do not relate to the Libtool package version.

should have been:

> ...they do not relate to the **Libfabric** package version.
