### ISSUE TITLE
define scope/requirements for Windows (and other non-Linux) support

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#2044]
Lots of the discussion on issues like #2041 and #2034 seems to stem from a lack of common understanding of the scope and requirements of adding Windows support to libfabric.  To a lesser extent we've had similar confusion on other non-Linux platforms but Windows is much more noticeably different in its APIs and development environment, so it warrants specific attention.  So let's try to get a common scope and set of requirements written down somewhere to help get everyone onto the same page.

**Which compilers are we targeting on Windows, and why (not)?**

Compiler            | Supported? | Notes
------------------- | ---------- | -------------------------------------------------------------------------
Visual C++ <= 2012  |   no        | [does not support C99](https://en.wikipedia.org/wiki/C99#Implementations)
Visual C++ 2013     |   no        | [limited C99](https://en.wikipedia.org/wiki/C99#Implementations)
Visual C++ >= 2015  |   no        | [most C99](https://en.wikipedia.org/wiki/C99#Implementations), but not `complex`
GCC - Cygwin        |   no        |
GCC - MinGW         |   no        |
Intel (ICC)         |   yes      |

Existing libfabric code squarely assumes certain C99 language features, so blatantly non-C99 compilers are likely to make porting more painful and libfabric less robust on all platforms.

Using Cygwin minimizes the code changes needed to existing libfabric source, but may yield worse performance than using native APIs (statement needs a check from a Windows expert).

The question of compiler support is intertwined with the next question about build systems.

**Which build systems are supported on Windows?**

Platform              | Build System            | Supported?  | Notes
--------------------- | ---------------------   | ----------  | --------------------------------------------
Linux / OS X / BSD    | autotools + make        | exclusively | already implemented, robust
Windows               | VC proj file (+ make?) | yes           | **need more details on how this works!**
Windows               | Cygwin autotools + make | no           | little/no divergence from existing build sys
Windows               | Cmake                   | no           | could handle Linux build too, though @goodell and @jsquyres will surely protest
Windows               | static config.h + config.status + make  | no           |

Most of the above choices are essentially a duplicate build system, which can be a real headache to keep in sync with each other.  This is especially true if we don't have continuous integration for the Windows side of the equation, as many devs on the Linux/Unix cannot easily make/test changes to the Windows build system.

**Which providers should be supported on Windows?**

Provider | Supported? | Notes
-------- | ---------- | -----
sockets  | yes        |
udp | yes |
rxm | yes |
other non-util providers  | no        |

**Comment by shefty** [comment]
The port is to support native window builds of applications.  As for the build, we can impose any restrictions that are necessary.  Windows will ship binaries anyway.  But the port is targeting Intel MPI, so if we can support their build environment, I'm sure that they would appreciate it.  :)

The only current providers that need to be supported are sockets and udp.  The utility providers will also need to be supported.  I expect that someday a native NetworkDirect provider will be added.  So changes to other providers (usnic, gni) are not necessary.

**Comment by goodell** [comment]
I just tweaked the issue description to incorporate @shefty's comments.

> But the port is targeting Intel MPI, so if we can support their build environment, I'm sure that they would appreciate it. :)

The details of this build env could use clarification from @hoopoepg and others.

**Comment by hoopoepg** [comment]
for now Intel MPI is built using VS environment and in case if OFI for windows will use VS project to build - it will work.
there is issue with MS compiler: no one compiler (including latest VS2015) supports for complex datatypes (float/double complex), that cause fail of build at least sockets provider. we are using Intel compiler which has much better support of C99

**Comment by goodell** [comment]
@hoopoepg I just updated the issue text based on your feedback.  Thanks for providing it.  Please let me know if I've filled out the table incorrectly.

Can you explain a bit further the way that the VS project build system works, and how you envision it integrating with any of the existing build system?  Our current build system works like this (as you probably know):

```
- autoreconf, which generates:
   - {configure.ac,**/*.m4} --> configure
   - {Makefile.am,**/Makefile.include} --> Makefile.in
   - config.h.in
- configure, which generates and runs config.status, which itself generates when run:
   - ${foo}.in --> ${foo}, notable values of ${foo}:
     - config.h
     - Makefile
- make, which builds all source files into a library and the fi_info utility
- make install, which installs the library, headers, and fi_info to ${prefix}
```

Does the VS project file provide equivalent build functionality for *all* of those steps?  Or is there some part of that autotools build system that will be shared with the VS project system?

**Comment by hoopoepg** [comment]
windows build based on VS project files are much more "static" that linux: there are no configuration scripts, autotools, etc... fortunately windows systems have quite similar build configurations, that is why we planned to use static config.h header. set of providers may be configured using preprocessor directives only (by modifying command line or config.h content)

makefiles may be used on windows, but VS makefile are different from Linux (yeah, windows is completely different from Linux :) ), but it requires bit complex environment preparation (call environment batch files prior to build launch), and manual handling of build content (VS project is configured using GUI)
