### ISSUE TITLE
add simple out of tree provider to CI testing

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#2047]
Discussion in #2046 makes it clear that if we continue to support out of tree providers, we should be running at least some minimal test build with a (possibly dummy) out of tree provider in the continuous integration testing.

A small dummy provider would be fine.  So would a static snapshot of some actual provider like verbs or sockets (if we add support to them for out-of-tree builds) that can actually build in the CI environment.

**Comment by shefty** [comment]
DL providers are tested as part of CI.
