### ISSUE TITLE
Remove config.h from fi_log.h

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2050]
See https://github.com/ofiwg/libfabric/commit/57dfe4f10fca760914b074ea871d2d7e7d235dec.

However fi_log.h is an external facing file needed by providers.  It should not include build specific files.  An alternate solution to the problem reported in the above commit is needed.

@goodell @jsquyres @hoopoepg

**Comment by goodell** [comment]
oops.. when I wrote that commit I didn't realize that `fi_log.h` was used externally.  Sorry!

Hopefully we'll get that fixed up in #2051.

**Comment by shefty** [comment]
fi_log.h was removed from the installation and moved under a provider directory.  There's no pressing need to remove the config.h include.
