### ISSUE TITLE
lifetime of the err_data field of struct fi_eq_err_entry

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2063]
When an active endpoint gets a rejected event as part of a remotely issued `fi_reject`, the remote application can specify data that will be available in the `err_data` field on the side being rejected. Since this data is managed by the application, what is the lifetime of this data? The man pages don't say how long this data will be valid for. A quick look at the [implementation](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_eq.c#L77) in the sockets provider seems to indicate that the data is only valid until the next call to `fi_eq_(s)read`. If that's the expected lifetime of the data, then it should be documented in the man page. 

@shefty

**Comment by shefty** [comment]
This should match the CQ readerr call, see

https://github.com/ofiwg/libfabric/blob/master/man/fi_cq.3.md

"The err_data field, if set, will reference an internal buffer owned by the provider. The contents of the buffer will remain valid until a subsequent read call against the CQ."

**Comment by bturrubiates** [comment]
> "The err_data field, if set, will reference an internal buffer owned by the provider. The contents of the buffer will remain valid until a subsequent read call against the CQ."

How about I add this info the man page for EQ readerr as well?

**Comment by shefty** [comment]
Yes, please.  With high-fructose corn syrup on top.
