### ISSUE TITLE
verbs provider needs to strengthen libibverbs link check

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#2070]
On a test system, neither libnl or libnl3 is installed, but usnic injects the dependency anyway. This occurs with and without the usnic provider (--disable-usnic). I don't feel that is appropriate to add a library that wasn't required. Especially so if the library can't be found by configure in the first place. 

A quick grep shows that only usnic introduces the libraries:
./prov/usnic/configure.m4:	      [$2_LIBS="-lnl-3 -lnl-route-3"

Result:
> /configure --prefix=$PREFIX --disable-usnic
...
configure: *** Configuring usnic provider
configure: usnic provider: disabled
...
  CCLD     src/libfabric.la
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-route-3
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: cannot find -lnl-3
collect2: error: ld returned 1 exit status
Makefile:3851: recipe for target 'src/libfabric.la' failed

@bturrubiates @hppritcha @sungeunchoi

**Comment by jswaro** [comment]
As a work-around, --disable-verbs is sufficient to remove the problem.

**Comment by jsquyres** [comment]
Yes, you're right that -lnl* shouldn't be added if they're only for a provider who is not being built.

But if `--disable-verbs` is making the problem go away, it's likely that it's the verbs provider that is causing the problem, not usnic.  E.g., libibverbs might be implicitly pulling in those (missing) libnl* libraries.

Can you `make V=1` to see the full link command that is being used to create src/libfabric.so?  That will show whether `-lnl*` is in the link command or not.  If it is, then please upload the config.log output from configure so that we can see who exactly added `-lnl*`.

**Comment by jswaro** [comment]
See https://gist.github.com/jswaro/48645a1f6c1f74b7f5856cd8a7c520b1

**Comment by jsquyres** [comment]
Cool, thanks.

It looks like the usnic configury didn't run at all (as you would expect if you --disable-usnic):

```
configure:17010: *** Configuring usnic provider
configure:18543: usnic provider: disabled
configure:18610: *** Configuring mxm provider
```

So GNU Libtool is likely pulling in -lnl* from elsewhere -- e.g., from libibverbs and/or librdmacm.  You might want to run ldd on those libraries and see if they're (trying to) link in libnl*.

**Comment by jswaro** [comment]
> ldd /usr/lib/libibverbs.so.1.0.0
	linux-gate.so.1 (0xffffe000)
	libnl-route-3.so.200 => /usr/lib/libnl-route-3.so.200 (0xf76da000)
	libnl-3.so.200 => /usr/lib/libnl-3.so.200 (0xf76bc000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xf76a0000)
	libdl.so.2 => /lib/libdl.so.2 (0xf769b000)
	libc.so.6 => /lib/libc.so.6 (0xf74ee000)
	libm.so.6 => /lib/libm.so.6 (0xf74a8000)
	/lib/ld-linux.so.2 (0xf778c000)

Looks like libibverbs and librdmacm are the culprits. I didn't post librdmacm for the sake of brevity. Should the verbs provider be checking for libnl as well, since the libibverbs library seems to require those libraries as well.

**Comment by jsquyres** [comment]
It sounds like the verbs provider should have a better check that it can successfully link against libibverbs, yes.

Github pro tip: use three single ticks to effect a verbatim block:

```
This is in a verbatim block.
    Wheee... I'm intended.
```

See https://help.github.com/articles/basic-writing-and-formatting-syntax/ for more info about Github markdown syntax.

**Comment by goodell** [comment]
> On a test system, neither libnl or libnl3 is installed, but usnic injects the dependency anyway. This occurs with and without the usnic provider (--disable-usnic). I don't feel that is appropriate to add a library that wasn't required. Especially so if the library can't be found by configure in the first place.

The verbs provider obviously needs a stronger link check.  But out of curiosity, how did you end up with a system where you have a `libibverbs.so` that depends on `libnl-3.so` but doesn't have `libnl-3.so` installed?  I think I must be missing something obvious...

**Comment by jswaro** [comment]
Sorry, long response time on my part. The system in question doesn't have libnl*-devel packages installed, so that seemed to be the root of the problem. After installing the packages, it compiled as expected. 

It seems like there should be a stronger check, possibly with user recommendations. I hadn't expected libnl and so that sent me on a goose chase down the wrong path. I would say that this could happen to someone else as well.

**Comment by a-ilango** [comment]
It seems libibverbs version 1.2 and later have a dependency on libnl-3. librdmacm doesn't have this dependency. @jsquyres Do you know if there is a way to check a library's version in configure? Verbs provider should disable itself if it finds libibverbs version > 1.2 and the system doesn't have libnl3 installed.

**Comment by goodell** [comment]
Please, unless absolutely, completely necessary, let's not test versions, instead test for the functionality we actually need.  The root of this bug is coming from a mismatch between the `AC_CHECK_LIB([ibverbs],...)` being indirectly invoked during `configure` and the actual `libtool` behavior at link time.  The `configure`-time check is passing because `libibverbs` is actually linkable if you only specify `-libverbs` on the link line.  But `libtool` [by default attempts to work around systems with less forgiving linkers than Linux](http://www.gnu.org/software/libtool/manual/libtool.html#Inter_002dlibrary-dependencies) and *also* adds `libibverbs.so`'s dependencies (`libnl-3` in this case) to the link line.

Libtool has an internal variable to control this (`link_all_deplibs`), but I'm not sure when/how we should best twiddle it from `unknown` to `no`.  I think it would require some `sed` hackery during `configure`...

**Comment by jsquyres** [comment]
@goodell FWIW, we can add a call to `LT_OUTPUT` any time after the call to `LT_INIT` in `configure.ac`, and then `libtool` will be available in the top builddir.  This could then be used to do an actual link test at configure time (we do something similar in Open MPI, but for a different reason).

It's a little gross, but it's better than doing version testing.

**Comment by goodell** [comment]
Ahh yes, I forgot about this trick.  I actually did something similar years ago in MPICH (for a different sort of bug) but forgot about it.

**Comment by hppritcha** [comment]
I like this approach - a libtool based link test during configure.

**Comment by jsquyres** [comment]
@a-ilango So I think @goodell and I are advising you to add an `LT_OUTPUT` right after the `LT_INIT` in `configure.ac`, and then use the `libtool` script to actually try to link a trivial verbs application (e.g., something that just calls a single `ibv_*()` function and see if it works).

Make sure that your code passes `make distcheck`.

**Comment by jsquyres** [comment]
I took the liberty of renaming this issue to: verbs provider needs to strengthen libibverbs link check

**Comment by shefty** [comment]
Is this request asking that libfabric work around a libibverbs configuration/install issue?

**Comment by a-ilango** [comment]
@shefty I might be wrong but that's how it seems to me.
Quoting @jswaro
> The system in question doesn't have libnl*-devel packages installed, so that seemed to be the root of the problem. After installing the packages, it compiled as expected.

It seems libibverbs didn't check for the presence for libnl*-devel packages when it was built/installed. When libfabric was built, libtool added the libnl dependency of libibverbs.
Quoting @goodell 
> But libtool by default attempts to work around systems with less forgiving linkers than Linux and also adds libibverbs.so's dependencies (libnl-3 in this case) to the link line.

**Comment by goodell** [comment]
> Is this request asking that libfabric work around a libibverbs configuration/install issue?

This depends on your perspective.  You can view it as a libibverbs configuration/install issue that `libnl-*-devel` packages are missing, even though the user technically has an environment/installation that is sufficient to link against `libibverbs`.  The other perspective is that this is a libtool misbehavior on Linux (which is why it gets patched to have different behavior on Debian/Ubuntu) that the libfabric build system should work around in order to give a much more useful error message to the user.

I tend to take the latter view.  IMO it's not expected that one should have to install the `-devel` packages for the transitive closure of dependencies of `libibverbs` in order to simply link against `libibverbs`.

**Comment by jsquyres** [comment]
I agree: the verbs provider just needs to determine if it can build.  If using `libtool` to try to link a trivial app that calls an `ibv_FOO()` symbol fails to link, then the verbs provider cannot build.

The rest of the infrastructure will then kick in:
* If the verbs provider was not specifically requested, it'll just be skipped.  Just like any other provider's m4 that reports that they cannot build.
* If the verbs provider was specifically requested (via `--enable-verbs`), then `configure` will abort on the rationale that a human asked for something that cannot be delivered, so we must abort and let the human figure it out.

**Comment by a-ilango** [comment]
@jsquyres I would need some help here with libtool. I'm not an expert in this area. :) How do I use it link it against a trivial app? Can you point me to some example code? (I tried googling but unable to find one).
The FI_CHECK_PACKAGE macro called from prov/verbs/config.m4 seems to do some link tests using AC_CHECK_LIB. I guess that's not sufficient?

**Comment by jsquyres** [comment]
Correct -- in this case, the `AC_CHECK_LIB` is *necessary*, but not *sufficient* (for the reasons discussed above).  Sorry.  😦 

`libtool` is just a script that is essentially a wrapper around the compiler.  You basically just want to write out a temp `.c` file that calls an `ibv_FOO` function.  Perhaps something like:

```c
#include <verbs.h>
int main(int argc, char **argv) { return ibv_FOO(...); }
```

And then use the `libtool` script to try to compile and link that.  If it succeeds, happiness.  If it fails, sadness.

You can run `libtool --help` to see the CLI options to libtool.  You probably want `--mode=link` to have it try to link the executable.  E.g., something like this (typed off the type of my head -- not tested!):

```sh
# After you have determined that verbs.h is good and that -libverbs works
file=conftemp.$$.c
rm -f $file conftemp
cat > $file <<EOF
#include <verbs.h>
int main(int argc, char **argv) { return ibv_FOO(...); }
EOF
# Assuming you are in the top build directory...
# (I'm not 100% sure $LIBS is necessary here...?)
./libtool --mode=link --tag=CC $CC $CPPFLAGS $CFLAGS $file -o conftemp $LDFLAGS -libverbs $LIBS 2> /dev/null > /dev/null
status=$?
AS_IF([test $status -eq 0 && test -x conftemp], [do the happy thing], [do the sad thing])
rm -f $file conftemp
```

**Comment by a-ilango** [comment]
@jsquyres Thank you for the configure code snippet and explanation. I have a PR that addresses this issue. Please take a look.
