### ISSUE TITLE
dl provider builds are broken

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2072]
PR #2041 broke dl provider builds. I'm working on a fix.

**Comment by shefty** [comment]
I thought travis tested this.  Wasn't provider builds added for all providers as a generic possibility?

**Comment by bturrubiates** [comment]
> I thought travis tested this. Wasn't provider builds added for all providers as a generic possibility?

Looks like Travis tests direct builds, but not dl builds. Our internal Jenkins instance broke a couple of days ago and I hadn't had time to look at it until now. We build the `usnic` and `sockets` provider as dl providers.

**Comment by bturrubiates** [comment]
> I thought travis tested this. Wasn't provider builds added for all providers as a generic possibility?

If you think it would be useful I could add another install target that would build sockets as dl as well. That would add some more time to the CI though. Even then, it built correctly but would return `-FI_ENOSYS` upon running `fi_info`. So to catch this sort of thing would involve a dl build + `fi_info` run.

**Comment by shefty** [comment]
I think testing this would be useful.  It's only a sockets provider build, plus running fi_info.  I wouldn't run through all of fabtests.
