### ISSUE TITLE
dl build is broken

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2107]
This problem seems to have been introduced by #2083. `core_prov` is an undefined symbol in dl builds because they don't link against `src/fabric.c`.

**Comment by jsquyres** [comment]
@hoopoepg Can you have a look at this?  It was your commit that broke dl builds.  Thanks!

**Comment by hoopoepg** [comment]
how can I reproduce dl build?

**Comment by bturrubiates** [comment]
> how can I reproduce dl build?

I'm going to be submitting an additional build step to the Travis config to enable building it. You build it by passing `--enable-<provider>=dl` to the configure script. 

So to build and test `sockets` as dl provider:

```
./autogen.sh
./configure --enable-sockets=dl --prefix=/path/to/prefix
make install
make test
```

Note that you need the install step for dl builds. Then you can just run `make test` and check that `fi_info` returned sockets devices in the list.

**Comment by hoopoepg** [comment]
./configure --enable-sockets=dl --prefix=$HOME/libfabric-test
make && make install && make test
```
ultra ~/devel/libfabric $ make test
./util/fi_info
provider: UDP
    fabric: UDP-IP
    domain: udp
    version: 1.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_UDP
```

**Comment by bturrubiates** [comment]
I should clarify that the build succeeds, but it fails at runtime due to inability to locate a symbol after dlopen.

**Comment by hoopoepg** [comment]
yep, i see... really innovation scheme to customize build :). i will make PR in few minutes

**Comment by hoopoepg** [comment]
I created PR to fix issue: move declaration of core_prov into common.c file. not sure if this is correct location, but file named 'common' is good candidate to store commonly used variable :)

**Comment by bturrubiates** [comment]
> I created PR to fix issue: moved declaration of core_prov into common.c file. not sure if this is correct location, but file named 'common' is good candidate to store commonly used variable :)

Thanks

**Comment by hoopoepg** [comment]
sorry for that. I completely forgot about dl-configured providers. will test this case next time.

have a nice day
