### ISSUE TITLE
Should fi_recvv support FI_MULTI_RECV

### ISSUE THREAD

**Issue by e-harvey** [ofiwg/libfabric#2111]
The man page for FI_MULTI_RECV says "...This flag allows the user to post a single buffer that will receive multiple incoming messages...".  Should the user be able to post a single iovector and do multiple sends to that vector or does the FI_MULTI_RECV flag only apply to single dimensional buffers?

**Comment by shefty** [comment]
We've had discussions as to whether FI_MULTI_RECV should support > 1 iovec.  So far, we've limited multi-recv to a single buffer.  This is primarily a result of application use case -- apps have only requested a single iovec as necessary -- coupled with simplifying the provider implementations.

**Comment by e-harvey** [comment]
Ok, thank you.
