### ISSUE TITLE
sockets: POLLHUP is not handled correctly

### ISSUE THREAD

**Issue by lionkov** [ofiwg/libfabric#2123]
When the socket connection is closed, the server keeps polling forever taking 100% CPU. When debug log is enabled, it prints:

    libfabric:sockets:ep_data:sock_pe_acquire_entry():213<debug> progress entry 0x52292e0 acquired : 127
    libfabric:sockets:ep_data:sock_pe_new_rx_entry():2215<debug> New RX on PE entry 0x52292e0 (127)
    libfabric:sockets:ep_data:sock_pe_new_rx_entry():2218<debug> Inserting rx_entry to PE entry 0x52292e0, conn: 0x6822a00
    libfabric:sockets:ep_data:sock_pe_release_entry():187<debug> progress entry 0x52292e0 released
l

And doesn't stop. It looks that sock_epoll_get_fd_at_index checks only for POLLIN but not POLLHUP.

OS: OSX 10.11 (El Capitan)

**Comment by jithinjosepkl** [comment]
PR #2180 fixes this.
