### ISSUE TITLE
Sockets provider EP_MSG / FI_WAIT_FD functionality not functioning

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2132]
I have been unable to get a test program with EP_MSG and FI_WAIT_FD functionality working properly.

[Here's a gist showing the program](https://gist.github.com/jsquyres/3a23ff0e98e01d6ef67218cb9937f2d0).  I apologize for the length, but it's as short as I could make it.  😲 

The program uses MPI for bootstrapping (just to use an MPI_BARRIER to guarantee that the server has called `fi_listen()` before the client calls `fi_connect()`, and to send the server's address to the client), and then tries to use the FDs associated the the EQs on the client and server to block, waiting for `fi_listen()` and `fi_connect()` to wake up.

The program has a macro, `WANT_FDS` that can be 0 or 1.  When 0, it will not use the FDs associated with the EQs, and will just use `fi_eq_sread()` to wait for the relevant `fi_listen()` and `fi_connect()` events.  When `WANT_FDS` is 1, it gets fds for the EQs, and then blocks in `epoll_wait(2)` before calling `fi_eq_read()` to get EQ events.

When I compile/run the program with `WANT_FDS=0` across two servers, it seems to work fine:

```
$ mpicc -g -O0 ofi-msg-fd-sockets-test.c -o ofi-test -lfabric && mpirun --map-by node --host ivy15,ivy16 --mca btl tcp,self -np 2 ./ofi-test
CLIENT running
SERVER running
SERVER listening on 10.0.20.11:::49215
SERVER sent via MPI to client: 10.0.20.11 / 49215
SERVER waiting for FI_CONNREQ
CLIENT received via MPI: 10.0.20.11 / 49215
CLIENT translated: 10.0.20.11:::49215
CLIENT connecting to 10.0.20.11:::49215
Client connecting...
CLIENT waiting for FI_CONNECT
SERVER got FI_CONNREQ, correct size, and correct data -- yay!
SERVER finished -- waiting for client before teardown
client got FI_CONNECTED, correct size, and correct data -- yay!
CLIENT finished -- waiting for server before teardown
CLIENT tearing down
SERVER tearing down
```

However, when I run the same program compiled with `WANT_FDS=1` across the same two servers, neither of the EQ FDs ever wake up in the client or the server (i.e., the FD associated with the EQ associated with the `fi_listen()` and `fi_connect()` never wakeup from `epoll(2)`).

```
$ mpicc -g -O0 ofi-msg-fd-sockets-test.c -o ofi-test -lfabric && mpirun --map-by node --host ivy15,ivy16 --mca btl tcp,self -np 2 ./ofi-test
CLIENT running
SERVER running
SERVER listening on 10.0.20.11:::37538
SERVER sent via MPI to client: 10.0.20.11 / 37538
SERVER blocking on epoll
CLIENT received via MPI: 10.0.20.11 / 37538
CLIENT translated: 10.0.20.11:::37538
CLIENT connecting to 10.0.20.11:::37538
Client connecting...
CLIENT blocking on epoll
[...hang...]
```

Am I doing something wrong in my program?

**Comment by jsquyres** [comment]
@jithinjosepkl @shantonu Can you guys have a look at this, perchance?  I was trying to trace how the sockets CM code works and was getting quite confused with all the threading... 😦

**Comment by jsquyres** [comment]
@bturrubiates points out that if https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_eq.c#L398 is changed to set `sock_eq->signal=1`, we get a different kind of error -- it tries to call https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_wait.c#L186-L208, but `sock_eq->waitset == NULL`, and it segv's.

**Comment by jsquyres** [comment]
@jithinjosepkl @shantonu Looks like this is a false alarm / bug in my program.  Sorry for the noise!

**Comment by shefty** [comment]
At least I'm not the only person who has online conversations with themselves.  :)

**Comment by shantonu** [comment]
Sorry, for not replying earlier. We had an offsite event :) Please let me know if there's still any issue.

**Comment by jsquyres** [comment]
I'm glad you didn't waste any time looking at my buggy program.  😄
