### ISSUE TITLE
sockets: provider doesn't check if specified source address belongs to local interface

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2146]
Providing a source address during discovery with the `FI_SOURCE` flag always succeeds even if the address is not local or not usable. It seems this is because the address is [resolved using `getaddrinfo`](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_fabric.c#L421-L431), but never checked against the interfaces on the system. This becomes a problem later when the provider attempts to open a connection thread on the address. The provider logs an error about the failed connection thread but does not return an error code. I think the provider should probably return an error code in the event that the connection thread cannot be started [here](https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_ep.c#L968-L972). Instead it seems to start up and wait for a timeout. 

```sh
bturrubi at blade11 :: FI_LOG_LEVEL=debug ./fi_dgram_pingpong -f sockets -s www.google.com
...
libfabric:sockets:ep_data:sock_pe_init_table():2803<debug> PE table init: OK
libfabric:sockets:ep_data:sock_pe_init():2854<debug> PE init: OK
libfabric:sockets:ep_data:sock_pe_progress_thread():2743<debug> Progress thread started
libfabric:sockets:ep_data:sock_pe_add_tx_ctx():2435<debug> TX ctx added to PE
libfabric:sockets:ep_data:sock_pe_add_rx_ctx():2453<debug> RX ctx added to PE
libfabric:sockets:ep_ctrl:sock_conn_listen():311<debug> Binding listener thread to port: 9228
libfabric:sockets:ep_ctrl:sock_conn_listen():327<warn> failed to listen to port: 9228
libfabric:sockets:ep_ctrl:sock_ep_enable():970<warn> cannot start connection thread
libfabric:sockets:ep_data:sock_rx_new_entry():83<debug> New rx_entry: 0x65c760, ctx: 0x645580
libfabric:sockets:ep_data:sock_ep_recvmsg():134<debug> New rx_entry: 0x65c760 (ctx: 0x645580)
5s timeout expired
ft_get_cq_comp(): ../common/shared.c:1313, ret=-61 (No data available)
libfabric:sockets:ep_data:sock_pe_progress_thread():2780<debug> Progress thread terminated
libfabric:sockets:ep_data:sock_pe_finalize():2910<debug> Progress engine finalize: OK
...
```

@shantonu @jithinjosepkl

**Comment by shefty** [comment]
If FI_SOURCE is set, we should add the AI_PASSIVE flag to getaddrinfo.

**Comment by shantonu** [comment]
Ok, will take look.

**Comment by bturrubiates** [comment]
> If FI_SOURCE is set, we should add the AI_PASSIVE flag to getaddrinfo.

The provider does already set `AI_PASSIVE` in this scenario but it also provides a `node` parameter. `AI_PASSIVE` is ignored if `node` is present.

**Comment by shefty** [comment]
> The provider does already set AI_PASSIVE in this scenario but it also
> provides a node parameter. AI_PASSIVE is ignored if node is present.

Gah - that was a dumb thing for getaddrinfo to do.  :P

**Comment by shantonu** [comment]
PR #2168 adds the logic to match source address with available local interfaces. Once the PR is merged, I'll add this as a negative test in runfabtests.sh.
