### ISSUE TITLE
Sockets provider should return correct fi_info attributes when returning FI_CONNREQ event

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#2147]
Scenario:
EP type: FI_EP_MSG. Client uses shared context tx context while server doesn't. Server, when returning a FI_CONNREQ event, returns a fi_info which has ep_attr->tx_ctx_cnt set to FI_SHARED_CONTEXT when it wasn't requested in hints when setting up the passive endpoint.

Sockets provider should check with fi_info that was used to create the passive endpoint when returning a fi_info back to the user.

**Comment by jithinjosepkl** [comment]
PR #2119 fixes this.
