### ISSUE TITLE
sockets: -FI_ENODATA not handled correctly during the discovery

### ISSUE THREAD

**Issue by piroux** [ofiwg/libfabric#2149]
While debugging an external program, we stumbled upon an issue with the sockets provider handling of unresponsive addresses during the network discovery for a fabric object.

More specifically, the [`fi_getinfo` function at line 535](https://github.com/ofiwg/libfabric/blob/4b11ab2c974a8bf7e3c278a28944bba9dfc5717c/src/fabric.c#L535) calls the [provider specific `sock_getinfo` function at line 668](https://github.com/ofiwg/libfabric/blob/4b11ab2c974a8bf7e3c278a28944bba9dfc5717c/prov/sockets/src/sock_fabric.c#L668) which returns with a call to [this internal `sock_node_getinfo` function at line 589](https://github.com/ofiwg/libfabric/blob/4b11ab2c974a8bf7e3c278a28944bba9dfc5717c/prov/sockets/src/sock_fabric.c#L589-L595) which finally calls `sock_ep_getinfo`. However `sock_ep_getinfo` returns `-FI_ENODATA` when given an unresponsive address, so that `sock_node_getinfo` returns `0`. So it means that the sockets provider is returning `0` after its internal getinfo is returning `-FI_ENODATA`, which differs from the others providers when contact can't be made.

The problem is that on this occasion the `fi_info` structure pointer called `cur` in `sock_getinfo` has not been written, thus triggering a segfault a few lines [after](https://github.com/ofiwg/libfabric/blob/4b11ab2c974a8bf7e3c278a28944bba9dfc5717c/src/fabric.c#L548).

The culprit seems to be `sock_node_getinfo`, which catches an error code to return a successful error code. Then the next function fails as expected.

### Steps to reproduce:

- Compile libfabric with the sockets provider only

```
$ ./configure --prefix=$HOME/usnicdev/builds/fi --enable-debug --disable-usnic -disable-udp --disable-verbs --disable-rxm && make -j16 && make install
[...]
***
*** Built-in providers: sockets
*** DSO providers:
***
```
 - Compile fabtests and cd to the bin directory of fabtests

```
[...]
```

 - Run the pingpong test of fabtests :

```
$ FI_LOG_LEVEL=debug ./fi_dgram_pingpong -s blaah
libfabric:core:core:fi_param_define_():224<info> registered var provider
libfabric:core:core:fi_param_get_():273<info> variable provider=<not set>
libfabric:core:core:fi_param_define_():224<info> registered var provider_path
libfabric:core:core:fi_param_get_():273<info> variable provider_path=<not set>
libfabric:sockets:core:fi_param_define_():224<info> registered var pe_waittime
libfabric:sockets:core:fi_param_define_():224<info> registered var max_conn_retry
libfabric:sockets:core:fi_param_define_():224<info> registered var def_conn_map_sz
libfabric:sockets:core:fi_param_define_():224<info> registered var def_av_sz
libfabric:sockets:core:fi_param_define_():224<info> registered var def_cq_sz
libfabric:sockets:core:fi_param_define_():224<info> registered var def_eq_sz
libfabric:sockets:core:fi_param_define_():224<info> registered var pe_affinity
libfabric:sockets:core:fi_param_define_():224<info> registered var dgram_drop_rate
libfabric:core:core:fi_register_provider():122<info> registering provider: sockets (1.0)
libfabric:sockets:fabric:sock_ep_getinfo():425<debug> getaddrinfo failed!
Segmentation fault
```

**Comment by shantonu** [comment]
Thanks for reporting. PR #2150 is submitted to return the correct error code.
