### ISSUE TITLE
windows: determine which wait objects applications want to use

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2158]
Stems from PR #2126, plus other changes that added FI_WAIT_CRITSEC_COND to the API.

We need to determine what wait objects applications on windows are wanting to use.  Then we can limit the windows implementation to targeting only those wait objects (for now).  This will prevent us from needlessly updating code and maintaining unused wait objects.

@hoopoepg

**Comment by hoopoepg** [comment]
actially windows has very close to Posix syncronization API:

1. critical section + conditional variable pair objects + API (already in OFI header)
2. file descriptor based syncronization objects (HANDLE) + API (WaitForSingleObject, WaitForMultipleObjects calls), this is the most general and common used synctoniztion way

additionally there is API to wait for socket (WSAPoll call), but it is rarely used.

**Comment by shefty** [comment]
I understand that we could map most of the OFI wait objects to a windows equivalent.  My question is which ones will actually be used?  If we can defer doing the work because no app will use that wait object, let's defer it.  Since the only app we know of for windows is currently MPI, which native wait objects will it use on windows?

**Comment by hoopoepg** [comment]
ok, I see tour point
as I can see MPICH/CH4 doesn't use this (fi_eq) API at all.
exclude FI_WAIT_FD & FI_WAIT_*_COND from windows build?

**Comment by shefty** [comment]
Yes, please exclude from the build.  Can you update and repush PR #2126?

**Comment by hoopoepg** [comment]
I created another PR: #2342
could you close #2126 for now? it is possible that wait objects will be required in CH4 later for RMA operations.

thank you
