### ISSUE TITLE
fi_getname and fi_enable documentation problem

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#2188]
A newbie to libfabric (as a consumer) has been trying to follow the guidance  in the libfabric documentation at 

http://www.slideshare.net/JianxinXiong/getting-started-with-libfabric

and has found some problems.  First on page 8 of the document there is a hardwired struct used for sizing the buffer to be passed to ```fi_getname```, rather than showing the correct usage of ```fi_getname``` - first call with NULL buffer and ```addrlen``` set to zero, then use the returned value in ```addrlen```.  If the user uses the code snippet in the document, it may or may not work for a given provider.

A more sublte problem is the fact that the document doesn't point out that ```fi_getname``` cannot be used prior to a call to ```fi_enable```.    The way the document is structured, it would seem that ```fi_enable``` is the last thing to be done prior to using the endpoint for communication.  

Note the ```fi_cm``` man page does point out that ```fi_getname``` should only be invoked after an EP has been enabled.

**Comment by j-xiong** [comment]
Thanks Howard. I will fix the document.

**Comment by jithinjosepkl** [comment]
I will also add a check in sockets provider for this. 

Btw, what about passive endpoint? I assume fi_getname() should fail (-FI_EOPBADSTATE?) if fi_listen()/fi_setname() has not been called yet.

Also, can fi_getname be called after fi_setname() even though fi_enable() has not been called?

**Comment by j-xiong** [comment]
@hppritcha The guide has been updated. 
@jithinjosepkl My understanding is that the provider should only fail fi_getname when it can't provide the information. But from the user's point of view, fi_getname is only supposed to be called after the endpoint is enabled (for active endpoint) or fi_setname is called (for passive endpoint).

**Comment by j-xiong** [comment]
The fi_getname man page (under fi_cm) is already quite good in describing the conditions. Now the guide has been updated accordingly, I am closing this issue.
