### ISSUE TITLE
FI_ORDER_NONE really no ordering requested, really!

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2198]
This is the current definition of FI_ORDER_NONE in the man pages.

> FI_ORDER_NONE
> No ordering is specified. This value may be used as input in order to obtain the default message order supported by the provider.

How does an app specify that it really does not want ordering. As in, provider should use whatever ordering it pleases, including not ordering anything at all.

Is it legal for the provider to set FI_ORDER_NONE back to the application after getinfo()? Or does the application expect one of the other ordering bits to be specified after return?

**Comment by goodell** [comment]
`FI_ORDER_NONE` is just an alias for `0`:
```
$ grep -n FI_ORDER_NONE include/rdma/fabric.h
199:#define FI_ORDER_NONE               0
```

That should probably be explicitly called out in the man page, since it might lead to surprising app behavior if the user assumes instead that it is a constant with exactly one bit set.

Would you file a PR with a documentation improvement?

**Comment by j-xiong** [comment]
Yes, FI_ORDER_NONE can be the output, and that's how a few currently providers are doing. Note that the same set of definitions can be used for both message ordering and completion ordering for many providers the support levels are different for these two orderings.

**Comment by j-xiong** [comment]
We could add another alias FI_ORDER_UNSPEC as the input and refer FI_ORDER_NONE as the output value, but that only serves cosmetic purpose.

**Comment by goodell** [comment]
I think clarifying the the alias for `0` should make things clear for any reasonable user, so I'm not sure we need an `UNSPEC` alias.

**Comment by sayantansur** [comment]
@goodell I didn't follow your comment ... why would a user assume it is a constant with a bit set? Shouldn't they assume that FI_ORDER_NONE is some opaque value (which may be zero)?

**Comment by sayantansur** [comment]
@j-xiong both of these statements cannot be true at the same time:

- user uses FI_ORDER_NONE to query for ordering supported by the provider
- provider returning FI_ORDER_NONE if FI_ORDER_NONE was set by the application

If provider returns FI_ORDER_NONE, then effectively, this is not a query operation, and user is being misled?

Things start to become clearer to me if we define FI_ORDER_UNSPEC as 0 and give FI_ORDER_NONE a different value, say 1<<9.

**Comment by goodell** [comment]
> @goodell I didn't follow your comment ... why would a user assume it is a constant with a bit set? Shouldn't they assume that FI_ORDER_NONE is some opaque value (which may be zero)?

@sayantansur they would assume that based on the earlier text in the fi_endpoint(3) man page:

> Message order is determined using a set of ordering bits.  Each set bit
> indicates that ordering is maintained between  data  transfers  of  the
> specified  type.

I.e., all other constants are single bits that are either set or not set.  This isn't opaque, it's necessary knowledge for users to write any encoding/decoding logic.  But `FI_ORDER_NONE` is a constant indicating the *absence* of any bits, making it special.  They can learn this from looking at the header, but IMO it should be called out in the documentation.

**Comment by sayantansur** [comment]
Thanks, yea it makes sense now.

**Comment by j-xiong** [comment]
@sayantansur The first statement is true, the second is not. There is no need for a provider to return FI_ORDER_NONE just because application asks for FI_ORDER_NONE, it can always returns all the ordering it supports. The provider returns FI_ORDER_NONE because if can't guarantee any ordering. This also applies to other ordering bits: e.g. application asks for FI_ORDER_SAS and the provider can return FI_ORDER_SAS | FI_ORDER_WAS.

**Comment by sayantansur** [comment]
@j-xiong Since the second statement cannot be true, then we have to fix the providers you said are doing this.

Ok, then back to the question: how does an application tell the provider that it does not want any ordering? Under the current scheme, is this what the application has to do?

- application sets FI_ORDER_NONE
- provider sets all ordering bits it can support (otherwise, if it simply returns FI_ORDER_NONE, it is misleading)
- application clears out all bits from ep_attr::msg_order when it creates an endpoint

**Comment by j-xiong** [comment]
@sayantansur the providers are doing as the first statement: they returns FI_ORDER_NONE because they don't support any ordering, not because the application asks for FI_ORDER_NONE.

**Comment by j-xiong** [comment]
@sayantansur If the application want a specific ordering, it should set that as part of input to fi_getinfo. Or alternatively it can pass FI_ORDER_NONE as the input but need to check the output to see if the needed ordering is supported by the provider. When creating endpoints, it can (but not necessary) clear the bits it doesn't need, but shouldn't clear the bit it want.

**Comment by sayantansur** [comment]
OK, that sounds good then. Do you mind if I add that in the notes in the man page, so it is clearer?

**Comment by j-xiong** [comment]
Yes, feel free to make the page clearer. In essence, the ordering requirement from application is "minimal requirement" that the provider must support, but the provider has the freedom to support more.
