### ISSUE TITLE
usnic: Properly report thread level

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2207]
The current support is limited to:

`FI_EP_DGRAM`: `FI_THREAD_COMPLETION`
`FI_EP_RDM`: `FI_THREAD_COMPLETION`/`FI_THREAD_DOMAIN`
`FI_EP_MSG`: `FI_THREAD_COMPLETION`/`FI_THREAD_DOMAIN`

The usNIC provider should not allow calls to `fi_domain` to succeed with unsupported thread levels.

**Comment by jsquyres** [comment]
@piroux Could you have a look at this one?

**Comment by jsquyres** [comment]
This should be easy enough to do in time for v1.4.0.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
