### ISSUE TITLE
providers: Support FI_THREAD_SAFE across all endpoints

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2208]
If a provider below is checked, it supports FI_THREAD_SAFE.  This issue can be closed when all providers below are checked:
- [ ] gni
- [ ] mxm
- [ ] psm
- [x] psm2
- [ ] rxd
- [ ] sockets
- [ ] udp
- [ ] usnic
- [x] verbs

**Comment by jsquyres** [comment]
I'm assuming this can't be done in time for v1.4.0.

Provider authors: please check off your provider if you support `FI_THREAD_SAFE`.

**Comment by evgeny-leksikov** [comment]
verbs/RDM is not thread safe now, it can't be done for 1.4, probably for 1.5.
