### ISSUE TITLE
fi_ep_alias with TX/RX only op-flags?

### ISSUE THREAD

**Issue by jithinjosepkl** [ofiwg/libfabric#2223]
Man page for fi_ep_alias says that -  "the flags must include FI_TRANSMIT or FI_RECV (not both) with other flags OR’ed to indicate the type of data transfer the flags should apply to"

So, if an application calls fi_ep_alias() with FI_TRANSMIT, what will be the default RX op flags for this alias EP? (and vice-versa).
- Will it be copied from the base EP? Or will it be reset to 0?
- Or is it expected that the application has to do setopflags() explicitly on the new alias-EP?

Will it be beneficial to have separate arguments to specify TX and RX op-flags?

**Comment by jithinjosepkl** [comment]
Btw, the following signature should help in specifying both tx and rx op-flags :

```
int fi_ep_alias(struct fid_ep *ep, struct fid_ep **alias_ep, 
                             uint64_t tx_flags, uint64_t rx_flags);
```

Any thoughts?
@j-xiong @sayantansur @jsquyres @bturrubiates @goodell @hppritcha

**Comment by bturrubiates** [comment]
From a usability perspective, I think it's most intuitive to me that the alias inherit the attributes of the base endpoint unless specifically set by giving flags to the alias call.

> Or is it expected that the application has to do setopflags() explicitly on the new alias-EP?

I think it should inherit the attributes of the base endpoint that was not changed by the `fi_ep_alias` call, and to change those a separate call to `fi_control` has to be made. 

Introducing a new call, or modifying `fi_ep_alias` might be a good API contribution for 2.0.0.  I can see how being able to set both at once would be convenient over separate calls to `fi_ep_alias` and `fi_control`.

**Comment by j-xiong** [comment]
I agree that the attributes should be inherited if not set with the corresponding flags. The proposed API change also makes sense for a future major release.

**Comment by sayantansur** [comment]
@bturrubiates one of the usages of alias is to be able to remove flags from an endpoint. if the aliased endpoint ended up inheriting the flags, then it would become impossible to remove flags from an endpoint that was once created.

**Comment by jithinjosepkl** [comment]
Agree with @sayantansur. I think it would be good to specify these flags explicitly.

**Comment by j-xiong** [comment]
@sayantansur If you set the flags explicitly, it overwrites the old one. why it becomes impossible to remove flags?

**Comment by sayantansur** [comment]
@j-xiong yea, that's what I was saying. Ben wanted the aliased EP to inherit the flags that weren't specified ... in that case we cannot remove the flag. I was just pointing that out.

**Comment by j-xiong** [comment]
@sayantansur @bturrubiates I think what Ben (and I) meant was that if one set tx_flags explicitly then the rx_flags should be inherited and vice versa.

**Comment by sayantansur** [comment]
In the new interface or the old one? I think that's confusing me.

Also, how does alias relate to SETOPSFLAG? Is alias the same as duping an endpoint and then applying SETOPSFLAG?

**Comment by bturrubiates** [comment]
> @sayantansur @bturrubiates I think what Ben (and I) meant was that if one set tx_flags explicitly then the rx_flags should be inherited and vice versa.

Yes, the man page currently specifies that you specify flags and EITHER `FI_TRANSMIT` or `FI_RECV`. So if you want to clear the transmit flags then you would pass in solely `FI_TRANSMIT`. The receive flags would be inherited from whatever was set in the endpoint before the alias call. 



> Also, how does alias relate to SETOPSFLAG? Is alias the same as duping an endpoint and then applying SETOPSFLAG?

That's the way I was thinking of it. It's essentially an operation that combines a duplication and setting EITHER the transmit or receive flags. If you want to change both the transmit AND receive flags, then it becomes a call to `fi_ep_alias` followed by a call to `fi_control`.

@j-xiong @jithinjosepkl Do you agree with that assessment?

**Comment by sayantansur** [comment]
> Yes, the man page currently specifies that you specify flags and EITHER FI_TRANSMIT or FI_RECV. So if you want to clear the transmit flags then you would pass in solely FI_TRANSMIT. The receive flags would be inherited from whatever was set in the endpoint before the alias call.

This brings back to the original question. How do I get an aliased EP that has a subset of both TX and RX flags?

Coming to think of it, does SETOPSFLAGS refer to TX flags or RX flags?

**Comment by bturrubiates** [comment]
> This brings back to the original question. How do I get an aliased EP that has a subset of both TX and RX flags?

I believe that would require a call to `fi_ep_alias` where you first change the transmit flags, followed by a call to `fi_control` + `FI_SETOPSFLAG` to set the receive flags.

> Coming to think of it, does SETOPSFLAGS refer to TX flags or RX flags?

`fi_control` + `FI_SETOPSFLAG` depends on whether the `FI_TRANSMIT` or `FI_RECV` bit was set. It works in the same way that `fi_ep_alias` works.

**Comment by jithinjosepkl** [comment]
I think the confusing part is about the assumption that flags will be inherited. And if app wants to set both TX and RX flags for an alias endpoint, additional call to fi_control is required. The new interface solves both these issues.

**Comment by j-xiong** [comment]
@jithinjosepkl  Yes I agree the API change is useful.

**Comment by bturrubiates** [comment]
> I think the confusing part is about the assumption that flags will be inherited. And if app wants to set both TX and RX flags for an alias endpoint, additional call to fi_control is required. The new interface solves both these issues.

It is confusing, and I agree that the new interface solves the issue. The reason I think it should be inherited if not being set is because it is conceptually equivalent to a duplication followed by setting the flags for only one half.

**Comment by j-xiong** [comment]
@bturrubiates Yes I agree with what you said.

**Comment by shefty** [comment]
Is there a use case for creating an alias that changes both the send and receive flags?

The intent was to inherit the base EP flags.  Note that fi_ep_alias may alias a tx or rx context, and not necessarily an ep that supports both sets of flags.

**Comment by sayantansur** [comment]
I don't remember if there was a use case that we thought of at that time. Updating the man page to be more clear as to what happens might be sufficient. Currently, it doesn't speak of the inheritance of the flags that we didn't set, and implies otherwise. Specifically, this line may have sparked the confusion.

>  This will override the transmit and recieve attributes of the alias endpoint.

**Comment by shefty** [comment]
I have an update to the man page, which I will add to my abi 1-1 PR.  I'm hesitant to add a new wrapper to support changing both the tx and rx flags at the same time, mostly because I'm not seeing a strong use case for having that functionality.  Is there even a strong case for changing the Rx flags?

**Comment by sayantansur** [comment]
I think your man page update should be good enough for now.
