### ISSUE TITLE
sockets provider fi_av_insert failure

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2226]
I have a sample code that shows odd behavior in the sockets provider: https://github.com/jsquyres/random-libfabric-tests/blob/master/ofi-av-test.c.  It's a simple test that essentially makes an AV of size 32, and then:

```
for (i = 0; i < 128; ++i) {
    fi_av_insert(...);
    fi_av_remove(...);
}
```

The test shows a single failure when fi_av_insert'ing the 32nd address -- all other insertions succeed.

@jithinjosepkl Could you have a look?

**Comment by jsquyres** [comment]
Per https://github.com/ofiwg/libfabric/pull/2261#issuecomment-239242466, @jithinjosepkl said:

> We plan to add garbage collection of deleted entries sometime soon. (which will fix #2226).

Do you have an ETA for this, perchance?

**Comment by jsquyres** [comment]
I note, too, that the reproducer only fails *once* out of 128 calls.  If the current sockets provider is not actually freeing slots in the AV, shouldn't (128-32) of the calls fail?

**Comment by shantonu** [comment]
@jsquyres, sockets provider reports error when number of entries exceeds 32 as it was set as <code>count</code> parameter in av attribute. Next time, it grows the av table, and doesn't get into the error. I have started working on cleaning up av entries. I hope to get it done by few days.

According to manpage <code>count</code>"Indicates the expected number of addresses that will be inserted into the AV. The provider uses this to optimize resource allocations." So what should be the behavior of the provider if more than <code>count</code> is inserted without removing? Should it report an error for all the following inserts?

31 fi_av_insert(...); //success
32 fi_av_insert(...); //error
33 fi_av_insert(...); //error
...

**Comment by jsquyres** [comment]
Good question.  I don't know if there is a good answer.  There are many types of applications where the number of peers isn't known ahead of time, and there's currently no explicit API to expand the AV.

My $0.02: providers (including the sockets provider) should treat the expected number as a hint.  But if the caller uses more slots and asked for, if the provider can expand the AV, then do so.  Otherwise, error.

The current sockets provider of "error once but then succeed after that" is a little weird.

**Comment by shantonu** [comment]
Yeah, I need to fix the logic. Probably, we can replace the error log to debug log if <code>count</code> attribute is treated as a hint. Again, then the hint becomes obsolete when the provider expands the AV. May be it should be clarified in the manpage.

**Comment by j-xiong** [comment]
@shantonu What the man page says ("The provider uses this to optimize resource allocations") is sufficient to suggest that it's not a hard limit. It's a hint for the initial resource allocation -- if the application chooses the value correctly, the provider can minimize the need of expansion while doesn't waste on allocating too much resource. The provider doesn't need to remember this hint after the initial creation of the AV, it should track the actual size instead.

**Comment by shantonu** [comment]
Ok, makes sense. Then the log should be a debug log when insert exceeds the hint.

**Comment by shantonu** [comment]
@jsquyres, I have updated sockets provider behavior (https://github.com/shantonu/libfabric/tree/pr/sockets-av) based on @j-xiong's explanation. Now it passes <code>ofi-av_test</code>. I didn't have to add garbage collection as socket provider expands AV.

I can submit a PR that just fixes this bug if you need it right away and submit the implementation of garbage collection in another PR. Let me know what you prefer.

I also noticed the discussion on #2261, which points out the following statement needs to be updated if we allow garbage collection of av indices after <code>fi_av_remove</code>.

_All resources associated with the indicated addresses are released, and no future references
to either the mapped address (in the case of FI_AV_MAP) or index (FI_AV_TABLE)
are allowed._

**Comment by jsquyres** [comment]
@shantonu FWIW, I think the garbage collection is a Good Thing -- having the table grow without bound containing only stale handles seems bad.  So I think #2277 is fine -- no need for a separate PR just to fix the one thing.

As for that statement in the docs, ...hmmm.  On the one hand, being able to *know* that AV handle/index X is stale and will never be used again is pretty nice for development / debugging.  But on the other hand, that might not be a realistic requirement for long-running libfabric-based applications (e.g., if your index is only 16 bits, it doesn't take too long to cycle it).

I'd be inclined to interpret that statement as meaning that you can't use the handle after you release it until it is returned again in by a new insert.  It might be worth clarifying that -- do you want to file a PR with slightly improved text?

**Comment by shantonu** [comment]
Thanks Jeff. I'll submit a PR with better wording.
