### ISSUE TITLE
synchronous fi_av_insert has no way of returning error information 

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2229]
When using the synchronous version of `fi_av_insert` (configured without flag `FI_EVENT`), the man page states that the return value of `fi_av_insert` will be the number of successful insertions to the AV. Upon failure, the `fi_addr` parameter will be set to `FI_ADDR_NOTAVAIL` (this doesn't seem to be documented in the man pages, but many providers seem to do this). Once an insert has failed, there doesn't seem to be a way to determine the nature of the failure.

It would be great if we could keep the current function signatures, but I think we are limited by the amount of error reporting we can currently do and will need to explore the possibility of a different function or error discovery mechanism in a future API update. Perhaps in a future release, we could add another AV call or modify the AV insertion call to communicate the error reason in the event of a failure.

Maybe something like: 

``` c
int fi_av_insert2(struct fid_av *av, void *addr, size_t *count, fi_addr_t *fi_addr, uint64_t flags, void *context);
```

> Insertion calls for an AV opened with synchronous operation will return 0 on success, or the error code corresponding to the first failed insertion. On output the count parameter will be set to reflect the number of addresses successfully inserted, this can be used as an index to determine which address insertion failed in the event of a negative return code. If the function has completed with no errors, then the count parameter should be unchanged.
## 

This will probably take more thought, but we should think about whether this is a problem we want to try solving in a future release.

Thoughts? 

@goodell @jsquyres @jithinjosepkl @hppritcha @sayantansur @j-xiong

**Comment by j-xiong** [comment]
Each failed address will generate an entry in the associated event queue, regardless of the FI_EVENT flag. The FI_EVENT only affects the behavior of successful address insertion.

**Comment by jithinjosepkl** [comment]
Sockets provider is implemented this way (every failed insertions will generate an EQ error entry, if the AV is bound to EQ). The 'data' field in the EQ event indicates the index of the entry that was failed. But, agree that it is not documented in the man pages.

**Comment by bturrubiates** [comment]
> Sockets provider is implemented this way (every failed insertions will generate an EQ error entry, if the AV is bound to EQ). The 'data' field in the EQ event indicates the index of the entry that was failed. But, agree that it is not documented in the man pages.

Hmm, that's an interesting idea to explore but it seems kinda contrary to the idea of a synchronous insertion function. I think there should be a discovery method that doesn't involve using a feature typically reserved for asynchronous modes of execution. 

Also, perhaps I should also submit some man page changes to indicate that `FI_ADDR_NOTAVAIL` will be used for addresses that fail.

**Comment by jithinjosepkl** [comment]
>Hmm, that's an interesting idea to explore but it seems kinda contrary to the idea of a synchronous insertion function. I think there should be a discovery method that doesn't involve using a feature typically reserved for asynchronous modes of execution.

Agree that we are using a feature typically reserved for async modes (also, a little different compared to other APIs). But I have a feeling that the current scheme serves the purpose.

```
num = fi_av_insert(..., count);
if (num != count) {
   /* at this time EQ is guaranteed to have info of failed entries */
   <read EQ for details on (count - num) failed addresses>
}
```

**Comment by j-xiong** [comment]
The fi_av_insert call used to return error code but the count parameter was input only. The caller could go through the fi_addrs output the count the number of failures encountered.  But in essence, the old version is similar to the fi_av_insert2 proposed above.

**Comment by bturrubiates** [comment]
> Agree that we are using a feature typically reserved for async modes (also, a little different compared to other APIs). But I have a feeling that the current scheme serves the purpose.

Okay, does an AV need to be bound to an EQ? What if an AV is opened in synchronous mode and not bound to an EQ? I think that having the `FI_EVENT` flag implies that an EQ isn't necessary. 



> The fi_av_insert call used to return error code but the count parameter was input only. The caller could go through the fi_addrs output to count the number of failures encountered. But in essence, the old version is similar to the fi_av_insert2 proposed above.

Hmm that's true, so you mean something like this? 

```c
err = fi_av_insert(..., count);
if (err) {
    for (i = 0; i < count; i++) {
        if (fi_addr[i] == FI_ADDR_NOTAVAIL) {
            first_failed = fi_addr[i];
            break;
        }
    }
}
```

**Comment by jithinjosepkl** [comment]
>Okay, does an AV need to be bound to an EQ? What if an AV is opened in synchronous mode and not bound to an EQ? I think that having the FI_EVENT flag implies that an EQ isn't necessary.

Yeah, binding to EQ isn't necessary. But, if the application needs additional info on failed insertions, AV-EQ binding should be done.

**Comment by j-xiong** [comment]
>Hmm that's true, so you mean something like this?
```c
err = fi_av_insert(..., count);
if (err) {
    for (i = 0; i < count; i++) {
        if (fi_addr[i] == FI_ADDR_NOTAVAIL) {
            first_failed = fi_addr[i];
            break;
        }
    }
```
That's mostly how it would be done with the old fi_av_insert, except that the `first_failed` assignment doesn't do anything useful.

**Comment by bturrubiates** [comment]
> That's mostly how it would be done with the old fi_av_insert, except that the first_failed assignment doesn't do anything useful.

Yeah, except in current synchronous `fi_av_insert` the `err` parameter would probably be `0` instead of a negative error code. 

Right, I was just trying to demonstrate that traversing the array is how the invalid index is found. I should have probably made that an index instead of an `fi_addr_t`.

**Comment by bturrubiates** [comment]
> Sockets provider is implemented this way (every failed insertions will generate an EQ error entry, if the AV is bound to EQ). The 'data' field in the EQ event indicates the index of the entry that was failed. But, agree that it is not documented in the man pages.

What does the sockets provider currently put on the EQ? By that I mean, how do you determine it corresponds to an AV failure? Does the `fid` field refer to the AV?

**Comment by jithinjosepkl** [comment]
Yes, fid refers to the AV. Also, the "context" field corresponds to the context passed in during fi_av_insert(), and ''data" indicates the index.

**Comment by j-xiong** [comment]
> Yeah, except in current synchronous fi_av_insert the err parameter would probably be 0 instead of a negative error code. 

In current synchronous call the err would be a non-negative value < count if any error happens. otherwise the old version and the current version work similarly in terms of finding the first error index. The main difference of the two versions are the old one can return an error code while the new version has the success count ready. Sometime in the past it was determined that the success count is more important than the reason of failure :)

**Comment by bturrubiates** [comment]
> In current synchronous call the err would be a non-negative value < count if any error happens. otherwise the old version and the current version work similarly in terms of finding the first error index. The main difference of the two versions are the old one can return an error code while the new version has the success count ready. Sometime in the past it was determined that the success count is more important than the reason of failure :)

I see, well the `FI_ADDR_NOTAVAIL` isn't documented so I'll submit a PR to document that. Well, I guess the new version allows all of the inserts to be attempted instead of stopping at the first erroneous insert, but it makes it difficult to know what happened. 

When was this changed?

**Comment by j-xiong** [comment]
That was before we started using markdown for the man pages ... it would take more effort to trace back further but that doesn't really matter much.

**Comment by bturrubiates** [comment]
> That was before we started using markdown for the man pages ... it would take more effort to trace back further but that doesn't really matter much.

Yeah, sounds like it's been a while 👌

**Comment by goodell** [comment]
> I see...I still dislike that there isn't a way to receive an error notification without having bound an EQ.

Agreed.  The current system only scores a [3 out of 10 on the hard to misuse scale](http://ozlabs.org/~rusty/index.cgi/tech/2008-03-30.html).

**Comment by sayantansur** [comment]
I agree with @goodell and @bturrubiates - returning the number of successful entries is non obvious, and I have made a mistake with this more than once only to be corrected by @jithinjosepkl :)

**Comment by bturrubiates** [comment]
@goodell @sayantansur 

Any suggestions on what might be more intuitive for a future API changing release?

**Comment by sayantansur** [comment]
Dunno, what you suggested isn't bad. i.e. turn 'count' into an in/out parameter.

Otherwise, we could also return the error code corresponding to the first failure, and set any failed addresses lookups to FI_ADDR_UNSPEC. Would that work?

**Comment by j-xiong** [comment]
I would suggest:
(1) return error number on failure and 0 on success;
(2) add one output argument, be it succ_count / error_count / error_array will need to be debated.

A new argument is more intuitive than an input/output argument, and the extra argument will force the user to rewrite the code instead of failing unexpectedly if only the return value is changed.

**Comment by goodell** [comment]
I thought your proposal was basically fine, though I'll admit I didn't spend a ton of time thinking about it.  I don't love in/out parameters and usually prefer to separate them into separate input and output parameters instead, but that's more of a style question.

**Comment by bturrubiates** [comment]
> Otherwise, we could also return the error code corresponding to the first failure, and set any failed addresses lookups to FI_ADDR_UNSPEC. Would that work?

I think that would work, it was briefly mentioned above. This maintains the function signature but changes the semantics of the return value. Applications would likely need an update.

I think it makes sense, but finding the errored entry involves re-iterating over the array. 



> I would suggest:
> (1) return error number on failure and 0 on success;
> (2) add one output argument, be it succ_count / error_count / error_array will need to be debated.

I think this is more in line with usual error handling, but having a second size parameter might seem a bit kludgy. 



> A new argument is more intuitive than an input/output argument, and the extra argument will force the user to rewrite the code instead of failing unexpectedly if only the return value is changed.

Hmm you have a point. Changing the function signature would definitely require application maintainers to be aware of the change.

**Comment by sayantansur** [comment]
> I think it makes sense, but finding the errored entry involves re-iterating over the array.

Yea, I was just trying to see if the existing function would work. I like returning the error index much better as a different argument.

**Comment by hppritcha** [comment]
> I think it makes sense, but finding the errored entry involves
> re-iterating over the array.
>
> Yea, I was just trying to see if the existing function would work. I like
> returning the error index much better as a different argument.
>

I like this solution.  I'd prefer to avoid changing the interface.  I think
for the async approach providers should behave consistently.  I'll open an
issue for gni provider to capture how sockets provider reports error info
in EQ events.

**Comment by bturrubiates** [comment]
> I think
> for the async approach providers should behave consistently.  I'll open an
> issue for gni provider to capture how sockets provider reports error info
> in EQ events.

Wait, what do you mean by this? What specifically are you going to make the gni provider do?

**Comment by bturrubiates** [comment]
So I talked with @goodell about this a little more on the phone. We still have a while before release 2.0.0 so there is still time to plan and talk about this more. I wrote out a list of all the ideas we threw around.  

--

#### 1

> Change the return value for synchronous `fi_av_insert` to be 0 on success and a negative error code on failure. Given an array of addresses to resolve, the return value will represent the failure reason for the first erroneous insertion. The failed resolutions will contain the value `FI_ADDR_NOTAVAIL`. The failed index can be found by iterating over the `fi_addr` array parameter and comparing against `FI_ADDR_NOTAVAIL`.

**Good**: 
- Doesn't require changing the function signature.
- More closely follows return value semantics for other API calls.

**Bad**:
- Semantic change is easy to confuse between versions and won't enforce the application maintainer updating the code. 
- Stalls the rest of the insertions if a single insertion fails.

--

#### 2

> Change the count parameter to be an in-out for the synchronous version. The return value will represent the error code and the count parameter on output will represent how many successful insertions occurred.

**Good**:
- Function signature changes so a compiler warning is issued for applications that may be used to using an older version.

**Bad**:
- Stalls the rest of the insertions if a single insertion fails. 
- In-out parameters can be confusing. 

--

#### 3

> Change the function signature of `fi_av_insert` to accept an array of integers representing the return value for each insertion. This is unused in the asynchronous version and may be `NULL`.

**Good**:
- Function signature changes so a compiler warning is issued. 
- Can get a return value for each insertion separately.
- All insertions can be attempted, even if a failure is encountered.

**Bad**:
- Array of integers is awkward and unused in asynchronous case.

--

Now at this point, it's clear that adding a count parameter or changing one of the parameters will be awkward for the asynchronous interface. Should we consider separating the synchronous and asynchronous versions (à la read/sread)?

--

#### 4

> Split the insertion functions into asynchronous and synchronous (`fi_av_insert` and `fi_av_sinsert`). Make the synchronous version accept an array of integers to store the results for each insertion. This allows the insertions to continue in the event that one has failed.

**Good**:
- Aligns more closely with other APIs that have separate functions for sync v. async (cq_read/cq_sread). 
- Can get return value for each insertion separately. 

**Bad**:
- Changes the programming model between V1.x.x and V2.x.x.

--

#### 5

> Require all AVs to be asynchronous and get rid of the synchronous mode of operation

**Good**:
- Simplifies the AV insertion API without adding/removing calls and removes the overloaded sync/async use of the `fi_av_insert` function. 

**Bad**:
- There may be situations where a synchronous insertion is necessary or more performant.

**Comment by sayantansur** [comment]
Thanks for the summary, @bturrubiates! I would like to add that for (1) and (2), there is no need "stall" the insert operations for the rest of addresses. It could be that we only return the error code for first, but populate all the entries we can. Any insertions that failed will be FI_ADDR_NOTAVAIL.

Of all the suggestions, I like (4) the best.

**Comment by bturrubiates** [comment]
> Thanks for the summary, @bturrubiates! 

👍 

> I would like to add that for (1) and (2), there is no need "stall" the insert operations for the rest of addresses. It could be that we only return the error code for first, but populate all the entries we can. Any insertions that failed will be FI_ADDR_NOTAVAIL.

Yes, but I think that makes assumptions about the failure being the same. Say I try to insert three addresses and the first one is a success, the second one fails with `EHOSTUNREACH`, and the third one fails with `EINVAL` or something like that. Returning `EHOSTUNREACH` only says something about the second insertion and doesn't indicate why the third failed. 



> Of all the suggestions, I like (4) the best.

I like that one too, but it involves the most changes. Let's see if people will get on board with it.

**Comment by j-xiong** [comment]
I actually prefer (3) over (4), the reason is that with (4) the existing usage of synchronous fi_av_insert would silently change the behavior to asynchronous, increasing the possibility of unexpected error. With (3) explicit change to the code is needed to pass compilation.

For (3), we can let the "errors" parameter be optional. For those who don't care about the reason of the failure (like how the current fi_av_insert is used) NULL can be passed, so do asynchronous calls.

**Comment by sayantansur** [comment]
We will bump the ABI, so there will be a link time issue if the app is not linking to the right version?

**Comment by j-xiong** [comment]
It can be linked to the right library, but the user may be unaware that the same fi_av_insert now behaves differently. He needs to change the code but it's possible he doesn't realize that until after debugging some mysterious failures.

**Comment by bturrubiates** [comment]
I think it's pretty clear that **3** and **4** are going to be the popular ones. I think it's a good idea to keep track of our options so that if we have any other considerations for AV interface updates, we can make sure they work with each other.

**Comment by jithinjosepkl** [comment]
+1 on (4).  
And, if I understand correctly, fi_av_insert will behave like the current one with FI_EVENT flag, and fi_av_sinsert will accpet an 'optional' int array for getting the return values for each address.

**Comment by bturrubiates** [comment]
I just realized I should have made these separate comments to allow a `+1` on them. 



> And, if I understand correctly, fi_av_insert will behave like the current one with FI_EVENT flag, and fi_av_sinsert will accpet an 'optional' int array for getting the return values for each address.

Yeah, exactly.

**Comment by shefty** [comment]
If the app really cares about *why* an insertion fails, it can call fi_av_insert in a loop (if we set errno) or use the async version.  On a failure, a provider doesn't know if it should attempt to continue insertions (which could take a significant amount of time) or just abort.

I dislike the idea of passing in an array of status values.  That sort of defeats the advantage of the symmetric insertion case.

**Comment by shefty** [comment]
Option 6:
Add a new flag: FI_ERRNO
When synchronously inserting into an AV, if this flag is set, then the context parameter references an array of integers.  Failures to insert an address into the AV will result in a failure code being written to the corresponding array location.  Successful insertions will be updated to 0.

Upon encountering an error, providers will abort any remaining insertions.  Aborted addresses will fail with the error code FI_EAGAIN.  Note that the addresses may be processed by the provider in any order, singly or in groups.

**Comment by shefty** [comment]
Note that if we go with option 6, no API update is needed.  The behavior of the current interface is simply changed when the new flag is provided.
