### ISSUE TITLE
fi_poll() with counter - missing threshold information?

### ISSUE THREAD

**Issue by jithinjosepkl** [ofiwg/libfabric#2240]
It seems there is no way to specify the threshold for counters in fi_poll().
For example, when an app calls fi_poll(), when should it succeed for a counter? 

For CQ, fi_poll() makes sense, fi_poll() just succeeds when there is an unread entry in the CQ. But, for counters we don't have a way to specify the threshold value (like in fi_cntr_wait). 
(Please correct me if I am missing somehting here.)

Do we need something like an fi_cntr_poll(), which takes the threshold values as well?

**Comment by bturrubiates** [comment]
> It seems there is no way to specify the threshold for counters in fi_poll().
> For example, when an app calls fi_poll(), when should it succeed for a counter?

Well if we were trying to match the semantics of `fi_poll` on a CQ, then shouldn't it succeed whenever the counter has changed at all? I think this requires keeping some internal state or something. So maybe an implementation of `fi_poll` for a counter would be something like: 

```c
current = fi_cntr_read()
progress_counter()
fi_cntr_wait(current + 1)
```

I haven't implemented / thought about counters very much so this may not be entirely accurate.



> Do we need something like an fi_cntr_poll(), which takes the threshold values as well?

Well isn't `fi_poll` for a CQ already like having `threshold = 1`?

**Comment by jithinjosepkl** [comment]
>Well if we we are trying to match the semantics of fi_poll on a CQ, then shouldn't it succeed whenever the counter has changed at all?

Yeah, but changed wrt what value? For CQ, we can detect a new entry by searching for an unread entry in CQ. But for counter, we cant detect a new value right?

**Comment by jithinjosepkl** [comment]
I mean my concern is with the usage of fi_poll() with counters:
say app does this:

```
value = fi_cntr_read();
fi_poll(pollset_with_cntr);
```

Suppose the counter value was changed after fi_cntr_read() and before fi_poll(), and if we go with the fi_poll() implementation mentioned above, we will not be detecting a new counter update. This can cause fi_poll() to wait infinitely (if timeout=-1).

**Comment by bturrubiates** [comment]
> Suppose the counter value was changed after fi_cntr_read() and before fi_poll(), and if we go with the fi_poll() implementation mentioned above, we will not be detecting a new counter update. This can cause fi_poll() to wait infinitely (if timeout=-1).

`fi_poll` doesn't take a timeout. 

> Yeah, but changed wrt what value? For CQ, we can detect a new entry by searching for an unread entry in CQ. But for counter, we cant detect a new value right?

Well I was thinking something along the lines of: 

```c
int poll(pollset, context, count)
{
    int current;
    int ret;

    pollset_foreach(pollset, item) {
        switch(item->fclass) {
        case FI_CLASS_CQ:
            // stuff here
            break;
        case FI_CLASS_CNTR:
            current = fi_cntr_read(item);
            progress_counter_operations(item);
            ret = fi_cntr_wait(cntr, current + 1, 5)

            if (ret != -FI_ETIMEDOUT)
                // copy the context over and mark it a success
        }
    }
}
```

Obviously this is not real C and oversimplified 😄  It's true that this will not return any contexts for the case you mentioned, but it won't wait indefinitely.

Does that make sense or am I misunderstanding the problem?

**Comment by j-xiong** [comment]
I agree with @bturrubiates 

For counter, any update ("add" or "set") would cause the associated wait object be signaled. That is the condition of its context being returned via fi_poll. The new value is not even necessary greater than the old one (due to "set"). The exact counter value should be tracked by the application.

**Comment by jithinjosepkl** [comment]
@bturrubiates - I was talking about the case in which the counter was incremented after application calling fi_cntr_read() and before calling fi_poll(). 

So, in fi_poll() implementation, the ```current``` value is somethig app has not seen. But fi_poll() does not indicate this as success, even though the counter value was updated.
(Btw, thanks for pointing out the timeout, I missed that)

@j-xiong - Agree that fi_poll() should signal when counter is updated. 
May be we should keep track of ```last_cntr_read``` value, and then we can make fi_poll() succeed if the ```last_read_val``` is different than current value. I think this will solve it.
If you all agree, I can go ahead and update this in sockets provider.

**Comment by bturrubiates** [comment]
> So, in fi_poll() implementation, the current value is somethig app has not seen. But fi_poll() does not indicate this as success, even though the counter value was updated.
> (Btw, thanks for pointing out the timeout, I missed that)

Ohhh so the threshold you were suggesting is so that the application could set the baseline compared to what it's already seen. I see what you mean now. 💭 

So I think it would be difficult to effectively maintain adding a threshold value because you could call poll on a set with many counters all with different thresholds.



> @j-xiong - Agree that fi_poll() should signal when counter is updated. 
> May be we should keep track of last_cntr_read value, and then we can make fi_poll() succeed if the last_read_val is different than current value. I think this will solve it.
> If you all agree, I can go ahead and update this in sockets provider.

Hmm, I'm not sure how I feel about the providers keeping track of the last read value. Is `fi_cntr_read` the _only_ way to get the current count?

**Comment by jithinjosepkl** [comment]
> Ohhh so the threshold you were suggesting is so that the application could set the baseline compared to what it's already seen. I see what you mean now. 💭

👍 👍 

> So I think it would be difficult to effectively maintain adding a threshold value because you could call poll on a set with many counters all with different thresholds.

Yes, exactly. (May be fi_cntr_set_poll() is an option, but not sure if we want to go that way).

>Hmm, I'm not sure how I feel about the providers keeping track of the last read value. Is fi_cntr_read the only way to get the current count?

I think provider should keep track of the last read value somehow. I was thinking of setting the ```last_read_val``` in the counter read/set functions (fi_cntr_set/read/add).

**Comment by j-xiong** [comment]
The provider should only track if there is any update since last time the counter value read or , that doesn't necessarily means the value is different.  That can be best captured as the signaled/cleared state of the wait object. If the counter is not created with an wait object, some internal flag can be used to serve similar purpose.

**Comment by jithinjosepkl** [comment]
> The provider should only track if there is any update since last time the counter value read or , that doesn't necessarily means the value is different.

@j-xiong - I took a look at the util_poll() implementation, and there we are comparing with the last_read_val. Which one do you think is better (from both app and provider perspective)?

**Comment by bturrubiates** [comment]
> Yes, exactly. (May be fi_cntr_set_poll() is an option, but not sure if we want to go that way).

That implies that you can't have mixed use pollsets. Not sure I like that restriction.



> I think provider should keep track of the last read value somehow. I was thinking of setting the last_read_val in the counter read/set functions (fi_cntr_set/read/add).

I see, what's the use for the `fi_cntr_set` and `fi_cntr_add` functionality? I thought the counter is supposed to  be a one-way communication device between the provider and the application that signifies the number of completed operations. 

For counters that have been configured with a wait object (`FI_WAIT_FD` / `FI_WAIT_MUTEX_COND`) then I think it isn't necessary to use a `last_read_val` variable. In the event that these are present, then yeah keeping a `last_read_val` count would suffice. Of course, it would need to make sure that all paths that count as a read update the variable. 

If the application reads a counter value into `x`, then calls `fi_cntr_wait` with `x + 5`, what should be the internal `last_read_val` after a successful call to `fi_cntr_wait`? Would it be `x + 5`?

**Comment by jithinjosepkl** [comment]
> I see, what's the use for the fi_cntr_set and fi_cntr_add functionality? 

These can be used by app to reset/signal a counter. I know some use cases (eg. collectives implemented over triggered operations) that make use of these.

> If the application reads a counter value into x, then calls fi_cntr_wait with x + 5, what should be the internal last_read_val after a successful call to fi_cntr_wait? Would it be x + 5?

It should be ```x + 5``` as per my understanding.

**Comment by bturrubiates** [comment]
> @j-xiong - I took a look at the util_poll() implementation, and there we are comparing with the last_read_val. Which one do you think is better (from both app and provider perspective)?

So the more I think about this, this could be well represented as either as a flag or count value in the provider structure for the counter. 

After taking a look at the `util_poll` implementation, I think it would invalidly mark a success in this situation that I had mentioned: 



> If the application reads a counter value into x, then calls fi_cntr_wait with x + 5, what should be the internal last_read_val after a successful call to fi_cntr_wait? Would it be x + 5?

I'm making that assumption because the `last_cntr_val` is part of the `fid_list_entry` and can't be updated in other places (such as `fi_cntr_read` and `fi_cntr_wait`). So why is `last_cntr_val` part of `fid_list_entry`? Maybe that should be evaluated...we could make a test to reflect what we think the API should be and then verify the implementations with it.

**Comment by bturrubiates** [comment]
> These can be used by app to reset/signal a counter. I know some use cases (eg. collectives implemented over triggered operations) that make use of these.

Oh I see, didn't think of that. 



> It should be x + 5 as per my understanding.

That is also my understanding. 👍
