### ISSUE TITLE
Are provider manpages not included in make nroff for a reason?

### ISSUE THREAD

**Issue by heartinpiece** [ofiwg/libfabric#2253]
`make nroff` builds man pages.
However the provider man pages (verbs, sockets, etc.) are not built when `make nroff` is called.

Checking the `Makefile` (and `Makefile.am`), I see that the man pages are split into different lists. 
I've sent up a pull request  #2252 for including the provider man pages to be generated with `make nroff`, but I was wondering if there is a reason this was not included in the first place.

**Comment by jsquyres** [comment]
Fixed by #2252.

@heartinpiece Github pro tip: you can put the text "Fixes #2252" in the commit message in a PR, and it will auto-close the issue when the PR is merged.
