### ISSUE TITLE
Get the correct endpoint from FI_SHUTDOWN

### ISSUE THREAD

**Issue by supunkamburugamuve** [ofiwg/libfabric#2257]
For the shutdown event we can read fi_eq_cm_entry. From this how can we figure out the correct fid_ep? I'm using a polling set to get the events.

**Comment by supunkamburugamuve** [comment]
Could someone please answer this question? I'm trying to use this software and there is not much resources available to get answers.

**Comment by bturrubiates** [comment]
> For the shutdown event we can read fi_eq_cm_entry. From this how can we figure out the correct fid_ep? I'm using a polling set to get the events.

The first field of the `fi_eq_cm_entry` struct is the `fid` associated with the request: 

```c
struct fi_eq_cm_entry {
	fid_t            fid;        /* fid associated with request */
	struct fi_info  *info;       /* endpoint information */
	uint8_t          data[];      /* app connection data */
};
```

This is the first field of the `struct fid_ep` type.

**Comment by supunkamburugamuve** [comment]
Thank you @bturrubiates. How should we compare the fid_t entries to figure out the correct one? Should we use the context attribute?

**Comment by bturrubiates** [comment]
> Should we use the context attribute?

That wouldn't work, the CM operations do not take a context and one is not returned in the `fi_eq_cm_entry` data structure. 

--

If you check out the definition of `fid_t` it's just a pointer to an object of type `struct fid`:

```c
typedef struct fid *fid_t;
```
Here are a couple of ways to handle it: 

1. If you have them in some sort of data structure then you can iterate and do a simple comparison: 

    ```c
    if (entry.fid == &ep->fid) {
        // found it
    } 
    ```

2. You can actually get to the parent `struct fid_ep` directly using the `container_of` macro:

    ```c
    struct fid_ep *ep = container_of(entry.fid, struct fid_ep, fid);
    ```

**Comment by supunkamburugamuve** [comment]
Thanks @bturrubiates. I used the first approach.
