### ISSUE TITLE
Update util poll implementation

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2260]
Update the util poll implementation based on discussion in #2240.

**Comment by shefty** [comment]
The util_poll_run() call looks correct to me.  What semantic change is being requested to fi_poll?

**Comment by bturrubiates** [comment]
> The util_poll_run() call looks correct to me. What semantic change is being requested to fi_poll?

I think the decision we ended up making in that decision was the the `last_cntr_val` value should be updated in both the set/read functions.  The provider is effectively keeping track of the last value that the application has seen in order to know when to notify.

So in the situation:

1. Counter value is last read via poll at 497
2. Counter is set back to 495
3. Counter is incremented to 497
4. Polling is performed on the counter

Should that signal that the `fid` has changed? Because if the utility provider is keeping track of that externally then it can't see that the counter value was lowered and has now changed. 

I've considered this a bit more and I'm not sure there is any way for the utility provider to handle this. The sockets provider added an update that would implement this sort of behavior.

**Comment by shefty** [comment]
> 1.	Counter value is last read via poll at 497
> 2.	Counter is set back to 495
> 3.	Counter is incremented to 497
> 4.	Polling is performed on the counter
> 
> Should that signal that the fid has changed? Because if the utility
> provider is keeping track of that externally then it can't see that the
> counter value was lowered and has now changed.

I'm assuming in steps 1 & 2 that these changes were initiated by the app, and step 3 was the result of a completion.  In that case, the provider should signal a change, as the last value should be what was set in step 2.  I.e. the last value is whatever was last read/set by the app.

**Comment by bturrubiates** [comment]
> I'm assuming in steps 1 & 2 that these changes were initiated by the app, and step 3 was the result of a completion.  In that case, the provider should signal a change, as the last value should be what was set in step 2.  I.e. the last value is whatever was last read/set by the app.

Okay, that's what I expect as well. Does the util providers poll implementation handle this correctly? 

I haven't read the utility provider fully, but it seems as if an app were using poll to determine if a counter has changed, then it would miss those two events.

**Comment by shefty** [comment]
The util provider doesn't implement counters that I know of.  It defines a structure and some calls use them, but it doesn't actually increment/decrement/set them.

**Comment by bturrubiates** [comment]
> The util provider doesn't implement counters that I know of.  It defines a structure and some calls use them, but it doesn't actually increment/decrement/set them.

I'm not sure if this is actually a problem, or if it can be fixed if it is. Here are the lines in question:

https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_poll.c#L101-L103

Notice that `last_cntr_val` is only updated here in this function. This makes sense since the utility provider implements the poll routine but does not implement the counter logic. This would mean that if an app were doing something like: 

```c
/* counters are implemented by provider X and provider X is using 
 * the utility provider to provide pollset support
 */
fi_cntr_open(domain, attr, &cntr, context);
fi_poll_open(domain, attr, &pollset);
fi_poll_add(pollset, cntr, 0);

ret = fi_poll(pollset, context, 1);
if (ret > 0) {
    /* counter has some completions. say 2 for example. */
}

/* at this point the utility provider has a last read value of 2
 * the provider X implementation resets the counter to 0 */
fi_cntr_set(cntr, 0);

/* two more completions come in */

/* utillity provider sees that the counter value is two, but it is the
 * same as the last read so it does not report a change
 */
ret = fi_poll(pollset, context, 1);
if (ret > 0) {
    /* this doesn't run */
}
```

That's the situation I was thinking of. Am I wrong in thinking this is a problem?

**Comment by shefty** [comment]
Ok - I see the problem now.  The last cntr value is stored with the fid_entry, not the util_cntr structure.  Thanks.

**Comment by bturrubiates** [comment]
> Ok - I see the problem now.  The last cntr value is stored with the fid_entry, not the util_cntr structure.  Thanks.

I'm still not sure this is a solution, there would need to be a way for the utility provider to reset it's `last_cntr_val` to `0` when the actual implementation sets it to `0` in `fi_cntr_set`.

**Comment by shefty** [comment]
> I'm still not sure this is a solution, there would need to be a way for
> the utility provider to reset it's last_cntr_val to 0 when the actual
> implementation sets it to 0 in fi_cntr_set.

The user of the utility code (e.g. rxd provider, udp provider, ...) would reset it to 0.  The current issue is that there's no way for a user of the utility code to access the last_cntr_val field.

**Comment by shefty** [comment]
The utility code has been disabled for this release.  Dropping the milestone.
