### ISSUE TITLE
Should there be a timeout associated with an asynchronous AV insertion? 

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2262]
Currently, there doesn't seem to be a way for a user to configure a timeout for an asynchronous AV insertion. There also doesn't seem to be a way to cancel an asynchronous AV operation. As far as I can tell, `fi_cancel` only operates at the `ep` level. 

Should there be some way to specify a timeout or maybe cancel an outstanding operation? Maybe this could be part of a future `fi_av_*` API update (some discussion on that over in #2229). 

@jithinjosepkl @goodell @jsquyres @j-xiong

**Comment by goodell** [comment]
One option: we could set the timeout via an `fi_control()` operation.

**Comment by sayantansur** [comment]
fi_control sounds cool! I think that interface is not as abused (yet).

**Comment by bturrubiates** [comment]
Yes, that's one option but that would be more of a general configurable timeout. Is that sufficient, or should there be a per-operation timeout as well?

**Comment by goodell** [comment]
I have trouble imagining value in a per-operation timeout (though if someone has a counterexample I'd love to hear it).  The potentially blocking parts of an AV insertion are comparable to a route lookup or an ARP lookup.  For example, on Linux you just configure a system-wide ARP timeout.

Any application written over libfabric that I can imagine writing will at most configure this timeout once based on a constant, a command line argument, or a configuration file.

**Comment by shefty** [comment]
I agree with using fi_control to modify the default timeout used by the provider, if an app ever requests control over the timeout value.  Though I would rather see the timeout controlled by the provider, with a possible global configuration parameter.  I have a hard time imagining what an app could want with this, versus giving control to an admin.

**Comment by bturrubiates** [comment]
> I agree with using fi_control to modify the default timeout used by the provider, if an app ever requests control over the timeout value.  Though I would rather see the timeout controlled by the provider, with a possible global configuration parameter.  I have a hard time imagining what an app could want with this, versus giving control to an admin.

I'm fine with `fi_control`, that sounds reasonable.

**Comment by shefty** [comment]
No progress or demand in 4 years.  Async AV calls aren't widely used anyway.  But we have a way to add this support, if it's ever needed.
