### ISSUE TITLE
sockets: Size left hint behavior

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2271]
Noticed this while working on ofiwg/fabtests#547. 

I have an example and some code displaying the issue [here](https://gist.github.com/bturrubiates/0b030b6d6d7b15af1ed2f77fa3f6efbd).

To summarize: 

1. If I set `hints->tx_attr->size` to `0` before `fi_getinfo`, then `fi->tx_attr->size` is `256`, but when I open it with `fi_endpoint` and call `fi_tx_size_left` I get back `368`. 
2. If I set the `hints->tx_attr->size` to anything above `256`, then the `getinfo` call fails. This is understandable if `256` is intended to be the maximum. 
3. If I set the `hints->tx_attr->size` to `0`, then change it to something above `256`, then the `fi_endpoint` call fails. This is expected.
4. If I set the `hints->tx_attr->size` to `0`, then the `fi->tx_attr->size` field contains `256`, but if I then change that back to `0`, then I get `188508`. I don't think this is correct. 

I'm pretty sure `#4` is incorrect, but what about `#1`? Should I interpret the output of `fi_getinfo` such that if the provider sets `fi->tx_attr->size` to `256`, then upon creating it the actual size will be `256`? 

@shantonu

**Comment by shantonu** [comment]
I think both <code>#1</code> and <code>#4</code> are wrong. There is possible a bug in calculating <code>fi_tx_size_left</code>. I'll update after detailed investigation.

**Comment by bturrubiates** [comment]
> I think both #1 and #4 are wrong. There is possible a bug in calculating fi_tx_size_left. I'll update after detailed investigation.

Thanks for looking into it!

**Comment by shantonu** [comment]
Does this output look alright now?

./test
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<103> tx size left reported: 256
############
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 300
[tx_behavior.c]:check_size():<57> provider rejected hint.
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 288
[tx_behavior.c]:check_size():<57> provider rejected hint.
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<64> changing size to 300 after getinfo
[tx_behavior.c]:check_size():<86> fi_endpoint rejected size.
############
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<64> changing size to 0 after getinfo
[tx_behavior.c]:check_size():<103> tx size left reported: 256
############

**Comment by bturrubiates** [comment]
> Does this output look alright now?
> 
> ./test
> ############
> [tx_behavior.c]:check_size():<52> providing tx size hint: 0
> [tx_behavior.c]:check_size():<61> provider returned: 256
> [tx_behavior.c]:check_size():<103> tx size left reported: 256
> ############
> ############
> [tx_behavior.c]:check_size():<52> providing tx size hint: 300
> [tx_behavior.c]:check_size():<57> provider rejected hint.
> ############
> [tx_behavior.c]:check_size():<52> providing tx size hint: 288
> [tx_behavior.c]:check_size():<57> provider rejected hint.
> ############
> [tx_behavior.c]:check_size():<52> providing tx size hint: 0
> [tx_behavior.c]:check_size():<61> provider returned: 256
> [tx_behavior.c]:check_size():<64> changing size to 300 after getinfo
> [tx_behavior.c]:check_size():<86> fi_endpoint rejected size.
> ############
> ############
> [tx_behavior.c]:check_size():<52> providing tx size hint: 0
> [tx_behavior.c]:check_size():<61> provider returned: 256
> [tx_behavior.c]:check_size():<64> changing size to 0 after getinfo
> [tx_behavior.c]:check_size():<103> tx size left reported: 256
> ############

Yeah, that looks correct!

**Comment by shantonu** [comment]
Here is the latest output after the discussion (#2275) on returning more than hint from <code>fi_tx_size_left</code>.

./test
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<103> tx size left reported: 368
############
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 300
[tx_behavior.c]:check_size():<57> provider rejected hint.
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 288
[tx_behavior.c]:check_size():<57> provider rejected hint.
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<64> changing size to 300 after getinfo
[tx_behavior.c]:check_size():<86> fi_endpoint rejected size.
############
############
[tx_behavior.c]:check_size():<52> providing tx size hint: 0
[tx_behavior.c]:check_size():<61> provider returned: 256
[tx_behavior.c]:check_size():<64> changing size to 0 after getinfo
[tx_behavior.c]:check_size():<103> tx size left reported: 368
############
