### ISSUE TITLE
sockets: filtering on domain doesn't seem to work as expected

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2302]
This is possibly related to #2248. 

Testing with the `fi_info` utility from PR #2300:

```sh
bturrubi at blade11 :: ./fi_info -d usnic_3 | grep provider
provider: usnic
provider: usnic
provider: usnic
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
provider: sockets
```

and 

```sh
bturrubi at blade11 :: ./fi_info -p sockets -d lo | grep domain
    domain: eth1
    domain: eth1
    domain: eth1
    domain: eth2
    domain: eth2
    domain: eth2
    domain: eth3
    domain: eth3
    domain: eth3
    domain: lo
    domain: lo
    domain: lo
```

This was found while testing `fi_pingpong`.

@shantonu @jithinjosepkl

**Comment by shantonu** [comment]
Thanks for reporting the issue. Looks like sockets provider is missing the filtering on domain name and fabric name. I'll submit a PR.

Just added the domain name filtering. Here is the output-

Before filtering
```
fi_info -p sockets -d lo | grep domain
    domain: eth0
    domain: eth0
    domain: eth0
    domain: lo
    domain: lo
    domain: lo
```
After filtering
```
fi_info -p sockets -d lo | grep domain
    domain: lo
    domain: lo
    domain: lo
```

Does it look alright?

**Comment by shantonu** [comment]
@bturrubiates, could you please check if this issue is resolved with the master?

**Comment by bturrubiates** [comment]
> @bturrubiates, could you please check if this issue is resolved with the master?

Yep, it's fixed. Thanks!

**Comment by shantonu** [comment]
Thanks!
