### ISSUE TITLE
Providers Feature: Verbs should state cntr is not supported?

### ISSUE THREAD

**Issue by heartinpiece** [ofiwg/libfabric#2319]
I just found out the hard way that Verbs MSG_EP does not support counters.

As Counters seems to be a big part of Libfabric, I think such lack of functionality should be stated in the provider feature matrices? Or at least a line in the man page?
#2282 has implemented counters for the RDM_EP; however the 'well supported' MSG_EP does not seem to have counter functionality.

**Comment by a-ilango** [comment]
I spoke with @j-xiong offline regarding counters in libfabric. At present, counters are an optional feature since there is no native support from all hardware. That's why it isn't listed in the provider feature matrix. Whether counters should be made a mandatory feature or not would have to be discussed with the community.

For verbs MSG_EP, fi_cntr_open would return -FI_ENOSYS indicating that counters are not supported. Currently, that's the only way to know that it's not supported.

The fi_verbs man page lists only supported features and limitations within them but doesn't explicitly list the unsupported ones. I'll fix this in the man page.

We are adding features to verbs provider on a priority basis and not all libfabric features are supported.

**Comment by goodell** [comment]
So long as counters are an optional feature we should expose a capability bit for them as well, like we do with RMA or tagged messaging.

Irrespective of the support detection mechanism, counter support should probably be added to the feature support matrix.

**Comment by a-ilango** [comment]
>Irrespective of the support detection mechanism, counter support should probably be added to the feature support matrix.

+1. Counters can be added under additional features in the feature matrix.

**Comment by heartinpiece** [comment]
> At present, counters are an optional feature since there is no native support from all hardware. That's why it isn't listed in the provider feature matrix. 
So, from an outsider's perspective, I hadn't known that counters were a optional feature.
The three documents on the [libfabric intro](https://ofiwg.github.io/libfabric/) page, as far as I know, does not explicitly give the information.
And naturally for a programmer wanting to use libfabric for another project, we have limited information, and the man pages & matrix are a place we get what limited info we can get.

As for me, I was implementing on sockets on my local machine, anticipating that if I followed the functions available on verbs, my code should be ported without much problem to verbs.
And I got an opportunity to do the actual testing on a IB machine, and alas! Counters are not supported!

So yes, I think stating that counters are optional & that verbs (and any other providers) does not provide counters at the moment, would be very very helpful for programmers wanting to use libfabric.

Thank you for the great work ;)
Back to changing counters to CQs...

**Comment by sayantansur** [comment]
I would prefer a domain attribute that lists the number of counters supported. Even on hardware that supports counters, there would be a limit on how many are supported (like completion queues).

**Comment by shefty** [comment]
We don't have attributes for other maximums (max_eps, max_cqs, max_mrs, etc.).  I wouldn't add a max counter value for the same reason.

**Comment by sayantansur** [comment]
fi_domain_attr::ep_cnt, cq_cnt, etc? Aren't those the max limits the user can open?

**Comment by shefty** [comment]
Yes, we could add cntr_cnt.  But the counts may be optimal limits, not maximums.

**Comment by sayantansur** [comment]
But that is strange, since the other values are indeed max values.

> The ep_cnt value may be a fixed value of the maximum number of endpoints supported by the underlying provider ...
