### ISSUE TITLE
prov/verbs: CQ open fails when cq_attr.size == 0

### ISSUE THREAD

**Issue by heartinpiece** [ofiwg/libfabric#2322]
According to the `fi_cq` manpage, 

> size  :  Specifies the minimum size of a completion queue.  A value of 0 indicates that the provider may choose a default value.

However, with verbs having a value of 0 results in an error of the `fi_cq_open` call.
The strerror returns "Invalid argument"

I've checked that the `prov/verbs/src/verbs_cq.c` passes the `cq_attr.size` right onto `ibv_create_cq()` however I couldn't check if `ibv_create_cq()` defines a default value if the `cqe` (or `cq_attr.size`) == 0.

Also, I am not sure of a decent default value for the completion queue, Thus I'm opening an issue, instead of a PR

**Comment by a-ilango** [comment]
Thank you for reporting this.
