### ISSUE TITLE
prov/sockets: possible race condition exposed in fi_shared_ctx test

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2325]
`fi_shared_ctx -e msg -f sockets` seems to fail periodically (at least in travis testing) with seg fault.

https://travis-ci.org/ofiwg/libfabric/jobs/158221410

FWIW, this is for GNU but I believe the last time I saw it was for Clang.

**Comment by hppritcha** [comment]
This snippet from the travis console
```
- name:   fi_shared_ctx -e msg -f sockets
  result: Fail
  time:   2
  server_stdout: |
    ./scripts/runfabtests.sh: line 313: 32083 Segmentation fault: 11  fi_shared_ctx -e msg -f sockets -s 127.0.0.1
  client_stdout: |
```

**Comment by sungeunchoi** [comment]
@shantonu

**Comment by shantonu** [comment]
Thanks for reporting. I'll try to reproduce the issue in my local Travis environment.

**Comment by jithinjosepkl** [comment]
In the shared ctx example, we expect the CM events sequentially.  ie, 
1. FI_CONNREQ for EP1
2. FI_CONNECTED for EP1
3. FI_CONNREQ for EP2
4. FI_CONNECTED for EP2

But the CONNREQ for EP2 can appear before the CONNECTED event of EP1. The current error handling in the test calls both fi_shutdown() and fi_reject() (for same EP), which was causing the random segfault.

PR #2384 adds error checking in cm-reject call(), which avoids the seg-fault.
We also need fixes to the shared-ctx test to
1) Handle out-of-order CM events
2) Fix error handling
