### ISSUE TITLE
Adding counters to the provider feature matrix

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#2327]
As per discussion in #2319 I have added counters as a feature in the provider feature matrix v1.4.0. Can other provider developers verify/edit the wiki to indicate whether their provider supports counters?
@j-xiong @goodell @sungeunchoi @shantonu

**Comment by goodell** [comment]
@bturrubiates will you handle the usnic update?

**Comment by bturrubiates** [comment]
> @bturrubiates will you handle the usnic update?

Added it. @a-ilango should we also add this field to the previous versions of the matrix?

**Comment by j-xiong** [comment]
The table is right for psm/psm2.

**Comment by a-ilango** [comment]
@bturrubiates Yes, I think someone who's using an older version of libfabric would also find the information useful. I'll add the line to feature matrices of previous versions.

**Comment by a-ilango** [comment]
I have added the line. Can the provider developers verify/update the provider matrix for older versions too? Thanks.

**Comment by sungeunchoi** [comment]
Done for gni provider.

**Comment by a-ilango** [comment]
It looks like the field matrix has been updated/verified for all providers. If there are no other changes/comments by end of day, I'll mark this issue as resolved.
