### ISSUE TITLE
prov/verbs fi_mr_regv error: Function not implemented

### ISSUE THREAD

**Issue by iamchanghyunpark** [ofiwg/libfabric#2330]
I have a code that works on _sockets_, using `fi_mr_regv`; however the same code returns an error in _verbs_.
The `strerror()` of the `errno` returns "Function not implemented".

Perhaps the _verbs_ version of `fi_mr_regv` is not available?

**Comment by heartinpiece** [comment]
in file: `prov/verbs/src/verbs_domain.c`

    static struct fi_ops_mr fi_ibv_domain_mr_ops = {
        .size = sizeof(struct fi_ops_mr),
        .reg = fi_ibv_mr_reg,
        .regv = fi_no_mr_regv,
        .regattr = fi_no_mr_regattr,
    };


Okay, so it seems verbs will not support regv. 

**Perhaps we need to add a line in fi_mr_regv, fi_mr_regattr that states that these functions are *optional* functions which may not be implemented in some providers.**

But looking at the fi_ops, fi_ops_mr, fi_ops_domain structures, there are quite a few functions that are not supported by verbs, and I guess some other special purpose networks... 

It may be nice if it could be organized into a matrix as well.. But I guess its not so critical...

**Comment by goodell** [comment]
And/or we need to add a new capability that the app can request indicating it wants/needs support for `fi_mr_regv`.

It looks like currently only sockets and psm/psm2 support `fi_mr_regv`.  I don't think it could be implemented with verbs in user space and we're unlikely to add the necessary kernel support for usnic any time soon.  I have no idea if it's realistic for mxm/gni to implement it.

I think that libfabric should generally try to stay away from using returning `-FI_ENOSYS` as the official mechanism for an app to determine whether a particular feature is supported by a provider.  There may be exceptions, but it seems like the right default position to me.

**Comment by j-xiong** [comment]
Lack of fi_mr_regv is something application can work around, so we don't want it be a capability bit for fi_getinfo that may filter out a provider completely.

One possible approach is similar to what verbs is doing -- to have a bit mask for all the API functions (or optional functions only) that the application can query.

**Comment by heartinpiece** [comment]
@j-xiong Would it be possible to check with the bit masks that does not have the physical verbs provider, but a libfabric that is built with verbs support?

For example if you wish to develop on a system without verbs, and run it on a system with IB?

**Comment by goodell** [comment]
@j-xiong I think that depends on how important an application views having the regv functionality.  Some apps will want it filtered, some won't.

But maybe the "optional functions" bit mask would at least be an improvement.  We should probably discuss this on one of the calls at some point.

**Comment by j-xiong** [comment]
@heartinpiece If we put the feature info fi_getinfo, that will depend on the provider's capability of returning success when the HW is not present.  Details will need some discussion.

@goodell Yes this can be a good candidate for the topics of the calls.

**Comment by shefty** [comment]
Any provider that supports memory registration should be able to support fi_mr_regv and fi_mr_regattr.  I think we need to add an fi_domain_attr::mr_iov_limit field.

**Comment by goodell** [comment]
@shefty You mean "support" it by exposing `mr_iov_limit=1`?

**Comment by shefty** [comment]
Yes - mr_iov_limit = 1

**Comment by shefty** [comment]
@a-ilango - can you please update the verbs provider to support the missing calls?  Just restrict the call to an iov limit of 1.

I will craft a proposal to update the API.
