### ISSUE TITLE
man: FI_SOURCE ambiguity in fi_getinfo(3)

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#2334]
There is ambiguity in the way `FI_SOURCE` is used in the [fi_getinfo(3)](https://ofiwg.github.io/libfabric/v1.3.0/man/fi_getinfo.3.html) manpage for v1.3.0. There is a capability named `FI_SOURCE` and a flag named `FI_SOURCE`. Both have two completely different meanings, and it can be difficult to derive intent.

If used as a capability, `FI_SOURCE` means:

> FI_SOURCE
> Requests that the endpoint return source addressing data as part of its completion data. This capability only applies to connectionless endpoints. Note that returning source address information may require that the provider perform address translation and/or look-up based on data available in the underlying protocol in order to provide the requested data, which may adversely affect performance.

If used as a flag to fi_getinfo, `FI_SOURCE` means:

> FI_SOURCE
> Indicates that the node and service parameters specify the local source address to associate with an endpoint. If specified, either the node and/or service parameter must be non-NULL. This flag is often used with passive endpoints.

The FI_INFO section mentions side effects if `FI_SOURCE` is specified, but doesn't state if it is referring to the capability or the flag:

> src_addrlen - source address length
> Indicates the length of the source address. This value must be > 0 if src_addr is non-NULL. This field will be ignored in hints if FI_SOURCE is specified, or src_addr is NULL.
> dest_addrlen - destination address length
> Indicates the length of the destination address. This value must be > 0 if dest_addr is non-NULL. This field will be ignored in hints unless the node and service parameters are NULL or FI_SOURCE is specified, or if dst_addr is NULL.
> src_addr - source address
> If specified, indicates the source address. This field will be ignored in hints if FI_SOURCE is specified. On output a provider shall return an address that corresponds to the indicated fabric or domain, with the format indicated by the returned addr_format field.
> dest_addr - destination address
> If specified, indicates the destination address. This field will be ignored in hints unless the node and service parameters are NULL or FI_SOURCE is specified.

I think it would be helpful if either the flag or capability name was changed to resolve the ambiguity.

**Comment by shefty** [comment]
We could define an alias for one of these and use that in the documentation.  I'm leaning to 'renaming' the fi_getinfo flag.  Maybe FI_LOCAL?

**Comment by a-ilango** [comment]
I have a related question:
> This flag is often used with passive endpoints.

Is one flag enough to determine if it's going to be used with passive endpoints?

Let's say the user specifies just service parameter and FI_SOURCE flag. What should be the behavior?
1. Provider returns a list of all local communication interfaces with info->src_address set to corresponding local interface address and port set to given service parameter.
**or**
2. Provider returns a wildcard address with port set to given service parameter. What should be the value of other attributes like domain/endpoint? Should the app be forbidden to use them since they wouldn't correspond to a specific device? This would fit well with a passive endpoint.

Should we have another flag (say FI_PASSIVE) to tell provider to follow scenario 2?

**Comment by shefty** [comment]
I would expect the second option -- the use of a wildcard address.  A domain may not be available.

**Comment by goodell** [comment]
Another option would be to deprecate the `fi_getinfo` call and create a new `fi_getinfo2` call that takes both source and destination node/service parameters.  While we lose the parallelism with `getaddrinfo`, I think such an API would be much more intuitive than the current scheme.  There are some obviously distasteful aspects to such a proposal, but I don't think it should be summarily dismissed.

**Comment by goodell** [comment]
Oh, also, 👍  for `FI_PASSIVE` over `FI_LOCAL`, so long as we're aping `getaddrinfo`.

**Comment by shefty** [comment]
I agree that we should consider fi_getinfo2 as a possible alternative.  There may still be an open issue on this.
