### ISSUE TITLE
Should counters be a mandatory or optional feature?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2335]
See #2319.

The original intent was that counters would always be available for all providers (baring missing functionality).  However, as I discovered with the UDP provider, support for counters is non-trivial and can result in a performance hit.  The question is whether we should make it mandatory or allow providers to opt-out of the support, e.g. by adding a new capability bit.

If you squint, this issue may be related with #1394

**Comment by sayantansur** [comment]
My vote is for them to be optional, with support being indicated by a domain attribute that lists the number of counters supported. The reasoning is that it will be useful to declare limits for providers that do support counters.

**Comment by shefty** [comment]
If we make them optional, then the utility framework must handle this case and export counters to the user.

**Comment by shefty** [comment]
We could expose counters as optional using cntr_cnt (new domain attribute), but this may not capture all use cases for how a counter may eventually be used.
