### ISSUE TITLE
meaning of domain attribute cq_cnt

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2340]
While looking at ofiwg/fabtests#550, I realized that the usNIC provider always provides `0` as the value for `domain_attr->cq_cnt`. After looking over the man page, I have determined that it would be most useful to instead set it to the limits imposed by the hardware. In the case of emulated endpoints, is it better arbitrarily pick a size, set it to the maximum value for the integral data type used by `cq_cnt` (subject to  memory constraints), or to leave it as `0` (indicating that there is no useful limit)?

In any case, should an application be able to successfully create `cq_cnt` simultaneous CQs?

**Comment by shefty** [comment]
An application may not be able to successfully create cq_cnt CQs.  This depends on the implementation and whether CQ resources are shared with other resources, such as EPs.  However, I would claim that if all the app does is allocate CQs of the optimal size, then it should be able to allocate cq_cnt -- not that we have a great way to report what the optimal size is...

**Comment by bturrubiates** [comment]
> An application may not be able to successfully create cq_cnt CQs. This depends on the implementation and whether CQ resources are shared with other resources, such as EPs. However, I would claim that if all the app does is allocate CQs of the optimal size, then it should be able to allocate cq_cnt -- not that we have a great way to report what the optimal size is...

Okay so assuming a single domain with the size hint set to `0` and the other hints set to `_UNSPEC`, then opening `cq_cnt

**Comment by shefty** [comment]
To your first question, I vote yes.  The app should be able to open at least cq_cnt CQs.

I would consider cq_cnt of 0 to be a bug.  Though we can define it as no limit (or limit is dependent on available system memory).  I'm leaning to making it have some value, so a resource manager might be able to depend on it.

**Comment by bturrubiates** [comment]
> To your first question, I vote yes. The app should be able to open at least cq_cnt CQs.

Awesome, that's the assumption I was making when contributing my last PR to `fi_cq_test`. 



> I would consider cq_cnt of 0 to be a bug. Though we can define it as no limit (or limit is dependent on available system memory). I'm leaning to making it have some value, so a resource manager might be able to depend on it.

Alright, I guess providers will have to figure out some way to define a value. The `udp` provider is in a similar case as our emulated endpoints because it isn't really dependent on any hardware. 

I suppose the provider could always impose some arbitrary restriction (say a maximum `cq_cnt` of `8192`).

**Comment by shefty** [comment]
Closing, as I think this question has been answered.
