### ISSUE TITLE
Clarify connected endpoints' behavior on fi_connect failure

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#2344]
Connected endpoints on receiving an error on fi_connect, should not be used to connect again.

Handling connection failure and resetting the endpoint's internal state to prepare to send a connection request again is not trivial in some providers (e.g. verbs). So add a note in man page that apps should not use a connected endpoint after receiving an error on fi_connect. It has to create a new endpoint to try and connect again.

The cm_data test in fabtests would have to be updated as well.

@shefty

**Comment by sayantansur** [comment]
It would be useful if you could add what the difficulty in verbs is (it is not readily apparent to me). Will help in the future when reading this issue.

**Comment by a-ilango** [comment]
Sure. Verbs uses rdmacm which doesn't support reusing the communication id and queue pair once a connect call on it fails. So if we have to handle this in the verbs provider, we would have to keep track of any CQs bound to the endpoint, receives posted to the endpoint and redo it once the connect call fails.

As per discussion with @shefty, it seems a connection failure is reported from rdmacm/ibcm after many retries.

This means there is a serious connectivity issue or the remote endpoint is down. I believe these are rare cases and it makes sense to leave it to the app, the responsibility of recreating the endpoint, binding resources and posting receives again. The app might choose to not do that just report a failure.
