### ISSUE TITLE
layered providers create circular dependencies

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2345]
As we bring up the utility framework, we have the potential for layered providers to layer over each other endlessly.  For example, the RXM (RDM over MSG EP) provider can get picked up by the MXR (MSG over RDM EP) provider, which could result in an infinite loop.  (This particular case is avoided today because the RXM provider requires a mode bit that the MXR provider does not set.)

We must come up with a way to handle this.

**Comment by j-xiong** [comment]
We could introduce a provider property identifying if it's an "terminal" provider and provide an option for only allowing layering over such providers.

On the other hand, it might also useful to allow certain level of nested layering. That would be an interesting feature at least for testing the implementations.

**Comment by shefty** [comment]
Yeah, I'm not sure we want to avoid all nesting -- MSG over RDM over DGRAM might be the way we want to support MSG over DGRAM

**Comment by j-xiong** [comment]
I can think of two ways to avoid endless layering. The first one is to pass down the current layering information to the internal getinfo calls to avoid any circle in the chain. The second one is control the allowed number of layers. The second one is simpler but doesn't exclude circle.

**Comment by a-ilango** [comment]
> The first one is to pass down the current layering information to the internal getinfo calls to avoid any circle in the chain.

We could pass provider nesting information to internal getinfo call. For example, the calling provider could add its name to a list that would be passed down. A provider can walk through the list and if finds a provider it doesn't want to support, it can return -FI_ENODATA. (e.g. mxr -> rxr ->rxm (rxm finds mxr in the list and returns -FI_ENODATA)).

**Comment by shefty** [comment]
Proposal: use internal flags to indicate which EP type each provider handles.  If an EP type is set, then a provider fails the getinfo call.  Basically, the bits become a short history of layering.

**Comment by shefty** [comment]
Another option.  Add a 'char *prov_stack' field to fi_fabric_attr.  This field would list all layered providers.  Example:

prov_name: "usnic"
prov_stack: "rxd/usnic"
protocol: FI_PROTO_RXD

The protocol field becomes relative to the provider stack, rather than the provider.  The fabric and domain names remain unchanged (as set by usnic in this example).  This proposal would meet Cisco's requirement to keep the provider name unchanged.

**Comment by sayantansur** [comment]
A random comment. A while ago, someone told me (forgot who), that FABRIC_DIRECT was broken with the layered provider approach. If I remember right, it wasn't clear where the FABRIC_DIRECT def'd part of the header files would be installed from. Suppose should have filed the bug then.

In any case, if this problem could be avoided when using layered providers that'd be great. I'm mainly looking to avoid a compile error when the app uses -DFABRIC_DIRECT, as opposed to micro optimization (since we are in a layered environment anyways).
