### ISSUE TITLE
prov/sockets: build warnings on 32-bit system

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2347]
prov/sockets/src/sock_progress.c: In function 'sock_pe_process_rx_read':
prov/sockets/src/sock_progress.c:667:6: warning: passing argument 3 of 'sock_mr_verify_key' from incompatible pointer type [enabled by default]
      FI_REMOTE_READ);
      ^
In file included from prov/sockets/src/sock_progress.c:60:0:
./prov/sockets/include/sock.h:1039:17: note: expected 'uintptr_t *' but argument is of type 'uint64_t *'
 struct sock_mr *sock_mr_verify_key(struct sock_domain *domain, uint64_t key,
                 ^
prov/sockets/src/sock_progress.c: In function 'sock_pe_process_rx_write':
prov/sockets/src/sock_progress.c:718:6: warning: passing argument 3 of 'sock_mr_verify_key' from incompatible pointer type [enabled by default]
      FI_REMOTE_WRITE);
      ^
In file included from prov/sockets/src/sock_progress.c:60:0:
./prov/sockets/include/sock.h:1039:17: note: expected 'uintptr_t *' but argument is of type 'uint64_t *'
 struct sock_mr *sock_mr_verify_key(struct sock_domain *domain, uint64_t key,
                 ^
prov/sockets/src/sock_progress.c: In function 'sock_pe_process_rx_atomic':
prov/sockets/src/sock_progress.c:1204:6: warning: passing argument 3 of 'sock_mr_verify_key' from incompatible pointer type [enabled by default]
      FI_REMOTE_WRITE);
      ^
In file included from prov/sockets/src/sock_progress.c:60:0:
./prov/sockets/include/sock.h:1039:17: note: expected 'uintptr_t *' but argument is of type 'uint64_t *'
 struct sock_mr *sock_mr_verify_key(struct sock_domain *domain, uint64_t key,
                 ^
  CC       prov/sockets/src/src_libfabric_la-sock_comm.lo

**Comment by jithinjosepkl** [comment]
Looks like this one is fixed in #2362
