### ISSUE TITLE
when can atomicvalid outputs change?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2357]
@jdinan brought up the question of whether middleware should be querying each endpoint (created off the same info structure) can have a different output of atomicvalid lengths, ops and what not.

Currently, the man pages don't guarantee that they won't change, leaving the user to the conclusion that every endpoint it creates needs to re-check if the atomicvalids changed or not.

It might be useful to provide the user with something better ... one idea we discussed was may be we can guarantee that atomicvalid remains the same for endpoints of the same type. i.e. all MSG EPs of a particular provider have the same atomicvalid outputs.

What do people think?

**Comment by shefty** [comment]
I think it's fair to claim that the atomic support from EP to EP with the same attributes will also be the same.

**Comment by sayantansur** [comment]
By endpoint attributes, do you mean to encompass the endpoint caps as well?

**Comment by shefty** [comment]
Yes
