### ISSUE TITLE
FI_DBG_TRACE?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2372]
Currently, we have this in fi_log.h that allows liberal usage of FI_DBG throughout with the assurance that for non debug builds this will be compiled out.

```c
#if ENABLE_DEBUG
#define FI_DBG(prov, subsystem, ...)                                    \
        FI_LOG(prov, FI_LOG_DEBUG, subsystem, __VA_ARGS__)
#else
#define FI_DBG(prov_name, subsystem, ...)                               \
        do {} while (0)
#endif
```

We also have FI_LOG_TRACE, which is intended to be used to trace API calls, etc. but needs to be compiled out for a non debug build. If we had the following we could enable/disable trace from within a debug build. Otherwise, using FI_TRACE requires that there be branches everywhere.

```c
#if ENABLE_DEBUG
#define FI_DBG_TRACE(prov, subsystem, ...)                                    \
        FI_LOG(prov, FI_LOG_TRACE, subsystem, __VA_ARGS__)
#else
#define FI_DBG_TRACE(prov_name, subsystem, ...)                               \
        do {} while (0)
#endif
```

Alternatively, we could just redefine FI_TRACE to work only under debug builds as well.

What do folks think?

**Comment by shefty** [comment]
I'm okay with FI_DBG_TRACE
