### ISSUE TITLE
Define error code for posting request on disconnected endpoint

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#238]
There is currently no action defined if the user attempts to post a request and the endpoint has been gracefully or abruptly terminated (corresponds to requirement 84).

**Comment by patrickmacarthur** [comment]
From [fi_cm(3)] (http://ofiwg.github.io/libfabric/master/man/fi_cm.3.html):

> An FI_SHUTDOWN event will be generated for an endpoint when the remote peer issues a disconnect using fi_shutdown or abruptly closes the endpoint.

I guess that will work; I don't really have any better ideas if we need to keep connection management out of the fast path.  The only nuisance is having to have a second event queue just to get disconnect notifications.

I'm ok with you closing the issue.

**Comment by shefty** [comment]
thanks - closing as 'wontfix'
