### ISSUE TITLE
Associate transport resource with fd

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#239]
Enables fstat, dup2, etc. to work as expected for rsockets and UNH EXS

**Comment by shefty** [comment]
I don't think there's any performant way of supporting this that doesn't just drop into the kernel.  This would need to be a provider specific option -- something like a kernel version of rsockets -- that could be provided for compatibility.  But then, if we had that, we would need a user space version of rsockets or EXS.  :)
