### ISSUE TITLE
return values for errors / unsupported features

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2424]
There are several error values encountered in Libfabric that can be used to signify that something is erroneous or not supported: `FI_EINVAL`, `FI_EOPNOTSUPP`, `FI_ENOSYS`,  and`FI_ENODATA`.

Do these have specific meanings associated with them? 
- Is `FI_ENODATA` reserved for use in `fi_getinfo()`? 
- Is `FI_EOPNOTSUPP` reserved for transport operations?
- Does `FI_EINVAL` imply that that an argument was invalid by the API? Or could it be valid for the API but invalid for the provider?
- `FI_ENOSYS` is used often as the return value for interfaces that are not implemented by a provider, but what about partially implemented interfaces? 

Some example cases:
- A provider does not support shared AVs and a name is provided to `fi_av_open`. I see that some providers return `-FI_EINVAL` and some return `-FI_ENOSYS`. 
- A field such as `cq_data_size` is out of bounds for the provider, should the provider return `-FI_EINVAL`?
- The domain name requested in `fi_domain` cannot be used with the fabric that the domain was opened from. Should that be `-FI_EINVAL` or `-FI_ENODATA`? 

@jsquyres @shefty @jithinjosepkl @j-xiong

**Comment by shefty** [comment]
> *	Is FI_ENODATA reserved for use in fi_getinfo()?
	
I wouldn't say it's reserved, but it may not be used outside of that call.

> *	Is FI_EOPNOTSUPP reserved for transport operations?

This appears to the case.  The help text (from errno) is "Operation not supported on transport endpoint"

> *	Does FI_EINVAL imply that that an argument was invalid by the
> API? Or could it be valid for the API but invalid for the provider?

Either?  Though I think of it more with respect to the API in general.

> *	FI_ENOSYS is used often as the return value for interfaces that
> are not implemented by a provider, but what about partially implemented
> interfaces?

I would allow ENOSYS for partially implemented interfaces as well.  For example, I can see it being used for fi_control.

> *	A provider does not support shared AVs and a name is provided to
> fi_av_open. I see that some providers return -FI_EINVAL and some return
> -FI_ENOSYS.

ENOSYS is preferable IMO

> *	A field such as cq_data_size is out of bounds for the provider,
> should the provider return -FI_EINVAL?

I would say yes, since the app could have determined the proper size earlier.

> *	The domain name requested in fi_domain cannot be used with the
> fabric that the domain was opened from. Should that be -FI_EINVAL or -
> FI_ENODATA?

FI_EDOMAIN?  FI_ENODEV?  This doesn't seem like an EINVAL error, for some arbitrary definition of EINVAL.

**Comment by shefty** [comment]
Btw, we should update the fi_errno man page as we define error codes in more detail.

**Comment by bturrubiates** [comment]
> ENOSYS is preferable IMO

Alright, I think this is already the usNIC behavior. @j-xiong want to update the psm provioder? 



> I would say yes, since the app could have determined the proper size earlier.

Okay, but in general things that are not supported by the provider can return `-FI_ENOSYS` (such as `FI_READ`/`FI_SYMMETRIC` flags or `FI_AV_TABLE`) and things that are programmatic issues (invalid sizes) are actually `-FI_EINVAL`. 

Sounds good to me. 




> Btw, we should update the fi_errno man page as we define error codes in more detail.

Good idea.



> FI_EDOMAIN?  FI_ENODEV?  This doesn't seem like an EINVAL error, for some arbitrary definition of EINVAL.

Oh, I think `-FI_ENODEV` is a good fit here. This could be the same case in `fi_fabric` if a fabric name is wrong, also `-FI_ENODEV`.
