### ISSUE TITLE
mechanism for domain events, eg link up/down

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#244]
We need a mechanism for notification of linkstate and possibly other domain-level events.  Suggest we define ability to bind a domain to an EQ and define at least "FI_LINKSTATE" for use as an event type.  fi_eq_entry::data would contain up/down status.

Maybe fabric instead of domain, can see either way.

**Comment by shefty** [comment]
Marked as to address post 1.0 release.  Good topic for discussion at a future OFIWG meeting or F2F.

**Comment by shefty** [comment]
List of desired events mentioned by MPI developers: endpoint (node?) up/down, link up/down, MTU change, logical/physical topology change

**Comment by shefty** [comment]
There is not a burning desire from applications for this feature.
