### ISSUE TITLE
non-static global variable named init

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#2448]
In [fabric.c](https://github.com/ofiwg/libfabric/blob/master/src/fabric.c), there is a non-static global variable named `init`:

`int init = 0;`

The reason it is non-static is because [var.c](https://github.com/ofiwg/libfabric/blob/master/src/var.c) relies on it. It is trivial for a statically linked application that defines its own symbol named `init` to collide with the one being exported by libfabric. Some sort of namespace isolation should be employed to avoid this situation.

**Comment by goodell** [comment]
I don't think this is an actual issue.  Libfabric is built with its symbols not visible by default (`-fvisibility=hidden`), we have to specifically opt-in each symbol that we want to be visible in the resulting library (`__attribute__((visibility ("default")))`).

`nm` seems to support this (lowercase 'b' means it's a local-only symbol in the BSS):

```
$ nm  _prefix/lib/libfabric.so | grep -w init
00000000002b0e40 b init
```

Please reopen the issue if I've misunderstood your point.

**Comment by shefty** [comment]
The issue referred to static linking

**Comment by goodell** [comment]
Yep, I just realized that as I re-read the question.

**Comment by sayantansur** [comment]
Ironically, I think this makes it more likely to have a namespace collision. I have seen code using libfabric to use ofi_* in their network API dependent code.

**Comment by shefty** [comment]
Okay - we use 'ofi' everywhere, with the intent of expanding its usage for all internal functions.
