### ISSUE TITLE
deprecate size_left calls

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2459]
The size_left call isn't used by applications (to the best of my knowledge), as it is impossible or exceedingly difficult to implement for some providers.  The best course is to remove this wart (my term) from the API and have apps rely on the EAGAIN return value.

Note that not all providers support this call today, so backwards compatibility is provider specific.

**Comment by bturrubiates** [comment]
> The size_left call isn't used by applications (to the best of my knowledge), as it is impossible or exceedingly difficult to implement for some providers. The best course is to remove this wart (my term) from the API and have apps rely on the EAGAIN return value.
> 
> Note that not all providers support this call today, so backwards compatibility is provider specific.

I have an application currently using this, but could just as easily make it a provider specific extension.

**Comment by shefty** [comment]
The calls are still there.  Their use just generates a compiler warning now.  (And the app won't work with all providers, but that's true today.)
