### ISSUE TITLE
atomicvalid() with iovecs

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2461]
The current definition of atomicvalid() doesn't let an application query if IOVECs are supported in the atomic interface.

e.g. iovecs for fi_atomic() might be supported, but not for fi_fetch_atomic() or fi_compare_atomic().

How should this restriction be conveyed up to the application?

**Comment by shefty** [comment]
Egads.  How is an app supposed to use the atomic interface at all if every single call may or may not be supported with varying degrees of options?  The atomic valid calls are already horribly complex.

I vote the provider needs to document this limitation in their man page.

**Comment by sayantansur** [comment]
Good enough for me. I just wanted to know what we should do (if anything). Agree about the explosion of options here.
