### ISSUE TITLE
fi_cq man page 'len' completion field clarification

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#2476]
The fi_cq man page states for the 'len' completion field only applies to completed receive operations.
What does "receive" mean?

For example, if the data is transferred from the remote instance using the fi_writedata API, does it mean that when the receiving side processes this CQ event, this field will be filled in?

Or does it mean that when the receiving side is using a "receive", i.e. fi_recv, API to transfer the data, then the  CQ event will have this field filled in?

**Comment by shefty** [comment]
This field applies to completions for fi_recv, fi_trecv, and related calls.  It represents "how many data bytes were actually placed into the associated receive buffer".  It is for message transfers only (send, tsend), not RMA or atomics.
