### ISSUE TITLE
`fi_write` with offset instead of address ?

### ISSUE THREAD

**Issue by danghvu** [ofiwg/libfabric#2489]
Taken from the [man page](https://ofiwg.github.io/libfabric/master/man/fi_rma.3.html)

> ssize_t fi_write(struct fid_ep *ep, const void *buf, size_t len,
>   void *desc, fi_addr_t dest_addr, uint64_t addr, uint64_t key,
>   void *context);
> addr
> Address of remote memory to access.

However, as I tested and check with the test at: https://github.com/ofiwg/fabtests/blob/master/simple/rdm_rma_simple.c#L68

This "address" seems to be an offset to the remote address registered with the key instead of the actual address? Maybe there is document somewhere that i have missed, otherwise this name is quite misleading.

**Comment by shefty** [comment]
What provider did you run this against?

**Comment by shefty** [comment]
Okay - I think I see.  That test uses FI_MR_SCALABLE, which treats the address as an offset.  The address is a virtual address if FI_MR_BASIC memory registration mode is used.
