### ISSUE TITLE
debug symbols are included in all builds

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2491]
Due to [this](https://github.com/ofiwg/libfabric/blob/master/Makefile.am#L26) line in `Makefile.am`, debug symbols are included independent of whether the library is configured with `--enable-debug`.

On one hand, it's useful to have this information when helping users with issues, but it also increases the library size.

Should this be left as-is, or fixed for the 1.5 release? 

@jsquyres @shefty

**Comment by shefty** [comment]
If this has always been like this, we should leave it for 1.4 and decide whether to keep it for 1.5.

**Comment by bturrubiates** [comment]
> If this has always been like this, we should leave it for 1.4 and decide whether to keep it for 1.5.

Yeah, I figured it's too close to 1.4 to fix now. I believe it's always been like this.

**Comment by shefty** [comment]
Looking into this, I'm not sure that we want to keep the --enable-debug option, but instead require the user to specify the correct CFLAGS as part of configure.

**Comment by bturrubiates** [comment]
> Looking into this, I'm not sure that we want to keep the --enable-debug option, but instead require the user to specify the correct CFLAGS as part of configure.

What's the reasoning behind removing the option?

**Comment by shefty** [comment]
Several posts I read indicated that the debug options were compiler specific.  But it looks like there is a standard to use -g for any c99 compliant compiler.  So I ended up keeping it.  See #2512.
