### ISSUE TITLE
libfabric.pc really shouldn't add -L/usr/lib or -L/usr/lib64

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2492]
Right now, libfabric.pc unconditionally does this:

```
Libs: -L${libdir} ...
```

which will end up including `-L/usr/lib` or `-L/usr/lib64` if the prefix is `/usr`.  This is Bad.  Instead, it should read something like this:

```
Libs: @PKGCONFIG_LIBDIR@
```

Then:
- If `$libdir` is `/usr/lib` or `/usr/lib64`, leave `PKGCONFIG_LIBDIR` blank
- Otherwise, set `PKGCONFIG_LIBDIR` to an expanded version of `$libdir`

**Comment by shefty** [comment]
Does this just require a 1-line change to libfabric.pc?  So far, nobody has complained, but I don't understand why "This is Bad".
