### ISSUE TITLE
add fi_av_get_distance

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#253]
Adjust name to suit.  It looks like:

``` C
    int fi_av_get_distance(struct fid_av *av, fi_addr_t addr, size_t *distance);
```

On success, distance contains a relative distance to the specified address, some provider-specific equivalent of network hops.  For usnic, for example, we would return distantce = 0 for "same local subnet" or distance > 0 for "reachable through router," ideally extracting a "route metric" from the routing table to be able to prefer one route over another.

Providers for which this is meaningless (or fi_no_av_get_distance) would just do something like:

``` C
    int prov_av_get_distance(struct fid_av *av, fi_addr_t addr, size_t *distance)
    {
        *distance = 0;
        return 0;
    }
```

**Comment by shefty** [comment]
Marking this as a post 1.0 feature

**Comment by shefty** [comment]
No requirements pushing this feature in 5 years.
