### ISSUE TITLE
Clarify use of fi_recv() with unconnected MSG endpoint

### ISSUE THREAD

**Issue by ztiffany** [ofiwg/libfabric#2530]
It looks like all the fabtests using FI_EP_MSG endpoints use fi_recv() before the endpoint is connected.  This seems strange to me and I couldn't find anything in the man page that clarified whether this was allowed.  There is this about fi_send():

"The local  endpoint  must  be connected to a remote endpoint or destination before fi_send is called."

With that, I assumed that fi_recv() was similar until I started running the FI_EP_MSG fabtests.  Can we state here if the use of fi_recv() on an unconnected MSG EP is intended to be valid and maybe clarify the man pages if so?

**Comment by shefty** [comment]
The behavior of fabtests is correct.

There is this statement in fi_endpoint.3:

"Once an endpoint has been activated, it may be associated with an address vector.  Receive buffers may be posted to it and calls may be made to connection establishment routines."

We should add more information to fi_msg.3 about pre-posting receive buffers.
