### ISSUE TITLE
Possible new mode bit: FI_LOCAL_RMA_MR

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2531]
The current API exposed an FI_LOCAL_MR mode bit.  When set, this requires that send, receive, and RMA buffers be registered before being used.  With MPI, it can easily register memory when posting RMA operations, but send and receive buffers come directly from the application. Supporting a new mode bit that only requires registering RMA buffers fits better with MPI for providers that do require registration.

The problem shows up in the RXM provider.  When sending or receiving large messages, the RXM provider will invoke a rendezvous protocol.  This converts the send/receive into a remote RMA read operation.  Small messages end up being copied in/out of pre-registered buffers.  Registration, in particular at the receive side, is not necessary for small messages, as the user's buffer is never directly accessed by the network.  For larger receives, the registration needs to be for RMA read access, not recv as expected by the app.  On the send side, small messages can either be injected (no registration required), or converted into RMA read target buffers.  The result is that send buffers must be registered for RMA remote read, not send.

For true RMA operations from the app, registration isn't an issue.  MPI must setup windows and can register buffers and exchange keys as part of that process.

The open question is whether there is any benefit to exposing a LOCAL_MR mode bit that only applies to RMA, versus simply turning FI_LOCAL_MR off completely.  The latter would require the RXM provider to automatically register initiator RMA read/write buffers as part of any transfer, which could impact latency.

**Comment by shefty** [comment]
@evgeny-leksikov @a-ilango - hopefully this captures the problem correctly

**Comment by a-ilango** [comment]
@shefty Looks fine to me. So with this change, only for large send/recvs we would incur additional latency due to memory registration of the send/recv buffers.

**Comment by shefty** [comment]
Correct, larger send/recv would use rendezvous protocol of rdma read.  The registration could be done per operation or cached.  Caching has problems and requires hooking all memory allocation calls, so registering/unregistering would be safer, though less performing.  We may want to get input from MPI developers on the best implementation techniques.

**Comment by evgeny-leksikov** [comment]
@shefty I do not see the problem for verbs compatible HW to hide the registration inside fi_read/fi_write calls.
Moreover, the verbs provider supports fi_write_inject which uses the local preregistered buffer. The same may be done inside fi_read/fi_write calls for optimizations purposes.
@hoopoepg please add or correct me if I missed something.

**Comment by shefty** [comment]
I have a patch that adds this mode bit, but it's easy enough to drop it.  We still need to discuss all proposed API changes.

I thought you mentioned that MPI can register source RMA buffers as part of window creation.  If that's the case, we could be better off with this mode bit, than registering and unregistering inside each fi_read/fi_write call.  What I need to understand is how MPI will use the RMA interfaces (assuming that rendezvous is implemented by the provider), and where the *source* RMA buffers come from.

**Comment by evgeny-leksikov** [comment]
Window creation does memory registration regions on targets and key exchange. Originator may work with new buffer every time to read/write from/to remote window. In addition, as I understand, upper level, such as MPI, is able to register local memory even if it's not required by FI_LOCAL_MR flag if the memory will be used many times. Then, for example, verbs provider just may check desc for valid MR and decide do registration or not. In this case we may need only doc update.
If this patch may help some other HW or make OFI model simpler I don't have any objections.

**Comment by shefty** [comment]
Thanks - this is helpful and leads me to believe that my current proposal isn't quite what we want.

**Comment by shefty** [comment]
After more offline discussion, this approach will not help and only complicates the API.  Closing the request, and I will drop the patch from my PR.
