### ISSUE TITLE
rxd provider fails rma_bw and rma write data streaming test

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#2532]
Opening this issue to track the following test failures (when running runfabtests.sh) for rxd provider:

fi_rma_bw -e rdm -o write -p rxd:                       Fail
fi_rma_bw -e rdm -o read -p rxd:                        Fail
fi_rma_bw -e rdm -o writedata -p rxd:                   Fail
fi_rdm_rma -o writedata -p rxd:                         Fail

**Comment by shefty** [comment]
adding this failure as well

*** Error in `fi_av_test': double free or corruption (out): 0x083e2408 ***
fi_av_test -g 192.168.10.1 -n 1 -s 127.0.0.1 -p ofi-rxd:      Fail

**Comment by shefty** [comment]
on virtual box over udp provider:

fi_poll -t queue -p ofi-rxd:                            Fail
fi_rdm -p ofi-rxd:                                      Fail
and nearly everything else is listed as notrun... so let's just say that the provider isn't baked yet.  :) These are the only tests that passed:

fi_dom_test -n 2 -p ofi-rxd:                            Pass
fi_eq_test -p ofi-rxd:                                  Pass
fi_cq_test -p ofi-rxd:                                  Pass
fi_dgram g00n13s -p ofi-rxd:                            Pass
fi_rdm g00n13s -p ofi-rxd:                              Pass
fi_msg g00n13s -p ofi-rxd:                              Pass

very basic unit tests and 3 tests that are intended to fail immediately.

**Comment by shefty** [comment]
FYI - I'm debugging these issues.  I have a fix for the AV issue, and I'm working on the other failures.

**Comment by shefty** [comment]
These have been fixed a long time ago...
