### ISSUE TITLE
build: Allow creation of provider DL packages

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2535]
I received a request:

> When we allow building a provider as a dl, is there an easy way to only install that dl, without installing a new libfabric as well?

Yes, this is do-able.  Filing an issue here to track it.

**Comment by shefty** [comment]
This request is still relevant and being examined.  It is possible to provider DL packages for Linux by using symlinks and provider specific makefile/configure files.  It may also be possible to disable libfabric from the build, but still build the providers.

**Comment by shefty** [comment]
Let's assume that after 7 years, even though, this is still a good idea, that it's not going to happen.
