### ISSUE TITLE
EQ, CQ, CNTR fi_*_sread/from fi_cntr_wait man page request for clarification

### ISSUE THREAD

**Issue by jshimek** [ofiwg/libfabric#2538]
I am requesting clarification on what error codes the providers should return if an invalid WAIT_OBJECT type is being used when an cq, eq, or cntr is used with fi_cq_sread/from, fi_eq_sread/from, or fi_cntr_wait.

The man pages for these functions specifically state that:
It is invalid for applications to call this function if the counter/cq/eq has been configured with a wait object of FI_WAIT_NONE or FI_WAIT_SET.

But it does not specifically state what return code should be when a user calls into these functions.
Should the error return be FI_EINVAL, FI_ENOSYS, or some other return code.

Also with this I noticed that most providers support busy spin when calling into sread/from cntr_wait if no wait object is specified, but the man says this is not allowed. Is this something that should be allowed and the man page updated or do we need bugs against all the providers that have a busy spin if no wait object is defined.

@shefty

**Comment by shefty** [comment]
My oriningal thinking on this is that I do not want to force providers to insert checks in the wait calls, especially if wait support would always be there whether the application requested it or not.

That said, I think returning FI_ENOSYS is a good choice, as that allows the provider to use the current enosys version of all calls.  I do not think providers should implement no wait object support as busy waiting.

**Comment by shefty** [comment]
I did a quick check of the providers for fi_eq_sread.
* util, usnic, bgq - return FI_ENOSYS
* gni - busy wait, but I think that's the only wait support it has.
* verbs, sockets - implement an eq using an fd, so call poll.
Providers could trap for no wait object during initialization and set sread=fi_no_eq_sread.

**Comment by jshimek** [comment]
Manipulating the ops table is perfectly workable when not using FI_DIRECT, but currently when using FI_DIRECT at least with the gni provider it bypasses all the ops tables and does a direct mapping to the underlying gni functions. In that case we would need to put the checks into the underlying provider functions anyway, or require extra checks in code that currently just does a quick pass-through to the underlying providers version.

**Comment by shefty** [comment]
I'd prefer to avoid forcing providers to keep this state and process checks on every call. I'd rather use assertions to trap for this, as this is a coding error that can't be fixed at run time by the app.  At least the sockets provider should trap for this as it's intended to be used for debugging.  If a provider does want to trap for this they can, but I'd rather not mandate it.
