### ISSUE TITLE
offload collectives: completion counter per triggered op

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2558]
As discussed in previous OFIWG meetings:

In order to support collective algorithms, it is required to know (and therefore trigger) a given message, provided some other specified message completes.

Currently, the triggered ops bump the counter associated with the endpoint when they complete, therefore it is impossible to distinguish *which* message completed.

An initial proposal was to add a completion counter into the struct fi_trigger_threshold. The triggered operations would then bump that counter instead of the endpoint counter when they complete.

**Comment by shefty** [comment]
This is conceptually equivalent to controlling completions on a per operation basis.  That is, each operation would need to specify which completion queue or counter that the completion should be reported to.  This is a significant deviation from the current completion model.
