### ISSUE TITLE
offload collectives: triggered counter increments

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2559]
As discussed in OFIWG meetings:

In order to chain independent sets of triggered operations to form a composite set, we need a triggered operation that just bumps a counter (instead of initiating a message). The idea is that then you could trigger another set of messages when this composite set completes.

An initial proposal was to add a trig_inc/trig_set function to the struct fi_ops_cntr.

**Comment by shefty** [comment]
I think this needs more discussion.  Conceptually, the proposal associates an asynchronous work queue of some sort with a counter.  The triggered add/set calls chain together counters, with the chained request becoming a queued operation that generates its completion by modifying the indicated counter.  It's not clear how errors can be handled.  And the counter work queue is limited by the type of requests that it can store.

As much as it pains me to say, I think a more generic concept which could support this is active messages.  When a counter reaches some threshold, invoke a callback that can just bump the second counter.

I'm trying to think of how one could implement chained counters in software, and the additional overhead seems significant.
