### ISSUE TITLE
Is the sleep(10) in the sockets provider necessary?

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#2586]
I see a `sleep(10)` in the sockets provider before it retries when it fails to `connect()`. (see https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_conn.c#L490)

That seems a bit excessive -- doesn't that block the entire progress thread?  (or is that progress that exclusive to that connection attempt?)

**Comment by jsquyres** [comment]
Ah, I see with a closer examination that this is not in the progress thread, but rather in the downcall (E.g., through `fi_send()`) in the calling thread (I think you might have mentioned this to me before...?).

Regardless, `sleep(10)` seems a bit excessive.  Perhaps this time could be adjustable, and default to a lower value...?

**Comment by shefty** [comment]
Sleep calls anywhere seem like a hack to me.  If this is in the fi_send call, rather than sleeping, that call could return EAGAIN and let the app retry on the next send attempt.

**Comment by jsquyres** [comment]
It's the bottom of all the `fi_send*()` calls (before it hits the sockets progression thread).  See https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_conn.c#L490.

The `sleep()` is in the middle of the retry logic if the `connect()` fails.  I'm ok with the sockets provider re-trying a few times -- even if there's no sleep of any kind between attempts (and potentially returning `EAGAIN` if it ultimately fails -- I haven't traced that code to know exactly what happens all the way up the stack if sock_conn.c:sock_ep_connect() fails).

**Comment by shefty** [comment]
sleep is no longer found in sockets provider
