### ISSUE TITLE
Failed to compile libfabric with gcc '-finstrument-functions' enabled

### ISSUE THREAD

**Issue by HonggangLI** [ofiwg/libfabric#2593]
Hi,
 I'm not sure that is an issue. It maybe failed just because some functions can't be instrumented.

```
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --disable-silent-rules 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -g -finstrument-functions'

libtool: link: gcc -std=gnu99 -g -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -g -finstrument-functions -Wl,-z -Wl,relro -o util/.libs/fi_info util/info.o  src/.libs/libfabric.so -lrdmacm -libverbs -lnl-3 -lnl-route-3 -lpsm_infinipath -lpsm2 -lrt -lpthread -ldl -Wl,-rpath -Wl,/usr/lib64
src/.libs/libfabric.so: undefined reference to `_mm_prefetch'
collect2: error: ld returned 1 exit status
src/.libs/libfabric.so: undefined reference to `_mm_prefetch'
collect2: error: ld returned 1 exit status
make[1]: *** [util/fi_strerror] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [util/fi_info] Error 1
src/.libs/libfabric.so: undefined reference to `_mm_prefetch'
collect2: error: ld returned 1 exit status
```

If remove '-finstrument-functions' from configure command line, everything works as expected. I attached the rpmbuild log as "rpmbuild.txt
[rpmbuild.txt](https://github.com/ofiwg/libfabric/files/645746/rpmbuild.txt)
".
thanks

***EDIT*** Made the middle section use Github verbatim markdown

**Comment by HonggangLI** [comment]
--- ./prov/verbs/src/ep_rdm/verbs_utils.h.old   2016-12-12 06:22:46.266014249 -0500
+++ ./prov/verbs/src/ep_rdm/verbs_utils.h       2016-12-12 06:23:37.136681676 -0500
@@ -50,7 +50,7 @@
  defined(__x86_64__)
 #include "xmmintrin.h"
 #define FI_IBV_PREFETCH_ADDR(_addr) {                    \
-        _mm_prefetch((const char *)(_addr), _MM_HINT_T0);\
+        __builtin_prefetch((_addr), 0, _MM_HINT_T0);\
 }
 #else /* ICC || GCC && x86_64 */
 #define FI_IBV_PREFETCH_ADDR(_addr)

This rude hack works for me.

**Comment by jsquyres** [comment]
@HonggangLI Github pro tip: to render lines in verbatim mode in Github issues, surround them by lines of 3 single tick marks.  See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by shefty** [comment]
This is an old issue.  The code referenced above is no longer part of the repository.
