### ISSUE TITLE
FI_DIRECTED_RECV - missing analog to 'fi_rx_addr' and 'rx_ctx_bits'

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#2604]
The FI_DIRECTED_RECV capability requires the user to specify the source address of the message to be matched. This address must come from the address vector, but the address vector only contains **destination** addresses, not **source** addresses. This is generally not a problem when only a single endpoint with a single rx context and single tx context is used.

Yet with scalable endpoints a single endpoint can expose multiple tx and rx contexts. Furthermore, the number of tx and rx contexts could be different. How is the user supposed to obtain the fi_addr_t of the tx context from the scalable endpoint address in the address vector?

Also consider multiple endpoints where an endpoint is created with only inject capabilities. How does the remote process obtain this tx-only endpoint address? Is it required that the tx-only addresses be exchanged and placed in the address vector object as well?

I **think** this could be solved - for scalable endpoints anyway - by adding the following interface:

` fi_addr_t fi_tx_addr (fi_addr_t fi_addr, int tx_index, int tx_ctx_bits)`

The remote (receiving) process would obtain the source tx address by invoking fi_tx_addr() with the address of the scalable endpoint from the address vector.

Since we have this notion of rx and tx contexts, doesn't it follow that we actually have different fi_addr_t's for each capability? In other words, it seems that fi_addr_t's have an implicit attribute, or flags, to them composed of "FI_ADDR_TX" and "FI_ADDR_RX" bits. Each fi_addr_t can be tx-only, rx-only, rx and tx, or even no-rx and no-tx (a.k.a. scalable endpoint).

I'm not suggesting that we add flags or capabilities or attributes or anything to fi_addr_t.  I'm just suggesting that there is an implicit difference between tx- and rx-fi_addr_t's that is not addressed by the interface/documentation.

@sayantansur @pkcoff

**Comment by shefty** [comment]
The AV stores endpoint addresses, and each EP has only a single address.  The context bits can be viewed as additional steering bits to select a specific queue with the EP, but the address itself is unchanged.  There is no exposed concept of different transmit queues having different addresses.  All tx contexts from the same EP are considered the same, with no way to distinguish them at the receiver.  This was intentional.  I.e. there is no FI_DIRECTED_RECV equivalent for the send (FI_SOURCED_SEND?).  I think we would first need to understand what app needs this information and how it would make use of it.

The ABI 1.1 series defines a mechanism for reporting the source address for EPs that are not in the local AV.  But the primary objective of FI_SOURCE is to return an address that can be used to send replies to.  I can think of situations where an app may need to insert a Tx only peer into its local AV, since an AV is used with other features beyond identifying a destination EP.

**Comment by mblockso** [comment]
Ok .. let me condense and replay what you've said, then you tell me what I still don't understand. :)

All tx contexts from the same endpoint have the same address, which is the endpoint's address, and therefore you can not match a specific tx context when using FI_DIRECTED_RECV. This is by design.

Applications should not be using `fi_rx_addr()` to obtain the `fi_addr_t` that is a parameter for the `fi_[t]recv*()` functions. Just use the address from the AV instead.

The AV (likely, depending on how it is set up) contains the scalable endpoint address, but it cannot be used to initiate send operations until it is specialized via `fi_rx_addr()` .

----

I *suspect* there are (or will be) problems for MPICH/CH4 when using scalable endpoints, but don't have an example yet.  Need time more think.

**Comment by sayantansur** [comment]
I'm trying to mind read here a bit, and assuming that you meant the usage of scalable endpoints for per-communicator queues.

I think that usage is fine, since the per communicator queues really require match ordering on the RX context.
@wesbland

**Comment by mblockso** [comment]
I think I'm worried about MPI ordering between threads. :)

Usually there is no MPI ordering between threads, right? So you can imaging two threads each targeting the _same_ remote rx context and each using different tx contexts. One thread issues messages "A', "B", and "C". The other thread issues messages "X", "Y", and "Z". The MPI messages can match in any order (for example, "AXBYZC").

_However_, if the application does a "synchronizing operation", such as pthread_barrier(), then the ordering between the threads *does* matter.... right? Please tell me I'm wrong.

If these two threads are using the same tx context, then the synchronization event will order the command queue (i.e., "ABCXYZ") and the HFI will process all the messaes in the single queue in order.  But if the threads are using different tx contexts, one command queue has "ABC" and the other command queue has "XYZ", then the HFI may process the head of these command queues in an unknown order.  The *HFI* may squirt the messages from the two command queue onto the fabric with an ordering fail (i.e., "ABXCYZ").

Now maybe this is a problem with multiple tx contexts and has nothing to do with FI_DIRECTED_RECV. But regarding FI_DIRECTED_RECV, I guess my question is if it could match a specific "source tx addr" then could the _receive_ fix up this message ordering issue (if there even is an issue)?

@hajimefu

**Comment by shefty** [comment]
> All tx contexts from the same endpoint have the same address, which is
> the endpoint's address, and therefore you can not match a specific tx
> context when using FI_DIRECTED_RECV. This is by design.

Correct.  It sounds like this design decision is what needs to be discussed.

> Applications should not be using fi_rx_addr() to obtain the fi_addr_t
> that is a parameter for the fi_[t]recv*() functions. Just use the
> address from the AV instead.

Correct - fi_rx_addr is only used with transmit calls, which, depending on your point of view, means that the name sucks.

> The AV (likely, depending on how it is set up) contains the scalable
> endpoint address, but it cannot be used to initiate send operations
> until it is specialized via fi_rx_addr() .

Correct

**Comment by sayantansur** [comment]
> If these two threads are using the same tx context, then the synchronization event will order the command queue (i.e., "ABCXYZ") and the HFI will process all the messages in the single queue in order. But if the threads are using different tx contexts, one command queue has "ABC" and the other command queue has "XYZ", then the HFI may process the head of these command queues in an unknown order. The HFI may squirt the messages from the two command queue onto the fabric with an ordering fail (i.e., "ABXCYZ").

All MPI two-sided operations need to use the same TX or RX context per communicator. Even without threads. Otherwise, there is no ordering provided across contexts.

MPI one-sided operations, however, can use multiple TX contexts. Within one thread (e.g. round-robin), or with multiple threads with each thread using its own context. This is because MPI does not define Put or Get ordering.

I *think* this is the definition we want. We should encourage MPI to relax its two-sided ordering rule such that MPI implementations can leverage more contexts simultaneously.

**Comment by mblockso** [comment]
Ok .. so I guess I was looking for an optimization in ofi for multiple tx contexts to support an optimization in MPI that is disallowed by the MPI standard? uhg.

**Comment by sayantansur** [comment]
haha, if you put it that way 😃

**Comment by mblockso** [comment]
I swear .. sometimes I feel like I am just wasting my time with all this messaging crap.

**Comment by sayantansur** [comment]
Good news is that @jdinan is pushing for changes to the MPI standard to relax ordering. It might not hurt to implement the proposed changes in MPI and map to multiple TX contexts.

**Comment by jdinan** [comment]
All parts of the proposal cleared first voting.  Should be ratified at the February meeting.  Woot!

Details here: mpi-forum/mpi-standard#14

**Comment by mblockso** [comment]
Closing this issue .. thanks for the fun conversation everyone!
