### ISSUE TITLE
Confusing use of the word "free" when referring to the FI_MULTI_RECV buffer

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2616]
Both the fi_msg and fi_endpoint man pages say that the multirecv buffer is freed, but I don't think that's what is meant.

- fi_endpoint: "Defines the minimum receive buffer space available when the receive buffer is automatically freed "
- fi_msg: "The buffer will be freed from the endpoint when the available buffer space falls below the network’s MTU size (see FI_OPT_MIN_MULTI_RECV)"

Also, the last bit about the MTU size seems like it should be changed.  It's a good suggested value, but doesn't have to be since you can change FI_OPT_MIN_MULTI_RECV via fi_setopt.

I'm happy to reword this if there are no objections.

**Comment by shefty** [comment]
Free could be better worded as returned or released by the provider.

Yes, please feel free to submit a PR with improved wording.  :)

**Comment by sungeunchoi** [comment]
Actually while we're on the topic, what error code should be returned in the error CQE if the last message delivered to a multirecv buffer is truncated?  Is this supposed to be provider-specific or should it be specified in the man page.

**Comment by shefty** [comment]
I can't easily find a consistent value used by the providers for this.  There's FI_ETRUNC as an error code that would work well, but that may have been added after providers selected some other value.  But if we can update all providers to use this value, it would be ideal.
