### ISSUE TITLE
Update providers to report number of counters

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2620]
For providers that support counters, update new domain attribute field. d670d791714b25907fb247bc9313b2cbe3194648

- [ ] bgq
- [x] gni
- [x] mlx
- [x] psm
- [x] psm2
- [x] rxd
- [x] rxm
- [x] sockets
- [x] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff
