### ISSUE TITLE
Update providers to support FI_SYNC_ERR for AV insertion

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2621]
See 380660902cd95c95fcacb338319214651e1ba7df.  Providers either need to support the new flag or at least fail any call that attempts to pass it in.

- [ ] bgq
- [x] gni
- [ ] mlx
- [x] psm
- [x] psm2
- [ ] rxd
- [ ] rxm
- [ ] sockets
- [ ] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by gladkovdmitry17** [comment]
@shefty  please, mark verbs provider. it was done within #2803
