### ISSUE TITLE
Providers should determine if they want to use FI_NOTIFY_FLAGS_ONLY mode bit

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2622]
This is a new mode bit, so no changes are required.  But providers may want to require it.  See 0f793fb6150756d1af19252001b81bdfc0d70eac

- [ ] bgq
- [x] gni
- [ ] mlx
- [x] psm
- [x] psm2
- [x] rxd
- [x] rxm
- [x] sockets
- [x] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff
