### ISSUE TITLE
Providers and core may want to support new address string format

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2623]
See 08f174f23061077d8db84f23729c5b2a78c5df68.  Providers can opt into supporting the new string format.  If necessary, the core may assist with parsing such strings (existing parsing functionality may already exist or just need to be expanded).

- [ ] bgq
- [ ] gni
- [ ] mlx
- [ ] psm
- [ ] psm2
- [ ] rxd
- [ ] rxm
- [ ] sockets
- [ ] udp
- [ ] usnic
- [ ] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by bturrubiates** [comment]
Just looked at the docs and have a few questions:

1. Can applications provide an `FI_ADDR_STR` formatted address in the `src_addr` and `dest_addr` fields of the `fi_info` struct? I assume so, but the docs only seem to mention overloading the `node` field.
2. How do I get an `FI_ADDR_STR` formatted address from an existing fabric configured with format `FI_SOCKADDR_IN`?
3. Is there a defined mechanism to switch address formats, or open a fabric with an addr format different than the type specified? So for instance, open a fabric using a destination hint in `FI_ADDR_STR` format but use `FI_SOCKADDR_IN` for future `fi_av_insert` calls?

**Comment by shefty** [comment]
> 1.	Can applications provide an FI_ADDR_STR formatted address in the
> src_addr and dest_addr fields of the fi_info struct? I assume so, but
> the docs only seem to mention overloading the node field.

Yes - they just need to set the addr_format correctly.  The overloading of node field is additional documentation to indicate how FI_ADDR_STR is passed in directly to fi_getinfo.

> 2.	How do I get an FI_ADDR_STR formatted address from an existing
> fabric configured with format FI_SOCKADDR_IN?

New helper functions need to be added to provide the to/from conversions. ofi_get_addr() can be adapted to be the from str to sockaddr call.

> 3.	Is there a defined mechanism to switch address formats, or open a
> fabric with an addr format different than the type specified? So for
> instance, open a fabric using a destination hint in FI_ADDR_STR format
> but use FI_SOCKADDR_IN for future fi_av_insert calls?

No, all addresses must be in the same format.  The exception is that fi_getinfo() will attempt to convert from node/service, which can be in STR format, while the rest of the API is in sockaddr format.

**Comment by bturrubiates** [comment]
> New helper functions need to be added to provide the to/from conversions. ofi_get_addr() can be adapted to be the from str to sockaddr call.

I don't think my original question was that clear, I actually meant how would an application get an address in `FI_ADDR_STR` format from an existing fabric configured with some other address format type. The use case for this would be the original feature request. Some fabric is opened and the address is going to be sent over some out-of-band communication as a string.



> No, all addresses must be in the same format.  The exception is that fi_getinfo() will attempt to convert from node/service, which can be in STR format, while the rest of the API is in sockaddr format.

If I understand correctly, then the application would pass in an `FI_ADDR_STR` formatted address in the `node` parameter, but the `addr_format` could be anything like `FI_SOCKADDR_IN` and the provider would correctly handle the conversion?

**Comment by shefty** [comment]
The application must specify FI_ADDR_STR for their address format.  The fi_getinfo node/service parameters are the same as always.  They can be a hostname, string based IP address, an FI_ADDR_STR formatted string, or some other character array that providers can interpret.

fi_getname() will return an FI_ADDR_STR formatted string, which can be exchanged out of band and inserted in AVs.

An app cannot mix address formats.  That would be impossible for a provider to distinguish.  The definition for FI_ADDR_STR is documented, so converting between a well-known format, such as sockaddr_in, to FI_ADDR_STR is doable by the app if that really have the need.  The goal of FI_ADDR_STR is that the app does not need to be able to interpret the string, only exchange it.

**Comment by bturrubiates** [comment]
> fi_getname() will return an FI_ADDR_STR formatted string, which can be exchanged out of band and inserted in AVs.

Okay, makes sense. When configured with `addr_format == FI_ADDR_STR`, the `fi_getname` function will return an `FI_ADDR_STR` formatted string (as expected). 

Is there any interest in having the `fi_av_straddr` output mirror the `FI_ADDR_STR` output from `fi_getname`?

**Comment by shefty** [comment]
> Is there any interest in having the fi_av_straddr output mirror the
> FI_ADDR_STR output from fi_getname?

This makes sense to me.

**Comment by bturrubiates** [comment]
> This makes sense to me.

Okay, I'll work on making this sort of change in usNIC. The `FI_ADDR_STR` output will _always_ be available via `fi_av_straddr`, and also be available conditionally from `fi_getname` iff `addr_format == FI_ADDR_STR`.

**Comment by bturrubiates** [comment]
> New helper functions need to be added to provide the to/from conversions. ofi_get_addr() can be adapted to be the from str to sockaddr call.

The core can provide a function for converting the standard `AF_` address families into `node;service` and then the providers could make use of this. I'm suggesting that it only format the `node` and `service` parameter because it's likely the provider will want control over the prefix (the "family" or provider name) and the suffix. 

So from a provider's perspective, it would probably be something like: 

```c
const char *straddr(av, addr, buf, len)
{
    char middle[64];
    ofi_addr_str(format, addr, str, sizeof(str));
    snprintf(buf, len, "usnic;%s;field1", middle);
    return buf;
}
``` 

Does that seem like a reasonable addition to the core? I think it could probably be rolled into `ofi_get_addr`, but it would need another address format parameter added. So if you pass in a node/service you can specify with the current `addr_format` field that you want an `FI_ADDR_STR` but that doesn't say anything about whether the str represents `FI_SOCKADDR_IN` or `FI_SOCKADDR_IN6`. 

For the destructuring, it could take a format (allowing the provider to have control over this), and basically just parse the string based on an address family given `AF_INET/AF_INET6`. The provider could then handle all of the stuff at the end of the string separately. (That way the provider can accept something like "usnic;..." and choose to interpret it as `AF_INET` by default.)

 I could add these functions as part of my usNIC changes.

Thoughts?

**Comment by shefty** [comment]
I believe that there should be helper functions in the core to assist with the sockaddr types at least. The specific details can be worked out once we have patches and users of it, but this seems like a reasonable start at least.

**Comment by jsquyres** [comment]
@shefty What happened to this -- are there helper functions in the core?  (I ask because @thananon  is working on this for usNIC literally right now)

**Comment by shefty** [comment]
Yes, there are helper functions that I added within the last week or so.  See the 2 new calls added here:

https://github.com/ofiwg/libfabric/blob/master/include/fi.h#L223
