### ISSUE TITLE
Providers that support counters need to set new cntr methods

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2625]
See 0f59e702474259f6e48fffec3d91b171e02badbd.  Add/set error functions were added.  ENOSYS versions are needed and providers that set counters should set these calls.

- [ ] bgq
- [ ] gni
- [x] mlx
- [x] psm
- [x] psm2
- [x] rxd
- [x] rxm
- [ ] sockets
- [x] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by e-harvey** [comment]
@shefty We can't tell from the man page, do triggered operations apply to error counters?

**Comment by shefty** [comment]
As currently defined, no, only the success value.

**Comment by jswaro** [comment]
@shefty The documentation isn't terribly clear about that detail. Could it be amended?

**Comment by gladkovdmitry17** [comment]
@shefty  Could you mark verbs provider? adderr/seterr is already implemented for verbs provider. Thanks!
