### ISSUE TITLE
Providers need to set the comp_list fabric attribute

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2628]
See bfbb27f9e7d9598899af40488bb492654edcdf13.  The util providers need to make use of this to avoid circular dependencies.  There may be help that the core layer can provide as part of fi_getinfo,

- [ ] bgq
- [ ] gni
- [ ] mlx
- [ ] psm
- [ ] psm2
- [ ] rxd
- [ ] rxm
- [ ] sockets
- [ ] udp
- [ ] usnic
- [x] verbs

**Comment by mblockso** [comment]
@pkcoff

**Comment by a-ilango** [comment]
@shefty I'm assuming this feature would have to be implemented only by the utility providers; the core providers need not set this string. But the man page update is pretty generic about this indicating that the core providers can also add strings:
"The component list is a comma separated set of string identifiers, each corresponding to a **specific core** or utility provider or **feature**" (emphasis mine)

**Comment by shefty** [comment]
The core providers probably don't need to set anything here.  I left the possibility open, so that a core provider could add to the string to indicate a specific implementation choice had been made.  For example, a core provider that makes use of shared memory for loopback communication might list that here.

**Comment by shefty** [comment]
I have a patch to remove comp_list from the API.  This is in response to changes that were made to the prov_name field instead in PR #2808 .
