### ISSUE TITLE
Triggered support proposals

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2630]
Related to #2558 and #2559.  Starting a new issue to discuss triggered operations in general, as I'm not convinced that the current definition is 'correct' and should be expanded.  (I'm referring to expanding the current definition, not expanding triggered operations or collective support as a concept).

I'm trying to define a foundation of what triggered operations are, and came up with this list of basic components.

- deferred work queue(s)
- _cause_ operations - result in the deferred WQ being processed
- _effect_ operations - operations posted on the deferred WQ
- conditions - events needing to be met before initiating a deferred operation

**Proposal**: a deferred WQ entry will consist of a _single_ operation and condition.  This is for simplicity, but I hope will be sufficient.

The existing APIs do not expose the deferred WQ, but the API _implies_ it is part of an EP.  #2559 suggests that this is not necessarily true.  The association of the WQ with other objects matters as that restricts the operations and conditions that can be defined.

**Proposal**: we associate a single deferred WQ with the domain.  A single WQ is for simplicity.  Moving to the domain provides greater flexibility for what a WQ entry can specify.

Note that we're not defining an implementation, only the conceptual model as viewed by the application.  I'm not sure if the WQ needs to be explicitly exposed.  #2558 is asking for the ability to make one WQ entry dependent upon another WQ entry.  On top of that we need some way to handle errors, where a condition can never be met.

**Proposal**: expose the deferred WQ entry to the application.  That is, the app needs some sort of handle related to the WQ entry.  Allow applications to cancel queued entries, similar to fi_cancel().   Applications are responsible of detecting errors and canceling queued entries that will never execute.

**Proposal**: Add an FI_TRIGGER mode bit to the domain.  When set, _all_ of the conditions eventually defined must be met by the provider.

**Proposal**: The current EP triggered definitions may be deprecated.  We will make an effort to integrate it with the new definitions.

If these proposals are accepted, the challenge is defining the WQ entry to support a wide number of possible conditions and operations.  Part of the intent with this change is to isolate triggered ops from the rest of the API as much as possible, so that it can be supplanted by more collective focused building blocks in the future.  We can even mark the triggered ops as experimental.

**Comment by shefty** [comment]
@sayantansur

**Comment by sayantansur** [comment]
Thanks, I'll think more in detail about this, but it seems like we really need to rethink how we exposed triggered as you suggest.
