### ISSUE TITLE
Need clarification about shared context attributes

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2634]
From the SHARED CONTEXT section of the fi_endpoint man page (under fi_stx_context):

> The exception is that endpoints attached to a shared transmit context must use a subset of the transmit context attributes. This is opposite of the requirement for scalable endpoints.

A similar statement is made for fi_srx_context.

I don't quite see how it's the "opposite" requirement.  Does that mean that for the contexts for scalable endpoints, the attributes *cannot* be a subset?  The man page section on contexts for scalable endpoints says that they can be configured with fewer attributes than the base endpoint.

Can someone clarify?

**Comment by shefty** [comment]
Here's what it's trying to convey:

Scalable EPs: The *context* has a subset of the (scalable) *EP* capabilities.
Shared Contexts:  The *EP* has a subset of the (shared) *context* capabilities.

This is the 'opposite' being described.  But I can see how someone would associate the scalable EP with the shared context, as they are both created first, which leads to the confusion.

For a scalable EP, the scalable EP has more capabilities than the independent rx/tx contexts.  For example, the scalable EP can be configured with FI_SEND + FI_RMA support.  A transmit context that belongs to the scalable EP can support one of these options: FI_SEND _or_ FI_RMA _or_ FI_SEND + FI_RMA.

For an EP that uses shared contexts, the shared context is first configured.  For example, shared Tx can be configured with FI_SEND + FI_RMA support.  An EP that uses the shared Tx can support one of these options: FI_SEND _or_ FI_RMA _or_ FI_SEND + FI_RMA.
