### ISSUE TITLE
Need better way to tell if per context attributes are supported

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2635]
It seems the only way to tell if a provider supports per tx/rx context attributes is by inspecting the returned context:

> Support for per transmit context attributes is provider specific and not guaranteed. Providers will return the actual attributes assigned to the context through the attr parameter, if provided.

(similar for receive contexts).

As a client, this means that if I set up my initial scalable endpoint with the minimal common set of attributes and wanted to add to those with each context, the only way for me to tell if the provider did not support this is to set up the endpoint and then inspect the attributes returned by fi_tx/rx_context.  If they were not the ones I requested, I'd have to tear everything down and start over.

It seems like a endpoint (or possibly domain) attribute could help clear this up earlier before I started down the path.

**Comment by shefty** [comment]
The intent is that all contexts associated with a scalable EP either support the requested subset of attributes or all attributes that the scalable EP has.  For example, if the scalable EP has FI_SEND + FI_RMA, and the user opens a context asking only for FI_SEND support, the returned context may actually support FI_SEND + FI_RMA.

This is done to give the provider greater flexibility in how they implement shared EPs, where it may not be able to selectively enable capabilities completely independently.  The ability to specify fewer attributes is an optional optimization technique, more than a requirement on the provider.

**Comment by sungeunchoi** [comment]
Okay that makes more sense.  Given a couple of us read it the other way, mind if a take a whack and fixing up in the wording in the man pages?

**Comment by shefty** [comment]
Please feel free to update the man pages to make them more understandable.
