### ISSUE TITLE
prov/util: verify_addr doesn't appear to iterate the iov structure

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#2637]
See https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_mr.c#L93-L96

It looks to me that it will compare (iov_base, iov_base + iov_len) of iov index 0 against the mr range for iov_count times, without changing the iov range. 

I'm guessing it was meant to be something closer to the following: 
```C
    for (i = 0; i < item->iov_count; i++) {
        start = (uintptr_t) item->mr_iov[i].iov_base;
        end = start + item->mr_iov[i].iov_len;

        if (start <= in_addr && end >= (in_addr + in_len))
            return 0;
    }
```

Is it incorrectly written, or am I misunderstanding the purpose of the function?

**Comment by shefty** [comment]
This entire file and surrounding code needs to be cleaned up.  It doesn't follow the coding style and its correctness looks questionable in a couple of other places.
