### ISSUE TITLE
prov/sockets: fi_close of scalable endpoint should return -FI_EBUSY if there are open contexts

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2638]
As per the man page.

**Comment by shefty** [comment]
sock_ep_close() has this code:
```c
	if (atomic_get(&sock_ep->attr->ref) || atomic_get(&sock_ep->attr->num_rx_ctx) ||
	    atomic_get(&sock_ep->attr->num_tx_ctx))
		return -FI_EBUSY;
```
Based on a code inspection, it looks like num_*x_ctx is incremented/decremented correctly based on opening/closing a context.  Do you have a test that is failing?

**Comment by sungeunchoi** [comment]
Sorry I mis-reported this.  I'll close an open a different issue.
