### ISSUE TITLE
prov/bgq: Make MPI3 MPICH-CH4-OFI beta release 0.1 available to BGQ users at Argonne

### ISSUE THREAD

**Issue by pkcoff** [ofiwg/libfabric#2648]
Here is what we have left to do before make a beta release of MPI3 MPICH-CH4-OFI (beta in that CH4 will not have its first production release until summer and we're still missing some core optimizations for which I will make another issue) available to BGQ users at Argonne on all 3 systems (Mira, Cetus and Vesta).

1.) Some code-cleanup / optimization to remove branching related to remote CQ Data support.
2.) Resolve a problem with the new capability set specification support with MPICH.
3.) Final regression testing.

Target date for this release is 2017-01-20.

**Comment by mblockso** [comment]
Might want to add a "documentation cleanup" step.  I don't think the current documentation is 100% accurate.

**Comment by pkcoff** [comment]
4.) Documentation cleanup.
5.) MPICH Jenkins build integration.

**Comment by pkcoff** [comment]
Line item 1 has been resolved, involving mpich and libfabric fixes.  I'll create a pr for this release in mpich and libfabric git repos.

**Comment by pkcoff** [comment]
Line item 2 has finally been resolved.

**Comment by pkcoff** [comment]
Going with my github fork for mpich and ofi Release 0.1 available to users at Argonne and being tried by 1 project already, will submit pull request once I have the hw accelerated rma working.
