### ISSUE TITLE
Define mechanism needed to support FI_MR_MMU_NOTIFY

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2668]
See PR #2659.  MMU_NOTIFY needs additional details on how the notification is accomplished.

**Comment by shefty** [comment]
@jswaro @hppritcha - I need assistance ensuring that we get the proper solution for this.  Based on my current knowledge, I'm proposing adding the following operation:

```
fi_mr_refresh(mr)
```

I don't think any parameters are needed, but I'm not sure.  (I may add a void * and flags for future extensibility, but I'm not sure if I'll do that either.)  The intent is that an app must call refresh any time there is a (potential) change to the memory pages backing a registered memory region.  Refresh has the effect of implicitly disabling and re-enabling the MR, which may result in active operations against the MR failing.

@sayantansur - I'm hoping this same API will work to handle the race raised in #2728, though with a different MR mode bit that I can't come up with a good name for.

**Comment by jswaro** [comment]
I would recommend the following definition:

fi_mr_refresh(domain, mr, flags); 

I like the idea of keeping flags in the definition for future proofing the function.

**Comment by sayantansur** [comment]
@shefty do you mean that the unnamed MR mode bit will indicate that this MR will be "refreshed" in the future?

**Comment by shefty** [comment]
@sayantansur - Let's call the new mode bit FI_MR_STATIC.  When set, then any changes to the MR attributes or bindings require that the app call fi_mr_refresh() to update them.  The definition of refresh is the same as above.  I.e. the MR is implicitly disabled/enabled. (Alternatively, any update automatically results in the MR being refreshed.)  Something like this anyway.

**Comment by sayantansur** [comment]
OK, thanks, yes, that works.

**Comment by shefty** [comment]
My intent was to wrap fi_mr_refresh around the MR fi_control interface.  So, we have this as the interface into the provider: control(mr, command, arg).  Arg would be reserved and NULL.  Command FI_REFRESH.  I'll work on a patch for further discussion.

**Comment by jswaro** [comment]
Actually, we may need additional parameters other than what I specified above. Depending on the provider, some update functions may require only the changed pages when refreshing a memory registration, not the entire range of pages. It would be beneficial to have address and length fields added to the parameter list.

**Comment by shefty** [comment]
I just pushed up a commit with my current proposal.  I included a void * parameter as input into fi_mr_refresh().  That parameter is currently reserved.  We can expand the proposal to define some sort of data structure to pass into that call.  The closest existing structure we have is this:
```
struct fi_mr_attr {
	const struct iovec	*mr_iov;
	size_t			iov_count;
	uint64_t		access;
	uint64_t		offset;
	uint64_t		requested_key;
	void			*context;
	size_t			auth_keylen;
	uint8_t			*auth_key;
};
```

If we can re-use this, great, though I'd like to define something like this:
```
struct fi_rm_refresh {
    uint64_t flags;
    struct fi_mr_attr attr;
};
```
Thinking beyond the current need, refresh could be used to modify a MR, so I want to ensure that we have something extensible (but usable!) here.  Note that we can add the flags as a parameter to fi_mr_refresh() and have the static inline format the actual structure that is passed to the provider.

**Comment by jswaro** [comment]
Interesting. **What would the new definition look like?** 

The mr_iov could cover the range to be updated, and iov count to determine the number of regions. 

I wouldn't expect the access/offset/requested_key/contexts to change unless we want to support true re-registration capabilities, or unless a provider supports capability/attribute changes in live registrations.

I don't think auth_keylen and auth_key changes on a live memory registration makes sense, but we could document that those attributes are ignored for refresh in the spirit of reusing structures.

**Comment by shefty** [comment]
Just to be clear, I only mention fi_mr_attr because it's an existing structure.  The refresh call itself is documented as disabling/enabling the MR, so support for live updates aren't required.  I'm still trying to figure out the best option here...  What if we tried this?

```
/* control operations */
enum {
    ...
    FI_REFRESH  /* struct fi_mr_modify */
    ...

struct fi_mr_modify {
    uint64_t flags;
    struct fi_mr_attr attr;
};

static inline int fi_mr_refresh(struct fid_mr *mr, const struct iovec *iovec,
    size_t iov_count, uint64_t flags)
{
    struct fi_mr_modify attr;
    attr.flags = flags;
    attr.mr_iov = iovec;
    attr.iov_count = iov_count;
    return mr->fid.ops.control(&mr->fid, FI_REFRESH, &attr);
}
```
In the future, additional control commands could be used to modify other aspects of the MR.

**Comment by jswaro** [comment]
I think I could be OK with this definition. I'm going to give it some more thought tonight to make sure I haven't missed anything.

**Comment by shefty** [comment]
See #2729 - just updated about 1 minute ago.

**Comment by sdvormwa** [comment]
> The refresh call itself is documented as disabling/enabling the MR, so support for live updates aren't required.

Why would a client want to use FI_MR_MMU_NOTIFY/fi_mr_refresh() without live updates?  To me, the whole point of FI_MR_MMU_NOTIFY is to allow the client to update parts of the MR that aren't currently being targeted without having to sync up with remote endpoints that are targeting other parts of the MR--it's a lot cheaper to sync up with just the remote endpoints that need to target the newly updated range than to sync up with _and quiesce_ everyone targeting any part of the MR.  By permitting off-line updates, the API prevents the performance improvement that comes with live updates while allowing...what?

**Comment by shefty** [comment]
An app doesn't really want to use FI_MR_MMU_NOTIFY at all.  This is a restriction placed by the provider, and I have no idea if gni supports live updates or not.  I defined fi_mr_refresh so that it can be implemented as widely as possible.  Even without live updates, the advantages with MMU_NOTIFY are that the provider can re-use page table entries when updating the mapping, and the key does not change.  The gni provider is driving this change.  If it can support live updates, we can adjust the definition or mr mode details.
