### ISSUE TITLE
prov/sockets: accidentally binding RX CQ with FI_TRANSMIT results in confusing failure

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2673]
The setup runs without hiccup:
```
    ret = fi_rx_context(ep, i, NULL, &rx_ep[i], NULL);
    assert(ret == FI_SUCCESS);
    ret = fi_cq_open(domain, &cq_attr, &rx_cq[i], NULL);
    assert(ret == FI_SUCCESS);
    ret = fi_ep_bind(rx_ep[i], &rx_cq[i]->fid, FI_TRANSMIT); // This could warn (GNI provider fails)
    assert(ret == FI_SUCCESS);
```
But then the close fails with -FI_EBUSY:
```
    ret = fi_close(&rx_ep[i]->fid);
    assert(ret == FI_SUCCESS);
    ret = fi_close(&rx_cq[i]->fid);
    assert(ret == FI_SUCCESS); // Fails here with ret = -FI_EBUSY
```

**Comment by shefty** [comment]
>     ret = fi_ep_bind(rx_ep[i], &rx_cq[i]->fid, FI_TRANSMIT); // This
> could warn (GNI provider fails)

IMO - this should be a failure.  I'll look at updating the socket code.

>     ret = fi_close(&rx_ep[i]->fid);
>     assert(ret == FI_SUCCESS);
>     ret = fi_close(&rx_cq[i]->fid);
>     assert(ret == FI_SUCCESS); // Fails here with ret = -FI_EBUSY

This is the new and now correct behavior (added to fix a crash).  The CQ must be closed prior to closing the EP, since the EP is bound to the CQ.

**Comment by sungeunchoi** [comment]
>>     ret = fi_close(&rx_cq[i]->fid);
>>     assert(ret == FI_SUCCESS); // Fails here with ret = -FI_EBUSY
> This is the new and now correct behavior (added to fix a crash).  The CQ must be closed prior to closing the EP, since the EP is bound to the CQ.

Correct.  I'm trying to close the CQ in the line above.

**Comment by shefty** [comment]
> 		ret = fi_close(&rx_cq[i]->fid);
> 		assert(ret == FI_SUCCESS); // Fails here with ret = -
> FI_EBUSY
> 
> 
> 	This is the new and now correct behavior (added to fix a crash).
> The CQ must be closed prior to closing the EP, since the EP is bound to
> the CQ.
> 
> Correct. I'm trying to close the CQ in the line above.

Sorry - I wrote that backwards.  The EP must be closed before the CQ.  Otherwise completions from the EP have no where to go.

**Comment by sungeunchoi** [comment]
Interesting.  In my same test program, I was able to close the TX CQ before the endpoint.  I'm assuming that's a bug, then?

**Comment by shefty** [comment]
I added referencing counting late last week to the socket provider to fail CQ close calls if there is an opened EP associated with it.  Have you tried with the latest upstream code?

**Comment by sungeunchoi** [comment]
Hang on a sec.  Are we talking about the SEP or the tx/rx contexts?

**Comment by shefty** [comment]
I added reference counting for the rx/tx contexts.

**Comment by sungeunchoi** [comment]
But are you saying that the SEP must be closed before the CQs, or are you saying that the tx/rx contexts must be closed before the CQs?  My test code does the latter.  From reading the man page, it seemed that the SEP shouldn't be closed until all of the above are closed.

**Comment by shefty** [comment]
The rx/tx contexts should be closed before closing the CQs or SEP.  The order between the CQ and the SEP shouldn't matter.

**Comment by sungeunchoi** [comment]
Okay, then my example above seems like it shouldn't fail on close of the RX CQ (of the CQ that was accidentally bound with FI_TRANSMIT).  I guess that problem goes away if the error with the flags returns failure, but seems like there might be some strange logic in there somewhere.  FWIW, if I open the TX CQ with FI_RECV, the same thing happens (close of tx_cq returns -FI_EBUSY).

**Comment by chuckfossen** [comment]
Reading through these comments, it sounds like only rx/tx contexts have the restriction of closing before the CQ is closed - not endpoints. Do I have that correct? The man page states: "When closing the CQ, there must be no opened endpoints, transmit contexts, or receive contexts associated with the CQ."

**Comment by shefty** [comment]
Normal (i.e. non-scalable) endpoints must be closed before closing the CQ.

**Comment by chuckfossen** [comment]
Does the sockets provider enforce this?

**Comment by shefty** [comment]
I'm not sure.  I added referencing counting to the sockets provider late last week, which may cover non-scalable EPs

**Comment by sungeunchoi** [comment]
Regardless, this isn't clear from the man pages and should be document.
