### ISSUE TITLE
Clarify use of fi_read()/fi_write()/fi_send() with use of unconnected endpoint

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#2683]
The [fi_rma(3)](https://ofiwg.github.io/libfabric/v1.4.0/man/fi_rma.3.html) and [fi_msg(3)](https://ofiwg.github.io/libfabric/v1.4.0/man/fi_msg.3.html) manpages state the following property for fi_read()/fi_write()/fi_send():

> The local endpoint must be connected to a remote endpoint or destination before ... is called.

The msg variants fi_readmsg()/fi_writemsg()/fi_sendmsg() state:

> The ... call supports data transfers over both connected and unconnected endpoints

Is the intent here really to only allow the use of the msg variants with connectionless endpoint types such as FI_EP_RDM?

**Comment by shefty** [comment]
All calls support connected and unconnected endpoints.  RMA operations require reliability as well.  The endpoints must be in the enabled state, and connection-oriented endpoints must be fully connected.

The connection comment under fi_send() should be ignored (and will be removed).
