### ISSUE TITLE
fi_cntr_read() and FI_THREAD_* modes

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#2704]
Say we have multiple tx contexts bound to a single counter and we want lock-free access to these tx contexts by multiple threads (perhaps the tx contexts are pinned to a thread, etc), yet these threads need to know when the shared counter has reached a certain value. 

Can these threads concurrently invoke `fi_cntr_read()` without forcing the domain into `FI_THREAD_SAFE` or some other onerous thread mode?

**Comment by shefty** [comment]
I think FI_THREAD_FID meets the requirements, as long as the app adds synchronization around fi_cntr_read().  My guess is that if the app doesn't lock around fi_cntr_read(), the code is likely to work correctly for most provider implementations of counters.

Maybe we can document that fi_cntr_read() must always be thread safe.  I'd need to see if this would cause a burden on any reasonable implememtation.

**Comment by mblockso** [comment]
> Maybe we can document that fi_cntr_read() must always be thread safe. 

It would be great if we can do this .. thread-safe counter read is all we really need.
