### ISSUE TITLE
fi_cntr max?

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#2705]
Are there provider-specific limitations on the number of counters that can be allocated/opened? Is there any way to query these limits instead of just "opening until fail"? Maybe something similar to the `fi_ep_attr::tx_ctx_cnt` attribute?

**Comment by shefty** [comment]
See fi_domain_attr::cntr_cnt, recently added for ABI 1.1

**Comment by mblockso** [comment]
thanks sean .. closing
