### ISSUE TITLE
prov/sockets: fi_write operation does not progress even with call to fi_cq_read

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2718]
When using manual data progress, if I do an fi_write and then repeatedly read the CQ bound to that ep, the write operation does not progress and the program hangs.  This can be even be seen in a single process job using 2 domains with an endpoint each and fi_write operations to each other.

I have not tried it with fi_read.

**Comment by sungeunchoi** [comment]
I confirmed that the same problem exists for fi_read.  I have a test program if anyone is interested.

**Comment by gladkovdmitry17** [comment]
@sungeunchoi could you send me your test program, please? it may speed up resolution of problem. I guess, I could take a look at this problem on this week.

**Comment by sungeunchoi** [comment]
[test_program.zip](https://github.com/ofiwg/libfabric/files/822966/test_program.zip)

**Comment by sungeunchoi** [comment]
See comments in that file, but if you change to sockets provider, it hangs.

**Comment by shefty** [comment]
The test program looks in error to me for handling manual progress.  When the test spins reading cq0, nothing is progressing ep1.  Cq0 is bound with ep0, but ep1 is bound to cq1.  You need to read both cq's to ensure that the write is progressed at both sides of the communication.  A fix to the program would be to read cq0 and cq1 in the same loop.

Note that I didn't try running the test.  I'm only performing a code inspection.

**Comment by sungeunchoi** [comment]
Why should ep1 have to be advanced to get a completion on ep0?  According to the man page, if I am waiting for a completion on ep0, I only need to read from cq0.

**Comment by sungeunchoi** [comment]
Actually, while we're here, the man page actually says "wait" on cq, eq, etc.  Is that meant to mean an actual wait call or does a read suffice.  If a wait call, then this program is wrong, but for a different reason.

**Comment by shefty** [comment]
Reading the CQ is sufficient.

The problem is that both endpoints are set to manual progress.  The result is that ep1 is not being progressed, which in turns affects anyone attempting to send to it.  Without progressing ep1, it will not process any incoming messages (such as the write from ep0) or send any acks.

**Comment by sungeunchoi** [comment]
I guess I do not get that from the man pages, but maybe I'm looking in the wrong place.  To me the fi_domain man page just says that I should care about the completions.

**Comment by sungeunchoi** [comment]
FWIW, I ran into this when using scalable endpoints.  I didn't bother advancing the rx contexts since I wasn't expecting remote events.

**Comment by sungeunchoi** [comment]
@shefty So what is the recommended thing to do in this case.  With manual progress, I have an rx context (from a scalable ep), to which I'm doing fi_writes(), and I don't want remote side notifications.  Do I have to artificially bind a cq/cntr to that rx context and query it every now and then even if I'm expecting nothing?

**Comment by shefty** [comment]
I need to think about this more, but I think what you suggested is required.  If the target side is also set to manual progress, it needs to do something to ensure that its peer can make progress.  Binding to a CQ and reading it seems like the best option.

**Comment by sungeunchoi** [comment]
Here is a behavior that I'm seeing with the sockets provider, which I believe is what is described by the man pages, thought I had to look a few times, so now I'm not sure.

I have 2 peers with a single endpoint each doing the following:

```
fi_write to peer

while (!done) {
  // check counter for FI_WRITE and FI_REMOTE_WRITE
}
```

If I don't have the counter bound with FI_REMOTE_WRITE, neither side progresses beyond just having the fi_write complete.  That is, the data never gets to the remote side.

So my conclusion is that if you want fi_write to progress, if using counters you need to have the remote side checking for FI_REMOTE_WRITE.

I haven't tried something similar with CQs, so I'm not sure what the equivalent is.  In particular, I'm wondering if I need to send remote CQ data for it to progress properly, or if just checking for FI_RECV is enough (even if nothing is received).

**Comment by shefty** [comment]
> I have 2 peers with a single endpoint each doing the following:
> 
> fi_write to peer
> 
> while (!done) {
>   // check counter for FI_WRITE and FI_REMOTE_WRITE
> }

IMO this should be sufficient.  There may be an issue in the provider.

 
> I haven't tried something similar with CQs, so I'm not sure what the
> equivalent is. In particular, I'm wondering if I need to send remote
> CQ data for it to progress properly, or if just checking for FI_RECV
> is enough (even if nothing is received).

Just checking FI_RECV should be sufficient.

**Comment by sungeunchoi** [comment]
> IMO this should be sufficient.  There may be an issue in the provider.

Sorry I didn't mean to imply that my example didn't work in the sockets provider.  It does.  I just wanted to make sure I interpreted the man pages correctly.

> Just checking FI_RECV should be sufficient.

I confirmed it does.  Thanks.
