### ISSUE TITLE
prov/gni: ioctl(GNI_IOC_MEM_DEREGISTER) returned error - Invalid argument at line 612 in file mem_registration.c

### ISSUE THREAD

**Issue by agrippa** [ofiwg/libfabric#2735]
On Edison with the SoS fork at https://github.com/jdinan/sandia-shmem and using the 'contexts' branch, running many PEs per node consistently causes the following error:

Warning: GNI_MemDeregister: ioctl(GNI_IOC_MEM_DEREGISTER) returned error - Invalid argument at line 612 in file mem_registration.c

I'm using an OFI installation provided by Howard Pritchard, he can add more details on its configuration.

In particular, this error appears on every run with 22, 23, or 24 PEs per node. 21 PEs per node shows no failures.

I've attached a ZIP with a simple reproducer (shmem_memreg_err.c) and a sample batch file (edison.slurm):

[shmem_memreg_err.zip](https://github.com/ofiwg/libfabric/files/790339/shmem_memreg_err.zip)

**Comment by agrippa** [comment]
@hppritcha @sungeunchoi

**Comment by hppritcha** [comment]
Its possible this is may be fixed by
https://github.com/ofi-cray/libfabric-cray/pull/1195.

**Comment by sungeunchoi** [comment]
@jswaro Is looking at this.

**Comment by jswaro** [comment]
@agrippa  Is this still an issue?

**Comment by hppritcha** [comment]
closing.  we can reopen if the problem resurfaces.
