### ISSUE TITLE
prov/sockets fi_fetch_atomicv fails with invalid parameter dst_len != src_len (sock_atomic.c line 219)

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#2740]
When sending a multiple source iov on the fi_fetch_atomicv API, an invalid parameter error is returned from the function sock_ep_tx_atomic() in sock_atomic.c at line 219, when it is comparing the source buffer length against the destination buffer length.

The log error message, that is displayed, with logging set to warn is:
  libfabric:sockets:ep_data:sock_ep_tx_atomic():219<warn> Buffer length mismatch

In the sock_ep_atomic_readwritev() function it sets up the fi_rma_ioc structure with a rma_iov.count value of 1.  This rma_iov.count value should be initialized to count.

When sending a multiple source iov on the fi_atomicv API, this error does not occur.

**Comment by shefty** [comment]
Can you see if PR #2743 fixes the problem for you?  Based on looking at the code, it looks like the iov handling was off in a few places, and the fix for sock_ep_atomic_readwritev() specifically looked more involved.

**Comment by tonyzinger** [comment]
With the proposed fixed, my test case successfully executes using the fi_atomic, fi_atomicv, fi_atomicmsg, fi_fetch_atomic, fi_fetch_atomicv, fi_fetch_atomicmsg, fi_compare_atomic, fi_compare_atomicv and fi_compare_atomicmsg APIS.
