### ISSUE TITLE
prov/psm2: With FI_THREAD_FID, polling while posting an FI_MULTI_RECV causes heap corruption

### ISSUE THREAD

**Issue by epaulson10** [ofiwg/libfabric#2741]
This issue is cropping up in GASNet while running its multithreaded tests. GASNet has an FI_MSG and an FI_RMA endpoint. There are two CQs, one for outgoing operation completion (both RMA and messages) and one for incoming messages. The implementation is using FI_MULTI_RECV for incoming messages and is using FI_THREAD_FID with individual locks around most of the objects.

What I see is heap corruption occurring sporadically when reposting the multi-recv buffer while running multithreaded applications. In theory (and if my reading of FI_THREAD_FID is correct), then all that should be required is a lock protecting fi_recvmsg() operations on the same endpoint. What I find though is that to get this crash to go away, I need to also lock both the CQs before calling fi_recvmsg, including the one that is only concerned with transmit operations.

I poked around in the psm2 provider code and I think it is possible for psm2_mq_irecv2() to be called concurrently in this situation, which could be the problem. While fi_recvmsg() (which calls psm2_mq_irecv2()) is being called to repost the buffer, an event could be read on another thread (as a result of polling a CQ) that will cause psm2_mq_irecv2() to be called. This is just a guess though and at this time I have no data to back that guess up.

**Comment by j-xiong** [comment]
@epaulson10 I have some questions: (1) do you use multiple multi-recv buffers? (2) if yes, do you have any assumption on the order the multi-recv buffers being used for each message?

**Comment by epaulson10** [comment]
Yes, multiple multi-recv buffers are being used. But no, there is no assumption on order.

**Comment by shefty** [comment]
This is over 3 years old and has either been fixed, or will probably never be fixed at this point.
