### ISSUE TITLE
what should fi_cq_readfrom() return?

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#275]
> the app must learn the address through some other means (e.g. carried in the message) and insert that address into the AV. Cq_readfrom is an optional call that not all providers may support (other than to return ADDR_NOTAVAIL). 

This is about how to get data from cq_readfrom.  I understand not all providers may support it, but if a provider does support FI_SOURCE and fi_cq_readfrom, then the app ought to have a way to learn the address of the source of a message (and be able to send a reply) without the sender having to explicitly include its address in the message.

So, if we don't want fi_cq_readfrom() to do an implicit fi_av_insert, which is fair, then I think it needs to be redefined to return a void *addr and size_t addrlen.  The app can then call fi_av_insert on this address in its own time if desired, or even break it apart itself since the addr_format is specified by the fabric info.

**Comment by shefty** [comment]
Replacing with #1399
