### ISSUE TITLE
Providers: Support domain query_atomic operation

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2755]
See fi_atomic_query() definition.

- [ ] bgq
- [ ] gni
- [ ] mlx
- [ ] psm
- [ ] psm2
- [ ] rxd
- [ ] rxm
- [x] sockets
- [x] udp
- [ ] usnic
- [x] verbs

**Comment by a-ilango** [comment]
Need a clarification.
From fi_query_atomic manpage:
>The query operation reports which atomic operations are supported by the domain, for suitably configured endpoints.

Atomic ops are defined per endpoint but the fi_query_atomic function makes it look like it's per domain. In case of verbs/RDM atomic ops are not supported. So query_atomic can't return valid info without knowing the endpoint type.

**Comment by shefty** [comment]
It's highly unlikely that the atomic attributes will change per endpoint.  I.e. ep1 supports one set of atomics (e.g. atomic add only), while ep2 supports a different set (e.g. atomic compare-swap only).  Moving the query to the domain avoids the potential issue an app might face trying to use atomics.  Any EP configured for atomics will support the same set of operations.

The query_atomic is not saying that all EPs will support atomics.  It says that any EP which does will have (at least) the functionality reported by fi_query_atomic.
