### ISSUE TITLE
Providers: Update support for mr_mode domain attribute

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2757]
See new definition of domain_attr::mr_mode.  Mr. Basic and Mr. Scalable were replaced with MR mode bits.

Providers:
- [ ] bgq
- [ ] gni
- [ ] mlx
- [ ] psm
- [ ] psm2
- [ ] rxd
- [x] rxm
- [ ] sockets
- [ ] udp
- [x] usnic
- [x] verbs

Util:
- [x] util_mr.c

Edit: Added checkbox for util_mr. Added it here to keep related updates together instead of opening a new issue.

**Comment by a-ilango** [comment]
@shefty I've updated the comment. I hope that's okay.
