### ISSUE TITLE
automate generation of provider matrix

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#2759]
Per item on the mail list
http://lists.openfabrics.org/pipermail/ofiwg/2017-February/001354.html
it would be nice to have an automated way to generate the provider matrix.

**Comment by hppritcha** [comment]
@jsquyres just so you know I opened an issue so we don't forget.

**Comment by shefty** [comment]
After 3 years, it's safe to say there's no desire to invest resources into this.
