### ISSUE TITLE
Disqualify providers at runtime

### ISSUE THREAD

**Issue by rhc54** [ofiwg/libfabric#2760]
I've been searching the documentation, but I'm not finding an answer to this question. There is a provider that has a bug in it that causes it to "hang" for 15 seconds on a call to getinfo when hardware is not present on the machine. I've spoken to that provider and they are going to fix the problem.

Meantime, it renders libfabric essentially unusable for me, even though other providers are available and can work. Is there a way I can tell libfabric to exclude certain providers at runtime?

**Comment by shefty** [comment]
You can set the FI_PROVIDER environment variable to enable/disable providers.  I *think* this is documented in the fabric man page, and is something like 'export FI_PROVIDER=^prov_name' will disable that provider.

**Comment by rhc54** [comment]
Aha - I did find it in the ```fi_fabric.3``` man page! Thanks
