### ISSUE TITLE
Documentation: fi_mr optional requested_key

### ISSUE THREAD

**Issue by danghvu** [ofiwg/libfabric#2761]
According to the document https://ofiwg.github.io/libfabric/master/man/fi_mr.3.html

> Optional requested remote key associated with registered buffers.

But It is not clear how to *not giving a key* because it is a part of the arguments for `fi_mr_reg`. If a key is reused there will be an error (I only tested psm2). This leads to my application must keep track of registered keys -- is there a way to avoid this ?

**Comment by shefty** [comment]
The selection of a key is dependent on whether the MR mode was set to BASIC or SCALABLE.  The MR mode will be updated in the next release to indicate this more explicitly, but most of the providers have not been updated for this yet.

If the app really doesn't care what key it gets, I would suggest just using a counter and bump it with each registration call.  With 64-bit keys, you won't ever cycle.

**Comment by danghvu** [comment]
> If the app really doesn't care what key it gets, I would suggest just using a counter and bump it with each registration call. With 64-bit keys, you won't ever cycle.

This is essentially what I am doing. But it has some drawback -- especially if doing registration from different thread -- this costs a cache miss (maybe can get away with a counter per thread.. but again not nice)
