### ISSUE TITLE
Support for using multiple API versions in a single program

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2764]
It seems like it would be possible for end-users to (unknowingly) use multiple API versions in a single program.  One possible problem with this are the static dispatch tables used in many (all?) providers.  Maybe there are other problems?

**Comment by shefty** [comment]
This should be supported by libfabric starting with the 1.5 release.  Prior to 1.5, I don't think different versions actually mattered any.  With 1.5, the api version will be associated with the fabric object, allowing for version checks throughout the API calls.

Obviously work is still needed underneath by the providers to check the version, but support is there from an API perspective.

**Comment by sungeunchoi** [comment]
Yes, this was about the "underneath" part.  Can we leverage common code for things like the dispatch tables.  Maybe other things.

**Comment by shefty** [comment]
It's my intent to leverage common code as much as possible.  Before releasing 1.5 we will at least test it against apps compiled against older versions of libfabric, to make sure that nothing breaks.  This isn't the same as supporting multiple versions from a single app, but will hopefully give us a reasonable assurance that the latter will work.

**Comment by shefty** [comment]
I believe #2772 addressed this issue.
