### ISSUE TITLE
Add api_version to struct fid_fabric?

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2772]
Does it make sense to have the API version be part of `struct fid_fabric`?  I see that the utility provider already has an api_version field in their fabric struct, but it seems like most of the providers will need this.  This is sort of related to #2764.

**Comment by shefty** [comment]
This seems like a really good idea.  Is there any downside to this?

**Comment by jsquyres** [comment]
Should it be part of `fid_fabric` or `fi_ops_fabric`?

**Comment by shefty** [comment]
I updated my PR to move api_version to fid_fabric, but spoke with @a-ilango about it.  These are the choices: place in util_fabric, fid_fabric, or fid.  The benefit of util_fabric is that it keeps it out of the external structures.  As the field is primarily for use by providers, this makes more sense.  The drawback is that not all providers will use util_fabric.  fid_fabric can be used by all providers and the apps, but it somewhat pollutes the exported API.  In struct fid, we can avoid de-references back to the fabric.  This results in increasing all fabric objects by a few bytes, and also pollutes the exported structures.  It can make the provider's life simpler.

So... now I'm not sure which way to go.  The API purist would say put this inside util_fabric.  Is this anything the app would ever need to look at?  It's not too unlike the fclass fid field, which is primarily for the providers, so adding it to fid_fabric doesn't seem that bad.  Input anyone?

**Comment by a-ilango** [comment]
From a provider maintainer's perspective, api_version being in util_fabric or in fabric_fid is almost the same in terms of work required to access it. So either choice is fine.

**Comment by sungeunchoi** [comment]
So just to be clear, leaving it in util_fabric implies that any other provider that needs an api_version field will have to add a similar field somewhere in their structures.  I can imagine a provider that doesn't ever need the field if they only plan to support the latest (or a particular) version, and so having it in fid_fabric would not benefit them.

At least from the gni provider's perspective, having it in fid is actually the most convenient and efficient, for the reason Sean stated above (dereferencing back to fabric).

From the client's perspective, I could see wanting to know the API version dynamically to support different versions from a single code base.  The client could maintain the version info, but having support from libfabric would be nicer.  For example, a new function fi_api_version(struct fid), where object could be fabric, domain, ep, cq.  This would make it convenient to put it in fid.

**Comment by shefty** [comment]
Adding an fi_api_version() call is interesting.  Depending on the implementation, it gives us full flexibility in the choice here.

The big advantage to fid_fabric or util_fabric is that it's a one line change to set the version.  fid_fabric just gets it for all providers.  The big disadvantage to fid is that all providers must be updated to set the version every time any fid is allocated.  This is why I'm leaning to a xxx_fabric option.

As soon as I consider moving it into fid, my brain jumps to why not just extend the fid with 8 or 16 bytes of provider specific data, and let the provider decide if it wants to store the api_version there or not...  To which my brain replies, no, that's a dumb idea, embed the structure.

**Comment by jswaro** [comment]
I prefer the fid_fabric approach since the api version is determined at the time the fabric is initialized via fi_fabric. The api version is inherited by objects created using that fabric (domain, etc...) and all sub-objects under those objects. If providers want to embed the information into their own structure for the purpose of ease, there is nothing to stop that in the fid_fabric approach. 

fi_api_version only really seems to apply at the top-level (fid_fabric) as well, but could apply if the fid approach was chosen. 

As a thought experiment, do we anticipate that applications will request specific and distinct versions within the same execution? IE. I want fabric v1.4 and a fabric v1.5 for the same provider.

**Comment by sungeunchoi** [comment]
If an application uses 2 or more libraries that independently use libfabric, I think requesting 2 different versions of the same provider is a very distinct possibility.

**Comment by shefty** [comment]
The api_version field was added to fid_fabric.  The value is set/checked by the framework based on the provider's fi_version.
