### ISSUE TITLE
possible bug in fi_accept/fi_reject

### ISSUE THREAD

**Issue by biddisco** [ofiwg/libfabric#2774]
I have a scenario that manifests itself as follows
node A calls fi_connect to node B - and simultaneously 
node B calls fi_connect to node A
on node A an atomic flag has been set that tells me a connection has been initiated to B, and similarly on B a flag is set that tells me a connection has been initiated to A.
Both A and B receive FI_CONNREQ events and a decision is made that whichever of A or B has the lowest IP address will accept the connection, the other will reject. In this scenario
A rejects the connection from B
B accepts the connection from A
A receives an FI_CONNECTED event, but B does not.

My solution (for now) is that B accepts the connection from A, and A just ignores the request from B, which seems to work, then both A and B receive FI_CONNECTED, but it feels like an unmatched event is left 'dangling'.

**Comment by shefty** [comment]
What provider does this occur on?

**Comment by biddisco** [comment]
That is with the verbs provider.

**Comment by shefty** [comment]
This is an old issue that was either resolved (most likely), or hasn't manifested as a problem to other applications.
