### ISSUE TITLE
selective completion and error events

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2775]
When the application is using selective completion, the operation itself may generate an error event, but not a successful event. Therefore, it is not clear if the provider should reserve space in the completion queue for ops with selective completion or not. If it does reserve space, then it doesn't know when to release the space (if op is successful there is no event).

In this case, there may be very little a provider might be able to do, even though the application has set FI_RM_ENABLED. Of course, one work around is for the provider to always generate events ... but that is not preferred due to performance impacts.

It might be useful to document in the sections around selective completion that in case of many errors, the application might be in hot water.

Thoughts?

**Comment by shefty** [comment]
I will provide an update to the man pages for discussion.  I think this is a situation that the app must be prepared to deal with.

**Comment by shefty** [comment]
See #2783
