### ISSUE TITLE
prov/bgq: sets fi_version using defines

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2776]
fi_bgq_init.c sets .fi_version using the defines from the fabric.h header file.  It should instead hard-code the actual value that it is written to.  E.g. FI_VERSION(1, 4) or FI_VERSION(1, 5).  This way if the version is updated in the header file, the provider doesn't incorrectly report that it supports those updates.

**Comment by pkcoff** [comment]
Fixed via https://github.com/ofiwg/libfabric/pull/2780 and merged.
