### ISSUE TITLE
prov/sockets fi_cntr_wait returns immediately when timeout value that is greater than zero

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#2789]
When using the fi_cntr_wait() API with a timeout value that is greater than zero, it returns immediately.

This problem is encountered with using a progress mode of FI_PROGRESS_AUTO and a timeout value that is greater than zero.

The error is in the function fi_wait_cond() in the file src/unix/osd.c.  This function does not add in the timeout value (timeout_ms) passed into this function to the microsecond value used in the pthread_cond_timedwait() call.

**Comment by shefty** [comment]
See PR #2792.  This adds the timeout to the wait time.  Thanks for the report.
