### ISSUE TITLE
FI_WAIT_NONE is value 0?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2799]
The SHMEM guys ran into this recently. From the man page:

> FI_WAIT_NONE
> Used to indicate that the user will not block (wait) for events on the counter.

Does this indicate that if the app called a wait call, then it can get back -FI_EINVAL? If so, a default value of 0 is going to disable an API call?

I'm wondering if FI_WAIT_UNSPEC should be value 0?

**Comment by shefty** [comment]
We can change the values at this point, or we break all apps.  The default of 0 means that the counter/cq are optimized for polling, and the app must opt into the additional overhead of allocating wait objects.

**Comment by sayantansur** [comment]
Breaking apps is probably not worth it for this change. It was just a bit surprising to me.

**Comment by jswaro** [comment]
For what is is worth, perhaps the documentation should be amended to indicate that FI_WAIT_NONE is the default (0).

**Comment by shefty** [comment]
Yes - good idea
