### ISSUE TITLE
mr_mode bits complication for API 1.5

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#2804]
In the GNI provider, we've been discussing how this would work in the pre 1.5 timeframe. Applications developed as ISVs against an older version of libfabric but linked to a newer version might check the fi_info structure to know what memory model is in use. If provided unspec, in the pre-1.5 timeframe, we should return unspec, basic or scalable, and not the mode bits because of the following case:

As an application designer, I may not specify a memory model and I get a selection of providers to choose from after calling fi_getinfo. I pick a provider out of the selection, and the default model for that provider is scalable. However, without using the old bits, I see that I've been returned some value other than FI_MR_SCALABLE and not FI_MR_BASIC either. As an older application, designed to check the memory model of the provider and adjusts the behavior based on that expectation, it will be confused.

I think that fi_getinfo calls should be returning the old enumerations, not newer bits if the API version requested is pre 1.5, so that it matches the expectation of older applications. 
@shefty @chuckfossen @sungeunchoi Let's discuss?

**Comment by shefty** [comment]
> I think that fi_getinfo calls should be returning the old enumerations,
> not newer bits if the API version requested is pre 1.5, so that it
> matches the expectation of older applications.

I believe this is a hard requirement to ensure ABI compatibility.

See https://github.com/ofiwg/libfabric/commit/47bee5aadf77e876536adf48fd151d104acad60b for a start on how to handle this.  My goal is for the providers to update as needed, with the framework handling most of the translation.

**Comment by bturrubiates** [comment]
> See 47bee5a for a start on how to handle this.  My goal is for the providers to update as needed, with the framework handling most of the translation.

The `ofi_check_mr_mode` function can be used at `fi_getinfo` time, but what if the provider wants to check the given `mr_mode` in `fi_domain`? There is no `version` field available in `fi_domain`. 

Should providers just assume that the `mr_mode` field is set to something valid?

**Comment by shefty** [comment]
A domain is attached to a fabric, and the fabric is opened to a specific API version.

**Comment by jswaro** [comment]
Has there been any additional discussion on this issue. Has 47bee5a been commited?.

**Comment by a-ilango** [comment]
@jswaro https://github.com/ofiwg/libfabric/commit/47bee5aadf77e876536adf48fd151d104acad60b has been committed. If a provider uses ofi_alter_info as part of its getinfo call, the translation would be handled by it otherwise the provider would have to translate the new mr_mode bits to old enumerations.

**Comment by jswaro** [comment]
I don't think its really wise to be altering the hints. hints are the application's perspective into the library, to which providers return a separate info detailing what they can or will provide. 

As an application designer, if I pass in FI_VERSION(1,0) and mr_mode = FI_MR_BASIC, I'd expect the info structure returned by the provider to give me 'FI_MR_BASIC'. This is especially true for applications compiled against a much older version of libfabric, but uses newer libfabric libraries as the system gets updated.

**Comment by jswaro** [comment]
I also think that it is fair to say, if an application requests FI_VERSION(1,4) or older, that they don't need to understand the new MR mode bits. The MR mode bits were a change to libfabric versions 1.5 and greater.

**Comment by a-ilango** [comment]
ofi_alter_info doesn't modify the hints. It only modifies the fi_info returned to the user. An app that requests  version 1.4 or older would get the old enumerations. This patch adds the required mr_mode translation.

**Comment by jswaro** [comment]
> ofi_alter_info doesn't modify the hints.

I misread that. Thanks for the clarification.

**Comment by shefty** [comment]
I believe the original issue has been addressed:
```
I think that fi_getinfo calls should be returning the old enumerations, not newer bits if the API version requested is pre 1.5, so that it matches the expectation of older applications.
```
The API adheres to this behavior.
