### ISSUE TITLE
Incorrect return type (or documentation error) from fi_read?

### ISSUE THREAD

**Issue by biddisco** [ofiwg/libfabric#2807]
I am making a call to fi_read(args...) and I receive the return from the call of zero - indicating success.
The docs state "Returns 0 on success. On error, a negative value corresponding to fabric errno is returned. Fabric errno values are defined in rdma/fi_errno.h."

The signature of fi_read (+friends) is different from other fi_xxx calls because it returns a size_t rather than just an int, so perhaps the documentation is in error here and actually, the return type should be different.

When I call fi_read with logging enabled, I can see in the trace between my call to fi_read and my printf of the return type of fi_read, that there is an error
`libfabric:gni:ep_data:_gnix_rma_post_req():1278<warn> [28831:12] GNI_Post*() failed: GNI_RC_INVALID_PARAM`

This almost certainly means that fi_read should be returning an error code instead of zero.

(As a bonus feature, it'd be great if it was possible to know which param was wrong)

```
750: <debug> 0x00002aaad4024f20 0x2aaad2c02700 RDMA Get fi_read : chunk 1  client 0x00002aaab5c8b800  fi_addr 0x005ac00200002200  local addr 0x00002aaac2c2e540  local desc 0x00002aaab5c3acb0  size 0x100000  rkey 0x00003362aaaceb2c  remote cpos 0x00002aaac2c2e540  remote pos 0x00002aaac2c2e540  index 46912900359488
libfabric:gni:eq:gnix_wait_wait():440<trace> [28831:6]
    [snip lots of almost identical <trace> messages]
libfabric:gni:eq:gnix_wait_wait():440<trace> [28831:13]
libfabric:gnignix_wait_wait():440<trace> [1452:8]
    [snip lots of almost identical <trace> messages]
libfabric:gni:ep_ctrl:_gnix_vc_ep_get_vc():2089<trace> [28831:12]
libfabric:gni:eq:gnix_wait_wait():440<trace> [28831:8]
    [snip lots of almost identical <trace> messages]
libfabric:gni:ep_ctrl:__gnix_vc_get_vc_by_fi_addr():218<trace> [28831:12]
    [snip lots of almost identical <trace> messages]
libfabric:gni:ep_data:_gnix_rma_post_req():1278<warn> [28831:12] GNI_Post*() failed: GNI_RC_INVALID_PARAM
    [snip lots of almost identical <trace> messages]
libfabric:gni:ep_ctrl:__gnix_nic_next_pending_vc():1987<e> [1452:8]
    [snip lots of almost identical <trace> messages]
libfabric:gniinfo> [28831:9] Dequeued progress VC (0x2aaab5df0350)
libfabric:gni:eq:gnix_wait_wait():440<trace> [28831:13]
libfabric:gni:eq:gnix_wait_wait():440<trace> [28831:6]
751: <debug> 0x00002aaad4024f20 0x2aaad2c02700 fi_read completed ok
```

**Comment by shefty** [comment]
fi_read and all data transfer calls return 0 for success, negative value on error.  The use of size_t is intentional for future extensibility.  E.g. to support endpoint types that behave more like sockets with synchronous transfer capabilities.

**Comment by shefty** [comment]
Assigning @sungeunchoi for the gni issues.  She can re-assign as desired.  :)

**Comment by sungeunchoi** [comment]
@biddisco Can you check that your caps include the operations you are issuing?  I found an problem where I did not specify FI_REMOTE_WRITE on the remote side and and fi_write operation exhibited the same behavior you described (https://github.com/ofi-cray/libfabric-cray/issues/1304).

**Comment by biddisco** [comment]
I'm not sure if I can recreate the particular bug I had because it turns out I was using a wrong parameter in my call and once I fixed that - all was fine. The main problem was the error code indicating success instead of fail. I cannot recall if I used the REMOTE_WRITE/READ flags at the time I had that problem, but I was certainly asking for FI_RMA in the caps.
The current code set the flags as follows
```
fabric_hints_->caps = FI_MSG | FI_RMA | FI_SOURCE | FI_WRITE | FI_READ | FI_REMOTE_READ | FI_REMOTE_WRITE | FI_RMA_EVENT;
```
So I did _probably_ have the flag set when this bug was happening

**Comment by sungeunchoi** [comment]
@shefty The man pages and the code say the return type for fi_cntr_read and fi_cntr_readerr are unsigned, so there is no way to return an error.

@biddisco We've been having some internal discussions, and we are thinking that perhaps the recommended way to use counters would be to call fi_cntr_readerr if you are missing events.

**Comment by shefty** [comment]
fi_cntr_read/fi_cntr_readerr just return the current value of the counters.

**Comment by sungeunchoi** [comment]
@shefty @biddisco Mixing my messages..  ignore my last comment.
