### ISSUE TITLE
fi_endpoint not verifying inputs

### ISSUE THREAD

**Issue by godfreja** [ofiwg/libfabric#2826]
fi_endpoint will segfault if given NULLs for all parameters. While NULLs are obviously not valid, it would be nice if libfabric could do some basic validations of inputs, at least for debug builds.

**Comment by shefty** [comment]
3 year old enhancement request.  Dropping.  There are some checks, but full validation checks for coding errors are unlikely to become a priority.  At best, the checks would be asserts, which would result in a segfault anyway.
