### ISSUE TITLE
fi_getinfo() - node,service,FI_SOURCE vs. fi_info::src_address

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#284]
The "source" address for a getinfo can be specified in two different ways, either through the "src_addr" of the hints, or via args node/service if FI_SOURCE is set.  

which takes precedence if both are specified?  seems odd to have two alternate ways to express (ultimately) the same info.  I'd like to at least have the man page document the precedence.

**Comment by ajinpradeep774** [comment]
I have a doubt. Is it possible to specify a client source port in libfabric? I want all inbound and outbound traffic from the client to be routed through the designated port. I have tried the code below, but it doesn't work.
```
auto _hint = fi_allocinfo();
std::shared_ptr<fi_info> hint(_hint, std::bind(&fi_freeinfo, std::placeholders::_1));
hint->ep_attr->type = FI_EP_MSG;
hint->caps = FI_MSG;
hint->domain_attr->mr_mode = FI_MR_BASIC;
hint->mode = FI_LOCAL_MR;

// Define source (client) address
struct sockaddr_in *src_addr = new sockaddr_in{};
memset(src_addr, 0, sizeof(src_addr));
src_addr->sin_family = AF_INET;
src_addr->sin_addr.s_addr = htonl(INADDR_ANY);
src_addr->sin_port = htons(8899); // Source port

// Assign addresses to hints
hint->src_addr = src_addr;
hint->src_addrlen = sizeof(sockaddr_in);
hint->addr_format = FI_SOCKADDR_IN;

int ret = fi_getinfo(OFI_VERSION, address.c_str(), input.c_str(), 0, hint.get(), &_info);
if (ret) {
    std::cout << "connect():fi_getinfo failed" << std::endl;
    return nullptr;
}
```

**Comment by shefty** [comment]
Yes, you should be able to set the source port (and address) that gets associated with an endpoint.  Fabtests support this through the -B option.  ft_read_addr_opts() in fabtests/common/shared.c might help, but the flow should be similar to what's above.
