### ISSUE TITLE
prov/psm2: Wrong reported fabric capabilities / domain attributes

### ISSUE THREAD

**Issue by pjgeorg** [ofiwg/libfabric#2847]
The psm2 provider does allow to open several domains and endpoints, however the reported fabric capabilities and domain attributes are wrong.
This is simply due to the fact that there is actually only one domain and one endpoint.

For the second domain to be opened the desired domain attributes in supplied info are not checked at all. Hence the domain is always configured with the desired domain attributes of the first one to open a domain. For any following the info is not even corrected to reflect the actual attributes.
(Easiest check is to open two domains, one with FI_MR_BASIC and one with FI_MR_SCALABLE. Both will report a different FI_MR mode, however the actual FI_MR mode is that of the first one.)

Opening a second endpoint the caps are at least compared against the actual available caps, however this does not seem to be a good solution as it is not clear to the user what went wrong. Afterall the provider has been reported to suit all requirements.

Proposed solution:
getinfo() should already check for opened domains/endpoints and set all caps accordingly. However in this case checks within open domain and open endpoint are still required to prevent errors due to outdated info.

Suggested enhancement:
Currently caps not request by the first initiator are not available to any follow up. E.g. OpenMPI currently does not request FI_RMA, hence an application using MPI + libfabric directly can not take advantate of any RMA capabilites. I suggest to change this behavior to allow subsequent domains to extend supported caps.

Without fixing this issues there is currently no reliable way to use MPI (using libfabric) + libfabric in any application without first checking the exact caps and modes set by a particular MPI implementation.

**Comment by shefty** [comment]
Tagging @j-xiong to take a look at this.
