### ISSUE TITLE
fid_ep vs fid_pep

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#285]
There's this undocumented/uncommented assumption that the first part of fid_pep looks exactly like fid_ep (used by fi_cancel/getopt/setopt).  The sharing of the fi_ops_ep and fi_ops_cm structure between these results in some weird looking ops structures, where the routines take different types of base objects.

I propose these changes that both fid_ep and fid_pep should start with the structure fid_base_ep:
```C
struct fid_base_ep {
    struct fid fid;
    struct fid_ops_base_ep *ops;
    struct fid_ops_base_cm *cm;
};

struct fid_ep {
    struct fid_base_ep  base;
    struct fid_ops_ep *ops;
    struct fid_ops_ep_cm *cm;
    ...
};

struct fid_pep {
    struct fid_base_ep  base;
    struct fid_ops_pep_cm *cm;
    ...
};
```
EP routines that are common to fid_ep and fid_pep go into fid_ops_base_ep:  cancel/getopt/setopt
fid_ops_ep then only has enable,tx_ctx,rx_ctx

CM routines in fid_ops_base_cm is maybe just getname
fid_ops_ep_cm has: getpeer, connect, accept, shutdown, join, leave
fid_ops_pep_cm has: listen and reject

The common routines could take either "fid_t" or "struct fid_base_ep" as argument.

If the objection to this is that it increases the size of fid_ep by 16 bytes (which it does :( ), then i still think there are similar ways with the same memory footprint to get away from this implicit cross-casting (just by making it explicit)

**Comment by shefty** [comment]
There are now 4 structures that all want to derive from some base ep type of structure - endpoint, passive ep, shared transmit context, and scalable ep.  I haven't been able to come up with any better solution than just defining the structures so that they can be cast.  Unless we can come up with a reasonable alternative, I motion to close this.
