### ISSUE TITLE
Support process-scoped memory registration

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#286]
Low priority request, but this would improve the mapping of ES-API onto libfabric, since registration handles created by exs_mregister() are defined to be process-scoped.  I assume this capability would also be useful for MPI, etc.

Sean mentioned that this would most likely require all providers to support user-selectable memory keys, which I would be fine with (we would just fall back to per-device registrations if the process-scope memory registration failed).

**Comment by shefty** [comment]
In the ideal world, you would need to call fi_reg_mr once per domain, but would only have a single *remote* registration key to deal with.  There would be no need to register memory for local use.  You would need to track each local registration.

Of course, this requires that the providers support all of these options, but at least from the API perspective, the support is there.

**Comment by shefty** [comment]
I believe that the current interfaces support this feature, depending on the provider implementation.
