### ISSUE TITLE
utils/util_buf: incorrect data value?

### ISSUE THREAD

**Issue by hoopoepg** [ofiwg/libfabric#2863]
at https://github.com/ofiwg/libfabric/blob/master/include/fi_mem.h#L168 there is union definition:
```
union util_buf {
	struct slist_entry entry;
	uint8_t data[0];
};
```
is this union correct? access to union values by ```data``` may destroy entry & break object.
shouldn't data points to space 'after' entry?

BTW, I couldn't find any reference to data value in libfabric...

**Comment by shefty** [comment]
> union util_buf {
> 	struct slist_entry entry;
> 	uint8_t data[0];
> };
> 
> 
> is this union correct? access to union values by data may destroy entry
> & break object.
> shouldn't data points to space 'after' entry?

This is correct.  When the buffer is stored in the free pool, the entry field will be accessed.  Once the user allocates the buffer from the free pool, it only deals with the data portion.  The union simply guarantees that the buffer is at least a minimum size.

**Comment by hoopoepg** [comment]
got it.
thank you
