### ISSUE TITLE
ofi_alter_info provides a default where one did not exist before

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#2865]
See https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_attr.c#L750.

I think this is incorrect. If a provider uses ofi_alter_info, it changes the value from FI_MR_UNSPEC to FI_MR_SCALABLE. This wasn't the intent of application designers when they chose FI_MR_UNSPEC. 
FI_MR_UNSPEC generally means to say that an application designer is not concerned with the chosen memory registration model of a provider and it will take what memory registration model that the provider will give by default. This line of code changes that behavior.

This is detrimental if a provider doesn't support FI_MR_SCALABLE prior to 1.4. 

The answer to this might be "don't use ofi_alter_info then"... but I thought the purpose of utility provider code was to eliminate copy-paste between providers when there was a good rationale for common code.

@shefty @a-ilango

**Comment by a-ilango** [comment]
Hmm, I'm not sure if I understand your issue. The line in question translates the provider mr_mode bits (1.5) to enumerations understood by a pre-1.5 app. To clarify, the attr variable is from the provider, not the app.

**Comment by jswaro** [comment]
> To clarify, the attr variable is from the provider, not the app.

I understand that.

> The line in question translates the provider mr_mode bits (1.5) to enumerations understood by a pre-1.5 app.

The behavior is not what was true in pre.1.5 libraries. If an application provided FI_MR_UNSPEC, that did not imply that it would get FI_MR_SCALABLE, especially if the provider did not support scalable. 
If I recall correctly, FI_MR_SCALABLE wasn't the default mode for libfabric proper if FI_MR_UNSPEC was given. (If I'm wrong, please point it out in the documentation where this is true in the older documentation)  

The language of the 1.4x man page for fi_domain says the following.

> FI_MR_UNSPEC : Any memory registration mode is requested and supported.

but ... that's not what we get out of that line of code that I pointed out above. What we get, is a default that may not be supported by the provider. 

Specifically, GNI provider does not support FI_MR_SCALABLE prior to 1.5. Other providers may not have supported FI_MR_SCALABLE in older releases either.

**Comment by shefty** [comment]
Apps that set mr_mode = FI_MR_UNSPEC prior to 1.5 indicate that the provider can return either FI_MR_BASIC or FI_MR_SCALABLE.  The call is attempting to interpret what the provider does support and return the appropriate value.  The provider's mr_mode value must have been updated to the 1.5 release.  IOW, if the provider mr_mode = 0, then it is the same as FI_MR_SCALABLE.  If any mr_mode bit is set, the best mapping is to FI_MR_BASIC.  If mr_mode bits are set that fall outside what FI_MR_BASIC allows, then no mapping is actually possible.

**Comment by jswaro** [comment]
> The call is attempting to interpret what the provider does support and return the appropriate value.

There is no check against the provider to determine if scalable is supported. It is a simply conversion from FI_MR_UNSPEC to FI_MR_SCALABLE.

**Comment by jswaro** [comment]
This statement:
> attr->mr_mode = attr->mr_mode ? FI_MR_BASIC : FI_MR_SCALABLE;

If attr->mr_mode is...

FI_MR_UNSPEC(0), then attr->mr_mode is now FI_MR_SCALABLE(2).
FI_MR_BASIC(1), then attr->mr_mode is now FI_MR_BASIC(1).
FI_MR_SCALABLE(2), then attr->mr_mode is now FI_MR_BASIC(1). 



It seems to me that it should be more reasonable to throw an error if mr_mode is something other than FI_MR_UNSPEC, FI_MR_BASIC, or FI_MR_SCALABLE, instead of dictating the mode here. Again, this is code that applies to applications requesting less than FI_VERSION 1.5.

**Comment by shefty** [comment]
The mr_mode is assumed to be version 1.5 on entry to the function.  It should not be set to either MR_BASIC or MR_SCALABLE on entry.  The provider should be using the 1.5 definition for mr_mode and set the individual bits that are needed.  The call is backporting the bits to either BASIC or SCALABLE if the app cannot interpret version 1.5.  The goal of the change is that providers only need to deal with the 1.5 defines, with the framework handling the conversion.

**Comment by shefty** [comment]
Are we settled on this issue?

**Comment by bturrubiates** [comment]
> Are we settled on this issue?

So, to clarify: in pre 1.5 `FI_MR_UNSPEC` is a value that can be passed in indicating support for any registration mode, but in 1.5 and above there is no unspec value. If it's passed in for 1.5 or greater then it implies scalable. So for usNIC since we require basic support, we should return `-ENODATA` in the event we get `0`. Is that right?

**Comment by shefty** [comment]
If the app specifies version 1.5, then they are using the new mr_mode values.  So mr_mode = 0 indicates that only 'scalable' is supported by the app.  If the app specifies version <= 1.4, then the previous behavior should be enforced.  I.e. mr_mode = 0 allows reporting either FI_MR_BASIC or FI_MR_SCALABLE (and only those values).

If an app updates to version 1.5 without making the corresponding change to mr_mode settings, then the app is basically lying, and there's no way for us to know that.

**Comment by jswaro** [comment]
For what it's worth, we encountered an issue with this recently with the GNI provider. If you use ofi_alter_info at the end of your call to fi_getinfo, AND you don't support scalable, you should set the returned info structure's domain_attr->mr_mode to FI_MR_BASIC prior to the call to ofi_alter_info, or it will alter your info structure to return scalable even if you don't support it.

This issue was fixed for the GNI provider with #3149 , even if it wasn't as elegant as I'd have liked it to be.

**Comment by shefty** [comment]
What was the mr_mode bits that were set by the gni provider as part of its fi_info requirements?

**Comment by jswaro** [comment]
> What was the mr_mode bits that were set by the gni provider as part of its fi_info requirements?

I don't understand what you are asking. I'm going to guess though. 

When no hints are provided, we return: 
```
    gnix_info->domain_attr->mr_mode = FI_MR_BASIC | OFI_MR_BASIC_MAP;
```

However, if hints are provided, and API version 1.4 or less is requested, and mr_mode is set to FI_MR_UNSPEC (0) ... then the GNI provider should return FI_MR_BASIC. But, without setting it the info structure to be returned to the user, to some value other than FI_MR_UNSPEC, the ofi_alter_info structure will coerce the value to FI_MR_SCALABLE.
