### ISSUE TITLE
ofi_check_mr_attr enforces incompatible restrictions on provider responses

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#2866]
See https://github.com/ofi-cray/libfabric-cray/blob/master/prov/util/src/util_attr.c#L425

There is no provision for allowing a provider to return an MR mode that differed from the hints mr mode. This doesn't really work with FI_MR_MMU_NOTIFY, which is an indicator from a provider, not a request from the application. 

For the GNI provider, we can't possible return FI_MR_MMU_NOTIFY to the application to indicate that they should call fi_mr_refresh if FI_MR_ALLOCATED wasn't provided by the application through the hints structure. 

@shefty @sungeunchoi @hppritcha @chuckfossen

**Comment by shefty** [comment]
The provider cannot set a mode bit that the application did not set in their hints.

If this is what you're wanting, it's disallowed by the API.  If not, then I'm not clear on the issue.  :)

**Comment by jswaro** [comment]
I can't say this makes much sense then. When would an application request a provider that makes them notify the provider? 

> FI_MR_MMU_NOTIFY is typically set by providers  that support  memory registration against memory regions that are not necessarily backed by allocated physical pages at the time the memory registration  occurs.

The language supports what I am saying above. If providers cannot set those bits, then perhaps the wording should be 'FI_MR_MMU_NOTIFY is a mode bit required by providers that...', or something of a similar nature.  

The language makes it sound like we are responsible for informing the application of the requirement for using refresh in the returned info structure.

**Comment by shefty** [comment]
The application isn't saying that it *wants* a provider to give them a mode bit.  It's saying that it knows how to deal with that mode bit if it is set.  The app sets the mode bit.  The provider can either leave it set, or clear it.

If the app leaves a mode bit set to 0, it is indicating that it cannot handle the provider requirements.  So either the provider needs to fail the requests or work around it.  The mr_mode bits behave similar to the fi_info mode bits.

**Comment by jswaro** [comment]
> The provider can either leave it set, or clear it.

The language is confusing... Providers cannot set bits, but they can clear them?

**Comment by shefty** [comment]
> Providers cannot set bits, but they can clear them?

correct

**Comment by jswaro** [comment]
So if providers cannot set bits, how is FI_MR_UNSPEC changed to anything else?

**Comment by shefty** [comment]
FI_MR_UNSPEC (value 0) can be converted into FI_MR_BASIC or FI_MR_SCALABLE, but only if the app is using version 1.4 or earlier.  For the app to use version 1.5, they have to explicitly set which mr_mode bits that they support.  This is part of the conversion from switching from an enum to bit fields.  FI_MR_UNSPEC is no longer supported starting with 1.5.  Or, more specifically, FI_MR_UNSPEC will only map to mr_mode = 0, which is basically scalable MRs.

Basically, apps will need something like the following:
```
if (FI_VERSION_LT(fi_version(), FI_VERSION(1,5))
    mr_mode = FI_MR_UNSPEC;  /* *only* support basic or scalable */
else
    mr_mode = MR_BIT1 | MR_BIT2 | ...;
```
Note that I just added a patch to clarify that an app that uses FI_MR_BASIC specifically requests basic registration mode, even if version 1.5 or later is used.  So, apps that are currently asking for basic will continue to get basic MRs.

**Comment by jswaro** [comment]
I think I'm fine with the revisions. Thanks
