### ISSUE TITLE
Allow fi_mr_bind to support FI_REMOTE_READ

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#2870]
fi_mr_bind only allows binding a counter to count FI_REMOTE_WRITE.

However, fi_ep_bind allows a counter to be bound for FI_REMOTE_WRITE and FI_REMOTE_READ.

Should we allow counting both, or separately read and writes, or only writes?

**Comment by shefty** [comment]
IMO, only counting remote writes makes sense, but what do apps want?  I can envision race conditions trying to make use of counting remote reads.  That would seem to require some sort of 'read done' ack from the initiator to be useful.

**Comment by sayantansur** [comment]
I can see a method to implement a large message broadcast using the remote_read counter. For example, the root sends out a small message when it enters the broadcast. Each of the broadcast tree members then performs a read, and the root looks at the attached counter. When counter reaches the desired threshold, it considers broadcast to be over.

I mean, counting reads could be useful, but is it a big implementation overhead for providers?

**Comment by shefty** [comment]
I doubt it's much more overhead (if any) to support counting reads on a MR, if it's already supported on the EP.  :)  I guess it does allow the provider to handle the read ack, rather than always pushing it to the app.  (And something like shared memory wouldn't need this anyway.)

**Comment by shefty** [comment]
Changing to an enhancement request to add support for FI_REMOTE_READ

**Comment by shefty** [comment]
closing out 4 year old request
