### ISSUE TITLE
prov/sockets: remote counter events delivered even when FI_RMA_EVENT not set

### ISSUE THREAD

**Issue by sungeunchoi** [ofiwg/libfabric#2873]
According to the man page:
```
FI_RMA_EVENT
Requests that an endpoint support the generation of completion events when it is the target of an
RMA and/or atomic operation. This flag requires that FI_REMOTE_READ and/or FI_REMOTE_WRITE
be enabled on the endpoint.
```
Assuming 'completion events' includes remote counter updates, then I would read that as the remote counter event should *not* be delivered unless FI_RMA_EVENT is set.  Currently the sockets provider updates remote counters even if FI_RMA_EVENT is not set.

**Comment by hppritcha** [comment]
Note that for some providers, there would be near catastrophic performance implications if we had to increment remote counters regardless of whether or not FI_RMA_EVENT secondary capability was requested.
