### ISSUE TITLE
Need to revert 3fbeb90056300ca3585439c345f26e1164417c5b

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#2892]
This change allows fi_getinfo to return a core provider without having a specified utility provider layered over it.  E.g. sockets will be returned directly even if the app requests the 'ofi-rxm' utility provider.  The original code was correct, but required that the utility provider only pass the core provider name through to the next fi_getinfo call.

**Comment by jsquyres** [comment]
@shefty Anything else to do on this one?

**Comment by shefty** [comment]
nope - thanks
