### ISSUE TITLE
fi_list.h not installed; unavailable for FABRIC_DIRECT

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#2958]
I'm trying to use the "utility" components, such as `fi_list.h` and `fi_lock.h`, with FABRIC_DIRECT ... only I can't because these files are not installed when I build/install the libfabric library.

Is there a specific reason why these files are not installed? Or is it just an oversight since no "FABRIC_DIRECT providers" have attempted to use this common code before?

Thanks!

@sayantansur @shefty

**Comment by shefty** [comment]
We do not want to maintain internal APIs, so those files are not installed.  There's no guarantee that the interfaces won't change from release to release.  A direct provider needs to include those files directly in their build sources if they want to use them.  This is true for any common/shared/helper routines that the core implements for providers to use.

**Comment by mblockso** [comment]
So if I want to use any of this with FABRIC_DIRECT I have to forward-declare the functions/structs in my fi_direct_foo.h files and then branch to function in my libfabric library that can use these utilities? What about things like `fi_atom.h` and `fi_lock.h` that have funky C preprocessor definitions that make the simple "forward declare" option untenable? 

I don't see how I could possibly use this "common" code without contorting the direct provider and/or risking out-of-line code gen.

Can't we namespace the symbols so that it is clear that applications should not directly use these internal functions and structs? Some way to signal that these are internal APIs and forward/backward compatibility will not be maintained?

**Comment by shefty** [comment]
Can't the provider simply include the necessary files directly into its build?  If the files are needed externally because a fi_direct_foo.h files need them, then the provider should install them along with fi_direct_foo.h.  But the framework should not, and they shouldn't be available outside of a FABRIC_DIRECT build.

This isn't just about applications trying to use them.  If external providers rely on those definitions, then ABI compatibility must be maintained.

**Comment by mblockso** [comment]
Ok ... I didn't realize that having the provider install these files was an option.

Should they be installed under `$(prefix)/include/rdma/<provider>` since they would be specific to the direct provider? Or should they be installed under `$(prefix)/include/rdma` since they are not "provider specific" files (i.e., not located under `$(srcdir)/prov/<provider>/include/rdma` in the git repository)?

**Comment by mblockso** [comment]
Well .. that's not quite right either, because now I have to install all the configury stuff that is referenced in `fi_list.h`, etc. 

hmm....

**Comment by shefty** [comment]
I would go with rdma/provider.  If there are other changes needed to the header files, we can make those.

**Comment by shefty** [comment]
We can separate dlistfd into another header file if that helps.

**Comment by shefty** [comment]
Are there still open issues to resolve here, or can this be closed?

**Comment by mblockso** [comment]
Because of `FI_CONTEXT2` I no longer require `FABRIC_DIRECT` which means I don't need these other headers installed. However, I'll bump into this again when I enable `FABRIC_DIRECT` in the future.

The answer is probably to just not use these headers ... (sigh)

Closing.

**Comment by shefty** [comment]
You can use the headers, and install them if needed.  If the headers need to be split, to isolate functionality, that's doable.
