### ISSUE TITLE
man: binding cq and counter to the same endpoint

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#2959]
The current head of [fi_endpoint(3)](https://ofiwg.github.io/libfabric/master/man/fi_endpoint.3.html) states:

> An endpoint may only be bound to a single CQ or counter for a given type of operation. For example, a EP may not bind to two counters both using FI_WRITE. Furthermore, providers may limit CQ and counter bindings to endpoints of the same endpoint type (DGRAM, MSG, RDM, etc.).

Is the intent here to disallow two CQs/two counters with the same fi_ep_bind flags from being bound to the same endpoint, or is the intent to also disallow CQs/counters that track completions of the same type of operation?

For example, is the following valid behavior:
```
fi_tx_attr::op_flags = 0;               // default - no cq entry
fi_ep_bind(ep, cntr, FI_READ | FI_WRITE);
fi_ep_bind(ep, cq, FI_TRANSMIT | FI_SELECTIVE_COMPLETION);
fi_write(ep, ...);                      // cntr incr, no cq entry
fi_writev(ep, ...);                     // cntr incr, no cq entry
fi_writemsg(ep, ..., FI_COMPLETION);    // cntr incr, cq entry
fi_inject_write(ep, ...);               // cntr incr, no cq entry
```
There is also ambiguity about use of the FI_SELECTIVE_COMPLETION flag. This flag is not listed under the allowable flag section for counters, yet the operation flags section states:

> FI_COMPLETION
> Indicates that a completion entry should be generated for data transfer operations. This flag only applies to operations issued on endpoints that were bound to a **CQ or counter with the FI_SELECTIVE_COMPLETION flag**. See the fi_ep_bind section above for more detail.

**Comment by shefty** [comment]
The intent is that an EP may not direct completions of the same type to two different CQs.  Additionally, an EP may not direct completions of the same type to two different counters.

E.g. the EP may not write receive completions to two CQs.  Nor can it update two counters for a single receive completion.

```
> fi_tx_attr::op_flags = 0;               // default - no cq entry
> fi_ep_bind(ep, cntr, FI_READ | FI_WRITE);
> fi_ep_bind(ep, cq, FI_TRANSMIT | FI_SELECTIVE_COMPLETION);
> fi_write(ep, ...);                      // cntr incr, no cq entry
> fi_writev(ep, ...);                     // cntr incr, no cq entry
> fi_writemsg(ep, ..., FI_COMPLETION);    // cntr incr, cq entry
> fi_inject_write(ep, ...);               // no cntr incr, no cq entry
```
The inject operation will still bump the counter.

I believe the FI_COMPLETION flag should only apply to CQs, not counters.  Let me verify the implementations on this and the inject case.
