### ISSUE TITLE
usnic: Provider does not check EP bind flags for AV

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#2971]
Reported by @thananon, he's binding an AV to an EP using `fi_ep_bind` with the `FI_RECV` flag and it's totally okay for usNIC but the sockets provider is failing with `-FI_EINVAL`. 

The usNIC provider should call into the common core function `ofi_ep_bind_valid`.

**Comment by jsquyres** [comment]
@thananon @bturrubiates When fixing this, be sure to keep ignoring `FI_RECV` if the specified API version is 1.4 or less (because otherwise you'll break existing versions of Open MPI).

**Comment by bturrubiates** [comment]
Closed in #2981
