### ISSUE TITLE
fi_av_insert_with_hint

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#298]
Sometimes, the user app may have information that can be used to complete or speed up AV insertion (or address resolution).  It could obtain this infornation through "other means" (OOB communication, command line, magic, etc.).  There ought to be a way to pass this information to av_insert or variant as some form of hint.

Case in point:  Address resolution for usnic consists of converting a remote host's IP address to a MAC address.  This is typically done with b ythe OS through ARP, but in the base of Open MPI, all participating processes communicate all their interface information (possibly several interfaces) to a central entity, which in turn distributes this information to all other processes without the need for a classical all-to-all on each interface to exchange ARP information.

In libfabric, this could take the form of an opaque "address hint" from fabric or domain which an app can obtain (from fi_getinfo, say?) and pass to other processes OOB, which would in turn pass this opaque hint (if present) to av_insert, possibly greatly speeding up the insertion process.  AV hints would, of course, be specific to a particular fabric and provider.

**Comment by shefty** [comment]
Is this feature still desirable?

**Comment by bturrubiates** [comment]
> Is this feature still desirable?

I believe this is still desirable, @jsquyres wouldn't this be useful for the usNIC BTL?

**Comment by jsquyres** [comment]
Yes, it would be.

**Comment by sayantansur** [comment]
@jsquyres @bturrubiates just curious, could you illustrate how the usNIC BTL would use this? I'm most interested in what the hint is, how it is obtained by a BTL.

**Comment by jsquyres** [comment]
Open MPI can already have the MAC addresses and give them to libfabric.

Sent from my phone. No type good.

On Feb 24, 2016, at 9:47 AM, Sayantan Sur <notifications@github.com<mailto:notifications@github.com>> wrote:


@jsquyres<https://github.com/jsquyres> @bturrubiates<https://github.com/bturrubiates> just curious, could you illustrate how the usNIC BTL would use this? I'm most interested in what the hint is, how it is obtained by a BTL.

-

**Comment by sayantansur** [comment]
Yeah, this seems like it could be useful. Wonder if we should make the type of hint explicit, or have the hint relate to libfabric constructs. What is a MAC address in libfabric? Does it belong in a provider specific address?

Otherwise, there's always the question of - which provider extension should the app use to get a blob that only the provider understands.

**Comment by rfaucett** [comment]
The way I had envisioned this is that a process with an endpoint could make a call that says "generate a hint for this endpoint" and it gets back an opaque blob and a (bounded) length.  It can then pass this blob up to a central repository who could then distribute it to all members of the job to use in inserting their addresses.  This maps shamelessly to the MPI startup pattern.

So, there is only one non-provider-specific call to generate the hint:
```
    uint8_t hint[FI_ADDR_HINT_MAX];
    size = sizeof(hint);
    status = fi_generate_address_hint(endpoint, hint, &size);
```
If a provider does not support hints, return a length of zero.  and fi_av_insert_with_hint() would just map to fi_av_insert().

**Comment by sayantansur** [comment]
I guess I'm wanting to understand why the usNIC address for the endpoint (the one you obtain by fi_getname and send around) cannot contain the MAC address in the first place?

**Comment by rfaucett** [comment]
Oh, it could, but right now there is nothing to do with the MAC once you have it.  Meaning no fi_xxx() to turn it into an fi_addr_t.  What I described above does exactly what you said (obtains the mac and passes it around) but it does it in a way having nothing to do with usnic or MAC addresses.  And it could be used by any other provider to pass around what that provider might need.

Just trying to do what you said with generic APIs instead of specific ones.

**Comment by shefty** [comment]
A provider can define their own address format, e.g. USNIC_UDP_IP_MAC_ADDRESS, which contains everything.  fi_getname can return that address, which may be passed directly into fi_av_insert.

There only seems to be an issue if the address format used by the applications (e.g. sockaddr) does not contain resolved data (e.g. MAC, LID, SL, GID), which an out of band exchange may help with.  This would allow the app to use hostnames or IP addressing, with local resolution for local endpoints, and that resolution exchanged out of band.

It seems like the question is whether the second usage model could just convert to the first model.

**Comment by sayantansur** [comment]
Does the OpenMPI BTL require sockaddr, or can it use a new USNIC_UDP_IP_MAC_ADDRESS address format? If there is no such requirement, then you're saying that usNIC provider can already get faster resolutions without any additions to libfabric API.
@jsquyres

**Comment by jsquyres** [comment]
The Open MPI usnic BTL currently is fed by an IP address (e.g., a sockaddr).  The usnic libfabric provider's fi_av_insert() currently does two things:

1. Determine whether the peer is reachable.
1. Determine the MAC address of the next hop to reach the peer.

The second step may have already been done, and can therefore be sent around as part of MPI's startup data exchange, which would mean that fi_av_insert() could be a skosh faster and simpler (i.e., the usnic provider may not need to force an ARP to load up the kernel's ARP table for this peer to get its next-hop MAC address, etc.).

**Comment by goodell** [comment]
@sayantansur Jeff didn't quite answer the question above.  AFAICT, the usnic BTL in OMPI should be able to use the new addr type approach and not require a new API call.

**Comment by sayantansur** [comment]
@goodell Thanks, but from Jeff's answer ... looks like you need the MAC address of the next hop to reach the target. Is that right? How can the target include this in its address? Sounds to me like this needs to be generated at the origin when its trying to get to the target. Just trying to understand ...

**Comment by goodell** [comment]
Two cases exist:

1. the next hop MAC is the MAC of the peer itself (by and large the most common case for a cluster where we would actually want this performance improvement)
2. the next hop MAC is the MAC of the IP gateway

To decide whether we have case *#*1 or *#*2 we would just make a quick netmask calculation that also gets backed up by the routing table lookup we have to do anyway (this is Jeff's "is reachable" step above).  If case *#*1, we can construct the header without initiating any ARP lookup.  Case *#*2 still requires the ARP lookup, though it should be highly cacheable inside the library, so I don't think this will be a real issue.

**Comment by sayantansur** [comment]
Excellent. Thanks for the detailed responses!

**Comment by shefty** [comment]
Returning to this issue, it appears that the discussion ended up that this feature is not needed and can be handled in a alternate way using the existing calls.  Please correct me if this is wrong.

**Comment by goodell** [comment]
@shefty agreed, no API extension seems to be required at this time.
