### ISSUE TITLE
verbs/RDM: RDMA_CM_EVENT_ROUTE_ERROR with ETIMEDOUT status

### ISSUE THREAD

**Issue by JoZie** [ofiwg/libfabric#3017]
I've written a small ping-pong application with libfabric, but when I'm scaling things up (> 1500 processes) many of them crash at the same time at prov/verbs/src/ep_rdm/verbs_ep_rdm.c:332. I did a little research and found out that they crashed from a **RDMA_CM_EVENT_ROUTE_ERROR** with an **ETIMEDOUT** status.

I'm not sure if this repo is the right place for this bug. I'm not even sure that this is a bug or just a miss-configuration of our cluster. Maybe it's the presence of MPI in the application.

I'm using the verbs/RDM provider of libfabric 1.4.2 on an Infiniband cluster with OFED 3.18.2 (I believe).

**Comment by shefty** [comment]
This is the correct place for reporting this.  Thanks!

**Comment by JoZie** [comment]
Are there any updates on this bug or can I contribute something to it's resolution?

**Comment by shefty** [comment]
There's no updates as far as I know.  If you can submit a patch that fixes this, that would be great.  :)  Adding @gladkovdmitry17 to this, but I'm not sure if he's the correct owner.  (Copying @a-ilango who maintains the overall verbs provider, just not the rdm portion.)  Can you confirm that this still happens with the 1.5a1 (alpha) release?

Note that we're hoping to replace the verbs/rdm code with the rxm provider, which should provide more OFI features.  Can you see if the app works with the rxm provider?  (RXM = reliable datagram endpoint over message endpoint)

**Comment by gladkovdmitry17** [comment]
Thanks for reporting this!
@JoZie it would be great if you can share your reproducer if possible and check your ping-pong application with 1.5a1 release as it was suggested by @shefty 
Seems you're right MPI application also is impacted by that.

**Comment by gladkovdmitry17** [comment]
@JoZie Is this still an issue for you? Did you try the master branch or the latest OFI release?

**Comment by shefty** [comment]
This is an old issue that references code which is no longer used.
