### ISSUE TITLE
ofi_alter_info discards primary capabilities if caps == 0

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3034]
Should this be discarding the secondary capabilities from the hints? 

https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_attr.c#L826

@shefty

**Comment by shefty** [comment]
I believe this is correct.  You're keeping only the primary capabilities that were requested by the app, but including all secondary capabilities supported by the provider.

**Comment by jswaro** [comment]
Well, I get that now... but doesn't a value of 0 for the caps mean all caps? This would seem to mean something different.

**Comment by shefty** [comment]
I think you're correct.  If caps == 0, then some sort of default caps supported by the provider should be returned.  This is matching the code from ofi_alter_info().  I wonder if both places shouldn't add a check like
```
if (hints->caps) {
    /* move caps assignment code here */
}
```
and assume that attr->caps has been set correctly by the provider otherwise

**Comment by jswaro** [comment]
I think its fair to assume the attr caps are set properly by the provider if the user doesn't provide a set of capability values.
