### ISSUE TITLE
Need manual ldconfig after fresh installation

### ISSUE THREAD

**Issue by byronyi** [ofiwg/libfabric#3038]
The error message appears after a fresh installation on Debian 8.8 of libfabric v1.4.2 from source:
```
$ fi_info
fi_info: error while loading shared libraries: libfabric.so.1: cannot open shared object file: No such file or directory
```

Such error goes away after ``sudo ldconfig``.

**Comment by jsquyres** [comment]
This is correct -- you may need to run `ldconfig` with root privileges in some environments / setups (but not all).

Are you asking why this is necessary?

**Comment by byronyi** [comment]
Sorry if this sounds stupid, but I am actually wondering if this could be done during the build/installation process. Some users may not be familiar with this particular issue, like myself several years ago.

**Comment by jsquyres** [comment]
Not stupid at all!

We hesitate to do that as part of the installation process for several reasons:

1. It's only necessary in some environments / setups.  For example, the libfabric library may not be installed into a default linker-located area (i.e., running `ldconfig` may have no effect).  
1. We don't want to surprise the admin by running `ldconfig` if it wasn't necessary (and it's not common among other GNU Autotools-built libraries).
1. The installing user may not have permissions to `ldconfig`, or even `sudo ldconfig`.

**Comment by byronyi** [comment]
Thanks for the explanation. This issue could still serve as a reference if anyone happen to get into the same issue.
