### ISSUE TITLE
FI_PEEK with buffer provided and FI_TRUNC

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#3046]
I need some clarification on the use of ```FI_PEEK``` without ```FI_CLAIM``` or ```FI_DISCARD``` and supplying a buffer as part of, say, a ```fi_trecv_msg``` call.  What happens if the supplied buffer is too small to consume a found message?   Should the provider post an error CQE with ```FI_ETRUNC```  to the appropriate CQ, or should it silently truncate the message and post a non-error CQE to the CQ?

The GNI provider as currently written does the later, but then it wasn't correctly reporting truncation errors either.  We have a unit test which posts a receive buffer with the peek request that is 1/2 the size of the waiting received message.  Now that I've fixed truncation error reporting, the unit test is failing.  So I'm wondering if its an error in the design of the test program, or should message truncation be handled differently in the case of a ```FI_PEEK``` only receive request.

Thanks for any clarification.

@sungeunchoi

**Comment by shefty** [comment]
Reading over the man pages and thinking about it, I agree with the behavior of the gni provider.  That is, return a successful completion, with the data truncated.  IIRC, the use case is to allow retrieving a header that may have been included as part of the message.  Note that the len reported in the CQ entry should still be the length of the message, not the size of the peeked data.

Does this make sense and seem reasonable?  I'll also see how the other providers are handling this.

**Comment by shefty** [comment]
I don't see that psm or sockets supports returning peek data.

**Comment by j-xiong** [comment]
My understanding is that it's the provider's choice to fill in any part of the user provided buffer, but the completion should always be a successful one if the message matches. The missing part is how the provider conveys the information about how much data is copied to the user buffer.

**Comment by shefty** [comment]
This is correct.  It's up to the app to remember the size of their peek buffer and compare that with the returned len.  A provider may not support peek returning any data, since the underlying interfaces or implementation may not allow it.

**Comment by hppritcha** [comment]
I'll do what @shefty suggests for the GNI provider.

**Comment by hppritcha** [comment]
closing this issue as I got the guidance needed.
