### ISSUE TITLE
Distinguish PSMX and PSMX2

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#3047]
Currently the same protocol type and address format is used for both psm and psm2 provider, i.e., FI_PROTO_PSMX and FI_ADDR_PSMX, respectively. This has been working fine since the too providers are completely separate. However, with the introduction of string address format, this can be an issue since the the address formats of the two providers are actually different. The protocols are also different. Should new definitions (FI_PROTO_PSMX2 and FI_ADDR_PSMX2) be introduced to avoid any future confusion?

**Comment by shefty** [comment]
I think new formats should be introduced, unless you can distinguish the two from each other (similar to sockaddr being one of many formats).  The protocol in particular seems that it should be separate.

**Comment by j-xiong** [comment]
Good. I will submit a PR for that.

**Comment by j-xiong** [comment]
Fixed by PR #3048.
