### ISSUE TITLE
clarification: FI_MR_MMU_NOTIFY

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3055]
I need clarification on the intent of the following:

> FI_MR_MMU_NOTIFY : FI_MR_MMU_NOTIFY is typically set by providers that support memory registration against memory regions that are not necessarily backed by allocated physical pages  at  the  time  the  memory  registration
       occurs.   (That is, FI_MR_ALLOCATED is typically 0).  However, such providers require that applications notify the provider prior to the MR being accessed as part of a data transfer operation.  This notification informs the
       provider that all necessary physical pages now back the region.  The notification is necessary for providers that cannot hook directly into the operating system page tables or memory management  unit.   See  fi_mr_refresh()
       for notification details.

Suppose an application will uses the following code:
```C 
struct fi_info *hints, *info;
int ret;

hints = fi_alloc_info();
hints->domain_attr->mr_mode = 0;

ret = fi_get_info(fi_version(), ..., hints, &info);
``` 

and with the above, does the application need to check for the presence of FI_MR_MMU_NOTIFY?

IE. Does the provider set that flag when needed, regardless of the provided hints -- OR -- Is the application responsible for knowing that a given provider requires FI_MR_MMU_NOTIFY, and thus should have provided FI_MR_MMU_NOTIFY above? 

The writing of the statement above would suggest that the application is expecting the provider to set the flag as a form of feedback... but generally speaking, aren't hints indicators to the provider, and not really vice versa? 

@shefty @hppritcha

**Comment by shefty** [comment]
> hints->domain_attr->mr_mode = 0;
> 
> ret = fi_get_info(fi_version(), ..., hints, &info);
> 
> and with the above, does the application need to check for the
> presence of FI_MR_MMU_NOTIFY?

No

> IE. Does the provider set that flag when needed, regardless of the
> provided hints -- OR -- Is the application responsible for knowing
> that a given provider requires FI_MR_MMU_NOTIFY, and thus should have
> provided FI_MR_MMU_NOTIFY above?

The application sets any mr_mode bits that it can support.  The provider will check the mr_mode bits and clear any that are not needed.

> The writing of the statement above would suggest that the application
> is expecting the provider to set the flag as a form of feedback... but
> generally speaking, aren't hints indicators to the provider, and not
> really vice versa?

When an app sets a mode bit, it is indicating that it is coded to handle that mode bit being set or not.

**Comment by jswaro** [comment]
> When an app sets a mode bit, it is indicating that it is coded to handle that mode bit being set or not.

So, is it fair to say, an application is coded to handle FI_MR_MMU_NOTIFY can use a provider that does not set that bit in the hints then? 

> sockets->domain_attr->mr_mode = 0
gni->domain_attr->mr_mode = FI_MR_MMU_NOTIFY

In the event that both of the info structures are provided back to the application, it could pick either one, as FI_MR_MMU_NOTIFY only indicates capability to handle the case, not the requirement.

**Comment by shefty** [comment]
correct
