### ISSUE TITLE
clarification: mr_mode bits

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3056]
In 1.4, an application was able to say 'I do not care what memory mode a provider can provide, just tell me what you can support' with FI_MR_UNSPEC. 

In 1.5, we seem to have lost that because FI_MR_BASIC and FI_MR_SCALABLE are deprecated, and the lack of bits doesn't imply that FI_MR_VIRT_ADDR is supported, and vice versa. 

Is this by design, or just a side-effect of making FI_MR_SCALABLE the default. Is this intentional or not?

@shefty @hppritcha @sungeunchoi

**Comment by shefty** [comment]
With 1.5+, an app that does not care can set all mr_mode bits to 1 to indicate that it does not care.  This is the cost of moving from an enum to selective requirements on the app.  The mr_mode bits behave similar to the fi_info::mode bits.

**Comment by jswaro** [comment]
Is that clearly documented? FI_MR_BASIC is a deprecated term in 1.5+, so as an application writer, I would not use a deprecated term as part of compliance with the API.

**Comment by shefty** [comment]
I'm not following the FI_MR_BASIC part.  With 1.5+, the app should set all mr modes that it supports to 1.  A don't care setting for 1.5 would be:

```
FI_MR_LOCAL | FI_MR_RAW | FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_MMU_NOTIFY | FI_MR_RMA_EVENT | FI_MR_ENDOPOINT
```

If new MR modes are added, the app must be updated to explicitly include them.  We can't use mr_mode = 0 to allow the app to say it doesn't care, since future versions of the api may add new modes, which would break the app.  The app should generally not reference UNSPEC, BASIC, or SCALABLE for 1.5+.  An exception is made for backwards compatibility purposes, so that existing apps do not break.

**Comment by jswaro** [comment]
> I'm not following the FI_MR_BASIC part. With 1.5+, the app should set all mr modes that it supports to 1.

My mistake. I misread what you wrote.



> A don't care setting for 1.5 would be:

That's a 'I support all of those modes, but I don't indicate that I can support 0-based offsets'. As a provider, I cannot infer that the application is capable of 0-based offsets *if* FI_MR_VIRT_ADDR is present. I have to assume that it is capable of that behavior *if* FI_MR_VIRT_ADDR is not present. 

I think my statement holds unless we are requiring application writers to support 0-based offsets regardless of whether any provider would support it. It doesn't actually matter much given some providers do support 0-based offsets.

**Comment by shefty** [comment]
> That's a 'I support all of those modes, but I don't indicate that I
> can support 0-based offsets'. As a provider, I cannot infer that the
> application is capable of 0-based offsets if FI_MR_VIRT_ADDR is
> present. I have to assume that it is capable of that behavior if
> FI_MR_VIRT_ADDR is not present.

The provider can clear the FI_MR_VIRT_ADDR bit.  The result is that 0-based addressing is used.  I.e. 0-based address is the default for 1.5+.  The same is true for other bits that get cleared -- e.g. user generated keys.

For compatibility an app can continue to use FI_MR_BASIC even in 1.5, which forces virtual addressing.

**Comment by jswaro** [comment]
> The provider can clear the FI_MR_VIRT_ADDR bit. The result is that 0-based addressing is used.

That's not really what I've been asking. How do I indicate I don't care what memory registration mode I get?

If my application supports 0-based AND virtual address AND 'I do not care what mode is returned to me', how do I indicate that? The presence of FI_MR_VIRT_ADDR doesn't imply support for 0-based addressing, and the omission of FI_MR_VIRT_ADDR does. I do not seem to have a way to say I support both.

As a provider, I might not support FI_MR_VIRT_ADDR... do I assume that the application can support 0-based addressing even if FI_MR_VIRT_ADDR is provided? 

More importantly (as an application writer), how do I convey to a provider that I am not capable of 0-based addressing? I provide all of those bits, because I can actually support  each of those modes, but ... the provider, without information about my capability with 0 based offsets, gives me the provider default of 'scalable'. I won't be able to request the 'virtual address' version of the provider, even if the provider supports that addressing model. 

This is a provider selection problem as well as a application operation issue, revolving around the FI_MR_VIRT_ADDR bit.

**Comment by shefty** [comment]
> That's not really what I've been asking. How do I indicate I don't
> care what memory registration mode I get?
> 
> If my application supports 0-based AND virtual address AND 'I do not
> care what mode is returned to me', how do I indicate that?

api_version = FI_VERSION(1,5)
mr_mode = FI_MR_VIRT_ADDR

 
> More importantly (as an application writer), how do I convey to a
> provider that I am not capable of 0-based addressing?

api_version = FI_VERSION1,4)
mr_mode = FI_MR_BASIC

Any app that moves to 1.5 MUST support 0-based addressing, which is trivial.

**Comment by jswaro** [comment]
Ok, recap:

- If I want a virtual addressing version from a provider capable of both modes in _**1.5**_:  mr_mode = FI_MR_BASIC. (is this true? you specified 1.4. Does this still apply to 1.5?)
- If I want a 0-based offset version from a provider capable of both modes in 1.5: mr_mode = (all bits but FI_MR_VIRT_ADDR);
- If I don't care what version I get from a provider (regardless of capabilities, as the provider is responsible for indicating what it is capable of): mr_mode=(all mr mode bits)


Use cases:  For allowing both versions of a provider to be requested:

For providers, we may be doing testing of both modes.

For users, there is a case for comparing implementations during design phase, for which a user might want MR_BASIC for a provider that is capable of scalable, just to ensure that the implementations match. (approximately) 


**As a thought**
And in 1.5: If FI_MR_BASIC is used to say 'virtual addresses only', why don't we have a separate flag, and allow the application to choose if it wants zero based offsets? Having both flags would convey to the provider that either addressing mode is acceptable, and would allow for greater flexibility. 0 could be all capabilities, similar to the current behavior with hints->caps. An application would have to support one or both of offset and virtual address, so 0 is a plausible catch-all. 

If I wanted anything, mr_mode=0; If I wanted only virtual addressing versions, mr_mode(all bits except FI_MR_OFFSET <name for sake of example>); If I wanted only 0-based offset versions (all bits except FI_MR_VIRT_ADDR)

**Comment by j-xiong** [comment]
Notice that mr_mode is mostly a "mode", i.e., a mechanism to expose the limitation of the provider, not to express what the application want to use. The application can set certain bits to indication that it is ready to deal with the corresponding limitations, but the provider can clear these bits to indicate that it doesn't have such limitation. For example, application can set FI_MR_VIRT_ADDR to tell the provider that it can handle virtual addressing (not that it can only handle virtual addressing). If the provider clears that bit, the application knows that the provider doesn't need virtual addressing and it can assume that 0-based addressing should be used.

The only exception is FI_MR_BASIC, which the provider would interpret as a request. 

If 0 is passed, it simply means that the application can't handle any limitations, i.e., it expects the default behavior i.e. FI_MR_SCALABLE.

**Comment by jswaro** [comment]
**I have the information I need to accomplish what I need to do.** I'm closing the issue since I have the clarification I wanted.  

I can understand most of the reasoning here. The decision months ago, as I understand it, was to expose the various aspects of FI_MR_BASIC and FI_MR_SCALABLE in a way that was not limiting to providers (or applications) and the hardware they would support.  Most of this seems to be treated well in spirit with the exception of the case of FI_MR_BASIC. 

What doesn't sit well with me is that this mode is encoded in flags where **one of them has a mixed meaning**. FI_MR_BASIC has the same meaning as (FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY), but with a **directive** to the provider to disregard all/some of other flags. 

My interpretation of the usage of FI_MR_BASIC, as a mode bit in 1.5, is that it isn't a mode bit at all, because it can't really be used with the other mode bits. The same expression could be done with one additional flag, and none of the complexity/confusion of FI_MR_BASIC's meaning in 1.5. Unlike every other flag in the mr_mode bit set, FI_MR_BASIC is exclusive or redundant with 3 or more flags. 

Given that it seems that as an API, libfabric is trying to get away from FI_MR_SCALABLE and FI_MR_BASIC definitions from the prior version of the API, I was not expecting to reuse those definitions to support behavior that could be defined via one extra bit.

I'd be open to discussions on the topic of how this could be approached differently.

**Comment by shefty** [comment]
FI_MR_BASIC is supported on 1.5 for backwards compatibility purposes.  As a result, it maintains the same definition that it had for all prior releases.  FI_MR_BASIC should not be mixed with any other mode bits.
