### ISSUE TITLE
NEWS.md file doesn't mention FI_CONTEXT2

### ISSUE THREAD

**Issue by wesbland** [ofiwg/libfabric#3059]
I was just going through the NEWS file to see all the changes for 1.5 and didn't see a mention of `FI_CONTEXT2`. Given that this is a new mode bit that could have some larger changes for how the user needs to work with a provider, I think it would be helpful to mention it.

I'd do it myself, but I'm not really sure how you guys handle the NEWS.md file so I don't know where to make the PR.

**Comment by shefty** [comment]
The NEWS.md file is just a text file in the libfabric repo.  I'll update the file, though.  Thanks for finding that gap.
