### ISSUE TITLE
Allow registration to map an iovec to a single virtual fabric memory region

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#3062]
I may have missed something but it does not seem to be correct that an array of descriptors should be passed to `fi_writev`/`fi_readv` ?
```
ssize_t
fi_writev(struct fid_ep *ep, const struct iovec *iov, void **desc, size_t count,
fi_addr_t dest_addr, uint64_t addr, uint64_t key, void *context);
```
Both fi_mr_regv and fi_mr_regattr take an iovec / iov_count as a parameter:
```
int
fi_mr_regv(struct fid_domain *domain, const struct iovec * iov, size_t count,
  uint64_t access, uint64_t offset, uint64_t requested_key, uint64_t flags, 
  struct fid_mr **mr, void *context);
```
The MR descriptor is returned from `fi_mr_desc`:
```
void * fi_mr_desc(struct fid_mr *mr);
```
I can understand the case where `fi_mr_reg` is called on each segment but if `fi_mr_regv` has been called previously, I get one desc for the region described, would I then have to copy each `desc`? Either there is a mistake in the API or something must be clarified in the documentation I think...

Thanks

Jerome

**Comment by shefty** [comment]
> fi_writev(struct fid_ep *ep, const struct iovec *iov, void **desc,
> size_t count,

Count applies to the number of entries in the iov and desc array.  Is that what you're asking about?

I think the answer is that, yes, you need to copy the desc.  There's no guarantee that the iov passed into writev is the same iov passed into regv.

**Comment by soumagne** [comment]
Yes, that's what I thought as this is what the API implies.

I would assume that the fi_mr_regv call is here to simplify/optimize things... I can understand that a user can pass an iovec with segments that are not the same as the ones passed into regv but I'm not really sure I see the value of doing that. Now I'm forced to create a separate array and copy the same desc value for each segment, whereas I could do exactly the same by calling fi_write in a loop (and I will anyway need a loop to parse/copy each desc). Why would I call fi_mr_regv then? If you pass just one single descriptor, at least the fi_writev call is limited to an iovec that is a subset of the one that was passed to the fi_mr_regv call...

**Comment by shefty** [comment]
To be fair, I don't think any provider supports registering an iov size other than 1...

I think what's wanted is for regv to convert an iovec into a single fabric virtual address range (with base address of 0).  So that the app can do something like:
```
regv(..., iovec, &mr, FI_NEW_FLAG_MAP_IOVEC);
write( ..., 0, fi_mr_desc(mr), ...);
```
Then the provider is responsible for using the desc to map to the specified set of pages.

**Comment by soumagne** [comment]
:) ok yes and it's certainly low-priority for now, I was just trying to see how this would fit into our API in the future when/if providers support it.
If I can just use fi_write then yes I think that would be good enough for me as I would just use a virtual offset/length to transfer the data.

**Comment by shefty** [comment]
Changed title and marked as an enhancement request for the API.  Full details would still need to be worked out.  Thanks for the feedback!

**Comment by soumagne** [comment]
ok thanks!

**Comment by j-xiong** [comment]
FYI, this (mapping iovec to a single virtual MR) has been supported in the psm/psm2 providers for a long time.
