### ISSUE TITLE
using the AV API with FI_ADDR_STR

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#3064]
@thananon is implementing the `FI_ADDR_STR` support for the usNIC provider and pointed out that the `fi_av_insert` function takes a variable number of addresses for insertion, but takes a single `void *` argument. How are the provider and application expected to interpret the `addr` argument to `fi_av_insert` in this case? I don't see anything in the documentation. One way to implement it is to assume that all address strings are the same length (i.e. 64 characters) and continuous in memory, is that the expected interface?

I can update the documentation if needed. 

@shefty

**Comment by shefty** [comment]
I can think of two choices.

1 Have addr point to char **.

2 Document that each string ends with a series of 1 or more '\0' (zero byte) characters.  The next string starts with the first non-zero byte.

Option two supports an array of concatenated strings and an array of fixed length strings.  I'm guessing that the latter may actually work best for apps wanting to use ADDR_STR.

**Comment by jsquyres** [comment]
I like the `(char **)` idea.  Trivial indexing that way.

Do we need to specify how to free the returned value?  I.e., specify that:

```c
free(addrs[0]);
free(addrs);
```

is sufficient?

**Comment by shefty** [comment]
I don't understand the question about freeing the returned value.  The issue is how to specify the addresses as input into av insert.

One issue with char ** is if cnt = 1, the interface is no longer intuitive.  I think we want the same behavior for all cnt values.  It would help to understand how an app would use this for cnt > 1.  E.g. are the apps going to collect strings using an array of fixed size strings.

I wonder if we can make use of the dest_addrlen field from fi_info.

**Comment by jsquyres** [comment]
Yes, please completely ignore my comment about freeing the data.  I was thinking of the wrong thing... 😨 

I think it's ok to pass an array for this parameter (for FI_ADDR_STR) in _all_ cases, even when `cnt==1`.

**Comment by bturrubiates** [comment]
> One issue with char ** is if cnt = 1, the interface is no longer intuitive. I think we want the same behavior for all cnt values. It would help to understand how an app would use this for cnt > 1. E.g. are the apps going to collect strings using an array of fixed size strings.

Well, it's the same behavior for all cnt values it just means we'd always need an array even if it's of size 1. Who proposed the original feature request? Maybe we could ask them. I think it was @rhc54 (judging from #2485).

After talking it over with @jsquyres and @thananon I think we'd prefer the `char **` approach just because it makes it a bit cleaner. We'd have to document the `char **` -> `void *` usage though. 





> I wonder if we can make use of the dest_addrlen field from fi_info.

As in specify a fixed length for the address strings? The original stringification proposal allowed for variable parameters at the end, so I'd like to keep the length flexible.

**Comment by shefty** [comment]
I agree we can pass an array for all cnt values.  I'm just pointing out that most people are going to try passing in a pointer to the string for cnt = 1.  That also matches how all other addresses work.  Requiring a pointer to a pointer to the string isn't an obvious thing to do.

I agree that char ** seems the least sucky option.  But will this result in the app needing to do additional work to construct the char ** list?

**Comment by bturrubiates** [comment]
For `fi_av_insertsvc` I assume that the string would be passed in the `node` parameter as in `fi_getinfo`. Probably good to document that.

**Comment by shefty** [comment]
I thought Jeff proposed the original feature request, though the solution was quite a bit different from the request.

**Comment by jsquyres** [comment]
Yes, I agree -- FI_ADDR_STR doesn't really solve #2485 in the way that I wanted.

I.e., I didn't want to force all interaction with the AV to be via strings.  I just wanted a way to stringify / destringify an address.

**Comment by bturrubiates** [comment]
> I agree that char ** seems the least sucky option. But will this result in the app needing to do additional work to construct the char ** list?

Yeah, it would have some construction overhead.

**Comment by bturrubiates** [comment]
After some offline discussion with @thananon @shefty @jsquyres we have come up with some proposed changes, I'll be submitting a PR to further the discussion.
