### ISSUE TITLE
verbs/RDM: Tests hang when source address is not provider on the server side

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#3134]
What works:
server: fi_rdm_pingpong -p verbs -s <server_address>
client: fi_rdm_pingpong -p verbs <server_address>

What doesn't work:
server: fi_rdm_pingpong -p verbs
client: fi_rdm_pingpong -p verbs <server_address>

If specifying the source address on the server side is a requirement, the provider can print a warning and return an error instead of hanging.

@gladkovdmitry17

**Comment by gladkovdmitry17** [comment]
@a-ilango @shefty Could you please assign the issue on me, please? I'm going to have a deal with this issue

**Comment by a-ilango** [comment]
@gladkovdmitry17 Did you get a chance to look at this?

**Comment by gladkovdmitry17** [comment]
@a-ilango, I'm really sorry, there were no time to look into this. I'll try to look into this right now or tomorrow. Thanks for reminder  :) 

--------------------------------------------------------------------
Joint Stock Company Intel A/O
Registered legal address: Krylatsky Hills Business Park,
17 Krylatskaya Str., Bldg 4, Moscow 121614,
Russian Federation

This e-mail and any attachments may contain confidential material for
the sole use of the intended recipient(s). Any review or distribution
by others is strictly prohibited. If you are not the intended
recipient, please contact the sender and delete all copies.

**Comment by gladkovdmitry17** [comment]
@a-ilango Btw, sockets provider hangs in the `fi_rdm` test as well.

**Comment by a-ilango** [comment]
> I'm really sorry, there were no time to look into this. I'll try to look into this right now or tomorrow.

No problem. Thanks!

> @a-ilango Btw, sockets provider hangs in the fi_rdm test as well.

I don't see any issue. Sockets provider works fine for me.

**Comment by a-ilango** [comment]
RDM implementation internal to verbs provider (verbs/RDM) has been deprecated.
