### ISSUE TITLE
sockets: ubertest is failing

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#3145]
See our Jenkins log [here](https://gist.github.com/cisco-usnic-bot/8c93da41fcc51a9fb4b948d0acbd0e39).

@shefty @aingerson 

I haven't been able to look into it much

**Comment by aingerson** [comment]
Looks like the runfabtests.sh script has a hardcoded timeout of 90 seconds per test and the recently added sockets "quick" ubertest now has 26000+ tests included, running at about 3 minutes. I will change the sockets quick test to actually be a quick test and change this test to "all" to fix this. Might have to figure out a workaround for that timeout value in the future, but the big test config is mostly there to record all iterations that are testable with ubertest.

**Comment by bturrubiates** [comment]
That makes sense, thanks!
