### ISSUE TITLE
rxm providers disppeared

### ISSUE THREAD

**Issue by droccom** [ofiwg/libfabric#3167]
After updating to commit c57d7f6 (was 53e5534), rxm providers (e.g., sockets;ofi_rxm, verbs;ofi_rxm) do not show up from fi_getinfo.

To reproduce, just run fi_info.

**Comment by shefty** [comment]
The removal of sockets;ofi_rxm was intentional.  The layering of utility providers (i.e. rxm) over sockets is no longer reported to the user unless that combination is explicitly requested.  The layering over verbs should still have worked however.  We'll investigate.  Thanks.

**Comment by a-ilango** [comment]
`fi_info -p ofi_rxm` works but just `fi_info` doesn't show ofi_rxm provider layering.
