### ISSUE TITLE
verbs/rxm provider: directed receive not working

### ISSUE THREAD

**Issue by droccom** [ofiwg/libfabric#3196]
In a simple test I wrote, I get a completion event for a receive request, with specific source address A, upon receiving data from another address B, although the request is the only one sitting in the completion queue.

The same code runs correctly with the sockets provider, whereas the issue is visible with the verbs;ofi_rmx one.

To replicate, clone this repository:
http://alpha.di.unito.it:8080/git/drocco/fabspikes.git

Run with sockets:
```bash
LFS_LOCALHOST=<ethernet_localhost_address> make pingpong5-test -B
```

Run with verbs;ofi_rxm:
```bash
LFS_LOCALHOST=<ib_localhost_address> make pingpong5-test -B
```

Check the selected provider in `srv.err`.

If you see the following message on stdout:
```bash
> ERROR broken order
```
then the issue has occured.

**Comment by a-ilango** [comment]
@droccom Thank you for reporting this and providing a reproducer. Let me know if the fix ( #3200 ) works for you. I ran the test you mentioned and it passes with this fix.

**Comment by droccom** [comment]
@a-ilango Thanks. Now the ordering issue has been resolved, but the program sometimes hangs if the server is started after the clients (Makefile, line 36).

With gdb, I see two threads are in execution while hanging, with the following traces:

=== Thread 1
#0  0x00007ffff706ad13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007ffff7b97a38 in fi_ibv_eq_sread () from /archive/home/mdrocco/usr/lib/libfabric.so.1
#2  0x00007ffff7babe90 in rxm_conn_event_handler () from /archive/home/mdrocco/usr/lib/libfabric.so.1

=== Thread 2
#0  0x00007ffff6727213 in pthread_spin_lock () from /lib64/libpthread.so.0
#1  0x00007ffff7b72b25 in ofi_cq_read () from /archive/home/mdrocco/usr/lib/libfabric.so.1
#2  0x0000000000401541 in fi_cq_read (cq=0x615630, buf=0x7fffffffd880, count=1)
    at /archive/home/mdrocco/usr/include/rdma/fi_eq.h:385
#3  0x0000000000401cc4 in lfs_node::fm_spin_for_comp (this=0x7fffffffd9d0, cq=0x615630) at lfs_node.hpp:146

Perhaps I am doing something nasty with polling in my code?

**Comment by a-ilango** [comment]
Re-opening as the test hang issue is not resolved yet.

**Comment by a-ilango** [comment]
@droccom I've opened one more PR with more bug fixes. I don't see the intermittent hangs anymore.

**Comment by droccom** [comment]
@a-ilango Thanks!

The problem on the replicator seems gone. I am still experiencing some hangs in my real application, but I think this issue should be closed since the directed-receive misbehavior has been resolved. I am preparing a replicator for the hangs.
