### ISSUE TITLE
FI_SOURCE_ERR and socket provider

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#3216]
https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.5.0 mentions that 1.5.0 has support for FI_SOURCE_ERR with socket provider but it does not seem to be enabled at least.

**Comment by shefty** [comment]
The feature matrix is in error.  Support for FI_SOURCE_ERR is not available for sockets yet.  I've updated the matrix.

**Comment by soumagne** [comment]
thanks!
