### ISSUE TITLE
Sockets: The provider is losing messages when FI_MULTI_RECV space runs low.

### ISSUE THREAD

**Issue by epaulson10** [ofiwg/libfabric#3217]
First off, this issue was reported by LBNL when testing GASNet and is described in detail on their Bugzilla here: https://upc-bugs.lbl.gov/bugzilla/show_bug.cgi?id=3597

Second, here are the hints being used in GASNet:
```
hints->caps                   = FI_RMA | FI_MSG | FI_MULTI_RECV;
hints->mode                   = FI_CONTEXT; 
hints->addr_format  = FI_FORMAT_UNSPEC;
hints->tx_attr->op_flags = FI_DELIVERY_COMPLETE;
hints->ep_attr->type = FI_EP_RDM;
hints->domain_attr->threading = FI_THREAD_DOMAIN;
hints->domain_attr->control_progress  = FI_PROGRESS_MANUAL;
hints->domain_attr->resource_mgmt  = FI_RM_ENABLED;
hints->domain_attr->av_type = FI_AV_TABLE;
```
Also note that this test is running in a single thread.

The test that is hanging due to lost messages is testam, which fires a large number of messages at once. This failure is sporadic and occurs at different times. Sometimes it takes place in the test warmup, sometimes it takes place in the test body, sometimes it happens after the test is run. To run the test and reproduce the failure, I loop the test as so: 
`$ while FI_PROVIDER=sockets ./contrib/gasnetrun_ofi -np 2 ./testam 10000 8192 F; do :; done `

The specific test above (designated by specifying 'F') is a two-way flood test, meaning both nodes are sending messages to each other. On examining the processes, I see that one process has finished sending and receiving all messages (10000, as specified in the command). The other process, has successfully sent all of its messages, but has only received a portion of them. In the run I have on my screen right now, out of 10,000 messages, the node is stuck only having received 5790 of them.

I believe this has to do with the handling of buffered messages in sockets when the FI_MULTI_RECV buffers in GASNet run out of space. The first indication of this is the log messages I get. Sometimes (but not all the time), I get this log dump:
```
libfabric:sockets:cq:_sock_cq_write():181<warn> Not enough space in CQ                        
...            
libfabric:sockets:cq:_sock_cq_write():181<warn> Not enough space in CQ                        
libfabric:sockets:ep_data:sock_rx_new_buffered_entry():109<warn> Exceeded buffered recv limit 
...
libfabric:sockets:ep_data:sock_rx_new_buffered_entry():109<warn> Exceeded buffered recv limit 
```

By default, GASNet allocates 8 multi-recv buffers, each 1MB in size. These are split between two receiving endpoints. If i greatly increase the size or number of the receive buffers (make each 8MB in size or post 8 times as many 1MB buffers) I can't reproduce this error. If I reduce the number of buffers to two (which is the minimum, as there are two MSG endpoints in GASNet/ofi) then the test won't function at all (and the test does function under these circumstances with other providers, like psm2).

**Comment by shefty** [comment]
From the log it appears that the provider is unable to write the completion, which results in lost events.   This may be an issue with the resource management support.

**Comment by epaulson10** [comment]
> From the log it appears that the provider is unable to write the completion, which results in lost events.
> This may be an issue with the resource management support.

If my reading of the code is correct, this message means that sockets will malloc additional memory to hold the completion entry. I get this message (by itself) on successful runs sometimes. I also can completely squelch this message and still get a hang by setting the CQ size to a number larger than the number of messages I need to send.

**Comment by shefty** [comment]
Do you always or only sometimes see this message:
```
libfabric:sockets:ep_data:sock_rx_new_buffered_entry():109<warn> Exceeded buffered recv limit 
```

**Comment by epaulson10** [comment]
Only sometimes, which also includes the message about the CQ not having enough space.

**Comment by epaulson10** [comment]
@shefty and I believe we found the solution to this bug, but I don't have the mental fortitude left after finding it to patch it and test it. I will do that tomorrow.

Note to self, the relevant diff is:
```
diff --git a/prov/sockets/src/sock_progress.c b/prov/sockets/src/sock_progress.c
index feeb94b..ecdac80 100644
--- a/prov/sockets/src/sock_progress.c
+++ b/prov/sockets/src/sock_progress.c
@@ -1160,14 +1160,15 @@ static int sock_pe_progress_buffered_rx(struct sock_rx_ctx *rx_ctx)
                datatype_sz = (rx_buffered->flags & FI_ATOMIC) ?
                        ofi_datatype_size(rx_buffered->rx_op.atomic.datatype) : 0;
                offset = 0;
+                // rem: size of the message
                rem = rx_buffered->iov[0].iov.len;
                rx_ctx->buffered_len -= rem;
                used_len = rx_posted->used;
                pe_entry.data_len = 0;
                pe_entry.buf = 0L;
                for (i = 0; i < rx_posted->rx_op.dest_iov_len && rem > 0; i++) {
-                       if (used_len >= rx_posted->rx_op.dest_iov_len) {
-                               used_len -= rx_posted->rx_op.dest_iov_len;
+                       if (used_len >= rx_posted->iov[i].iov.len) {
+                               used_len -= rx_posted->iov[i].iov.len;
                                continue;
                        }
```
```
@@ -1221,11 +1225,15 @@ static int sock_pe_progress_buffered_rx(struct sock_rx_ctx *rx_ctx)

                if (rem) {
                        SOCK_LOG_DBG("Not enough space in posted recv buffer\n");
                        sock_pe_report_rx_error(&pe_entry, rem, FI_ETRUNC);
                } else {
                        sock_pe_report_recv_completion(&pe_entry);
                }

+                rx_posted->is_busy = 0;
+
                dlist_remove(&rx_buffered->entry);
                sock_rx_release_entry(rx_buffered);
```

**Comment by bonachea** [comment]
Thank you both for your quick response and great work!
