### ISSUE TITLE
prov/socket, psm, psm2, util: cq readerr corrupts stack with 1.4 app

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#3226]
The size of fi_cq_err_entry changed from 1.0 to 1.5.  The 1.5 version includes an extra field that is not present in 1.4 and earlier.  Based on code inspection, the socket, psm, psm2, and ofi_cq_readerr code improperly copy too much data when a 1.4 application calls cq_readerr.  Apparently this bug doesn't show up in practice all that much, but can be reproduced by running the 1.4 fabtests against libfabric 1.5 with the fi_rdm_tagged_peek test with debugging enabled.

I've seen this with the sockets provider, but checked all of them.  The ones mentioned appear to have this issue.

@a-ilango @j-xiong - I'm working on a fix for all providers, so this is just an FYI

**Comment by bturrubiates** [comment]
In order to do the copy correctly it requires a version check, right? That must mean that usNIC is also affected.

**Comment by shefty** [comment]
usnic is doing a version check

**Comment by shefty** [comment]
@j-xiong - The psm providers aren't tracking the version that I can tell.  How do you want to handle this?  Should I track the version with the fabric, similar to the util code?

**Comment by shefty** [comment]
@j-xiong never mind - I forgot how we did this :P

**Comment by j-xiong** [comment]
@shefty The psm/psm2 providers call utility fabric functions. To track the version passed down from the user code,  a new field can be added to either "struct util_fabric" or to "struct psmx*_fid_fabric". The former is more preferable since it can benefit multiple providers.

**Comment by j-xiong** [comment]
@shefty I missed that part, too :) I looked at the utility code but overlooked the common code.

BTW, is this the only ABI change that can cause backward compatibility issue?

**Comment by shefty** [comment]
Most of the compatibility issues are handled by the framework, so that the provider only deals with 1.5 structures.  But there is a similar compatibility situation dealing with EQ readerr.  The behavior changes from 1.4 to 1.5, but in the EQ case, the structure is the same.  You may want to see:

https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_eq.c#L153

I don't know if this sort of change applies to psm, but I'd guess no.

**Comment by j-xiong** [comment]
The psm/psm2 providers totally use the utility eq so I think no change is needed.
