### ISSUE TITLE
Support for hardware collective offloading

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3234]
The Aries hardware has a built-in collective offloading engine that we could expose via libfabric using common interface(fi_collective?). Is there any interest in creating a common interface that other providers could use? 

- It could be similar to the atomics interface in terms of what operations are supported (fi_collective_valid/fi_query_collective)
- It could define a standard set of collectives, such as AND, OR, ADD, etc... 
- Using the knowledge above, applications could choose to use a provider-level collective if the operation is supported, reducing the number of messages/operations issued to providers for collective operations.

Thoughts?

@shefty @a-ilango @hppritcha

**Comment by shefty** [comment]
I believe that there is interest in defining collective support.  The schedule API proposed by @sayantansur a while back was for this purpose.  The experimental deferred work queue is intended as a step to defining that scheduling API.  Someone from the Intel MPI group may discuss this more at SC 17, but I'm not completely sure if that will happen or what the details will be.

**Comment by jswaro** [comment]
> The schedule API proposed by @sayantansur a while back was for this purpose.

Was it proposed in a WG call? I performed a quick search but did not find an OFIWG issue related to 'schedule' or 'deferred'. 

> The experimental deferred work queue is intended as a step to defining that scheduling API.

Same as above. I didn't find it. I'd be curious to see what has been proposed in other areas. 

> Someone from the Intel MPI group may discuss this more at SC 17, but I'm not completely sure if that will happen or what the details will be.

Do you believe they will request this from the OFI working group, or have they done something with a fork and provider extensions?

**Comment by sayantansur** [comment]
Here are some slides about the thoughts I had discussed during OFIWG calls. This is nearly a year back, and I think there are better ways of going about it, but the core idea remains the same. Have the MPI/SHMEM layer define a schedule of operations and dependencies that it wants to do, and then the provider can go about performing the task using the primitives it has from the underlying system.

http://mug.mvapich.cse.ohio-state.edu/static/media/mug/presentations/2016/Collective-Offload-OFI.pdf

**Comment by shefty** [comment]
The schedule API was discussed when I was out on sabbatical, I believe. It was a while ago.  I'll see if I can find the presentation and send it to the mail list.  The deferred work queue is part of the 1.5 release (marked as experimental).  See the fi_trigger man page.

The Intel MPI work would be for the working group, and not tied to a specific provider.  It's a relatively high-level abstraction.
