### ISSUE TITLE
util_ns changes breaking fabtests

### ISSUE THREAD

**Issue by aingerson** [ofiwg/libfabric#3236]
Commit bd7db0a5ad37c1070e7fb479c175591e9f5086f7 seems to be breaking many of our fabtests with psm/psm2. Various tests are returning ENODATA or segfaulting.

@gladkovdmitry17 could you take a look?

**Comment by gladkovdmitry17** [comment]
Sure, I'm working on that now. Thanks for you finding.

**Comment by gladkovdmitry17** [comment]
@shefty Seems it should be fixed by #3239. Could you close this, please? Thanks.
