### ISSUE TITLE
DL Providers are not registered in the correct ranking order

### ISSUE THREAD

**Issue by nrspruit** [ofiwg/libfabric#3263]
When OFI registers the static(built-in) providers. they are registered based off a ranking scheme to enforce certain providers being chosen over other providers when a user does not specify the provider they wish to use.

For example, this means that the PSM2 provider would be chosen before the PSM or VERBS providers on a supported HW.

Our current ranking is : PSM2,PSM,USNIC,MLX,VERBS,GNI,BGQ,NETDIR,RXM,RXD,UDP,SOCKETS

This works well for built-in providers, but when a user installs DL providers this ranking scheme is broken.

DL providers are registered in the order in which they are read in the DL Prov directory. This means that any DL provider registered would potentially precede providers that otherwise would have been chosen since they are not ordered based off the above ranking.

The DL providers need to be added to the provider registration while maintaining the ranking order otherwise users with DL providers will have a high chance of using a provider that was unexpected.

**Comment by pmmccorm** [comment]
I was just looking at your PR (please reference this issue in that in the future). I wanted to get clarification, the order we have now is (from left to right):

```
[dl providers in some filesystem dictated order] [builtin providers: psm2,psm,usnic,mlx...]
```

And what you want is:

```
psm2-dl,psm2 psm-dl,psm usnic-dl,usnic ...
```

**Comment by shefty** [comment]
The main issue is a sockets-dl provider will be reported before a high-performing network provider, or that verbs over OPA would be reported before psm2 over OPA.

The proposed solution allows us to specify the order we want and ensure that order is maintained.

In a separate email exchange, we discussed allowing an admin to set the order based on the FI_PROVIDER settings, but that can be a separate change.
