### ISSUE TITLE
fi_pingpong assumes !FI_MR_PROV_KEY returned by provider

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3264]
FI_MR_PROV_KEY isn't covered by the test, because otherwise it would be attempting to provide 0 as the requested key.

**Comment by jswaro** [comment]
@shefty

**Comment by shefty** [comment]
Why wouldn't 0 work as a requested key?

**Comment by jswaro** [comment]
0 would work. It looks to me that it is attempting to pass a non-zero value.
