### ISSUE TITLE
prov/psm2: gcc implicit fall-through warning

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#3342]
gcc complains implicit fall through in the following line. @j-xiong can you check this? Please add a comment: /* fall through */ if needed. That should silence gcc warning.

https://github.com/ofiwg/libfabric/blob/b1180f312c0e953dfa84899732c180bab393f100/prov/psm2/src/psmx2_rma.c#L424

**Comment by j-xiong** [comment]
Actually a break is missing here. Thanks for bring this up. Will fix it soon.
