### ISSUE TITLE
prov/verbs - possible race in disconnection code

### ISSUE THREAD

**Issue by fzago-cray** [ofiwg/libfabric#3348]
While running:

    # while true; do sleep 3; MPIR_CVAR_OFI_USE_PROVIDER="verbs" srun --kill-on-bad-exit -N 32 -n 256 sh -c "ulimit -c unlimited ; ./mpi/collective/osu_alltoall -m 8" ; done

a process crash. gdb shows this:

    #0  0x00007ffff6e0037c in dlist_insert_after (item=0x911100, head=0x911100) at ./include/fi_list.h:73
    73		head->next->prev = item;
    Missing separate debuginfos, use: debuginfo-install glibc-2.17-105.el7.x86_64 libgcc-4.8.5-4.el7.x86_64 libibverbs-1.2.1mlnx1-OFED.3.4.0.1.4.34100.x86_64 libmlx4-1.2.1mlnx1-OFED.3.4.0.0.4.34100.x86_64 libmlx5-1.2.1mlnx1-OFED.3.4.1.0.0.34100.x86_64 libnl-1.1.4-3.el7.x86_64 librdmacm-1.1.0mlnx-OFED.3.4.0.0.4.34100.x86_64 numactl-libs-2.0.9-5.el7_1.x86_64
    (gdb) bt
    #0  0x00007ffff6e0037c in dlist_insert_after (item=0x911100, head=0x911100) at ./include/fi_list.h:73
    #1  0x00007ffff6e003b4 in dlist_insert_before (item=0x911100, head=0x6f0a10) at ./include/fi_list.h:80
    #2  0x00007ffff6e00acf in fi_ibv_rdm_move_to_cq (cq=0x6f09e0, request=0x911100) at prov/verbs/src/ep_rdm/verbs_queuing.h:56
    #3  0x00007ffff6e02643 in fi_ibv_rdm_eager_send_ready (request=0x911100, data=0x7fffffffcf30) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c:212
    #4  0x00007ffff6e0f669 in fi_ibv_rdm_req_hndl (request=0x911100, event=FI_IBV_EVENT_POST_READY, data=0x7fffffffcf30)
    at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm_states.c:1719
    #5  0x00007ffff6e1575f in fi_ibv_rdm_send_common (sdata=0x7fffffffcfe0) at prov/verbs/src/ep_rdm/verbs_utils.c:270
    #6  0x00007ffff6e11d0f in fi_ibv_rdm_tagged_senddatato (fid=0x6effd0, buf=0x7ffff1ea9698, len=8, desc=0x0, data=0, dest_addr=7365696, 
    tag=3076567035254145058, context=0x7ffff1ea9660) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c:307
    #7  0x00007ffff6e11d67 in fi_ibv_rdm_tagged_sendto (fid=0x6effd0, buf=0x7ffff1ea9698, len=8, desc=0x0, dest_addr=7365696, tag=3076567035254145058, 
    context=0x7ffff1ea9660) at prov/verbs/src/ep_rdm/verbs_tagged_ep_rdm.c:315
    #8  0x00007ffff75d5432 in MPID_nem_ofi_iStartContigMsg () from /home/users/fzago/install/lib/libmpi.so.0
    #9  0x00007ffff755f91c in MPIDI_CH3_PktHandler_Close () from /home/users/fzago/install/lib/libmpi.so.0
    #10 0x00007ffff75bd055 in MPID_nem_handle_pkt () from /home/users/fzago/install/lib/libmpi.so.0
    #11 0x00007ffff75c8df2 in MPID_nem_ofi_handle_packet () from /home/users/fzago/install/lib/libmpi.so.0
    #12 0x00007ffff75d5d12 in MPID_nem_ofi_poll () from /home/users/fzago/install/lib/libmpi.so.0
    #13 0x00007ffff75bde9a in MPIDI_CH3I_Progress () from /home/users/fzago/install/lib/libmpi.so.0
    #14 0x00007ffff755facd in MPIDI_CH3U_VC_WaitForClose () from /home/users/fzago/install/lib/libmpi.so.0
    #15 0x00007ffff75a6a85 in MPID_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #16 0x00007ffff74dec9c in PMPI_Finalize () from /home/users/fzago/install/lib/libmpi.so.0
    #17 0x000000000040126d in main (argc=3, argv=0x7fffffffd648) at osu_reduce.c:72
    (gdb) p head
    $1 = (struct dlist_entry *) 0x911100
   (gdb) p *head
   $2 = {next = 0x0, prev = 0x911100}

That looks like a race with something else. It's the first time I saw that bug.

**Comment by gladkovdmitry17** [comment]
Is the issue still reproducible?

**Comment by fzago-cray** [comment]
#3392 appears to fix that one.
