### ISSUE TITLE
prov/verbs/ep_rdm: av_insert returned insertion count gets overwritten if entry not already found in hash

### ISSUE THREAD

**Issue by rhalkyard** [ofiwg/libfabric#3357]
When using RDM endpoints with Verbs, I'm seeing `fi_av_insert()` calls indicate failure when, from single-stepping through the code, they should be succeeding.

As far as I can tell, the problem is in https://github.com/ofiwg/libfabric/blob/master/prov/verbs/src/ep_rdm/verbs_av_ep_rdm.c#L227, where, if an entry is not found in the hash, memory is allocated. The return value of `ofi_memalign()` is stored in `ret` for error checking, overwriting the count of insertions that is being accumulated in that variable.

I've put together a fix in https://github.com/rhalkyard/libfabric/commit/bfce986b95b8e0c50e8fac83c62aefa1cc7c4790, but since I've not contributed before I'm not sure if matches established coding style. Let me know if it's OK, and I'll make a PR.

**Comment by gladkovdmitry17** [comment]
Seems #3358 fixes this issue. Thanks!
Can we close this issue?
