### ISSUE TITLE
prov/netdirect: Several build warnings

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#3368]
AppVeyor produces these warnings (many are duplicated) for the ND related code

C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_cntr.c(95): warning C4101: 'hr': unreferenced local variable [C:\projects\libfabric\libfabric.vcxproj]
  netdir_ep_msg.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_cq.h(172): warning C4267: 'function': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_msg.c(165): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINT32' [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_msg.c(309): warning C4267: 'initializing': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  netdir_ep_rma.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_cq.h(172): warning C4267: 'function': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_rma.c(254): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINT32' [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_rma.c(250): warning C4267: 'initializing': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_rma.c(413): warning C4311: 'type cast': pointer truncation from 'void *' to 'UINT32' [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_rma.c(409): warning C4267: 'initializing': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_ep_rma.c(451): warning C4267: 'initializing': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  netdir_ep_srx.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_cq.h(172): warning C4267: 'function': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  netdir_mr.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_mr.c(180): warning C4312: 'type cast': conversion from 'UINT32' to 'void *' of greater size [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_mr.c(288): warning C4312: 'type cast': conversion from 'UINT32' to 'void *' of greater size [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_mr.c(324): warning C4101: 'hr': unreferenced local variable [C:\projects\libfabric\libfabric.vcxproj]
  netdir_unexp.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(244): warning C4324: 'nd_ep': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_iface.h(257): warning C4324: 'nd_srx': structure was padded due to alignment specifier [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_ov.h(175): warning C4197: 'volatile PVOID': top-level volatile in cast is ignored [C:\projects\libfabric\libfabric.vcxproj]
c:\projects\libfabric\prov\netdir\src\netdir_cq.h(172): warning C4267: 'function': conversion from 'size_t' to 'ULONG', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_unexp.c(125): warning C4101: 'hr': unreferenced local variable [C:\projects\libfabric\libfabric.vcxproj]
prov\netdir\src\netdir_unexp.c(124): warning C4101: 'i': unreferenced local variable [C:\projects\libfabric\libfabric.vcxproj]
  rxd_attr.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxd_av.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxd\src\rxd_av.c(180): warning C4244: 'function': conversion from 'uint64_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxd_cntr.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxd_cq.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]

You can see more by examining the appveyor build logs.

**Comment by gladkovdmitry17** [comment]
Please, assign this issues on me. I'll take a look in near feature.
Since we're going to offload some NetDir's functionality to the RxM, some part of NetDir's code will be dropped. Because it looks more naturally to implement flow control (for instance) on the RDM level (not MSG).
