### ISSUE TITLE
prov/rxm: build warnings on windows

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#3369]
Snippet from AppVeyor logs:

prov\rxd\src\rxd_init.c(38): warning C4459: declaration of 'rxd_info' hides global declaration [C:\projects\libfabric\libfabric.vcxproj]
  c:\projects\libfabric\prov\rxd\src\rxd.h(94): note: see declaration of 'rxd_info'
  rxd_rma.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxm.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxm_attr.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_attr.c(44): warning C4245: 'initializing': conversion from 'int' to 'uint64_t', signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_attr.c(52): warning C4245: 'initializing': conversion from 'int' to 'uint64_t', signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
  rxm_conn.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_conn.c(230): warning C4389: '!=': signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
  rxm_rma.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_rma.c(75): warning C4244: 'return': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_rma.c(173): warning C4244: 'return': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_rma.c(178): warning C4244: 'return': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_rma.c(218): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxm_cq.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_cq.c(180): warning C4244: '=': conversion from 'int' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_cq.c(222): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_cq.c(256): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_cq.c(437): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_cq.c(598): warning C4018: '<': signed/unsigned mismatch [C:\projects\libfabric\libfabric.vcxproj]
  Compiling...
  rxm_domain.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxm_ep.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(164): warning C4244: '=': conversion from 'int' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(175): warning C4244: 'function': conversion from 'int' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(289): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(521): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(666): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(706): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(717): warning C4244: '=': conversion from 'int' to 'uint8_t', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(752): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(773): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
prov\rxm\src\rxm_ep.c(787): warning C4244: '=': conversion from 'ssize_t' to 'int', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]
  rxm_fabric.c
C:\projects\libfabric\include\windows/osd.h(863): warning C4244: '=': conversion from 'int' to 'float', possible loss of data [C:\projects\libfabric\libfabric.vcxproj]

**Comment by gladkovdmitry17** [comment]
Btw, assign this on me as well. I'm going to deal with RxM/Netdir stack for the MPI on Windows. And I can deal with these warning for both RxM and NetDir. Thanks!

**Comment by shefty** [comment]
I have assigned *all* future work on OFI to you, since you apparently *never* sleep!  :)

**Comment by gladkovdmitry17** [comment]
> I have assigned all future work on OFI to you, since you apparently never sleep! :)

Thanks :) Windows doesn't let me sleep
