### ISSUE TITLE
util av hash - no free list

### ISSUE THREAD

**Issue by fzago-cray** [ofiwg/libfabric#3381]
The way the hash list is created (in util_av_init), there is exactly one available slot per index, and no free entry to be linked in case of collision. And collisions happen easily when running MPICH with 32 nodes and 4 ranks per node (256 total ranks) when using verbs+rxm. This has the effect of failing the MPI test, which is not desirable.

Doubling or quadrupling UTIL_DEFAULT_AV_SIZE temporarily solves the issue (by chance.)

The current design is akin to a regular array, not a hash table.

**Comment by a-ilango** [comment]
The util av hash does have a free list (which is actually a fixed size array). If you take a look at `util_av_hash_insert` function you can see the inserted item getting appended to the free list on collisions.

Irrespective of that verbs+rxm hasn't been tested with a total of 256 ranks so there is a chance that a lot of collisions happen and we run out of space in the list. Let me try testing with more # of ranks.

**Comment by a-ilango** [comment]
Btw what's the error code that you're getting in your failing test?

**Comment by fzago-cray** [comment]
I hit 

    if (hash->free_list == UTIL_NO_ENTRY)

 in util_av_hash_insert(), and get the "failed to insert addr into hash table" error message. Then mpich falls over.

**Comment by a-ilango** [comment]
This is definitely a case of running out of space in the fixed size array. I'll work on a patch to fix this issue.

**Comment by fzago-cray** [comment]
In util_av_hash_init, I see that hash->slots, hash->total_count and hash->free_list contain 1024, which is the total number of slot allocated. And AFAICS that makes free_list pointing outside of the table, when used in util_av_hash_insert(). Do I read that right?

**Comment by a-ilango** [comment]
hash->total_count should be higher than hash->slots. The following line should ensure that:
https://github.com/ofiwg/libfabric/blob/94aedbd8f78d072ec6a1c01648ed0bc54df4b9da/prov/util/src/util_av.c#L484
and the overhead is set based on attr->count which is max(av_size, 1024):
https://github.com/ofiwg/libfabric/blob/94aedbd8f78d072ec6a1c01648ed0bc54df4b9da/prov/util/src/util_av.c#L1017

So free_list would point outside "slot space" but still within the table.

**Comment by fzago-cray** [comment]
attr->count (for MPICH) is 0, so av->count defaults to UTIL_DEFAULT_AV_SIZE. 

Since attr->count is 0, av->overhead is: 0 >> 1    -> 0.

So av->hash.total_count == av->count.

**Comment by fzago-cray** [comment]
Maybe MPICH should set attr->count, but the code in libfabric implies that this is optional. And that client works with just the verbs provider.

**Comment by a-ilango** [comment]
Oops, I missed that! av->overhead is based on attr->count which can be zero.

**Comment by shefty** [comment]
I want to add to this discussion that the util AV code is intended to allow future changes to expand it to support FI_SHARED_AV.  So the data structures need to be able to be shared between processes using shared memory.  Changes to the code should keep this in mind.
