### ISSUE TITLE
Long timeout in psm provider if no hfi device exists

### ISSUE THREAD

**Issue by StefanBruens** [ofiwg/libfabric#3393]
The psm2 provider has a check for the existence of the hfi device prior to calling psm2_ep_num_devunits
https://github.com/ofiwg/libfabric/blob/master/prov/psm2/src/psmx2_init.c#L225

Added/extended here:
https://github.com/ofiwg/libfabric/commit/31384811a549cb7c3c7f8fba6f326a1850a8a5b1
https://github.com/ofiwg/libfabric/commit/5360e8c307ceee59e3a87e66105afd1faff8c83e

For the psm provider, there is no such check:
https://github.com/ofiwg/libfabric/blame/master/prov/psm/src/psmx_init.c#L200

**Comment by j-xiong** [comment]
The PSM library for TrueScale doesn't exhibit the long delay. That's why the check is absent from the psm provider.

The psm provider can see the same delay if used over Omni-Path using the psm2-compat library. However, that's not the typical use of the psm provider -- the psm2 provider should be used in this configuration.

**Comment by StefanBruens** [comment]
I see this delay when using e.g. fi_info, and also when running the unit-tests from libmesh. In the latter case, each test is slowed down by the 15 second delay.

I have the psm2-compat library installed, as it is required by libfabric (distribution build), more specifically libpsm_ifinipath.so.1.

**Comment by j-xiong** [comment]
Yes that's a scenario that warrants a patch. I will submit a PR to port the device checking code over to the psm provider.

**Comment by StefanBruens** [comment]
I tried, but I still see the long delays:
https://github.com/ofiwg/libfabric/compare/master...StefanBruens:avoid_psm_delay

Anything missing?

**Comment by j-xiong** [comment]
Your patch missed a few bits. Use mine :)

**Comment by StefanBruens** [comment]
Mine worked too, although I screwed up when updating the library on my system. Yours works too, so issue is fixed.

Thanks for the prompt fix.
