### ISSUE TITLE
verbs: assert in fi_ibv_rdm_tagged_recvmsg

### ISSUE THREAD

**Issue by fzago-cray** [ofiwg/libfabric#3438]
With MPICH using CH4+libfabric, I hit that assert in fi_ibv_rdm_tagged_recvmsg:

    if (msg->iov_count > 1) {
            assert(0);
            return -FI_EMSGSIZE;
    }

msg->iov_count is 4. Is that a caller error, or something not implemented in libfabric?

**Comment by gladkovdmitry17** [comment]
The caller should check the `fi_info::fi_tx_attr::iov_limit` before calling the `fi_sendv/recv`v and etc with `iov_count > 1`.
Support of the `iov_count == 1` only is a limitation of the verbs provider with `FI_EP_RDM` endpoint type.

**Comment by fzago-cray** [comment]
It does. fi_rx_attr->iov_limit is 30, while fi_tx_attr->iov_limit is 1.

fi_ibv_alloc_info() is clipping one value but not the other:

    if (ep_dom->type == FI_EP_RDM) {
        fi->tx_attr->iov_limit = 1;
        fi->tx_attr->rma_iov_limit = 1;
        fi->tx_attr->inject_size = fi_ibv_gl_data.rdm.buffer_size;
    }

If I duplicate for rx_attr, then my test passes. Is that the right fix?

**Comment by gladkovdmitry17** [comment]
@fzago-cray You've found a bug. Thanks!

`fi_ibv_alloc_info()` does the following:
```
...
*(fi->rx_attr)          = (ep_dom->type == FI_EP_RDM) ?
                                   verbs_rdm_rx_attr : verbs_rx_attr;
...
ret = fi_ibv_get_device_attrs(ctx, fi);
```
but `fi_ibv_get_device_attrs` overwrites the `iov_limit` value for `fi_rx_attr` structure as follows:
```
...
info->rx_attr->iov_limit                = device_attr.max_srq_sge ?
                                             MIN(device_attr.max_sge,
                                                       device_attr.max_srq_sge) :
                                                    device_attr.max_sge;
...
```

Yes, I've proposed the right fix. It will align handling of `fi_rx_attr` with what `fi_ibv_alloc_info` does for `fi_tx_attr`.

Can I ask you to combine setting rx_attr and tx_attr to one if statement as follows:
```
if (ep_dom->type == FI_EP_RDM) {
            fi->mode        = VERBS_RDM_MODE;
            *(fi->tx_attr)  = verbs_rdm_tx_attr;
            *(fi->rx_attr) = verbs_rdm_rx_attr;
} else {
            *(fi->tx_attr)  = verbs_tx_attr;
            *(fi->rx_attr) = verbs_x_attr; 
}
```

Once again. Thank you so much for finding and fixing this!

**Comment by fzago-cray** [comment]
Thanks Dmitry. The iov_limit clue likely saved me some hours of debugging.

PR #3439.

**Comment by gladkovdmitry17** [comment]
> Thanks Dmitry. The iov_limit clue likely saved me some hours of debugging.

Thank you too. I guess it saved saved some hours for MPI users who could potentially face this :)
It should be included to the next release.
