### ISSUE TITLE
Reword fi_mr man page regarding setting of mr_mode field

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3444]
>  Unlike other mr_mode bits, if FI_MR_BASIC is set on input to fi_getinfo(), it will not be cleared by the provider.  That is, setting FI_MR_BASIC to one requests basic registration.

should probably be 

>  Unlike other mr_mode bits, if FI_MR_BASIC is set on input to fi_getinfo(), it will not be cleared by the provider.  That is, setting mr_mode to FI_MR_BASIC requests basic registration.

@shefty

**Comment by shefty** [comment]
It took 3 years, but fixed by #6300
