### ISSUE TITLE
Compile time issue raised by shared memory provider

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3446]
prov/shm/src/smr_ep.c: In function 'smr_progress_iov':
prov/shm/src/smr_ep.c:230:8: warning: implicit declaration of function 'process_vm_readv' [-Wimplicit-function-declaration]
  ret = process_vm_readv(peer_smr->pid, entry->iov,
        ^~~~~~~~~~~~~~~~
  CC       prov/shm/src/src_libfabric_la-smr_fabric.lo
  CC       prov/shm/src/src_libfabric_la-smr_init.lo
  CC       prov/shm/src/src_libfabric_la-smr_av.lo
  CCLD     src/libfabric.la
  CC       util/info.o
  CCLD     util/fi_info
src/.libs/libfabric.so: undefined reference to `process_vm_readv'

@shefty

**Comment by shefty** [comment]
@aingerson - we need to include <sys/uio.h>

**Comment by shefty** [comment]
@jswaro - Can you try adding
```
#define _GNU_SOURCE
```
immediately before the include of sys/uio.h?  @aingerson is submitting a patch with that change, but we don't see the warning on our systems.

**Comment by jswaro** [comment]
> @jswaro - Can you try adding

I did, but it had no effect on the compilation. Where does the 'process_vm_readv' function live? Is it something present in that file in sufficiently newer kernels?

**Comment by shefty** [comment]
The function is declared in sys/uio.h, supposedly.  glibc has it starting in version 2.15.  It was added to Linux 3.2, which is fairly old at this point.  But it is a Linux specific call.

**Comment by shefty** [comment]
Btw - there's a configure check for the call.  So it's odd that we can get past that check but see a warning here.
