### ISSUE TITLE
Coverity issues

### ISSUE THREAD

**Issue by gladkovdmitry17** [ofiwg/libfabric#3459]
1. Don't free resources `ofi_domain_init`. I guess more proper way is to free memory when it was allocated. Let's remove `free(util_domain)` from `ofi_domain_init`
```
72int smr_domain_open(struct fid_fabric *fabric, struct fi_info *info,
73                struct fid_domain **domain, void *context)
74{
75        int ret;
76        struct util_domain *util_domain;
77
78        ret = smr_check_info(info);
79        if (ret)
80                return ret;
81
82        util_domain = calloc(1, sizeof(*util_domain));
83        if (!util_domain)
84                return -FI_ENOMEM;
85
86        ret = ofi_domain_init(fabric, info, util_domain, context);
87        if (ret) {
88                free(util_domain);    <=============== DOUBLE FREE (already freed in the ofi_domain_util)
89                return ret;
90        }
```

2. Buffer not null terminated:
```
179 int smr_map_add(const struct fi_provider *prov, struct smr_map *map,
180                const char *name, int *id)
181{
...
189                strncpy(map->peer_addr[*id].name, name, SMR_NAME_SIZE);
```
Should we add something like `map->peer_addr[*id].name[SMR_NAME_SIZE - 1] = '\0`' or copy only `SMR_NAME_SIZE - 1` elements

3. Possible deadlock

```
252 void smr_progress_cmd(struct smr_ep *ep)
```
Acquires locks in the following sequence:
- smr_region.lock
- util_cq.cq_lock

```
430 ssize_t smr_sendmsg(struct fid_ep *ep_fid, const struct fi_msg *msg,
431                uint64_t flags)
```
Acquires locks in the following sequence:
- util_cq.cq_lock
- smr_region.lock

Seems we should acquire locks in the similar sequence (i.e. acquires all or nothing).

4. Possible null-dereferencing (if `flag & FI_SOUCE`, `service != NULL`, but `node == NULL`)
```
141i nt util_getinfo(const struct util_prov *util_prov, uint32_t version,
142                 const char *node, const char *service, uint64_t flags,
143                 const struct fi_info *hints, struct fi_info **info)
144 {
...
155        if ((flags & FI_SOURCE) && !node && !service) {
```
Shoudl it be `if ((flags & FI_SOURCE) && !node || !service) {` ? Seems we should have both `node` and `service` not NULL in case of `FI_SOURCE`

**Comment by shefty** [comment]
All coverity issues have been fixed
