### ISSUE TITLE
possible verbs API misuse in fi_ibv_rdm_conn_cleanup

### ISSUE THREAD

**Issue by fzago-cray** [ofiwg/libfabric#3467]
fi_ibv_rdm_conn_cleanup() expects rdma_destroy_qp() to set errno on error, but this is not what the function does, or it's not documented. 

The result of ibv_destroy_qp (which return 0 or -errno) is ignored by rdma_destroy_qp():

    void rdma_destroy_qp(struct rdma_cm_id *id)
    {
        ibv_destroy_qp(id->qp);
        id->qp = NULL;
        ucma_destroy_cqs(id);
    }

Is there a reason this was done that way in fi_ibv_rdm_conn_cleanup()?

Furthermore if that's how it works, then errno is not reset for the second call to rdma_destroy_qp().

**Comment by fzago-cray** [comment]
It looks like everywhere errno is set to 0 is either an error or unneeded as well.

**Comment by gladkovdmitry17** [comment]
The rdma_destroy_qp looks as follows:

```
void rdma_destroy_qp(struct rdma_cm_id *id)
{
	struct rdma_id_private *id_priv;

	id_priv = container_of(id, struct rdma_id_private, id);
	mutex_lock(&id_priv->qp_mutex);
	ib_destroy_qp(id_priv->id.qp);
	id_priv->id.qp = NULL;
	mutex_unlock(&id_priv->qp_mutex);
}
```

The both `ibv_destroy_qp` and `ib_destroy_qp` set `errno` (the driver implemented by HW vendor have to do this).


> It looks like everywhere errno is set to 0 is either an error or unneeded as well.


Do you mean it's always 0? even if case of failure?

**Comment by fzago-cray** [comment]
I copied the userspace version of rdma_destroy_qp, which is different than the kernel version which you copied.

ibv_destroy_qp returns an errno code, but doesn't set errno (at least according to the man page).

Also setting errno to 0 in these cases is pointless:

                    errno = 0;
                    if (rdma_bind_addr(cm->listener, (struct sockaddr *)&ep->my_addr)) {
                        VERBS_INFO(FI_LOG_EP_CTRL,
                                "Failed to bind cm listener to my IPoIB addr %s: %s\n",
                                my_ipoib_addr_str, strerror(errno));
                        return -FI_EOTHER;
                    }

or

                if(errno == EAGAIN) {
                        errno = 0;
                        usleep(ep->domain->rdm_cm->cm_progress_timeout);
                        return FI_SUCCESS;
                } else {

or

        errno = 0;
        rdma_freeaddrinfo(ep->rai);
        if (errno) {

**Comment by gladkovdmitry17** [comment]
> the kernel version which you copied.

Sorry, copied from the wrong repository 



> ibv_destroy_qp returns an errno code, but doesn't set errno

Yes, man page says this. But I'm going to check it. 
I agree all places that contains `errno = 0`, should be removed

**Comment by fzago-cray** [comment]
I'll make a PR for the errnos.

**Comment by gladkovdmitry17** [comment]
> I'll make a PR for the errnos.

Thanks!

**Comment by fzago-cray** [comment]
PR #3468 merged.
