### ISSUE TITLE
Socket provider IPv6 support

### ISSUE THREAD

**Issue by dmitrygx** [ofiwg/libfabric#3484]
The socket provider support only IPv4 address format - `FI_SOCKADDR_IN` address format.
This issue is a follow-up for activities related to extending the socket provider by adding `FI_SOCKADDR_IN6` address format support.
Mostly this is needed to be compliant with process managers that will support IPv6 addressing (or already there is support).

Btw, Will the tcp provider support IPv6 address format?

**Comment by vkrishna** [comment]
Yes the TCP provider is being implemented with IPV6 support.

**Comment by gladkovdmitry17** [comment]
@vkrishna Thanks for the information
