### ISSUE TITLE
SO_REUSEADDR equivalent?

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#3502]
Currently, OFI doesn't expose a setting similar to SO_REUSEADDR. Regardless, it seems like sockets, USNIC and GNI (?) providers set this value when opening sockets from within them.

Setting of this value can only be done in certain circumstances when the application has its own finalization protocol, or is willing to take the risk that some previously delayed packet shows up.

Should we expose something similar?

[https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux](https://stackoverflow.com/questions/3229860/what-is-the-meaning-of-so-reuseaddr-setsockopt-option-linux)

**Comment by shefty** [comment]
3 year old request with no application requirement pushing for the feature.
