### ISSUE TITLE
Double free issue on providers using ofi_domain_init()

### ISSUE THREAD

**Issue by epaulson10** [ofiwg/libfabric#3511]
Many of the providers that use the domain utility function ofi_domain_init() have a potential double free issue. The provider allocates the memory that is passed into this function, but the function on error will free the memory. Many of the providers are additionally freeing the memory in the event that ofi_domain_init() returns an error.

This is incredibly unlikely to happen, since the only way that function can fail is if strdup() fails, but is still bad. I propose modifying ofi_domain_init() to not free the provider allocated memory: since the provider allocated it, it makes sense for the provider to free it as well. I can make this patch if there is agreement on this.

**Comment by epaulson10** [comment]
I noticed this due to a Coverity scan on the new tcp provider.

**Comment by shefty** [comment]
Thanks - I noticed the coverity report as well, and I agree that init() should not free the memory, since it doesn't allocate it.
