### ISSUE TITLE
Example libfabric code for verbs?

### ISSUE THREAD

**Issue by songweijia** [ofiwg/libfabric#3554]
I tried fi_pingpong with sockets and it works perfectly. But it failed with verbs API.

Server: 
./fi_pingpong -v -d mlx5_0 -e msg
[debug] util/pingpong.c:313 :  * PingPong options:
[debug] util/pingpong.c:314 :   - src_port            : [0]
[debug] util/pingpong.c:315 :   - dst_addr            : [None]
[debug] util/pingpong.c:316 :   - dst_port            : [0]
[debug] util/pingpong.c:317 :   - sizes_enabled       : default size = 1024
[debug] util/pingpong.c:318 :   - iterations          : default iterations: 10000
[debug] util/pingpong.c:324 :   - domain              : mlx5_0
[debug] util/pingpong.c:2139: Selected endpoint: MSG
[debug] util/pingpong.c:496 : Initializing control messages
[debug] util/pingpong.c:461 : SERVER: waiting for connection
[debug] util/pingpong.c:472 : SERVER: connected
[debug] util/pingpong.c:519 : Control messages initialized
[debug] util/pingpong.c:1536: Connected endpoint: starting server
[debug] util/pingpong.c:1572: Connected endpoint: server started
[debug] util/pingpong.c:1584: Connected endpoint: connecting server
[debug] util/pingpong.c:1509: Connection-based endpoint: setting up connection
[debug] util/pingpong.c:649 : Syncing nodes
[debug] util/pingpong.c:680 : SERVER: syncing
[debug] util/pingpong.c:548 : receiving
[debug] util/pingpong.c:682 : SERVER: after recv / ret=2
[debug] util/pingpong.c:693 : SERVER: syncing now
[debug] util/pingpong.c:698 : SERVER: after send / ret=2
[debug] util/pingpong.c:706 : SERVER: synced
[debug] util/pingpong.c:709 : Nodes synced
[debug] util/pingpong.c:572 : Fetching local address
[debug] util/pingpong.c:586 : Sending name length
[debug] util/pingpong.c:592 : Sending name
[debug] util/pingpong.c:594 : Sent name
[debug] util/pingpong.c:649 : Syncing nodes
[debug] util/pingpong.c:680 : SERVER: syncing
[debug] util/pingpong.c:548 : receiving
[error] util/pingpong.c:558 : ctrl/read: no data or remote connection closed
[debug] util/pingpong.c:682 : SERVER: after recv / ret=-103
Segmentation fault (core dumped)

Client Side:
./fi_pingpong -v -d mlx5_0 -e msg server_address
[debug] util/pingpong.c:313 :  * PingPong options:
[debug] util/pingpong.c:314 :   - src_port            : [0]
[debug] util/pingpong.c:315 :   - dst_addr            : [compute32]
[debug] util/pingpong.c:316 :   - dst_port            : [0]
[debug] util/pingpong.c:317 :   - sizes_enabled       : default size = 1024
[debug] util/pingpong.c:318 :   - iterations          : default iterations: 10000
[debug] util/pingpong.c:324 :   - domain              : mlx5_0
[debug] util/pingpong.c:2139: Selected endpoint: MSG
[debug] util/pingpong.c:496 : Initializing control messages
[debug] util/pingpong.c:412 : CLIENT: connected
[debug] util/pingpong.c:519 : Control messages initialized
[debug] util/pingpong.c:1509: Connection-based endpoint: setting up connection
[debug] util/pingpong.c:649 : Syncing nodes
[debug] util/pingpong.c:655 : CLIENT: syncing
[debug] util/pingpong.c:657 : CLIENT: after send / ret=2
[debug] util/pingpong.c:665 : CLIENT: syncing now
[debug] util/pingpong.c:548 : receiving
[debug] util/pingpong.c:668 : CLIENT: after recv / ret=2
[debug] util/pingpong.c:678 : CLIENT: synced
[debug] util/pingpong.c:709 : Nodes synced
[debug] util/pingpong.c:604 : Receiving name length
[debug] util/pingpong.c:548 : receiving
[debug] util/pingpong.c:616 : Receiving name
[debug] util/pingpong.c:548 : receiving
[debug] util/pingpong.c:620 : Received name
fi_getinfo(): util/pingpong.c:1436, ret=-61 (No data available)
[debug] util/pingpong.c:2153: CLIENT: client_connect=KO
[debug] util/pingpong.c:1795: Freeing resources of test suite
[debug] util/pingpong.c:1826: Resources of test suite freed

It seems that the client side cannot do "getinfo()" with the 'name' information from the server side. It would be great if anybody can share a sample code that works with verbs provider.

BTW, the model of our InfiniBand/SoftRoCE NICs is Mellanox ConnectX-4 VPI. We have 19 cards connected with both 100G IB switch and 100G Ethernet switch. They work well with Mellanox verbs library.

**Comment by gladkovdmitry17** [comment]
I've checked the pingpong example over the verbs provider. It works for me.
Can I ask you to collect some useful data for me?
So if possible, please collect both server and clients console output by setting `FI_LOG_LEVEL=info` variable.
Just to make sure that the verbs provider is chosen as a provider, you may try to run this test with `-p verbs` for both client and server.

Btw, are you using libfabric's master branch?

**Comment by songweijia** [comment]
Thank you for the reply! Sure I can do what you suggested. The experiment in the first post was done with libfabric release 1.5.2. Now, I updated with the latest master code and set the FI_LOG_LEVEL=info.

I used the following commands:

server:
./fi_pingpong -v -p verbs -d mlx5_0 -e msg

client:
./fi_pingpong -v -p verbs -d mlx5_0 -e msg <server_addr>

The server complains that FI_EP_RDM supported but FI_EP_MSG requested. So I tried with rdm as well as dgram(not supported either). The log files are attached.

Interestingly, when I tried with mlx5_1 port, which is the RoCE interface on the same NIC. It works fine with the following output: 

bytes   #sent   #ack     total       time     MB/sec    usec/xfer   Mxfers/sec
64      10      =10      1.2k        0.00s     19.69       3.25       0.31
256     10      =10      5k          0.00s     78.77       3.25       0.31
1k      10      =10      20k         0.00s    243.81       4.20       0.24
4k      10      =10      80k         0.00s    655.36       6.25       0.16
64k     10      =10      1.2m        0.00s   3947.95      16.60       0.06
1m      10      =10      20m         0.00s  10538.45      99.50       0.01

I attached all of the logs for your convenience. 

[roce.client.msg.log](https://github.com/ofiwg/libfabric/files/1503692/roce.client.msg.log)
[roce.server.msg.log](https://github.com/ofiwg/libfabric/files/1503693/roce.server.msg.log)
[client.dgram.log](https://github.com/ofiwg/libfabric/files/1503698/client.dgram.log)
[client.msg.log](https://github.com/ofiwg/libfabric/files/1503699/client.msg.log)
[client.rdm.log](https://github.com/ofiwg/libfabric/files/1503700/client.rdm.log)
[server.dgram.log](https://github.com/ofiwg/libfabric/files/1503695/server.dgram.log)
[server.msg.log](https://github.com/ofiwg/libfabric/files/1503696/server.msg.log)
[server.rdm.log](https://github.com/ofiwg/libfabric/files/1503697/server.rdm.log)

**Comment by gladkovdmitry17** [comment]
Thanks for collecting all info.
Looking more deeper into the provided logs, I have to say that it's not a software problem, seems it's configuration problem. As far as configuration/installed mlx drivers are not the same for both nodes on which the `fi_pingpong` over the verbs was running.

Let's look into the logs (e.x. examine server/client.msg.log file -- but the same is applicable for the server/client.[rdm|dgram].log files):
- the server.msg.log:
we can see that provider examined all available domains and when it found the requested "mlx5_0", it just silently picked it up.
```
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1-rdm
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1-dgram
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_0-rdm
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_0-dgram
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
```
The following line proves that the provider was launched successfully on the `mlx5_0` domain (Passive EP started to listen incoming connections):
`libfabric:verbs:core:fi_ibv_pep_listen():293<info> Listening on 0.0.0.0:0`

- the client.msg.log:
Here the verbs provider didn't find `mlx5_0` domain name, because there are only `mxl5_1` and `mlx4_0` HCAs are installed.
```
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1-rdm
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_1-dgram
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_0-rdm
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx5_0-dgram
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx4_0
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx4_0-rdm
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:core:ofi_check_domain_attr():512<info> Unknown domain name
libfabric:verbs:core:ofi_check_domain_attr():513<info> Supported: mlx4_0-dgram
libfabric:verbs:core:ofi_check_domain_attr():513<info> Requested: mlx5_0
libfabric:verbs:fabric:fi_ibv_create_ep():224<info> rdma_create_ep: No such device(19)
libfabric:verbs:core:fi_ibv_get_match_infos():1402<info> Handling of the socket address fails - -19
```

Please, try to run two instances of the `fi_pingpong` (server and client) on the single node (e.x. where the `mxl5_0` is installed. I guess it should work fine)

Btw, to examine your hw/sw installation and which interfaces are detected by the libfabric, please launch `fi_info`

Thanks!

**Comment by a-ilango** [comment]
In addition to @gladkovdmitry17 's suggestions, can you also check if mlx5_0 IPoIB interface is properly configured with an IP address?

> The server complains that FI_EP_RDM supported but FI_EP_MSG requested.

This particular log is from a different (but related) provider, ofi_rxm which can be safely ignored when running a test that uses FI_EP_MSG.
```
libfabric:ofi_rxm:core:ofi_check_ep_attr():620<info> Supported: FI_EP_RDM
libfabric:ofi_rxm:core:ofi_check_ep_attr():620<info> Requested: FI_EP_MSG
```

You can also checkout https://github.com/ofiwg/fabtests/ that has several examples / tests that can run over the verbs provider.

**Comment by songweijia** [comment]
Thank you @a-ilango and @gladkovdmitry17 for the help! Enabling an IP address for the IPoIB interface solve the whole problem. Now everything works well(with both rdm and msg endpoints).

**Comment by gladkovdmitry17** [comment]
@songweijia Thanks for the conformation.
Can we close this issue?

**Comment by songweijia** [comment]
Sure, please go ahead.

**Comment by gladkovdmitry17** [comment]
@a-ilango @shefty Could close this issue, please? I don't have permissions to close this
