### ISSUE TITLE
prov/gni fi_cq_read does not receive source cq from fi_readv

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#3583]
In the test case that fails, I am doing a loop of 1000 transfers using the fi_readv api.  After each fi_readv call, I process the source cq using the fi_cq_read api with count value of 1.

This test case uses 2 ranks.  One of the ranks will send 1000 transfers and receive 1000 cq events.  The other rank will hang in the fi_cq_read call waiting for a cq event.

The more debug information I enable the more likely all of the cqs will be received.

My test case starts printing debug information on the 850 transfer.

The test case hangs the majority of the time.  But you might only see debug information from one of the ranks.  If this is the case, rerun the test until you see debug information from both ranks.

**Comment by tonyzinger** [comment]
I have the test case on jupiter in the directory: /home/users/ajz/issue_3583

**Comment by hppritcha** [comment]
@tonyzinger are you still observing this problem?  If so, could you post the test here?

**Comment by hppritcha** [comment]
I'm not seeing a problem running this test case on jupiter using libfabric configured with the following options:
```
./configure --prefix=/cray/css/users/n17276/libfabric/install --with-kdreg=/home/users/n17276/kdreg  --disable-verbs
```

**Comment by tonyzinger** [comment]
I built libfabric from the tip of github.  I then used these libfabric libraries from my build with the latest version of my test and I did not see this problem.

So this issue can be closed.
