### ISSUE TITLE
prov/psm2: Provider doesn't support 1.5 mr_mode bits correctly

### ISSUE THREAD

**Issue by epaulson10** [ofiwg/libfabric#3589]
I have an application that tries to be able to run over both psm2 and verbs, and thus it supports the following mr_mode bits: `FI_MR_LOCAL | FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY`.

My application sets these bits and, based on what bits are cleared after fi_getinfo(), sets a global variable to either do the Mr. Scalable-style registration of the entire virtual address space or to fall back to a memory-registration caching scheme.

I'm finding that psm2 does not handle setting the above bits, failing with this error message: 
`libfabric:psm2:domain:psmx2_domain_open():568<info> mr_mode mismatch: expecting FI_MR_BASIC`

What I would expect the provider to do in this case is to clear all of these bits because it doesn't require them.

**Comment by epaulson10** [comment]
You know what, this might be the result of me using both an MPI that uses OFI plus my own OFI application.

**Comment by epaulson10** [comment]
@j-xiong I just confirmed this is because the MPI I was using was using OFI/psm2 for its communication. Do you know if there has been or will be a fix to psm2 to allow you to use it from multiple libraries?

**Comment by j-xiong** [comment]
What you want is the ability to open separate domains. Currently although fi_domain() can be called multiple times, the same domain object is returned.

This feature is planned, but it will be a while before it will be worked on.
