### ISSUE TITLE
shared libs: master uses older shared lib version number than branch

### ISSUE THREAD

**Issue by chuckcranor** [ofiwg/libfabric#3628]
If you compile libfabric on the v1.5.x branch with shared libs enabled, it installs as:

$prefix/lib/libfabric.so.1.9.3

if you switch to master from a v1.5.x branch install, and recompile/install it installs as:

$prefix/lib/libfabric.so.1.9.0

But because the old 1.9.3 lib is present in the $prefix/lib directory, the install does
not update the $prefix/lib/libfabric.so.1 symbolic link, so it still points to the old v1.5.x
compile and the new 'master' compiled library is ignored.

example:
```
mkdir -p /tmp/fab/src
git clone https://github.com/ofiwg/libfabric.git
cd libfabric
git checkout v1.5.x
./autogen.sh
./configure --prefix=/tmp/fab --enable-shared
make install
```

produces:
```
% ls -l /tmp/fab/lib/libf*
-rw-r--r-- 1 chuck TableFS 797010 Dec 16 15:24 /tmp/fab/lib/libfabric.a
-rwxr-xr-x 1 chuck TableFS    949 Dec 16 15:24 /tmp/fab/lib/libfabric.la
lrwxrwxrwx 1 chuck TableFS     18 Dec 16 15:24 /tmp/fab/lib/libfabric.so -> libfabric.so.1.9.3
lrwxrwxrwx 1 chuck TableFS     18 Dec 16 15:24 /tmp/fab/lib/libfabric.so.1 -> libfabric.so.1.9.3
-rwxr-xr-x 1 chuck TableFS 487783 Dec 16 15:24 /tmp/fab/lib/libfabric.so.1.9.3
```

now if you switch to master (which should a version number newer than 1.9.3):
```
make clean
git checkout master
./autogen.sh
./configure --prefix=/tmp/fab --enable-shared
make install
```

you get:
```
% ls -l /tmp/fab/lib/libf*
-rw-r--r-- 1 chuck TableFS 6968462 Dec 16 15:31 /tmp/fab/lib/libfabric.a
-rwxr-xr-x 1 chuck TableFS     949 Dec 16 15:31 /tmp/fab/lib/libfabric.la
lrwxrwxrwx 1 chuck TableFS      18 Dec 16 15:31 /tmp/fab/lib/libfabric.so -> libfabric.so.1.9.0
lrwxrwxrwx 1 chuck TableFS      18 Dec 16 15:31 /tmp/fab/lib/libfabric.so.1 -> libfabric.so.1.9.3
-rwxr-xr-x 1 chuck TableFS 3431169 Dec 16 15:31 /tmp/fab/lib/libfabric.so.1.9.0
-rwxr-xr-x 1 chuck TableFS  487783 Dec 16 15:24 /tmp/fab/lib/libfabric.so.1.9.3
```

notice the symlinks: libfabric.so points to 1.9.0 but libfabric.so.1 points to the older 1.9.3.
I don't think that should ever happen (all the symlinks should point at the same file, right?)

Looking at the output of "ldd" ... the important link is "libfabric.so.1":
```
% ldd /tmp/fab/bin/fi_info
        linux-vdso.so.1 =>  (0x00007fff74bfe000)
        libfabric.so.1 => /tmp/fab/lib/libfabric.so.1 (0x00007fe954bd6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe954807000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe9545fe000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe9543e0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe9541dc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe954e3b000)
```

So running "fi_info" after installing master is still going to use the older 1.9.3 file from the previous install on the 1.5.x branch (even though you just installed master, which is what you'd expect it to use).

**Comment by jsquyres** [comment]
I confirm that you are correct.

This is mainly because we really don't update the shared library version numbers until right before release.  The v1.5.x series is the latest set of releases, and therefore has the latest shared library version number (in `Makefile.am` on the v1.5.x branch, it's `--version-info 10:3:9`; on master, it's `--version-info 10:0:9`).  It hasn't been updated on master yet because we don't know what it will be for the v1.6.x series.

Especially since master/v1.6.x hasn't been released yet, your best bet is to treat master as a development branch and not install it into the same location as your production releases.

**Comment by chuckcranor** [comment]
This isn't getting installed in a production location.  We've been tracking down a Cray GNI problem that shows differently in 1.5.x and master, so as part of our debugging we've been switching between the branch and master (or at least we've been trying to, but this unexpected bug prevented us from getting the correct library when switching from 1.5.x to master until we figured out what the libfabric.so install was doing wrong).

**Comment by a-ilango** [comment]
@chuckcranor Keeping the installation directory of v1.5.x and master different should fix this problem. It seems in your case it's the same and that's why the libfabric.so.1 symlink might point to the library with wrong version.
