### ISSUE TITLE
TX only endpoints?

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#3682]
Is there a way to create TX only endpoints?  Setting "rx_attr->caps" or "ep_attr->rx_ctx_cnt" to 0 only means default value are to be used.

TX only endpoints can be useful to save resource for certain applications, especially for providers that can support shared TX context but not shared RX context.

**Comment by shefty** [comment]
The app should be able to request this by adding FI_SEND or FI_WRITE to the info->caps.  E.g. info->caps = FI_SEND | FI_MSG requests the ability to only send messages.  Leaving the tx/rx_attr->caps = 0 indicates that the info->caps are used instead.
