### ISSUE TITLE
prov/gni provider fails to create EP

### ISSUE THREAD

**Issue by gladkovdmitry17** [ofiwg/libfabric#3695]
fi_endpoint() fails with the following output:

```
libfabric:gni:ep_ctrl:_gnix_cm_nic_alloc():649<warn> [182539:1] gnix_nic_alloc returned Permission denied
libfabric:gni:ep_ctrl:_gnix_ep_nic_init():2187<warn> [182539:1] _gnix_cm_nic_alloc returned Permission denied
libfabric:gni:ep_ctrl:gnix_ep_open():2402<warn> [182539:1] _gnix_ep_nic_init returned -13
```

Here is a [log file](https://github.com/ofiwg/libfabric/files/1640145/mpirun_fi_debug.log) that is collected with `FI_LOG_LEVEL=warn`.

**Comment by hppritcha** [comment]
How are you running this test?  It looks like you're not running on a compute node or if you are, you don't have the right RDMA credentials.

**Comment by hppritcha** [comment]
closing this issue.  likely user error.  you can't run a GNI provider test with either
- using the job launcher
- using DRC (which requires extra work in your application)
