### ISSUE TITLE
prov/gni: failure in send/recv alignment test

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#3726]
[----] prov/gni/test/rdm_sr.c:691: Assertion failed: Bad recv count
[FAIL] rdm_sr::send_alignment: (0.00s)

This occurred with git hash 3e1303d853ad6e88700a90537d6f0aa4e430b6e2, with the debug build.

**Comment by jswaro** [comment]
@hppritcha  In case you are interested.

**Comment by hppritcha** [comment]
I'm not seeing this sha it in my up to date workarea:

hpp@cori12:~/libfabric> (master)git show 3e1303d
fatal: ambiguous argument '3e1303d': unknown revision or path not in the working tree.

I'm also unable to reproduce this error.

**Comment by hppritcha** [comment]
not able to reproduce on master.  closing.
