### ISSUE TITLE
fi_tag_bits() and fi_tag_format() work incorrectly?

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#3751]
These two functions may be working incorrectly:

```
uint64_t fi_tag_bits(uint64_t mem_tag_format)
{
        return UINT64_MAX >> (ffsll(htonll(mem_tag_format)) -1);
}
 
uint64_t fi_tag_format(uint64_t tag_bits)
{
        return FI_TAG_GENERIC >> (ffsll(htonll(tag_bits)) - 1);
}
```

My intuitive understanding of the intention of algorithm is that the `ffsll(htonll(x))` part tries to find the location of the most significant "1". However, the function `ffsll()` only finds the least significant "1". The call to `htonll()` swaps bytes on little endian machines, but that doesn't affect bits order within the byte, and it has no effect on big endian machines.

As an example, if I reserve 4 top most bits from a 64-bit tag to leave 60-bit effective tag, the resulting "tag_bits" should be `0x0FFFFFFFFFFFFFFFULL`, and the "tag_format" should be `0x0AAAAAAAAAAAAAAAULL`. However, these two functions don't convert as expected:

```
fi_tag_bits(0x0AAAAAAAAAAAAAAAULL) = 0x7FFFFFFFFFFFFFFFULL
fi_tag_format(0x0FFFFFFFFFFFFFFFULL) = 0xAAAAAAAAAAAAAAAAULL
```

**Comment by j-xiong** [comment]
@shefty

**Comment by shefty** [comment]
I think you're correct.  This looks wrong.
