### ISSUE TITLE
bit polarity of "ignore" in tagged operations

### ISSUE THREAD

**Issue by rfaucett** [ofiwg/libfabric#383]
Why is the bit polarity of "ignore" the way it is?  Seems more logical and intuitive to be "mask" where "1" in mask means "this bit matters" instead of 1 meaning "ignore this bit".  As expected, I see a lot of "~ignore" in the PSM code to deal with this, and I would expect a lot of "ignore = ~mask" in apps also.  

What's the rationale for this?

**Comment by shefty** [comment]
Unless there's a strong argument for this change, I'm closing the issue at this point.  Looking at the apps, they seem to want 'ignore' syntax, which has the added benefit (IMO) of allowing 0 to indicate a full match.
