### ISSUE TITLE
prov/usnic: CQ FD handling is broken

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#3865]
Haven't been able to track this all the way to the source of the problem, but it looks like this happens with newer versions of `usnic_verbs` as a result of incompatibilities between `usnic_direct` and `usnic_verbs`.

**Comment by shefty** [comment]
Nearly all of the API is asynchronous, soooooo.... are you saying that everything is broken?

**Comment by bturrubiates** [comment]
> Nearly all of the API is asynchronous, soooooo.... are you saying that everything is broken?

Oops. Anything that requires waiting on a CQ FD. So `fi_cq_sread` and waitsets and things like that.

**Comment by bturrubiates** [comment]
@shefty we didn't realize at first because we had been testing with our Open MPI BTL which only uses polling.

**Comment by bturrubiates** [comment]
This turned out to be a bug in a recent commit on the `usnic_verbs` kernel driver. No fixes are necessary for our provider.
