### ISSUE TITLE
New libpsm2 requirements in 1.6?

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#3912]
I am trying to update from libfabric-1.5.1 to 1.6.0 on a system with OmniPath.
While I had no problem building the psm2 provider in 1.5.1, configure in 1.6.0 complains:

```
[...]
configure: *** Configuring psm2 provider
checking psm2.h usability... yes
checking psm2.h presence... yes
checking for psm2.h... yes
looking for library without search path
checking for psm2_am_register_handlers_2 in -lpsm2... no
configure: recheck psm2 with reduced feature set.
checking psm2.h usability... yes
checking psm2.h presence... yes
checking for psm2.h... yes
looking for library without search path
checking for psm2_ep_epid_lookup2 in -lpsm2... no
configure: psm2 provider: disabled
[...]
```

I see nothing in the NEWS.md indicating a minimum supported version of libpsm2.
Assuming the failure I observed is the expected behavior, can somebody please let me know the minimum libpsm2?

The system I am using (not managing) has the following:
```
$ rpm -qi libpsm2
Name        : libpsm2
Version     : 10.2.175
Release     : 1
Architecture: x86_64
Install Date: Wed 23 Aug 2017 12:37:12 PM PDT
Group       : Unspecified
Size        : 544505
License     : BSD or GPLv2
Signature   : (none)
Source RPM  : libpsm2-10.2.175-1.src.rpm
Build Date  : Tue 20 Jun 2017 11:21:12 AM PDT
Build Host  : ph-bld-node-11.ph.intel.com
Relocations : (not relocatable)
URL         : https://github.com/01org/opa-psm2/
Summary     : Intel PSM2 Libraries
Description :
The PSM2 Messaging API, or PSM2 API, is the low-level
user-level communications interface for the Intel(R) OPA
family of products. PSM2 users are enabled with mechanisms
necessary to implement higher level communications
interfaces in parallel environments.
```

-Paul

**Comment by shefty** [comment]
@j-xiong - Do you know the new minimum requirement?

**Comment by j-xiong** [comment]
10.2.235 and later.

**Comment by epaulson10** [comment]
@PHHargrove There is a new configure flag where you can specify libpsm2's source code and it will be compiled directly into the provider, which can be useful if you don't want to try to get whoever owns that system to upgrade.

--with-psm2-src=<some dir>

**Comment by shefty** [comment]
I'm adding a note to the news, or would putting this in the man page be better?
Btw, what sort of bizarre numbering scheme are they using?  10.2.235?

**Comment by j-xiong** [comment]
I think news is a better place than man page.

Yes, the PSM2 numbering scheme is not intuitive. The first and second numbers are related to IFS version (but not the same). The third number is probably increased with each commit.

**Comment by PHHargrove** [comment]
@j-xiong 
Is`https://github.com/01org/opa-psm2/`  the proper place to get the source code for an up-to-date version?

**Comment by j-xiong** [comment]
@PHHargrove yes.
