### ISSUE TITLE
Fix license typos

### ISSUE THREAD

**Issue by pombredanne** [ofiwg/libfabric#3934]
There are a few typos that sneaked in the license notices of some files. Since the BSD-2-clause license with an MIT warranty disclaimer is already a rather odd license, it would make sense to fix these to avoid other variations.

Some files include
- `waitailable` instead of `available` in 
  - prov/psm/src/psmx_wait.c
  - prov/psm2/src/psmx2_wait.c
- `AWV` instead of `AND` in  
  - prov/gni/test/run_gnitest
  - util/info.c
  - util/pingpong.c
  - util/strerror.c
  - util/windows/getopt/getopt.cpp

I will  accumulate more here and submit a patch at once.
And for context, this is based on a review of licensing I am doing for this library as well as rdma-core and the corresponding code in the kernel following this discussion thread https://www.spinics.net/lists/linux-rdma/index.html#61713 started by @jgunthorpe

**Comment by pombredanne** [comment]
In rdma-core-master/providers/rxe/rxe_queue.h `fileA`

**Comment by pombredanne** [comment]
in libfabric-master/prov/gni/src/gnix_xpmem.c a missing c in `opyright notice`

**Comment by pombredanne** [comment]
* in openib/libfabric-master/include/ofi_atomic.h: *      - `Redistibutions` of source code must retain the above
* in the kernel 
  * linux-4.13/drivers/infiniband/sw/rxe/rxe_queue.c: *	- Redistributions in binary form must `retailuce` the above
  * linux-4.16-rc4/drivers/infiniband/sw/rxe/rxe_queue.c: *	- Redistributions in binary form must `retailuce` the above


* in libfabric-master/prov/psm/src/psmx_wait.c: * This software is `waitailable` to you under a choice of one of two
* in libfabric-master/prov/psm/src/psmx_wait.c: * General Public License (GPL) Version 2, `waitailable` from the file
* in libfabric-master/prov/psm2/src/psmx2_wait.c: * This software is `waitailable` to you under a choice of one of two
* in libfabric-master/prov/psm2/src/psmx2_wait.c: * General Public License (GPL) Version 2, `waitailable` from the file

**Comment by pombredanne** [comment]
Here we have many many typos:
* linux-4.13/drivers/infiniband/core/cm_msgs.h: *     withmodification, are permitted provided that the following
* linux-4.16-rc4/drivers/infiniband/core/cm_msgs.h: *     withmodification, are permitted provided that the following

**Comment by pombredanne** [comment]
More `AWV` instead of `AND`

dma-core-master/ibacm/src/acm_util.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/acm.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/libacm.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/libacm.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/parse.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/acme.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/src/acm_util.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/linux/osd.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/include/acm_mad.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/include/infiniband/acm_prov.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/include/infiniband/acm.h: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/ibacm/prov/acmp/src/acmp.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/riostream.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rdma_server.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rstream.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rdma_client.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rcopy.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rdma_xserver.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/rdma_xclient.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/udpong.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
rdma-core-master/librdmacm/examples/cmtime.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
libfabric-master/util/pingpong.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
libfabric-master/util/windows/getopt/getopt.cpp:* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
libfabric-master/util/strerror.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
libfabric-master/util/info.c: * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV
libfabric-master/prov/gni/test/run_gnitest:# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AWV

**Comment by shefty** [comment]
PRs have been opened to fix the libfabric and fabtests typos.  Note that rdma-core is a separate project that apparently doesn't allow the reporting of issues directly to github.  No one tracking rdma-core will look into this project for issues against the core.

This issue will automatically close once the libfabric changes are merged.

**Comment by pombredanne** [comment]
@shefty Thanks ++ for following up on this as I raise the issue but did not had the time to work on a proper patch yet!
I guess that for rdma-core, the way is a proper patch to the linux-rdma mailing list?

**Comment by pombredanne** [comment]
Note that this will be the way for anything related to Linux too. I tried to cast a wide net on the specific "openib/openfabrics" licenses and where they are used primarily here, in the kernel and rdma.

**Comment by pombredanne** [comment]
@shefty there could be a few similar issues in the other ofiwg repos. I will try to run some scans on these too and report the issues where appropriate

**Comment by pombredanne** [comment]
@shefty Actually https://github.com/linux-rdma/rdma-core/pulls is accepting PRs too

**Comment by shefty** [comment]
The best option for rdma-core (user or kernel) is to post to the linux-rdma mailing list.  You can open a PR for the user space, you just can't open an issue to track it.
