### ISSUE TITLE
msvc++ designated initializer compile issue

### ISSUE THREAD

**Issue by ct-clmsn** [ofiwg/libfabric#3935]
compilation with msvc++ /std:c++17 breaks due to the use of [gcc style designated initializers](https://gcc.gnu.org/onlinedocs/gcc-4.1.2/gcc/Designated-Inits.html). More specifically, the following style of struct initializer `struct foo f = { .d = 4 };` isn't something the msvc++ compiler supports. An example in libfabric of this issue is in the following file: [fi_domain.h](https://github.com/ofiwg/libfabric/blob/a42e642a23a7705f12e647bccb4f9bdd18641382/include/rdma/fi_domain.h#L321). The following modification fixes this compile issue: 
```
	struct fi_mr_raw_attr attr = {
		flags = flags,
		base_addr = base_addr,
		raw_key = raw_key,
		key_size = key_size
	};
```
This fix, if applied across the project, should make libfabric compile clean with msvc++. Not sure if this a C/C++ issue, gcc-extension issue, or an msvc++ issue.

Also, libfabric compiles clean when built against [hermes](https://github.com/Microsoft/hermes) and it's dependencies mala and ndv2lib. mala and ndv2lib are distributed with hermes.

**Comment by shefty** [comment]
We can update the exported headers to compile cleanly.  I doubt there are too many places where this is used in the headers.

**Comment by ct-clmsn** [comment]
@shefty thanks!

**Comment by shefty** [comment]
@ct-clmsn - can you tell me if this code in fi_mr_refresh() compiles?
```
struct fi_mr_modify = {0};
```

**Comment by ct-clmsn** [comment]
@shefty the code sample was missing an identifier (variable name)

```
struct fi_mr_modify mod = {0};
```
that line compiles well with msvc++ /std:c++17

**Comment by shefty** [comment]
Okay, then I think #3937 fixed this (just merged).  I didn't see any other problems in the header files based on visual inspection.  Let me know if you hit other issues.

**Comment by ct-clmsn** [comment]
@shefty awesome! thanks!
