### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by ct-clmsn** [ofiwg/libfabric#3936]
[vcpkg](https://github.com/Microsoft/vcpkg) is similar to bsd-ports or Gentoo's portage system for windows; provides a nice interface for distributing software.

**Comment by shefty** [comment]
We don't actually create a package for windows, but should look at doing this.

**Comment by shefty** [comment]
The ND provider needs the ND headers.  I've thought about including those headers in the git tree (mostly for convenience), but I'm not sure if we want to add Microsoft header files directly into the tree.  I don't know what license those files are under for including them as part of our source tree or package.  I'm not familiar with mala (other than google search telling me to look at https://github.com/Microsoft/mala).  Why would that be needed?

**Comment by gladkovdmitry17** [comment]
@ct-clmsn Yes, this is nice point. I know about vcpkg tool.
I tried to find the information how to do hermes as a vcpkg dependency for msvc++, but I didn't find any information about that :(
Should it be updated in the VS project file?

**Comment by ct-clmsn** [comment]
@shefty [mala](https://github.com/Microsoft/mala) and [GSL](https://github.com/Microsoft/GSL) are dependencies pulled from git by hermes ([file](https://github.com/Microsoft/hermes/blob/718643927ff44d8db18d3a59b12840d13ad39665/GetDependencies.bat)). mala strikes me as a "boost::io_service" tool - software that manages asynchrony. GSL is a support header file library. I suspect getting the ND headers is all that's necessary. My attempt to build libfabric was successful b/c hermes packaged ND nicely into github. So, my request for hermes is really a request for ND and an easy way to download ND.

**Comment by ct-clmsn** [comment]
@gladkovdmitry17 yep. hermes provides ND and ND is *the* libfabric dependency. maybe hermes isn't worth getting into vcpkg if there's an easier way to get ND into vcpkg?

**Comment by shefty** [comment]
I believe vcpkg support was enabled.  If not, we can revisit.  To date, there has not been huge demand for a windows package.
