### ISSUE TITLE
RxM AUTO Progress engine

### ISSUE THREAD

**Issue by mohanasudhan** [ofiwg/libfabric#4048]
This is mostly a question to the community, rather an issue. Correct me if this is wrong place for such questions

I am currently digging in RxM utility provider to understand more on how it implements FI_PROGRESS_AUTO. As i dig in, I see RxM doesn't use separate thread for its progress, It implements fi_cq_sread and some tweak large message w.r.t progress (Refer https://github.com/ofiwg/libfabric/commit/b6f7a007587d9f1a9bde21d0c3eace55918459a1 https://github.com/ofiwg/libfabric/commit/2faac2b505ea240e8936cef76b090f30dee51ab3 ) when enabling data_progress as FI_PROGRESS_AUTO. 

As per my understanding this does not adhere to the definition stated here https://ofiwg.github.io/libfabric/master/man/fi_domain.3.html

Copying for quick access: 
FI_PROGRESS_AUTO
This progress model indicates that the provider will make **forward progress on an asynchronous operation without further intervention by the application**. 

In the above case, applications has to call fi_cq_sread / poll on fi_cq_read (which is a manual progress) for provider to progress. 

Please let me know if i miss any thing.

**Comment by shefty** [comment]
I'm not certain if rxm adheres to auto-progress, but the act of using cq read to complete an operation doesn't necessarily indicate manual progress.  What matters is if the action is something that an application would need to do anyway -- i.e. will the app hang waiting for an operation to complete.  RxM mostly targets verbs devices, which offload transport functionality.  So RMA and message transfers will proceed without application involvement.

For large transfers, on the receiving side, it's expected that an application will need to read the CQ to detect when a message has arrived.  The interception of that call to process a rendezvous message, followed by the initiation of an RMA read to retrieve the data, is permissible.  The message latency may not be what's desired, but the behavior could still be correct.

Manual progress as a requirement shows up most easily with RMA, where the receiving side isn't expecting to take any action.  In this case, not reading the CQ will result in the RMA never completing.

Is there a specific call sequence that you're concerned would break an app that is assuming auto-progress, but rxm implements somewhat manually?

Tagging @a-ilango
