### ISSUE TITLE
util/av: Scalability issue

### ISSUE THREAD

**Issue by dmitrygx** [ofiwg/libfabric#4066]
When running ofi_rxm provider with MPICH/CH4 (and CH3 as well) for overall number of ranks > 1024, it leads to ABORT signal for 1025th rank and so on.
So, both CH3 and CH4 doesn't set `fi_av_attr::count` value to optimize handling of addresses at the provider level. This is just expected value (and OFI doesn't require to set it) of addresses that will be inserted.
In this case, util/av uses default value of address limit (1024).

The first idea that comes to me is to implement something like libfabric has for utility buffer pool functionality (i.e. having a linked lists of AV tables).
Btw, we can use utility buf pool to generate internal AV entries and use pointer to buf pool entry as a `fi_addr` value that is returned to app. It similar to AV_MAP.

What do you think to add environment variable to increase this value ? Yes, this is weird, but it would be good to have in 1.6.1 to allow customers run RxM at a large scale.
Please, check this solution in my repo - https://github.com/gladkovdmitry17/libfabric/tree/av. Setting this environment variable fixes scalability issue. If it is OK to have it in 1.6.1 as a workaround, I prepare PR to include this.

It seems RxD should have the same issue as soon it uses the util/av functionality

@shefty @a-ilango @aingerson  @sayantansur @michael-chuvelev

**Comment by gladkovdmitry17** [comment]
@jsquyres Thanks. Hmm, good question.

It can be set when initializing OFI netmod without any problems.
But how much this should value be? `MPI_COMM_WORLD` size?
But when initializing OFI netmod, we don't know about spawned processes and therefore we don't have a chance to predict the proper `fi_av_attr::count` value

**Comment by jsquyres** [comment]
Are the issues:

1. The AV size is fixed and cannot be grown after creation.  Hence, how would you know what size to use?
1. Does MPICH need to keep AV entries in the table?  Or are connections made, and then AV entries can be removed?  (this may be a naive question, but my transport only supports DGRAM, so I am not wise in the ways of RDM and MSG...)

**Comment by shefty** [comment]
So, this hits me as an application problem, but adding new env variables seems like the least sucky solution to support the broken apps.  Do we need each provider to have this variable, or could we use a single library wide value, that providers can support or not?

**Comment by sayantansur** [comment]
I agree this is an application problem. MPI should be able to provide the 'count'. @gladkovdmitry17 I have a design update pending to the MPICH team to avoid them using the AV in a boundless fashion. I want intercommunicators to be their own AV and intercomm merge to result in creation of a new AV. This makes AVs static.

BTW, even in the presence of spawn, they could technically provide the value of MPI_UNIVERSE_SIZE. Although this value can be really large, so providers will need some internal way of handling that.

**Comment by shefty** [comment]
Independent of the reason, the proposed changes allow using an environment variable to override a hard-coded value.  That seems reasonable to me and does align with other use cases for environment variables

**Comment by jsquyres** [comment]
So I guess that's the crux of it: fi_av(3) says that count "Indicates the expected number of addresses that will be inserted into the AV. The provider uses this to optimize resource allocations."  It does *not* state that it is a maximum number of entries in the AV.

I.e., is our documentation of this interface not sufficient, and MPICH (and apparently Open MPI) reasonable in their assumptions that AV sizes are not bounded?

**Comment by shefty** [comment]
I don't think it's safe to assume that an AV will grow or will not grow.  A hardware based AV, or even a software based one that might make use of a hash table for FI_SOURCE, could be restricted.  An AV that is shared between processes may also have a fixed maximum.

At the same time, the av::count is not defined as a maximum, because it may not be.  A provider could grow the AV, and I didn't want to disallow that.

At best, we could say that av::count is a (mostly) guaranteed minimum number of addresses that can be inserted into the AV.  I don't think that we can realistically test for other behavior.

**Comment by jsquyres** [comment]
I hear what you're saying, but it feels weird to have to say:

1. If you run with <=X MPI processes, everything works fine out of the box.
1. If you run with >X MPI processes, you have to set this magic environment variable to a magic value.

(especially if X is a fairly low number, like 1024)

**Comment by shefty** [comment]
Well, that's saying the truth, even if it does feel weird in today's political spectrum.  :)  I guess the more complete truth is:

1. If MPI doesn't specify X, then the provider developer pick a hard-coded value.
2. If you run with <= X ranks, things work.
3. If you run with > X ranks, it doesn't work.
4. If we add this magic value, we can adjust the value of X.

Along this line, I just had a side conversation about the possibility of allowing an EP to be associated with multiple AVs.  It sounds like this might work well in more dynamic use cases.

**Comment by gladkovdmitry17** [comment]
> @gladkovdmitry17 I have a design update pending to the MPICH team to avoid them using the AV in a boundless fashion. I want intercommunicators to be their own AV and intercomm merge to result in creation of a new AV. This makes AVs static.

@sayantansur Do this mean that each communicator will contain its own AV?
But we still need to maintain AV for MPI_COMM_WORLD communicator. And we have to insert the addresses of spawned processes into AV of MPI_COMM_WORLD, i.e. we still have AV that should be expand dynamically.

**Comment by sayantansur** [comment]
@gladkovdmitry17 Ideally, we don't want AVs to expand dynamically. That doesn't work very well with things like "instant-on" schemes. i.e. you can do that from MPI if you must, but you might lose out on system/provider level optimizations. I was talking with Sean to have the libfabric APIs allow dynamic binding of EPs to multiple AVs. Therefore every MPI_COMM_WORLD could be its own static AV.

**Comment by gladkovdmitry17** [comment]
@sayantansur I see. Thanks for the explanation. OFI AVs are mapped very well to MPI communicators in that case.

**Comment by shefty** [comment]
The AV size may be controlled via environment variable.  The util code will also dynamically grow the AV size, because the apps are horrible about setting this correctly (or even knowing what to set the size to).  There's no guarantee that providers with HW based AVs will be able to make the same adjustment.
