### ISSUE TITLE
prov/sockets: provider always return FI_MR_UNSPEC with new mr_mode bits.

### ISSUE THREAD

**Issue by thananon** [ofiwg/libfabric#4086]
In sockets provider: 

sock_ep.c:
```c
1473     if (FI_VERSION_LT(api_version, FI_VERSION(1, 5))) {
1474         if (attr->mr_mode == FI_MR_UNSPEC)
1475             attr->mr_mode = FI_MR_SCALABLE;
1476     } else {
1477         if ((attr->mr_mode != FI_MR_BASIC) &&
1478             (attr->mr_mode != FI_MR_SCALABLE))
1479             attr->mr_mode = 0;
1480     } 
```
From this part of code, if the new mr_mode flags are given, the provider will just blindly return 0 (`FI_MR_UNSPEC`). This creates problems later as the user will use the flags to register memory with `ofi_mr_map_insert()` which calculates the address offset based on the flag.  (and with the wrong offset, we read the wrong address on later stages)

```c
 59 int ofi_mr_map_insert(struct ofi_mr_map *map, const struct fi_mr_attr *attr,
 60               uint64_t *key, void *context)
 61 {
 62     struct fi_mr_attr *item;
 63
 64     item = dup_mr_attr(attr);
 65     if (!item)
 66         return -FI_ENOMEM;
 67
 68     if (!(map->mode & FI_MR_VIRT_ADDR))
 69         item->offset = (uintptr_t) attr->mr_iov[0].iov_base;
 70
 71     if (!(map->mode & FI_MR_PROV_KEY)) {
 72         if (rbtFind(map->rbtree, &item->requested_key)) {
 73             free(item);
 74             return -FI_ENOKEY;
 75         }
 76     } else {
 77         item->requested_key = map->key++;
 78     }
 79
 80     rbtInsert(map->rbtree, &item->requested_key, item);
 81     *key = item->requested_key;
 82     item->context = context;
 83
 84     return 0;
 85 }
```
Should provider return the new flags instead?

**Comment by shefty** [comment]
The new mr_mode are flags, so 0 is valid.  Prior to 1.5, mr_mode was an enum (UNSPEC, BASIC, SCALABLE).  A new mr_mode = 0 is basically the older version of SCALABLE.  The address is 0-based, the user selects the key.

**Comment by thananon** [comment]
Thank you for the answer Sean.

I think I know what happened. In my code, everything on the registration is fine.
```
161             ret = ofi_mr_map_insert(&dom->mr_map, attr, &key, _mr);
(gdb) p *attr
$5 = {mr_iov = 0x7ffdfd53c9e0, iov_count = 1, access = 12288, offset = 0, requested_key = 1,
  context = 0x0, auth_key_size = 4196800,
```

Without FI_MR_VIRT_ADDR, `ofi_mr_map_insert()` stores the offset as the address.
```c
68     if (!(map->mode & FI_MR_VIRT_ADDR))
 69         item->offset = (uintptr_t) attr->mr_iov[0].iov_base;
```

So when I retrieve it, the offset is the address.
```
111             rbtKeyValue(map->rbtree, itr, &key_ptr, (void **) &attr);
(gdb)
112             assert(attr);
(gdb) p *attr
$6 = {mr_iov = 0xd79f50, iov_count = 1, access = 12288, offset = 14135296, requested_key = 1,
  context = 0xd7a3e0, auth_key_size = 4196800,
  auth_key = 0x7f0d3277f0c0 <_dl_runtime_resolve+80> "I\211\303f\017\032\\$0f\017\032T$ f\017\032L$\020f\017\032\004$L\213L$pL\213D$hH\213|$`H\213t$XH\213T$PH\213L$HH\213D$@H\201Ĉ"}

(gdb) p (void*)attr->offset
$9 = (void *) 0xd7b000

(gdb) p *attr->mr_iov
$8 = {iov_base = 0xd7b000, iov_len = 4096}

```
And `ofi_mr_verify` is trying to validate the address by getting iov address + offset. It gets some out of bound address and return FI_EACCES.

```c
119     addr = (void *) (*io_addr + (uintptr_t) attr->offset);
120
121     if ((addr < attr->mr_iov[0].iov_base) ||
122         (((char *) addr + len) > ((char *) attr->mr_iov[0].iov_base +
123                           attr->mr_iov[0].iov_len))) {
124         return -FI_EACCES;
125     }
```
I'm not sure if I'm missing some steps or some flags for this to happen or is it a bug in the provider? Please suggest.

**Comment by shefty** [comment]
What you described above sounds fine to me.  With FI_MR_VIRT_ADDR = 0, the app should use a 0-based address.  The MR key identifies the region, with the app providing an offset into that region where the transfer should occur.  For example, an RMA write to the region would specify key = BLAH and remote address = 0.  The target would write the data starting at the base address of the memory region.

The use of 0-based addressing means that the app doesn't need to exchange virtual addresses between peers.

**Comment by thananon** [comment]
io_addr is what the application requested address. Now I understand. 
Thank you Sean. This turns out to be a non-issue. I will close this right away.
