### ISSUE TITLE
Using the tcp provider

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#4141]
Hello, I noticed the new TCP provider on the most recent commit and wanted to try using it. However, running fi_info or fi_pingpong on it doesn't seem to work, returning fi_getinfo: -61. Is there a particular flag I have to enable or code I have to delete in order to test the provider?

**Comment by vkrishna** [comment]
You should be able to test as-is. Just make sure you are enabling the tcp provider when you run configure. Which OS are you trying it on?

**Comment by wckzhang** [comment]
Is the flag --enable-tcp (I ran this one on configure). Running it on Amazon Linux.

**Comment by wckzhang** [comment]
Ah I cleaned my install directory and tried again and it seems to have worked. fi_info displays the tcp provider, though fi_pingpong is getting a segmentation fault. "[error] util/pingpong.c:546 : fi_getname didn't return length
Segmentation fault"

**Comment by wckzhang** [comment]
Thanks for your help!
