### ISSUE TITLE
Behavior of FI_MR_UNSPEC in version 1.5 or later

### ISSUE THREAD

**Issue by jlbyrne-hpe** [ofiwg/libfabric#4158]
The current fi_domain man page has the following to say about FI_MR_UNSPEC.

*FI_MR_UNSPEC*
: Defined for compatibility -- library versions 1.4 and earlier.  Setting
  mr_mode to 0 indicates that FI_MR_BASIC or FI_MR_SCALABLE are requested
  and supported.

From this, the expectation is that passing in FI_MR_UNSPEC (zero) would result in returning FI_MR_BASIC (one) or FI_MR_SCALABLE (two). However, the fi_getinfo_test fabtest's final test getinfo_mr_mode6 passes in zero as a hint and expects to see zero returned or get -FI_ENODATA. This conflicts with the description above. 

Without the compatibility concerns, passing in zero would mean no mr modes were supported and this is equivalent to FI_MR_SCALABLE, which is compatible with the **bold** text below:

FI_MR_SCALABLE : Defined for compatibility -- library versions 1.4  and
       earlier.  Only scalable memory registration operations are requested or
       supported.  Scalable registration uses offset  based  addressing,  with
       application  selectable  memory  keys.   **For  library  versions 1.5 and
       later, this is the default if no mr_mode bits are set.**  This  flag  may
       not be used in conjunction with other mr_mode bits.

This was discussed at the OFIWG meeting and the conclusion was that this is best dealt with as  documentation issue and that passing zero in for the mr_mode hint should indicate that no mr_mode flags are supported and the man page should be changed to reflect this.

**Comment by shefty** [comment]
This is the intent:

The definition for FI_MR_UNSPEC is meant only to apply to version 1.4 and earlier.  That is, FI_MR_UNSPEC will return either FI_MR_BASIC or FI_MR_SCALABLE for the 1.4 version of the library. FI_MR_UNSPEC is not supportable for 1.5 and later.

Both FI_MR_BASIC and FI_MR_SCALABLE are supported for all library versions.

We want applications to move away from using FI_MR_UNSPEC/BASIC/SCALABLE and respond to individual mr_mode bits being set to 0 or 1.

**Comment by jlbyrne-hpe** [comment]
Understood, but all three of FI_MR_UNSPEC, FI_MR_BASIC, FI_MR_SCALABLE begin with
"Defined for compatibility -- library versions 1.4 and earlier." Two of them work with API version >= 1.5, one doesn't. I find that confusing and worthy of clarification in the man page.

Something like:

FI_MR_UNSPEC:
Defined for compatibility -- library versions 1.4 and earlier, but not supported for versions 1.5 or greater. 

FI_MR_BASIC and FI_MR_SCALABLE:
Defined for compatibility -- library versions 1.4 and earlier, deprecated for versions 1.5 or greater.
