### ISSUE TITLE
prov/sockets: hang with scalable endpoint.

### ISSUE THREAD

**Issue by thananon** [ofiwg/libfabric#4166]
I took a look at #3886 but it seems to be a different problem. 

I initialize sockets provider and create a scalable endpoint with just 1 tx context and it hang on `fi_read()`. The log shows that the peer is trying to process the same entry (read) over and over.

```
libfabric:sockets:ep_data:sock_comm_peek():207<debug> peek from network: 24
libfabric:sockets:ep_data:sock_pe_peek_hdr():1586<debug> PE RX (Hdr peek): MsgLen:  48, TX-ID: 0, Type: 6
libfabric:sockets:ep_data:sock_pe_release_entry():199<debug> progress entry 0x7f2aac1926e8 released
libfabric:sockets:ep_data:sock_pe_acquire_entry():227<debug> progress entry 0x7f2aac1926e8 acquired : 127
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2086<debug> New RX on PE entry 0x7f2aac1926e8 (127)
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2089<debug> Inserting rx_entry to PE entry 0x7f2aac1926e8, conn: 0xead600
libfabric:sockets:ep_data:sock_comm_peek():207<debug> peek from network: 24
libfabric:sockets:ep_data:sock_pe_peek_hdr():1586<debug> PE RX (Hdr peek): MsgLen:  48, TX-ID: 0, Type: 6
libfabric:sockets:ep_data:sock_pe_release_entry():199<debug> progress entry 0x7f2aac1926e8 released
libfabric:sockets:ep_data:sock_pe_acquire_entry():227<debug> progress entry 0x7f2aac1926e8 acquired : 127
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2086<debug> New RX on PE entry 0x7f2aac1926e8 (127)
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2089<debug> Inserting rx_entry to PE entry 0x7f2aac1926e8, conn: 0xead600
libfabric:sockets:ep_data:sock_comm_peek():207<debug> peek from network: 24
libfabric:sockets:ep_data:sock_pe_peek_hdr():1586<debug> PE RX (Hdr peek): MsgLen:  48, TX-ID: 0, Type: 6
libfabric:sockets:ep_data:sock_pe_release_entry():199<debug> progress entry 0x7f2aac1926e8 released
libfabric:sockets:ep_data:sock_pe_acquire_entry():227<debug> progress entry 0x7f2aac1926e8 acquired : 127
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2086<debug> New RX on PE entry 0x7f2aac1926e8 (127)
libfabric:sockets:ep_data:sock_pe_new_rx_entry():2089<debug> Inserting rx_entry to PE entry 0x7f2aac1926e8, conn: 0xead600
```

After some debugging I found the fail point here:
```c
1606     if (rx_ctx->is_ctrl_ctx && sock_pe_is_data_msg(msg_hdr->op_type))
1607         return -1;
```
op_type is `SOCK_OP_READ` (valid) and `rx_ctx->is_ctrl_ctx` is 1.

The code works fine for psm2 provider.  The only thing I can think of is, I dont have rx context in my application (It is one sided only). Is rx context necessary for sockets provider?

**Comment by shefty** [comment]
It sounds like a bug.  But probably not one that I'll fix, since we're trying to move away from the sockets provider in favor of the tcp provider.  We can at least document this in the man page

**Comment by shefty** [comment]
To clarify, if the fix is easy, we can do it.  Along this line, if you remove lines 1606-1607 mentioned above, can you see if that works for you as well (with rx context disabled again)?

**Comment by thananon** [comment]
> if you remove lines 1606-1607 mentioned above, can you see if that works for you as well (with rx context disabled again)?

Yes, it works but I'm not sure if it breaks something else. XD

**Comment by shefty** [comment]
I can make the same change and check our CI.  :)  It may be a (wrong) sanity check, rather than something that's necessary.

**Comment by thananon** [comment]
I think this is somewhat resolved. I'm closing this issue.
