### ISSUE TITLE
prov/verbs;ofi_rxm: Assertion in prov/rxm/src/rxm.h line 653 during shutdown after doing a fi_read()

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#4232]
Executing a test using the fi_read() API, during the cleanup/shutdown of the application, an assertion was encountered.  The assertion message was:
prov/rxm/src/rxm.h:653: rxm_tx_buf_release: Assertion `(tx_buf->type == RXM_BUF_POOL_TX_MSG) || (tx_buf->type == RXM_BUF_POOL_TX_TAGGED) || (tx_buf->type == RXM_BUF_POOL_TX_ACK) || (tx_buf->type == RXM_BUF_POOL_TX_LMT) || (tx_buf->type == RXM_BUF_POOL_TX_SAR)' failed.

Here is some debug output from my test:
[cn1, Rank:  0] DEBUG: do_api: FI_READ(1): dt: UINT32, xfer: 1, flags: 0x0000000000000000, len: 8, user cntx: 0x1000001, ep: 0x1c61330, local: 0x1cb8940, num: 1, fi_addr: 0x1, remote: 0x1536980, dest_mr_key: 0x500f2
[cn1, Rank:  0] DEBUG: do_api: FI_READ(1): xfer: 1, user cntx: 0x1000001, Successful
  :
  :
[cn1, Rank:  0] DEBUG: verify_data_buffers(1:0): api: FI_READ, read, data type: UINT32, data size: 4
[cn1, Rank:  0] DATA: sft_verify_data_uint32_t, read: data compare error: xfer: (1:1), expected: 0x01001001(0x1cb8880), actual: 0x00000000(0x1cb8940)
  :
  :
[cn1, Rank:  0] ERROR: rma_operation, failed data verification: api: FI_READ, verification errors: 4
[cn1, Rank:  0] RESULT: RMA test FAIL.
rma: prov/rxm/src/rxm.h:653: rxm_tx_buf_release: Assertion `(tx_buf->type == RXM_BUF_POOL_TX_MSG) || (tx_buf->type == RXM_BUF_POOL_TX_TAGGED) || (tx_buf->type == RXM_BUF_POOL_TX_ACK) || (tx_buf->type == RXM_BUF_POOL_TX_LMT) || (tx_buf->type == RXM_BUF_POOL_TX_SAR)' failed.

**Comment by jswaro** [comment]
@tonyzinger Does this still occur with master? What commit did we first see this error?

**Comment by shefty** [comment]
old issue that has likely been resolved (no further complaints in this area have been reported).
