### ISSUE TITLE
prov/verbs;ofi_rxm: test using fi_read() API does not get CQ events on the initiator side

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#4233]
When executing a test using the fi_read() API, the initiating side does NOT receive any CQ events.
When executing a test using the fi_wrtie() API, the initiating side does receive CQ events.

Debug output for the fi_read() test:
[cn1, Rank:  0] DEBUG: do_api: FI_READ(1): dt: UINT32, xfer: 1, flags: 0x0000000000000000, len: 8, user cntx: 0x1000001, ep: 0x1c61330, local: 0x1cb8940, num: 1, fi_addr: 0x1, remote: 0x1536980, dest_mr_key: 0x500f2
[cn1, Rank:  0] DEBUG: do_api: FI_READ(1): xfer: 1, user cntx: 0x1000001, Successful
[cn1, Rank:  0] ERROR: ltu_get_cq_tagged_entry Line: 2490, fi_cq_read(FI_READ): flags: 0x0, len: 0, buf: (nil), data: 0x0, tag: 0x0, err: -258, prov_errno: -258 returned -258 (Unknown error -258)

Debug output fot the fi_write() test:
[cn1, Rank:  0] DEBUG: do_api: FI_WRITE(1): dt: UINT32, xfer: 1, flags: 0x0000000000000000, len: 8, user cntx: 0x1000001, ep: 0x2535330, local: 0x258dbc0, num: 1, fi_addr: 0x1, remote: 0x1800b80, dest_mr_key: 0x4cebf
[cn1, Rank:  0] DEBUG: do_api: FI_WRITE(1): xfer: 1, user cntx: 0x1000001, Successful
[cn1, Rank:  0] INFO: fi_cq_read(FI_WRITE), entries: 1, flags: 0x204, buffer: (nil), length: 0, data: 0x0, context: 0x1000001, tag: 0x7fa02cee5000
[cn1, Rank:  0] DEBUG: sft_get_cq_events: num_cq_requests: 1, current_cq: 1, cq_index: 0, uc: 0x1000001
[cn1, Rank:  0] DEBUG: do_transfers: FI_WRITE: memory_registration index: buf_index_for_rank: 0, cur_send_to: 1, mr_send_to: 1
[cn1, Rank:  0] DEBUG: do_api: FI_WRITE(1): dt: UINT32, xfer: 2, flags: 0x0000000000000000, len: 8, user cntx: 0x1000002, ep: 0x2535330, local: 0x258dbc8, num: 1, fi_addr: 0x1, remote: 0x1800b88, dest_mr_key: 0x4cebf
[cn1, Rank:  0] DEBUG: do_api: FI_WRITE(1): xfer: 2, user cntx: 0x1000002, Successful
[cn1, Rank:  0] INFO: fi_cq_read(FI_WRITE), entries: 1, flags: 0x204, buffer: (nil), length: 0, data: 0x0, context: 0x1000002, tag: 0x7ffe41b5cfc0
[cn1, Rank:  0] DEBUG: sft_get_cq_events: num_cq_requests: 1, current_cq: 1, cq_index: 0, uc: 0x1000002

**Comment by dmitrygladkov** [comment]
> can you add what version you are running to the issues you just opened?

I suppose this is version from my GitHub fork, right?

**Comment by tonyzinger** [comment]
Yes, the libfabric library that I was using has Dmitry's fix for cmap.

**Comment by jswaro** [comment]
@tonyzinger Does this still occur with master? What git commit is the error associated with?

**Comment by swelch** [comment]
@dmitrygladkov - Tony has confirmed this issue is not reproducible and can be closed.
