### ISSUE TITLE
custom psm2 install path is not honored

### ISSUE THREAD

**Issue by ael-code** [ofiwg/libfabric#4271]
I've an old version of psm2 library installed under `/usr/lib64` and a newer one on `/build/psm2/usr/lib64`.

If I've configured with the `--enable-psm2="/build/psm2/usr"` flag.

From the verbose output I can see that the folllowing compilation flags are properly used:
```
-L/build/psm2/usr/lib64 -lpsm2 -lrt -lpthread -ldl
```

But then if I use ldd on the generated `libfabric.so.1.9.14` I find out that the system wide one is actually used instead of the one I've provided:
```
libpsm2.so.2 => /usr/lib64/libpsm2.so.2
```

**Comment by ael-code** [comment]
I found a temporary solution.
If I force the following compilation flags:
```
CFLAGS="-Wl,-rpath,/build/psm2/usr/lib64"
```
The newer psm2 library is actually used and ldd upon `libfabric.so.1.9.14` returns:
```
libpsm2.so.2 => /build/psm2/usr/lib64/libpsm2.so.2
```

**Comment by jsquyres** [comment]
@matcabral can you have a look?
