### ISSUE TITLE
How about to remove verbs/RDM?

### ISSUE THREAD

**Issue by dmitrygladkov** [ofiwg/libfabric#4278]
What we have:
1. libfabric uses RxM/verbs/MSG as a default
2. RxM/verbs pass all MPICH tests with MPICH/IMPI. And as far as I know, well tested with OpenMPI.
verbs/RDM has too much bugs and not stable.
3. RxM/verbs (latest one form master branch) shows better performance numbers and scalability

@shefty @a-ilango what do you think? If you agree, I'd remove verbs/RDM's code from libfabric in 1.7 release.

**Comment by shefty** [comment]
Go for it.

**Comment by a-ilango** [comment]
👍
