### ISSUE TITLE
fi_cq_readfrom() semantics

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#4282]
Reading through the man page and past issues on the topic, I take it that applications calling `fi_cq_readfrom()` are responsible for the lifecycle of an AV that gets returned in this call. In the case where an application gets a message from a peer it has not seen before (hence, not called `fi_av_insert()` on), providers are going to send up a `-FI_EAVAIL` and send a completion error of type `FI_ADDR_NOTAVAIL` if `FI_SOURCE_ERR` capability is requested. Do I have that right?

It is not clear from the semantics described in the man page what providers do in the face of a message from an unknown peer. Are they guaranteed not to implicitly insert the address into their AV after sending up the completion error. If that is going to happen, the app could end up pulling the err_data from the completion error and explicitly inserting the address, causing a duplicate insertion which providers are going to assume illegal based on the WG discussion from a while back. This is particularly ambiguous when looking at how utility providers might use this interface when not wanting to deal with source addresses in their protocol headers.

**Comment by shefty** [comment]
@rajachan - Please see https://github.com/ofiwg/libfabric/pull/4285 and let me know if that clarifies the behavior.

**Comment by rajachan** [comment]
Yes, that's much more explicit and clear now, thanks!
