### ISSUE TITLE
RXM utility provider does not pass FI_ATOMIC flag from core provider to application

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4310]
@shefty @a-ilango @dmitrygladkov 
Is this expected behavior? If so, why?

We are attempting to run an fi_atomic test using verbs;ofi_rxm, and the messaging endpoint used with ofi_rxm supports FI_ATOMIC, but the ofi_rxm layer doesn't seem to allow the capability to be set.

**Comment by jswaro** [comment]
> Verbs provider supports only a limited set of atomic ops so RxM doesn't pass along or support FI_ATOMIC.

So if this wasn't verbs that we were discussing, rather it was a provider with full (or close to full) support for atomics -- would this still be expected behavior of the RxM provider? 

**Opinion:** _A utility provider shouldn't artificially limit the set of functions that should be exposed to the application **without good reason**_.

In this specific case, RxM should be able to use the same set of functions that an application would use, fi_query_atomic, to determine whether it could pass the request through to the core provider. Conceptually, I believe RxM can support atomics so long as the core provider supports atomics, even if only limited support. RxM only needs to provide support for any atomic operation that the core provider supports. I see this as a bug or gap in the RxM provider that could be resolved with a patch or two. 

What I would like to understand better is why the decision was made to not pass-through the atomics flag with a utility provider. If it was deliberate, what was the basis for the decision and does the decision still make sense today? If not, do we believe that there is anything that prevents us from exposing that functionality?

**Comment by swelch** [comment]
@shefty  @a-ilango - I was looking into adding this atomic support, but there is an API issue I would like your opinion and/or suggestions on handling.

The layering of the utility provider over the core provider exposes an issue with the fi_atomicvalid(), fi_fetch_atomicvalid() and fi_compare_atomicvalid(), when mapping from the RxM endpoint to the core provider message endpoint to use in making the core provider call. These routines include the endpoint FID, but not a destination fi_addr_t that can be used to map to a connection and it's associated message endpoint.

While these calls could open a message endpoint, make the core call and close it, that seems overly expensive. It seems it would be even worse to arbitrarily force a connection. Possibly there is a way to maintain a link from the RxM domain to message endpoint or be able to find a valid connection without the peer address? Any thoughts or recommendations on how you think this should be handled are appreciated.

**Comment by shefty** [comment]
This is an RxM implementation issue, not an API problem.  RxM will need to implement full atomic support in software, or require full atomic support by the underlying MSG provider.  IMO, the first is preferred.  RxM can then check if the MSG provider has full atomic support, and if so, use that over its emulation.

In practice, we expect RxM to be used with MSG EPs that either lack full atomic support or implement it in software.  So an RxM software implementation with no optimizations based on the underlying MSG provider will likely be sufficient.

Also, please note that there is already an implementation for atomic operations as part of the common code, in case you're not aware.  Only the protocol piece is missing.

**Comment by swelch** [comment]
Thanks. The use of the term "API issue" on my part was not meant to imply the API was the problem, only that I had questions about the RxM implementation of those API calls; so I think we agree on that. By full atomic support, do you mean the core provider implements the API basic, fetch, and compare calls (possibly for some datatypes and operations), or that every combination of datatype and operation must be supported by the core provider?

**Comment by shefty** [comment]
By full I mean the complete set of atomics for all datatypes and operation.  This is what the upper libraries need.  And I don't believe that using a mix of hardware and software based atomics is able to provide the right level of guarantees.

**Comment by jswaro** [comment]
@shefty Just a few questions.

If a utility provider is providing a feature or function for a core provider, shouldn't it defer to the core provider when the core provider supports something? **Lack of being able to call the MSG EP core provider's functions for atomic operations seems to be odd from my perspective since RxM provides an emulation over a core provider's MSG endpoint.** 

I can see the simplification and it makes sense to require all or nothing from the atomics in a core provider. I can also see that it makes sense with the current implementation. However, what doesn't make sense to me is why the RxM provider would not use a supported native atomic which would be faster than software emulation and/or leverage those native atomics to make the emulated atomics faster. Feasibly, we could use a single MSG EP that has already been established to verify the level of atomic support for all EPs under the same RxM RDM endpoint -- and admittedly, that is hacky. Why wouldn't/shouldn't we use those native atomics from the core provider even if it is a subset of the libfabric atomic set of operations?

**Comment by shefty** [comment]
I'm not convinced that you can mix software and hardware based solutions and still retain correctness.  I.e.. are the resulting operations still atomic with data ordering maintained.

**Comment by bcernohous** [comment]
Where does the all or nothing "require full atomic support" come from? AFAIK, no provider is required to provide all or nothing.  

libfabrics provides the atomic valid APIs *so* you can check which atomics are supported by the provider.  Is RXM not able to answer that question for the underlying provider?

**Comment by shefty** [comment]
MPI requires full atomic support, so the requirement is coming from the app.  RxM targets MPI as one of its primary users, and will eventually expose support for all atomics.  An alternative is for RxM to only export what the underlying MSG provider supports.  But in all cases I'm aware of, no MSG provider will support the needs of MPI.

If we can show that mixing onload and offload atomic support will work in a generic fashion, then RxM can optimize based on the MSG provider support. Otherwise, it needs to emulate them.

**Comment by swelch** [comment]
I think it would be hard to mix emulated and native hardware atomics. Hardware atomic operation serialization is done by the destination HCA. Once you have introduced emulated atomics, I think it would be hard if not impossible from the provider level to guarantee that a node won't issue a hardware atomic to the same location that a different node has issued an emulated atomic. While that might not make sense for the application to do, the point is it would not be easily detected by the individual providers.

It seems like sequencing of emulated and hardware atomics from the same node could be problematic as well in this case as simple fencing of a hardware operation would be insufficient.

**Comment by bcernohous** [comment]
I'm not sure how this became a discussion of mixing emulated and hardware atomics.   RxM doesn't emulate atomics, does it?   So why doesn't it support fi_atomic_valid/etc and tell us what the provider supports?  My app will decide what to do with the information, like it does for any other provider.

If RxM someday emulates atomics, then it will just reply itself to fi_atomic_valid calls.  It wouldn't expose a mix of underlying atomics and emulated atomics. I think everyone agrees that's a bad idea.

**Comment by jswaro** [comment]
We may have gotten off track here. I think we would only want to expose the native hardware atomics from the verbs MSG endpoints. Applications that use providers such as GNI, or verbs MSG have always had the caveat that if software atomics were done with native hardware atomics -- then the application would be responsible for coherency. 

I don't think it is being suggested to introduce OFI emulated atomics with the core provider's native atomics. That would create an issue that shouldn't be dealt with by the provider. Does this make sense or is the issue still fuzzy?

**Comment by shefty** [comment]
I'm saying that exposing only what verbs devices support through rxm is not useful for middleware targeting RDM EPs.  Verbs supports maybe 2 atomic operations against 1 datatype with an array size of 1, and that's only IB.  IWarp doesn't support atomics.

Exposing verbs atomics up would force a software base implementation to all middleware (all MPIs, SHMEM, etc.).  It is preferable that there be a single implementation within the rxm provider.  The libfabric core already has a full implementation available.  RxM just needs to hook into that with the right protocol.

rxm is a utility provider, exactly because the native core provider can't even meet the basic requirement of rdm ep support.  Providing software based atomics isn't different than software tag matching.

So, no, I don't think it makes sense to expose the core provider atomic support upward.  I don't see that as useful.
