### ISSUE TITLE
Stale content while using ofi_recvwin_get_next_msg

### ISSUE THREAD

**Issue by mohanasudhan** [ofiwg/libfabric#4319]
We were noticing stale content while retriving next item from [ofi_recvwin_get_next_msg](https://github.com/ofiwg/libfabric/blob/master/include/ofi_recvwin.h#L90) in recvwin. On digging in we noticed recvwin is not clearing the content during ofi_recvwin_get_next_msg call.

e.g. Let's take recvwin of size 1024, as recvwin is implemented as circular queue msg_id 10 and 1034 will land in same slot. In here, lets say msg_id 10 was saved and retrieved from recvwin, and then next 1024 messages pass on. So the current expected value is 1034, and lets say we haven't saved 1034 in the recvwin yet. But, since recvwin haven't cleared the content we were getting next value which is stale msg_id 10 (comparing expected behaviour of NULL). 

There are two option we propose here 

(1) Do a copy of result to user location and clear the content of circular queue slot in ofi_recvwin_get_next_msg, but this increase mem copy overhead.
(2) Add some metadata footer in each entry to state the validity of the entry, which will be used while retrieving the content. 

I sideline with option (2) here. Let me know what you guys think, we are happy to update the code based on your thought in here.

**Comment by shefty** [comment]
Can we increase the queue size by 1 extra slot?

**Comment by mohanasudhan** [comment]
Can you pls elaborate on it ?

**Comment by shefty** [comment]
The problem says that id's 10 and 1034 land on the same slot because the queue size is 1024.  Can we either increase the size to 1025 or reduce the number of usable slots to 1023, so that there's always an unused slot in the queue?  Two id's should not be able to land into the same slot.

Or maybe I'm not understanding the issue, which is very possible.

**Comment by mohanasudhan** [comment]
Sorry, I completely missed this thread as I was in vacation during that time-frame.

The case will happen even if we change the size of recvwin to 1025/1023. ofi_recvwin_get_next_msg return **address** of entrytype, and moves the pointer to next slot. So the slot is not cleared at all. 

Here is how I solve the case today by making 2 calls
1. ofi_recvwin_peek to fetch value *entrytype
2. ofi_recvwin_get_next_msg() = NULL (clears older entry)
