### ISSUE TITLE
AWS-ci always using latest fabtests, even for libfabic v1.6.x?

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#4342]
Got AWS-ci failure for a v1.6.x PR, the error message was like this:

> 09:14:15   CC       unit/eq_test.o
09:14:15 unit/eq_test.c: In function ‘main’:
09:14:15 unit/eq_test.c:574:3: error: ‘FI_BUFFERED_RECV’ undeclared (first use in this function)
09:14:15    FI_BUFFERED_RECV;
09:14:15    ^
09:14:15 unit/eq_test.c:574:3: note: each undeclared identifier is reported only once for each function it appears in
09:14:15 make[1]: *** [unit/eq_test.o] Error 1
09:14:15 make[1]: Leaving directory `/home/ec2-user/workspace/single-node/PROVIDER/sockets/label/rhel/fabtests'
09:14:15 make: *** [all] Error 2
09:14:15 Build step 'Execute shell' marked build as failure
09:14:16 Finished: FAILURE

The FI_BUFFERED_RECV flag is not defined in v1.6.x branch. It seems AWS-ci is trying to build fabtests master when testing the libfabric v1.6.x commits.

**Comment by rajachan** [comment]
The CI framework does not take branches into account yet. The intent with using master was that fabtests itself will do the necessary FI_VERSION checks where appropriate to maintain backward compatibility at runtime. But I agree, that does not help with missing symbols like in this case.  Assign this issue to me, and I'll go take a look at what we can do here.

**Comment by shefty** [comment]
FYI - fabtests only tries to work with the latest version of libfabric in order to minimize maintenance costs.

**Comment by shefty** [comment]
Requested @rajachan with reader access, to assign requests.

**Comment by rajachan** [comment]
Alright then, will clone fabtests from the branch that a PR is targeted for. Will close this issue once the changes have been made.

**Comment by rajachan** [comment]
This has been taken care of.
(I don't have permissions to close the issue)

**Comment by j-xiong** [comment]
Thanks. I am closing the issue.
