### ISSUE TITLE
psm2 CPU detection causes erroneous Makefile creation

### ISSUE THREAD

**Issue by hhoffstaette** [ofiwg/libfabric#4355]
Trying to build libfabric 1.6.1 on Gentoo running on a SandyBridge CPU causes a confused
Makefile to be generated:

```
$make
Makefile:9050: target 'Core(TM)' given more than once in the same rule
Makefile:9050: target 'i7-2600K' given more than once in the same rule
Makefile:9050: target 'CPU' given more than once in the same rule
Makefile:9050: target '@' given more than once in the same rule
Makefile:9050: target '3.40GHz.Plo' given more than once in the same rule
..etc..
```

I traced this to psm2's 'prov/psm2/configure.m4' which says:
```
     # Determine if we can support the psm2 provider
     psm2_ARCH=`uname -p | sed -e 's,\(i[456]86\|athlon$$\),i386,'`
     AM_CONDITIONAL([HAVE_PSM2_X86_64], [test x$psm2_ARCH = xx86_64])
```
On my box `uname -p` results in `Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz`,
all of which is then happily interpolated into configure & the resulting Makefile,
whitespace and all.
It seems to me the right thing here would be `uname -m` (machine hardware name),
which results in ``x86_64`` and seems to match the expected capability.

**Comment by j-xiong** [comment]
Fixed via #4356
