### ISSUE TITLE
Counters and FI_SELECTIVE_COMPLETION?

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#4426]
Should rx/tx counters be incremented regardless of whether a completion event is written when FI_SELECTIVE_COMPLETION is enabled on an endpoint? It's a bit unclear in the documentation so I wanted to check first.

**Comment by j-xiong** [comment]
As for documentation. FI_SELECTIVE_COMPLETION only appears under the section about binding completion queues to endpoints, not under the section of binding counters to endpoints (see fi_endpoint man page).

**Comment by rwespetal** [comment]
That makes sense, thank you for the clarification.
