### ISSUE TITLE
core/fid_nic: better support prov_attr

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#4442]
Per https://github.com/ofiwg/libfabric/pull/4433#issuecomment-424136716:

> For the prov_attr, we need to extend struct fi_provider if we want to be able to print them or allow a complex structure. So, I guess the first decision is how flexible do we want provider attributes to be?
> 
> My current thinking is to add tostr(), allocinfo, and freeinfo() calls to fi_provider. The provider would only be responsible for handling provider specific portions of input data.

And per https://github.com/ofiwg/libfabric/pull/4433#issuecomment-424145293:

> I was considering adding the other external API calls to the provider, but the provider would only deal with the provider specific pieces.  For example, today if an app calls fi_dupinfo() on an fi_info where the handle is set to FI_CLASS_CONNREQ, the handle is ignored.  So, I'd like to have a more generic solution.
> 
> These would be the additions:
> ```
> dupinfo(const struct fi_info *info, struct fi_info *new_info);
> freeinfo(struct fi_info *info);
> tostr(const void *data, enum fi_type datatype);
> ```
> There needs to be enough information in whatever input data there is in order to route the call to the correct provider.  So, not all calls into the main API can find their way to the provider, even it provider specific data is present.
> 
> For dupinfo/freeinfo, the provider only deals with the handle field.  But maybe this would allow a provider to store data beyond the end of the user visible structure(s)?

**Comment by shefty** [comment]
This is a couple of years old at this point, but the upstream code handles this by calling back into the providers to handle the nic_attr as needed.
