### ISSUE TITLE
prov/psm2: Fails to build with an old libpsm2

### ISSUE THREAD

**Issue by hajimefu** [ofiwg/libfabric#4484]
Observed behavior:
====

When an old libpsm2 is detected, libfabric succeeds in `configure` but fails at `make` stage.

```
$ ~/src/libfabric/configure --enable-psm2=yes

...

configure: *** Configuring psm2 provider
checking psm2.h usability... yes
checking psm2.h presence... yes
checking for psm2.h... yes
looking for library without search path
checking for psm2_mq_fp_msg in -lpsm2... no
configure: recheck psm2 without psm2_mq_fp_msg.
checking psm2.h usability... yes
checking psm2.h presence... yes
checking for psm2.h... yes
looking for library without search path
checking for psm2_am_register_handlers_2 in -lpsm2... yes
configure: psm2 provider: include in libfabric

...

$ make

...

  CC       prov/psm2/src/libpsmx2_la-psmx2_attr.lo
In file included from /home/hajimefu/src/libfabric/prov/psm2/src/psmx2_attr.c:33:0:
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2.h: In function ‘psmx2_get_source_name’:
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2.h:1051:2: warning: implicit declaration of function ‘psm2_epaddr_to_epid’; did you mean ‘psmx2_epid_to_epaddr’? [-Wimplicit-function-declaration]
  psm2_epaddr_to_epid(epaddr, &name->epid);
  ^~~~~~~~~~~~~~~~~~~
  psmx2_epid_to_epaddr
  CC       prov/psm2/src/libpsmx2_la-psmx2_init.lo
In file included from /home/hajimefu/src/libfabric/prov/psm2/src/psmx2_init.c:33:0:
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2.h: In function ‘psmx2_get_source_name’:
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2.h:1051:2: warning: implicit declaration of function ‘psm2_epaddr_to_epid’; did you mean ‘psmx2_epid_to_epaddr’? [-Wimplicit-function-declaration]
  psm2_epaddr_to_epid(epaddr, &name->epid);
  ^~~~~~~~~~~~~~~~~~~
  psmx2_epid_to_epaddr
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2_init.c: In function ‘psmx2_check_multi_ep_cap’:
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2_init.c:176:18: error: ‘PSM2_MULTI_EP_CAP’ undeclared (first use in this function); did you mean ‘PSM2_PATH_RES_OPP’?
  uint64_t caps = PSM2_MULTI_EP_CAP;
                  ^~~~~~~~~~~~~~~~~
                  PSM2_PATH_RES_OPP
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2_init.c:176:18: note: each undeclared identifier is reported only once for each function it appears in
/home/hajimefu/src/libfabric/prov/psm2/src/psmx2_init.c:179:6: warning: implicit declaration of function ‘psm2_get_capability_mask’ [-Wimplicit-function-declaration]
  if (psm2_get_capability_mask(caps) == caps && psmx2_get_yes_no(s, 0))
      ^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:10410: prov/psm2/src/libpsmx2_la-psmx2_init.lo] Error 1
make[1]: Leaving directory '/home/hajimefu/build/libfabric-test'
make: *** [Makefile:3800: all] Error 2
```

Expected behavior:
====

libfabric should either
* Fail at configure time saying installed `libpsm2` is too old
* Succeed in building (with potentially limited feature set)

Configuration:
====

* libfabric: `master` as of today: fcf0f2ec3c7109e06e09d3650564df8d2dfa12b6 (also happens at `v1.6.2` as well)
* libpsm2: hfi1-psm.x86_64 0.7-244
* OS: CentOS Linux release 7.2.1511 (Core)

**Comment by j-xiong** [comment]
Could you check you LD_LIBRARY_PATH settings? It looks like configure picked up a newer libpsm2.so while the system had old psm2.h (and maybe also old libpsm2.so) installed at the default location.

**Comment by j-xiong** [comment]
Correction: LD_LIBRARY_PATH should not matter. But nevertheless it sounds the libpsm2.so and psm2.h on the system are not from the same package.

I double checked with old psm2 library locally and the configure script stopped correctly after detecting required functions are missing. 

> checking for psm2_am_register_handlers_2 in -lpsm2... no
configure: recheck psm2 without psm2_am_register_handlers_2.
checking psm2.h usability... yes
checking psm2.h presence... yes
checking for psm2.h... yes
checking for psm2_ep_disconnect2 in -lpsm2... no
configure: psm2 provider: disabled
configure: WARNING: psm2 provider was requested, but cannot be compiled
configure: error: Cannot continue

**Comment by hajimefu** [comment]
I tested with a clean shell with minimal environment variable settings but the result was the same.
```
bash-4.2$ echo $PATH
/usr/local/bin:/usr/bin:/bin
bash-4.2$ echo $LD_LIBRARY_PATH

```

I do have a newer libpsm2 in a different location than `/usr/lib64`.  Is there any other settings that libfabric might use to search libpsm2?

**Comment by j-xiong** [comment]
Try 'ld --verbose | grep SEARCH_DIR'. Here is the output on my machine:

> SEARCH_DIR("/usr/x86_64-redhat-linux/lib64"); SEARCH_DIR("/usr/lib64"); SEARCH_DIR("/usr/local/lib64"); SEARCH_DIR("/lib64"); SEARCH_DIR("/usr/x86_64-redhat-linux/lib"); SEARCH_DIR("/usr
/local/lib"); SEARCH_DIR("/lib"); SEARCH_DIR("/usr/lib");

**Comment by hajimefu** [comment]
Oh wait... it turns out we somehow messed up libpsm2 installation in this system. Apparently we overwrote the libpsm2* files under `/usr/lib64` with newer versions but not the header files under `/usr/include`.

Now I think this issue is invalid, so I'll close it. Thank you for your help! @j-xiong
