### ISSUE TITLE
fi_atomic manpage ambiguity

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#4500]
The [fi_atomic(3)](https://ofiwg.github.io/libfabric/v1.6.2/man/fi_atomic.3.html) manpage for v1.6.2 states the following in the Completions section:

> Updates to the target buffer of an atomic operation are **visible to processes** running on the **target system** either **after a completion has been generated**, or after the completion of an operation initiated after the atomic call with a fencing operation occurring in between. For example, the target process may be notified by the initiator sending a message after the atomic call completes, or sending a fenced message immediately after initiating the atomic operation.

This is ambiguous/inconsistent as worded. It states that **any** completion provides visibility guarantees at the target. Consider the case where the initiating endpoint has a default operation flag of `FI_TRANSMIT_COMPLETE`. The [fi_endpoint(3)](https://ofiwg.github.io/libfabric/v1.6.2/man/fi_endpoint.3.html) states the following for `FI_TRANSMIT_COMPLETE` in the OPERATION FLAGS section:

> The state of the operation at the peer endpoint is not defined.

For base atomics (i.e. non-fetching atomics not called out in fi_endpoint(3) under `FI_DELIVERY_COMPLETE`), the above statement is contradicted by the visibility guarantee being made in the fi_atomic(3). The reader will likely assume that network atomics provide `FI_DELIVERY_COMPLETE` like behavior, but it is not explicitly stated.

I also think it would be helpful if the fi_atomic(3) manpage describes expected memory ordering between atomic operations, similar to what was done for the C++11 memory model. The reader likely assumes memory_order_relaxed ordering between atomic operations lacking an established happens-before relationship (via a completion event or `FI_FENCE` flag), but it is not explicit. The only language that exists in fi_atomic(3) is the following:

> Conceptually, they are similar to local atomic operations of a similar nature (e.g. atomic increment, compare and swap, etc.).

This is not enough information to derive meaning of comparisons to CPU atomics.

**Comment by shefty** [comment]
I think you're interpreting "after a completion has been generated" to mean any completion, but it refers to the completion of the atomic operation itself.  The or clause refers to the completion of a separate operation, but that requires a fencing operation.

The API is intended to allow a peer NIC to cache the results of the atomic operation. The visibility of the results depends on how the results are accessed.  The results are available, but not necessarily without being accessed through the same provider (NIC) that completed the operation.

I'm not following the memory ordering issue.  There is a separate endpoint attribute that indicates if messages are processed in order or not, and if data is updated in order or not.  That semantic is separate from whether the operation is an atomic update or other message, such as an RMA write.

**Comment by agontarek** [comment]
I agree that the statement "after a completion has been generated" refers to the completion of the atomic operation, not any arbitrary completion. 

If the default op flags are generating completion events for `FI_TRANSMIT_COMPLETE`, or even `FI_INJECT_COMPLETE`, is it not the case that the atomic operation will generate a completion for that type? In other words, if an atomic operation has a `FI_TRANSMIT_COMPLETE` completion event generated, is there visibility guarantees at the target? How about for `FI_INJECT_COMPLETE`? If so, the fi_atomic(3) manpage contradicts these completion types.

The caching of results of the atomic operation at the peer NIC is orthogonal to this discussion as the fi_atomic(3) manpage states "visible to processes running on the target system". This statement does not imply the peer NIC must be used as a sequence point. It provides a stronger visibility guarantee. It is saying a CPU core will observe the result of the atomic operation at the moment a completion is generated for the operation at the initiator.

My comment about comparisons to CPU atomics was not to describe atomic vs non-atomic (e.g. RMA write) ordering semantics. I was focusing on ordering semantics between two atomic operations. I viewed the endpoint attribute indicating order more of a how atomic vs non-atomic ordering is defined, but it is a good point. I think it would be helpful to refer back to the fi_endpoint(3) manpage to describe ordering semantics between two atomic operations in the fi_atomic(3) manpage.

**Comment by shefty** [comment]
> If the default op flags are generating completion events for
> FI_TRANSMIT_COMPLETE, or even FI_INJECT_COMPLETE, is it not the case
> that the atomic operation will generate a completion for that type? In
> other words, if an atomic operation has a FI_TRANSMIT_COMPLETE
> completion event generated, is there visibility guarantees at the
> target? How about for FI_INJECT_COMPLETE? If so, the fi_atomic(3)
> manpage contradicts these completion types.

I think the confusion is stemming from completion events at the initiator versus the target.  Inject/transmit complete semantics are in reference to the initiator and provide no guarantees at the target.

The fi_atomic 'Completion' section is referring to completion events generated *at the target*.  That part can be clarified.  The requirement is that a completion event directly associated with the atomic operation cannot be generated until at the target until after the target buffers have been updated.  Similarly, a received message event generated at the target for a sent fenced message cannot post prior to the atomic data having been written.

> My comment about comparisons to CPU atomics was not to describe atomic
> vs non-atomic (e.g. RMA write) ordering semantics. I was focusing on
> ordering semantics between two atomic operations. I viewed the
> endpoint attribute indicating order more of a how atomic vs non-atomic
> ordering is defined, but it is a good point. I think it would be
> helpful to refer back to the fi_endpoint(3) manpage to describe
> ordering semantics between two atomic operations in the fi_atomic(3)
> manpage.

I'll try to come up with specific updates to the text to clarify the behavior, both for here and above.

**Comment by agontarek** [comment]
@jswaro @bcernohous
