### ISSUE TITLE
fi_atomic/FI_INJECT clarification

### ISSUE THREAD

**Issue by bcernohous** [ofiwg/libfabric#4504]
I need clarification on fi_atomics and inject.

The fi_inject_atomic call is an optimized version of fi_atomic. The fi_inject_atomic 
function behaves as if the FI_INJECT transfer flag were set, and FI_COMPLETION were 
not. That is, the data buffer is available for reuse immediately on returning from 
from fi_inject_atomic, and no completion event will be generated for this atomic. 
The completion event will be suppressed even if the endpoint has not been configured 
with FI_SELECTIVE_COMPLETION. See the flags discussion below for more details. The 
requested message size that can be used with fi_inject_atomic is limited by inject_size.

```
FI_INJECT
    Indicates that the outbound non-const data buffers (buf and compare parameters) 
    should be returned to user immediately after the call returns, even if the 
    operation is handled asynchronously. This may require that the underlying provider 
    implementation copy the data into a local buffer and transfer out of that buffer. 
    The use of output result buffers are not affected by this flag. This flag can only 
    be used with messages smaller than inject_size.
```

So we can specify FI_INJECT on a msg API like:

```c
ssize_t fi_compare_atomicmsg(struct fid_ep *ep,
	const struct fi_msg_atomic *msg, const struct fi_ioc *comparev,
	void **compare_desc, size_t compare_count,
	struct fi_ioc *resultv, void **result_desc, size_t result_count,
	uint64_t flags);
```

But what are "buf and compare parameters" on this API?  Are we safe 
to just interpret "the outbound non-const data buffers" statement 
appropriately on the iov's?  The local data will be injected and we'll
(of course) wait for the result/return appropriately?

```c
struct fi_msg_atomic {
	const struct fi_ioc *msg_iov; /* local scatter-gather array */
	void                **desc;   /* local access descriptors */
	size_t              iov_count;/* # elements in ioc */
	const void          *addr;    /* optional endpoint address */
	const struct fi_rma_ioc *rma_iov; /* remote SGL */
	size_t              rma_iov_count;/* # elements in remote SGL */
	enum fi_datatype    datatype; /* operand datatype */
	enum fi_op          op;       /* atomic operation */
	void                *context; /* user-defined context */
	uint64_t            data;     /* optional data */
};

struct fi_ioc {
	void		*addr;    /* local address */
	size_t		count;    /* # target operands */
};

struct fi_rma_ioc {
	uint64_t	addr;     /* target address */
	size_t		count;    /* # target operands */
	uint64_t	key;      /* access key */
};
```

**Comment by shefty** [comment]
So, there's an error in the man page.  'non-const' should have said 'const'.  This problem was just raised to me a couple of days ago. In the call referenced above, comparev and msg::msg_iov should be the injected buffers.

I will update the man page.

**Comment by jdinan** [comment]
I just finished implementing the proposed nonblocking shmem_atomic_compare_swap operation in SOS and can confirm that this works with the sockets provider as described by @shefty.

**Comment by bcernohous** [comment]
'Works' in sockets is different than works across providers.  I have it working on GNI with GNI developer assurances.  But I'm not going to every provider for confirmation.  

Glad for the confirmation.
