### ISSUE TITLE
mr_regv and mr_regattr test is not testing interface for MR_IOV_LIMIT=1

### ISSUE THREAD

**Issue by mohanasudhan** [ofiwg/libfabric#4540]
Minimium size in test_size = 2 [https://github.com/ofiwg/libfabric/blob/master/fabtests/common/shared.c#L117](url)
which will skip for loop in mr_regv and mr_regattr for mr_iov_limit=1 e.g. [https://github.com/ofiwg/libfabric/blob/8d7ba6767d40884648efc5239b2a3b9ab8254d1f/fabtests/unit/mr_test.c#L160](url) and making test as passed

As few provider support mr_iov_limit=1, above tests are testing interface correctly

**Comment by shefty** [comment]
Good catch, 1 should be added to test_size.

**Comment by shefty** [comment]
Addressed by PR #4541
