### ISSUE TITLE
.ibtoolize:   error: AC_CONFIG_MACRO_DIRS([config]) conflicts with ACLOCAL_AMFLAGS=-I config

### ISSUE THREAD

**Issue by germanafro** [ofiwg/libfabric#4546]
any idea why this may be happening? 

previously i done 
> apt-get install autoconf
> apt-get install libtool

then:

root@i-need-change:~/libraries/c_c++/libfabric# ./autogen.sh

**Comment by jsquyres** [comment]
This may be a silly question, but just to make sure: are automake, autoconf, and libtool all installed in the same directory?  I.e., did you apt-get autoconf and libtool, but automake is being used from some other installation tree?

**Comment by germanafro** [comment]
whew I don't really know. I'm certainly more at home on windows. how would I find that out?

**Comment by jsquyres** [comment]
What's the result of:

```
which autoconf
which automake
which libtool
```

**Comment by germanafro** [comment]
well isnt that interesting:

> root@i-need-change:~/Libfabric_Benchmark/CBM_Benchmark# which autoconf
> /usr/bin/autoconf
> root@i-need-change:~/Libfabric_Benchmark/CBM_Benchmark# which automake
> /usr/bin/automake
> root@i-need-change:~/Libfabric_Benchmark/CBM_Benchmark# which libtool
> root@i-need-change:~/Libfabric_Benchmark/CBM_Benchmark#

I guess that would probably explain why the error occurs... now to figure out why libtool has no folder...

**Comment by jsquyres** [comment]
Github pro tip: use 3 single tick marks to indicate the beginning and end of a multi-line verbatim section (instead of prefixing each line with >).

Yeah, if you have no Libtool, Weird Things(tm) will happen.  It's odd if you did `apt-get install libtool`, but somehow you have no libtool.

🤷‍♂️
