### ISSUE TITLE
prov/verbs, prov/rxm; osu_get_latency benchmark hangs with recent changes to master

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4557]
Using master, verbs;ofi_rxm; and MPICH3.3b3. Prior to the merges yesterday, this benchmark passed. It does not now. 

@a-ilango  @dmitrygladkov 

CHANGES
--
Revision by dmitry.gladkov | util/buf: Remove region_list as not needed
edit | include/ofi_mem.h
edit | prov/util/src/util_buf.c
Revision by dmitry.gladkov | util/buf: Add indexing capability
edit | prov/util/src/util_av.c
edit | include/ofi_mem.h
edit | prov/util/src/util_buf.c
Revision by dmitry.gladkov | util/av: Use indexing capability for utility buffer
edit | prov/util/src/util_av.c
edit | prov/util/src/util_buf.c
Revision by arun.ilango | fabtests: add some logging to fi_poll test
edit | fabtests/functional/poll.c
Revision by arun.ilango | prov/rxm: fix counter increment for inject ops
edit | prov/rxm/src/rxm_ep.c
Revision by arun.ilango | prov/rxm: use util_ep counter increment functions which don't have
edit | prov/rxm/src/rxm_cq.c
edit | prov/rxm/src/rxm_rma.c
edit | prov/rxm/src/rxm_ep.c
edit | prov/rxm/src/rxm.h
Revision by arun.ilango | fabtests: enable some tests for verbs, rxm providers
edit | fabtests/test_configs/ofi_rxm/ofi_rxm.exclude
edit | fabtests/test_configs/verbs/verbs.exclude
Revision by alexia.ingerson | prox/rxd: check seq_no for wrapping
edit | include/ofi_util.h
edit | prov/rxd/src/rxd.h
edit | prov/rxd/src/rxd_cq.c

**Comment by jswaro** [comment]
[log.txt](https://github.com/ofiwg/libfabric/files/2506991/log.txt)

See log.txt for debug log.

**Comment by dmitrygladkov** [comment]
@jswaro Thanks!
I see that it can be related to my or Arun's changes.
I'll take a look tomorrow.
