### ISSUE TITLE
fabtests: environment variables are not propagated

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4559]
This may simply just be informative rather than a bug. 

When running fabtests in our test environment, we were attempting (prior to fabtests being integrated with libfabric) to test a stable fabtest installation against multiple versions of libfabric. This was done by providing the libfabric library via LD_LIBRARY_PATH. However, we found out earlier this week that those environment variables we'd set in the build environment are not propagated by fabtests out to the nodes the tests will run on. This caused us to run fabtests on the original installation that fabtests was compiled against, and not on the intended libfabric libraries. 

fabtests cannot control SSH environment propagation settings, nor would we wish it to. However, is this something that we should expect, or was the intention that fabtests would inherit the environment of the node where it was being run from? If it is the latter, could another option be added to introduce certain environment variables prior to execution of the fabtest tests? 

@shefty

**Comment by shefty** [comment]
I'm not following the requests.  Are you wanting the script that executes the independent tests to set certain environment variables prior to executing those tests?

**Comment by jswaro** [comment]
Yes.

Something like this perhaps?
`./runfabtests.sh -E LD_LIBRARY_PATH -E FI_LOG_LEVEL -t unit verbs 10.0.0.1 10.0.0.2`

**Comment by shefty** [comment]
These would be nice.  Not sure how difficult it would be to add.  @a-ilango - any idea on how hard this might be?  (Don't interpret this as a request to make the change.)

**Comment by jswaro** [comment]
While trying to explain it, I put a possible solution above.

**Comment by a-ilango** [comment]
It seems @jswaro 's solution should work. It would be nice to have runfabtests.sh script propagate env variables to ssh'd nodes.

**Comment by jswaro** [comment]
If no one minds, I'll draft up something and post a PR then. I would like this feature.

**Comment by shefty** [comment]
Go for it!
