### ISSUE TITLE
prov/verbs, prov/rxm; RMA test fails during connection setup/first transfer

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4565]
[log.txt](https://github.com/ofiwg/libfabric/files/2511703/log.txt)

See log.txt for libfabric debug output. 

So I'm trying to get my head wrapped around this, but I see a few concerning statements in the log file. There is a conn reject at some point in the file, followed by some verbs error completions, and flushes. I suspect that the connection reject may have caused the error completions indirectly if the QP was in a bad state. 

Thoughts? @a-ilango @dmitrygladkov @tonyzinger

**Comment by a-ilango** [comment]
I see these in the logs:
```
2: libfabric:ofi_rxm:cq:rxm_cq_read_write_error():864<warn> Unable to fi_cq_readerr
2: libfabric:ofi_rxm:cq:rxm_cq_read_write_error():896<warn> Invalid state!
2: libfabric:ofi_rxm:cq:rxm_cq_read_write_error():899<warn> msg cq error info: local protection error
```
Seems like a missing / erroneous memory registration issue. What test is this?

**Comment by jswaro** [comment]
I was just looking into that. It’s a test that Tony wrote to exercise the RMA paths in a variety of different communication patterns. I’m looking to see if a flag was forgotten somewhere.

-- Jim

**Comment by jswaro** [comment]
Here's his logic regarding memory registration. However, changing the permission of his memory registrations  (FI_READ|FI_WRITE|FI_REMOTE_WRITE|FI_REMOTE_READ) -- it doesn't seem to affect the output of his test. I'll ask him more about it tomorrow.

```
If a read API, 
     source buffer permissions = FI_REMOTE_READ
     target buffer permissions = FI_READ
If a write API,
     source buffer permissions = FI_WRITE
     target buffer permissions = FI_REMOTE_WRITE
```

**Comment by shefty** [comment]
For RMA write, the source buffer needs no access (or read based on MR_LOCAL).  The target needs remote write.

For RMA read, the source buffer needs write access (based on MR_LOCAL).  The target needs remote read.

**Comment by jswaro** [comment]
Right, but giving the source buffer all of the access permissions didn't change the result. That's the confusing part.

**Comment by jswaro** [comment]
Tony structured the code differently than how I interpreted it. It seems like he has the correct flags, and may even have flags he does not need. 

Implementation aside, the flags seem correct. 

The remote buffer for a read operation has FI_REMOTE_READ, while the local buffer for a read operation has FI_READ (which may be unnecessary based on your comment).

**Comment by jswaro** [comment]
We can close this. We found an issue in the application code regarding the local memory descriptor. 

@a-ilango  We are seeing that information during the first RMA operation if I read the log correctly.
