### ISSUE TITLE
weird behavior regarding fi_av_insert() using g++ compiler

### ISSUE THREAD

**Issue by germanafro** [ofiwg/libfabric#4581]
Hello Everyone,
I'm working on my Bachelor thesis and for that I'm supposed to write a Benchmark
utilizing libfabric. [https://github.com/germanafro/Libfabric_Benchmark/tree/master/Benchmark](url)
For the first testing stage I set up my own local Ubuntu 16.04 machine and a remote server also Ubuntu 16.04 using regular ethernet. later the project will be portet to a larger system of multiple hosts using infiniband architecture. well  I doubt this has anything to do with the issue but I find it best practice to provide as much background infos as possible.

 For now I just wanted to build a simple ping pong and then work my way up. As I'm on normal ethernet network I'm asking for sockets provider with rma and msg caps as that is how we want to transfer data later on.
```
    hints->addr_format = FI_SOCKADDR;
    hints->ep_attr->type = FI_EP_MSG;
    hints->domain_attr->mr_mode = FI_MR_BASIC;
    hints->caps = FI_MSG | FI_RMA;
    hints->mode = FI_LOCAL_MR;
```

I've had many failed attempts utilizing connected endpoints and none of the tutorials or documentation seem to particularly adress the issue in detail. 
So I went back to using unconnected endpoints using AV as the documentation for that usecase is simply much better. here i simply set 

> av_attr.type = fi->domain_attr->av_type;
> av_attr.count=1;

  

I'm using the standard chain that I have seen many times now to initialize my nodes:
fi_getinfo() -> fi_fabric() -> fi_domain() -> fi_cq -> fi_av() -> fi_mr()->fi_endpoint -> fi_bind() -> fi_enable

the code branches depending on functionality (server / client):
server:
```
fi_getinfo(FIVER, "127.0.0.1", "1234", FI_SOURCE, conf->hints, &fi);
```
client: 
```
fi_getinfo(FIVER, addr, port, 0, conf->hints, &fi);
```

now here comes the tricky part:

when I call fi_getname() for the server i get the proper expected return "127.0.0.1:1234"
calling the same for the client (params: addr=127.0.0.1, port=1234) returns "127.0.0.1:0" This doesn't suprise me all that much though I haven't really figured out how I would go about adding the correct port to the src adress (e.g. 1233). 

The actual problem arises with the client  when I call fi_av_insert:
```abc
    fi_addr_t remote_addr = FI_ADDR_UNSPEC;
    size_t buff_size = conf->buff_size;
    void* buff = malloc(conf->buff_size);
    size_t local_addrlen = 100; //FIXME
    size_t remote_addrlen = 100; //FIXME
    char * laddr = new char(100);
    char * raddr = new char(100);

    //laddr = (char*)malloc(sizeof(char*) * 30);
    //raddr = (char*)malloc(sizeof(char*) * 30);

    ret = fi_getname(&ep->fid, buff, &buff_size); // get client address
    if (ret) {
        printf("fi_getname: %s\n", strerror(ret));
       // return -1;
    }
    fi_av_straddr(av, buff, laddr, &local_addrlen);

    ret = fi_av_insert(av, fi->dest_addr, 1, &remote_addr, 0, NULL); // insert server address
    if (ret < 0) {
        printf("fi_av_insert: %s %d\n", strerror(ret), ret);
        return -1;
    }
    fi_av_straddr(av, &remote_addr, raddr, &remote_addrlen);
    //fi_av_straddr(av, fi->dest_addr, raddr, &remote_addrlen);
    printf("client: local: %s (%d), remote: %s (%d)\n", laddr, (int)local_addrlen, 
                                                     raddr, (int)remote_addrlen);
```

where I get an output like this:

> ~/Libfabric_Benchmark/Benchmark$ ./Benchmark localhost 1234
> Hello, World!
> client: 127.0.0.1 1234 
> fi_getinfo: sockets 127.0.0.0/8 
> init: Success 
> client: local: 127.0.0.1:0 (12), remote: 127.0.0.�c*uhU:0 (17)  16
> fi_send: Operation now in progress

to me this looks like a pointer or memory issue. it's almost like the size of the av table entry wasn't big enough to fit the last entry of the ip address though I'm pretty sure fi_addr_t is the correct type to be used here. 
I checked fi->dest_addr as you can see in the comments. and it returns the expected adress "127.0.0.1:1234".

so I'm really at loss here... could this be an actual bug or am I not supposed to use fi_av_straddr() for that purpose?

**Comment by shefty** [comment]
So, there are several example applications available from fabtests.  You may want to look at these samples:

https://github.com/ofiwg/libfabric/blob/master/fabtests/benchmarks/msg_pingpong.c
https://github.com/ofiwg/libfabric/blob/master/fabtests/benchmarks/msg_bw.c

These are connected-endpoint benchmark examples for latency and bandwidth tests.

Note that fabtests support a variety of endpoint and test options, so tracing through the code isn't always straightforward.  But you should be able to ignore code branches for features that you don't care about.

Regarding fi_getinfo(): when you specify FI_SOURCE, you are requesting that the server endpoint have the address that was given.  In this case 127.0.0.1:1234.  Calling fi_getinfo() on the client side, the address being passed in is the address of the server -- that is, the address that the client will try to communicate with.  The client will select an endpoint address that is usable.  The 127.0.0.1:0 address that you are seeing means that the client address has a wildcard port.  The actual port number won't be assigned until the endpoint is enabled.

fi_av_straddr() is for debugging purposes.  It's expecting as input the same address format that you pass to fi_av_insert(), struct sockaddr * in your case (fi->dest_addr).

**Comment by germanafro** [comment]
ty - so I was simply using it wrong then.
