### ISSUE TITLE
fi_accept() does not transition ep to active state

### ISSUE THREAD

**Issue by germanafro** [ofiwg/libfabric#4582]
> The fi_enable call is used to transition an active endpoint into an enabled state. The fi_connect and fi_accept calls will also transition an endpoint into the enabled state, if it is not already active. 

apparently this is not true for 1.6.2 

i had a a pep listening for incoming conn. 
on connreq create active ep then do fi_accept() then fi_send()

the fi_send gave "Operation not permitted in current state" 

I fixed the issue by explicitly calling fi_enable() before fi_accept()

**Comment by shefty** [comment]
Which provider were you using for this?  This sounds like a bug

**Comment by germanafro** [comment]
that happens with the sockets provider I haven't testet for the verbs provider yet.

**Comment by shefty** [comment]
Can you test with the changes in PR #4583?  https://github.com/ofiwg/libfabric/pull/4583

**Comment by shefty** [comment]
Btw - it looks like the verbs provider should be okay.

**Comment by germanafro** [comment]
I suppose I have to compile this myself ?

**Comment by germanafro** [comment]
i Just looked into the src file sock_ep_msg.c referenced in the patch and it seems to deviate heavily from the pre-build 1.6.2 packages' file. So I guess I'm gonna try and compile from source and apply your patch and see how it goes.

**Comment by shefty** [comment]
I'll port the patch to the 1.6.x branch and open another pull request.  Just give me a few minutes.

**Comment by shefty** [comment]
Okay - try https://github.com/ofiwg/libfabric/pull/4584, which has been updated for the 1.6.x branch.  This is a 1-line patch, so you could manually edit the file/location/function in question to test.

**Comment by germanafro** [comment]
I'm not sure what's going on here 
i did 
`make clean && make && make install`
> root@i-need-change:~/Libfabric_Benchmark/CBM_Benchmark# ./Benchmark
> ./Benchmark: /usr/local/lib/libfabric.so.1: version `FABRIC_1.2' not found (required by ./Benchmark)

`ldconfig -v` gives me this for libfabric:
> /usr/local/lib:
>         libfabric.so.1 -> libfabric.so.1.9.15

if this is related to the FI_version call then I'm using FI_VERSION(1, 6)

**Comment by germanafro** [comment]
alright that did the trick. TY I spend weeks figuring this out.. I almost gave up on my thesis out of frustration until it hit me and I checked whether the endpoint was actually enabled or not and it wasn't ^^

**Comment by shefty** [comment]
That's good to hear, and thanks for finding this bug.  Note that there is a mailing list ofiwg@lists.openfabrics.org that you can also mail with questions.  You'll usually get a fairly quick response.
