### ISSUE TITLE
Libfabric doesn't compile with g++ compiler and "-Werror=shadow"

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#4593]
Hi,
I'm trying to compile a C++ application with the libfabric interface.
When I include `rdma/fabric.h`, g++ fails with the following error message:

`pkgbuild/libfabric/include/rdma/fabric.h: In function 'int fi_alias(fid*, fid**, uint64_t)':
pkgbuild/libfabric/include/rdma/fabric.h:535:83: error: 'int fi_alias(fid*, fid**, uint64_t)' hides constructor for 'struct fi_alias' [-Werror=shadow]
 static inline int fi_alias(struct fid *fid, struct fid **alias_fid, uint64_t flags)`

I guess it's because `fabric.h` declares two symbols with the same name `fi_alias`:
1. `static inline int fi_alias(struct fid *fid, struct fid **alias_fid, uint64_t flags)`
2. `struct fi_alias {           
    struct fid      **fid;  
    uint64_t        flags;  
};`

I'm using g++ version 8.2.0 on Linux and I can reproduce the issue with libfabric 1.4.0 and 1.6.2.

Have you ever tried to compile Libfabric with g++? I think we would need a basic job in Travis/Jenkins to verify that Libfabric compiles fine with some recent g++ compilers.

Thanks for your help!
Sylvain

**Comment by sydidelot** [comment]
Thanks for your reply, @shefty.
I had been conducting some additional tests and I've found that the cpp application I'm trying to compile automatically includes the compilation flag `-Werror=shadow` (you can get more information about shadowed variables there: https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)
However, this `-Werror=shadow` flag is not exported when using `-Werror -Wextra -Wall` so I guess the issue is not critical since Libfabric compiles fine with these regular flags.

Please feel free to close this issue if you don't consider supporting `-Werror=shadow` compilation flag in Libfabric.
Sorry for the noise and thanks again for your reply @shefty

**Comment by shefty** [comment]
I don't know how this can be avoided without breaking apps.  We can't rename either the struct or function name.  :/
