### ISSUE TITLE
prov/psm2 performance issue with fi_trywait()

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#4599]
When using the psm2 provider with `FI_WAIT_FD` and `FI_PROGRESS_AUTO`, I am getting bad performance when entering the fi_trywait() call. If I skip that call and just wait all the time in epoll_wait on the file descriptor retrieved from fi_control(), everything looks fine. It is my understanding though that one should call fi_trywait() to potentially skip the epoll_wait() call if something is already in the queue, hence potentially getting better performance but in that case it's the opposite. Any idea what is happening there?

**Comment by j-xiong** [comment]
Could you provide a reproducer?

**Comment by j-xiong** [comment]
No update for two years. Close it now.
