### ISSUE TITLE
prov/psm2 FI_WAIT_FD not compatible with  FI_PROGRESS_MANUAL

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#4600]
If I try to use `FI_PROGRESS_MANUAL` with `FI_WAIT_FD`, I am able to retrieve a file descriptor by using `fi_control()` but it does not seem to be signaled correctly, and I never wake up from a call to `epoll_wait()` once that file descriptor is added to a poll set. No error is being thrown though. If I use `FI_PROGRESS_AUTO`, signaling seems to be done correctly.

**Comment by j-xiong** [comment]
Due to the nature of how PSM2 works, no progress is going to be made when the application is blocked inside epoll_wait() in manual progress mode. Use fi_wait() instead.

**Comment by j-xiong** [comment]
Won't fix. Close now.
