### ISSUE TITLE
prov/verbs: a message fi_send gets a bogus CQ entry with "Message Truncated" error message

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#4616]
This CQ entry with the "Message Truncated" error makes no sense.  The message size that I sent is 4 bytes and the CQ entry says that the message length is 68 bytes.  Also, the message that was sent and received contains the correct data.

I am attaching  a file that contains test output and Libfabric debug messages documenting the test case that I used to receive this inappropriate CQ event message.

[Message_FI_SEND_gets_cq_message_truncated_error.txt](https://github.com/ofiwg/libfabric/files/2589689/Message_FI_SEND_gets_cq_message_truncated_error.txt)

**Comment by AddyLaddy** [comment]
I have also started seeing that issue, I made this change to fix it;

```
diff --git a/prov/rxm/src/rxm_ep.c b/prov/rxm/src/rxm_ep.c
index 0859d20..42f4657 100644
--- a/prov/rxm/src/rxm_ep.c
+++ b/prov/rxm/src/rxm_ep.c
@@ -1297,7 +1297,7 @@ rxm_ep_send_inject(struct rxm_ep *rxm_ep, const struct iovec *iov, size_t count,
                                "Ran out of buffers from Eager Inject buffer pool\n");
                        return -FI_EAGAIN;
                }
-               rxm_ep_format_tx_buf_pkt(rxm_conn, total_len, op, data, tag,
+               rxm_ep_format_tx_buf_pkt(rxm_conn, data_len, op, data, tag,
                                         flags, &tx_buf->pkt);
                ofi_copy_from_iov(tx_buf->pkt.data, tx_buf->pkt.hdr.size,
                                  iov, count, 0);
```

I believe this bug was introduce in this commit;

```
commit 06011ce7babc33084c279f5af9eaf3ce561c2569
Author: Dmitry Gladkov <dmitry.gladkov@intel.com>
Date:   Thu Oct 25 09:54:00 2018 +0300

    prov/rxm: Refactor TX buffer handling
    
    This commit does the following:
    - Remove `rxm_ep_format_tx_res_lightweight` and split it into
    `rxm_tx_buf_get` and `rxm_ep_formфе_tx_buf_pkt`.
    - Fix TX buffer leak when `rxm_ep_normal_send` fails
    - Move `msg_ep` field from `struct rxm_buf` to `struct rxm_rx_buf`
    
    Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>
```

It would be good to get the developers to confirm the bug and fix.

**Comment by shefty** [comment]
@a-ilango @dmitrygladkov

**Comment by a-ilango** [comment]
@AddyLaddy Yes, that's the right fix. It seems like a copy paste error in the offending commit. I can prepare a PR with the fix or if you already have it ready please open a PR.

**Comment by a-ilango** [comment]
I've opened a PR to fix this issue. Fabtests posts a receive buffer that's large enough for all message sizes being tested and also large enough for control messages like sync. It may not be trivial to adjust the recv buffer size to just the right value.

I think adding a unit test where we can post a rightly sized receive buffer would be easier and it could detect this regression in the future. I'll look into it.
