### ISSUE TITLE
1.5 verbs provider not showing in fi_info structure when using hints

### ISSUE THREAD

**Issue by germanafro** [ofiwg/libfabric#4639]
**Issue solved:**
`hints->domain_attr->mr_mode = FI_MR_BASIC | FI_MR_LOCAL | FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR;`
did the trick

I am really at my wits end here. 

I originally had my hints set to:
```
hints->addr_format = FI_SOCKADDR_IN;
hints->ep_attr->type = FI_EP_MSG;
hints->domain_attr->mr_mode = FI_MR_BASIC;
hints->caps = FI_MSG | FI_RMA;
hints->mode = FI_CONTEXT | FI_LOCAL_MR | FI_RX_CQ_DATA;
```
those caps are said to be supported by the verbs provider(some may even be required?). But somehow I only receive the sockets provider when calling fi_getinfo().

when i run 
`fi_getinfo(FI_VERSION(1, 5), NULL, NULL, 0, NULL, &fi) `
I get this list of providers: 
(formating: _provider: fi->fabric_attr->prov_name  fi->fabric_attr->name_)
> 0: provider: verbs IB-0x80fe
> 0: provider: verbs IB-0x80fe
> 0: provider: verbs;ofi_rxm IB-0x80fe
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 127.0.0.0/8
> 0: provider: sockets 127.0.0.0/8

yet calling
```
struct fi_info * hints = fi_allocinfo();
fi_getinfo(FI_VERSION(1, 5), NULL, NULL, 0, hints, &fi);
```
where hints is simply allocated but nothing has been set yet 
will only yield the sockets and UDP providers:

> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: UDP UDP-IP
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.0.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 10.1.0.0/16
> 0: provider: sockets 127.0.0.0/8
> 0: provider: sockets 127.0.0.0/8

I also tried explicitely requesting verbs with:
`hints->fabric_attr->prov_name = strdup("verbs");`
which then just fails with errno -61 

checking for verbs providers from terminal yields:

> berger@login:~/Libfabric_Benchmark/CBM_Benchmark$ srun -l --nodelist=pn[04] fi_info --provider=verbs
> 0: provider: verbs
> 0:     fabric: IB-0x80fe
> 0:     domain: mlx4_0
> 0:     version: 1.0
> 0:     type: FI_EP_MSG
> 0:     protocol: FI_PROTO_RDMA_CM_IB_RC
> 0: provider: verbs
> 0:     fabric: IB-0x80fe
> 0:     domain: mlx4_0-rdm
> 0:     version: 1.0
> 0:     type: FI_EP_RDM
> 0:     protocol: FI_PROTO_IB_RDM
> 0: provider: verbs;ofi_rxm
> 0:     fabric: IB-0x80fe
> 0:     domain: mlx4_0
> 0:     version: 1.0
> 0:     type: FI_EP_RDM
> 0:     protocol: FI_PROTO_RXM
> 0: provider: verbs;ofi_rxm
> 0:     fabric: IB-0x80fe
> 0:     domain: mlx4_0
> 0:     version: 1.0
> 0:     type: FI_EP_RDM
> 0:     protocol: FI_PROTO_RXM

So I really have no idea why this is happening :/ could this be a bug or do I need to set a certain capability in hints? - if so I don't think I read anything about that in the man pages.

**Comment by shefty** [comment]
The behavior of NULL hints, versus a cleared hints structure differs.
```
The hints parameter, if provided, may be used to limit the resulting output as indicated below. As a general rule, specifying a non-zero value for input hints indicates that a provider must support the requested value or fail the operation with -FI_ENODATA
```
When NULL is passed in for hints, this indicates that that all available providers should be returned.  This acts as a generic query mechanism.  However, when hints are provided, even if all fields are 0/null, then hints act as a filter on the output.  In your case, the key field to look at is hints::mode.  Because that field is 0, it indicates that the app does not support any requested 'modes'.  However, verbs and the utility providers that layer over verbs need those mode bits set.

You can try turning up the FI_LOG_LEVEL to see additional details on why a specific provider might not be responded to the fi_getinfo() call.  See https://ofiwg.github.io/libfabric/master/man/fabric.7.html for how to control that.

**Comment by germanafro** [comment]
thanks again for your continued support.
you probably read the post before I edited it so you didn't get that missing info: 
in my original attempt i used:
```
hints->addr_format = FI_SOCKADDR_IN;
hints->ep_attr->type = FI_EP_MSG;
hints->domain_attr->mr_mode = FI_MR_BASIC;
hints->caps = FI_MSG | FI_RMA;
hints->mode = FI_CONTEXT | FI_LOCAL_MR | FI_RX_CQ_DATA;
```
which only gave me the sockets providers - so somethign must still be missing I guess :/ I'll reiterate through the documentations. Maybe I missed something.

**Comment by shefty** [comment]
When you run fi_info -v, do  you see verbs provider responses that match your hints?  I.e. same addr_format, etc.?  Those look correct to me.  @a-ilango ?

**Comment by a-ilango** [comment]
Yes, the hints seems right. But then 1.5 is really old and I think there might be some bugs when parsing FI_MR_BASIC. @germanafro can you try with v1.6.2? Is there a need to use v1.5?

**Comment by germanafro** [comment]
> 
> 
> Yes, the hints seems right. But then 1.5 is really old and I think there might be some bugs when parsing FI_MR_BASIC. @germanafro can you try with v1.6.2? Is there a need to use v1.5?

I'm working on a faculty cluster not owned or administrated by me but I'll talk to my professor to make the upgrade though that probably wont be happening today =D. 

regarding fi_info -v:

> berger@login:~/Libfabric_Benchmark/CBM_Benchmark$ srun -l --nodelist=pn[04] fi_info -v --provider=verbs --ep_type=FI_EP_MSG --caps="FI_RMA|FI_RMA" --mode="FI_CONTEXT|FI_LOCAL_MR|FI_RX_CQ_DATA"
> 0: ---
> 0: fi_info:
> 0:     caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM, FI_RMA ]
> 0:     mode: [  ]
> 0:     addr_format: FI_SOCKADDR_IN
> 0:     src_addrlen: 16
> 0:     dest_addrlen: 0
> 0:     src_addr: fi_sockaddr_in://10.1.103.104:0
> 0:     dest_addr: (null)
> 0:     handle: (null)
> 0:     fi_tx_attr:
> 0:         caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM, FI_RMA ]
> 0:         mode: [  ]
> 0:         op_flags: [  ]
> 0:         msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
> 0:         comp_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
> 0:         inject_size: 88
> 0:         size: 384
> 0:         iov_limit: 4
> 0:         rma_iov_limit: 4
> 0:     fi_rx_attr:
> 0:         caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM, FI_RMA ]
> 0:         mode: [ FI_RX_CQ_DATA ]
> 0:         op_flags: [  ]
> 0:         msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT ]
> 0:         comp_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAR, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_STRICT, FI_ORDER_DATA ]
> 0:         total_buffered_recv: 0
> 0:         size: 384
> 0:         iov_limit: 4
> 0:     fi_ep_attr:
> 0:         type: FI_EP_MSG
> 0:         protocol: FI_PROTO_RDMA_CM_IB_RC
> 0:         protocol_version: 1
> 0:         max_msg_size: 1073741824
> 0:         msg_prefix_size: 0
> 0:         max_order_raw_size: 1073741824
> 0:         max_order_war_size: 0
> 0:         max_order_waw_size: 1073741824
> 0:         mem_tag_format: 0x0000000000000000
> 0:         tx_ctx_cnt: 1
> 0:         rx_ctx_cnt: 1
> 0:         auth_key_size: 0
> 0:     fi_domain_attr:
> 0:         domain: 0x0
> 0:         name: mlx4_0
> 0:         threading: FI_THREAD_SAFE
> 0:         control_progress: FI_PROGRESS_AUTO
> 0:         data_progress: FI_PROGRESS_AUTO
> 0:         resource_mgmt: FI_RM_ENABLED
> 0:         av_type: FI_AV_UNSPEC
> 0:         mr_mode: [ FI_MR_BASIC, FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
> 0:         mr_key_size: 4
> 0:         cq_data_size: 4
> 0:         cq_cnt: 65408
> 0:         ep_cnt: 163768
> 0:         tx_ctx_cnt: 1024
> 0:         rx_ctx_cnt: 1024
> 0:         max_ep_tx_ctx: 1024
> 0:         max_ep_rx_ctx: 1024
> 0:         max_ep_stx_ctx: 0
> 0:         max_ep_srx_ctx: 65472
> 0:         cntr_cnt: 0
> 0:         mr_iov_limit: 1
> 0:     caps: [  ]
> 0:     mode: [  ]
> 0:         auth_key_size: 0
> 0:         max_err_data: 4
> 0:         mr_cnt: 524272
> 0:     fi_fabric_attr:
> 0:         name: IB-0x80fe
> 0:         prov_name: verbs
> 0:         prov_version: 1.0
> 0:         api_version: 1.5

I noticed FI_CONTEXT is actually deprecated and also not included in the mode bits of the shown result. however removing it did not bring any improvement and as we can see the provider still shows up with above query so I'm once again clueless as to what might be missing here. 

There is a silver lining though when I removed the FI_EP_MSG requirement but gave the mode bits. I actually got a verbs provider with FI_EP_RDM caps when running the Benchmark. Sadly this isn't exactly what I'm looking for.

**Comment by a-ilango** [comment]
As a workaround you could try giving the following mode bits instead of FI_MR_BASIC:

hints->domain_attr->mr_mode = FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR

Can you try this?

**Comment by germanafro** [comment]
> 
> 
> As a workaround you could try giving the following mode bits instead of FI_MR_BASIC:
> 
> hints->domain_attr->mr_mode = FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR
> 
> Can you try this?

sadly this didn't fix the issue :/

**Comment by shefty** [comment]
You may need to OR in FI_MR_LOCAL to the mr_mode.

**Comment by germanafro** [comment]
> 
> 
> You may need to OR in FI_MR_LOCAL to the mr_mode.

yep... that did the trick...thank you! so is this working as intended?

 in regards to all the new flags will I have to adjust my code ?
