### ISSUE TITLE
Compile errors on systems without XRC verbs support

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#4658]
libfabric master fails to build on systems that do not have XRC support (e.g., RHEL 6).  The compile errors are fairly obvious; just take any older version of `libibverbs` (before `rdma-core`) and try to compile -- you'll see the failures immediately.

The XRC code is quite pervasive in the verbs provider; I didn't want to make an attempt to make it safe to compile on XRC-less machines.  

I think there are two possibilities here:

1. Make the verbs provider safe to compile without XRC support.
    * If this is the route chosen, I suggest adding something like this to `prov/verbs/configure.m4`, and then using `#if VERBS_HAVE_XRC` in C code:
```patch
index 326688dfe..0ae0d9c3e 100644
--- a/prov/verbs/configure.m4
+++ b/prov/verbs/configure.m4
@@ -65,6 +65,16 @@ AC_DEFUN([FI_VERBS_CONFIGURE],[
                           [Experimental verbs features support])],
                [])
 
+       # See if we have XRC support
+       VERBS_HAVE_XRC=0
+       AS_IF([test $verbs_ibverbs_happy -eq 1],[
+               AC_CHECK_DECL([IBV_QPT_XRC_SEND],
+                       [VERBS_HAVE_XRC=1],[],
+                       [#include <infiniband/verbs.h>])
+               ])
+       AC_DEFINE_UNQUOTED([VERBS_HAVE_XRC],[$VERBS_HAVE_XRC],
+               [Whether infiniband/verbs.h has XRC support or not])
+
        # Technically, verbs_ibverbs_CPPFLAGS and
        # verbs_rdmacm_CPPFLAGS could be different, but it is highly
        # unlikely that they ever will be.  So only list
```
2. Require XRC support for the verbs provider to compile.
    * If this is the case, it would be straightforward to modify the above-suggested patch to disable the verbs provider if XRC support is not found.

**Comment by swelch** [comment]
@jsquyres @shefty @jswaro - Thanks Jeff. Originally the code was setup with config "ifdefs" similar to what you are suggesting. A common consensus developed that for readability/maintenance and ease of use, that it was preferable to always have XRC available. For the travis builds updates were made to use the minimum rdma-core that included XRC support (I believe v13). So, I expect the answer is (2) require XRC support for the verb provider to compile. However, I certain I'm not the person that gets to make this call, so I wait to hear from others.

**Comment by jsquyres** [comment]
My $0.02 is that we definitely still need to be able to build successfully on RHEL 6 with inbox verbs.  It's old, I know, and it sucks, but a fair number of customers still use it.  ☹️   Whether or not a RHEL-6-with-inbox-verbs-build includes verbs support in libfabric is a decision I leave to others.

**Comment by jswaro** [comment]
I don't have an issue with either approach. I'd lean toward (1) over (2), but I'd propose a hybrid of (1) and (2). 

Option 3: Make the verbs provider safe to compile without XRC, and add a configure flag that allows me to require that XRC is part of the build. 

With option 3, I could specify something on the configure line to ensure that I build verbs if I have support for XRC -- or -- it throws an error since I was expecting XRC (if the required option were provided). However, if that argument was not provided on the configure line, and I could not find the correct XRC defines, the XRC variant would be compiled out. 

An example of what the configure line could look like. 
```Bash
./configure --prefix=/path/to/installation --enable-verbs --enable-verbs-xrc
```


Example usage:
```Bash

# If I require verbs, but cannot compile XRC into the provider
./configure --prefix=/path/to/installation --enable-verbs 

# If I require verbs, but can compile XRC into the provider
./configure --prefix=/path/to/installation --enable-verbs

# If I require verbs, and I require XRC to be part of the build
./configure --prefix=/path/to/installation --enable-verbs --enable-verbs-xrc
```

**Comment by shefty** [comment]
When Steve merged xrc support, I went with requiring a libibverbs that had been created in the last half decade.

There are probably only a couple of definitions that are needed for xrc.  We can see if those exist and, if not, provide them.  That would allow the build to proceed.  The xrc code would just make sure it can handle the underlying libibverbs failing any xrc related queries.

**Comment by swelch** [comment]
> Something along the lines of a 'verbs_priv.h' to supplement the missing values?
> 
> I'd guess that we could easily do an initialization check during fi_getinfo for something specific to XRC, and simply omit the XRC-variant provider if the requirement isn't satisfied

@jswaro - Yes, in fi_ibv_init_info() we could omit verbs_msg_xrc_domain from the array used to create the infos.

**Comment by swelch** [comment]
@jsquyres: Jeff, @jswaro is going to work this issue.

**Comment by jswaro** [comment]
@jsquyres I do not have access to a RHEL system with IB/RoCE to test with. Would you be able to test a PR?

**Comment by shefty** [comment]
@jswaro - if you update the travis file to remove the verbs clone or use v12, you can force test this with travis.  Just keep that change in a separate patch and remove it prior to merging

**Comment by jswaro** [comment]
@shefty I've tested this with Ubuntu Trusty outside of Travis using the stock libibverbs. The stock libibverbs in Trusty is pre-rdma-core. I'm just hoping to avoid a run-time issue with the verbs provider with some testing over hardware. Travis doesn't have a RHEL container does it?

**Comment by shefty** [comment]
Ah - no, verbs won't work.  And all of Intel's CI uses a more up to date version of verbs

**Comment by jswaro** [comment]
If nothing else, I'll post the build log from the Ubuntu Trusty VM, and/or a log for a Travis build with the original IB stack in it. This is currently running through the Cray CI at the moment as well.

**Comment by jsquyres** [comment]
Sure -- feel free to ping me when you need compilation tests on RHEL 6.  I don't have any Mellanox hardware with which to test, however.
