### ISSUE TITLE
fabtests configure output: "rm: cannot remove 'core': Is a directory"

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#4659]
A recent change in fabtests (4c579b65055ec3145f47c071b68b1c21446b6ed5) renamed `common` to `core`.

This is resulting in a lot of configure macros emitting warnings:

```
rm: cannot remove 'core': Is a directory
```

because they including code to `rm -rf core` to remove stale corefiles.

These are Autoconf macros that we can't change, unfortunately.

Perhaps `core` is not a good directory name -- can it be changed?

**Comment by jsquyres** [comment]
Actually, it's even worse: a side-effect of this "can't remove core directory" problem is causing `configure` to end up leaving `confdefs.h` in the top-level directory, which causes `make distcheck` to fail, which is causing read-only files to get left on the OpenFabrics build server when it tries to make the nightly snapshot tarballs.

Bottom line: the nightly snapshot tarballs are failing to get created because of 4c579b65055ec3145f47c071b68b1c21446b6ed5.  I'm sorry; this commit needs to be reverted.  `common` can be renamed to something else, if desired -- but the name `core` cannot be used.

**Comment by a-ilango** [comment]
Sorry, I was on vacation. Thanks for fixing this. Didn't realize a directory name of `core` can cause issues with autoconf.
