### ISSUE TITLE
prov/verbs(1.6.2): Regression regarding how failed Work Completions are handled during connection shutdown

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#4672]
Hi,

I've recently started testing Libfabric 1.6.2 with a client/server application we are developing at DDN (I was previously using version 1.4.0).

I' found a regression in a way how Work Completions are handled in Libfabric during connection shutdown following a peer disconnection. When this happens (application killed for example), some outstanding Work Requests (WR) are never completed.
My expectation when a remote peer disconnects is that the network adapter/driver should abort any outstanding WR and generate one Work Completion entry in the CQ for every aborted WR, even those that were outstanding. 
This is the way Verbs works and this is also the behaviour adopted in Libfabric 1.4.0.

I had a quick look at the code and the patch below has introduced the regression:

> commit fe16dd1287eb4145800a2aeed886c4601b134eeb
> Author: Dmitry Gladkov <dmitry.gladkov@intel.com>
> Date:   Wed Sep 13 09:13:55 2017 +0300
> 
>     prov/verbs: Fix a bug during connection shutdown from remote side
>     
>     The following problem can be seen on iWarp verbs devices:
>     The WCs with status `IBV_WC_WR_FLUSH_ERR` is returned for
>     the preposted buffers, when the remote side closes
>     the connection and there is no event
>     `RDMA_CM_EVENT_DISCONNECTED` is returned from rdma_get_cm_event.
>     
>     The following solution fixes this problem:
>     Implemented the pool of posted Work Request entries (just a wrapper
>     for ibv_[send|recv]_wr with control fields). When the upper layer
>     posts the send/recv WR (via fi_send or fi_recv), the verbs provider
>     allocates fi_ibv_wre entry and puts it to wre_list.
>     After successful completion of WR, it is released and moved to
>     fi_ibv_wce entry or directly gave to upper layer.
>     If the WC returned with status `IBV_WC_WR_FLUSH_ERR` it's released
>     by assuming that's remote side closes connection.
>     
>     Signed-off-by: Dmitry Gladkov <dmitry.gladkov@intel.com>

In the patch above, every WC with the status `IBV_WC_WR_FLUSH_ERR` are silently skipped, which cause our application to never receive these WCs (FYI, I'm running with Mellanox IB FDR HCAs). Since the patch above fixes an issue in iWarp, would it be possible to limit the action of that patch to iWarp devices only?

Thanks for your help!
Sylvain

**Comment by shefty** [comment]
Both Arun and Dmitry are out on vacation.  I think Dmitry is back next week.

I don't recall if the API specifies that posted receive operations will be flushed back to the app.  For example, I believe usNIC isn't capable of this.  But, we can at least see if it's possible to pass what failures are available through to the app.

I'd like to have this resolved prior to 1.7, with any fix also backported to the 1.6 branch.

**Comment by sydidelot** [comment]
I'm closing the issue, since patch 4a1ec36 got merged.
