### ISSUE TITLE
prov/tcp: fi_pingpong doesn't work with the provider

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#4678]
While testing the current master, we've figured out that `fi_pingpong` binary included into libfabric repos doesn't work with the `tcp` provider. The client fails with the following log messages:

```
libfabric:tcp:ep_ctrl:tcpx_pep_listen():924<warn> socket listen failed
libfabric:ofi_rxm:ep_ctrl:rxm_ep_bind():2218<warn> Unable to set msg PEP to listen state
fi_ep_bind(): util/pingpong.c:1474, ret=-9 (Bad file descriptor)
libfabric:tcp:fabric:ofi_wait_fd_del():169<info> Given fd (-1) not found in wait list - 0x616f00
```

`tcpx_pep_listen()` fails because the socket given to  `listen` is invalid (-1).

Also, in tcpx_passive_ep(), the creation of the Passive Endpoint depends if the source address is set or not:
```
if (info->src_addr) {                            
     ret = tcpx_pep_sock_create(_pep);            
     if (ret)                                     
         goto err2;                               
 }    
```

In the case of `fi_pingpong`, the source address is never set and there is no way to set it.

I'm not really sure what would be the proper fix here. I'm still a bit surprised that the client side of `fi_pingpong` requires the creation of a passive endpoint. I quickly checked the code and it looks like this PEP is a requirement from `rxm` when an endpoint is bound to an address vector (function `rxm_ep_bind`).

For your information, I've also conducted some tests with the pingpong tests provided by `fabtests` and everything works fine with `tcp` (rdm and msg).

**Comment by shefty** [comment]
This is a problem with rxm + tcp, correct, and not tcp used stand-alone?

**Comment by sydidelot** [comment]
Right, the problem I have described above was with rxm + tcp.

I'm currently testing with tcp stand-alone (msg endpoint type, I disable rxm when calling configure script), but the test now hangs. 
That's a different issue than the one reported above. I'll try to dig into the problem when I have time.

Server: `fi_pingpong -p tcp -e msg`

*Latest log messages:*
```
libfabric:core:core:ofi_register_provider():268<info> registering provider: tcp (0.1)
libfabric:core:core:ofi_register_provider():268<info> registering provider: ofi_perf_hook (1.0)
libfabric:core:core:ofi_register_provider():268<info> registering provider: ofi_noop_hook (1.0)
libfabric:tcp:core:fi_param_get_():272<info> variable iface=<not set>
libfabric:ofi_mrail:core:mrail_check_modes():274<info> Unable to pass through given modes: FI_CONTEXT, FI_MSG_PREFIX, FI_CONTEXT2
libfabric:core:core:fi_getinfo_():928<warn> fi_getinfo: provider ofi_mrail returned -61 (No data available)
libfabric:core:core:fi_fabric_():1120<info> Opened fabric: TCP-IP
````

Client: `fi_pingpong -p tcp -e msg 10.1.1.3`

*Latest log messages:*
```
libfabric:core:core:ofi_register_provider():268<info> registering provider: tcp (0.1)
libfabric:core:core:ofi_register_provider():268<info> registering provider: ofi_perf_hook (1.0)
libfabric:core:core:ofi_register_provider():268<info> registering provider: ofi_noop_hook (1.0)
libfabric:tcp:core:util_getinfo():251<info> cannot resolve source address
libfabric:ofi_mrail:core:mrail_check_modes():274<info> Unable to pass through given modes: FI_CONTEXT, FI_MSG_PREFIX, FI_CONTEXT2
libfabric:core:core:fi_getinfo_():928<warn> fi_getinfo: provider ofi_mrail returned -61 (No data available)
libfabric:core:core:fi_fabric_():1120<info> Opened fabric: TCP-IP
```

**Comment by shefty** [comment]
Hmm... on the client side, inserting the ctrl_sync() before processing the connection event seems wrong.  However, that _should_ not impact the eq_sread on the server.

My guess is that it does because the client needs to wait for the socket to connect before sending a connection message, and the app must read the eq before the connection is considered complete.

So, there's some argument that the test is coded incorrectly, and the sync should occur after the connections have been established.

**Comment by vkrishna** [comment]
Yes, eq_sread would progress the connection establishment. 

@sydidelot tcp used to have the thread for progress but was removed in favor of using eq waitset.

**Comment by sydidelot** [comment]
@vkrishna, I thought that the purpose of `FI_PRORESS_AUTO`  was to progress network communication without the need of calling `eq_sread()`. Shouldn't we create a progressin thread to make sure that the waitset is progressed in case of `FI_PROGRESS_AUTO`?`

**Comment by shefty** [comment]
@vkrishna is out until near the end of January.

I would really like to avoid re-inserted threads into the tcp provider.  That causes all sorts of complications.  Tcp is more like almost auto progress for connections.  It use a 2-step setup, both of which are auto, but doesn't kick off the second step until the app checks that the connection has completed (EQ read).  The EQ read is required by the app in any case.

I have no idea why the test app wants to use some sort of out of band synchronization call in the middle of the connection process.  The connection setup itself can be that sync.  I would actually prefer to change the test to remove the OOB sync in the middle of waiting for fabric events to show up.

**Comment by shefty** [comment]
I have an update to pingpong that allows it to work with tcp -- also tested with udp and rxd.  However, it doesn't work with rxm over tcp.

**Comment by shefty** [comment]
I now have a fix for this issue
```
libfabric:tcp:ep_ctrl:tcpx_pep_listen():924<warn> socket listen failed
libfabric:ofi_rxm:ep_ctrl:rxm_ep_bind():2218<warn> Unable to set msg PEP to listen state
fi_ep_bind(): util/pingpong.c:1474, ret=-9 (Bad file descriptor)
libfabric:tcp:fabric:ofi_wait_fd_del():169<info> Given fd (-1) not found in wait list - 0x616f00
```
The high-level problem is in the pingpong test.  It does an OOB address exchange, which it uses as an input hint into fi_getinfo.  However, it fails to set the address_format, which causes fi_getinfo to leave the src_addr unset.  There should probably be an EINVAL check if the address_format is 0 but src_addr/dest_addr are set on input.

Fixing that allows the test to move forward to a new hang!

**Comment by shefty** [comment]
PR #4691 should fix the test with rxm now as well.

The automatic progress mode for tcp would need a thread
