### ISSUE TITLE
RPM spec file invalid for git snapshot build

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#469]
$ rpmbuild -ba libfabric.spec
    error: line 2: Illegal char '-' in: Version: 0.0.2-dev-123-g381e3a6

I propose that we fix this by conforming to the [Fedora Packaging Guidelines] (https://fedoraproject.org/wiki/Packaging:NamingGuidelines?rd=Packaging/NamingGuidelines#Non-Numeric_Version_in_Release), which specify that snapshot version tags go into the Release field and not the Version field, like this:

    Version: 0.0.2
    Release: 0.20150108git381e3a6%{?dist}

I plan to submit a pull request to implement this unless there are any objections.

**Comment by jsquyres** [comment]
Sounds good!

On Jan 8, 2015, at 1:13 PM, Patrick MacArthur <notifications@github.com> wrote:

> $ rpmbuild -ba libfabric.spec
> error: line 2: Illegal char '-' in: Version: 0.0.2-dev-123-g381e3a6
> 
> I propose that we fix this by conforming to the Fedora Packaging Guidelines, which specify that snapshot version tags go into the Release field and not the Version field, like this:
> 
> Version: 0.0.2
> Release: 0.20150108git381e3a6%{?dist}
> 
> I plan to submit a pull request to implement this unless there are any objections.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by patrickmacarthur** [comment]
@jsquyres: Commit 683224a is my first stab at this.  I don't 100% like it since this will only kick in for daily builds and not for someone manually running `make distcheck`.  I also haven't fully tested it since I am looking at a couple of alternative mechanisms (`distscript.pl` and doing it in `configure.ac`) so that it can work even outside of the daily build script environment, but I figured I'd post something to see if you had any comments.

**Comment by pmmccorm** [comment]
Looking at 683224a, can't you just call rpmbuild and "--define" release, and the version will be substituted by autoconf?

**Comment by patrickmacarthur** [comment]
That could work (it's what I currently do with UNH EXS), but then the person calling rpmbuild has to remember to pass the `--define` option.  Unless we want to also generate RPMs for every daily build, IMHO it would be best to make some part of the build system get the correct version into the spec file.

**Comment by patrickmacarthur** [comment]
Tested the patch and made several bug fixes.  Pull request #479 is my initial proposal to resolve this issue.

**Comment by shefty** [comment]
I'm assuming that the merging of #482 fixed this.  If not, please re-open.
