### ISSUE TITLE
Do not call into psm2 when not needed

### ISSUE THREAD

**Issue by opoplawski** [ofiwg/libfabric#4702]
See https://bugzilla.redhat.com/show_bug.cgi?id=1659852 for more info

Basically we are seeing openmpi 3.1 + libfabric 1.6.0 + psm2 11.2.23 Fedora packages call AVX2 code on machines that do not support AVX2.  It seems that we need libfabric to not try to initialize PSM2 when not needed/available.  Thoughts?

**Comment by opoplawski** [comment]
Well, in order to provide generic packages that work across all hardware libfabric needs to be configured to use psm2.  We're trying to avoid completely dropping psm2 support from Fedora if we can.

**Comment by shefty** [comment]
Well, it's really not libfabric's responsibility to determine if some underlying library (which is installed on the system) has the necessary hardware and software to work.  That's should reside in the underlying library.  How is libfabric supposed to know that libpsm2 isn't needed when it's there and available, and libfabric was configured to include libpsm2 support?
