### ISSUE TITLE
1.7.0rc2 - invalid max inline data running in vm with roce

### ISSUE THREAD

**Issue by jesternberg** [ofiwg/libfabric#4719]
testing with fi_rdm_rdma_simple or other fabtests within the rc2 repo, dmesg shows max inline data size is exceeded and client fail to connect to server.

dmesg snippet:
[  894.661096] rdma_rde: invalid max inline data = 512 > 400
[  894.661110] rdma_rde: invalid max inline data = 448 > 400
[  894.661112] rdma_rde: invalid max inline data = 416 > 400
[  894.661125] rdma_rde: invalid max inline data = 407 > 400
[  894.661129] rdma_rde: invalid max inline data = 404 > 400
[  894.661132] rdma_rde: invalid max inline data = 402 > 400

commands to reproduce are:
sudo modprobe rdma_rxe
sudo rxe_cfg add enp0s3
cd libfabric/fabtests/functional
./fi_rdm_rma_simple -p verbs -e rdm
<in second terminal>
./fi_rdm_rma_simple -p verbs -e rdm localhost

also tried sockets provider and with different ep_type with same behavior.

**Comment by shefty** [comment]
The verbs provider attempts to find the max inline size of the devices.  The different devices all seem to report the max size differently.  Any idea how rxe reports the size?

**Comment by a-ilango** [comment]
> The verbs provider attempts to find the max inline size of the devices. 

Yes. IIRC, there isn't a way through verbs API to find the max inline data size, so we try different sizes when creating QP until we succeed. The error messages correspond to the failed attempts. That shouldn't affect the connectivity. Something else might be going wrong.

**Comment by jesternberg** [comment]
The verbs provider attempts to find the max inline size of the devices.

Yes. IIRC, there isn't a way through verbs API to find the max inline data size, so we try different sizes when creating QP until we succeed. The error messages correspond to the failed attempts. That shouldn't affect the connectivity. Something else might be going wrong.

The errors are the only indication as to what is happening when the client fails to connect. Is there anything else you suggest to try to identify why the client cannot connect using any of the providers or ep types?

**Comment by a-ilango** [comment]
Can you run the test with FI_LOG_LEVEL=warn? That should show fatal errors if any. If not debug level logs would be helpful if you can get it.

**Comment by jesternberg** [comment]
ulimit corrected the issue as well as rc3/repo head.
