### ISSUE TITLE
Performance issue with PMIx

### ISSUE THREAD

**Issue by pierretr** [ofiwg/libfabric#4720]
I observe poor performance when using OpenMPI with libfabric and PMIx.
When setting FI_LOG_LEVEL to debug I get the following output:
~~~
libfabric:psm2:core:psmx2_name_server():158<info> couldn't listen to port 64256. try set FI_PSM2_UUID to a different value?
~~~
This name server is deactivated when PMI_RANK is set but not when PMIx_RANK is set:
https://github.com/ofiwg/libfabric/blob/master/prov/psm2/src/psmx2_init.c#L72

If I manually set PMI_RANK mpi communication performances get back to normal.
Does it make sense to check for PMIx_RANK in psmx2_init_env ?

**Comment by pierretr** [comment]
Sorry the environment variable is PMIX_RANK and not PMIx_RANK ...

**Comment by shefty** [comment]
@j-xiong - Can you update the providers with the correct name?
