### ISSUE TITLE
contrib/buildrpm: Add options for specifying alternative installation prefix and modulepath prefix

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4724]
@jsquyres @martinkontsek 

This would be ideal for what I'm doing for PR #4722 , but I don't feel like it needs to be done immediately given that I can do what I need to do with the -r option. 

What I would like -- is a -P,--prefix option for specifying the install prefix, and a -M,--modulepath option to specify alternative modulepath installations. 

We could tackle this in a separate issue, but it would be nice to specify an alternate version for the libfabric RPM. In development systems, the same RPM might be installed to /opt/... with various versions. I'd like to be able to more finely control the installation path (ex. /opt/libfabric/1.7.0.[build_number].[githash]). I don't think the logic for something like that needs to exist in the script, but being able to specify the opt version string would be nice.

**Comment by jsquyres** [comment]
`-P`/`--prefix` and `-M`/`--modulepath` works for me.
