### ISSUE TITLE
FI_INJECT behavior clarification

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#4783]
@shefty @swelch 

There has been discussion regarding the behavior of FI_INJECT with the fi_*msg function variants. 

It isn't clear how FI_INJECT affects completion behavior, and due to that fuzziness, it isn't clear how it should affect counters. 

In the fi_endpoint man page, there are three separate examples of how selective completion or the lack of it affects certain transactions. 

With FI_SELECTIVE_COMPLETION, and fi_sendmsg using FI_COMPLETION as a flag, it generates a completion as expected. 

With FI_SELECTIVE_COMPLETION, and fi_sendmsg without FI_COMPLETION as a flag, it does not generate a completion as expected.

**However, this is where it starts to get fuzzy.** 

```
fi_tx_attr::op_flags = 0;
fi_ep_bind(ep, cq, FI_TRANSMIT);    // default - completion
fi_send(ep, ...);                   // completion
fi_sendv(ep, ...);                  // completion
fi_sendmsg(ep, ..., 0);             // completion!
fi_sendmsg(ep, ..., FI_COMPLETION); // completion
fi_sendmsg(ep, ..., FI_INJECT|FI_COMPLETION); // completion!
```

With, or without FI_COMPLETION, a completion is generated. However, that would imply that FI_COMPLETION is unnecessary. If FI_COMPLETION was unnecessary, then why is it coupled with FI_INJECT? Does FI_INJECT assume that the completion is suppressed and requires FI_COMPLETION? We've had the discussion internally and I've referenced #724, but the issue is still unclear because of this example. My understanding of FI_INJECT as a flag is that it only affects the buffering of data, and the definition is not clear enough to suggest any affects on completion behavior. **However, the default behavior of the inject functions, and the examples given on the man page might suggest otherwise.** 

Reading the man pages, and trying to interpret the intent between FI_INJECT, fi_inject, fi_inject_write, and FI_COMPLETION -- this approach is rife for opportunities to misinterpret what is presented. **So I'd like to get that clarification into the man pages.** 

In addition to this discussion, I'd like some clarification on how counter increments are handled with the FI_INJECT flag. The fi_cntr man page clearly specifies that counters record the number of requested operations that have completed. So my interpretation here is that if a data transfer operation would generate a completion, then a counter would also increment. However, if a provider would suppress the generation of a completion for any reason, then that would also suppress an increment of the counter in the same manner. So if the above is true, then clarification regarding FI_INJECT would help to set the expectation regarding counters as well.

**Comment by shefty** [comment]
The FI_INJECT flag indicates that the user may re-use the transmit buffer as soon as the call returns.  It has no impact on completions and makes no mention of them.

```
Indicates that the outbound data buffer should be returned to user immediately after the send call returns, even if the operation is handled asynchronously.
```

In the example you referenced above, the EP has been configured to always generate a completion for any operation that can. The FI_COMPLETION flag is ignored.

The inject calls allow for immediate buffer re-use and always suppress completions, regardless of the EP configuration.

```
Example: Omitting FI_SELECTIVE_COMPLETION when binding will generate completions for all non-fi_inject calls:
```

The selective completion discussion only references whether a CQ entry is generated or not.

```
By default, data transfer operations generate completion entries into a completion queue after they have successfully completed. Applications can use this bind flag to selectively enable when completions are generated
...
Although applications typically associate individual completions with either completion queues or counters, an endpoint can be attached to both a counter and completion queue. When combined with using selective completions, this allows an application to use counters to track successful completions, with a CQ used to report errors. Operations that complete with an error increment the error counter and generate a completion event. The generation of entries going to the CQ can then be controlled using FI_SELECTIVE_COMPLETION.
```

**Comment by shefty** [comment]
We can fix-up the wording anywhere things aren't clear.

**Comment by shefty** [comment]
I think there is confusion on when a counter should be updated.  It should match up with the completion 'level' -- i.e. FI_INJECT_COMPLETE, FI_TRANSMIT_COMPLETE, FI_DELIVERY_COMPLETE.

**Comment by jswaro** [comment]
> The FI_INJECT flag indicates that the user may re-use the transmit buffer as soon as the call returns. It has no impact on completions and makes no mention of them.

Ok. To avoid future discussions on topics like this, I'd like to propose that we something to that effect to the documentation. Something like 'FI_INJECT has no impact on completions' would be fine by me. 

> In the example you referenced above, the EP has been configured to always generate a completion for any operation that can. The FI_COMPLETION flag is ignored.

I'd like to pull those examples then since it isn't clear from an initial reading that the flag is ignored. 

> The selective completion discussion only references whether a CQ entry is generated or not.

Right. However, the wording for counters suggests that if a CQ entry is generated, then a counter event would be generated. If CQ events were suppressed, would we expect counter increments to be suppressed as well? 

Specifically, what is the expected behavior here? 

```
fi_tx_attr::op_flags = 0;
fi_ep_bind(ep, cq, FI_TRANSMIT | FI_SELECTIVE_COMPLETION);    // default - completion
fi_writemsg(msg..., flags=FI_INJECT); // Does the counter increment? 

```

**Comment by shefty** [comment]
I will propose a set of changes.

**Comment by bcernohous** [comment]
>Right. However, the wording for counters suggests that if a CQ entry is generated, then a counter event would be generated. If CQ events were suppressed, would we expect counter increments to be suppressed as well?

I'm not aware of counters *ever* being suppressed.  Back to my previous comment 1) about "completions" vs "cq completions".

>I'd like to pull those examples then since it isn't clear from an initial reading that the flag is ignored.

I'm not sure which example you want to pull.  If it's the third, I think it's ok.  It does not use :

FI_SELECTIVE_COMPLETION
    By default, data transfer operations generate completion entries into a completion queue after they have successfully completed. Applications can use this bind flag to selectively enable when completions are generated.

so you always get completions (by default).

**Comment by jswaro** [comment]
```
fi_sendmsg(ep, ..., FI_COMPLETION); // completion 
fi_sendmsg(ep, ..., FI_INJECT|FI_COMPLETION); // completion!
```
I think these two should be pulled since adding the flag has no bearing on the example. If they aren't pulled, a note could be added to indicate the FI_COMPLETION is ignored in the example.

**Comment by jswaro** [comment]
> I'm not aware of counters _ever_ being suppressed. Back to my previous comment 1) about "completions" vs "cq completions".

Bob, my point here is that the counter man page indicates the counter are incremented on a successful completion. We should define what that 'completion' is and what it means. My interpretation is the 'completion' is 'CQ completion' or CQ entry generation. 

My interpretation of the page, is that counters are incremented whenever a CQ event would be generated. 
`Counters can provide a light-weight completion mechanism by suppressing the generation of a full completion event.`
`Counters typically only count successful completions.`

To me, this affirms my interpretation that counters are incremented with CQ event generation. That is why I am raising the question of how FI_SELECTIVE_COMPLETION affects counter increments, because to me, counters and cq events are directly associated by those statements. 

The notion of a non-cq completion in this topic doesn't make much sense to me with respect to counters. If a counter was incremented due to a 'completion' and not a 'cq completion', then what work was actually done? The return code from data transfer functions is sufficient to indicate that custody of the data transfer has been accepted by the provider, so transfer of custody is already covered. Delivery agreements such as FI_INJECT_COMPLETE or FI_DELIVERY_COMPLETE are already covered as well by CQ event generation, so there doesn't seem to be any room for a 'completion' that isn't a 'cq completion'.

**Comment by bcernohous** [comment]
>there doesn't seem to be any room for a 'completion' that isn't a 'cq completion'.

There's a light weight completion that doesn't update the CQ, it's called counters.

Counters can provide a light-weight completion mechanism by suppressing the generation of a full completion event.

**Comment by jswaro** [comment]
I am aware that counters provide a mechanism to avoid the full generation of the information surrounding the completion of an asynchronous network data transfer request by allowing you to simply read a value out of a construct that indicates 'completion' as defined by the endpoint/tx context/domain. 

My point, is that what is represented by that 'increment' must follow one of the existing mechanisms of completion (inject, transmit, delivery...) and that this increment appears to be directly tied to the generation of the completion itself. I think it can simplified to this: Do counter increments happen for every operation, regardless of whether a CQ event would be generated? 

That is simply a different way of asking the same thing I've been asking.

**Comment by bcernohous** [comment]
>Do counter increments happen for every operation, regardless of whether a CQ event would be generated?

I think the answer is "Yes".  At least I've asserted that several times, in several ways, here and in email:

>I'm not aware of counters ever being suppressed. 

What may be newly clarified is *when* are they incremented.  And that would be when a CQ is or could be (selectively) generated.

>I think there is confusion on when a counter should be updated. It should match up with the completion 'level' -- i.e. FI_INJECT_COMPLETE, FI_TRANSMIT_COMPLETE, FI_DELIVERY_COMPLETE.

My #3  - two scenarios (with SELECTIVE completions)

>fi_writemsg(... flags);
>fi_writemsg(... flags | FI_COMPLETION);
>
>Only difference between the two writes is whether a CQ completion is generated. Counter increments are unchanged. 

was written because Steve found a scenario where the counters were incremented at different times in a scenario like this and I do not believe that should be true.

**Comment by jswaro** [comment]
> The FI_SELECTION_COMPLETION flag is only defined when binding an EP to a CQ.

Right, I get that. Conceptually, I think of it as applying a specific behavior to an endpoint with that resource. In this case, I'm asking the completions to be suppressed when binding the CQ to the endpoint, and I think we can be more clear to say that completions are suppressed to the specific CQ that is being bound to the endpoint. Without that, I would intuitively think that it is the case that the suppression is specific only to events for the CQ that I'm binding -- but perhaps the intent was specific to suppressing CQ events in general on the EP. 

I'm not arguing that the second case makes sense, only that the definition could be clearer to indicate how constrained the FI_SELECTIVE_COMPLETION flag is with respect to the generation of events/counters on a given endpoint.

**Comment by jswaro** [comment]
> There's a desire to apply the FI_SELECTIVE_COMPLETION flag from line 1 to the ep <-> cntr binding in line 2, as if this is an EP setting rather than a bind setting. That's wrong.
> Secondly, there's a desire to have FI_INJECT modify the completion generation.

I think the PR hits the right clarifications. I'm not sure there was desire for the above behaviors, but the modifications clear it up well. Thanks for making the modifications.
