### ISSUE TITLE
prov/rxm: Counters for FI_INJECT operations are updated prematurely

### ISSUE THREAD

**Issue by swelch** [ofiwg/libfabric#4803]
In RXM for cases where FI_INJECT flag is used, the associated counter is incremented upon posting the request to the core provider, not when the transfer has completed. The counter update should be done at the actual completion of the operation, even though a completion entry would not be written.

**Comment by shefty** [comment]
Based on reading through the code, counters are updated after reading completions.  Guessing that this issue was fixed a while ago.
