### ISSUE TITLE
undefined ucm_config_modify

### ISSUE THREAD

**Issue by hpjeonGIT** [ofiwg/libfabric#4806]
Hi, 
In CentOS7.5, using gcc/4.8, I am trying to install libfabric. I met errors:
src/.libs/libfabric.so: undefined reference to `ucm_config_modify'
src/.libs/libfabric.so: undefined reference to `ucm_config_modify'
src/.libs/libfabric.so: undefined reference to `ucm_config_modify'

In prov/mlx/src/mlx_init.c:206, status = ucm_config_modify("MALLOC_HOOKS", "no") is found while I cannot find ucm_config_modify() from openucx library. Or is this from other libraries? Any comments are appreciated.

Thanks,

BJ

PS. I tracked the openucx lib, and ucm_config_modify() seems to be deprecated since 1.4x.

**Comment by shefty** [comment]
I would disable the mlx provider from the build and use verbs instead.  The API compatibility of ucx isn't guaranteed (obviously), and almost no effort is going into the mlx provider at this point.  I'll make a note to disable it from the next release.

**Comment by hpjeonGIT** [comment]
Thanks for the update. Will try to do your suggestion.
