### ISSUE TITLE
Document what functionality must be provided, versus which is optional

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#485]
Mechanism is available, but specific functionality needs to be determined.  Intent is to allow providers to optionally support specific functionality.  Some support may require provider specific protocols.  Is there a core set of functions defined that all providers must support?

(From MPI requirements list)

**Comment by shefty** [comment]
See fi_fabric.7.  The listing there can be modified.

**Comment by sayantansur** [comment]
Looks good to me. I'll mark this as done in the MPI listing.
