### ISSUE TITLE
Ability to determine if loopback communication is supported

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#486]
Assumption is that loopback communication must be supported by providers. This is not necessarily a good assumption.

(From MPI requirements list)

**Comment by shefty** [comment]
My vote is to make loopback support a requirement.  I'm not aware of any hardware that doesn't support this.

**Comment by shefty** [comment]
No special handling for loopback addressing is defined.  It should be assumed that loopback works.  We can revisit this if there ever exists a provider that can't talk with itself, though I would argue that it should do so using software emulation.
