### ISSUE TITLE
Support providers built-in or as DSOs for portable libfabric?

### ISSUE THREAD

**Issue by mkre** [ofiwg/libfabric#4894]
We are currently in the process of creating a libfabric build which should 
1. be portable, and 
2. support a reasonable range of providers to be used with Open MPI. 

Libfabric providers can be supported directly by libfabric or as DSOs. It seems like _direct_ provider support can cause libfabric.so to depend on some other third-party libraries, and if those are not found at runtime, it will make the OFI MTL unusable in Open MPI. For example, assuming that we want to support both the psm2 and mlx providers in libfabric _directly_, libfabric.so will depend on the UCX libraries and we will not be able to use Open MPI's OFI MTL for PSM2 communication if the UCX libraries are not installed on the target system. 

So it seems like from a portability point of view, we would like to support _all_ desired providers as DSOs. Is that correct or are there any potential negative side effects (e.g., in terms of performance)? I'm also wondering because, e.g., the official libfabric distribution of RHEL seems to have _direct_ support at least for some providers (granted, the distro guys have full control over satisfying the dependencies).

Thanks,
Moritz

**Comment by shefty** [comment]
When building providers directly into libfabric, the dependencies are per provider.  So, if UCX is not there that will only disable the mlx provider from the build.  Other built providers, such as psm2, are unaffected.

If you build libfabric with those dependencies available, then remove the dependent libraries, then yes, you would hit the issue you're describing.  There shouldn't be any negative effects from only having DSO providers, other than a slight increase in total library sizes.

**Comment by mkre** [comment]
Thanks for the prompt and helpful reply, @shefty!
