### ISSUE TITLE
Add query interface to get full library version string

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#490]
This is something that came up (tangentially) during the discussion of pull request #482.

`fi_version()` produces an API version that is machine-readable, which is useful for testing API compatibility, etc.

However, I think it would be good to also provide a similar function (`fi_version_str()`?) that returns the full version as a string, e.g., "1.3.5", "1.0rc1", or "0.0.2-dev-135-abcdefa", none of which are representable in the current version structure.  This could be presented to the user by libraries and applications that use libfabric, which may be useful for things like bug reporting.

**Comment by shefty** [comment]
The API version is separate from the library release version.  The API version can fairly easily be expanded out using FI_MAJOR and FI_MINOR macros and fed into sprintf or simply printf.

The library release version is a different matter, and I don't think is available currently.

**Comment by patrickmacarthur** [comment]
I make the library version available in UNH EXS by using code like the following:

```C
/* Generated by configure */
#include <config.h>

/* PACKAGE_VERSION is defined in config.h by configure */
static const char version[] = PACKAGE_VERSION;

EXPORT const char *
fi_library_version(void)
{
        return version;
}
```

The `fi_library_version` function can then be used in user code to retrieve the version, for use in things like `mylibfabricapp --version`.

**Comment by pmmccorm** [comment]
These two can be added to fi_tostr() pretty easily if desired, then you can just:

    printf("%s", fi_tostr(version_int, FI_TYPE_VERSION))

**Comment by shefty** [comment]
I like the idea of folding this into the fi_tostr() functionality.

**Comment by patrickmacarthur** [comment]
That plan works for me.
