### ISSUE TITLE
RXM fi_cq_sread() and fi_cntr_wait() 

### ISSUE THREAD

**Issue by swelch** [ofiwg/libfabric#4903]
@shefty @a-ilango:

I have a question about the RXM implementation of fi_cq_sread() and fi_cntr_wait() and their relationship to progress. Both of these calls will initiate progress when called, and as expected will then wait if the CQ is empty or the counter threshold has not been met. However, since they wait on the RXM CQ/Counter wait object in this case (not the core provider wait objects), it seems that progress will not be made again unless another call into the API is made by the application.

Is this the intended behavior, and if so is it then true that fi_cq_sread() and fi_cntr_wait() should not be used with FI_THREAD_DOMAIN threading?

Assuming the above is true, would it be better in the case of a RXM (layered providers) for the fi_cq_sread and fi_cntr_wait to call fi_wait() on core provider wait objects? Which would then initiate RXM progress again when the waiter is awoken.

**Comment by shefty** [comment]
Does the rxm wait object include the core provider wait objects, e.g. via epoll?

I don't get the question about threading.  This is a progress question.

**Comment by a-ilango** [comment]
RxM adds core provider wait objects (CQ and EQ file descriptors) to the epoll. So fi_cq_sread / fi_cntr_wait should wait on them.

**Comment by swelch** [comment]
@a-ilango - Ok, I see now where the core CQ FD is added when the message CQ is created, thank you for the clarification!
