### ISSUE TITLE
tcp: multi-threaded multi-ep send-recv test fails

### ISSUE THREAD

**Issue by mshiryaev** [ofiwg/libfabric#4920]
Hello,

The fail happens on multi-threaded send-recv test. Each thread uses own regular EP, i-th thread on local side communicates only with i-th thread on remote side.

Reproducer:
[tcp_mep_test.zip](https://github.com/ofiwg/libfabric/files/2973376/tcp_mep_test.zip)

on server node
FI_PROVIDER=tcp ./ofi_test_pt2pt 1 <server_hostname> port 

on client node
FI_PROVIDER=tcp ./ofi_test_pt2pt 0 <server_hostname> port 

The fails happen more often on large messages, near 1 MB message size.
Test works well with PSM2 provider (with single/multiple threads) and with TCP provider in case of single thread.

**Comment by mshiryaev** [comment]
@shefty , @vkrishna - please take a look

**Comment by vkrishna** [comment]
Good test 👍 

tcp is using thread unsafe call to verify mr. Replaced it with thread safe one in PR #4921

**Comment by mshiryaev** [comment]
@vkrishna could you please clarify on which path pt2pt operations (which we use in test) call tcpx_validate_rx_rma_data function?

**Comment by mshiryaev** [comment]
although seems I see that rxm can use fi_readv from msg_ep for rndv with large messages
but it still would be great to get your clarification

**Comment by vkrishna** [comment]
Yes rxm uses rma read for large messages as a part of its rndv protocol.

As per my understanding this is the path for tsend or large message through rxm.

-rxm on process P1 sends rndv hdr to the rxm on process P2
- P2.rxm issues rma_read to get the large buffer (follow path rmx_cq_handle_comp->rxm_handle_recv_comp->rx_cq_match_rx_buf->rx_cq_handel_rx_buf->rxm_cq_handle_large_data)
-P2.rxm sends ack once read done
-P1.rxm receives the ack and finishes up
-P2.rxm receives the ack msg sent completion and finishes up

**Comment by mshiryaev** [comment]
@vkrishna many thanks for the fix and for information. I verified fix, test works well. The issue can be closed.
