### ISSUE TITLE
fabtests/runfabtests: timeout only when there's no output

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#4926]
runfabtests.sh script has a fixed timeout. This should be changed to a timeout that monitors the output and expires when there's none for a certain period of time. This would enable running fi_ubertest with more test combinations that would otherwise need a much higher value of static timeout. A  higher static timeout value can increase the overall test run time. There might be some bash trick to accomplish this.

**Comment by shefty** [comment]
Can we just code a different timeout for ubertest as a short term fix?

**Comment by a-ilango** [comment]
> Can we just code a different timeout for ubertest as a short term fix?

Yes, that can be a short term fix.
