### ISSUE TITLE
prov/verbs:  minimal OFED version requirements

### ISSUE THREAD

**Issue by miharulidze** [ofiwg/libfabric#4977]
Hi folks!

Are there any requirements on Intel/Mellanox OFED version in verbs provider?

As far as I understand, there are some checks during configure. It checks that verbs headers exist on current system.

In case when we put precompiled libfabric (and if it depends on OFED version) on machine with very old OFED, it will fails without any human-readable message in debug.
Maybe it will good to add some runtime checks on OFED version somewhere in getinfo?

**Comment by miharulidze** [comment]
> Maybe it will good to add some runtime checks on OFED version somewhere in getinfo?
Found answer to this question here https://github.com/ofiwg/libfabric/issues/4702

**Comment by shefty** [comment]
lbfabric is dependent on libibverbs and librdmacm.  OFED is just some random packaging, which is usually not installed on distro systems.  I'm not aware of any run time checks that can be done against libibverbs or librdmacm.  AFAIK, neither provides runtime version data.
