### ISSUE TITLE
prov/gni FI_SOURCE behaves as if FI_SOURCE_ERR is always selected

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#4992]
In the gni provider, if FI_SOURCE is specified and FI_SOURCE_ERR is not specified, then a message from an unknown initiator should simply report FI_ADDR_NOTAVAIL and not generate an error.  However, the gni provider reports error FI_EAVAIL whether or not FI_SOURCE_ERR is not specified.

**Comment by krehm** [comment]
I have a PR ready for this, how do I get write permission to assign this to myself?

**Comment by hppritcha** [comment]
This issue fixed by #4993. Closing.
