### ISSUE TITLE
prov/gni: messages larger than fi_recv buffer size corrupt adjacent memory

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#5002]
There is no logic in __smsg_eager_msg_w_data() to deal with arriving messages that are larger than the matching posted receive buffer, FI_ETRUNC is not implemented.   An incoming message is matched, then __gnix_msg_copy_data_to_recv_addr() is called to memcpy the incoming message into the matched buffer using the size of the incoming message.  If that size is larger than the size of the receive buffer, or larger than the amount of remaining space in a MULTI-RECV buffer, then the memory following the buffer is overwritten.   Next, __gnix_msg_recv_completion() is called, which uses the minimum of the incoming message size and the receive buffer size to set the 'len' field in the receive completion event.  The application receives an unexpectede successful CQE with the short length, when it should have received a FI_ETRUNC error.

I modified the gnitest cm_basic_send() to issue a fi_send of 8 bytes, and a fi_recv of 4 bytes.

<pre><code>
        uint64_t source = 0xa4321234a4321234,
                 target = 0xb5678901b5678901;

        dbg_printf("before source 0x%lx target 0x%lx\n", source, target);

        sz = fi_send(cli_ep, &source, 8, 0, 0, &target);
        cr_assert_eq(sz, 0);

        sz = fi_recv(srv_ep, &target, 4, 0, 0, &source);
        cr_assert_eq(sz, 0);
...
                ret = fi_cq_read(srv_cq, &cqe, 1);
                if (ret == 1) {
                        dbg_printf("recv cqe.len is %ld\n", cqe.len);
...
        dbg_printf("after source 0x%lx target 0x%lx\n", source, target);
</code></pre>

When the test is run, an unexpected successful 4-byte receive CQE is received, and 4 bytes beyond the receive buffer are destroyed.

<pre><code>
before source 0xa4321234a4321234 target 0xb5678901b5678901
recv cqe.len is 4
after source 0xa4321234a4321234 target 0xa4321234a4321234
</code></pre>

**Comment by krehm** [comment]
The behavior is similar for FI_MULTI_RECV buffers.  I re-enabled the gnitest rdm_multi_r::multirecv_trunc_last test which is supposed to verify that an FI_ETRUNC error is generated when a message is too large to fit in a multi-recv buffer.  I called do_multirecv_trunc_last() with a message size of 2, so two messages of size 2 bytes would be written into a multi-recv buffer of size 3 bytes.  min_multi_recv was set to 1 byte, so the arrival of the first 2-byte message would not trigger the release of the the multi-recv buffer.

I sprinkled many debug messages into the test, see the output snippet below.  Instead of a FI_ETRUNC error, an unexpected second receive CQE with len=1 was received, and the second byte of the second send message (0b) overwrote the fourth byte at 'target', which is beyond the end of the 3-byte multi-recv buffer.
<pre><code>
do_multirecv_trunc_last() called with len = 2
source starting bytes: 0a 0b 0c 0d 0e 0f 10 11`
target starting bytes: 00 01 02 03 04 05 06 07`
post multirecv buffer: msg.context 0x2aaaaab25000, iov.iov_base(target) 0x2aaaae063000, iov.iov_len 3, msg.data(source) 0x2aaaaab25000
send first msg: source 0x2aaaaab25000, len 2, context 0x2aaaae063000
first send cqe: s_cqe.op_context 0x2aaaae063000, s_cqe.buf (nil), s_cqe.len 0, s_cqe.flags 0x802
first recv cqe: d_cqe.op_context 0x2aaaaab25000, d_cqe.buf 0x2aaaae063000, d_cqe.len 2, d_cqe.flags 0x402
source after 1st send: 0a 0b 0c 0d 0e 0f 10 11`
target after 1st send: 0a 0b 02 03 04 05 06 07`
send second msg: source 0x2aaaaab25000, len 2, context 0x2aaaae063000
second send cqe: s_cqe.op_context 0x2aaaae063000, s_cqe.buf (nil), s_cqe.len 0, s_cqe.flags 0x802
second recv cqe: d_cqe.op_context 0x2aaaaab25000, d_cqe.buf 0x2aaaae063002, d_cqe.len 1, d_cqe.flags 0x402
source after 2nd send: 0a 0b 0c 0d 0e 0f 10 11`
target after 2nd send: 0a 0b 0a 0b 04 05 06 07`
[----] prov/gni/test/rdm_multi_recv.c:898: Assertion failed: fi_cq_read should return 0, actually returned 1
</code></pre>

**Comment by hppritcha** [comment]
@krehm are you going to fix this problem?  Otherwise I'll take a look.

**Comment by krehm** [comment]
I'm not going to have time, I'm afraid.  If you could fix it, that would be great.

**Comment by hppritcha** [comment]
okay I'll take a look.  may be tickling a problem the mercury crew is seeing.

**Comment by krehm** [comment]
Interesting; do they have an open issue for their problem?

**Comment by hppritcha** [comment]
sorry I didn't see your question.  No they don't yet, but they've given me core files, etc.
