### ISSUE TITLE
prov/gni fi_av_insert/fi_av_remove

### ISSUE THREAD

**Issue by bcernohous** [ofiwg/libfabric#5048]
I have two entries in my av table.  I remove them, reverse them, and insert them back.  For fun. 😉

They appear to be appended, not inserted, at indices 2 and 3 instead of 0 and 1, even though I expect the av to only be 2 entries.  Entries 0 and 1 do appear to have been removed/are junk.

fi_av_lookup      0, "0001:0x00000010:0x006b7002:01:0x6b7002:0x000000"

fi_av_lookup      1, "0001:0x00000011:0x00440002:01:0x440002:0x000000"

fi_av_remove returned 0

fi_av_insert returned 2

(-22)fi_av_lookup     0, "0001:0xffffffff:0xffffffff:255:0xffffff:0xffffffff:2"

(-22)fi_av_lookup     1, "0001:0xffffffff:0xffffffff:255:0xffffff:0xffffffff:2"

I was using a TABLE, not a MAP, so I had a null fi_addr on the insert.  But I put a fi_addr on the insert and it does come back with addr[0]=2, addr[1]=3.  So lookup on fi_addr[index] sort of shows what I wanted, reversed addrs.
 
     fi_av_lookup     2, "0001:0x00000011:0x00440002:01:0x440002:0x000000"

     fi_av_lookup     3, "0001:0x00000010:0x006b7002:01:0x6b7002:0x000000"

That’s not quite what I expected?

**Comment by hppritcha** [comment]
not sure if this is in correct behavior but will look into it.

**Comment by bcernohous** [comment]
Using FI_AV_MAP works as I'd expect it to.

**Comment by bcernohous** [comment]
>not sure if this is incorrect behavior but will look into it.
I'm questioning it myself.  

I think removing an entry doesn't remove the table row.  So I insert two addresses, remove 2 addresses, add two addresses results in  4 addresses (odd math 2 - 2 + 2 = 4).  2 of which are empty.

**Comment by shefty** [comment]
no action in 2 years.  Is this still an issue, or can we close, even if it's marked as wontfix?

**Comment by bcernohous** [comment]
wontfix is fine with me

**Comment by shefty** [comment]
Thanks - closing.  I'm trying to close all older issues that almost certainly won't be addressed, so we can prioritize and assign people to issues as they are opened, rather than having them linger for years.
