### ISSUE TITLE
PGI compiler support

### ISSUE THREAD

**Issue by hzhou** [ofiwg/libfabric#5049]
I tried to compile `libfabric` with `pgcc` version 18.10 and it doesn't seem to work but fixable. Is there a plan to support pgi compilers?

The issues I discovered:
* pgcc does not support `-Wall`
* asm(".symver "... "\n") -- it needs an explicit new line
* pgcc does not accept the tail (`,externally_visible`) in `__attribute__((visibility("default"),externally_visible))`
* it complains `imm_data is not a member of this struct or union (prov/verbs/src/verbs_msg.c: 137)` -- by pass by `--disable-verbs`

**Comment by shefty** [comment]
I wouldn't say there's a plan to support pgcc, but I doubt there would be objections if someone wanted to provide reasonable updates to support it.  It isn't included in any build testing, so there's a chance of it breaking again unless someone periodically checks it..

**Comment by raffenet** [comment]
We can set this up on the ANL CI server. We are still running nightly FreeBSD regression tests, FWIW. I should configure those to actually report to PRs at some point.

**Comment by nemequ** [comment]
> It isn't included in any build testing, so there's a chance of it breaking again unless someone periodically checks it..

Since you're already using Travis it should be pretty straightforward to set it up, see https://github.com/nemequ/pgi-travis

**Comment by shefty** [comment]
This issue is over a year old without action.  Support for pgcc is not a priority for the active developers.  I don't believe there would be any objection for supporting it, but there appears to be a lack of resources to make this happen.
