### ISSUE TITLE
MPI req: complete FI_MULTI_RECV definition

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#506]
Currently, FI_MULTI_RECV is defined as a flag in fi_msg.3.  Is there a reason why this is not defined for other EP types, such as DGRAM?

Also, fi_msg.3 says that the buffer is *freed* when the available space left is less than the MTU.  Is "freed" the wrong word here -- don't you mean that it simply won't be used for subsequent receives?

Finally, as noted in https://docs.google.com/document/d/1c0A239yVdwRaRg2YIUsQUNP0Om_mcx8my8sAILrCX98/edit#, it looks like fi_getinfo doesn't return FI_MULTI_RECV capabilities yet.

**Comment by shefty** [comment]
fi_msg is referring to the msg operations, not the FI_EP_MSG endpoint type.  So, yes, this flag is usable by all endpoint types that support the msg operations.

'Free' is the wrong word.  It means that control of the buffer is returned back to the application.

**Comment by jsquyres** [comment]
Right -- perhaps I'm being dense, but why is FI_MULTI_RECV only applicable to the message EP type?  I.e., why isn't the same concept also applicable to datagram endpoints?

**Comment by jsquyres** [comment]
Ooohhh.... I see.  I mis-parsed -- it's *not* EP_MSG.  Got it.  Ok, so that point is moot.

**Comment by jsquyres** [comment]
Looks like FI_MULTI_RECV is listed in fi_getinfo.  So -- entire issue is moot/done (I'll do a separate PR for the "freed" issue).
