### ISSUE TITLE
prov/rxm: connection setup with manual control/data progress takes a 'long' time to establish connections

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#5066]
A test that we run has a tendency to time out during the initial stages of the test due to long periods of time of polling the CQ with no CQ events generated by the ofi_rxm provider. It was discovered that a recent modification to the ofi_rxm provider (commit: b83bcb54d92ac5ff74be3b8c66ffb78ff19b312f) changed the frequency that rxm allows the cm event queue to be polled during cq progression functions. This affected the test in a manner that caused connection establishment times to rise from ~0.4s to over three minutes. We have an assertion in the test that if a CQ was not generated in a long period of time (10s was arbitrarily chosen to ensure the test would not run too long if a bug was encountered), that the test would abort. 

@shefty  @a-ilango

**Comment by jswaro** [comment]
I have a PR that I will submit to address the issue. It is based on an adaptive threshold for calling connection management progression functions based on event generation feedback from the underlying provider via rxm_msg_eq_progress. 

I'm not done, but here is the general idea: https://gist.github.com/jswaro/67e5f6fbd77ae5c4fc74e9c9e6ee05de

**Comment by a-ilango** [comment]
Interesting. RXM_EQ_PROGRESS_SPIN_COUNT was chosen as 10k in an arbitrary manner and it gave reasonably good performance in an all-to-all test that I was running.

> This affected the test in a manner that caused connection establishment times to rise from ~0.4s to over three minutes.

I wonder if 10k spin count is too large for the specific environment where this test was run. As long as the spins complete quickly, the CM progress shouldn't take too much of wall time. 3 minutes sounds a lot. Nevertheless, I think adaptive threshold should help slower / busier environments.

A few comments on the patch:
- Do we need the thresholds to be set per endpoint? They can be global.
- We may want to change the greater than threshold check to a modulo one. Otherwise we would progress EQ in quick successions when the eagain count is being reset to 0. I'm assuming "progress the EQ early" is needed only at the beginning of the test.

**Comment by shefty** [comment]
Relying on a spin count assumes an application level behavior, such as busy polling.  If that isn't the case, then a spin count doesn't provide a timing estimate, which is really what's desired.  We could use time stamps in place of spin counts.  I would expect that to introduce more overhead than a simple counter increment.  But the proposed patch is adding quite a bit of overhead and new code.

**Comment by shefty** [comment]
What we could test is using the existing code add a call to fi_gettime_us() in the EAGAIN path, and see how much that impacts the performance.  fi_gettime_us() calls gettimeofday() underneath.  If the impact is too high, we could also test by calling clock_gettime()  (see ft_start() in fabtests).  If either of these provide low enough overhead, they might work better than relying on a spin count.  But this is something that we would need to check first.

**Comment by jswaro** [comment]
I'll drop those in and do some simple tests. 

> Do we need the thresholds to be set per endpoint? They can be global.

We don't need them per EP. I was following the behavior of the msg_cq_eagain_count variable from the original patch. 
> We may want to change the greater than threshold check to a modulo one. Otherwise we would progress EQ in quick successions when the eagain count is being reset to 0. I'm assuming "progress the EQ early" is needed only at the beginning of the test.

Progressing the CQ early is more an aspect of doing a priming read more than a tail-end. When progression is driving at a slower rate due to reduced calls to fi_cq_read, or maybe just a busier application, it makes sense to me to hit the CM events earlier than later. I may be misunderstanding what you mean here.

**Comment by jswaro** [comment]
> Relying on a spin count assumes an application level behavior, such as busy polling.

To some extent, isn't busy polling expected with manual progress in providers where progression is not only done in software, but potentially handles operations that are not visible to the user such as software rendezvous replies?

> a spin count doesn't provide a timing estimate, which is really what's desired

I'd agree with that. It's hard to tell how often an application may call into progression functions, and what we really want here is a certain frequency for checking connection manager events.

>  I would expect that to introduce more overhead than a simple counter increment. But the proposed patch is adding quite a bit of overhead and new code.

One thing to keep in mind, is that all of the currently proposed code is entirely user-space. Time-based functions may invoke a system call depending on implementation, which could cost more due to the context switch from user-space to kernel. It could be better, it could be worse. I'm planning to measure it either way.

**Comment by jswaro** [comment]
I've been running OSU latency, OSU alltoall, and a few other tests this morning. The results between the approaches seem to be same. There is no discernible impact to latency or bandwidth with manual progress with either approach. I have verified that the mechnisms are in-use, so they function as expected. Additionally, for the failing test, connection setup times are better using the timing based approach. This is primarily due to the fact that we would want to check CM events on a time-based frequency rather than based function call frequency. 

If there are other approaches to measuring the impact of the CM polling change, such as the tests that you used with your original commit @a-ilango, I can try to run them if they are available to me.

**Comment by a-ilango** [comment]
> If there are other approaches to measuring the impact of the CM polling change, such as the tests that you used with your original commit @a-ilango, I can try to run them if they are available to me.

I usually run pingpong and all-to-all tests (with full subscription) to ensure there are no increased latencies. Let me run those tests against your PR on our labs to ensure everything's good.
