### ISSUE TITLE
MPI req: Need coherent atomic query

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#508]
From the MPI requirements: Query to determine if atomic operations are coherent with host.

There was a note in Sean's spreadsheet about FI_WRITE_COHERENT, but I can't find the (case insensitive) word "coherent" anywhere in the git repo.

**Comment by shefty** [comment]
I removed FI_WRITE_COHERENT flag from the API.  The idea was to define FI_WRITE_NONCOHERENT, or something like that, if there was ever hardware that wasn't coherent.  Basically, I think all apps will want coherent atomic operations, and all HW that I'm aware of supports this behavior.  So I would rather introduce a NONCOHERENT option later when it becomes needed.

**Comment by sayantansur** [comment]
At some point we would need a flag to indicate this, since MPI implementer needs to know whether network atomics are coherent w.r.t. host atomics. e.g. IB atomics are not coherent w.r.t. host atomics (if not using loopback)

**Comment by shefty** [comment]
Ah, I was thinking of a different thing.  I.e. are the atomic operations coherent with host memory (versus cached by the NIC), rather than coherent with host atomic operations.  That has not been exposed.

**Comment by shefty** [comment]
This feature can be exposed as a capability flag, which a provider can set when true.  However, I'm struggling with what it means to be coherent with the host.  Doesn't this imply a specific implementation of atomics?  For example, using compiler built-in atomics, or using pthread mutex and an integer, or ...?

**Comment by sayantansur** [comment]
It should indicate whether it is safe for the same variable to be updated concurrently using atomic operations from the CPU and the fabric.

For example, InfiniBand standard says that atomics are only coherent with other InfiniBand atomic operations. Since libfabric is a fabric/vendor agnostic library, it isn't clear where the programmer gets this information from. It would certainly be handy if there is a flag somewhere that a provider can set that indicates that this particular system supports atomics coming from both cpu and fabric.

**Comment by shefty** [comment]
This requires defining/identifying *how* the host CPU performs its atomic operations.  Ignore the fabric at the moment.  Two libraries aren't even guaranteed to update memory atomically wrt each other.  They have to use the same sequence of instructions.  So I take back what I said.  This can't easily be captured by a single bit.

**Comment by sayantansur** [comment]
That's probably right, there may be better places where this information is obtained by the user. It isn't libfabric's sole responsibility, as you point out.

@jsquyres : are you OK with classifying this as 'won't fix' in the MPI req document, per Sean's explanation?

**Comment by jsquyres** [comment]
If it's a one-sided issue, and @sayantansur is ok with it, then I'm ok with it. :-)
