### ISSUE TITLE
prov/gni: fi_readmsg asserts if fi_addr_t is incorrect

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#5086]
If fi_readmsg is called with an incorrect fi_addr_t for the source PE, the GNI provider asserts with:

gnix_fr_free: Assertion `(fr->flags & FI_LOCAL_MR) == 0'

Function _gnix_rma() in prov/gni/src/gnix_rma.c calls _gnix_mr_reg() to register local memory and set the FI_LOCAL_MR flag.  A little farther down it calls _gnix_fc_ep_get_vc() to find the VC of the source PE for the read, but the bad fi_addr_t values causes the code to jump to label err_get_vc.  Code at that label does un-register the local memory, but forgets to also clear the FI_LOCAL_MR flag.  Routine _gnix_fr_free() is called immediately after that, which asserts because the FI_LOCAL_MR flag is set.   A simple fix:
```
diff --git a/prov/gni/src/gnix_rma.c b/prov/gni/src/gnix_rma.c
index 0c0329be3..b3023f115 100644
--- a/prov/gni/src/gnix_rma.c
+++ b/prov/gni/src/gnix_rma.c
@@ -1575,8 +1575,10 @@ ssize_t _gnix_rma(struct gnix_fid_ep *ep, enum gnix_fab_req_type fr_type,
 
 err_get_vc:
        COND_RELEASE(ep->requires_lock, &ep->vc_lock);
-       if (flags & FI_LOCAL_MR)
+       if (flags & FI_LOCAL_MR) {
                fi_close(&auto_mr->fid);
+               flags &= ~FI_LOCAL_MR;
+       }
 err_auto_reg:
        _gnix_fr_free(req->vc->ep, req);
        return rc;
```

**Comment by krehm** [comment]
PR #5087 was just opened to fix this issue.

**Comment by shefty** [comment]
#5087 was merged.
