### ISSUE TITLE
MPI req: need to ensure FI_MR_OFFSET is sufficient

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#509]
This is a placeholder for @sayantansur to think about whether FI_MR_OFFSET is sufficient.  E.g., he should make up an example showing that it is good enough.

**Comment by shefty** [comment]
I don't know that we need a solution by 1.0, but we should at least examine the usage model here to see if things are completely broken.

**Comment by shefty** [comment]
@sayantansur @jsquyres  Can we verify that FI_MR_OFFSET works?   Or should it be removed (deferred for a later release)?  Or if something else is needed?

**Comment by sayantansur** [comment]
Sorry, missed this. Checked with Jithin, and there is a FI_MR_SCALABLE test now. Please close this.
