### ISSUE TITLE
MPI req: recover from checkpoint/restart

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#510]
From MPI requirements: if a libfabric-based process is checkpointed and then later restarted, it is probably that the upper layer (e.g., MPI) may know that the process is now in a restarted state (i.e., it is not the original process).  Networking resources are likely stale, and need to be safely closed.

However, libfabric may well not know that it is in a restart state -- if it goes to free various types of handles with associated kernel or hardware state, disaster may occur.

Do we need a way for an upper layer to tell libfabric "this handle is now stale; please discard"?

This is an open question.

**Comment by shefty** [comment]
After 5 years, not seeing this happening anytime soon.
