### ISSUE TITLE
prov/tcp/rxm wrong handling of MR modes through RxM provider

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#5102]
I'm not sure if that should be an RxM provider or a TCP provider issue or both but there is currently (in 1.8.0rc1) a very bad mismatch between MR modes set through hints when calling `fi_getinfo()`. For example, currently setting something other than `FI_MR_BASIC` or `FI_MR_SCALABLE` will result in an MR mode for the domain attr set to 0. This is mostly because of the routine `fi_alter_domain_attr()` in `util_attr.c`.
If you look there:
```C
	if (hints_mr_mode & (FI_MR_BASIC | FI_MR_SCALABLE)) {
		attr->mr_mode = hints_mr_mode;
	} else if (FI_VERSION_LT(api_version, FI_VERSION(1, 5))) {
		attr->mr_mode = (attr->mr_mode && attr->mr_mode != FI_MR_SCALABLE) ?
				FI_MR_BASIC : FI_MR_SCALABLE;
	} else {
		if ((hints_mr_mode & attr->mr_mode) != attr->mr_mode) {
			attr->mr_mode = ofi_cap_mr_mode(info_caps,
						attr->mr_mode & hints_mr_mode);
		}
	}
```
In that particular case, I had set my `hints_mr_mode` to `FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY` which is supposedly the default for most providers. However I discovered that `hints_mr_mode` is set to 3 there, which is what the tcp provider sets, i.e. `FI_MR_BASIC | FI_MR_SCALABLE` in `tcpx_attr.c` Of course doing the `&` of both modes results in a 0 that is then passed to `ofi_cap_mr_mode`. I was then getting errors from RMA transfers because `FI_MR_VIRT_ADDR` ended up not being set.
This needs to be fixed or the manpage/documentation needs to clearly tell to use FI_MR_BASIC instead of the other modes. Currently looking at the manpage for fi_rxm it says:
```
       Memory Region
              FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY  MR  mode  bits
              would  be  required  from  the app in case the core provider re‐
              quires it.
```
That's very ambiguous and misleading since FI_MR_BASIC does not map to those bits or the comparison is not done correctly in the code.

**Comment by shefty** [comment]
FI_MR_BASIC and FI_MR_SCALABLE are there for backwards compatibility.  If you switch to using the new mr_mode bits, then the provider can clear those bits when they are not required.  That is, if the app asks for FI_MR_BASIC, then the provider must either support that option as fully defined (use of virtual addresses, provider allocated keys, and buffers must be allocated), or fail the request.  This is the problem that the new mr_mode bits address -- the separate requirements are no longer grouped together.

If the app instead sets mr_mode bits individually, the provider can clear them, which allows for a simpler (more scalable) use case.  The text from the fi_rxm man page is indicating that it simply passes the mr_mode bits mentioned directly through from the core provider to the application.

I believe the behavior here is correct.  If your app only supports the case where all 3 requirements are needed, then you will want to set FI_MR_BASIC.  If you set the bits individually, then the app must be able to respond to any or all of them being cleared.

**Comment by soumagne** [comment]
Hmm ok... so are you telling me that I am responsible for falling back to FI_MR_BASIC if I get a 0 in the MR mode bits field? I mean that's fine with me but I really don't think I should have to check whether providers are setting backward compatibility flags by default. I'm perfectly fine with providers clearing some of the bits that are not supported by default as long as things work :) but I would expect you to check whether those new flags are equivalent to FI_MR_BASIC? The tcp provider currently only defines FI_MR_BASIC | FI_MR_SCALABLE... my understanding is that FI_MR_BASIC is there for backwards compatibility and that I should not have to use it anymore, here I am clearly forced to use it?

**Comment by shefty** [comment]
I'm not saying the app is responsible for falling back to FI_MR_BASIC.  I'm saying if the app sets any of the mr_mode bits other than BASIC or SCALABLE, then it must be able to handle those bits being cleared by the provider.  Mode bits are a requirement on the application in order to achieve good performance, not the provider.

**Comment by soumagne** [comment]
OK... well that seems pretty equivalent to me at the moment :) if I want FI_MR_BASIC behavior with the new bits, what am I supposed to do then? the tcp provider is going to clear all of the new bits anyway because it only sets FI_MR_BASIC | FI_MR_SCALABLE in the domain attributes... so basically what you're saying is that I should be prepared to be using the backward compatibility flags? What should the app be doing if everything is cleared out?

I just read the documentation:
```
     Basic Memory Registration
              Basic  memory  registration  is  indicated  by  the  FI_MR_BASIC
              mr_mode bit.  FI_MR_BASIC is maintained for  backwards  compati‐
              bility  (libfabric version 1.4 or earlier).  The behavior of ba‐
              sic registration is equivalent to setting the following  mr_mode
              bits    to    one:    FI_MR_VIRT_ADDR,    FI_MR_ALLOCATED,   and
              FI_MR_PROV_KEY.  Additionally, providers that support basic reg‐
              istration usually required FI_MR_LOCAL.  FI_MR_BASIC must either
              be set alone, or in conjunction with FI_MR_LOCAL.  Other mr_mode
              bit  pairings  are  invalid.   Unlike  other  mr_mode  bits,  if
              FI_MR_BASIC is set on input to  fi_getinfo(),  it  will  not  be
              cleared  by  the  provider.  That is, setting FI_MR_BASIC to one
              requests basic registration.
```
Clearly it does say I should be using FI_MR_VIRT_ADDR, FI_MR_ALLOCATED,   and FI_MR_PROV_KEY to get FI_MR_BASIC equivalent behavior. I would be fine if a provider does not support some of those bits or clears some as long as I have some remaining bits that are still set :)

**Comment by soumagne** [comment]
And I see what you mean and what I should do in that case and check for those bits before doing any operation but it still does seem odd to me and would force me to change behavior in doing RMA etc simply because a provider only supports the backward compatibility flags. Anyway I guess I'll just stick with the compatibility flags for now. I think you should document that the tcp provider only supports those backward compatibility MR flags though.

**Comment by shefty** [comment]
I still think you're viewing the mode bits as opposite of their intent.  They are requirements *on the app*.  The tcp provider has *no requirements*.  The tcp provider supports all the flags.  It doesn't place additional requirements on the app.  This is equivalent to supporting the older 'FI_MR_SCALABLE' as the default. 

Examples: TCP does not require that the application have physical memory backing virtual addresses at the time memory is registered (ALLOCATED).  That doesn't mean the app can't have physical memory backing the virtual address; tcp just doesn't require it.  As a result, the app could create a single MR spanning its entire virtual address space.  That's not possible when ALLOCATED is set.

For VIRT_ADDR and PROV_KEY, tcp uses 0-based addressing and user defined keys.  This means that apps do not have to exchange addresses and keys with peers prior to their use.  However, an app may still perform the exchange.  The base address would just be 0, and the key set to whatever the app requested.

If the providers return the same mode bits that were passed into fi_getinfo(), the result is that apps would never be able to take advantage of available of the optimizations mentioned above.  It would always fall back to a less scalable path.

The mr_mode bits behave the same as the fi_info::mode bits.  The exception is that BASIC and SCALABLE maintain their original API definition for compatibility purposes.

**Comment by soumagne** [comment]
Thanks for the explanation, it does correct my view. Now though if I take word for word what you said:

> For VIRT_ADDR and PROV_KEY, tcp uses 0-based addressing and user defined keys. This means that apps do not have to exchange addresses and keys with peers prior to their use. However, an app may still perform the exchange. The base address would just be 0, and the key set to whatever the app requested.

That's exactly when problems started to occur for me because I was not passing the base address as 0, and if I do that and exchange keys etc then I get errors telling me that my RMA descriptor is not valid because `ofi_mr_map_verify()` returns `-FI_EACCES` in that case when it does that check:
```C
        addr = (void *) (*io_addr + (uintptr_t) attr->offset);
        if ((addr < attr->mr_iov[0].iov_base) ||
            (((char *) addr + len) > ((char *) attr->mr_iov[0].iov_base +
                                      attr->mr_iov[0].iov_len))) {
                return -FI_EACCES;
        }
```
The reason it fails that check is because the attr->offset value is no longer 0. And the reason it is not 0 is because of the way the insert checks for the MR modes:
```C
int ofi_mr_map_insert(struct ofi_mr_map *map, const struct fi_mr_attr *attr,
                      uint64_t *key, void *context)
{
...
        if (!(map->mode & FI_MR_VIRT_ADDR))
                item->offset = (uintptr_t) attr->mr_iov[0].iov_base;

        if (!(map->mode & FI_MR_PROV_KEY)) {
                if (ofi_rbmap_find(map->rbtree, &item->requested_key)) {
                        free(item);
                        return -FI_ENOKEY;
                }
        } else {
                item->requested_key = map->key++;
        }
...
}
```
`(map->mode & FI_MR_VIRT_ADDR)` being 0 will then force the offset as the base address because  `map->mode` ended up being 0. If on the other hand I set `FI_MR_BASIC` then in `ofi_mr_map_init()` it will default `map->mode` to `OFI_MR_BASIC_MAP`, which is `(FI_MR_ALLOCATED | FI_MR_PROV_KEY | FI_MR_VIRT_ADDR)` so then my offset remain 0  and the base address is fine.

So is the right fix in my code to check whether the `FI_MR_VIRT_ADDR` mode bit has been cleared? And if it has been cleared, then set the base address to 0? Hopefully I'm getting there :)

**Comment by shefty** [comment]
Correct.  If FI_MR_VIRT_ADDR is 0, then you should provide a base address of 0 to the peer.  Otherwise, the base address is the VA of the buffer.  You should always be able to obtain the key using fi_mr_key().  If FI_MR_PROV_KEY has not been set, though, you'll need to ensure that a new key is generated for each registration.

**Comment by soumagne** [comment]
Great thanks! that was very helpful.
