### ISSUE TITLE
Util code remaining timeout calculation in loop can prematurely cause timeouts

### ISSUE THREAD

**Issue by swelch** [ofiwg/libfabric#5108]
@a-ilango - In several functions (e.g. util_wait_fd_run(), ofi_cntr_wait(), ofi_cq_sreadfrom()) the timeout can be prematurely reached due to decrementing the timeout repeatedly within a loop based on the current time and start time. i.e. once there is delta between current time and start time that time is decremented from timeout every time through the loop. Instead it probably should maintain a time_remaining count based on timeout and current time less start time, or calculate an end_time and determine the timeout remaining in the loop from the end_time and current time.

**Comment by shefty** [comment]
I will look into this.
