### ISSUE TITLE
When using rxm/verbs when fi_cntr_wait() is called the receipt of EQ events is not causing progress

### ISSUE THREAD

**Issue by swelch** [ofiwg/libfabric#5109]
@a-ilango - I see that the EQ FD is added to the counter wait object. What I'm seeing is that when fi_cntr_wait() is called, that in the call util_wait_fd_run(), fi_epoll_wait() returns 1. The loop then continues and the call wait->util_wait.wait_try() returns 0, so the code then calls fi_epoll_wait() again (which returns 1 again). This repeats until the timeout occurs.

**Comment by a-ilango** [comment]
That's weird. Are you able to see if we get any event on EQ or CQ read as part of calling the try function? If they return events, the try function should return EAGAIN and the control should exit the loop.

**Comment by swelch** [comment]
> That's weird. Are you able to see if we get any event on EQ or CQ read as part of calling the try function? 
That was my thought too :)

I might see the error: It looks like the Verbs message provider trywait, fi_ibv_trywait(), always just assumes we are ready to wait if the class is FI_CLASS_EQ. So I think it will return 0 regardless if the EQ FD is ready and so we will not get the EAGAIN to break out of the loop.

**Comment by a-ilango** [comment]
Hmm. So this would happen when only EQ has events.

> If poll returns > 0 in util_wait_fd_run() , can we just return and not rely on the trywait call to terminate the loop?

Yes, that should work. Either that or modify verbs EQ trywait code to check rdmacm EQ and enqueue any events to the internal software EQ. @shefty any thoughts on this?

**Comment by shefty** [comment]
Does the EQ have an existing SW queue associated with it?  If so, then trywait should return EAGAIN if there is something queued on it.

I can't think of an issue breaking out of util_wait_fd_run() if poll > 0.  I would try that approach first.

**Comment by a-ilango** [comment]
I think the reason to call trywait again was probably to avoid any spurious wakeups? I can update verbs provider EQ trywait to check the SW queue for any available events.

**Comment by a-ilango** [comment]
It seems we would also need to read events from rdmacm event channel in case the SW queue is empty. As we won't know the size of the event being received, I think it's probably better to go for the other approach (skip trywait when poll > 0).

**Comment by swelch** [comment]
We need to handle when only eq->channel RDMA CM fd is ready, that EAGAIN is returned in trywait (or return when poll > 1 and skip trywait). Is checking only the SW queue enough?

**Comment by swelch** [comment]
> We need to handle when only eq->channel RDMA CM fd is ready, then EAGAIN is returned in trywait (or return when poll > 1 and skip trywait). Is checking only the SW queue enough?

@a-ilango - Sorry, did not see your above post. Please disregard.
