### ISSUE TITLE
MPI req: triggered operations

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#511]
fi_trigger.h exists right now, but may get dropped in v1.0 because no one is currently implementing it.

Need someone to go take a hard look at fi_trigger.h and see if it is a good proposal / can be implemented.

**Comment by sungeunchoi** [comment]
FWIW, I agree that triggered ops should receive more scrutiny, but from an consumer's point of view they seem very useful.  For example, they are well suited for object-based collective operations such as those provided by Chapel and Charm++.

**Comment by shefty** [comment]
Triggered operations are implemented by the sockets and psm provider.  They are limited by the current definition, but I believe that the API is generic enough that additional trigger mechanism can be supported.   In theory all operations are triggerable.
