### ISSUE TITLE
prov/gni: problems with routine __gnix_msg_unpack_data_into_iov()

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#5169]
I am unfamiliar with this code, so I will only point out what I believe are
problems with the implementation of routine __gnix_msg_unpack_data_into_iov,
and will leave any required code changes to be made by others more familiar
with the code.

The routine is written using static variables i, cum_len, and offset.  The
expectation seems to be that the routine will be called multiple times in a
row with the exact same values for dest and dest_cnt, but different values
for src and src_len, and locking somewhere would prevent calls to this routine
by other threads in the interim.   I don't see these guarantees in place.

The only time that variables i, cum_len, and offset get set back to zero,
their initial values, is if the src_len bytes that were copied into dest
happened to exactly fill to the end of dest[dest_cnt].  That seems like
an unlikely occurrance.  If those variables don't get set back to zero,
and if the routine is then called for a different req->msg.recv_info, it
seems like data will be copied to the wrong location.

Assume that src_len is less than the remaining space in dest.  Variables
i and offset will be left with their current static values.  If the next
call to this routine is for a different req->msg.recv_info, the src/src_len
data in that call will be copied into that recv_info at the wrong offset.

Assume that src_len is greater than the remaining space in dest.  The
while loop will run to completion.  Variables i and offset will be left
pointing to dest[dest_cnt].recv_addr + dest[dest_cnt].recv_len, beyond
the end of the array.   And cum_len will be left with a non-zero value,
so the next call for some other req->msg.recv_info is going to copy
data to some undefined location.  There is no notification back to the
caller of the routine that all the src data did not fit, requiring that
an error CQE event be posted for the truncated message.

I don't understand this code well enough to fix it, I will leave it for
bigger brains to handle.

**Comment by hppritcha** [comment]
not fixing, closing
