### ISSUE TITLE
Shared receive context: fi_recv - src_addr

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#523]
Is the src_addr argument supported for fi_recv when posting it to a shared receive context? What would be the behavior when source address is specified and when not specified (FI_ADDR_UNSPEC)?

**Comment by shefty** [comment]
Added note: a shared receive context is not associated with an AV, so there's no easy way to identify what the src_addr references.  It may be that a shared receive context must be associated with endpoints that also share an AV.
