### ISSUE TITLE
prov/gni: progression thread exhibits high latency

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#5234]
Over the past several months I have been testing gni libfabric with a client/server application, trying to find the sources of all latency that occurs with messages sent from client to server and back again.  Using a Cray-XC, I ran UGNI library ping-pong benchmarks showing that an initiator can get its send CQE back for a sent message back in just a hair over 1 usec, and a ping-pong round trip of messages between the client and server completes in just over 2 usecs.

Performing a similar ping-pong test with GNI libfabric, I was seeing latencies in the range of 35-40 usecs in each direction.   It turns out that the excess latency is caused by routine __gnix_wait_nic_prog_thread_fn(), which gets awakened whenever an application thread goes to sleep in a blocking function like fi_cq_sreadfrom().

Function __gnix_wait_nic_prog_thread_fn() is a loop, when awakened it goes through all send and receive work queues in libfabric looking for work do to, and performs whatever work is pending.  After making a complete pass through all work queues, it calls usleep() to sleep N seconds, where N is a configurable value that defaults to 20 usecs.   During my testing I reconfigured this value to be 1 usec but saw no noticeable improvement in latency.

I turns out that usleep() has a minimum delay of 54 usecs on my test Cray-XC, no matter what value that you pass as a parameter.  This explains the excess latency, if I comment out the usleep() call and re-run the ping-pong benchmark, I get similar round-trip latencies to that seen with the UGNI benchmark.

One possible solution would be to modify this function to keep track of whether or not any work was performed while going through its loop.   As long as work is performed, the usleep() call could be skipped, minimizing the latency on any subsequent messages.   If N seconds pass with no work performed, then the function could start calling usleep() again.

**Comment by jswaro** [comment]
In general, I believe those usleep calls should probably be a yield().

**Comment by hppritcha** [comment]
closing, not fixing.
