### ISSUE TITLE
man: inconsistent statements about FI_MR_LOCAL and FI_MR_BASIC

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#5239]
In the man page of fi_domain:

>       FI_MR_BASIC
>              ...... This flag may not be used in conjunction with other mr_mode bits......

In the man page of fi_mr:
>       Basic Memory Registration
>             ...... Additionally, providers  that  support basic registration usually required
>             FI_MR_LOCAL.  FI_MR_BASIC must either be set alone, or in conjunction with 
>             FI_MR_LOCAL.  Other mr_mode bit pairings are invalid....... 

For reference, the current utility code for checking mr_mode bits doesn't allow FI_MR_LOCAL
to be used together with FI_MR_BASIC.

**Comment by shefty** [comment]
See #5236

**Comment by j-xiong** [comment]
Thanks, that clears the confusion.
