### ISSUE TITLE
fi_endpoint(3) has strange C++ snippet in example code

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#524]
Go [here](http://ofiwg.github.io/libfabric/master/man/fi_endpoint.3.html) and search for `::op_flags`.  It looks like this:

```
fi_tx_attr::op_flags = 0; // default - no completion
  fi_ep_bind(ep, cq, FI_SEND | FI_COMPLETION);
  fi_send(ep, ...);                   // no completion
  fi_sendv(ep, ...);                  // no completion
  fi_sendmsg(ep, ..., FI_COMPLETION); // completion!
```

I'm not 100% sure what was intended here, but if very vague pseudocode was intended, then a comment would probably be better here than some C++ code that refers to a static member of a global structure/class that doesn't really work that way.

**Comment by shefty** [comment]
It's example pseudocode.  The are comments which describe this behavior.  The example is simply to make the intent clearer to a reader.

**Comment by goodell** [comment]
If it's really the desired text, then I withdraw my objection.  It just feels strange whenever I read it.
