### ISSUE TITLE
performance degradation for multithreaded verbs;ofi_rxm in 1.8.0

### ISSUE THREAD

**Issue by carns** [ofiwg/libfabric#5244]
I haven't been able to distill this into an easily shareable/reproducible test case, but we've encountered an extreme performance degradation (> 100x drop in throughput) when using verbs;ofi_rxm in some multithreaded scenarios in 1.8.0.  Performance is fine in 1.7.2, and performance is also fine in 1.8.0 if we run the workload in a single-threaded configuration.

The `perf` tool indicates that they key difference is that the 1.8.0 version is spending most of it's time in pthread_spin_lock() when run in multithreaded configurations.  I haven't been able to attribute it to a specific invocation yet, though.

From browsing the libfabric code, I see that pthread_spin_lock() is called via fastlock_acquire().  I don't see any blatantly obvious problems in the verbs or rxm providers in the changes from 1.7.x to 1.8.x, but I did notice some oddities in the mr cache code.

For example, this code shows a system call being made while a spinlock is held:
https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_mem_monitor.c#L222

... and this code shows a fairly complex cache flush subroutine being called while a spinlock is held:
https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_mr_cache.c#L162

I don't know that those examples (or any others) are the source of my specific problem, but at any rate there seems to be a spinlock problem somewhere in 1.8.0.  Has anyone else observed this?

@shanedsnyder @soumagne @vschhabra

**Comment by carns** [comment]
I was able to produce a proper call graph profile with help from @kevin-harms.  Here is an abridged version, in pdf form, showing the call paths that lead to spinlocks in libfabric:

https://drive.google.com/open?id=18BcdGYzzMowkYw6VoCayHLJw7MvPMwx_)

The workload that was executed to generate this caused a single process (a server daemon in this case) to issue quite a few concurrent memory registration and deregistration calls.  That could probably be optimized in this specific case, but it something that we will continue to hit in other cases regardless.

There are a few caveats with this profile: it's only a few hundred samples (a short run) and the performance actually did not *entirely* collapse in this example, because there were adequate cores available to allow several threads to busy spin and still make progress eventually, but the profile is consistent with what we see in other runs and with other profiling tools.

For some reason this trace (collected with google perf tools, using a code stack compiled with -g and -fno-omit-frame-pointer) omits at least one stack level in the visualization.  This graph makes it look like fi_ibv_mr_cache_close() and fi_ibv_mr_cache_reg() are the ones calling spinlocks (which are represented with hex addresses at the bottom), but perusing the code it's seems pretty clear that these functions are actually just relaying to the generic ofi_mr_cache_delete() and ofi_mr_cache_search() functions.  Maybe compiler optimizations are collapsing those.

At any rate, it looks like `ofi_mr_cache_search()` and `ofi_mr_cache_delete()` are the specific functions that are holding spinlocks longer than they should for our workload.

**Comment by carns** [comment]
I think these code locations are the key:

https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_mr_cache.c#L287
https://github.com/ofiwg/libfabric/blob/master/prov/util/src/util_mr_cache.c#L173

Naively I would guess that cache->monitor->lock simply needs to be a different kind of mutex (not a spinlock), but it's also possible that the code blocks that they protect are doing something unexpected.  In other words, I don't know if the spinlocks are the problem or the symptom.

**Comment by shefty** [comment]
You can try setting the environment variable FI_MR_CACHE_COUNT = 0.  That will disable the memory registration cache.

**Comment by carns** [comment]
Thanks @shefty , I'll try that and see if it confirms the source of the problem.  The system that I was reproducing this on has been down for maintenance so I haven't been able to look at it in a few days.

**Comment by carns** [comment]
Hi @shefty, I tried setting FI_MR_CACHE_COUNT=0 and it didn't seem to have any effect (the performance still collapsed in the multithreaded test case).  I've opened a pull request linked to this issue that just swaps out the spinlock for a mutex and now performance is as expected.

**Comment by carns** [comment]
Confirmed the `FI_MR_CACHE_MAX_COUNT=0` behavior!  My build isn't precisely 1.8.1rc1; it is a snapshot of origin/master that is very similar.  Regardless, if I set that environment variable, then it exactly matches the performance that we were seeing in 1.7.1 for this workload.

That's a welcome workaround for us.

I would be curious if there is a way to have a cache without serializing registration.  I have not looked at that code, but in the abstract sense you probably only need to serialize attempts to register/deregister the same (or overlapping) regions.  The *intent* to register a particular region (and later completion of that action) definitely needs to be atomic so conflicts can be detected and serialized, but the actual registrations themselves (presumably the expensive part) should be legal to do concurrently when they don't conflict?

Something like that might also make spinlocks viable again if the critical region they protected were a data structure describing in-progress registrations rather than the actual act of registering.  In some sense this might be a lock granularity problem.

**Comment by shefty** [comment]
That's good to hear.

I've already starting thinking about how to avoid full serialization when going through the cache.  You're correct that the serialization is there to handle same and overlapping regions.   So some sort of state would need to be maintained to know if a registration is in process, and only overlapping regions need to serialize.

Locking at a per region level might work, provided that reference counting ensures we can't free locks that we're waiting to acquire.  I'll continue to look into this, since so far, multi-threaded users haven't been a high priority.

**Comment by wckzhang** [comment]
I wanted to add a point:

In 1.7.0, verbs was incorrectly using the cache. The cache calls required locking around them, which verbs was not doing. Thus it was performing the operations in a non thread safe manner.

Thus the main difference in 1.7 and 1.8 is that verbs did no locking at all in 1.7 and it does locking in 1.8

I do recommend not using 1.7 for multi threaded applications due to this issue, more information can be found here: #4802

**Comment by shefty** [comment]
The cache was disabled by default in 1.7.  It has other issues (like doesn't really work) even without the multi-threaded problems.  1.8 has an entirely different cache implementation and is enabled by default.

So, 1.7 should be usable as-is.  It's only the enabling of the cache that causes issues.

**Comment by wckzhang** [comment]
Ah makes sense, I forgot verbs had it disabled by default before as well.
