### ISSUE TITLE
Need fi_cq_readfrom to work for connected EPs

### ISSUE THREAD

**Issue by DougSO** [ofiwg/libfabric#5257]
Using a Shared Rx context and 1 CQ with connected endpoints is very much like running connectionless: when a message is received, we don't have an easy way to determine the source of the message.  The CQ entry does not have the endpoint in it and AVs don't work with the TCP or verbs provider (thus you cannot use fi_cq_readfrom).

We need a way to get the functionality of fi_cq_readfrom() to work with connected EPs.  Rather than an fi_addr_t, it could return the fid_ep pointer for the EP the message came in on.

This needs to be done so a mix of connected and unconnected EP can operate together with the same CQ.

**Comment by shefty** [comment]
I've started working on a patch for this.  After looking at this, IMO the best option is to define a new fi_cq_ep_entry format that can be used to report the local EP associated with a completion.  That appears to be the easiest for maintaining backwards compatibility and for apps to use.
