### ISSUE TITLE
prov/verbs: feature request - support for defining PKEYs and SL

### ISSUE THREAD

**Issue by lflis** [ofiwg/libfabric#5263]
Some HPC sites are using QOS for Infiniband to assure priority for MPI traffic.
This requires ability for defining PKEY or SL in communication layer. PKEY defines which infiniband partition to use, SL defines Service Level field in LRH header which is used for mapping traffic classes to Virtual Lanes.

Examples:
 - DAPL  - allows seting pkey or sl via DAPL_IB_PKEY and DAPL_IB_SL environment vabiables
 - OpenMPI verbs transport allows to select it via btl_openib_ib_service_level,  btl_openib_pkey

Please consider adding such functionality if it's not against the design goals.
The easiest way and most flexible way is to use env variables for selecting those values

**Comment by jswaro** [comment]
I believe that authorization keys were design with the pkey feature in mind, as well as others. 
You might also find #5148 to be a potential starting point for setting the IB service level within the provider.

**Comment by lflis** [comment]
@jswaro thanks for pointing this out. I'll have a look how this can be used for setting pkeys however ability to set SL independently might be desired in some situations

**Comment by jswaro** [comment]
No problem. Verbs doesn't currently support authorization keys but it should be relatively simple to add it. Traffic classes/Service level are a coming feature that is not fully fleshed out yet, but should work for what you need here.

**Comment by shefty** [comment]
Having QoS controls aligns with the design goals.  The traffic classes being defined now are a better fit for specifying QoS than authorization keys.

A couple of notes:  The pkey is determined based on the mapping of the IP address.  SL really needs to be a protected value, with the setting controlled by the kernel or some privileged entity.  The app can request an SL, but should not be able to set it directly, again for security and to avoid potential subnet deadlock conditions.  It's possible to associate an SL with an Infiniband service identifier at the SA/SM.  The service id contains a mapping of the transport port number.  So apps that request a specific port (range) can be assigned a specific SL.  By controlling which address the apps use, that will select the pkey.

**Comment by shefty** [comment]
If there's a mapping from the user space SL to a kernel SL, that's new since I last looked (which, granted, has been a long, long time now).  In any cast, I believe the SL can be controlled indirectly by assigning an SL to a service_id / port range at the SA.

**Comment by lflis** [comment]
@shefty in the most recent OFED  (MLNX_OFED_LINUX-4.6-1.0.1.1) on Centos 7.6 there is no restriction such. When creating QPs as a user you can select any SL from 0-15, and if there's no mapping for portrange/ulp in subnet manager, ib packets will leave HCA with a desired SL number in LRH header.
Confirmed today with Intel MPI (DAPL transport) run as unprivileged user on one of our clusters
