### ISSUE TITLE
unify logging for libfabric and providers

### ISSUE THREAD

**Issue by pmmccorm** [ofiwg/libfabric#527]
Create one true set of macros/functions for logging used across all providers and libfabric. Otherwise all providers end up reinventing the same macros. Prefix them like:

    libfabric: msg logged to stderr from fabric.c
    libfabric:provider: msg logged to stderr from provider

So that messages can be easily grepped. Define three macros:

FI_DEBUG - debug printing, compiled out of non debug builds
FI_WARN - warnings that unconditionally print important errors/conditions
FI_LOG - enabled by environment variable FI_LOG_LEVEL=N

**Comment by jsquyres** [comment]
:+1: 

@goodell and I were just talking about something like this yesterday, actually.  :-)

**Comment by goodell** [comment]
@pmmccorm are you implementing this right now?

**Comment by pmmccorm** [comment]
I'm not, go for it!

**Comment by goodell** [comment]
working on this today as part of tracking down a bug w.r.t. fi_msg_pingpong and provider selection
