### ISSUE TITLE
fi_endpoint: TRANSMIT CONTEXT ATTRIBUTES: size description is wrong, should be maximum not minimum

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#5301]
In the fi_endpoint man page, the TRANSMIT CONTEXT ATTRIBUTES section describes the various attributes.  For the 'size' description, it states:
    The  size of the context.  The size is specified as the minimum number of transmit
     operations that may be posted to the end-point without the operation returning -
     FI_EAGAIN.****

The statement says "minimum" when it should be "maximum" number of transmit operations.

**Comment by shefty** [comment]
Minimum is intended.  The provider can size the endpoint larger, such as rounding up to the next power of 2.

**Comment by tonyzinger** [comment]
As an application programmer, if I try to send equal to or more than "size" messages, I receive the fi_eagain error.  This means that it is the maximum number of messages that can be sent before a receive needs to be done to accept the messages.

Yes, the provider can change this value to whatever they want to.  But this is still the maximum number of outstanding messages that can be sent at one time.

**Comment by shefty** [comment]
In your provider's case, the minimum equals the maximum (with a possible off by 1 error).  You should be able to send at least 'size' messages before getting EAGAIN.  It's intended as a lower bound, not upper.

Note that EAGAIN can be returned for other reasons than the local queue being full. That should be indicated in the man pages in this area.

**Comment by tonyzinger** [comment]
Yes, my statement about "equal to the SIZE number of messages" was incorrect.  It should have been only "greater than" the SIZE number of messages.

After rereading the SIZE description, the problem in the documentation is using "minimum" and "without".

In the documentation, I believe it would be better worded as:
The size of the context. The size is specified as the MAXIMUM number of transmit
operations that may be posted to the end-point BEFORE the operation RETURNS -
FI_EAGAIN.

**Comment by shefty** [comment]
It may be useful to understand 2 specific examples of how size relates to HW resources.

Case 1: The size is the number of commands that can be written into a transmit queue.  Here, size is the size of the queue. Each transmit command consumes one entry.  This is the verbs HW model.

Case 2: The size is the number of iovec entries that can be written into a transmit queue.  Here, size is related to the number of iovecs each transmit requires, and not directly to the number of commands that are issued.  This is the usNIC model.

Software can emulate either option above, based on which is most convenient or efficient.

For case 1, size maps to the size of the queue, but the queue size may be increased to the next power of 2.  So a size of 100 can result in a queue size of 128, meaning that the user can post up to 128 transfers before hitting EAGAIN.

For case 2, the size provided by the user ends up being adjusted.  If the provider reports that it can support up to 4 iovecs per transfer, then the queue size = 4 x 100 = 400.  This too might be rounded up to the next power of 2, but for simplicity, assume it stays at 400.  The app can now post either 400 commands, each with an iovec count of 1, or 100 commands, each with an iovec of 4, or something in between.

In both of these examples, the size provided by the user is the lower bound.
