### ISSUE TITLE
RFC: make CQ and EP progress functions take a max_count arg

### ISSUE THREAD

**Issue by a-ilango** [ofiwg/libfabric#5305]
If we make CQ and EP progress functions types take a maximum # of completions that may be needed, as an argument, the provider may be able to optimize for bandwidth by reading more completions (if available) from a lower layer. The max_count can be same as the count arg passed to fi_cq_read.

In some cases, a ofi_cq_count function may be needed to check how many completions have been accumulated so far.

https://github.com/ofiwg/libfabric/blob/f67071b7d0950cc2ea14bc3564c455f2a3990a55/include/ofi_util.h#L456

https://github.com/ofiwg/libfabric/blob/f67071b7d0950cc2ea14bc3564c455f2a3990a55/include/ofi_util.h#L253

The addition of this feature can help deprecate `FI_OFI_RXM_COMP_PER_PROGRESS` env variable.

Thoughts?

@shefty

**Comment by shefty** [comment]
This could work, but I'm just trying to understand how much it helps.  I don't see a strong drawback, and it would allow a single env var control the progress for any provider that uses the common path. 

Anyway, some thoughts:

CQ progress calls EP progress for all EPs.  I don't know that passing a count from the CQ to the EP helps.  For example, we would still need to call progress on each EP, regardless of how many completions the first EP generates, and independent of the count passed in by the user.  So, it's not clear to me what value of count would be useful.

Maybe if the CQ tracked the last EP it made progress on, it could start on the next EP the next time progress is called?  Then passing count through could work while still ensuring fairness.

**Comment by a-ilango** [comment]
> This could work, but I'm just trying to understand how much it helps. I don't see a strong drawback, and it would allow a single env var control the progress for any provider that uses the common path.

Actually, I would not want an env variable as apps already have control over how many completions  they want per fi_cq_read call. By re-using that arg, existing RxM env variable can be eliminated. This makes sense unless upper layer middleware wants such a run-time option.

> we would still need to call progress on each EP, regardless of how many completions the first EP generates
...
> Maybe if the CQ tracked the last EP it made progress on, it could start on the next EP the next time progress is called? Then passing count through could work while still ensuring fairness.

No need to skip progressing an EP just because a previous EP generated enough completions. The objective of the max_count is just to provide a hint to an EP to fetch more completions (as a batch operation) if needed. I envision that a provider would get the completions fetched so far using `ofi_cq_count` and only try to fetch remaining completions that are available.

I do agree with starting on a different EP on next progress call if fairness is needed.

RxM needs `ofi_cq_count` function since an upcoming change would call MSG CQ progress as part of closing a MSG EP. The way the code is structured today, RxM would need to call this function to know how many completions it has seen so far to satisfy the `FI_OFI_RXM_COMP_PER_PROGRESS` env variable requirement. I was hoping to remove this env variable (if run-time option is not needed) and make the count arg to fi_cq_read more useful.

**Comment by shefty** [comment]
Assuming that cnt is updated after calling ep->progress(), and we stop calling ep->progress() once we have cnt completions, this changes the progress model.  So, we would need to track which ep would be the next one to call to avoid starvation.  Adding support for ofi_cq_count adds more overhead to every completion.

For closing the MSG EP, don't you just need to read everything off the CQ associated with that EP?

**Comment by shefty** [comment]
Year old request that does not have a strong requirement
