### ISSUE TITLE
prov/psm2: distributed deadlock when using scalable endpoint?

### ISSUE THREAD

**Issue by yilongli** [ofiwg/libfabric#5326]
Hi, I am trying to use the scalable endpoint feature in the psm2 provider but I run into a very annoying problem where a thread can take 5 seconds to send a small message. After searching the code base for keyword "5", I realize that it's the default value of `FI_PSM2_CONN_TIMEOUT`. Digging a little deeper in the source code, I figure out that the slow thread is blocked inside `psmx2_av_translate_addr` waiting for the `av_lock`:
https://github.com/ofiwg/libfabric/blob/master/prov/psm2/src/psmx2.h#L1041
At the same time, there is another thread holding the `av_lock` and doing `psmx2_av_query_sep`, which involves sending a message to a remote node and waiting for its reply. It seems very dangerous to invoke an RPC while holding a lock. How do you prevent distributed deadlock in this case? What if the remote process is also in such a state where one thread is blocked holding the `av_lock` while other threads can't send or receive any message? Could someone clarify if my understanding is correct? Thank you!

**Comment by shefty** [comment]
Asking @j-xiong to look into this.  He's the best person for this code.

**Comment by j-xiong** [comment]
Although it's not ideal to make a remote query while holding the lock, the "distributed deadlock" scenario won't happen. The reason is that the active message mechanism used for the query doesn't depend on the av lock. The active message handler at the remote side can always send the reply -- it just may be a slow response if the load is heavy.

**Comment by yilongli** [comment]
Hi @j-xiong, thanks for your response. I understand that the active mechanism doesn't need the av lock but which if the remote thread responsible for running the active message handler is also blocked waiting for the av lock? For example, suppose there are two processes P1 and P2 and each process has two threads T1 and T2. When P1:T1 is in the middle of sending an active message to P2:T1, P1:T2 might be blocked waiting for the av lock. Now what if the remote thread P2:T2 is also in the middle of sending an active message to P1:T2? P2:T1 might also be blocked waiting for P2:T2's av lock so it can not run the AM handler for P1:T1. Now none of the thread can make any progress. Is there some mechanism to avoid this scenario? Thanks!

**Comment by j-xiong** [comment]
That's a valid concern. However, unless explicitly disabled, the PSM2 library has an internal receive thread that will be able to call the AM handlers. If that thread is disabled (by setting PSM2_RCVTHREAD to 0) and OFI is set to use manual progress (i.e. the OFI level progress thread is not started), then the scenario you described can happen.

**Comment by yilongli** [comment]
I have to disable the PSM2 receive thread for performance reason. I am not using MPI and I already have my own dedicated communication threads, so I don't need an extra communication thread to help me overlap communication and computation. I am also using manual progress for performance reason.

Any chance to fix this problem? For example, instead of using a blocking call to acquire the lock, what about invoking `try_lock` in a while loop so that we can call the poll method when `try_lock` fails to make progress on the AM handlers?

**Comment by j-xiong** [comment]
The purpose of the PSM2 receive thread is not for overlapping communication with computation. It's for ensuring progress can be made when the application fails to make manual progress. The frequency that the receive thread is activated is pretty low. 

The lock is in a critical path, replacing it with a loop of trylock plus progress calls can negatively impact the performance, including those applications that don't use scalable endpoints. Ideally, we want to remove the lock from the critical path, but that will require some major change to the AV implementation. 

Let me continue to look into this.

**Comment by yilongli** [comment]
Thanks for clarifying the purpose of the receive thread. I will have to take a closer look why it has such a significant performance cost to enable the receive thread in my application.

Yes, removing the lock from the critical path would be very desirable. On the other hand, I would like to have a temporary workaround to unblock myself. Is there a single progress call I can use after trylock? Thanks.

**Comment by rzambre** [comment]
@yilongli one thing you could experiment with, if you haven't already, is setting the `HFI_NO_CPUAFFINITY=1` environment variable when you have the receive thread enabled. In my experiments, I have noticed not setting it to hurt performance.

**Comment by yilongli** [comment]
@rzambre Thanks for your suggestion. I will give it a try when I get a chance to investigate why the receive thread hurts my performance so much.

**Comment by mshiryaev** [comment]
@yilongli, the receive thread frequency can be controlled by PSM2_RCVTHREAD_FREQ
https://www.intel.com/content/dam/support/us/en/documents/network-and-i-o/fabric-products/Intel_PSM2_PG_H76473_v_11_0.pdf (section 1.11.29)

**Comment by yilongli** [comment]
@mshiryaev Thank you. I am aware of that. The problem is that I don't really understand what the receive thread is doing and I have no idea how to set the thread frequency. Should I set the frequency higher to ensure low-latency communication? Besides, I already have dedicated communication threads doing busy polling, so I don't need the receive thread to help me make progress.

I am also using a [core-aware scheduling system](https://github.com/PlatformLab/Arachne) with lightweight user-threads in my application, so I am very reluctant to introduce one more unmanaged kernel thread that doesn't seem to offer any performance benefit.

**Comment by mshiryaev** [comment]
@yilongli, it does receive side progressing, but this includes not only user messages but also service messages like acknowledgments. It does polling for each opened PSM2 endpoint in the loop. Just like example - if dedicated communication threads on app level are busy with other tasks, i.e. don't call poll and for example do reduction phase in mpi_allreduce, and receive thread is disabled then handling of acknowledgments can be delayed.

**Comment by yilongli** [comment]
> @yilongli, it does receive side progressing, but this includes not only user messages but also service messages like acknowledgments. It does polling for each opened PSM2 endpoint in the loop. Just like example - if dedicated communication threads on app level are busy with other tasks, i.e. don't call poll and for example do reduction phase in mpi_allreduce, and receive thread is disabled then handling of acknowledgments can be delayed.

@mshiryaev Thank you for the explanation. It's very helpful.

**Comment by j-xiong** [comment]
Don't expect an further action on this. Close now.
