### ISSUE TITLE
switch GNI provider to use common MR code

### ISSUE THREAD

**Issue by roblatham00** [ofiwg/libfabric#5328]
The GNI provider should use the common memory registration infrastructure.   Came up in discussion in this email thread: https://lists.openfabrics.org/pipermail/libfabric-users/2019-September/000558.html

**Comment by hppritcha** [comment]
talking with ANL crew, sounds like it may be better to just use the userfault fd part of the common MR cache.

**Comment by jswaro** [comment]
I've considered it a few times. There is not solid solution because userfaultfd isn't available until kernel 4.11, and kdreg is not a provider for the memory reg implementation in common core.

**Comment by hppritcha** [comment]
this isn't going to happen.  closing
