### ISSUE TITLE
Libfabric hangs at startup with verbs provider

### ISSUE THREAD

**Issue by mkre** [ofiwg/libfabric#5335]
Hi,

We are observing hangs at startup of our MPI application when Libfabric with the `verbs` provider is used across (at least) two nodes on a specific system: 

- CentOS 6.5
- MOFED 2.4
- Mellanox Technologies MT27500 Family [ConnectX-3] network adapter
- Dual-socket Intel Xeon E5-2697v3 (28 processes per node)

The hang occurs both with
- Open MPI 3.1.3 with Libfabric 1.8.0, and
- Intel MPI 2019.5 with its bundled Libfabric 1.7.2a-impi

The same software stack is working fine on other systems, so it might be an issue specific to this cluster. Also, the `sockets` provider is working fine on this system.

The hang does not occur when we only start a small number of processes per node (e.g., `ppn=1` or `ppn=2`). The hang always occurs when the nodes are fully populated (`ppn=28`).

Log files with Open MPI and `FI_LOG_LEVEL=Debug`:
- `verbs` (hangs): [ofi_debug_verbs.txt](https://github.com/ofiwg/libfabric/files/3697776/ofi_debug_verbs.txt)
- `sockets` (works): [ofi_debug_sockets.txt](https://github.com/ofiwg/libfabric/files/3697779/ofi_debug_sockets.txt)
- `verbs` with `ppn=2` (works): [ofi_debug_verbs_ppn2.txt](https://github.com/ofiwg/libfabric/files/3697846/ofi_debug_verbs_ppn2.txt)

There are no `<err>` messages in [ofi_debug_verbs.txt](https://github.com/ofiwg/libfabric/files/3697776/ofi_debug_verbs.txt), but some unsettling `<warn>` messages, like
```
libfabric:121679:ofi_rxm:ep_ctrl:rxm_eq_readerr():89<warn> fi_eq_readerr: err: Operation not permitted (1), prov_err: Success (0)
libfabric:82702:ofi_rxm:ep_ctrl:rxm_eq_readerr():89<warn> fi_eq_readerr: err: Connection timed out (110), prov_err: Success (0)
```

Other than that, I couldn't find any smoking guns and any help is greatly appreciated.

Thanks,
Moritz

**Comment by a-ilango** [comment]
You may want to try with more recent versions of the CentOS and/or MOFED. The logs show the connection requests are timing out but it's not obvious why. There could be some issue in the underlying RDMA stack.

**Comment by mkre** [comment]
Thanks, @a-ilango! Using a different MOFED version indeed does the trick. The issue seems to specific to MOFED 2.4. I have tried MOFED 1.5, 2.3 (direct predecessor of 2.4), 3.0 (direct successor of 2.4), and 4.6, and all of them are working. Strangely, Open MPI with UCX is also working with MOFED 2.4, so it seems to be an issue in the interplay of OFI/verbs and MOFED. 

Are you aware of such issues? I think for our code, we will have to disable Intel MPI in case MOFED 2.4 is installed, and rely on Open MPI over UCX in that case.

**Comment by a-ilango** [comment]
I see, so the problem is limited to MOFED 2.4. I'm not aware of such issue. We have tested OFI/verbs over only recent versions of MOFED.

**Comment by mkre** [comment]
Okay, thanks! Could you possibly say what "recent" means? Is there any minimum MOFED version with which OFI is guaranteed to work?

**Comment by a-ilango** [comment]
@mkre I've tested with MOFED 4.6.-1, 4.5-1 and 4.2-1 and they work fine.

**Comment by mkre** [comment]
Awesome, thanks for your help!
