### ISSUE TITLE
include/osx etc. missing from fabtests release tarball

### ISSUE THREAD

**Issue by bsteinb** [ofiwg/libfabric#5339]
I tried to install fabtests from the 1.8.1 release tarball on macOS, but could not. The `make` step complains about not finding `<osx/osd.h>` and indeed that file is not included in the release tarball. `include/freebsd` and `include/windows` are missing as well. Building and installing from the `v1.8.1` git tag works and allows me to run `runfabtests.sh` against the `sockets` provider with 71 passed tests, 1 excluded.

**Comment by shefty** [comment]
Thanks - will fix.

**Comment by shefty** [comment]
So, the published release tarballs are for Linux only.  We don't actually publish release tar files for OS X or freebsd.  I don't have a way to generate those.  Windows uses a different build system.

**Comment by bsteinb** [comment]
Fair enough, although it comes as a bit of a surprise, since the libfabric tarballs do build on macOS and fabtests itself builds from a git checkout. Maybe this should be added to fabtests' README or the tarballs be renamed fabtests-X.Y.Z.linux.tar.bz2?
