### ISSUE TITLE
MR cache merge regions bug

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#5347]
@shefty I was investigating a bug I experienced with userfault notifications when merge regions was enabled. I ended up tracking it down to these lines inside util_mr_free_entry.

```
if (entry->subscribed && cache_params.merge_regions) {
                ofi_monitor_unsubscribe(cache->monitor, entry->info.iov.iov_base,
                                        entry->info.iov.iov_len);
                entry->subscribed = 0;
}
```

Removing these lines causes the issue to disappear - which means that we are unsubscribing from regions that we still need to be receiving fault notifications from.

I have only experienced this issue with merge regions. Removing the line from ofi_mr_cache_notify:

```
if (!cache_params.merge_regions)
```

caused the issue to reappear, which is a little concerning. I'll keep investigating to see if there is an appropriate fix, but currently merge regions is bugged.

**Comment by shefty** [comment]
Is this with master?  Nothing there stands out to me, which I agree is concerning and suggests that my logic is overlooking some problem.

**Comment by wckzhang** [comment]
Yes, this is with master.

**Comment by wckzhang** [comment]
We're going to upstream an ep unit test that has been catching the issue (with bounce buffers being registered during ep_bind). This unit test reproduces the issue with EFA and we will push a PR for it. We will try to get it upstreamed this week.

**Comment by shefty** [comment]
Thanks - that will help.  Btw, there is one test that tries to catch MR caching issues (see fabtest unmap_mem).  Expanding it may help catch this as well.

**Comment by rajachan** [comment]
The unit test that William referred to is now up as PR https://github.com/ofiwg/libfabric/pull/5350

**Comment by wckzhang** [comment]
To give a more in-depth explanation of the bug that was being hit with merge regions enabled.

ep_open_max_simultaneous - Passes
- Opens at least as many endpoints as maximum advertised endpoints.
- Each endpoint is enabled which causes bounce buffers to allocate huge pages, which are registered by the application.
- Each buffer is munmap'd, only some of them get notifications, some of them notifications fail to unsubscribe from the region (Tries all 3 page sizes but returns 22). The registrations that are not unsubscribed against are inserted into the lru.
- No merging occurs

ep_rand_access - Fails
- Endpoints are opened randomly
- Some buffers overlap with the previously registered buffers, detects a match, but doesn't merge, returns.
- A buffer overlaps with a previously registered buffer, detects a match, starts a merge.
- Merging occurs, uncaches entries from tree, attempts to create a new region.
- New region fails due to -12 (Cannot allocate Memory) from an madvise call.

I determined that the new region failed during madvise because the old registration had been unmapped, causing a portion of the madvise call to encompass unmapped buffers. Since all the buffers should have been unmapped, I suspected an issue with the uffd. Removing the call to unsubscribe from any region fixed the issue, so it leads me to believe we are unmonitoring the region before we should.

A few questions I need to dig into are - Why is the uffd_unregister call failing? Why are unmapped regions not all triggering the monitor? Why do we need notifications from regions we already got notifications from?

**Comment by shefty** [comment]
Is there a chance this is specifically related to huge pages?  We're guessing what page size was used for an allocation (ofi_uffd_register).  If we guess wrong, I'm not sure what happens.  Or if a huge page can be broken by the kernel into multiple smaller pages...

**Comment by wckzhang** [comment]
I believe I disabled huge pages at one point and it still had the same problem. I will test it again.

**Comment by wckzhang** [comment]
On further investigation, huge pages disabled makes the test pass. I don't know if there's some sort of race condition involved though.

I also started printing the uffd register and unregister output (This is without huge pages). Sometimes it works, sometimes it doesn't..very strange:
```
Successfully registered, Addr: 0x7f3fe9f7e000, Len: 74461184
Unmap Event Notified
Address 0x7f3fe9f7e040, 74457984, erased from tree
Successfully unregistered, Addr: 0x7f3fe9f7e000, Len: 74461184
.
.
.
Successfully registered, Addr: 0x7f3fe38fd000, Len: 74461184
Unmap Event Notified
Address 0x7f3fe38fd040, 74457984, erased from tree
Failed to unregister: Addr: 0x7f3fe38fd000, Len: 74461184
Failed to unregister: Addr: 0x7f3fe3800000, Len: 75497472
Failed to unregister: Addr: 0x7f3fc0000000, Len: 1073741824
```

**Comment by shefty** [comment]
I wonder if it really matters if the unregister call fails.  We've tried.  It would be nice to know why, but maybe this is an error we can skip?

**Comment by wckzhang** [comment]
We currently do just skip it...I would like to know why it fails when it really shouldn't.

**Comment by shefty** [comment]
Is there any useful error code with the failure?  I'm hoping the failure will help point back to whatever the other problem(s) might be.

**Comment by wckzhang** [comment]
Unfortunately not, it's just 22 (which it does if it's not page aligned as well).

```
Successfully registered, Addr: 0x7f661aff9000, Len: 74461184
Unmap Event Notified
Address 0x7f661aff9040, 74457984, erased from tree
Successfully unregistered, Addr: 0x7f661aff9000, Len: 74461184
.
.
.
Address = 0x7f66138fd040, Len = 74457984, Cache Search
Creating
Successfully registered, Addr: 0x7f66138fd000, Len: 74461184
Unmap Event Notified
Address 0x7f66138fd040, 74457984, erased from tree
Failed to unregister: Addr: 0x7f66138fd000, Len: 74461184, Errno: 22 - Invalid argument
Failed to unregister: Addr: 0x7f6613800000, Len: 75497472, Errno: 22 - Invalid argument
Failed to unregister: Addr: 0x7f6600000000, Len: 1073741824, Errno: 22 - Invalid argument
```

I did find something interesting though...This failure also only happens with merge regions. If I turn merge regions off, it successfully passes the entire ep_open_close test without hitting this unregister bug. So this is also something that only appears with merge regions...odd.

**Comment by shefty** [comment]
Can you see if using the memhooks instead of userfaultfd produces a similar problem?

**Comment by shefty** [comment]
I don't think we're specifying huge page support correctly.  In util_mem_monitor.c : line 355, I think we want to or in UFFD_FEATURE_MISSING_HUGETLBFS to the api.features, if we detect that huge pages are available.

**Comment by shefty** [comment]
From the kernel.org doc (https://www.kernel.org/doc/Documentation/admin-guide/mm/userfaultfd.rst):
```
However, in the latter case, when an area is unmapped, either explicitly (with munmap() system call), or implicitly (e.g. during mremap()), the area is removed and in turn the userfaultfd context for such area disappears too and the manager will not get further userland page faults from the removed area
```
So, if we receive an UNMAP event, we shouldn't need to unregister the memory from userfaultfd.

**Comment by wckzhang** [comment]
Using memhooks caused a hang in the ep_open_close test - I'll have to debug that.
```
If the kernel supports registering userfaultfd ranges on hugetlbfs
virtual memory areas, UFFD_FEATURE_MISSING_HUGETLBFS will be set in
uffdio_api.features.
```
I understood this as the ioctl call returning setting this flag. So I don't think we are supposed to set the UFFD_FEATURE_MISSING_HUGETLBFS flag ourself - I will test this.

I think you're correct on the UNMAP event. We can notify the cache without unsubscribing. Our current method of unsubscribing for UNMAP notifications is probably causing some unexpected behavior, which is why removing the unsubscribe call from the notify function works.

**Comment by wckzhang** [comment]
I verified that the ioctl call is in fact setting the uffdio_api.features flag with UFFD_FEATURE_MISSING_HUGETLBFS. So this isn't something we need to be OR'ing. We can however put a check in util_mem_monitor.c : line 370 for
```
if (api.features & UFFD_FEATURE_MISSING_HUGETLBFS) {
    //Handle relevant huge page features
}
```
if we need to do anything specific in regards to huge pages.

**Comment by shefty** [comment]
The documentation needs help.  I was looking at:
```
To enable userfaultfd features the application should set a bit 
corresponding to each feature it wants to enable in the features field.
```
I had the same initial understanding as you, that the kernel would set this bit if it's usable.  Note that we don't check this, but then I wouldn't expect to find hugepage sizes available if it were 0.

I started down the path of removing the unsubscribing with UNMAP, but it's not that simple.  We want to unregister the entire cached region, not just the unmapped portion.  And REMOVE requires us to act on it.  But this could explain the unregister errors that you're seeing.

**Comment by wckzhang** [comment]
> We want to unregister the entire cached region, not just the unmapped portion.

When you say unregister do you mean memory registration or userfault fd registration?

It is a bit of a pain that REMOVE and UNMAP require separate behavior...

**Comment by shefty** [comment]
I meant uffd unregister.  Based on the man pages, it seems that an UNMAP event results in an implicit deregistration.  So, the uffd unregister failures may be a result of that.  If you could verify this, it could be helpful.  But I'm assuming this for now.

I'm still thinking about how to handle this.  We can add uffd unregister into util_mem_monitor for the REMOVE case.  The cache would then assume that the reported range was unregistered.  It would still need to unregister the regions before and after the reported range, if needed.

**Comment by wckzhang** [comment]
> We want to unregister the entire cached region, not just the unmapped portion.

Then I don't think we care about the rest of the rest of the cached region. As long as we remove it from the cache and deregister the mr, the worst that can happen is we receive an UNMAP event for a region not in the cache. In that case, userfault fd will unregister it itself and we can just do a no-op when we don't detect anything in the cache (I hope what I just said was coherent and understandable).

Thus in the UNMAP case, I don't believe we have to ever unregister from the uffd.

In the REMOVE case, I think we can just add the unregister in the uffd_handler function.

As long as we remove any region from the cache that contains the notified region, I think it's okay to never have an unregister happen inside ofi_mr_cache_notify.

**Comment by shefty** [comment]
I have a patch that adds unregister in the uffd handler for REMOVE.  I removed unregister from the mr cache notify handler.

I have a follow on patch that moves the unregister in the mr cache 'free' path to the 'uncache' path.

I agree that we could drop it and never unregister at the cost of just getting additional events.  I am concerned about this error in the ioctl_userfaultfd man page:
```
EBUSY  A mapping in the specified range is registered with another
              userfaultfd object.
```
I think this error only shows up if we have 2 actual fd objects open and doesn't imply that we can't register the same range twice.

**Comment by wckzhang** [comment]
I'm pretty sure I tested and you can register the same region twice with a fd harmlessly. I believe you're correct on the 2 fd objects.

**Comment by wckzhang** [comment]
It might be worth thinking a bit on how generic the ofi_mr_cache_notify function should be...We don't want ofi_monitor_unsubscribe to be called inside it for uffd, but we might want it to be called for other memory monitors.

**Comment by shefty** [comment]
I'm trying to understand the failure more.
```
ep_rand_access - Fails

1 Endpoints are opened randomly
2 Some buffers overlap with the previously registered buffers, detects a match, but doesn't merge, returns.
3 A buffer overlaps with a previously registered buffer, detects a match, starts a merge.
4 Merging occurs, uncaches entries from tree, attempts to create a new region.
5 New region fails due to -12 (Cannot allocate Memory) from an madvise call.
```
Why are some buffers matching in 2, but not merging?  Are these matches fully within a registered region?
What is calling madvise?  Is that coming from the EFA provider?

**Comment by shefty** [comment]
I think I see where the madvise is coming from -- efa_ib_cmd_reg_mr

**Comment by shefty** [comment]
My latest wondering is if we somehow end up trying to merge regions backed by different page sizes.  From the discussion so far, if huge pages are available at all (likely?  always the case?), we should disable merging as an option.

**Comment by rajachan** [comment]
> I think I see where the madvise is coming from -- efa_ib_cmd_reg_mr

76a9f40ffe92d has more context for the madvise() in there.

**Comment by wckzhang** [comment]
I think I figured out what's happening. The huge pages are set to 2097152 for me, not 1073741824.

However, since the region has been unsubscribed to already during the fault itself, when we try to call ofi_uffd_unsubscribe -> it fails on page_sizes[0] and page_sizes[1] (4096 and 2097152), but it succeeds on page_sizes[2] (1073741824).

Since that isn't my huge page size, it should never succeed at that size - otherwise we're unsubscribing from a huge region that we weren't meant to be unsubscribing from - which is what I think is happening.

During the ep_open_max_simultaneously, due to failing at page_sizes[0] and page_sizes[1] (already unsubscribed automatically, so it makes sense), we unsubscribe from regions we shouldn't be unsubscribing for - causing us to miss faults for regions that we still have cached.

Supporting evidence for this is that without removing the unsubscribe call, the number of userfault notifications at the end of ep_open_max_simultaneously is 87, while after removing the unsubscribe call, the number of userfault notifications is 353. We are losing at least 266 notifications here, causing us to retain them in the cache and match against unmapped regions.

**Comment by shefty** [comment]
That description makes sense to me, and I agree with the proposed options for a solution.

**Comment by wckzhang** [comment]
PR 5376 merged
