### ISSUE TITLE
prov/shm: FI_MR_VIRT_ADDR bit is dropped off if setting hints as FI_MR_BASIC

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5352]
shm provider has the default mr_mode as FI_MR_BASIC | FI_MR_SCALABLE. As per the spec, this mode is equivalent to the FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, and FI_MR_PROV_KEY flags being set in later library versions. But once I set the hints to FI_MR_BASIC, FI_MR_VIRT_ADDR bit is dropped off. Therefore, the fast_rma_path can not be triggered.

> FI_MR_BASIC

Defined for compatibility – library versions 1.4 and earlier. Only basic memory registration operations are requested or supported. This mode is equivalent to the FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, and FI_MR_PROV_KEY flags being set in later library versions. This flag may not be used in conjunction with other mr_mode bits.

>

**Comment by shefty** [comment]
If FI_MR_BASIC is set as an input hint, it must be returned from fi_getinfo.

**Comment by zhngaj** [comment]
Ah. I see. It's only mr_mode: [ FI_MR_VIRT_ADDR ] for shm. 
False positive, so close this issue.
