### ISSUE TITLE
No interface to control passive endpoint listener backlog

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#537]
According to the fi_cm.3 manpage:

> The number of outstanding connection requests that can be queued at an endpoint is limited by the listening endpoint's backlog parameter.  The backlog is initialized based on administrative configuration values, but may be adjusted through the `fi_control` call.

There is no such parameter to the `fi_control` call that I can see.  The verbs provider seems to only use the default value obtained by calling `rdma_listen(cm_id, 0)`.

I can submit a pull request to add this feature and add the functionality to at least the verbs provider if this seems desirable.

**Comment by shefty** [comment]
If you can add this feature, that would be great.
