### ISSUE TITLE
Move rx/tx size left calls to basic ep ops

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#539]
See PR #525.  The rx_size_left and tx_size_left calls were added to the fi_ops_msg.  They would be better placed as base ops of the endpoint, rather than associated with message transfers.  For example, the calls also apply to rma, atomic, and tagged operations as well.  @goodell @jsquyres

**Comment by shefty** [comment]
A couple of other notes.  The name of the call and prototype look fine to me.  In the man pages, I would use the term 'transmit' in place of 'send' when describing the tx_size_left.  I just want to avoid any confusion that tx_size_left only applies to functions with 'send' in the name, versus any outgoing request.

**Comment by goodell** [comment]
I'll take care of this on Monday. Thanks for the feedback.
