### ISSUE TITLE
prov/gni:  scalable endpoint, failed to send to different receive context

### ISSUE THREAD

**Issue by zjf2012** [ofiwg/libfabric#5390]
As tested, the send context in client side and the recv context in server cannot be changed to other contexts once client sent a message to server. 

My case is server recv context, srx[0], receiving any client request and getting proper recv context, srx[i], back to client crx[0]. Then client changes its target recv context from srx[0] to srx[i]. Later communication is between client ctx[0] crx[0] and server srx[i] stx[i]. The purpose is to make all server recv contexts except stx[0] srx[0] load-balanced. It worked well on PSM2. May be GNI is different than PSM2.

As a workaround, I remove the server address via fi_av_remove method first. Then insert the address back to av again. Here is the code.
`
fi_av_remove(av, &dest_provider_addr, 1, 0);
assert(fi_av_insert(av, info->dest_addr, 1, &dest_provider_addr, 0, NULL) == 1);
send_ctx_addr = fi_rx_addr(dest_provider_addr, send_ctx_id, RECV_CTX_BITS);
`
With above workaround, my case worked.

**Comment by hppritcha** [comment]
not fixing.  closing
