### ISSUE TITLE
Man page for fi_cq_readerr()  needs some clarifition (or maybe a bug in the Verbs provider)

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#5433]
Hi Libfabric's community!

I was recently chasing a bug in an application we are developing at DDN Storage, which was causing a memory corruption with the verbs provider.

The code is doing something similar to this:
```
struct fi_cq_err_entry err_event;
size_t err_rc = fi_cq_readerr(nd_cq, &err_event, 0);
```

As you notice, `err_event` is not memset to 0 before calling `fi_cq_readerr()`
It looks like the verbs provider tries to write some data pointed by `struct fi_cq_err_entry::err_data` if `struct fi_cq_err_entry::err_data` != NULL and `struct fi_cq_err_entry::err_data_size` is > 0.
The code is located here: https://github.com/ofiwg/libfabric/blob/master/prov/verbs/src/verbs_cq.c#L116

In my case, `err_event` is not memset to 0 and likely contains garbage data for `err_data` and `err_data_size`, which was causing a bad memory corruption in Libfabric.

Initially I thought that the argument `struct fi_cq_err_entry` was only used as output parameter, which explains why I omitted memset-ing this parameter to 0. I checked the manual and it doesn't clearly state anything about it. The following paragraph in the man page is even more confusing:

According to https://github.com/ofiwg/libfabric/blob/master/man/fi_cq.3.md
> For compatibility purposes, if err_data_size is 0 on input, or the fabric was opened with release < 1.5, err_data will be set to a data buffer owned by the provider. The contents of the buffer will remain valid until a subsequent read call against the CQ. Applications must serialize access to the CQ when processing errors to ensure that the buffer referenced by err_data does not change.

It states that `err_data` is set to a data buffer owned by the provider, which is not right, at least for the Verbs provider. Is it a bug to this specific provider? Or the man pages contain wrong information? Thanks for your help!

**Comment by shefty** [comment]
The man page description is referencing the behavior of libfabric version 1.4 and prior.  Beginning at 1.5, the behavior changed in order to handle multi-threaded apps better.  Hence, err_data went from being an output only buffer to an input/output buffer.  The description for err_data is definitely not clear that it should be a user provided buffer.  I will update the man page.

**Comment by sydidelot** [comment]
Thanks, @shefty !

**Comment by shefty** [comment]
See if PR #5435 helps clarify the intended behavior, or if additional wording tweaks are needed.

**Comment by sydidelot** [comment]
The paragraph is clearer now. Thanks for the patch!
