### ISSUE TITLE
Q&A: Resource Management Enabled/Disabled

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5440]
I have been reviewing the resource management section in the fi_domain manpage, and it is not clear what type of error is classified as a resource management error which would cause an EP to be disabled.

For example, suppose a RDM/MSG EP issues an RMA operation to a target MR that does not exist. Does the resulting transmit error (CQ error) cause the EP to be disabled?

Another example, suppose a RDM/MSG EP with RM enabled issues a send operation to a target EP without a receive buffer posted. After retrying the operation N times, does the resulting CQ error cause the EP to be disabled?

It seems that resource management is suppose to protect local EP resources against overrun, but it is not clear if a transmit error is classified as a resource management error.

**Comment by shefty** [comment]
> I have been reviewing the resource management section in the fi_domain manpage, and it
> is not clear what type of error is classified as a resource management error which
> would cause an EP to be disabled.

Resource management is related to internal queues and transport level flow control.  It protects against overrunning hardware send and receive queues, as well as completion queues.

> For example, suppose a RDM/MSG EP issues an RMA operation to a target MR that does not
> exist. Does the resulting transmit error (CQ error) cause the EP to be disabled?

This will generate an error, as it's related to security.

> Another example, suppose a RDM/MSG EP with RM enabled issues a send operation to a
> target EP without a receive buffer posted. After retrying the operation N times, does
> the resulting CQ error cause the EP to be disabled?

The underlying msg ep is likely to become disabled, however the rxm ep should remain functional.

The number of retries before the transfer fails is a function of the underlying provider.  In some cases, the request may be retried indefinitely.  The intent in this case is that the app should be protected for a reasonable period of time, such that the app should not need to handle their own flow control.
 
> It seems that resource management is suppose to protect local EP resources against
> overrun, but it is not clear if a transmit error is classified as a resource management
> error.

If a transfer actually fails, it will be reported to the app as a failure.

- Sean

**Comment by iziemba** [comment]
>The underlying msg ep is likely to become disabled, however the rxm ep should remain functional.

Is an endpoint going disabled dependent on the endpoint type or the providers implementation of the endpoint?

**Comment by shefty** [comment]
This will be implementation dependent.  I believe today the msg ep will be disabled permanently.  However, my preference is that the rxm code reset the connection, so that future communication would be possible.

**Comment by iziemba** [comment]
Thanks! This has been helpful.
