### ISSUE TITLE
order in which to call fi_close

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#545]
Is there an order in which an application can call fi_close? I'm thinking of an order like the following (just an example).

* close endpoints
* close shared contexts
* close queues, counters
* close domain
* close fabric

It would be nice if an order was documented. This allows providers to return FI_EBUSY if the application is closing objects in the wrong order, and potentially avoid bugs.

What do you think? If people like this idea, then we should probably have a manpage for fi_close to document this.

**Comment by shefty** [comment]
That looks like the correct order.  I would update the individual man pages to clarify the ordering.  For example, in the CQ man page:  "When closing the CQ, there must be no opened endpoints, transmit contexts, or receive contexts associated with the CQ.  If resources are still associated with the CQ when attempting to close, the call will return -FI_EBUSY."

**Comment by sayantansur** [comment]
OK. I'll generate a PR.
