### ISSUE TITLE
endpoint enumeration/ ipv6 endpoints unusable

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#5453]
I have been trying to set up a server/multi-client use case as follows:
The server process does `fi_getinfo()` with the appropriate hints to identify all suitable endpoint candidates (basically `caps=(FI_MSG|FI_RMA|FI_TAGGED)`, `mode=FI_CONTEXT`, `ep_type=FI_EP_RDM`). Then it creates an endpoint for all of the entries and enables each of them. (I'll typically see some socket/IPv4, socket/IPv6 and some GNI endpoints on my test system.)
As it turns out, the IPv4 and GNI endpoints have an address that is reasonable: IPv4 has the right local address and some (high) port number, GNI is a nice Aries address. There are however some IPv6 endpoints (based on link-local addresses) which have a port number of `0` even after enabling the endpoint.
Why does the socket provider not assign a port number at this stage for IPv6 endpoints?

In a second step I'm serializing the endpoint addresses and pass them OOB to client processes. The goal is that a client can pick the most suitable provider/interface to connect to the server process.

As it turns out, a client process may successfully insert the server's IPv6 address (even with `sin6_port==0`) into its address vector of an ipv6 endpoint, but `fi_send()` will subsequently fail (with errno -2).

Is this an error on my side? How do I check that an endpoint obtained from an entry in the `fi_getinfo()` result where I did bind completion and event queue, address vector etc. and enabled it is actually reachable, in particular for the socket/IPv6 provider?

What I really want to obtain is a server process with enabled RDM endpoints on all suitable network interfaces, and a list of these that a client can pick the most suitable from to talk to (where you have to imagine a multi-homed server and clients with heterogeneous network capabilities, e.g., some on simple IP, some on HPC interconnects).

**Comment by shefty** [comment]
What provider are you using that's giving the incorrect ipv6 address?  If this is the socket provider, that sounds like a bug in the provider.  We're trying to replace the socket provider with the tcp provider.  Can you try using that provider and see if you have the same issue?

**Comment by u-u-h** [comment]
This is with sockets (in 1.8.0), yes. 

Conceptually I'm trying to enumerate and open endpoints for anything that `fi_getinfo()` finds on a given node that matches my hints. For some reason the tcp provider (while fi_info shows it's available) does not yield any candidates. I'll investigate whether they're there in my initial `fi_getinfo` output too, and why they get dropped as unsuitable.

**Comment by u-u-h** [comment]
Ok, the tcp provider does not yield any suitable `fi_info` entries on my laptop (a macos one). I'm using
`hints->caps=(FI_MSG|FI_RMA|FI_TAGGED)`
`hints->mode=(FI_CONTEXT)`
`hints->ep_attr->type=FI_EP_RDM`
and version requirement `FI_VERSION(1,5)`.
That yields 7 fis:
```[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1436) 7 fis found
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets fe80::/64
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ep_desc_serialize__in6(ofi.c:410) sockaddr_in6 with port 0
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 0. usable endpoint: OFI EP prov sockets name fe80::/64 straddr fe80::aede:48ff:fe00:1122:0
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets fe80::/64
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ep_desc_serialize__in6(ofi.c:410) sockaddr_in6 with port 0
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 1. usable endpoint: OFI EP prov sockets name fe80::/64 straddr fe80::c46:160c:2dca:cbef:0
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets 192.168.178.0/24
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 2. usable endpoint: OFI EP prov sockets name 192.168.178.0/24 straddr 192.168.178.42:50845
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets fe80::/64
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ep_desc_serialize__in6(ofi.c:410) sockaddr_in6 with port 0
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 3. usable endpoint: OFI EP prov sockets name fe80::/64 straddr fe80::78a1:d3ff:fed3:dbe2:0
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets fe80::/64
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ep_desc_serialize__in6(ofi.c:410) sockaddr_in6 with port 0
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 4. usable endpoint: OFI EP prov sockets name fe80::/64 straddr fe80::75f1:1b49:a5b5:a339:0
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets 127.0.0.0/8
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 5. usable endpoint: OFI EP prov sockets name 127.0.0.0/8 straddr 127.0.0.1:50846
[D] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1443) potential endpoint: sockets ::1/128
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ep_desc_serialize__in6(ofi.c:410) sockaddr_in6 with port 40902
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1452) 6. usable endpoint: OFI EP prov sockets name ::1/128 straddr ::1:50847
[I] t83742 (C02ZD3QXLVDR 23290): mstro_ofi_init(ofi.c:1462) 7 usable endpoints
```
The output from command line tool `fi_info(1)` without caps or mode requirements shows tcp entries, but none of them show a network address. If I add `FI_TAGGED` they disappear -- does the tcp provider not support that yet?

**Comment by shefty** [comment]
tcp works with the rxm utility provider to support RDM endpoints, including tagged support. The tcp provider by itself only supports MSG endpoints.  If you run fi_info, you should see a provider that looks like "ofi_rxm;tcp".

**Comment by u-u-h** [comment]
I had disabled the rxm provider in my libfabric build because on tcp;ofi_rxm endpoints I get
```fi_enable failed: -78 (Function not implemented)```
(leading up to this I do `fi_ep_bind()` with av, eq, cq, mostly with default settings)

Would a more recent version than 1.8.0 work here?

**Comment by shefty** [comment]
You can try using 1.9.0rc3 (or 1.8.1, though I doubt the behavior would change).  But I would be interested to know why you see the fi_enable failure on 1.8.  That is, where in the code is this failure being returned.  I expect rxm+tcp to work in 1.8, so if it doesn't, I'd like to understand why not and fix it.

**Comment by u-u-h** [comment]
Ok, then let's debug this.
On the current build I see
```step
Process 7607 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = step in
    frame #0: 0x0000000100017b41 check_pool_manager`mstro_ep_build_from_ofi [inlined] fi_enable(ep=0x00000001006075b0) at fi_endpoint.h:189:17 [opt]
   186 	
   187 	static inline int fi_enable(struct fid_ep *ep)
   188 	{
-> 189 		return ep->fid.ops->control(&ep->fid, FI_ENABLE, NULL);
   190 	}
```
That is very ... expected and not clarifying anything. I'll try to get a non-optimized build, but if you can tell me which function to break on & single-step that might be quicker. (I don't have a minimal reproducer, and the whole project build with dependencies takes a while)

**Comment by shefty** [comment]
Try breaking on rxm_ep_ctrl() in prov/rxm/src/rxm_ep.c.  You can also turn on debug logging in case that reveals the problem.  FI_LOG_LEVEL=debug.

The return code of function not implemented also suggests putting a break on fi_no_control() in src/enosys.c.  Though if we hit that break, it may not tell us much.

**Comment by u-u-h** [comment]
Going from `rxm_ep_ctrl()` -> `rxm_ep_enable_check()` I see
```  
2228		if (rxm_ep->util_ep.rx_cq)
-> 2229			return 0;
``` 
Then it goes into `rxm_ep_msg_cq_open(rxm_ep);`, which decides that `FI_WAIT_FD` is needed. `fi_cq_open()` succeeds.

Then I see `rxm_ep_wait_fd_add()` failing on the first of 2 cq_list entries with `-78`.
This comes from a chain of `fi_control()` calls ending in `util_wait_fd_control()`, where the code takes the `#else` path of the `#ifdef HAVE_EPOLL`:
```
util_wait.c:299:7         ret = -FI_ENOSYS;
```

I guess it really means that the functionality is not implemented for non-linux systems. 
I see that there is an implementation of the `fi_epoll_*` functions in src/common.c even for the case based on poll -- so there must be some subtlety to conditionalize on `HAVE_EPOLL` in util_wait_fd_control()`.

(BSD has `kqueue(2)` which should provide similar behavior to epoll, but I've never used it myself;
not sure how much effort it would it be to add as an alternative.)

**Comment by u-u-h** [comment]
The code in master of util_common.c is still the same, btw (https://github.com/ofiwg/libfabric/blob/b00579610ca0a380746884625c0c88d72eab3d73/prov/util/src/util_wait.c#L298)

**Comment by shefty** [comment]
OS X support is primarily there for development purposes.  The use of an fd wait object is one of those areas where we can't hide this from the API.  Although we have an internal implementation for epoll for systems that don't support it, we can't 'leak' that out through the API.  That's what's causing the issue here.

**Comment by shefty** [comment]
Does your application use blocking CQ calls?

**Comment by u-u-h** [comment]
same here (regarding OS X) :)

I'm not sure I understand the second sentence above regarding the fd wait object.
But: wouldn't generic BSD support be of use?

No fi_cq_s* calls at this point, no.

**Comment by u-u-h** [comment]
I'm using `FI_WAIT_UNSPEC` for eq and cq, hoping that it would select the most appropriate one for each provider. (Blindly using one of `FI_WAIT_FD`, `FI_WAIT_NONE` or `FI_WAIT_MUTEX_COND` based on the host system does not make sense, as some providers don't like some of these, right?)

**Comment by shefty** [comment]
rxm uses epoll, mixing its wait objects with that of the core provider (tcp in this case), in order to properly handle applications that want to block.  kqueue would likely work in this case, but... that's not implemented (because it's only needed for OS X, which is a low priority).

If you don't need to block on the CQ, specify FI_WAIT_NONE when creating the CQ.  That should remove the need for rxm to create an FD for a wait object.

I'll see if I can think of a way to handle this better, even if it means leaking the epoll implementation outside the API, as long as the user is actually a utility provider.

**Comment by shefty** [comment]
Yes, WAIT_UNSPEC is ideal if you're using blocking calls.  But if you don't use them, WAIT_NONE removes the extra overhead of allocating the wait objects (which will be an fd given the current implementation).

**Comment by u-u-h** [comment]
Thanks!

I seem to remember having issues with `FI_WAIT_NONE` (on GNI?) despite not using blocking calls, but maybe I'm wrong. I'll try.

**Comment by u-u-h** [comment]
Ah, here's the reason I disabled rxm in the first place:
With the rxm provider I occasionally get a segfault along the following path:
The 6th fi_info (after a couple of IN6 and IN4 tcp;ofi_rxm endpoints) looks like this:
```
(lldb) print *fi
(fi_info) $1 = {
  next = 0x0000000100309310
  caps = 6755399441137422
  mode = 0
  addr_format = 2
  src_addrlen = 16
  dest_addrlen = 0
  src_addr = 0x00000001003092d0
  dest_addr = 0x0000000000000000
  handle = 0x0000000000000000
  tx_attr = 0x0000000100309100
  rx_attr = 0x0000000100309150
  ep_attr = 0x0000000100309190
  domain_attr = 0x00000001003091f0
  fabric_attr = 0x00000001003092b0
  nic = 0x0000000000000000
}
```
when I do
```
stat = fi_endpoint(domain, fi, &ep, NULL);
```
That goes into `rxm_endpoint()`, into `rxm_ep_msg_res_open()`, `rxm_listener_open()`, which fails (need to check where exactly), then jumps to the `err:` label, triggering an `rxm_listener_close()`. In that `fi_close(&rxm_ep->msg_pep->fid)` fails with as SEGV.

**Comment by u-u-h** [comment]
> Yes, WAIT_UNSPEC is ideal if you're using blocking calls. But if you don't use them, WAIT_NONE removes the extra overhead of allocating the wait objects (which will be an fd given the current implementation).

So I can rely on every provider to support running with `FI_WAIT_NONE`?

**Comment by shefty** [comment]
You _should_ be able to rely on the providers supporting WAIT_NONE.  There's nothing that prevents them from allocating a wait object anyway.  It looks like the gni code handles this.

Thanks for the segv report.  That definitely shouldn't happen.  I'll look into that.  Then we'll need to understand why rxm_listener_open fails.

**Comment by u-u-h** [comment]
The `err:` label is jumped to from `rxm_listener_open()` at 
```
  2337		ret = fi_passive_ep(rxm_fabric->msg_fabric, rxm_ep->msg_info,
  2338				    &rxm_ep->msg_pep, rxm_ep);
```
which returns `ret==-1`.

That is due to `tcpx_passive_ep()` receiving -1 as return value from `ret = tcpx_pep_sock_create(_pep);`

That is due to 
```
ret = bind(pep->sock, pep->info->src_addr,
   263 			      (socklen_t) pep->info->src_addrlen);
```
returning -1.

Hope that helps. (Likely the deep trace is not needed to see why the `err:` cleanup should be more careful.)

**Comment by shefty** [comment]
The following patch (to be included in 1.9) should fix the segfault.

https://github.com/ofiwg/libfabric/pull/5456/commits/db96285360eeb716fc511a6188a6fba5d8c409e3

I reproduced the fault by forcing an error just above the code and confirmed that this avoids the fault.  This doesn't fix the failing coming from the socket bind() call.  It's possible that failure is coming from conflicting bind calls against the same port.  For example, binding port X with IPv6 loopback and port X with IPv4 loopback.  More work will be needed to isolate that problem.

**Comment by u-u-h** [comment]
Thanks, that fixes the segv. Let me know if I can help figuring out why the `bind()` fails.

The ipv6 straddr looks better with tcp;ofi_rxm: `fe80::aede:48ff:fe00:1122%en6:55705`, however connection setup fails.
The client does av_insert with the above address on its local endpoint `fi_sockaddr_in6://[fe80::aede:48ff:fe00:1122]:55714`, which succeeds, but then the first send operation fails: `fi_send failed: -65 (No route to host)`

I had expected `FI_EAGAIN`, but no route is weird.

**Comment by u-u-h** [comment]
@shefty Any insight into this? After the segfault is fixed by db96285 I can enumerate a dozen endpoints with disjoint port numbers on the server and client side (running on the same physical node), and while inserting the AV succeeds, the first `fi_send()` fails with a non-EAGAIN error (see above).
Should I open a separate issue for this maybe?

**Comment by shefty** [comment]
I have not had time to look into this bug.  I asked another developer to check on it, so I'll follow up with him to see where he's at.  If the issues look different from the app's viewpoint, then, please open separate issues for them.

**Comment by u-u-h** [comment]
Ok.
The user experience is the same as initially, except that I can now enumerate the ofi_rxm;tcp provider endpoints (no segfault anymore in using that provider): AV insert succeeds, `fi_send()` fails with `-65 No route`.

Some endpoints still end up having a port of 0 (all coming from the sockets provider), and some candidates are unusable (`fi_endpoint()` fails with -1), but I can deal with that. Likely I'll disable the sockets provider anyway.

**Comment by u-u-h** [comment]
@shefty Any news on this? Anything I can try help getting this to work?
This is a blocking issue for my application.

**Comment by shefty** [comment]
@nikhilnanal - Have you been able to make any headway looking into this problem?  (Is the the issue that you were looking at?)

Does your code attempt to mix ipv4 and ipv6 addressing in any way?  E.g. inserting both into the same AV, or mixing them between a client and server?

**Comment by u-u-h** [comment]
I guess I should try to build a minimal reproducer for you to look at, as I'm not sure what constitutes 'mixing' in your view, but that is an effort I've tried to avoid for a while now.
I'm creating endpoints for every entry in the fi_info list that I find, and then try to insert all addresses that the remote end has handed over OOB until one is accepted in an endpoint. In doing so I check that the fi->addr_format of the local endpoint matches that of the address that was received OOB, so I don't think I'm trying to insert an IP4 into an IP6 EP or vice versa.
In the particular case I look at now the first pairing succeeds, but then the first actual transfer (`fi_send()`) fails:
```
[D] t4237119 (C02ZD3QXLVDR 41256): mstro_ofi__select_endpoint(ofi.c:2165) Trying remote EP EPD type 2 (MSTRO_EP_OFI_IN6) addr fe80::aede:48ff:fe00:1122%en6:49903
[D] t4237119 (C02ZD3QXLVDR 41256): mstro_ofi__select_endpoint(ofi.c:2167) Trying local EP OFI EP prov tcp;ofi_rxm name TCP-IP straddr fi_sockaddr_in6://[fe80::aede:48ff:fe00:1122]:49919
[D] t4237119 (C02ZD3QXLVDR 41256): mstro_ofi__select_endpoint(ofi.c:2201) AV of ep OFI EP prov tcp;ofi_rxm name TCP-IP straddr fi_sockaddr_in6://[fe80::aede:48ff:fe00:1122]:49919 accepted address
[I] t4237119 (C02ZD3QXLVDR 41256): mstro_ofi__select_endpoint(ofi.c:2207) Using local endpoint OFI EP prov tcp;ofi_rxm name TCP-IP straddr fi_sockaddr_in6://[fe80::aede:48ff:fe00:1122]:49919 to communicate to pool manager at EPD type 2 (MSTRO_EP_OFI_IN6) addr fe80::aede:48ff:fe00:1122%en6:49903
```

**Comment by shefty** [comment]
By mixing, I meant are you ever trying to insert IPv4 and IPv6 addresses into the same AV.  Or attaching an IPv4 endpoint and and IPv6 endpoint to the same local AV.

You said that you allocate 1 endpoint for every fi_info that is returned.  Do those endpoints share the same resources, such as domain, AV, CQ, etc.?

Also, are you limiting yourself to a single provider?  I can help look at problems with the tcp provider, but I can't do anything about gni.
