### ISSUE TITLE
PGI compiler Issue on Rock Cluster frontend node

### ISSUE THREAD

**Issue by usmanfarooq948** [ofiwg/libfabric#5463]
Sorry i am new to Rock Distribution. How a user can compile his application using PGI compiler. As i Know Front-end node only manages software packages on cluster as well as the submitted jobs and compute-end provide the processing power.

**Comment by shefty** [comment]
I would try posting a message to libfabric-users@lists.openfabrics.org and see if anyone subscribed to that list might be able to help.  I'm not sure anyone monitoring these issues would know.
