### ISSUE TITLE
prov/verbs: IPv6 link local address locks multi-node MPI execution

### ISSUE THREAD

**Issue by MatthAlex** [ofiwg/libfabric#5466]
Setting an IP address for Infiniband hardware to IPv4, or IPv6 link local and IPv6 global, results in positive Infiniband traffic on multi-node MPI runs. However, using only IPv6 link local, the run hangs or stalls execution. Additionally, it stalls differently (earlier) when `I_MPI_DEBUG=6` is used.

MPI is only 2 ranks across 2 nodes, pinned with `-rr`.

From what I can tell from the logs, the IPv6 address has been correctly picked up:
```
[0] libfabric:2860:verbs:ep_ctrl:fi_ibv_pep_listen():494<info> listening on: fi_sockaddr_in6://[fe80::5205:700:5b01:11bd]:43700
[1] libfabric:3728:verbs:ep_ctrl:fi_ibv_pep_listen():494<info> listening on: fi_sockaddr_in6://[fe80::5205:700:5b01:b01]:44386
```
[2core-rr-debug1.txt](https://github.com/ofiwg/libfabric/files/3905811/2core-rr-debug1.txt)
[2core-rr-debug6.txt](https://github.com/ofiwg/libfabric/files/3905812/2core-rr-debug6.txt)

Tested with libfabric versions 1.8.1, 1.9.0 (rc1,2,3), and intel MPI 2019.5
Configuration used:
```
./configure --prefix=$HOME/libfabric --enable-verbs=yes --enable-shm=yes --enable-rxm=yes \
--disable-psm --disable-psm2 --disable-sockets --disable-usnic --disable-gni \
--disable-xpmem --disable-udp --disable-tcp --disable-mrail --disable-bgq \
--disable-rstream --disable-perf --disable-hook_debug --disable-efa --disable-rxd
```
Variables used:
```
export I_MPI_FABRICS="shm:ofi"
export I_MPI_OFI_LIBRARY_INTERNAL=0
export FI_LOG_LEVEL=debug
export FI_VERBS_IFACE=ib0
export FI_PROVIDER="shm,verbs"
export I_MPI_DEBUG=1 (6)
```

**Comment by shefty** [comment]
Do you know if the same problem shows up if you use the tcp provider instead of verbs?

**Comment by MatthAlex** [comment]
Indeed, the problem persists on the `tcp` provider, for both IPv6 local and local+global.
Changed configure to enable tcp, `export FI_PROVIDER="shm,tcp"`, and unset `FI_VERBS_IFACE`.
[tcp-ipv6global.txt](https://github.com/ofiwg/libfabric/files/3916147/tcp-ipv6global.txt)
[tcp-ipv6local.txt](https://github.com/ofiwg/libfabric/files/3916148/tcp-ipv6local.txt)

**Comment by nikhilnanal** [comment]
The problem is happening because getaddrinfo(tcp) and rdma_getaddrinfo(verbs) does not return an appropriate sin6_scope_id value. This is leading to server failing to bind or a client in connect. The scope id value is only relevant in the ipv6 link local address case, this problem is not seen with the global ipv6 addresses so these can still be used.  I am trying to experiment with a solution to see if this could be handled in libfabric.
