### ISSUE TITLE
fi_cntr_init globally changes wait function pointer

### ISSUE THREAD

**Issue by jlbyrne-hpe** [ofiwg/libfabric#5472]
If a counter is opened with FI_WAIT_NONE, fi_cntr_init() overwrites the wait function in the counter ops.
https://github.com/ofiwg/libfabric/blob/544500c2e2bf67db268291387bd5e071d890dac7/prov/util/src/util_cntr.c#L244-L247

Unfortunately, ops points to the global util_cntr_ops and it modifies the function for all counters using these ops. Instead of changing wait, the code needs to change ops to a set of no-wait ops.

**Comment by shefty** [comment]
Yes, that's clearly a bug.
