### ISSUE TITLE
Questions about multilink

### ISSUE THREAD

**Issue by abner-ma** [ofiwg/libfabric#5486]
I am curious whether for the data transmission of the link in FI_EP_MSG mode, should I use multithreading to process each link separately(I saw in the pmdk project that multithreading was used to handle multilink.), or directly use the fi_poll function to know that there is data on the link, and then traverse to get which link. Is there an epoll mode?

**Comment by shefty** [comment]
I'm not understanding the question.  Are you using multiple endpoints for communication?

OFI uses epoll when available and appropriate.  For example, it will use epoll with sockets.  But for most providers, data transfers are directly to/from user space, so there's no equivalent.

libfabric has an asynchronous transfer API.  So, you will get a receive completion when data is available.  For most apps using message endpoints, you can allocate a single completion queue.  To check for data, you just need to read the CQ.

**Comment by abner-ma** [comment]
@shefty  Thank you for your  answer.
My English is bad,so let me describe the problem encountered. I want to use libfabric to implement the epoll method similar to tcp sockets. The initial idea is that a completion queue corresponds to a link. When there is data on the link, a function can let me know which completion queue corresponds to the link. Thus data from multiple links can be processed on a single thread. Because I'm not sure if this method is correct, I found an open source project PMDK and found that one of its completion queues corresponds to one link and one thread, and a thread specifically monitors whether there is data on the link through fi_cq_sread. So I'm a little curious whether this should be used under libfabric.

**Comment by shefty** [comment]
Your English is fine.  At a very high level, fi_poll is somewhat similar to epoll, except that it is non-blocking.  So you can call fi_poll to determine which completion queue has an event on it.

Note that many apps can get away with having a single completion queue, with different endpoints bound to the same CQ.  In that case, you would only need to read the CQ to know which endpoint received data.
