### ISSUE TITLE
Multi-threaded OpenSHMEM test invoking remote read operation hangs with RXM provider

### ISSUE THREAD

**Issue by wrrobin** [ofiwg/libfabric#5493]
Attached a re-producer. This test hangs when `shmem_int_get` is invoked with multiple threads. The hang can be avoided by any of these 3 ways:
1. Running the re-producer with single thread (T = 1 in line number 8)
2. Disabling the MR cache by running with FI_MR_CACHE_MAX_COUNT=0
3. Using Fetch AMO instead of Get RMA by passing an argument value 1
e.g. SHMEM_OFI_PROVIDER="verbs;ofi_rxm" oshrun -ppn 1 -np 2 -f hosts ./mr_issue_reproducer 1 
[mr_issue_reproducer.c.txt](https://github.com/ofiwg/libfabric/files/3948858/mr_issue_reproducer.c.txt)

**Comment by shefty** [comment]
Given that disabling the cache is a work-around, this may be related to #5554 .  Setting the cache to use the memhooks monitor may also provide a work-around.

**Comment by shefty** [comment]
@wrrobin - Can you re-test with the latest master?  PR #5562 added a fix to the MR cache that was causing hangs.

**Comment by wrrobin** [comment]
@shefty I am still seeing the same issue with the latest master. Disabling the MR cache still solves the problem.

**Comment by shefty** [comment]
Thanks for testing and reporting back.

**Comment by wrrobin** [comment]
Seems like 1.11.x has resolved this issue. Closing.
