### ISSUE TITLE
Broken fi_pingpong with usnic

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#5497]
It looks like 8b2b28df768b957d85ae800d7aad71b601c780c5 broke `fi_pingpong` for usnic.

It tries to add the local address into the `fi_av`.  In usnic's case, this fails, because there is no IP route from our device back to the localhost (i.e., libnl effectively returns "no route to host").

Is adding the local address to an AV strictly necessary?

If so, it is defined that this is always supposed to work?  For usnic, we had interpreted that it was _not_ supposed to work, because usnic does not support loopback communication.

FYI @dmitrygx

**Comment by jsquyres** [comment]
@dmitrygx @shefty Any thoughts on this one, perchance?

**Comment by shefty** [comment]
I don't believe there's a reason for the test to insert its own address into the AV.

**Comment by jsquyres** [comment]
The commit message says:

> This patch changes behavior of PP by inserting the local and remote address into OFI AV es in the following order:
> 1) The PP client inserts the remote nae and then the local name
> 2) The PP server inserts the local name and then the remote name
> 
> This is needed to construct behavior of many apps that are relises on PMI and its Key-value Storage (KVS).

@dmitrygx Can you confirm that this is actually needed?  Or can we revert 8b2b28df768b957d85ae800d7aad71b601c780c5?

**Comment by shefty** [comment]
Dmitry (sadly) no longer works for Intel, so I don't know that he's tracking libfabric development at this point.  I'm guessing that he might have been tracking a bug in a provider and wanted to have a test case for it, but that's still just a guess.  The test itself doesn't seem to need this.

**Comment by dmitrygx** [comment]
@jsquyres @shefty 
Actually, I can't recall the reason for this change. Perhaps, it was introduced in order to check that RDM/DGRAM EPs support the inserting of local address into OFI AV.
I *think* it would be better to not revert the change. Hopefully, adding something like would be 
better here (there are no other dependencies on `ct->fi_loca;_addr` in the PP code):
```
if (ct->opts.dst_addr) {
    /* Set */
   ret = pp_av_insert(ct->av, ct->rem_name, 1, &(ct->remote_fi_addr), 0,	
                                 NULL);	
   if (ret)	
       return ret;
   
    if (ct->fi->domain_attr->caps & FI_LOCAL_COMM)
       ret = pp_av_insert(ct->av, ct->local_name, 1, &(ct->local_fi_addr), 0,	
                                     NULL);
} else {
    if (ct->fi->domain_attr->caps & FI_LOCAL_COMM)
        ret = pp_av_insert(ct->av, ct->local_name, 1, &(ct->local_fi_addr), 0,	
                                     NULL);	
    if (ret)	
        return ret;
    
    ret = pp_av_insert(ct->av, ct->rem_name, 1, &(ct->remote_fi_addr), 0,	
                                 NULL);	
}
```
@jsquyres it has to work, since usnic sets only `FI_REMOTE_COMM` - https://github.com/ofiwg/libfabric/blob/ebc9f61438c93c111580009b3bc41521dce667d4/prov/usnic/src/usdf.h#L80

wdyt?

**Comment by jsquyres** [comment]
@dmitrygx Yes, your patch works.  Thanks!

The usnic provider only supports remote communications -- it does not support loopback communications.  That's why we set FI_REMOTE_COMM.

Does that answer your question, or are you asking something deeper?
