### ISSUE TITLE
max message size of udp provider

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ofiwg/libfabric#5501]
These days I am writing a communicate library with libfabric, and I have some question of `udp` provier:   
It seems that the when use the `udp` provider, I can't send messages above 7kb, which is to say that `fi_send` can't handle buffer length of which is greater 7kb. Does provider `udp`' have this limits? and if yes, how can I get the max message length of a provier?

**Comment by shefty** [comment]
All providers have max_msg_size limits.  That limit is reported through fi_getinfo() as part of the endpoint attributes.

For UDP, the limit will be the link level MTU, minus headers.  It does not support message segmentation

**Comment by Keepmoving-ZXY** [comment]
ok, thank you.
