### ISSUE TITLE
prov/shm: functional issue with oneCCL test

### ISSUE THREAD

**Issue by mshiryaev** [ofiwg/libfabric#5508]
Hello,

I noticed that there is correctness issue on CCL test with shm provider. This test starts bunch of allreduce operations in parallel, then complete them all and then do correctness check.
With bunch size=1 or with non-shm providers this test works well, but with bunch size>1 and with shm provider test fails. With larger bunch size (like 8 or 16) it is reproduced more stable.

Here are steps to reproduce:

git clone https://github.com/intel/oneccl.git
cd ./oneccl
mkdir build
cd ./build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j install
. ./_install/env/setvars.sh
FI_PROVIDER=shm CCL_LOG_LEVEL=1 CCL_ATL_TRANSPORT=ofi LD_PRELOAD=”<…>/libfabric.so” mpiexec.hydra -n 4 -ppn 1 ./_install/examples/common/benchmark cpu regular allreduce

It will fail with output like this:
“ASSERT '0' FAILED unexpected value
allreduce: recv_bufs: buf_idx 0, elem_idx 0, expected 6.000000, got 1.000000”

Bunch size can be controlled in code, modify “BUF_COUNT” define value at the very beginning of ./examples/common/benchmark.cpp. 16 is default value. If you will set BUF_COUNT=1 then test should work with shm too.

Test works well with psm2/tcp/verbs providers and fails with shm.

Could you please take a look on this?

**Comment by aingerson** [comment]
@mshiryaev I managed to recreate the failures, even with the new changes I emailed you about. I will take a look at this. Thank you!
