### ISSUE TITLE
shm provider has multiple issues with signal handlers

### ISSUE THREAD

**Issue by jlbyrne-hpe** [ofiwg/libfabric#5520]
The shm provider registers signal handlers in its init routine and this causes changes to application behavior even if the provider is not being used. The signal handler's attempt to re-register the original handler and raise a signal is interesting --- I hadn't considered this --- but the fact the only one old sigaction is used for all signals is a bug. 

The signal handlers should only be registered with the creation of the provider object that creates the files that need to be cleaned up.

As to the nesting issue, the immediate problems call probably be solved with per-signal storage of the old sigaction, but has anyone created a library API for nesting signal handlers generically? I'm unaware of one. While we might create an API in the utility code, I don't see how it could work reliably unless all users of signal handlers call it.

**Comment by jlbyrne-hpe** [comment]
...problems *can* probably be solved...

**Comment by rajachan** [comment]
You are right, the old_sigaction is not signal-specific. Like you say, the simplest fix would be to have separate objects for each signal's old_sigaction.

> The shm provider registers signal handlers in its init routine and this causes changes to application behavior even if the provider is not being used

How so? The only action taken in these handlers is to cleanup the shm files, which would be a no-op if shm is not used. Are you seeing some case where these handlers are interfering with applications in some way? There was one case with SIGBUS that I had noted in the original commit (https://github.com/ofiwg/libfabric/commit/d8f6f623c16b6a74eff0412e9933544aa16ad748) but that only affects cases where shm is used actively.

**Comment by jlbyrne-hpe** [comment]
Yes, I  had a tester not using shm and had registered a handler for SIGTERM and was not getting the signal delivered because of the bug, but the larger argument I'd make is that, ideally, a provider that isn't being used should have no side-effects on application execution.  I believe this is impossible in the strictest sense because of the way fi_getinfo() works, but it is a goal we should strive for.

As a practical matter, if you do signal-handler nesting properly and the application does not, it is to your advantage to register as late as possible. It increases the chance of everyone getting their desired behavior.

I do think nested signal handling should be a part of the util code, perhaps even exposed as a part of the API.

**Comment by bfaccini** [comment]
Are there any plans to implement a per-signal/handler backup/restore in shm provider ?
Current lack is causing a real problem when you want to implement your own and different signal handlers inside an application using libfabric.

**Comment by shefty** [comment]
This should be handled somehow.

**Comment by rajachan** [comment]
Agreed, I will write up a fix for this.


Raghu

On Jan 13, 2020 8:34 AM, Sean Hefty <notifications@github.com> wrote:

This should be handled somehow.

**Comment by zhngaj** [comment]
#5613

**Comment by aingerson** [comment]
@jlbyrne-hpe Can you confirm that #5613 fixed your issue?

**Comment by shefty** [comment]
#5613 should have fixed this.
