### ISSUE TITLE
Potential fabric/domain locking issue in util_getinfo() 

### ISSUE THREAD

**Issue by jlbyrne-hpe** [ofiwg/libfabric#5530]
` 

               fabric = ofi_fabric_find(&fabric_info);
                if (fabric) {
                        FI_DBG(prov, FI_LOG_CORE, "Found opened fabric\n");
                        (*info)->fabric_attr->fabric = &fabric->fabric_fid;

                        fastlock_acquire(&fabric->lock);
                        item = dlist_find_first_match(&fabric->domain_list,
                                                      util_find_domain, *info);
                        if (item) {
                                FI_DBG(prov, FI_LOG_CORE,
                                       "Found open domain\n");
                                domain = container_of(item, struct util_domain,
                                                      list_entry);
                                (*info)->domain_attr->domain =
                                                &domain->domain_fid;
                        }
                        fastlock_release(&fabric->lock);

                }                                                                
`
The locking in the above code from util_getinfo() really doesn't against the fabric structure going away. I would think that any issue is unlikely to be seen in practice because of the general flow of fi_getinfo() vs the creation/destruction of a provider's fabric structures in an application, but it feels wrong not to have a reference count or lock preventing this.

ofi_fabric_find() uses common_locks.util_fabric_lock. The easiest fix would be to have a _nolock version ofi_fabric_find() and hold the mutex manually across the entire test.

**Comment by shefty** [comment]
fabric->lock is protecting the domain list.  The util_fabric_lock protects the fabric list.  The 'issue' is that ofi_fabric_find() doesn't take a reference on the fabric object.

As soon as we release either lock, the fabric and domain could be destroyed and we can return an fi_info structure that references deleted objects.  Holding references would help against accessing freed memory, but the app is basically in a mess now.  For example, to the app, it's only opened the fabric once, then called close on it.  A separate thread calls fi_getinfo(), which takes a reference on the fabric.  When is that reference released?  Is the app supposed to call close every time it calls fi_getinfo?

I agree that we should hold the util_fabric_lock across the entire call here.  That's probably the best that we can do.  Then document that if fi_getinfo is called in parallel to another thread calling close on a fabric or domain, that the returned fi_info structure may reference the closed object.  Multi-threaded apps that behave in this manner should not rely on the fabric/domain objects to be valid.
