### ISSUE TITLE
Handling the case where core providers use another core provider?

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#5542]
We're looking for some advice on how we should handle the case where a core provider would like to load and use another core provider.

This is related to PR #5536 where we ran into an app that set `FI_PROVIDER=efa` and failed to load EFA due to the issue mentioned in the PR. For that app, shared memory is done at a higher level so it's okay to disable the SHM provider. However, we've found other applications that do set `FI_PROVIDER=efa` that will benefit from using SHM in Libfabric. We'd like to come up with a solution for this case that doesn't require users to change their scripts.

We can set the `OFI_GETINFO_INTERNAL` flag when calling `fi_getinfo("shm")` in EFA to skip the filter but the SHM provider isn't loaded in `fi_ini()` due to the filter. Should we unconditionally load providers like SHM? Or should we allow core providers to explicitly register a provider that wasn't loaded previously?

**Comment by shefty** [comment]
I had a several thoughts on this, but after typing a story, I decided to trim it down.

I believe this feature is desirable and will become used more once we have it.
I don't think we want to load providers unconditionally or change current filtering.

We can use an internal getinfo flag (e.g. OFI_CORE_PROV_ONLY / OFI_GETINFO_INTERNAL), along with a provider name to force load a provider into a hidden provider list, if it isn't already loaded.  As a hidden provider, it would still be filtered for direct user queries.

**Comment by rwespetal** [comment]
Thanks, that seems reasonable to me. I'll work on a patch for this.

**Comment by rwespetal** [comment]
I opened #5547 with one approach to this - let me know if that matches what you were thinking or not.
