### ISSUE TITLE
Equivalent to FI_WAIT_FD for Windows

### ISSUE THREAD

**Issue by dylanede** [ofiwg/libfabric#5588]
Currently, `util_wait_fd_control` returns `-FI_NOSYS` on Windows because it does not have support for epoll (`HAVE_EPOLL` is undefined). From my initial investigations into using libfabric, I have found that this stops wait sets from being usable with RxD over UDP on Windows, since RxD depends on the underlying provider supporting `FI_WAIT_FD`. Perhaps support for [Win32 I/O Completion Ports](https://docs.microsoft.com/en-us/windows/win32/fileio/i-o-completion-ports) would fill this gap in support? I/O Completion Ports use file handles, which are pointer-sized, so they wouldn't be a drop in replacement for the `int`-sized file descriptors currently used, and therefore it might require some API changes.

Regardless, I appreciate the well-thought-through design of this library.

**Comment by shefty** [comment]
I agree that the best option for windows is I/O completion ports, and it would require API changes.  Windows has been a relatively low priority with most of the current developers.  The API changes themselves may not be too bad, but it would take some effort to update the internal implementation to support I/O completion ports.

Just thinking... maybe windows could be made to work with an option like FI_WAIT_SOCKET?  If the fd's used internally for waiting actually map to sockets, the epoll abstraction could be made to work.  I don't know if that's always the case without digging through all the code.
