### ISSUE TITLE
Windows `ofi_recvmsg_udp` returns error codes incorrectly

### ISSUE THREAD

**Issue by dylanede** [ofiwg/libfabric#5590]
I have found that when `WSARecvMsg` fails with `SOCKET_ERROR` (-1), for example due to the socket not being ready to receive (`WSA_IO_PENDING`), `ofi_recvmsg_udp` returns this 32-bit error code cast without sign extension to a 64-bit integer, producing 4294967295. Since this is positive, `udpx_ep_progress` treats this as success and produces a completion event for receiving a message of length 4294967295.

Instead of this behaviour, `WSAGetLastError` should be called in `ofi_recvmsg_udp` to check the type of error and act appropriately. At the very least the cast of the return value should be fixed.

I don't fully understand libfabric internals at this point, but I will see if I can put an appropriate PR together.

**Edit:** The reason the sign extension is not happening is because `bytes` is an unsigned 32-bit integer, so the conditional operator is implicitly casting away the sign of `ret` due to integer promotion rules. The resulting unsigned 32-bit integer is then cast to a signed 64-bit integer, which of course does not do any sign extension. An appropriate fix for this then is to change line 595 in osd.c to
```C
return ret ? (ssize_t) ret : (ssize_t) bytes;
```

What is the general state of Windows support? What is known to work? Even after this fix I still cannot get a UDP message to be received.

**Comment by dylanede** [comment]
Further investigation shows that the error that `WSARecvMsg` is failing with is `WSAEOPNOTSUPP`, which would suggest that the socket has not been set up properly.

**Comment by dylanede** [comment]
Other problems in `msghdr` (corresponding to `WSAMSG`):

* msg_iovlen, which corresponds to `dwBufferCount`, has the wrong size. It should be an unsigned 32-bit int instead of `size_t`
* `iovec` is used in lieu of `WSABUF` from the Win32 API, but the layout doesn't match:
  * `iovec` is pointer to data followed by `size_t` length
  * `WSABUF` is unsigned 32-bit length followed by pointer to data
* `msg_control` and `msg_controllen` are in the wrong order to emulate the `WSABUF Control` member of `WSAMSG`, similar to the problem with `iovec` above.

**Comment by dylanede** [comment]
After correcting the layout of the structure as per my previous comment I am now successfully receiving messages. I'll submit a PR.

**Comment by shefty** [comment]
Thanks for the information.  I'll wait for your PR.

**Comment by dylanede** [comment]
I'm currently waiting on approval from work to make the PR.
