### ISSUE TITLE
prov/shm: fi_ubertest failed with master branch

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5595]
I ran fabtests with master branch (HEAD 70c2f242f) with shm provider, and it's failing with fi_ubertest. Just want to double check if I was missing something option or it's expected. 
```
/fabtests/install/bin/runfabtests.sh -v -t all  -f /home/ec2-user/ofiwg-libfabric/fabtests/install/share/fabtests/test_configs/shm/shm.exclude -p /home/ec2-user/ofiwg-libfabric/fabtests/install/bin shm  172.31.32.230  172.31.32.230 | tee shm-master.log
```

```
.....
    Starting test 449 / 690:
    [shm, latency, atomic (FI_SUM, FI_INT64)--, FI_EP_RDM, FI_AV_UNSPEC, eq_wait_none, cq_wait_none, cntr_wait_none, comp_queue -- tx (bind-NONE, op-NONE), rx: (bind-NONE, op-NONE),  FI_PROGRESS_MANUAL, FI_THREAD_SAFE (only hints), [], [], [FI_MSG, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE]]
    lat                                               16      5       160         0.00s      5.00       3.20       0.31
    lat                                               192     5       1.8k        0.00s     68.57       2.80       0.36
    lat                                               768     5       7.5k        0.00s    187.32       4.10       0.24
    lat                                               3k      5       30k         0.00s    503.61       6.10       0.16
    lat                                               12k     5       120k        0.00s       inf       0.00        inf
    lat                                               48k     5       480k        0.00s       inf       0.00        inf
    lat                                               192k    5       1.8m        0.00s       inf       0.00        inft_fw_recv(): common/shared.c:3182, ret=-1 (Operation not permitted)
    recv: Connection reset by peer
    ft_run_latency(): ubertest/test_ctrl.c:1089, ret=-256 (Unspecified error)
```

[shm-master.log](https://github.com/ofiwg/libfabric/files/4142028/shm-master.log)

**Comment by aingerson** [comment]
We run shm with the ubertest on our CI so I wouldn't expect to see any failures. One thing to note though is that the total time for shm running the ubertest usually exceeds the default timeout for runfabtests.sh (120). When we run our CI we change the default to 300 seconds to let shm run to completion. I'm seeing it currently run at 135 seconds so try increasing to at least ~150 and see if that allows it to pass. This is done with the -T <seconds> option

**Comment by aingerson** [comment]
Also, the shm tests do not work with the negative tests. You can disable them with the -N argument

**Comment by zhngaj** [comment]
We discussed the negative tests before, so I'm aware of it. 
Thanks for your clarification for ubertest.

**Comment by zhngaj** [comment]
Verified it's just a timeout issue, so close it.

**Comment by rajachan** [comment]
We're making some updates to the AWS-CI infrastructure today, which will start running shm in the single-node matrix. This was long time coming, but was blocked on some other CI work.
