### ISSUE TITLE
ofi_rxm: Seg Fault in rxm_ep_send_common.constprop when sending a message greater than 131072 bytes

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#5596]
This problem occurs whenever the nessage transfer size is greater than 131072 bytes in length (128K bytes).  The application was setting the domain->attr->mr_mode to FI_MR_BASIC.

The application was passing a NULL parameter for the desc on the fi_send API call.

The test case was using the provider: verbs;ofi_rxm.

This problem occurs at least when using the SEND and SENDDATA APIs.

The traceback for this problem is:
#0  0x00007f9128d61f63 in rxm_ep_send_common.constprop ()
--
from /scratch/jenkins/builds/libfabric/tags/nightly/lib/libfabric.so.1
#1  0x00007f9128d64008 in rxm_ep_senddata () from /scratch/jenkins/builds/libfabric/tags/nightly/lib/libfabric.so.1
#2  0x00007f91294300e4 in fi_senddata (context=0x1000001, dest_addr=<optimized out>, data=65537, desc=0x0,
len=131073, buf=0xee7680, ep=0xecbfb0)
at /scratch/jenkins/builds/libfabric/tags/nightly/include/rdma/fi_endpoint.h:317

The application was in error for not registering the local memory and passing the mr_desc value on the fi_send API call.  But libfabric should not be Seg Faulting when this type of user error is encountered.  An appropriate error message should be returned.

**Comment by shefty** [comment]
We don't want these sort of checks in the fast path operation, as they are coding errors, not run time.  A segfault is appropriate.

**Comment by jswaro** [comment]
Since assertions are compiled out for production builds anyway, an assertion or #if debug option doesn't seem like a bad compromise. 

I understand your perspective on this, and agree for the most part. I think there is value in returning clear information about the problem to the user that isn't really conveyed by a segfault. 

```assert(desc || !(info->mr_mode & FI_LOCAL_MR));``` 

Thoughts?

**Comment by shefty** [comment]
Yes, an assertion driving segfault would be ideal here.
