### ISSUE TITLE
1.9.0 - fi_pingpong -p shm ... - allocates a buffer too small for address

### ISSUE THREAD

**Issue by nufosmatic** [ofiwg/libfabric#5597]
I can't tell if this is a bug in provider shm or in the app fi_pingpong. The prov/shm/src/smr_ep.c::smr_getname() returns the correct size of the address, but then pingpong.c::pp_send_name() allocates a buffer with no accommodation for the NUL terminal character.

Workaround is to increment the "addrlen" acquired from smr_getname() before using it for allocation or further accommodation.

Doesn't appear to be an issue for sockets or verbs.

$ build*/bin/fi_pingpong -p shm -e rdm & sleep 1 ; build*/bin/fi_pingpong -p shm -e rdm localhost
[1] 234302
addrlen=15
buffer=234302:2041:0:0 (15) addrlen=15
fi_getname(): util/pingpong.c:566 , ret=-257 (Provided buffer is too small)
[error] util/pingpong.c:521 : ctrl/read: no data or remote connection closed
[1]+  Exit 1                  build*/bin/fi_pingpong -p shm -e rdm

**Comment by aingerson** [comment]
This issue was fixed a couple months ago here with commit cc93726c9e10979d89b75b033aba34661f20a326
Make sure you're running on master.
