### ISSUE TITLE
verbs;ofi_rxm: should either stop advertising FI_DELIVERY_COMPLETE or support it

### ISSUE THREAD

**Issue by gbtitus** [ofiwg/libfabric#5601]
If I include `FI_DELIVERY_COMPLETE` in my `fi_getinfo()` `hints->tx_attr->op_flags`, on an InfiniBand-based system with a libfabric that includes the verbs and ofi_rxm providers, then verbs;ofi_rxm is included in the returned provider list.  But based on an email conversation (libfabric-users@lists.openfabrics.org or ofiwg@lists.openfabrics.org, Jan 28-29 2020, Subject: "no perf effect from FI_MORE with verbs; ofi_rxm provider?"), it seems that the verbs;ofi_rxm provider doesn't actually support `FI_DELIVERY_COMPLETE`, but silently provides `FI_TRANSMIT_COMPLETE` semantics instead.  This can lead to application errors, in my case when an initiating node does a bunch of RDMA writes and then continues, believing that the target node must be able to see the results of those in its memory when in fact the latter cannot yet do so.

To correct this, the verbs;ofi_rxm provider should either not include itself in the list of providers returned by `fi_getinfo()` when `FI_DELIVERY_COMPLETE` is requested, or it should support proper `FI_DELIVERY_COMPLETE` semantics.  Either of these has potential difficulties, of course.  No longer including verbs;ofi_rxm when `FI_DELIVERY_COMPLETE` is requested will result in applications using a less-capable provider or perhaps even failing to find an appropriate provider at all.   That would be unfortunate, to say the least.

Adding `FI_DELIVERY_COMPLETE` support in verbs;ofi_rxm is clearly the better solution.  It will undoubtedly have a performance penalty, but perhaps that will be just the impetus needed for developers to discover that all they really need is `FI_TRANSMIT_COMPLETE` along with stronger ordering constraints and/or improved completion handling.

**Comment by shefty** [comment]
Based on previous attempts, we must continue to report FI_DELIVERY_COMPLETE incorrectly, or most/all MPIs will break.  :(  True support for FI_DELIVERY_COMPLETE is required.  Maybe an environment variable could be used to disable real delivery complete semantics until apps can update to the semantics that they really need.

**Comment by gbtitus** [comment]
> ... we must continue to report FI_DELIVERY_COMPLETE incorrectly, or most/all MPIs will break.

I'm slightly puzzled by this.  Those MPIs surely aren't depending upon full `FI_DELIVERY_COMPLETE` semantics, because the provider doesn't provide that.  Are they "breaking" because they end up either not finding a provider at all or finding one that doesn't actually use the IB network hardware and so cannot deliver the performance they expect?  If so, it seems they could easily switch to asking for `FI_TRANSMIT_COMPLETE` instead.  Or is the situation more complicated, in that when delivery_complete is specified verbs;ofi_rxm actually provides something that is neither delivery_complete nor transmit_complete but rather somewhere in between (by virtue of some feature of the IB hardware or the verbs provider), and the MPIs are relying on that without knowing they're doing so?

**Comment by shefty** [comment]
They were asking for FI_DELIVERY_COMPLETE, so they would not find a provider.

**Comment by gbtitus** [comment]
> They were asking for FI_DELIVERY_COMPLETE, so they would not find a provider.

Understood, but is there anything deep (i.e., other than fear, uncertainty, and doubt) that would prevent them from asking for `FI_TRANSMIT_COMPLETE` instead?  They can't have a functional dependence on full delivery_complete semantics, because they're not getting it.  Are we just stuck waiting for them to change this one token in their sources and do releases, and then for all their older releases to trickle into disuse?  (alas, if so)

**Comment by shefty** [comment]
Yes, we're pretty much stuck waiting for them to change and older releases to trickle out.  I'm 100% certain that breaking MPI will result in years of bug reports.

**Comment by bcernohous** [comment]
>They were asking for FI_DELIVERY_COMPLETE, so they would not find a provider.

So giving them a provider that does not actually provide FI_DELIVERY_COMPLETE is the answer?

Do they, or do they not, require FI_DELIVERY_COMPLETE?

**Comment by shefty** [comment]
MPI does not.

**Comment by gbtitus** [comment]
Even for MPI-3 one-sided communication?  I'm far from an MPI expert.  Are the guarantees about when an MPI-3 one-sided PUT is visible on the target defined in such a way that an MPI library would choose to use something other than `FI_DELIVERY_COMPLETE`, in a libfabric-based implementation?

**Comment by shefty** [comment]
I don't know the details.  I'm not an MPI developer.  I know that when we tried to fix this by removing support, it broke the MPIs.  I also know that no hardware I'm aware of supports this level of completion, so there are ways to work around it.  This is likely limited to one-sided MPI RMA operations, which has maybe one broad user (nwchem?).  So nearly all MPIs applications would be unaffected.  My understanding is that MPI can fallback to an active messaging path in that case.

**Comment by jswaro** [comment]
> Are the guarantees about when an MPI-3 one-sided PUT is visible on the target defined in such a way that an MPI library would choose to use something other than `FI_DELIVERY_COMPLETE`, in a libfabric-based implementation?

We have a responsibility as maintainers and developers of a libfabric provider to advertise what we can support as accurately as possible. It is up to MPI and other upper-layer frameworks to write to what is provided by libfabric, if any provider meets the requirements of the framework. 

@shefty is stating the changing the advertised delivery model would cause problems with MPI support for the foreseeable future, and that the change should be postponed so that MPI has a chance to react prior to the change in libfabric. @shefty , Does that sum it up ? 

I do think that we need to advertise transmit complete, or a mechanism must be provided for delivery complete behavior if that is going to be required. It's about honoring our agreement with the user application and being accurate about what providers report. This discussion has been had in other issues/PR: #5011 , #5027

**Comment by bcernohous** [comment]
>My understanding is that MPI can fallback to an active messaging path in that case.

Then they can fall back to not requiring FI_DELIVERY_COMPLETE and libfabrics can stop pretending.  

Anyone writing something new and relying on accurate information from the provider is screwed.

**Comment by gbtitus** [comment]
> Then they can fall back to not requiring FI_DELIVERY_COMPLETE and libfabrics can stop pretending.

Well, sure, but if libfabric just drops it on them with no warning they and their users are both going to be upset.  And there's not a really good way to warn them, because libfabric has the not-at-all-uncommon problem of not knowing who all is using it.

**Comment by bcernohous** [comment]
>Well, sure, but if libfabric just drops it on them with no warning they and their users are both going to be upset. And there's not a really good way to warn them, because libfabric has the not-at-all-uncommon problem of not knowing who all is using it.

And somehow the status quo will lead to a fix in MPI?

**Comment by gbtitus** [comment]
> And somehow the status quo will lead to a fix in MPI?

No, I think the question is just how best to get the change made first in the provider's direct users, that is the MPI implementations.  If we don't do that we run the risk of breaking the applications, which would be unfortunate because they (1) pay the bills and (2) don't know this situation exists and couldn't do anything about it if they did.

**Comment by shefty** [comment]
The answer is that libfabric should be updated to support the desired semantic.  As free, open source software, anyone can contribute that fix.

**Comment by bcernohous** [comment]
Are you asking for a fix to fi_getinfo to provide accurate attributes?   

Or a fix to provide a semantic (FI_DELIVERY_COMPLETE) that hardware doesn't provide and MPI doesn't actually need?

**Comment by shefty** [comment]
To provide a correct implementation of delivery_complete.
