### ISSUE TITLE
prov/shm: smr_map_add return value issue

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5636]
https://github.com/ofiwg/libfabric/blob/3c35d62af6e043fbdb09502fc3b725bad240d9eb/prov/util/src/util_shm.c#L285

This looks like an issue, and it should directly return `ret` IMO. 
Is there any particular reason we return in this way?

**Comment by aingerson** [comment]
The reason behind this was to allow for the case where the peer has not been initialized yet and hasn't created the shared memory region yet so shm_open will return ENOENT. If this happens, we don't want to return an error to the user, but just postpone the mapping when the application initiates it's first send. On every shm send, we call shm_verify_peer which tries to map it again if it wasn't mapped successfully before. The shm_verify_peer has the same ENOENT check that the smr_map_add call has.
We could push this check up to smr_map_to_region and then change the return check in smr_verify_peer to check the peer.addr again.

**Comment by zhngaj** [comment]
I see your point, and it sounds reasonable to me. 
My concern is that the shm region mapping could never be successful if the user passes the wrong address (the corresponding shm file name does not exist at all). In this case, if warn level log is enabled, it will keep dumping the `shm:av:smr_map_to_region():197<warn> mmap error` to the user's log file, which could potentially use up all the file system space. 

For such case, I'm thinking to add a retry counter to limit the number of calling `smr_verify_peer`. I'm glad to have your feedback.

**Comment by shefty** [comment]
Retry counters aren't useful.  Many apps spin on retrying failed operations.  If we're concerned about logging space, I would look at adding a couple of new logging functions, similar to what the linux kernel has.  E.g. FI_WARN_ONCE and FI_LOG_RATE_LIMITED.  I haven't looked at how the linux kernel implements similar calls, but some sort of static var might do it.

**Comment by zhngaj** [comment]
Add FI_WARN_ONCE in PR #5642

**Comment by zhngaj** [comment]
PR #5642 merged, close
