### ISSUE TITLE
prov/shm: RMA read operation fails if CMA is not available.

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5656]
The RMA read operation with shm provider (e.g., `fi_rma_bw -e rdm -o read -p "shm"` in fabtests) fails if CMA is not available. 
This is because no matter what the message size is, the local endpoint always calls `smr_format_iov`, and the remote endpoint has to call `smr_progress_iov`. If CMA is not available, `smr_progress_iov` will fail. 

Tested with master [5ef6249](https://github.com/ofiwg/libfabric/commit/5ef62492e43ccd2cc87927848b6cba482472d8b7).
Server: fi_rma_bw -e rdm -o read -p "shm"  -s [node_ip]
Client: fi_rma_bw -e rdm -o read -p "shm"  -s [node_ip] [node_ip]

**Comment by aingerson** [comment]
@zhngaj Working on fixing this btw
