### ISSUE TITLE
how to capture packet send by usNIC?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ofiwg/libfabric#5657]
Is there any tools that enable me capture packet sent by `usNIC`, and I also want to know that can `wireshark` parse packet sent by `usNIC`?

**Comment by shefty** [comment]
@jsquyres for the first question ?

Wireshark should be able to parse the packets, which are just UDP/IP.

**Comment by jsquyres** [comment]
There are not, sorry.

usNIC is OS Bypass.  By definition, OS tools will not see usNIC traffic.

Your best bet is to run your outbound traffic through an inline analyzer (e.g., even routing through another node running Linux where you can capture the traffic going from one port to another).

**Comment by Keepmoving-ZXY** [comment]
ok, I will configure port mirroring on switch.
