### ISSUE TITLE
prov/shm: RMA write failed in fi_ubertest #49

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5659]
### Failure
RMA write failed in fi_ubertest (test 49)

```
[shm, latency, write--, FI_EP_RDM, FI_AV_UNSPEC, eq_wait_none, cq_wait_none, cntr_wait_none, comp_queue -- tx (bind-NONE, op-NONE), rx: (bind-NONE, op-NONE),  FI_PROGRESS_MANUAL, FI_THREAD_SAFE (only hints), [FI_MR_VIRT_ADDR], [], [FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE]]
name                                              bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
lat                                               16      10k     312k        0.04s      8.75       1.83       0.55
lat                                               32      10k     625k        0.03s     19.08       1.68       0.60
lat                                               64      10k     1.2m        0.03s     39.36       1.63       0.61
fi_ubertest: ./include/ofi_mem.h:224: smr_freestack_pop_impl: Assertion `next != NULL' failed.
Aborted (core dumped)
```

### To reproduce
1. checkout master branch commit [5ef62492e](https://github.com/ofiwg/libfabric/commit/5ef62492e43ccd2cc87927848b6cba482472d8b7)

2. run server/client command:
Server: FI_SHM_DISABLE_CMA=1 /path/to/libfabric/fabtests/install/bin/fi_ubertest -x
Client: FI_SHM_DISABLE_CMA=1 /path/to/libfabric/fabtests/install/bin/fi_ubertest  -u /path/to/libfabric/fabtests/test_configs/shm/all.test -y 49 -z 49 [NODE_IP]

**Comment by zhngaj** [comment]
PR #5667 to fix this issue

**Comment by shefty** [comment]
shm reports that it does not require FI_MR_VIRT_ADDR.  The fi_getinfo call should return with this bit cleared.  Check the non-cma path to ensure that it is using 0-based offsets for RMA.

**Comment by zhngaj** [comment]
Thanks for your comment, @shefty 

> shm reports that it does not require FI_MR_VIRT_ADDR. The fi_getinfo call should return with this bit cleared.
You are correct. In this case, I think fi_ubertest 49 needs to use 0-based offsets for RMA even though it requests FI_MR_VIRT_ADDR via hints. 
Looking at the function ft_fw_update_info https://github.com/ofiwg/libfabric/blob/b5a1f96f9605eeeae299f2c12cd762c2694195de/fabtests/ubertest/uber.c#L273, it seems that mr_mode update is missing. If this looks reasonable, I can update the PR.

In addition, shm provide implements FI_MR_VIRT_ADDR memory mode, as per https://ofiwg.github.io/libfabric/master/man/fi_shm.7.html. What would be an appropriate way to test virtual address based (FI_MR_VIRT_ADDR) RMA operations, given that fi_getinfo call clears this bit.

**Comment by zhngaj** [comment]
I opened another PR #5672 to update the test_info's mr_mode bit with the one returned from the provider.

**Comment by zhngaj** [comment]
close
