### ISSUE TITLE
MR_CACHE userfaultfd leads to connection rejects on verbs.

### ISSUE THREAD

**Issue by vschhabra** [ofiwg/libfabric#5662]
When using Verbs provider, we are seeing connection rejects leading to a failure of communication.

Client:
libfabric:172083:ofi_rxm:ep_ctrl:rxm_conn_handle_reject():1143<warn>connection reject:
 no reject error data (cm_data) was found (data length expected: 2
 found: 0)

On Server we see:

libfabric:180424:core:mr:ofi_monitor_subscribe():205<warn>
Failed (ret = -14) to monitor addr=0x7fb204041780 len=408

libfabric:180424:ofi_rxm:ep_ctrl:rxm_conn_handle_notify():1096<info>
notify event 1

libfabric:180424:verbs:domain:vrb_ep_close():360<info> EP
0x7fb2cc000a30 is being closed

FI_MR_CACHE_MAX_COUNT=0
(Turning MR CACHE off) makes is a workaround with reduced performance.

**Comment by shefty** [comment]
Email communication indicated that using the memhooks cache monitor also worked.

**Comment by shefty** [comment]
pull request #5666 changes the default memory monitor option until the usefaultfd problem can be resolved.

**Comment by rwespetal** [comment]
Does turning on `FI_LOG_LEVEL=warn` give any useful information? I see a print in `ofi_uffd_register` that should give the errno for the failed userfaultfd registration.

Can we have providers override the default if the caching mechanism is not explicitly set? We'd like to keep userfaultfd enabled for EFA.

**Comment by shefty** [comment]
I assume the errno is -14.  The monitor can still be set through the environment variable.  Does that work for you?  I'm also okay letting a provider change the default.

**Comment by rwespetal** [comment]
Looking at `ofi_uffd_register` it returns -14 for all errors - seems like that's a side effect of having to try all the page sizes. I can open a PR to make this better.

I think we'd prefer to change the default in code for EFA instead of an environment variable. I didn't realize that the glibc memory hooks were replaced with syscall intercepts instead so this change might be okay.

**Comment by shefty** [comment]
Yeah, the glibc memory hooks don't work.  What we have was pulled from OpenMPI, which they've used for quite some time now.

**Comment by swelch** [comment]
@shefty, @vschhabra  - Is there a reproducer defined for this error when userfaultfd? userfaultfd has been working well for me, so I'd like to see what other issues there might be.

**Comment by shefty** [comment]
I'm not aware of any specific reproducer.  The reports I have from the MPI and DAOS teams is that with any caching turned on data corruption occurs.   There's a PR open now to add a better test app to fabtests

**Comment by swelch** [comment]
> The reports I have from the MPI and DAOS teams is that with any caching turned on data corruption occurs.
@shefty - If the MPI folks know of an IMB test that can cause corruption (possibly detected with -DCHECK) when using userfaultfd then that test case would be appreciated.

> There's a PR open now to add a better test app to fabtests
Yes, I've seen this and it looks like a good test to verify cache monitor events are received/processed
