### ISSUE TITLE
Sockets provider no longer works with mercury + ofi b5a1f96f9605eeeae299f2c12cd762c2694195de

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#5675]
Updating CART to OFI of b5a1f96f9605eeeae299f2c12cd762c2694195de causes sockets provider to no longer work.

Previous OFI that worked was 955f3a07dd011fb1dbfa6b6c772ada03d5af320e

verbs provider still works in latest ofi.

When using b5a1f9 mercury fails to initialize sockets provider with mercury errors of:

hg   ERR  # NA -- Error -- /home/aaoganez/github/liwei/cart/_build.external-Linux/mercury/src/na/na_ofi.c:1677
# na_ofi_domain_open(): No provider found for "sockets" provider on domain "lo"
hg   ERR  # NA -- Error -- /home/aaoganez/github/liwei/cart/_build.external-Linux/mercury/src/na/na_ofi.c:3041
# na_ofi_initialize(): Could not open domain for sockets, lo
hg   ERR  # NA -- Error -- /home/aaoganez/github/liwei/cart/_build.external-Linux/mercury/src/na/na.c:312
# NA_Initialize_opt(): Could not initialize plugin

As far as I can tell form mercury code the fi_info::caps are set to:

FI_TAGGED | FI_RMA for all providers

For sockets additional caps are:
FI_SOURCE | FI_DIRECTED_RECV

**Comment by shefty** [comment]
From email thread:

Now if do fi_info I get:
provider: sockets
    fabric: sockets
    domain: sockets
    version: 2.0
    type: FI_EP_RDM
    protocol: FI_PROTO_SOCK_TCP

etc etc
before it was:
provider: sockets
    fabric: ::1/128
    domain: lo
    version: 2.0
    type: FI_EP_RDM
    protocol: FI_PROTO_SOCK_TCP

**Comment by shefty** [comment]
This apparently only happens on master with a clean install, and not on 1.9.1.  The fabric/domain names will default to 'sockets' if there is an error resolving the IP/netdev names.

**Comment by shefty** [comment]
Report that reverting 8ac53a9a65f77f2e045e1896d07f39afc072ddab fixes the issue

**Comment by shefty** [comment]
Prior to 8ac53a9a65f77f2e045e1896d07f39afc072ddab sockets implemented its own 'getinfo' calls.  That was changed to call util_getinfo.  As part of the change, an internal call to sock_fi_info() was lost.  The sock_fi_info() call was responsible for setting the fabric and domain names.

**Comment by shefty** [comment]
The current status of a fix for this is here: https://github.com/ofiwg/libfabric/pull/5698

I see an issue updating the fabric and domain names when a source address is provided, but no EP type is given.   I'm working on an update to that and will validate the patches more tomorrow.

**Comment by shefty** [comment]
#5698 should resolve this issue and be ready for testing.  The fabric and domain names should be set as before to the network address and interface, respectively.  Additionally, the tcp and udp providers were updated to report similar names.

**Comment by shefty** [comment]
Please verify fix in master.

**Comment by frostedcmos** [comment]
Tried locally with 8af3c112bfce155eb04218bef656f58f3609ce19 - all local tests passed. Submitted automated CI to update to that revision, will provide details once CI finishes (day or so)

**Comment by frostedcmos** [comment]
Automated CI passed all tests with "ofi+sockets" as well using 8af3c11

**Comment by shefty** [comment]
Thanks!
