### ISSUE TITLE
[Question] What to do when using verbs with tagged messages?

### ISSUE THREAD

**Issue by carstenpatzke** [ofiwg/libfabric#5683]
Hello,
after testing a bit with libfabric I have to say that is really hard to find easy examples.

I currently want to develop an multi-threaded RPC like system, where a client can send small requests which are answered by a server, in between these messages large amount of memory sections may be transferred.

**This is my current understanding:**

Tagged messages seems to be perfect for this, since the client can have multiple requests running at the same time which might be answered in another order than it was requested. In my case the tag is just a messageId which is also send in the request (so the server knows what tag to set in the response).

To use tags in conjunction with verbs(and RMA) I most likely need to use `verbs;ofi_rxd` or `verbs;ofi_rxm` provider. I went with `verbs;ofi_rxm`.

**My first question** is why, when `FI_RMA` is added to `hints->caps`, I don't get any fabric info but when using the command line tool(`fi_info -p VERBS -t FI_EP_RDM -c "FI_RMA|FI_TAGGED"`) it works
``` c
fi_info* hints = fi_allocinfo();
hints->fabric_attr->prov_name = strdup("verbs");
hints->ep_attr->type = FI_EP_RDM;
hints->ep_attr->protocol = FI_PROTO_RXM;
hints->dest_addr = strdup(serverip);
hints->caps = FI_TAGGED;

// Client
fi_getinfo(EXPECTED_FI_VERSION, serverip, port, 0, hints, &fabric_info);

// Server
fi_getinfo(EXPECTED_FI_VERSION, NULL, port, FI_SOURCE, hints, &fabric_info);
```

**My second question** is about how to initialize the server and the client?
Do I need to call connect on the client side? How do I initialize the server when I cannot use fi_passive_ep?

<details>
<summary>My Code when I was experimenting with <code>sockets</code> looks like this:</summary>

**Server**
``` c
FI_OK(fi_fabric(fabric_info->fabric_attr, &fabric, NULL));
FI_OK(fi_domain(fabric, fabric_info, &domain, NULL));

fi_eq_attr eq_attr{0};
fi_cq_attr cq_attr{0};

FI_OK(fi_eq_open(fabric, &eq_attr, &event_queue, NULL));
FI_OK(fi_cq_open(domain, &cq_attr, &completion_queue, NULL));

FI_OK(fi_passive_ep(fabric, fabric_info, &passive_endpoint, NULL));
FI_OK(fi_pep_bind(passive_endpoint, &event_queue->fid, 0));
FI_OK(fi_listen(passive_endpoint));
```

**Client**
``` c
FI_OK(fi_fabric(fabric_info->fabric_attr, &fabric, NULL));
FI_OK(fi_domain(fabric, fabric_info, &domain, NULL));

fi_eq_attr eq_attr{0};
fi_cq_attr cq_attr{0};

FI_OK(fi_eq_open(fabric, &eq_attr, &event_queue, NULL));
FI_OK(fi_cq_open(domain, &cq_attr, &completion_queue, NULL));

FI_OK(fi_endpoint(domain, fabric_info, &endpoint_, NULL));
FI_OK(fi_ep_bind(endpoint, &event_queue->fid, 0));
FI_OK(fi_ep_bind(endpoint, &completion_queue->fid, FI_TRANSMIT | FI_RECV));

FI_OK(fi_connect(endpoint, fabric_info->dest_addr, nullptr, 0));

FI_OK(fi_enable(endpoint));
```
_Assuming that `FI_OK` is a macro to check if the result is == 0._

</summary>
</details>

Maybe I am completely wrong and there is an easier way to implement this.

**Comment by shefty** [comment]
You are likely not getting any results because you need to set some mr_mode bits when using verbs.  I think you need LOCAL, VIRT_ADDR, and PROV_KEY.

RXM supports reliable-datagram endpoints (RDM).  Those are connectionless and do not use connect/listen/accept.  You associate the endpoint with an address vector, insert the target address into the AV, and then just send to the target.

**Comment by carstenpatzke** [comment]
Thanks for the response.

<details>
<summary>These are my new <i>working</i> hints now:</summary>

``` c
hints->fabric_attr->prov_name = strdup("verbs");
hints->ep_attr->type = FI_EP_RDM;
hints->ep_attr->protocol = FI_PROTO_RXM;
hints->domain_attr->mr_mode = FI_LOCAL_MR | FI_MR_ALLOCATED | FI_MR_VIRT_ADDR | FI_MR_PROV_KEY;
hints->caps = FI_TAGGED | FI_RMA;
```

</details>

My client also seems to work(?) since I get `FI_EAGAIN` when I want to send data.  
But the problem is that is  **always** returning `FI_EAGAIN`.

<details>
<summary>Client code:</summary>

``` c
// Additionally for the client
hints->dest_addr = strdup(serverip);

FI_OK(fi_getinfo(EXPECTED_FI_VERSION, serverip, port, 0, hints, &fabric_info));

fi_eq_attr eq_attr{0};
fi_cq_attr cq_attr{0};

FI_OK(fi_fabric(fabric_info->fabric_attr, &fabric, NULL));
FI_OK(fi_domain(fabric, fabric_info, &domain, NULL));

FI_OK(fi_eq_open(fabric, &eq_attr, &event_queue, NULL));
FI_OK(fi_cq_open(domain, &cq_attr, &completion_queue, NULL));

fi_av_attr av_att {};
FI_OK(fi_av_open(domain, &av_att, &address_vector, NULL));

FI_OK(fi_endpoint(domain, fabric_info, &endpoint, NULL));

FI_OK(fi_ep_bind(endpoint, &event_queue->fid, 0));
FI_OK(fi_ep_bind(endpoint, &completion_queue->fid, FI_TRANSMIT | FI_RECV));
FI_OK(fi_ep_bind(endpoint, &addressVector->fid, 0));

FI_OK(fi_mr_reg(domain, &payload, sizeof(payload),
                    FI_REMOTE_READ | FI_REMOTE_WRITE | FI_SEND | FI_RECV,
                    0, 0, 0, &mr, NULL));

fi_addr_t dstAddr;
[...] fi_av_insertsvc(addressVector_, serverip, port, &dstAddr, 0, nullptr) == 1 [...]

FI_OK(fi_enable(endpoint));

// Try to send data
ssize_t err;
do {
	err = fi_send(endpoint, &payload, sizeof(payload), fi_mr_desc(mr), dstAddr, NULL);
} while(err == -FI_EAGAIN);

// This part is never reached because there is always FI_EAGAIN

```

</details>

I don't get any data on the server side.  
Do I need to insert an address into the av even when I just want to receive data?

<details>
<summary>Server code:</summary>

``` c
FI_OK(fi_getinfo(EXPECTED_FI_VERSION, NULL, port, FI_SOURCE, hints, &fabric_info));

fi_eq_attr eq_attr{0};
fi_cq_attr cq_attr{0};

FI_OK(fi_fabric(fabric_info->fabric_attr, &fabric, NULL));
FI_OK(fi_domain(fabric, fabric_info, &domain, NULL));

FI_OK(fi_eq_open(fabric, &eq_attr, &event_queue, NULL));
FI_OK(fi_cq_open(domain, &cq_attr, &completion_queue, NULL));

fi_av_attr av_att {};
FI_OK(fi_av_open(domain, &av_att, &address_vector, NULL));

FI_OK(fi_endpoint(domain, fabric_info, &endpoint, NULL));

FI_OK(fi_ep_bind(endpoint, &event_queue->fid, 0));
FI_OK(fi_ep_bind(endpoint, &completion_queue->fid, FI_TRANSMIT | FI_RECV));
FI_OK(fi_ep_bind(endpoint, &addressVector->fid, 0));

FI_OK(fi_mr_reg(domain, &payload, sizeof(payload),
                    FI_REMOTE_READ | FI_REMOTE_WRITE | FI_SEND | FI_RECV,
                    0, 0, 0, &mr, NULL));

FI_OK(fi_enable(endpoint));

// Try to receive data
ssize_t err;
do {
	err = fi_recv(endpoint, &payload, sizeof(payload), fi_mr_desc(mr), 0, NULL);
} while(err == -FI_EAGAIN);

wait_for_completion(completion_queue);

// This part is never reached

```

</details>

There is no error in the `completion_queue`.

Did I miss something?

**Comment by shefty** [comment]
RDM establishes connections underneath as part of the send operation.  When you receive EAGAIN on the send side, you should try reading the completion queue to drive progress.  The EAGAIN either means that the transmit queue is full, or the underlying connection is not yet established.

If you get EAGAIN on the receive side, that likely means that the receive side is full.  You don't want to spin in that case.  Once you get EAGAIN, you will need to wait until you receive a completion before trying to post another receive buffer.

**Comment by carstenpatzke** [comment]
Thanks for the information, the tip with reading the queue from the sending side really helped.  
Now I get a stack trace at the client and server (at the same time). Which I see this as a success! 😄 

I will further investigate this tomorrow.

**Comment by carstenpatzke** [comment]
Okay the segment fault came from a non initialized `fi_eq_err_entry` when calling `fi_eq_readerr`.
Since I reevaluated my needs for this project I switched to a connection based approach using `FI_PROTO_RDMA_CM_IB_RC`.

I also have some question about this protocol, but I will create a new issue for that.

**Comment by carstenpatzke** [comment]
I am sorry that I have to reopen this issue, but I think its better that I'll just ask here.

Since the service that I'm trying to implement should respond to requests, I somehow need to figure out where to send the response. I don't want to include the source address into the payload of the message.

So I thought it might be a good idea to simply use `fi_cq_readfrom` at the receiving queue, but unfortunately the address always returns **`FI_ADDR_NOTAVAIL`**.

This is how I enqueue the receive request: `fi_recv(endpoint, dst, size, fi_mr_desc(mr), 0, NULL)`.
The capabilities of my server are `FI_TAGGED | FI_RMA | FI_SOURCE` and `fi_info` is also called with `FI_SOURCE`.
The address vector and queues _(one for FI_RECV and one FI_SEND)_ are created and bound with default(ZERO) attributes.

**Comment by carstenpatzke** [comment]
I mean, is there a way to know about the source address without inserting it manually into the address vector? I currently also currently don't see any way to garbage collect stale/disconnected connections in the av.

The issue 1399 discussed such a mechanism but was closed.

**Comment by shefty** [comment]
The address must be in the AV to be reported.  RxM should cleanup stale connections, though the address will remain part of the AV.  To report stale addresses, we would need to define the mechanism as part of the API and add the implementation.  Even then the mechanism isn't guaranteed to work.  So, it would be of limited use.

A mechanism was defined for reporting when data is received from an unknown peer (FI_SOURCE_ERR), however, I don't see that rxm implemented this feature.  That is just a developer resource issue.

**Comment by carstenpatzke** [comment]
Hmm okay.
My client will now send a _handshake_ when a server address is added, the server will send an empty response to acknowledge that the address was successfully added to the av.
The _handshake_ contains the client's address that was resolved with 
`fi_getname(&(endpoint->fid),...)`.
It this a legitimate way to solve this?

**Comment by shefty** [comment]
Yes, you should be able to use fi_getname, pass that address over, and insert it into the peer's AV.

**Comment by carstenpatzke** [comment]
After implementing all the base features am now trying to handle erroneous states.
I am using the `op_context` extensively to determinant what request is currently handled.

<details>
<summary>
But when forcefully try to write RDMA data with a wrong key, my next <code>fi_cq_readerr</code> does not yield any <code>op_context</code> back.
</summary>

``` c
errEntry.op_context: 0
errEntry.flags: 0
errEntry.len: 0
errEntry.buf: 0
errEntry.data: 0
errEntry.tag: 0
errEntry.olen: 0
errEntry.err: 258
errEntry.prov_errno: -258
errEntry.err_data: 0
errEntry.err_data_size: 0
```

</details>

I also do get these warnings:
```
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1236<warn> fi_cq_readerr: err: Input/output error (5), prov_err: remote access error (10)
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1282<warn> Invalid state!
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1285<warn> msg cq error info: remote access error
```
Which lets me to believe that RMA errors are not handled yet.

Is there some way to add `case RXM_RMA:` to this switch case?

https://github.com/ofiwg/libfabric/blob/master/prov/rxm/src/rxm_cq.c#L1238

**Comment by shefty** [comment]
Are you running with the tip of master?

Based on your output, I tend to agree that we need to expand the switch handling.  I'm not that familiar with this part of the code, but I'll take a look at it.

**Comment by carstenpatzke** [comment]
I've been using https://github.com/ofiwg/libfabric/commit/3e971a6527cb53674b9be166e536c897f758fe06 (1.9.1) but https://github.com/ofiwg/libfabric/commit/8ffbf69fb71aabd8a3348c115b3b4e1b2d1985e0 (master) results in the same behavior.

It would be really great if you could fix this :)

**Comment by shefty** [comment]
Can you open a separate issue to track that bug?  I think this specific issue has been resolved.

**Comment by carstenpatzke** [comment]
I've opened a new issue for the said problem.
I also have some questions about the `sockets` provider which I want to use in integration tests on machines without verbs capabilities.

Since I don't want to clutter other issues with this, would you mind if I ask them here?
Otherwise you can close this issue and I will create a new one with my `sockets` question probably tomorrow.

**Comment by shefty** [comment]
If you just have questions, the best option is to post an email to the libfabrics-users or ofiwg mailing lists.  More people monitor those lists than the github issues.
