### ISSUE TITLE
commit 6620146a440b715fd85d0f827f5616d9f520bc04 affect some benchmark performance significantly.

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#5697]
Our nightly test has shown the following benchmark test's performance drop significantly today:

fi_rdm_pingpong -v -p efa,
fi_rdm_tagged_pingpong -v -p efa,

Both does data verification. 

The performance degradation can be attributed to the following commit:

"commit 6620146a440b715fd85d0f827f5616d9f520bc04
fabtests/shared.c: Changed Memory Registration for larger buffers."

The following are numbers with and without this commits:

with:

bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      10k     1.2m        0.40s      3.20      20.00       0.05
256     10k     4.8m        0.40s     12.65      20.23       0.05
1k      10k     19m         0.46s     44.89      22.81       0.04
4k      10k     78m         0.65s    126.51      32.38       0.03
64k     1k      125m        0.51s    258.98     253.06       0.00
1m      100     200m        0.64s    329.76    3179.83       0.00

without:

bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      10k     1.2m        0.40s      3.18      20.11       0.05
256     10k     4.8m        0.41s     12.61      20.30       0.05
1k      10k     19m         0.45s     45.54      22.49       0.04
4k      10k     78m         0.60s    135.90      30.14       0.03
64k     1k      125m        0.43s    302.58     216.59       0.00
1m      100     200m        0.52s    405.58    2585.38       0.00

As can be seen, latency for 64K and 1M message increased by 20%. The commit message indicate this change should only affect multi node test. I wonder whether this behavior is expected or not?

**Comment by shefty** [comment]
@AMcKinley15 

This is unexpected.  The commit referenced removed an alignment of the tx_buf, in addition to increasing the size of the buffers.  Can you see which of these changes has the impact on your performance?

The change is only needed for the multi-node test.  We may need to set some option and only adjust the allocations if that is set.

**Comment by wzamazon** [comment]
It is the following one-line change caused the performance degradation:


@@ -379,7 +379,7 @@ static int ft_alloc_ctx_array(struct ft_context **mr_array, char ***mr_bufs,
        for (i = 0; i < opts.window_size; i++) {
                context = &(*mr_array)[i];
                if (!(opts.options & FT_OPT_ALLOC_MULT_MR)) {
-                       context->buf = default_buf;
+                       context->buf = default_buf + mr_size * i;
                        continue;
                }

**Comment by shefty** [comment]
Does this change result in each transfer referencing a different data buffer?

**Comment by aingerson** [comment]
I don't think this change should affect which buffer it's using. This change shouldn't even be necessary in the first place...
In the case of !(opts.options & FT_OPT_ALLOC_MULT_MR) the mr_size gets set to 0 so this should always evaluate the same way as before. fi_rdm_tagged_pingpong doesn't use FT_OPT_ALLOC_MULT_MR and I'm pretty sure just passes in tx_buf/rx_buf to it's send/recv calls so it never even uses the ctx array

**Comment by wzamazon** [comment]
Yes you are right. In fact, I verified that mr_size is 0 here, so 
```
context->buf = default_buf;
```
should be equivalent to
```
context->buf = default_buf + mr_size * i;
```

So, I do not understand how this change could affect performance

**Comment by AMcKinley15** [comment]
I ran through all of the providers and did not see significant regressions anywhere else. I'm going to try rolling back the whole patch to see if it appears then.

**Comment by shefty** [comment]
@wzamazon - Can you rerun your performance tests and confirm that the performance drop is repeatable?

**Comment by wzamazon** [comment]
@shefty @AMcKinley15  
I rerun the test with tcp provider and can still see the performance drop.
I used the following command to run test:
on server:
```
fi_rdm_tagged_pingpong -l -v -p tcp -s server_ip -S 1048576 -w 0 -I 1000
```
on client
```
fi_rdm_tagged_pingpong -l -v -p 'tcp;ofi_rxm' -S 1048576 -w 0 -I 1000 -s client_ip server_ip
```
The following output is what I got from master branch
```
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
1m      1k      1.9g        6.75s    310.88    3372.92       0.00
```

I then apply the following one line change to the code:
```
--- a/fabtests/common/shared.c
+++ b/fabtests/common/shared.c
@@ -379,7 +379,7 @@ static int ft_alloc_ctx_array(struct ft_context **mr_array, char ***mr_bufs,
        for (i = 0; i < opts.window_size; i++) {
                context = &(*mr_array)[i];
                if (!(opts.options & FT_OPT_ALLOC_MULT_MR)) {
-                       context->buf = default_buf + mr_size * i;
+                       context->buf = default_buf;
                        continue;
                }
                (*mr_bufs)[i] = calloc(1, mr_size);
```
and get the following output from the same command:

```
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
1m      1k      1.9g        5.34s    392.64    2670.59       0.00
```

**Comment by shefty** [comment]
And mr_size is 0?  The change above looks like it uses a different buffer per transfer, rather than always using a single buffer.  If that's the case, I could understand some drop from caching, but these are large transfers.

**Comment by wzamazon** [comment]
I did some test, and it looks like ```context->buf``` was not even used in the ```fi_rdm_tagged_pingpong -l -v``` test. In fact, I can set ```context->buff``` to ```NULL``` and the test would still work.

It looks to me almost like an alignment issue. The difference between 
```context->buf = default_buf```
and 
```context->buf = default_buf + mr_size * i```
is that the latter added a few instructions which somehow changed memory alignment, and caused the performance difference.

**Comment by shefty** [comment]
One of the changes the commit made was to remove memory alignment from how tx_buf was set.  These lines were removed.

```
tx_buf = (char *) buf + MAX(rx_size, FT_MAX_CTRL_MSG);	
	tx_buf = (void *) (((uintptr_t) tx_buf + alignment - 1) &		if (opts.options & FT_OPT_ALLOC_MULT_MR)
			   ~(alignment - 1));
```

**Comment by shefty** [comment]
Well, that copy-paste didn't work, but it at least shows where the problem may be in the original patch.

**Comment by aingerson** [comment]
That well formatted line looks like it needs to be back in there. But @wzamazon you said it was happening without alignment being set right? Could you also try running without data verification and see if you get the same regression?

**Comment by wzamazon** [comment]
add back the following line
```
tx_buf = (void *) (((uintptr_t) tx_buf + alignment - 1) & ~(alignment - 1));
```
Did not change the performance.

Also, running without data verification does NOT get same regression.

**Comment by shefty** [comment]
I think we're likely looking at the wrong location in the code for where the problem is.  Honestly, I'm not concerned about performance regressions when data verification is turned on, because I'm not even concerned about performance in that case.

**Comment by wzamazon** [comment]
works for me. I will close then
