### ISSUE TITLE
prov/sockets fi_cancel() doesn't work for send operations

### ISSUE THREAD

**Issue by yulujia** [ofiwg/libfabric#5701]
For send operations fi_cancel() returns FI_ENOENT, no completion event is for it is seen from the completion queue. Upon investigation fi_cancel() executed this branch of the switch statement:
```
https://github.com/ofiwg/libfabric/blob/master/prov/sockets/src/sock_ep.c#L509
```

**Comment by shefty** [comment]
The sockets provider is basically deprecated at this point.  fi_cancel is a best effort operation, with no guarantees that a specific operation is actually canceled.  The only requirement is that the operation complete (successfully or otherwise) eventually.  The operation is permitted to go through the normal control path.  Are you seeing send operations remain outstanding and not complete?

**Comment by yulujia** [comment]
> Are you seeing send operations remain outstanding and not complete?

yes. my test sends an RPC to an exited rank, waits for  it to time out, then calls fi_cancel(). fi_cancel() returns FI_ENOENT. The test hangs overnight because the sender didn't see the completion event.

**Comment by shefty** [comment]
Can you run with the tcp provider and see if you get the same results?  If the peer exited, the operation should complete in error, and not require the app to call cancel.

**Comment by soumagne** [comment]
@shefty I am looking at that issue as well. Yes I really think there's an issue with both sockets and tcp providers. Assume you do something like that:
```C
fi_tsend(..) /* send message to target that is alive */
<wait for completion>
[...]
<kill target>
[...]
fi_tsend(...)
<wait for completion>
```
In that case, both `fi_tsend()` operations are successfully posted, however the second `fi_tsend()` operation in the case of sockets provider will raise an `FI_EIO` error in the CQ and in the case of tcp provider, no error at all and it will even complete successfully...
I also believe that in that case, the second `fi_tsend()` operation should return an error at the time it gets posted and not later on? Do you have a test that covers that? What is the correct behavior we should expect?

**Comment by shefty** [comment]
If the socket send call fails, I would expect tcp to report a failure by writing an error to the CQ.  (I don't know if it does this.)  Although a sockets based provider might be able to detect the error at post time, that won't be true of all providers, and also depends on the socket-based provider implementation.  For example, I think the sockets provider will queue the operation to an internal thread, which will perform the actual send call.

We don't have a test for this.

**Comment by soumagne** [comment]
OK yes I can confirm that the rxm;tcp provider does not do that. The socket provider seems to do it though with FI_EIO, I will assume that this is the expected behavior.
