### ISSUE TITLE
err: Input/output error (5) prov_errno: Unknown error -11 (-11)

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#5716]
Hi there, 
I am encountering following error:
```
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -11 (-11) prov/efa/src/rxr/rxr.h:1343
```
After debugging through the code, I only know it is triggered by `fi_cq_read` function.
here is my waiting function, I am sure when I invoke the function the `cq` is a valide pointer. 

```cpp
void wait_cq(fid_cq *cq, int count) {
  struct fi_cq_err_entry entry;
  int ret, completed = 0;
  printf("wait_cq cq addr %p\n", cq);
  while (completed < count) {
    // ret = fi_cq_readfrom(cq, &entry, 1, &from);
    // ret = fi_cq_sread(cq, &entry, 1, NULL, timeout);
    ret = fi_cq_read(cq, &entry, 1);
    if (ret == -FI_EAGAIN)
      continue;

    if (ret == -FI_EAVAIL) {
      ret = fi_cq_readerr(cq, &entry, 1);
      CHK_ERR("fi_cq_readerr", (ret != 1), ret);

      printf("Completion with error: %d\n", entry.err);
      // if (entry.err == FI_EADDRNOTAVAIL)
      // 	get_peer_addr(entry.err_data);
    }

    CHK_ERR("fi_cq_read", (ret < 0), ret);
    completed++;
  }
};
```

Any suggestions for debugging? I have seen this thread https://github.com/aws/aws-ofi-nccl/issues/20 
but I am using the newest `fabric-1.9.0` and `efa 1.6.0`.

I am using endpoint with multi-threading environment, I am using one thread for launching `fi_send/fi_recv`, another thread for completion check `fi_cq_read`. I read EFA, document, where claims `RDM` endpoint supports `FI_THREAD_SAFE`. so I thought it should be ok in this usage.

One wired thing of the `fi_cq_read` is that the speed is insanely fast for those non-failure function calls. E.g. only takes `0.3 ms` for checking 40 `fi_send` job, each job sends buffere size 5 MB.

**Comment by wzamazon** [comment]
Hi @zarzen , would you please run you program with environmental variable FI_LOG_LEVEL set to debug? this will give us more information

**Comment by zarzen** [comment]
Hi @wzamazon 

I have cli-server structure, where server send buf to client, here are logs for both
```
server:
libfabric:20828:efa:cq:rxr_cq_handle_pkt_recv_completion():1434<warn> invalid control pkt type 0
libfabric:20828:efa:cq:rxr_cq_handle_cq_error():321<warn> fi_cq_read: Input/output error
libfabric:20828:efa:eq:rxr_eq_write_error():1323<warn> Writing error Input/output error to EQ.
libfabric:20828:efa:eq:rxr_eq_write_error():1339<warn> Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -5 (-5)
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -5 (-5) prov/efa/src/rxr/rxr.h:1343

client:
libfabric:20881:shm:ep_ctrl:smr_rma_fast():84<warn> CMA write error
libfabric:20881:efa:cq:rxr_cq_handle_cq_error():329<warn> fi_cq_readerr: Resource temporarily unavailable
libfabric:20881:efa:eq:rxr_eq_write_error():1323<warn> Writing error Input/output error to EQ.
libfabric:20881:efa:eq:rxr_eq_write_error():1339<warn> Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -11 (-11)
Unable to write to EQ: Missing or unavailable event queue. err: Input/output error (5) prov_errno: Unknown error -11 (-11) prov/efa/src/rxr/rxr.h:1343
```

full log is available at here: https://gist.github.com/zarzen/4a4037d503b502fa97f80ed5bfe51644

**Comment by zarzen** [comment]
Hi @wzamazon 
I actually found the problem is not due `fi_cq_read`, but while calling `fi_send/fi_recv`, I passed a buffer pointer stored which is computed based on `offset`, as following:
``` cpp
char *large_buf = new char[1000];
std::vector<char*> split();
for (int i = 0; i < 10; ++i) {
  char * new_start_p = large_buf + i * 100;
  split.push_back(new_start_p);
}

...later in somewhere:
for (int i = 0; i < 10; ++i) {
   fi_send(ep, split[i], 100, ...);
}
// for some reason, char pointers inside `vector` split is not available...
// when I try to printf the value of the split[i], I will get segfault.
```
I think it is more like a C++ language question.

**Comment by rajachan** [comment]
Thanks for providing the logs, @zarzen. Two observations:

```
libfabric:20828:efa:cq:rxr_cq_handle_pkt_recv_completion():1434<warn> invalid control pkt type 0
```
This makes me think your client and server are running different versions of libfabric (with possibly incompatible EFA protocol). Can you make sure you have the same version running across your instances?

```
libfabric:20881:shm:ep_ctrl:smr_rma_fast():84<warn> CMA write error
```
This could be a manifestation of https://github.com/ofiwg/libfabric/issues/5656. What AMI are you running with?  If you are running with Ubuntu, please follow the guidelines here to disable ptrace protection (which is necessary for the use of CMA, a kernel capability libfabric uses in the shared-memory provider to optimize intra-instance communication):
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-ptrace

**Comment by zarzen** [comment]
> Thanks for providing the logs, @zarzen. Two observations:
> 
> ```
> libfabric:20828:efa:cq:rxr_cq_handle_pkt_recv_completion():1434<warn> invalid control pkt type 0
> ```
> 
> This makes me think your client and server are running different versions of libfabric (with possibly incompatible EFA protocol). Can you make sure you have the same version running across your instances?
> 
> ```
> libfabric:20881:shm:ep_ctrl:smr_rma_fast():84<warn> CMA write error
> ```
> 
> This could be a manifestation of #5656. What AMI are you running with? If you are running with Ubuntu, please follow the guidelines here to disable ptrace protection (which is necessary for the use of CMA, a kernel capability libfabric uses in the shared-memory provider to optimize intra-instance communication):
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-ptrace

Hi @rajachan  I have disabled `ptrace` protection by overwrite `/etc/sysctl.d/10-ptrace.conf`. 
I am running both server and client on same machine, so they should use same libfabric lib. 
This morning I found one issue in my code: 
for the client side, after `fi_send` request to server, I didn't put a `wait_cq` function for completion check, and start `fi_recv` for responses from the server immediately. Once I added a `wait_cq(txcq, 1)` right after, the "err: Input/output error (5)", seems to disappear. 
But I have separate the `txcq` and `rxcq`, later `wait_cq(rxcq, counter)` should not be bothered with `txcq` right?

**Comment by zhngaj** [comment]
Hi @zarzen 
Regarding the CMA issue
```
libfabric:20881:shm:ep_ctrl:smr_rma_fast():84<warn> CMA write error
```
In the failure case, the typical return value could be -1 (operation not permitted), printing out `CMA write error` therefore. But you already disabled ptrace protection. 
I'm wondering what the return value is in your case?
    
```c
ret = CMA calls
if (ret < 0) {
        FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
                "CMA write error\n");
        ret = -errno;
} else {
        FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
                "unable to process tx completion\n");
        ret = -FI_EIO;
}

```

**Comment by zarzen** [comment]
Hi @zhngaj 
I didn't invoke CMA call explicitly, could you give me some concrete calls?
