### ISSUE TITLE
Supporting PMIx instant on

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#5719]
In past ofiwg calls, we have talked about possible `fi_cm()` (or other) API enhancements necessary to support [PMIx](https://pmix.org/) instant-on like use-cases. Creating an issue here to summarize the discussion we have had so far and to capture some offline discussions.

**Comment by wesbland** [comment]
Maybe I can help out by bringing up the problem we were specifically running into. In current MPICH, we support a version of “instant on” where a provider gets the address information out of band (doesn’t matter how, but it could be PMI, fabric manager, etc.) and constructs its own address vector which is published as a well-known, named AV. Then we try to open it via the `name` attribute on the AV via `fi_av_open`.

https://github.com/pmodels/mpich/blob/a854ba5d3bbac9e30ea115b050f7826f6eb6aa74/src/mpid/ch4/netmod/ofi/ofi_init.c#L1324-L1347
 
While this works fine in the single nic scenario, there’s two problems with it in the multi-nic scenario:
 
1. Given the lack of specification on this issue, it’s hard to guarantee that all of the nic addresses are present in the AV, and we have no way of knowing how many nics are assigned to a given process. This is different from right now where we are guaranteed that AV index 0 will map to MPI rank 0. I'm not sure if this this is something that's guaranteed only by a few providers or if this is part of the specification. We might want to do something like sharing the nics amongst processes so it could be a mapping like AV indices 0 and 1 are both mapped to MPI ranks 0 and 1.
 
2. At least with current providers, when trying to open a named AV more than once in a single OS process / MPI rank, OFI crashes. From the specification, there is no language guaranteeing that this will work, so it’s not unexpected. However, if we were to expand the “named AV” solution to work for multiple NICs where each endpoint would open it’s own copy of the AV (to avoid creating lots of copies of the same AV everywhere), this would need to get resolved somehow.

**Comment by shefty** [comment]
AVs are designed to map to HW specific resources.  Trying to share them between OFI domains (i.e. NICs), is not intended.

**Comment by wesbland** [comment]
> AVs are designed to map to HW specific resources. Trying to share them between OFI domains (i.e. NICs), is not intended.

Is that not the intent of `FI_SHARED_AV`? Obviously I don't claim to be an OFI expert here so I'm happy to get better guidance on how this should work.

Either way, I think that's only a part of the issues I was raising above.

**Comment by shefty** [comment]
The intent of a shared AV is that multiple processes using the same NIC can share the HW resources.  AVs are created off of the domains.

**Comment by rajachan** [comment]
Sean beat me to it (twice) and helped trim my reply, so I'll just add named AVs would help minimizing state (and possible provider-specific look up costs) for processes talking to a single domain within a node but can not be extrapolated to the instant-on use case or to multiple NICs in that manner, at least in the way we have been talking about it.

Summarizing the last ofiwg discussion on this topic, we need one of two things to realize the instant-on use case — an out-of-band device management API (or a management type class for existing fabric/domain APIs) which libfabric currently does not have, or in the short term, a fi_cm() API that will allow middleware to get a set of reserved addresses from providers.  
Process management frameworks and job schedulers can use this API to preallocate addresses based on the number of slots they will have on the system. MPI libraries and other middleware interafacing with PMI can get/allocate an address for a rank from PMI for node and device on which they get scheduled on and assign it to their libfabric endpoint (with a fi_setname()). I started teasing apart a short-term proposal for this special getname, but focused on getting out the 1.10 changes for EFA now.

There are provider-specific implications for how these reserved addresses are maintained, particularly around the lifecycle of the reserved addresses as it relates to the different entities (OOB management API user vs actual data path lifecycle from the app). The costs of the reservation could also be different for different providers, a local operation for one and a query to a central daemon for another. It would be best to leave this up to the provider as an implementation detail.

The other issue I see with named AVs even without the multi-nic piece is the "well-known" name part. Unless we define canonical names for special AVs, there would be no easy way for middleware developers to programmatically discover and open such an AV. But that could be an option?

**Comment by rhc54** [comment]
@rhc54 Just so I can see what is going on

**Comment by wesbland** [comment]
Ok, this is fine. I'm really not trying to get hung up on the shared address vector. The ability to get all of the addresses somehow and map multiple nics into a single OS process is really what I'm trying to get out of this.

**Comment by shefty** [comment]
To support instant on, I believe we have the following requirements:
```
1. Control process must reserve a set of addresses
1a. Optionally, the resources must also be reserved
2. The addresses must be communicated to the compute processes
3. Compute processes must be able to allocate the desired resources and addresses
4. Providers must be able to release addresses/resources for re-use
```
Step 2 is outside the scope of OFI.  There is an existing API (fi_setname) which is usable for selecting a specific address for step 3.  If specific resources are reserved at step 1a, we need to analyze whether this is possible through the existing fi_getinfo / fi_domain / fi_endpoint APIs, or if small adjustments are needed to help guide the provider.  There is no current solution for step 1.

Step 1 is the device management API that Raghu is referring to.

**Comment by sayantansur** [comment]
> The other issue I see with named AVs even without the multi-nic piece is the "well-known" name part. Unless we define canonical names for special AVs, there would be no easy way for middleware developers to programmatically discover and open such an AV. But that could be an option?

I agree. The named AVs were a hack to get instant-on going in previous versions of OFI/MPICH. I think a fresh approach is desired here.

**Comment by shefty** [comment]
The control process that is providing the addresses needed by each app could easily convey the AV name to use as well.  Well-known names shouldn't be needed.

**Comment by shefty** [comment]
[OFI-InstantOnOverview.pptx](https://github.com/ofiwg/libfabric/files/4920117/OFI-InstantOnOverview.pptx)

**Comment by rajachan** [comment]
This proposal came up when discussing https://github.com/open-mpi/ompi/pull/8359 and I realized the API we presented in a past OFIWG call was not captured here:

```
#include <rdma/fi_mgmt.h>
int fi_mgmt_fabric(struct fi_fabric_attr *attr, struct fid_fabric **fabric, void *context); 
int fi_close(struct fid *fabric); 

int fi__mgmt_domain(struct fid_fabric *fabric, struct fi_info *info, struct fid_domain **domain, void *context);
int fi_close(struct fid *domain); 

int fi_mgmt_endpoint(struct fid_domain *domain, struct fi_info *info, struct fid_ep **ep, void *context);
int fi_close(struct fid *ep);

int fi_get_reserved_names(fid_t fid, void **addr, size_t *addrlen, size_t count);
int fi_release_reserved_names(fid_t fid, void **addr, size_t addrlen, size_t count);
```
