### ISSUE TITLE
EFA, first 'fi_recv' task cost over 400ms to complete

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#5724]
Hi there,
I have programmed several libfabric programs using EFA as the provider. but I am encountering really bad performance in terms of bandwidth. 
My setup: 
* c5n.18xlarge instance
* AMI: Deep Learning AMI (Amazon Linux) Version 27.0 (ami-0e2a8509db267f072)
* EFA installed using [aws-efa-installer-latest](https://s3-us-west-2.amazonaws.com/aws-efa-installer/aws-efa-installer-latest.tar.gz).

## my application idea:
* server: send data to the client, 200MB, each `fi_send` operation takes care of 2MB data
* client: recv data from server, 200MB, each `fi_recv` takes 2MB data buffer
* both client and server running on local 127.0.0.1, they will first exchange EFA address through socket

## Issue: 
* at the server side the sending bandwidth achieves 50 Gbps, if I repeat tests more than 3 times.
* at the client-side, the receiving bandwidth only 2.5Gbps. No matter how many times I repeated. 
  * After breaking down the time cost of each `fi_recv` at the client-side, I notice that for first `fi_recv` task to complete takes around 470 ms. 

## code
I have uploaded the implementation to here https://github.com/zarzen/efa-bad-practice
### specifically
* https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_serv.cpp
* https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_cli.cpp
### instructions to run
* compile with cmake: `mkdir build && cd build && cmake .. && make`
* run server: `./nothd_serv 127.0.0.1 8888 1`
* run client: `./nothd_cli 127.0.0.1 8888 1`

It would be great if someone could point out some wrong usage in my program, Thanks!

**Comment by wckzhang** [comment]
I've been able to reproduce this issue and am looking into it.

**Comment by wckzhang** [comment]
Due to the way that EFA does not progress long messages until the progress engine is called (During cq read), the way your tests are written cause the numbers to be lower than expected. I rewrote your tests and instead of send 100 times , cq read 100 times and recv 100 times, cq read 100 times, I call send 10 times and cq read 10 times, 10 times total (Same thing for recv). These significantly boost the BW numbers you calculated on both send and recv side. Can you let me know if these changes work for you?

server code
```
  for (int i = 0; i < total_size / batch_p_size; ++i) {
    char* _buf_s = p_buf + i * batch_p_size;
    fi_send(efa->ep, _buf_s, batch_p_size, NULL, efa->peer_addr, NULL);
    if (i+1 % 10 == 0) {
        wait_cq(efa->txcq, 10);
    }
  }
```

client code
```
  for (int i = 0; i < total_size/batch_p_size; ++i) {
    char* _buf_s = p_buf + i * batch_p_size;
    fi_recv(efa->ep, _buf_s, batch_p_size, NULL, 0, NULL);
    if (i+1 % 10 == 0) {
        wait_cq(efa->rxcq, 10);
    }
  }
```

**Comment by zarzen** [comment]
> if (i+1 % 10 == 0) {
>         wait_cq(efa->rxcq, 10);
>     }

Hi @wckzhang Thanks for your responsiveness, 
I have changed as you said, but the first receive job still takes over 400ms. Thus the bandwidth still as low as 2.5Gbps.
Though I modified a little, added parenthesis of i+1
server
```
  auto s = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < total_size / batch_p_size; ++i) {
    char* _buf_s = p_buf + i * batch_p_size;
    fi_send(efa->ep, _buf_s, batch_p_size, NULL, efa->peer_addr, NULL);
    if ((i+1) % 10 == 0) {
        wait_cq(efa->txcq, 10);
    }
  }
```

client:
```
  for (int i = 0; i < total_size/batch_p_size; ++i) {
    // char* _buf_s = p_buf + i * batch_p_size;
    // fi_recv(efa->ep, _buf_s, batch_p_size, NULL, 0, NULL);
    fi_recv(efa->ep, p_buf, batch_p_size, NULL, 0, NULL);
    if ((i+1) % 10 == 0) {
        wait_cq(efa->rxcq, 10);
    }
  }
```

**Comment by zarzen** [comment]
BTW, how long does EFA consider it as long message?

**Comment by zarzen** [comment]
In general I would like to know how to avoid such "straggler" Thanks!

**Comment by zarzen** [comment]
> > if (i+1 % 10 == 0) {
> > wait_cq(efa->rxcq, 10);
> > }
> 
> Hi @wckzhang Thanks for your responsiveness,
> I have changed as you said, but the first receive job still takes over 400ms. Thus the bandwidth still as low as 2.5Gbps.
> Though I modified a little, added parenthesis of i+1
> server
> 
> ```
>   auto s = std::chrono::high_resolution_clock::now();
>   for (int i = 0; i < total_size / batch_p_size; ++i) {
>     char* _buf_s = p_buf + i * batch_p_size;
>     fi_send(efa->ep, _buf_s, batch_p_size, NULL, efa->peer_addr, NULL);
>     if ((i+1) % 10 == 0) {
>         wait_cq(efa->txcq, 10);
>     }
>   }
> ```
> 
> client:
> 
> ```
>   for (int i = 0; i < total_size/batch_p_size; ++i) {
>     // char* _buf_s = p_buf + i * batch_p_size;
>     // fi_recv(efa->ep, _buf_s, batch_p_size, NULL, 0, NULL);
>     fi_recv(efa->ep, p_buf, batch_p_size, NULL, 0, NULL);
>     if ((i+1) % 10 == 0) {
>         wait_cq(efa->rxcq, 10);
>     }
>   }
> ```

I have pushed code: https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_serv.cpp

**Comment by zarzen** [comment]
It is very wired, I have further added a pingpong message before I initialized 100 times `fi_recv` operation, but still the first job of initialized `fi_recv` cost over 450ms. 

code location:
https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_cli.cpp#L65

**Comment by zarzen** [comment]
Hi @wckzhang I found the issue is due to the `ft_fill_buff` function takes ~450ms to complete, thus it delays the first `fi_send` for over 400 ms. sorry for the bothering.

**Comment by wckzhang** [comment]
Were you able to figure out "Thus the bandwidth still as low as 2.5Gbps."? On my tests after my changes, my bandwidth on the recv side was never that low:

```
[ec2-user@ip-172-31-12-208 build]$ FI_EFA_ENABLE_SHM_TRANSFER=1 ./nothd_cli 127.0.0.1 8888 1
Using OFI device: EFA-fe80::ae:3bff:fea7:3859
Cli-efa-ep rxcq : 0x2103930
Local ep addresses: 
fi_addr_efa://[fe80::ae:3bff:fea7:3859]:1
Get remote EFA address 
fi_addr_efa://[fe80::ae:3bff:fea7:3859]:0
verified inserted: fi_addr_efa://[fe80::ae:3bff:fea7:3859]:0
0 :Recv bw: 722.174 Gbps
Dur 2.32315 ms 
1 :Recv bw: 286398 Gbps
Dur 0.005858 ms 
2 :Recv bw: 287232 Gbps
Dur 0.005841 ms 
3 :Recv bw: 309200 Gbps
Dur 0.005426 ms 
4 :Recv bw: 295426 Gbps
Dur 0.005679 ms 
5 :Recv bw: 315598 Gbps
Dur 0.005316 ms 
6 :Recv bw: 308745 Gbps
Dur 0.005434 ms 
7 :Recv bw: 307331 Gbps
Dur 0.005459 ms 
8 :Recv bw: 320115 Gbps
Dur 0.005241 ms 
9 :Recv bw: 325077 Gbps
Dur 0.005161 ms 
```

**Comment by rwespetal** [comment]
> BTW, how long does EFA consider it as long message?

8928 is the EFA MTU. The libfabric provider uses some of that MTU for protocol headers so as a general rule of thumb you can consider messages over 8k to be long messages.
