### ISSUE TITLE
Unable to run verbs over RoCE

### ISSUE THREAD

**Issue by vschhabra** [ofiwg/libfabric#5728]
Unable to run ibv_rc_pingpong over RoCE. Same test works for IB.

We are seeing sends over the fabric timing out.

**Comment by mj-harvey** [comment]
That's going to be something wrong with the basic RoCE setup. Try following Mellanox's RoCE debug processes
https://community.mellanox.com/s/article/RoCE-Debug-Flow-for-Linux

**Comment by vschhabra** [comment]
Was a config issue.
