### ISSUE TITLE
EFA, multi-threading performance degrades from 50 Gbps to 30 Gbps

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#5733]
Hi there,
Recently I have been able to achieve 50Gbps bandwidth with a single EFA-RDM-endpoint in one process(where I launch `fi_send/fi_recv` 100 times with 2MB buffer for each operation then wait for all jobs to complete. the code is at here: https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_serv.cpp, and https://github.com/zarzen/efa-bad-practice/blob/master/demo_nothd_cli.cpp)

After that, I am trying to move the `fi_send/fi_recv` operations into a thread, so my main-thread can do something else, then waiting for job completions. Concretely:
* server
  * has a worker thread, communicate with main-thread through a `task_queue`, where main thread put `send/recv` tasks. Tasks include buffer pointers.
  * worker thread only launches `fi_send/fi_recv`
  * main-thread will wait for all launched job to complete than compute the bandwidth

* client
  * has a worker thread, thread get a `task_queue` for main-thread to put tasks, tasks include buffer pointers.
  * worker thread only launches `fi_send/fi_recv`
  * main-thread will wait for all launched job to complete than compute the bandwidth

EFA-RDM-endpoint is created inside the worker thread. The codes are at here [msg-server](https://github.com/zarzen/efa-bad-practice/blob/master/demo_msg_serv.cpp) and [msg-client](https://github.com/zarzen/efa-bad-practice/blob/master/demo_msg_cli.cpp). 
In this way, I got the computed bandwidth around 30 Gbps. 

This time I am sure both server and client started their `fi_send/fi_recv` at almost the same time. And all  `fi_send/fi_recv` launch pretty quickly. 

One thing I found based on the timing-log of `wait_cq`, wait for jobs to complete, is that there are some stragglers slows down the process. (later I did some changes to improve the performance)

* server-side log
```
got new tasks 1584295628579248639
async tasks complete 1584295628579254203
1 job cost : 0.027099 ms
Recv request msg: <fake-request-for-parameters>
got new tasks 1584295628579288298
async tasks complete 1584295628579383515
1 job cost : 14.8437 ms
2 job cost : 5.6e-05 ms
3 job cost : 5.9e-05 ms
4 job cost : 5.9e-05 ms
5 job cost : 5.7e-05 ms
6 job cost : 7.1e-05 ms
7 job cost : 5.6e-05 ms
8 job cost : 5.5e-05 ms
9 job cost : 5.6e-05 ms
10 job cost : 5.6e-05 ms
11 job cost : 5.6e-05 ms
12 job cost : 5.6e-05 ms
13 job cost : 5.5e-05 ms
14 job cost : 5.6e-05 ms
15 job cost : 5.5e-05 ms
16 job cost : 5.6e-05 ms
17 job cost : 5.5e-05 ms
18 job cost : 5.6e-05 ms
19 job cost : 0.05253 ms
20 job cost : 5.6e-05 ms
21 job cost : 5.6e-05 ms
22 job cost : 5.6e-05 ms
23 job cost : 5.6e-05 ms
24 job cost : 5.9e-05 ms
25 job cost : 5.6e-05 ms
26 job cost : 5.6e-05 ms
27 job cost : 5.6e-05 ms
28 job cost : 5.5e-05 ms
29 job cost : 5.6e-05 ms
30 job cost : 5.7e-05 ms
31 job cost : 5.6e-05 ms
32 job cost : 7.2e-05 ms
33 job cost : 35.1484 ms
```

* client-side log
```
got new tasks 1584295628579265217
async tasks complete 1584295628579274049
1 job cost : 0.013898 ms
start new tasks 1584295628579284719
got new tasks 1584295628579296703after put tasks 
1584295628579296939
async tasks complete 1584295628579310570
1 job cost : 14.8294 ms
2 job cost : 0.00037 ms
3 job cost : 5.6e-05 ms
4 job cost : 5.5e-05 ms
5 job cost : 5.6e-05 ms
6 job cost : 7.3e-05 ms
7 job cost : 5.5e-05 ms
8 job cost : 5.6e-05 ms
9 job cost : 5.6e-05 ms
10 job cost : 5.6e-05 ms
11 job cost : 5.7e-05 ms
12 job cost : 5.7e-05 ms
13 job cost : 5.5e-05 ms
14 job cost : 5.7e-05 ms
15 job cost : 5.6e-05 ms
16 job cost : 5.6e-05 ms
17 job cost : 5.6e-05 ms
18 job cost : 5.5e-05 ms
19 job cost : 19.0518 ms
20 job cost : 0.00028 ms
21 job cost : 0.000123 ms
22 job cost : 0.000131 ms
23 job cost : 7e-05 ms
24 job cost : 0.000122 ms
25 job cost : 5.6e-05 ms
26 job cost : 0.000127 ms
27 job cost : 5.6e-05 ms
28 job cost : 0.000125 ms
29 job cost : 0.000129 ms
30 job cost : 0.000126 ms
31 job cost : 5.8e-05 ms
32 job cost : 0.000124 ms
33 job cost : 16.0958 ms
```

### 1. move the `wait_cq`, wait for job completion, into the worker thread
Instead of waiting for job completion in *main-thread*, I moved `wait_cq` function call into worker thread. While I exposed a *counter pointer* to the worker thread, so the main-thread get the job completion status through the counter. 

This modification results in 3-6 Gbps performance gain. 

Implementations are at `try-impr` branch: [demo_msg_serv.cpp](https://github.com/zarzen/efa-bad-practice/blob/try-impr/demo_msg_serv.cpp) and [demo_msg_cli.cpp](https://github.com/zarzen/efa-bad-practice/blob/try-impr/demo_msg_cli.cpp)

Reason to have this modification: I guess there are some lock between worker-thread and main-thread for serializing libfabric operations.

### 2. Instead of buffer pointers from *main-thread*, create buffers inside *worker-thread*
At first, my Tasks class will include `buffer pointer`s in each sub-task. Now, I created a buffer insider worker thread locally, for `fi_send/fi_recv` purpose. 

The modification results around 6 Gbps bandwidth improvement. Together with the previous modification I did, the bandwidth can reach 43 Gbps. 

Codes are at `use-local-buf` branch: [demo_msg_serv.cpp](https://github.com/zarzen/efa-bad-practice/blob/use-local-buf/demo_msg_serv.cpp) and [demo_msg_cli](https://github.com/zarzen/efa-bad-practice/blob/use-local-buf/demo_msg_cli.cpp)

### 1
So what could be the reason for those stragglers? (some wait for job completion takes over 10ms to complete, while most of others take less than 1ms)

### 2
Why waiting for job completion in main-thread causes performance degradation? 

### 3
Why using buffer created inside worker threads getting better performance? (I thought buffer created in main-thread(process) is shared with child-thread completely, and I didn't put any mutex there)

Really thanks for your patient!

**Comment by rwespetal** [comment]
Yes, the send/recv/completion queue operations that your worker threads are calling are serialized against the one endpoint as libfabric has semantics regarding multi-threaded applications. The EFA provider supports `FI_THREAD_SAFE` which does use locks to guarantee that any thread can safely access the underlying libfabric resources. You can find more information about this in the [fi_domain](https://ofiwg.github.io/libfabric/master/man/fi_domain.3.html) man page.

In general, I recommend that you create new libfabric resources for each thread unless you have a reason not to do so. This will do two things: 1) get rid of any lock contention during send/recv/cq polling operations between your worker threads and 2) provide dedicated network resources (queue pairs, buffers, etc.) for each thread which will also reduce contention and better saturate the network. Other libfabric applications such as MPI libraries follow this convention and setup libfabric resources for each rank on the node.

Regarding your questions, there are a handful of possibilities but I could only speculate without taking the time to profile this code. I would try using a dedicated endpoint per thread first unless you have a strong need to utilize the same endpoint across threads.

**Comment by zarzen** [comment]
@rwespetal thanks for your suggestion! I have moved to multiprocess to isolate endpoints now.
