### ISSUE TITLE
fi_cq_readerr with RMA data in verbs;ofi_rxm yields empty op_context

### ISSUE THREAD

**Issue by carstenpatzke** [ofiwg/libfabric#5738]
When calling `fi_write` with wrong information on a `verbs;ofi_rxm` domain will the next call of `fi_cq_readerr` yield in a mostly empty response.

``` c
errEntry.op_context: 0
errEntry.flags: 0
errEntry.len: 0
errEntry.buf: 0
errEntry.data: 0
errEntry.tag: 0
errEntry.olen: 0
errEntry.err: 258
errEntry.prov_errno: -258
errEntry.err_data: 0
errEntry.err_data_size: 0
```

It has probably something to do with an missing `case RXM_RMA:`-statement around here:

https://github.com/ofiwg/libfabric/blob/3e971a6527cb53674b9be166e536c897f758fe06/prov/rxm/src/rxm_cq.c#L1244

Also these warnings are displayed:
```
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1236<warn> fi_cq_readerr: err: Input/output error (5), prov_err: remote access error (10)
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1282<warn> Invalid state!
libfabric:18218:ofi_rxm:cq:rxm_cq_read_write_error():1285<warn> msg cq error info: remote access error
```

**Comment by shefty** [comment]
I can't say that I understand everything happening in the code through the completion path, but I think PR #5743 might fix the RMA error case.  There are other error cases still not being handled, but I need to figure out when those occur in the different protocol.

**Comment by carstenpatzke** [comment]
Running my test code against (90959f79d26217db1799605db673a152ee225228) result in  `fi_cq_read` just keeps returning `-FI_EAGAIN`.
When I run the exact same code from the previous commit of your branch (15ce5c62e2f87715b32bc546d33bb132b97aea4c) results in the behavior mentioned in the issue.

When running you branch I also get these messages.
```
libfabric:10217:ofi_rxm:cq:rxm_cq_read_write_error():1241<warn> fi_cq_readerr: err: Input/output error (5), prov_err: remote access error (10)
libfabric:10217:verbs:mr:ofi_mr_cache_delete():198<debug> delete 0x2ae234000010 (len: 838860800)
```

**Comment by shefty** [comment]
Are you getting -FI_EAGAIN or -FI_EAVAIL?  The latter is expected when there's an error completion available.

The message coming from rxm_cq_read_write_error is the reporting of the failed RMA transfer.  Were you able to retrieve the failed RMA request from fi_cq_readerr?

I will change one of our tests to generate an RMA error, so I can test this as well.  Note that this likely breaks the underlying connection, and I don't think rxm has the ability to recover from that sort of error.

**Comment by carstenpatzke** [comment]
With 15ce5c62e2f87715b32bc546d33bb132b97aea4c I get:
``` c
fi_cq_read: -259
fi_cq_readerr: 1
```

With 90959f79d26217db1799605db673a152ee225228 (your commit) I get:
``` c
fi_cq_read: -11 // Even after looping and waiting I still get -11
// In the mean time: ibfabric:10217:ofi_rxm:cq:rxm_cq_read_write_error():1241<warn> fi_cq_readerr: err: Input/output error (5), prov_err: remote access error (10)
fi_cq_readerr: -11
```

My calls
``` c
fi_cq_read(completion_queue, &entry, 1);
fi_cq_readerr(completion_queue, &err_entry, 0);
```

Btw. what do you mean with breaking the underlying connection?
I did not test it yet, but when the connection is closed / broken, I expect to receive an error when sending / receiving data, right?

**Comment by shefty** [comment]
259 is FI_EAVAIL.  You can use fi_strerror() to convert return codes to printable error strings.  Is  this the direct return value from the calls and not errno being read?  I don't see how -11 is even possible, with or without the changes.

**Comment by carstenpatzke** [comment]
I just want to give you the numeric values in order to be sure.

Did you test work?

You forget to set `util_cq`, the result is not written to the queue
``` c
if (RXM_IS_PROTO_STATE_TX(state)) {
```
does not hit.

Just redefine the macro
``` c
#define RXM_IS_PROTO_STATE_TX(state)	\
	((state == RXM_SAR_TX)  ||  \
	 (state == RXM_TX)      ||  \
	 (state == RXM_RNDV_TX) ||  \
	 (state == RXM_RMA))
```

**Comment by shefty** [comment]
For the disconnect, I mean that the underlying verbs RC QP will break.  I don't know how rxm handles this, if at all.

**Comment by shefty** [comment]
Thanks - so the problem is in the code I didn't change.  Even adding the change you suggest (which makes sense), I still don't see where -11 comes from.  I haven't had a chance to test this myself yet.

**Comment by carstenpatzke** [comment]
Uhh, so handling unexpected errors could be funny huh.
My understanding of the part that you modified is, that its taking entries from the _underlying_ provider and putting them in actual completion queue. Since no target completion queue was set, the entry was discarded. Maybe there should be a warning about this.

**Comment by shefty** [comment]
Your understanding is correct.  I'm updating my patch now.  I think there's more wrong here than just not reporting RMA events.  I'm at least trying to get that fixed.

Other operations could complete in error that also aren't being reported up to the application.  Without at least reporting a failure, the app won't even know of an issue.

**Comment by carstenpatzke** [comment]
Is it intended that the app won't know about this?
If not, maybe add a warning or **at least a debug log** here for an else part:
https://github.com/ofiwg/libfabric/blob/90959f79d26217db1799605db673a152ee225228/prov/rxm/src/rxm_cq.c#L1309-L1315

**Comment by shefty** [comment]
The intent is that the app should get a completion for any operation that completes in error.  The code has a switch statement with a catch-all default case that displays a warning for ops not expected to be handled, plus generates completion errors into all possible CQs.  I doubt the default handling is correct for some of the unhandled ops.

I've updated my patch to report the RMA error.  At least with a simple hack to one of the fabtests, I can force an RMA error and see that an error entry has been written.

**Comment by carstenpatzke** [comment]
Can confirm that f44cbb65d2d3ec633f05481b094afea933931022 is working for me

**Comment by shefty** [comment]
Thanks!
