### ISSUE TITLE
Inconsistent fi_getinfo behavior when using sockets vs verbs;ofi_rxm

### ISSUE THREAD

**Issue by carstenpatzke** [ofiwg/libfabric#5739]
Hey,
when using `hints->domain_attr->mr_mode` to set some attributes and then calling `fi_getinfo` with
**`sockets`** results in `fabric_info->domain_attr->mr_mode == 0`.
However running the same with
**`verbs;ofi_rxm`** results in `hints->domain_attr->mr_mode == fabric_info->domain_attr->mr_mode`.

Can I even assume that the result of `fi_getinfo` contains my given flags?

In both cases I set `mr_mode = FI_LOCAL_MR | FI_MR_ALLOCATED | FI_MR_VIRT_ADDR | FI_MR_PROV_KEY`. _(but I guess FI_LOCAL_MR is not necessary since its overflowing the 32 bit int anyways)_

Creating a domain by manually setting `fabric_info->domain_attr->mr_mode = hints->domain_attr->mr_mode` works.

**Comment by shefty** [comment]
More people monitor the libfabric-users@lists.openfabrics.org mailing list for general questions than github issues, which only a couple of developers likely subscribe to.

The mr_mode are treated as 'mode bits'.  (See the Mode section of fi_getinfo).  The provider will remove any bits (which are restrictions) that it does not require.   Sockets does not require any restrictions on the app, however, verbs does.

Valid mr_mode bits begin with FI_MR_xxx.  FI_LOCAL_MR is a deprecated mode (info::mode) flag and should not be used with mr_mode.  See FI_MR_LOCAL instead.

**Comment by carstenpatzke** [comment]
Thanks for clarification
