### ISSUE TITLE
What could be the reason to get error number 265 (Truncation error) with EFA-provider ?

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#5757]
Hi there, I am using libfabric-EFA-endpoint transmission data.
While sometimes I got error code 265. I have tried to print more detailed error information. While I only got `unknow error` from `fi_cq_strerror` function. 
With `FI_LOG_LEVEL=Debug`. I got following warning from console:
```
...
1 job cost : 10.674 ms
2 job cost : 18.9641 ms
3 job cost : 8.97145 ms
4 job cost : 2.51055 ms
5 job cost : 0.0321865 ms
libfabric:9961:efa:cq:rxr_cq_write_rx_completion():511<warn> Message truncated: tag: 0 len: 77922304 total_len: 26071040
Completion with error: 265
!!! err: unknown error
unknown error
6 job cost : 11.2801 ms
...
```

I feel the issue is due to the fact the transmission jobs are finished in the wrong order. 
My `job 6` should receive a buffer with length `26071040`, while `job 5` is a `fi_recv` job with length `77922304`. 

I think EFA-RDM-Endpoint is guaranteed to have send-after-send order right?
So what could the reason have such unordered truncation?
And how could we fix it?

here is the full log https://gist.github.com/zarzen/8cef76119dc6008ac5959742cf19f96c

**Comment by zhngaj** [comment]
Hi @zarzen,

What are the expected buffer lengths in your jobs, and what are the ones you were actually receiving? And did you set FI_ORDER_SAS in the hints when calling fi_getinfo?

**Comment by zarzen** [comment]
@zhngaj 
it would be good to have the buffer size larger than 100MB. (I think the EFA-RDM does not have message length limitation right?)
I haven't set the FI_ORDER_SAS in hints, I thought it would be forced by default. So I still need to pass FI_ORDER_SAS for both `fi_tx_attr` and `fi_rx_attr`?

BTW,
I have tried using `fi_tsend/fi_trecv` with a tag number to force order.

**Comment by zhngaj** [comment]
> Hi @zhngaj
> it would be good to have the buffer size larger than 100MB. (I think the EFA-RDM does not have message length limitation right?)

Correct, no message length limit.

> I haven't set the FI_ORDER_SAS in hints, I thought it would be forced by default. So I still need to pass FI_ORDER_SAS for both `fi_tx_attr` and `fi_rx_attr`?

Yes, you need to explicitly request FI_ORDER_SAS via hint->rx_attr->msg_order, and hint->tx_attr->msg_order. This way the endpoint can guarantee send-after-send order.

**Comment by zhngaj** [comment]
> I have tried using `fi_tsend/fi_trecv` with a tag number to force order, which can resolve this issue

The tagged message can not help you to guarantee the message order, they are not related. You still need to request message ordering.
