### ISSUE TITLE
Memory leak: Free the fi_prov instances

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#576]
There's at least two places where fi_prov instances should be freed (in src/fabric.c):

1. During fi_fini() (should be pretty straightforward)
2. During fi_register_provider(), if an error occurs

Note that fi_register_provider() seems to already handle the case where fi_getprov() returns a previously-registered provider of the same name.

**Comment by shefty** [comment]
I think these may have been addressed.  Setting a milestone, so that I remember to verify this later.
