### ISSUE TITLE
Intel-mpi-benchmarks pingpong test hangs with PR #5682 

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#5773]
Our nightly test caught a hanging issue when running Intel-mpi-benchmarks pingpong test with PR #5682 with 2 processes with shm provider. 

```
[ec2-user@ip-172-31-34-83 ~]$ mpirun --prefix /opt/amazon/openmpi -np 2  --hostfile /fsx/hosts --mca mtl ofi --mca mtl_ofi_provider_include shm /fsx/mpi-benchmarks-IMB-v2019.3/src_c/IMB-MPI1 -npmin 2 -iter 200 PingPong
#------------------------------------------------------------
#    Intel(R) MPI Benchmarks 2018, MPI-1 part
#------------------------------------------------------------
# Date                  : Thu Mar 26 17:53:11 2020
# Machine               : x86_64
# System                : Linux
# Release               : 4.14.165-103.209.amzn1.x86_64
# Version               : #1 SMP Sun Feb 9 00:23:26 UTC 2020
# MPI Version           : 3.1
# MPI Thread Environment:


# Calling sequence was:

# /fsx/mpi-benchmarks-IMB-v2019.3/src_c/IMB-MPI1 -npmin 2 -iter 200 PingPong

# Minimum message length in bytes:   0
# Maximum message length in bytes:   4194304
#
# MPI_Datatype                   :   MPI_BYTE
# MPI_Datatype for reductions    :   MPI_FLOAT
# MPI_Op                         :   MPI_SUM
#
#

# List of Benchmarks to run:

# PingPong

#---------------------------------------------------
# Benchmarking PingPong
# #processes = 2
#---------------------------------------------------
       #bytes #repetitions      t[usec]   Mbytes/sec
            0          200         1.08         0.00
            1          200         1.09         0.92
            2          200         0.96         2.08
            4          200         0.91         4.40
            8          200         0.91         8.75
           16          200         0.91        17.52
           32          200         0.92        34.71
           64          200         0.93        69.18
          128          200         1.04       122.77
          256          200         1.10       233.23
          512          200         1.12       455.15
         1024          200         1.19       858.82
         2048          200         1.43      1433.70
         4096          200         1.88      2183.91
^C^C[ec2-user@ip-172-31-34-83 ~]$ ^C
```
libfabric: 7219f3aac (HEAD -> master) Merge pull request #5682 from aingerson/shm
openmpi: v4.0.2
IMB: mpi-benchmarks-IMB-v2019.3

**Comment by aingerson** [comment]
@zhngaj Thanks, I'll look into this!

**Comment by zhngaj** [comment]
https://github.com/ofiwg/libfabric/blob/a0ccaf9f621152939b319b0a288a8e1dbcae2a47/prov/shm/src/smr_progress.c#L48

We should use id (fi_addr passed in smr_generic_sendmsg) instead of peer_id (cmd.msg.hdr.addr) here to get access to peer's shm region.
The quickest fix can be just adding fi_addr_t in smr_tx_entry struct.

**Comment by aingerson** [comment]
@zhngaj  Thanks for finding that. Yeah that should definitely be id. Thanks!

**Comment by aingerson** [comment]
Oh wait sorry, I was thinking of the wrong place. I think the ones in the progress_resp_entry should be ok.

**Comment by aingerson** [comment]
Aaaaand. I take it back again. Sorry. Yes. It sounds like we need an fi_addr_t in the pending struct. How was this working before though?

**Comment by zhngaj** [comment]
Without the refactoring of smr_progress_resp_entry, we don't need to access the peer's shm region, id/peer_id is not needed either.

**Comment by aingerson** [comment]
The resp progress call has always needed the peer_smr to push the inject buffer back into the pool.

**Comment by zhngaj** [comment]
Sorry, you are right.

**Comment by aingerson** [comment]
Not sure how this was working before (probably just coincidence that both addresses were the same) and why it's only failing now but this definitely needs to be fixed.

**Comment by zhngaj** [comment]
I'm testing the patch. I will open a PR once it's passing.

**Comment by zhngaj** [comment]
https://github.com/ofiwg/libfabric/pull/5775

**Comment by shefty** [comment]
Has this issue been resolved?

**Comment by zhngaj** [comment]
Yup. Resolved
