### ISSUE TITLE
Does shared contexts can bring performance improve?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [ofiwg/libfabric#5785]
These days, I am working on an library with libfabric's API to provide a fast communicate implement for upper code. And now my library is nearly complete, so I do a performance test but find low performance. In my code, each libfabric endpoint use only one QP, and I find the libfabric support an endpoint equipment with more than one contexts, does this mean that each libfabric endpoint support  more than one QPs? and if yes,  does more than one contexts can bring the improve of libfabric's send and recv performance in theory?

**Comment by shefty** [comment]
This question would see a better response if you posted it directly to the libfabric-users mailing list.

I'm guessing you're using FI_MSG endpoints.  Those map 1:1 to a QP for verbs based devices.  Verbs devices do not support shared transmit contexts (shared send queues).  Some support shared receive contexts (shared receive queues), but in practice shared receive queues help with scaling, but hurt latency performance.

You can try using multiple endpoints for communication to improve performance, but guessing without knowing more details, the performance may be the result of how your library is making use of asynchronous transfers and handling memory registration more than other factors.

**Comment by jsquyres** [comment]
This is probably in the context of https://github.com/open-mpi/ompi/issues/7567

For usNIC, there isn't much of a benefit of using more than one endpoint.

**Comment by Keepmoving-ZXY** [comment]
ok, thank you very much.
