### ISSUE TITLE
Assertion is triggered when using fi_cq_sread in verbs;ofi_rxm

### ISSUE THREAD

**Issue by carstenpatzke** [ofiwg/libfabric#5788]
When calling `fi_cq_sread/sreadfrom` with verbs;ofi_rxm an assertion is thrown.
https://github.com/ofiwg/libfabric/blob/5ea9ccb7a6ee9b0177d3b66bd1869806120425d6/prov/util/src/util_cq.c#L388

If `FI_ENOSYS` would be returned it would be safer to use.

**Comment by carstenpatzke** [comment]
Maybe I misused the verbs;ofi_rxm, but is there a way to setup a custom waitset in order to actually use `fi_cq_sread`?

I know that of what I read in the man page that it would be possible to wait for the completion queue, but it requires the use of `fcntl` and `poll`.
https://linux.die.net/man/3/ibv_get_cq_event

**Comment by shefty** [comment]
We avoid adding unnecessary branches in the code where possible, particularly to handle coding errors.  The caller can't handle a failure here, as the code is wrong and must be modified.

**Comment by shefty** [comment]
To use fi_cq_sread(), you need to specify a wait object when creating the CQ.  This can be specified through the fi_cq_attr.  If you only plan on calling the cq sread calls, the best option is to set the wait_obj to FI_WAIT_UNSPEC.  The provider will select the best option in that case.

**Comment by carstenpatzke** [comment]
Thanks for the super quick response. :) 
`FI_WAIT_UNSPEC` worked!
