### ISSUE TITLE
MR cache and FI_HMEM_CUDA

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#5789]
The memhooks and uffd monitors we have do not suffice for CUDA buffers. We have one of two options to be subscribed to deallocation events for CUDA buffers:

1. Intercept CUDA alloc/dealloc functions
2. Implement a [buffer ID tag check](https://docs.nvidia.com/cuda/gpudirect-rdma/index.html#invalidating-based-on-buffer-id)

Option #2 introduces additional expensive checks in the data path, which is not ideal for latency-sensitive applications. Open #1 is straightforward. We can either extend the existing memhooks monitor or add a new cuda-memhooks monitor. Providers that support FI_HMEM_CUDA can subscribe to multiple monitors if they so choose.

It looks relatively easy to extend the existing memhooks to cuda* methods (guarded by `HAVE_LIBCUDA`).

@shefty @j-xiong @aingerson / others - thoughts?

**Comment by shefty** [comment]
I would like to understand the memhooks and uffd issues and solutions somewhat separate from each other.

First, in order to use the cache, are we requiring that GPU addresses be mapped into the VA of the application?

What is the issue with the uffd option?

Without looking deeper into an implementation, it's hard to say if we wanted an extended memhooks or separate memhooks option.  I would start with extending the existing, and see if that leads to wanting it to be separated.

**Comment by rajachan** [comment]
> First, in order to use the cache, are we requiring that GPU addresses be mapped into the VA of the application?

For [CUDA devices](https://docs.nvidia.com/cuda/gpudirect-rdma/index.html#basics-of-uva-cuda-memory-management) at least, the GPU addresses are already mapped into the application's virtual address space by the CUDA runtime, just that it has to be handled differently. The OS manages the mappings backed by host memory while CUDA runtime manages the mappings for CUDA memory.  This is different when dealing with the Unified Memory that is managed by CUDA (physical pages are migrated based on where it is accessed), but I haven't fully thought through that case yet. If I am thinking through this right, from a network provider's perspective, it just has to be concerned with the memory explicitly allocated out of the CUDA virtual address space. For the mr_map in the cache, this would work like just another address range, except for missing out on the deallocation events.

> What is the issue with the uffd option?

With the mapping no longer managed by the OS, we are not getting page-fault notifications through UFFD for GPU backed pages. I am writing a simple test program to prove this out outside libfabric, will post it here in a while.

> Without looking deeper into an implementation, it's hard to say if we wanted an extended memhooks or separate memhooks option. I would start with extending the existing, and see if that leads to wanting it to be separated.

That makes sense. Will take a stab at it.

**Comment by shefty** [comment]
The uffd documentation doesn't indicate that it handles any VA->PA mapping changes.  It is only reporting changes for specific calls made by the application.  Maybe it could be made more generic someday...

OFI does support device memory that has not been mapped in the VA of the process.  If we need to cache device addresses, that will likely need to go into its own cache.  We might even need one cache per device.

**Comment by rajachan** [comment]
> The uffd documentation doesn't indicate that it handles any VA->PA mapping changes. It is only reporting changes for specific calls made by the application.

Right, I should have been less ambiguous. We would not get UFFD events for calls made by the application either, like a cudaFree().

**Comment by iziemba** [comment]
While offering lower latency, intercepting CUDA alloc/free functions can be problematic. For example, if an application is using nvcc but does not explicitly link to CUDA, the CUDA alloc/free functions will be statically defined within the binary. Libfabric would have no way to intercept these function calls. The buffer ID approach would have to be used for this example.

**Comment by rajachan** [comment]
Yeah, good point. Another (fixable) problem with the tag check on cache hit is the lack of an internal API in libfabric's MR cache for providers to manually kick out an entry if the buffer ID check fails.

cc: @wckzhang

**Comment by shefty** [comment]
If an entry is found, there's currently a check to see if the entry is usable (ofi_iov_within called from ofi_mr_cache_search).  That check likely just needs to be expanded.  E.g. create a new call ofi_entry_usable() -- move ofi_iov_within() into it and also add a tag check for device buffers.  The code already removes buffers that aren't usable.

**Comment by iziemba** [comment]
Since MR caches are associated with a memory monitor, I would assume a new CUDA memory monitor would be defined, correct? If so, if a provider wants to cache both host and CUDA MRs, would it need to have two MR cache instances?

**Comment by shefty** [comment]
I think we may just need to see how complex the implementation ends up.  Device memory that is NOT mapped into the VA probably needs to be separated into its own cache.  If the address maps into a VA, a single cache may be preferable.  In that case, it make make sense to allow multiple monitors per cache.  At this point, it's just a guess without digging deeper into the implementation to figure out how difficult each option would be.

**Comment by rajachan** [comment]
> I think we may just need to see how complex the implementation ends up. Device memory that is NOT mapped into the VA probably needs to be separated into its own cache. If the address maps into a VA, a single cache may be preferable. In that case, it make make sense to allow multiple monitors per cache. At this point, it's just a guess without digging deeper into the implementation to figure out how difficult each option would be.

+1. As long as the core cache provides the right monitors to cover FI_HMEM_* interfaces, this decision can be localized to providers based on the type of HMEM interfaces/devices they end up supporting. For FI_HMEM_CUDA in EFA, we are taking the single-cache approach.

So I implemented the tag check, and in the process realized that the cache (or the provider which pinned the buffer in the first place) needs to get the CUDA pointer attributes not just on a successful cache hit but also during the original registration (so we can do a diff to validate), which introduces the checks were were trying to avoid with the attr.iface bit in the first place ☹️.  CUDA-aware middleware using libfabric are probably going to do the pointer attribute check to set fi_mr_attr, so we'll have a redundant check in the call path if we took this route.

**Comment by iziemba** [comment]
> So I implemented the tag check, and in the process realized that the cache (or the provider which pinned the buffer in the first place) needs to get the CUDA pointer attributes not just on a successful cache hit but also during the original registration (so we can do a diff to validate), which introduces the checks were were trying to avoid with the attr.iface bit in the first place ☹️. CUDA-aware middleware using libfabric are probably going to do the pointer attribute check to set fi_mr_attr, so we'll have a redundant check in the call path if we took this route.

Is calling `cuPointerGetAttribute()` with `CU_POINTER_ATTRIBUTE_BUFFER_ID` a concern during MR allocation? I wouldn't think a CUDA-aware middleware would be making this specific call unless middleware was also doing a cache. Seems like middleware would call `cuPointerGetAttribute()` with `CU_POINTER_ATTRIBUTE_MEMORY_TYPE`.

**Comment by shefty** [comment]
The API is optimized for users that are aware of what memory buffers they are using, versus middleware that must re-discover it because its API doesn't allow that information to be conveyed.

*Why* is the middleware calling cuPointerGetAttribute()?

**Comment by iziemba** [comment]
If middleware/application knows that CUDA malloc was used, then it would not have to call `cuPointerGetAttribute()` with the `CU_POINTER_ATTRIBUTE_MEMORY_TYPE` and could hand libfabric the `FI_HMEM_CUDA` enum.

With the CUDA buffer ID cache approach, `cuPointerGetAttribute()` with `CU_POINTER_ATTRIBUTE_BUFFER_ID` needs to be called in order to get the unique ID for the given device VA to device page mapping. In addition, libfabric would need to repeatedly call `cuPointerGetAttribute()` with `CU_POINTER_ATTRIBUTE_BUFFER_ID` to verify the MR cache entry.

**Comment by rashikakheria** [comment]
The middleware/application may know that is it a CUDA buffer but libfabric APIs require additional information like CUDA device aka `mr_attr.cuda.device` to associate the cuda buffer with the actual hardware. This information are gathered using `cuPointerGetAttribute()`.

**Comment by shefty** [comment]
To me, that seems to indicate that the middleware really doesn't know where the buffer is from and is trying to rediscover it.

**Comment by shefty** [comment]
The buffer id check is fairly simple and should work in all circumstances.  Correct?  What advantage is there to creating an alternative solution that only sometimes works and requires that we have the buffer id check solution anyway?

**Comment by iziemba** [comment]
If the MR cache is to handle CUDA and host buffers, this makes the assumption that both the GPU and CUDA support a unified virtual addressing space. From the following link:

_When the application is run as a 64-bit process, a single address space is used for the host and all the devices of compute capability 2.0 and higher._

https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#unified-virtual-address-space

Is this something to be concerned with?

**Comment by shefty** [comment]
My short answer is no.

If a single cache is handling both host and GPU buffers, then they must share the same address space.  If the GPU buffers do not share the same VA space, then that requires a separate cache.  In that case, the only addresses which should go into the second cache would be GPU buffers.  But for that to work, the application must indicate what address space each buffer belongs to, and this needs to be carried through the API.

Keep in mind that the cache is to register buffers on demand that the application is not able to register itself.

**Comment by rajachan** [comment]
> The buffer id check is fairly simple and should work in all circumstances. Correct? What advantage is there to creating an alternative solution that only sometimes works and requires that we have the buffer id check solution anyway?

I am primarily concerned with having a pointer attribute query in the happy path for CUDA buffers, regardless of the application telling us it is a CUDA buffer.  From the data I could gather, the overhead is ~1us on most architectures for 1-1KB buffers, but could be as high as ~3us on others. We might not want to pay this price on every inline registration or cache hit.

Paging @Akshay-Venkatesh for input.

**Comment by iziemba** [comment]
>I am primarily concerned with having a pointer attribute query in the happy path for CUDA buffers, regardless of the application telling us it is a CUDA buffer. From the data I could gather, the overhead is ~1us on most architectures for 1-1KB buffers, but could be as high as ~3us on others. We might not want to pay this price on every inline registration or cache hit.

During libfabric initialization, maybe dl_iterate_phdr could be used to see if the application is linking to CUDA? If so, maybe a CUDA memhooks approach would be safe to use. Else, fallback to the CUDA buffer ID approach.

**Comment by shefty** [comment]
If the cache had hmem_setup() and hmem_validate() callbacks, I think it could work.  Those would be set to the query functions you wrote in your PR.  If memory hooks are enabled (cuda or amd), they become no-ops, unless the setup call needs to record a bit of state.

**Comment by rajachan** [comment]
Looks like we are reaching some consensus. I'll cut another PR for memhooks, and once we get that in, will look into a `dl_iterate_phd` based fallback to the buffer ID check. Sound good?

**Comment by Akshay-Venkatesh** [comment]
> I am primarily concerned with having a pointer attribute query in the happy path for CUDA buffers, regardless of the application telling us it is a CUDA buffer. From the data I could gather, the overhead is ~1us on most architectures for 1-1024 byte buffers, but could be as high as ~3us on others. We might not want to pay this price on every inline registration or cache hit.

Can confirm this is accurate. 

> During libfabric initialization, maybe dl_iterate_phdr could be used to see if the application is linking to CUDA? If so, maybe a CUDA memhooks approach would be safe to use. Else, fallback to the CUDA buffer ID approach.

This is along the lines of usage elsewhere for CUDA-Aware communication libraries. The hurdle that we commonly see is when CUDA is statically linked and we can't make the decision of whether to use buffer ID or interception. On a case by case basis, we've had to disable pointer interception when static linking result in illegal memory accesses.

**Comment by shefty** [comment]
#5978 added cuda support to the mr cache.
