### ISSUE TITLE
libfabric-1.10.0rc1.tar.bz2 does not have rxr_pkt_type_req.h 

### ISSUE THREAD

**Issue by Honggang-LI** [ofiwg/libfabric#5803]
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./include -D_GNU_SOURCE -D__USE_XOPEN2K8 -DSYSCONFDIR=\"/etc\" -DRDMADIR=\"@rdmadir@\" -DPROVDLDIR=\"/usr/lib64/libfabric\" -I./prov/sockets/include -I./prov/sockets -I./prov/verbs/src/ep_rdm -I./prov/verbs/src/ep_dgram -I./prov/efa/src/ -I./prov/efa/src/rxr/ -D__LIBUSNIC__ -DWANT_DEBUG_MSGS=0 -DHAVE_LIBNL3=1 -I/usr/include/libnl3 -I./prov/usnic/src/usnic_direct -I./prov/hook/include -I./prov/hook/perf/include -I./prov/hook/hook_debug/include -Wall -O2 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c prov/efa/src/efa_device.c  -fPIC -DPIC -o prov/efa/src/.libs/src_libfabric_la-efa_device.o            
In file included from ./prov/efa/src/rxr/rxr.h:66,                                                                                      
                 from prov/efa/src/efa.h:68,                                                                                            
                 from prov/efa/src/efa_device.c:50:                                                                                     
./prov/efa/src/rxr/rxr_pkt_type.h:399:10: fatal error: rxr_pkt_type_req.h: No such file or directory                                    
  399 | #include "rxr_pkt_type_req.h"                                                                                                   
      |          ^~~~~~~~~~~~~~~~~~~~                                                                                                   
compilation terminated.                                                                                                                 
make[1]: *** [Makefile:13245: prov/efa/src/src_libfabric_la-efa_device.lo] Error 1                                                      
make[1]: Leaving directory '/builddir/build/BUILD/libfabric-1.10.0rc1'

libfabric (master)]$ tar -tf libfabric-1.10.0rc1.tar.bz2 | grep rxr_pkt
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_type_misc.c
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_entry.h
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_type_data.c
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_cmd.c
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_type.h
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_entry.c
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_type_req.c
libfabric-1.10.0rc1/prov/efa/src/rxr/rxr_pkt_cmd.h
 libfabric (master)]$ tar -tf libfabric-1.10.0rc1.tar.bz2 | grep rxr_pkt_type_req.h
 libfabric (master)]$ find ~/upstream/libfabric/ | grep rxr_pkt_type_req.h
/~/upstream/libfabric/prov/efa/src/rxr/rxr_pkt_type_req.h

**Comment by shefty** [comment]
It looks like this file is missing from the _efa_headers section in rxr/Makefile.include.

**Comment by wzamazon** [comment]
My mistake, I  will open a PR soon

**Comment by wzamazon** [comment]
https://github.com/ofiwg/libfabric/pull/5804

**Comment by rwespetal** [comment]
Travis does have a `make rpm` step but it didn't catch this issue. rdma-core is not installed so the efa and verbs providers are not enabled when building the rpm. @shefty - do you want me to change this to use the `buildrpmLibfabric.sh` script with the right configure flags so we test this path for these providers?

**Comment by shefty** [comment]
If we can catch this with travis, I think we should try.

**Comment by rwespetal** [comment]
Sure, I'll submit a fix for it.
