### ISSUE TITLE
[EFA] calling fi_getinfo causes static variable to destruct

### ISSUE THREAD

**Issue by eric-haibin-lin** [ofiwg/libfabric#5829]
## Environment:
Amazon Linux 2 (`amzn2-ami-hvm-2.0.20200406.0-x86_64-gp2 (ami-0323c3dd2da7fb37d)`)
- installed g++ via `sudo yum group install "Development Tools" -y`
- installed EFA following https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-enable
```
[ec2-user@ip-172-31-23-194 src]$ fi_info --version
fi_info: 1.9.0amzn1.1
libfabric: 1.9.0amzn1.1
libfabric api: 1.9
```

## Test code:
```
#include <iostream>
#include <cstdlib>
#include <thread>
#include <rdma/fi_errno.h>
#include <rdma/fabric.h>
#include <rdma/fi_endpoint.h>
#include <rdma/fi_cm.h>
#include <rdma/fi_tagged.h>

class MyClass {
public:

  MyClass() {std::cout << "MYCLASS\n";}

  ~MyClass() {std::cout << "~MYCLASS\n";}

  void Init() {
    std::cout << "Init called\n" << std::flush;
    struct fi_info *fi;
    // =================================
    int ret = fi_getinfo(FI_VERSION(1, 8), NULL, NULL, 0, nullptr, &fi);
    std::cout << "ret = " << ret << "\n";
    // =================================
    while (true);
  }

  static MyClass* Get() {
    static MyClass e;
    return &e;
  }
};

int main(int argc, char *argv[]) {
  MyClass* c = MyClass::Get();
  c->Init();
  while (true);
  return 0;
}
```
## error 
Running the above code gives me:
```
[ec2-user@ip-172-31-23-194 src]$ ./test_efa
MYCLASS
Init called
~MYCLASS
ret = 0
```

However, since there are infinite `while true` loops, the static `MyClass` variable should never be destructed. 

If I remove 
```
    // int ret = fi_getinfo(FI_VERSION(1, 8), NULL, NULL, 0, nullptr, &fi);
    // std::cout << "ret = " << ret << "\n";
```
, the program will not print `~MYCLASS`, which is normal. 

Why would calling `fi_getinfo` causes my static variable to destruct? 

## compilation
`g++ -std=c++0x -std=c++14 -ggdb -Wall -finline-functions -I/opt/amazon/efa/include -o test_efa test_efa.cc -pthread -lfabric -L/opt/amazon/efa/lib64`

**Comment by eric-haibin-lin** [comment]
I tried both Ubuntu 18.04 and Amazon Linux 2. Both are problematic

**Comment by wzamazon** [comment]
Hi Haibin,

What you have observed is normal. During the initialization process, fork() was called to create a child process.  the fork operation creates a separate address space for the child. The child process has an exact copy of all the memory segments of the parent process. What you have seen is the child process called exit() and destructed the static variable in its address space. The static variable in parent's address space is remain intact. 

If you comment out the two ```while(true);``` statement, you will notice that the destructor of MyClass was called twice.
