### ISSUE TITLE
what happened to mlx provider?

### ISSUE THREAD

**Issue by holgerBerger** [ofiwg/libfabric#5845]
I am confused, I find many traces of a formlerly existing mlx provider, 
even the README.md mentions -with-mlx,
I see tickets with --enable-mlx, but non of those works.
How does one use libfabrics with UCX?

**Comment by shefty** [comment]
There was no maintainer or support available for the mlx provider, so it was removed.  What was there was incomplete.  Verbs based devices are supported through the verbs provider.  There is no current support for libfabric over ucx.

**Comment by holgerBerger** [comment]
it would be may good to remove the mentioning from the README.md then, and have that removal visible in the NEWS.md, when it happened and that is happened, I could not find it, which is confusing.
