### ISSUE TITLE
FI_HMEM support for RxM;Verbs

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5849]
I figured I would open up an issue to discuss how HMEM support should be introduced to RxM;Verbs in addition to opening a series of PRs to enable support. I would like to use this ticket to help guide the implementation.

The following are the high-level requirements I have for the implementation:
- RxM;Verbs must support Nvidia and AMD GPUs
- RxM;Verbs must support FI_MR_HMEM being unset
- RxM;Verbs must support messaging, tagged messaging, RMA, and atomics
- Nvidia and AMD MR cache must be implemented

The following sections are the main areas in libfabric I think need to be updated to support it.

\
**New internal HMEM operations**: Two of the common operations that RxM will be performing is copying to/from bounce buffers from/to user buffers. Currently, libfabric has copy operations defined for host memory (```ofi_iov.h```) and CUDA memory (```ofi_cuda.h```). Since AMD needs to be supported, a third one would need to be defined, ```ofi_amd.h```. But, instead of having a new header for each new device, a single header, ```ofi_hmem.h```, could be defined to handle all three cases. The following is how the prototypes could look.

```
ssize_t ofi_copy_from_hmem_iov(void *dest, size_t size,
			       const struct iovec *hmem_iov,
			       enum fi_hmem_iface *hmem_iface,
			       size_t hmem_iov_count, uint64_t hmem_iov_offset);

ssize_t ofi_copy_to_hmem_iov(const struct iovec *hmem_iov,
			     enum fi_hmem_iface *hmem_iface,
			     size_t hmem_iov_count, uint64_t hmem_iov_offset,
			     void *src, size_t size);
```
This would allow for all the ```ifdefs``` for memory operations to be placed in a single hmem.c file instead of having each provider have ```ifdefs```. Note that this assumes that the provider knows the HMEM iface type of the buffer which I think is a safe assumption.

In addition, a buffer check function could be added to ```ofi_hmem.h```.
```
enum fi_hmem_iface ofi_get_hmem_iface(const void *buf);
```
The use of this function is addressed further in the RxM section.

\
**Verbs support**: Currently, I see four main areas in the verbs provider which need to be addressed:
1. Selectively advertise ```FI_HMEM`` capability.
2. Support FI_MR_HMEM MR mode bit.
3. Use of bounce buffers for ```FI_INJECT``` with HMEM MRs.
4. MR cache memory monitors for Nvidia and AMD device buffers.

For item 1, for the verbs provider to support Nvidia and AMD GPUs, the system must be running MOFED which adds an IB peer memory component to kernel IB core (upstream Linux does not support IB peer memory). In addition, only offloaded-verbs, Mellanox NICs can support IB peer memory. This limits the type of verbs devices that can be supported to mlx4 and mlx5 devices and excludes rxe and hfi1 devices. Since it is possible to have a mixture of IB devices that do and do not support IB peer memory on the same system, the verbs provider may have to query both the kernel (e.g. check /proc/kallsyms for IB peer memory related symbols) and the verbs device to see if the ```FI_HMEM``` capability can be set.

For item 2, since the verbs provider requires users to register memory for local access (```FI_MR_LOCAL```), if the ```FI_HMEM``` capability is set, ```FI_MR_HMEM``` will also be set. Thus, ```fi_mr_regattr()``` must be used when working with device memory and the verbs provider.

For item 3, since a libfabric user could issue a ```fi_sendmsg()``` with a valid HMEM device MR and the ```FI_INJECT``` flag set, verbs needs to use a bounce buffer for this case before posting the send work request. This is due to the libmlx4/5 libraries performing a host copy operation of the inject payload onto the send queue.

For item 4, new memory monitors (or a different approach) needs to be taken to enable supporting caching of Nvidia and AMD MRs. As discussed in a previous issue, it seemed like the preferred approach is that if a GPU supports unified virtual addressing, a single MR cache can be used. The issue here is that a MR cache can only subscribe to a single memory monitor. Either another approach needs to be taken for device memory, or the MR cache and memory monitor implementations need to be update to a many-to-many relationship. An AMD memory monitor is discussed in a later section.

\
**RxM Support**: Currently, I see three main areas in RxM that need to be addressed:
1. Address the copying to/from RxM bounce buffers from/to device buffers.
2. Enable RxM to run with ```FI_MR_HMEM``` MR mode unset and ```FI_HMEM``` capability set.
3. When should RxM advertise the FI_HMEM capability.

For item 1, this is relatively easy to solve; replace the bounce buffer to/from user buffer copy operation with a device specific operation. The assumption here is that RxM would know the buffer type to select the correct operation. Where it gets a bit complicated is handling user IOV buffers. Currently, there is nothing in libfabric preventing an IOV style operation from using an IOV with different buffer types. This could result in RxM having to use different memory copy operations to move data to/from the bounce buffer from/to the IOV. Note that the above ```ofi_hmem.h``` copy routines would be used here.

For item 2, either RxM or another libfabric component needs to rediscover the buffer type for RxM to select correct memory copy operation to be performed. Currently, the implementation I have has introduced a new internal libfabric call, ```enum fi_hmem_iface ofi_get_hmem_iface(const void *buf)```, which RxM calls for each data transfer operation only if the ```FI_HMEM``` capability is set. At some point, there was talk of a hooking provider providing this functionality. But, this functionality (buffer query) does not appear to be implemented, so it was not completely clear how this would work.

For item 3, RxM is dependent on the core provider having support for ```FI_HMEM``` for RxM to support ```FI_HMEM```. One approach is that if the core provider supports ```FI_HMEM```, RxM would support ```FI_HMEM```. This would require RxM to support ```FI_HMEM``` with the collective API. I have yet looked at updating ```util_coll.c``` to support device memory, so maybe it makes sense for RxM ```FI_HMEM``` support to be conditional on the core provider supporting it and the user requesting it the hints. Note that ```FI_MSG```, ```FI_TAGGED```, ```FI_ATOMIC```,  and ```FI_RMA``` are required to be supported.

\
**New HMEM Interfaces**: To support AMD GPUs, new HMEM interfaces need to be defined. The AMD GPU software stack has two different APIs: ROCR/HSA and HIP.

ROCR is AMD’s HSA implementation. The HSA API is a very different from CUDA. In addition, AMD has extended the HSA implementation to provide additional functionality such as the ability to perform pointer query operations and register device memory free callbacks. For this interface, I think it makes sense to define ```FI_HMEM_ROCR```.

HIP is a CUDA-like API which can support either Nvidia or AMD GPUs. When a user is using HIP, during compilation, the user selects the HIP platform which is NVCC (Nvidia) or HCC (AMD). Depending on the platform, HIP will layer over CUDA or ROCR. For this interface, I think it makes sense to define ```FI_HMEM_HIP```. But, within libfabric, ```FI_HMEM_HIP``` should be remapped to either ```FI_HMEM_CUDA``` or ```FI_HMEM_ROCR```. This would all MRs to be cached using the CUDA or ROCR cache implementation.

At this point, the requirement has been to support FI_HMEM_ROCR leaving FI_HMEM_HIP for future work.

\
**AMD MR Cache Updates**: If the HMEM interface type is ```FI_HMEM_ROCR```, a memory monitor using the AMD HSA extensions can be implemented. The AMD HSA extensions allow HSA users to register a callback for a given device buffer which is called with the given device buffer is freed. A memory monitor using this callback would resemble the current UFFD or memory hooks monitor.

At this point, I have been maintaining a separate cache for each HMEM interface type. I think it would make sense to only have a single MR cache, assuming all GPU interfaces support unified virtual addressing. To support this, the MR cache implement needs to be updated to be able to subscribe to multiple monitors (e.g. one monitor for each HMEM interface type).

**Comment by shefty** [comment]
**HMEM operations**
Enum fi_hmem_iface can be used as an index into an array of data copy routines.  There's no use case for a mixed hmem iovec, so we restrict an iovec to a single hmem_iface through documentation.

**Comment by shefty** [comment]
**Verbs**
If HMEM is enabled, the inject size can be set to 0 to disable inject support.

MR cache discussion is in issue #5789

**Comment by shefty** [comment]
**RxM**
This applies to verbs as well, but the API assumes that the application indicates where all buffers reside.  If a provider allows FI_HMEM, but does not require FI_MR_HMEM, then that provider must determine where all buffers reside, if it needs that information.  Verbs will require FI_MR_HMEM, and RxM will pass it through.
