### ISSUE TITLE
DAOS: verbs - running connect/disconnect client hangs on 1024th iteration

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#5864]
Running simple server/client model where 5 servers are launched and client sends rpc to each server endpoints (8 total) and then gets restarted results in servers stop accepting rpcs on iteration 1024. 

RPCs contain  4096 input iov and 4096 output iov payload.

During one of the runs following error was produced:
libfabric:163648:ofi_rxm:ep_ctrl:rxm_conn_handle_reject():1143<warn> connection reject: no reject error data (cm_data) was found (data length expected: 2 found: 0)

Majority of the reruns however no error/warning is seen.

First 1023 launches of client pass fine with no issues.
This behavior has been confirmed multiple times, always failing on 1024th iteration.

Provider: "verbs;ofi_rxm"
OFI used: ad820ea4b195521c98a27f8bb49eabed04ab792f (latest tip as of today)
Also tried with previous OFI 62f6c937601776dac8a1f97c8bb1b1a6acfbc3c0 with same error.

Both servers and clients are launched on the same node over verbs.

Running same experiment over sockets provider passed above 30k iterations before being forcefully stopped.

In one of the retries over verbs provider it resulted in a complete 'hang' of the whole system at 1024th iteration requiring reboot.

Environment data:
FI_UNIVERSE_SIZE=256
FI_LOG_LEVEL=warn

Some additional info

After 1024th iteration when client fails, the system seems to be almost out of memory with servers using majority of the memory (61G over 5 servers)

aaoganez@wolf-55 cart> free -h
              total        used        free      shared  buff/cache   available
Mem:            62G         61G        239M        2.5M        290M         12M
Swap:           31G        4.0G         27G

The same experiment after running with sockets provider:
              total        used        free      shared  buff/cache   available
Mem:            62G        1.2G         60G        2.7M        309M         60G
Swap:           31G         83M         31G

**Comment by shefty** [comment]
The sockets provider isn't comparable to verbs devices in connected mode.  Verbs requires bounce buffers, particularly on the receive side, and needs pinned memory for QP and CQ allocations.  By default, each connection allocates a QP sized to 128 entries.  That should be controllable via env vars.  The default receive buffer size is 16k.  That's 2 MB of receive buffer space needed per connection, which is pinned.  There's additional overhead for the QP, CQ, and send buffers.

If the memory registration cache is enabled, that will result in additional pinned memory.  The size of the cache can be adjusted using env vars.

**Comment by frostedcmos** [comment]
for PSM2 case there is FI_PSM2_DISCONNECT=1 setting in order to purge server side connection info once client gracefully exits. is there anything similar in verbs?

**Comment by soumagne** [comment]
@shefty Unless I'm misunderstanding, what you're saying makes me feel that currently RxM is not honoring its semantics. By using RxM, we should be able to have emulated _unconnected_ endpoints, whatever happens underneath should remain hidden I believe. If a remote peer gets inserted into an AV for example and that peer is not connected (emulated or not), that peer should only need to be inserted once and RxM should track the connection state underneath and update it when necessary and when the peer disconnects / reconnects, allocating / freeing up resources at the same time but from the user point of view, it would be the same AV entry, set of resources that are not duplicated between connections. What you're saying makes me believe that this is currently not the case. If that were the case a remote peer that is referred by a unique address should not generate additional resource allocation or pinning.

**Comment by shefty** [comment]
It's possible that https://github.com/ofiwg/libfabric/pull/6292 may help here.  It should allow for establishing new connections after old ones have been disconnected.  However, I can't say if there aren't other issues being hit.

**Comment by shefty** [comment]
It appears that this issue was resolved or worked around.  There are other open issues regarding the rxm connection (or disconnect) handling.
