### ISSUE TITLE
Intel compiler warnings

### ISSUE THREAD

**Issue by mblockso** [ofiwg/libfabric#5872]
I'm attempting to compile libfabric 1.10.0rc3 with `icc` and see many warnings of this type:
```
In file included from .../libfabric/include/ofi.h(52),
                 from .../libfabric/src/log.c(41):
.../libfabric/include/ofi_atom.h(267): warning #2330: argument of type "ofi_atomic_int32_t={atomic_int_least32_t={_Atomic(int)}} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OFI_ATOMIC_DEFINE(32)
  ^

In file included from .../libfabric/include/ofi.h(52),
                 from .../libfabric/src/log.c(41):
.../libfabric/include/ofi_atom.h(268): warning #2330: argument of type "ofi_atomic_int64_t={atomic_int_least64_t={_Atomic(long)}} *" is incompatible with parameter of type "volatile void *" (dropping qualifiers)
  OFI_ATOMIC_DEFINE(64)
```
Compiler version is:
```
$ icc -v
icc version 19.1.0.166 (gcc version 7.4.1 compatibility)
```

Could this be related to #4063 or #4081 ?

Continuing to debug.

**Comment by shefty** [comment]
#4081 was incorrect and closed.

**Comment by mblockso** [comment]
This icc warning is discussed in the MPICH issue https://github.com/pmodels/mpich/issues/3997 and appears to be a compiler bug. Last comment from @jeffhammond is to use `-diag-disable 2330` to suppress the warning until the bug is fixed.

I'll work up a patch then we can decide if it is even worthy of pushing upstream.

**Comment by mblockso** [comment]
`export CFLAGS="-diag-disable 2330"` prior to configure suppresses the warnings.

Now what? Is this something of interest to the libfabric community that we should jam into configure for everyone, or should I just maintain this in my private build scripts?

**Comment by shefty** [comment]
Does the compile still work with the warnings being generated?

**Comment by mblockso** [comment]
The compile still works with the warnings .. but I need to do some more testing on the generated library/tests.

**Comment by jeffhammond** [comment]
You can talk to the compiler team to be sure, but I believe the warning is innocuous and only needs to be suppressed to get `configure` to complete successfully.

**Comment by shefty** [comment]
Does this actually cause the build to fail at the configure or make step, or is this just a harmless warning being spewed?

**Comment by mblockso** [comment]
I think it is "harmless warning being spewed".
