### ISSUE TITLE
verbs;ofi_rxm cache issue with MPICH collectives

### ISSUE THREAD

**Issue by aingerson** [ofiwg/libfabric#5880]
When running some of their collective tests, MPICH reports data integrity issues with verbs;ofi_rxm for messages taking the rendezvous protocol. At first glance it seems like the data is coming from the wrong peer.
We seem something like the following:
peer 0 sends rndv request to peer 1 -> tx_buf contents = 0,1,2,3
peer 2 sends rndv request to peer 1 -> tx_buf contents = 0,2,4,8
peer 1 does an fi_readv from peer 0 -> rx_buf contents = 0,2,4,8 (should be 0,1,2,3)
peer 0 gets rndv completion ack -> check tx_buf contents = 0,1,2,3

MPICH is using the following mr_modes:
`mr_mode: [ FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]`

To reproduce:
Build MPICH from https://github.com/pmodels/mpich
```
./configure --disable-oshmem --with-device=ch4:ofi --enable-ch4-direct=netmod --with-libfabric=<libfabric> && make install
export PATH=<mpich_bin>:$PATH
export LD_LIBRARY_PATH=<mpich_lib>:<libfabric_lib>:$LD_LIBRARY_PATH
cd mpich/test/mpi/coll
make reduce
export MPIR_CVAR_CH4_OFI_ENABLE_AV_TABLE=1
export MPIR_CVAR_CH4_OFI_ENABLE_RMA=1
export MPIR_CVAR_CH4_OFI_ENABLE_TAGGED=1
export FI_PROVIDER="verbs;ofi_rxm"
mpirun -n 4 -ppn 1 ./reduce
```

Disabling the MR cache (setting `FI_MR_CACHE_MAX_COUNT=0`) fixes the issue.
Could be related to issue #5867

**Comment by aingerson** [comment]
@shefty Let me know if you want more information

**Comment by aingerson** [comment]
@zhenggb72 Feel free to tag Atul here. I don't know his handle or if he has one.

**Comment by zhenggb72** [comment]
@aingerson Thanks for creating the issue. There is a typo in the description: 
peer 1 does an fi_readv from peer 1 -> rx_buf contents = 0,2,4,8 (should be 0,1,2,3)
It should be that peer 1 does an fi_readv from peer 0.

Also this happens whenever rxm sending a message goes through the rendezvous path. 
Glad to know disabling the MR cache workaround it. Does the caching happen in verbs provider, but not in TCP provider?  tcp;ofi_rxm run the test just fine.

**Comment by atulkulk** [comment]
Thanks @aingerson for opening this issue! Also, do you think an issue needs to be open for the out of memory error encountered during ibv_post_recv call in rxm as well?

**Comment by aingerson** [comment]
@zhenggb72 Thanks for the catch! I've updated it. The MR cache is used in verbs but not tcp so that makes sense that tcp;ofi_rxm works fine.

@atulkulk The other issue I don't think was a critical issue, just a warning, but I'll see if we need to fix that too and, if so, open a PR for it. Could you try running without the credits fix and disable the MR cache and see if that passes? If it doesn't, that likely needs to be fixed. If it does pass, it might still need to be adjusted but it's not critical.

**Comment by shefty** [comment]
The MR cache will not work prior to upcoming v1.11.1 and v1.12.0 releases.  Though uffd might work provided that the application does not enable or try to fork.
