### ISSUE TITLE
The shared library version number went down in 1.10.0

### ISSUE THREAD

**Issue by yurivict** [ofiwg/libfabric#5903]
With version upgrade 1.9.1 -> 1.10.0 the shared library version went down: ```lib/libfabric.so.1.12.1``` -> ```lib/libfabric.so.1.12.0```.

This is a small issue, but it might cause some confusion.

**Comment by shefty** [comment]
Whoa - that's not right then. I thought I updated the version number, but maybe I skipped it thinking I had when I hadn't.  I will look into this.

**Comment by shefty** [comment]
The 1.9.x branch has version 13:1:12.  The 1.10.0 release _should_ have been 14:0:13, as there as an API change, but was instead set to 13:0:12.  This is broken.  I doubt it will cause issues given the scope of the API changes, but this needs to be fixed.  The 1.10.0 version is reporting the same library version as 1.9.0 now.  ugh.

The 1.10.1 version should update to 14:1:13.  I will try to publish a 1.10.1 release next week to address this and an bsd build issue.

Thanks for finding this so quickly.

**Comment by shefty** [comment]
The version was updated in 1.10.1
