### ISSUE TITLE
Verbs: Flow control credits do not work with SRQs

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5907]
We are seeing failures with test suites and OSU benchmarks when running with RxM with XRC and SRQs. The issue seems to be in the verbs layer with vrb_post_send() always returning EAGAIN due to rq_credits_avail == 1. Comparing vrb_post_srq() and and vrb_post_recv(), vrb_post_srq() does not have the credit logic implemented that vrb_post_recv() has including incrementing rq_credits_avail.

**Comment by shefty** [comment]
Flow control shouldn't have been enabled in that case.  We'll look into it.  Is this against master?

**Comment by iziemba** [comment]
This is against master.

**Comment by iziemba** [comment]
Sorry. This appears to be with just normal SRQs and unrelated to XRC.

**Comment by iziemba** [comment]
Here is what I am running with MPICH and libfabric master:
MPIR_CVAR_OFI_USE_PROVIDER='verbs;ofi_rxm' srun  --exclusive -N 2 --ntasks-per-node=2 osu_alltoall -> passes
FI_OFI_RXM_USE_SRX=1 MPIR_CVAR_OFI_USE_PROVIDER='verbs;ofi_rxm' srun  --exclusive -N 2 --ntasks-per-node=2 osu_alltoall -> hangs
FI_VERBS_PREFER_XRC=1 FI_OFI_RXM_USE_SRX=1 MPIR_CVAR_OFI_USE_PROVIDER='verbs;ofi_rxm' srun  --exclusive -N 2 --ntasks-per-node=2 osu_alltoall -> hangs

**Comment by shefty** [comment]
The fix should be in master now.
