### ISSUE TITLE
dlopen GPU libraries

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#5928]
As libfabric is becoming more GPU aware, it could end up having to link to multiple GPU libraries. Currently, the way libfabric is configured and compiled, if these GPU libraries are not found, the application will not start. This may not be an ideal behavior for applications that are using libfabric without GPUs.

Two solutions exist with the current implementation for these applications: all node images have GPU libraries installed or have different libfabric builds base on node type. I think the ideal option would be to have one libfabric build that works with and without GPU libraries present. This would require libfabric to dlopen the GPU libraries.

Thoughts?

**Comment by rajachan** [comment]
Was thinking about this just the other day, when looking into `dl_iterate_phdr` to detect statically linked symbols for the MR cache CUDA memhooks. I can't think of a reason why not to do this other than the runtime branching in a bunch of places inside providers, some even in the critical path.

**Comment by iziemba** [comment]
Speculating a bit, but I think we could maintain per GPU dispatch tables which would only be initialized when that HMEM iface type is seen. Initialization would be costly, but it would only need to occur once. I think this would help reduce overhead described above.

**Comment by rajachan** [comment]
Yeah, that will help with things like picking the correct hmem IOV copy/validate function. There might be cases where a provide would want to conditionally toggle functionality based on the availability of a library (say, like deciding how to support FI_INJECT when dealing with a non-system buffer) that will need provider-specific dispatch tables, but yeah having the generic ops initialized to a specific implementation at init would help.  Where I landed the other day was having both somehow, and leaving the decision up to folks who distribute/deploy the package.

**Comment by iziemba** [comment]
> There might be cases where a provide would want to conditionally toggle functionality based on the availability of a library (say, like deciding how to support FI_INJECT when dealing with a non-system buffer) that will need provider-specific dispatch tables

If the providers need to be maintain their own dispatch tables for this case, up to them.

I think having both as an option makes sense. Maybe we should have a new configure option: --enable-dlopen-cuda. If this option is enable, the various CUDA functions will be resolved using dlopen and dlsym. Else, the various CUDA functions will be resolved with the dynamic linker. I can also work through a draft PR here outlining what I am thinking.

**Comment by rajachan** [comment]
> If the providers need to be maintain their own dispatch tables for this case, up to them.

Agreed.

> Maybe we should have a new configure option: --enable-dlopen-cuda. If this option is enable, the various CUDA functions will be resolved using dlopen and dlsym.

Sounds good to me. @shefty / @j-xiong / @aingerson, are you all fine with this too?

**Comment by j-xiong** [comment]
I am fine with the proposal, but have reservation on whether the new configure option is necessary. Always dlopen should work just fine.

**Comment by shefty** [comment]
A configure option seems reasonable, but is there really a significant drawback to always using dlopen?

**Comment by iziemba** [comment]
dlopen PR merged
