### ISSUE TITLE
'Excessive' warnings at initialization

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#5937]
```
user@host /scratch/jswaro/libfabric ((HEAD detached at ofiwg/master)) $ FI_LOG_LEVEL=warn /scratch/jswaro/install/libfabric/stash/master/bin/fi_info
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libpsm2-fi.so): libpsm2-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libpsm-fi.so): libpsm-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libefa-fi.so): libefa-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libusnic-fi.so): libusnic-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libgni-fi.so): libgni-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libbgq-fi.so): libbgq-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libverbs-fi.so): libverbs-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libnetdir-fi.so): libnetdir-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(librxm-fi.so): librxm-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(librxd-fi.so): librxd-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libshm-fi.so): libshm-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libudp-fi.so): libudp-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libtcp-fi.so): libtcp-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libsockets-fi.so): libsockets-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libhook_perf-fi.so): libhook_perf-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libhook_debug-fi.so): libhook_debug-fi.so: cannot open shared object file: No such file or directory
libfabric:3694:core:core:ofi_reg_dl_prov():559<warn> dlopen(libhook_noop-fi.so): libhook_noop-fi.so: cannot open shared object file: No such file or directory
provider: sockets
    fabric: 10.100.48.0/22
    domain: eth2
    version: 110.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_SOCK_TCP
...
```

This seems like too much information, and the warnings feel spurious. 

At compile time, most providers default to 'auto'. I think we probably have enough information to determine whether libfabric would load that provider by dlopen or not. If that's true, can we get rid of these warnings by only issuing these warnings if a provider was built to be opened as a dlopen library, and it couldn't be found? 

@shefty 

It's my opinion here, but these warnings seem unnecessary unless those providers have been compiled to be dlopen'd. This isn't a common runtime issue because I expect customers to run without FI_LOG_LEVEL=warn, but if every rank in a large job issues this statement at the beginning, this becomes a lot of output that is generally not useful for most cases -- and developers will have to sift through it. I'm suggesting trying to limit the number of messages where we can.

**Comment by shefty** [comment]
The warnings should be removed.  They aren't needed, and definitely should not be warnings, as they aren't errors in most cases.

But we cannot assume anything about whether a provider library is available as a dl based on the libfabric build.

**Comment by jswaro** [comment]
I agree with the first part.



> But we cannot assume anything about whether a provider library is available as a dl based on the libfabric build.

Why not? We get that information from the --enable/disable-<prov> options in the output/variables of configure don't we?

**Comment by shefty** [comment]
This is the expected use:

1. libfabric is built with all providers available internally, or at least all providers that the distributor supports.

2. Sometime later, a provider needs to provide a fix for their code.  They build their provider as a dl library, and ship that dl library to the customers.

The libfabric built in step 1 now discovers and loads the dl library from step 2, with the necessary fixes.

The libfabric build system makes it easy for the provider developer to perform step 2 by using the dl-build feature that's available.  This results in building a new version of libfabric, which the provider simply discards.

It helps if you think of the libfabric version in step 1 as being shipped by a linux distro.  The provider is only fixing their code by shipping a dl-provider.  They cannot replace all of libfabric as that replaces the distro version and affects other providers.

The libfabric build and the provider builds should be thought of as being separate.  It's mainly for testing purposes that we build things the way we do.

**Comment by jswaro** [comment]
Where is this functionality documented? I guess my understanding to date was libfabric is built as a mono-build unless otherwise requested with the dl functionality. If dl was requested, then step 2 was the model. 

I can understand the motivation, but where do we call out this type of behavior so it's well understood by developers and users? I did a brief search and didn't find anything except a brief reference to provider_path in the source code only.
