### ISSUE TITLE
feature request: add --without-<monitor> option to configure

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#5944]
Memhooks as a memory monitor is an option that users should have the choice to use. However, I believe there are valid reasons to compile out memory monitor implementations. 

In several issues from the last few years, I've encountered issues with memory hooking at the user level that resulted in silent corruption or functional errors. Memhooks follows a model that can be deliberately avoided by user applications. Whether the application does it directly or indirectly, memory hooks cannot provide a full solution.

I have observed several issues recently where we have observed silent corruption issues with independent software vendor (ISV) applications when using the memhook monitor, but not when using uffd or caching disabled. 

I would suggest an option to be added to configure to remove specific memory monitors at compile-time. I'm advocating for a change that can be done locally, at the discretion of software distributors. 

@shefty

**Comment by shefty** [comment]
It can already be disabled, why do we need to compile it out?  Data corruption has been reported for both memhooks and uffd, but it's a stretch to claim that neither can ever be made to work.  I have no idea how OpenMPI doesn't see data corruption, which is where the memhooks came from. 
 Disabling the cache fixes this, but no one likes the performance there.  Disabling the caches should be the default at this time, but there are some apps that would work fine with either enabled.

**Comment by swelch** [comment]
A concern here is if you have an application that works well with userfaultfd but not memhooks, that might be run on a system where userfaultfd is not available. Right now if FI_MR_CACHE_MONITOR is always initialized to userfaultfd, it would fallback to memhooks in that case.

Another option could be that is if FI_MR_CACHE_MONITOR is specified and not available, the disabled is set. That is, if you can't get what you requested you disable the cache.

**Comment by shefty** [comment]
The introduction of the GPU caches is changing things in this area.  Given that we have reports of data corruption if the cache is enabled, we need to disable it by default.  I agree if the user requests uffd, and that isn't available, then no fallback should be provided.

The current proposal for the CUDA cache is to mark it as enabled/disabled.  That's different from how the system memory cache is configured.  Maybe we should copy the enable/disable option for all monitors?  So, uffd is either enabled/disabled.  memhooks is enabled/disabled.  etc.  We can define the preference internally if there is more than one cache enabled for a given memory type, unless we implement a way to support multiple monitors at the same time.   (It's possible that enabling both memhooks and uffd might work?)

**Comment by jswaro** [comment]
> Data corruption has been reported for both memhooks and uffd, but it's a stretch to claim that neither can ever be made to work

Any person could write an application which would never function with memhooks. All it takes is behavior we'd generally frown upon, but as a lower-layer library, we lack the view into what memory allocation functions that an application chooses to employ. 

Personally, I believe uffd detects more occurrences of memory allocation than memhooks because it catches page changes in the kernel. 

> It can already be disabled, why do we need to compile it out?

The default ordering of memory monitors requires that a conscious decision be made to use a different monitor than memory hooks on certain distributions. On SLES for example, uffd and memhooks are available, but memhooks is chosen by default unless the user actively selects uffd or chooses to disable caching. 

Having an option to remove an option means that a software distributor can choose to provide a different default by omitting options that are chosen instead. In this case, the software distributor can omit implementations it doesn't choose to support. As libfabric developers, we could offer a method to change the default ordering of monitors or provide an option to remove monitors that shouldn't be shipped. I think removing monitors from the build is a less complex option with better control over what a distributor chooses to support.

**Comment by jswaro** [comment]
>  Maybe we should copy the enable/disable option for all monitors?

I think I would be fine with this. The reason why I suggested compiling it out is that if multiple distributors provide the same provider (verbs for example), we should have an option to have slightly different behavior if needed without modifying the source code that everyone uses. 

I want to avoid complicating the monitor selection code. The behavior I'd like to see most is clearly explainable from man pages, and clearly shown from the logging output if the log level matches. 

What I do want, is a option to allow applications to run on a different default monitor... and if that monitor isn't available, then it shouldn't fallback to a monitor I don't support. If no monitors exist that fit the criteria, then caching should be disabled. 

My first choice would be

**Comment by shefty** [comment]
memhooks was chosen as the default because uffd was showing data corruption at that time.  Data corruption has now been shown on both.

I don't care if we allow excluding an option from the build, though we're soon to have 5 different monitors available as part of HMEM support.  That's a lot of build testing.  But we still need to address how to handle the monitors when all are available.

**Comment by jswaro** [comment]
>  That's a lot of build testing. But we still need to address how to handle the monitors when all are available.

Fair points. I'm not sure how to best address it, but this is the best venue to find that answer. 

How would you suggest modifying the current behavior in a way that is transparent to the user (no need to specify a cache via environment variable), but doesn't increase the complexity of build testing?

**Comment by shefty** [comment]
tagging @iziemba - This discussion could lead to defining a standard way of enabling/disabling different monitors.  Even CUDA could end up with multiple monitors.

**Comment by iziemba** [comment]
The reason I went the enable/disable route for the CUDA monitor is because there was only a single monitor. I think @rajachan is working on a memhooks based CUDA monitor. So once there are two CUDA monitors, another solution would be needed for CUDA. I think whatever the solution is for system memory can be applied to CUDA.

**Comment by jswaro** [comment]
@shefty  I'm going to put up a PR for this. If you have suggestions, feel free to add them here or in the PR. I would like to get something merged for this issue soon because it is affecting applications and users adversely.

**Comment by shefty** [comment]
My only suggestion at this time is to have a way to enable/disable each monitor.  I'm indifferent to a compile option, but we need a way to disable all monitors in a released build in order to resolve data corruption issues.

If we end up with 2 monitors enabled for the same memory type, we can handle that either by actually enabling both, or letting the library only use the default.

**Comment by jswaro** [comment]
Ok, I'll post up a short-term solution, and we can handle the behavior of multiple monitors per memory type later.
