### ISSUE TITLE
EFA: Is there any way to control endpoint speed?

### ISSUE THREAD

**Issue by zarzen** [ofiwg/libfabric#5948]
Hi there,
Is there any way to control the bandwidth consumption of each endpoint?
or control the EFA nic bandwidth directly.

**Comment by rajachan** [comment]
This is currently not feasible. The libfabric API does have a Traffic class (tclass) attribute that was recently added (see [fi_endpoint(3)](https://ofiwg.github.io/libfabric/master/man/fi_endpoint.3.html)) that allows applications to configure different endpoints with varying performance characteristics, but the EFA provider does not support that interface today.  Do you have a particular use case in mind?

**Comment by zarzen** [comment]
@rajachan Thanks!
mainly for experiments, to understand how network speed affects application behaviors. 
It would be a legitimate use case to me where two applications want to fairly share EFA bandwidth on a single machine.
