### ISSUE TITLE
FI_MORE/FI_COMPLETION without fi_sendmsg?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#598]
I'm coming into the libfabric design process a little late, so I have a question about the various send flavors.  It looks like `fi_sendmsg` is the only version that allows the caller to specify flags on a per-transmit basis.  But `fi_sendmsg` will generally be slower than the other send operations, all else being equal.  So if flags like `FI_MORE` and `FI_COMPLETION` (namely its selective omission) provide significant performance opportunities, why does a caller have to use the slower API call to specify these optimizations?

`fi_inject` could be the right thing in some cases, but it doesn't cover the same use cases as `FI_MORE` for all networks.

One option to fix this would be to add an `fi_sendflags` (and possibly `fi_sendflagsv`, though  it's less critical):

```c
              ssize_t fi_sendflags(struct fid_ep *ep, void *buf, size_t len,
                  void *desc, fi_addr_t dest_addr, void *context, uint64_t flags);
              ssize_t fi_sendflagsv(struct fid_ep *ep, const struct iovec *iov, void **desc,
                  size_t count, fi_addr_t dest_addr, void *context, uint64_t flags);
```

We could also talk about the same sort of addition for the recv side, but the performance case is much less compelling.  Mainly being able to use `FI_MORE`, but even that's weak.

I don't have any hard performance data right now to pick at, but if others are receptive to the general idea then I can take a TODO to code this up so we can measure the impact.

-------
For reference in the discussion, here are some relevant excerpts from the current man pages:

(I just noticed that the `fi_sendv` prototype is wrong in the man page, I'll file a PR to fix in a moment)
```
              ssize_t fi_send(struct fid_ep *ep, void *buf, size_t len,
                  void *desc, fi_addr_t dest_addr, void *context);

              ssize_t fi_sendv(struct fid_ep *ep, const void *iov, void *desc,
                  size_t count, fi_addr_t dest_addr, void *context);

              ssize_t fi_sendmsg(struct fid_ep *ep, const struct fi_msg *msg,
                  uint64_t flags);
[...]
   fi_sendmsg
       The  fi_sendmsg  call  supports  data transfers over both connected and
       unconnected endpoints, with the ability to control the  send  operation
       per  call  through  the  use of flags.  The fi_sendmsg function takes a
       struct fi_msg as input.

              struct fi_msg {
                  const struct iovec *msg_iov;/* scatter-gather array */
                  void               **desc;  /* local request descriptor */
                  size_t             iov_count;/* # elements in iov */
                  const void         *addr;   /* optional endpoint address */
                  void               *context;/* user-defined context */
                  uint64_t           data;    /* optional message data */
              };

   fi_inject
       The send inject call is an optimized version of fi_send.  The fi_inject
       function  behaves  as  if  the  FI_INJECT  transfer  flag were set, and
       FI_COMPLETION were not.  That is, the  data  buffer  is  available  for
       reuse  immediately  on returning from from fi_inject, and no completion
       event will be generated for this send.  The completion  event  will  be
       suppressed even if the endpoint has not been configured with FI_COMPLE-
       TION.  See the flags discussion below for more details.
[...]
       FI_COMPLETION  :  Indicates that a completion entry should be generated
       for the specified operation.  The endpoint must be bound  to  an  event
       queue  with  FI_COMPLETION that corresponds to the specified operation,
       or this flag is ignored.
[...]
       FI_MORE : Indicates that the user has  additional  requests  that  will
       immediately be posted after the current call returns.  Use of this flag
       may improve performance by enabling the provider to optimize its access
       to the fabric hardware.
[...]
       FI_INJECT : Applies to fi_sendmsg.  Indicates that  the  outbound  data
       buffer  should  be  returned  to  user  immediately after the send call
       returns, even if the operation is  handled  asynchronously.   This  may
       require  that the underlying provider implementation copy the data into
       a local buffer and transfer out of that buffer.
```

**Comment by shefty** [comment]
The processing of flags results in branches being introduced in the calls.  This is why they have been omitted from the base data transfer operations.  Instead, the flags to apply to a given set of calls may be supplied through the fi_tx_attr::op_flags and fi_rx_attr::op_flags fields.

A general example of how this can be used with FI_COMPLETION is described in the fi_endpoint man page.

The intent is that apps that want multiple, optimized versions of the same interface can create an alias (fi_control FI_ALIAS), and modify the op_flags of the alias endpoint.

We have to balance having optimized calls with API explosion: send, senddata, sendflags, senddataflags, etc.

**Comment by rfaucett** [comment]
> The intent is that apps that want multiple, optimized versions of the same interface can create an alias (fi_control FI_ALIAS), and modify the op_flags of the alias endpoint.

Ah, right!  That's a subtlety I forgot about!  We may not have implemented that yet, but it works for me as an approach.

**Comment by goodell** [comment]
Yeah, I didn't see the fi_control/fi_alias stuff either.  This works well for me.  Thanks for the explanation.
