### ISSUE TITLE
Some libfabric logging enhancements

### ISSUE THREAD

**Issue by bfaccini** [ofiwg/libfabric#5996]
Possibility/choice (using some env var ?) to get the date/time added as each log line prefix.
Print thread-id instead of pid, or better in addition.
Possibility to overload current fprintf(stderr, ...) only logging way with an external method to redirect to a log-file, add more logged stuff/infos, ...

**Comment by bfaccini** [comment]
[PR-6030](https://github.com/ofiwg/libfabric/pull/6030) has been submitted to provide APIs allowing to overload log function and streams. This will allow to customize msg (adding timestamp, thread-id,...).

**Comment by shefty** [comment]
Logging can now be redirected to user provided calls.  See #7653.  Documentation in the man pages is missing but should be coming shortly.
