### ISSUE TITLE
[psm2] fi_writemsg() function does not terminate when the destination is not reachable 

### ISSUE THREAD

**Issue by fsalem** [ofiwg/libfabric#5997]
When there is a connection between two endpoints (different machines), each writes RMA messages to the other endpoint. In order to simulate the the failure of a connection between two endpoints, we terminate one of the endpoints and we expect that when the running endpoint tries to write RMA message to the failed endpoint, an exception/error will be thrown. Unfortunately, this is not the case. The function fi_writemsg() does not terminate at all and it hangs. This mainly happens when calling fi_writemsg() with FI_COMPLETION flag.

**Comment by shefty** [comment]
Do you know if this is through the psm2 provider?

**Comment by fsalem** [comment]
Yes, it is.

**Comment by fsalem** [comment]
I believe that it is duplicated (PR #6002).

Thanks @j-xiong & @shefty

**Comment by shefty** [comment]
I'm confused.  Did PR #6002 fix the issue?

**Comment by j-xiong** [comment]
@fsalem If possible, please verify that your test works fine after applying the fix. Or if you can provide the test source here I can give it a try.

**Comment by fsalem** [comment]
Sorry, I assumed this issue will be solved and merged to the main repository soon. Now I tested it myself. I cloned j-xiong's libfabric repository (https://github.com/j-xiong/libfabric). Unfortunately, the mentioned PR does not solve the problem. I debugged in the libfabric code and it still hangs on this function "psm2_am_request_short" (https://github.com/ofiwg/libfabric/blob/946cca3dfe2283788062424767289ae5bb75ada8/prov/psm2/src/psmx2_rma.c#L1083)

**Comment by j-xiong** [comment]
If the hanging happens inside psm2_am_request_short() it's an issue with the psm2 library.

**Comment by fsalem** [comment]
@j-xiong it is tested as a part of a large stream processing application (https://github.com/tschuett/flesnet/tree/fles_libfabric_DFS) If it would be hard to debug from this application, please let me know and I will write a micro-benchmark specifically for the fi_writemsg.

**Comment by j-xiong** [comment]
@fsalem Yes, a simpler reproducer is preferred.

**Comment by fsalem** [comment]
@j-xiong Please find a simple script that reproduces the problem
https://github.com/fsalem/psm2-micro-benchmark

**Comment by j-xiong** [comment]
The hanging inside `psm2_am_request_short()` is due to running out low level tx buffers. In the micro-benchmark, after the destination is terminated, the sender just keeps calling `fi_writemsg()` (from `sender_cq_event_handler()`). None of the writes would complete and the resource exhausts in the end.
```
368		if ((read == 1 && 0 == strcmp(alps_app_pe, "1")) || dest_terminated) { 
369 			sender_cq_event_handler(event); 
370 		} 
```

Of course, this won't happen if the `fi_writemsg()` call would fail or complete with an error status after the peer is terminated. Unfortunately, for PSM2 remote disconnection seems to be a silent event -- local side can continue to post new send requests and no asynchronous event is generated to terminate pending requests.

**Comment by fsalem** [comment]
Thanks @j-xiong for your investigation. Should I expect that this problem will be solved from the PSM2 library? or should I try to find a workaround?

**Comment by j-xiong** [comment]
@fsalem I would suggest you to find a workaround. I will report the issue, but don't expect expect it be fixed soon.
