### ISSUE TITLE
API: can we make fi_tostr() thread-safe?

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#6009]
Hi everyone,
I have a use-case here at DDN where `fi_tostr()` needs to called in a multi-threaded context. 
However and according to `man fi_fabric`,  `fi_tostr()` is not thread-safe. Is there any objection to change that behavior?

I would suggest 2 possible approaches: 
* Either declare the internal buffer used by `fi_tostr()` as a TLS variable with `__thread`.
* Provide a reentrant version of `fi_tostr()` (say `fi_tostr_r()`) that would accept a buffer (and a size) provided by the user to store the output string.

I can take care of the code changes if you agree with this proposal. 
Thank you!

**Comment by shefty** [comment]
I'd go with having a thread safe option.  I don't have a preference yet as to which option to take.  It would help to understand why GNU went with adding a new call like strerror_r(), rather than fixing strerror().

**Comment by sydidelot** [comment]
@shefty Thanks for your insight on this. I created the pull request  #6013 to add the function `fi_tostr_r()` to the API.

**Comment by shefty** [comment]
Addressed by PR #6354.
