### ISSUE TITLE
core: Additional clarification on traffic class behavior is needed in the man pages

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#6010]
@shefty I know we covered this with the original pull request for traffic classes, but a question came up on how discovery of traffic classes done by libfabric. 

At the time, we decided that a function to directly query the available traffic classes of a provider was unnecessary because a provider would map the requested traffic class in the hints to an available traffic class. 

If the application requested a traffic class that was not available... ie, FI_TC_DEDICATED_ACCESS was requested, but not available -- then the provider would be responsible for mapping it to an available traffic class -- FI_TC_BEST_EFFORT for example, and that FI_TC_BEST_EFFORT would be returned in the fi_info structure to provide some form of feedback to the application. That is how I recall the discussion but it's been a while since we've discussed it. 

What users have asked is this:

```Since libfabric does not have a way to directly query traffic class availability, how do I probe the interface to find out what is available?```

I am pretty sure our answer was to return the traffic class from the hints if it was available, or return a different traffic class that mapped closely to the requested traffic class if it wasn't available. The other option was to return an error or not return the provider if the traffic class wasn't available... but I thought we decided against that because it could cause problems with provider discovery... and it would not be intuitive as to why provider discovery could fail.

**Comment by shefty** [comment]
Providers can always support all traffic classes.  That doesn't mean that the traffic will end up using different flows underneath.  A provider may only have 1 underlying service level, for example, available that everything must map to.

The traffic classes that have been defined are generic hints and do not provide any real guarantees, since there's no way to specify what guarantees are needed.  For example, there's no way to specify how much bandwidth must be reserved for an app.  Those details are not something that an app can expect to control though, as it must be configured through an administrative entity, not just an application request.

I would expect a provider to fail an fi_getinfo request if it cannot return the requested traffic class value back to the user.  I would consider it an error if a specific value were provided as input, but another value was returned.

**Comment by jswaro** [comment]
That sounds vaguely familiar. 

However, two things you said seem to conflict. 

> A provider may only have 1 underlying service level, for example, available that everything must map to.

and 

> I would expect a provider to fail an fi_getinfo request if it cannot return the requested traffic class value back to the user. 

Conceptually, If a provider couldn't provide a traffic class, then we couldn't map to it. How do we reconcile those two statements. 




Additionally, how we provide any feedback to applications outside of the fi_getinfo case. The traffic class can be set at the transmit context as well. When a user creates a new transmit context, how do we provide information back to the user that informs them that the traffic class is unavailable? 

Through fi_getinfo, a user can only really determine if a few traffic classes would be available by setting the traffic class fields in the hints of a few different structures (domain, tx, rx). So maybe this is justification for a new FI return code? Something to more clearly indicate the cause of failure in a function call.

**Comment by shefty** [comment]
For the TC labels, I would not expect a provider to fail.  With DSCP, I believe failures could occur.  We can define a new error code to make those failures easier to identify.

**Comment by jswaro** [comment]
> For the TC labels, I would not expect a provider to fail. With DSCP, I believe failures could occur. We can define a new error code to make those failures easier to identify.

So, for TC labels, is the behavior I described above accurate with how we expect providers to respond? 

```If the application requested a traffic class that was not available... ie, FI_TC_DEDICATED_ACCESS was requested, but not available -- then the provider would be responsible for mapping it to an available traffic class -- FI_TC_BEST_EFFORT for example, and that FI_TC_BEST_EFFORT would be returned in the fi_info structure to provide some form of feedback to the application. That is how I recall the discussion but it's been a while since we've discussed it.```

**Comment by shefty** [comment]
No, I would not expect the provider to change the value requested by the app. That does not match other fi_info fields, and really isn't a policy that the provider should assume.  The provider should either fail the call if it wants to make the application developer's life painful, or return success.  If the app requests FI_TC_DEDICATED_ACCESS, and the best the provider can do with that results in the same behavior as FI_TC_BEST_EFFORT or FI_TC_SCAVENGER, oh well.  None of the FI_TC definitions provide any actual guarantees to the app.
