### ISSUE TITLE
OFI appears to be ignoring the value of FI_PROVIDER

### ISSUE THREAD

**Issue by mwheinz** [ofiwg/libfabric#6014]
I'm running an experiment to see if I can use an updated libpsm2 with the currently installed libfabric (I'm using the libfabric provided by IMPI...)

The problem is that even though I am specifying FI_PROVIDER_PATH and FI_PROVIDER I get the message:

```
libfabric:144556:core:core:ofi_register_provider():417<info> registering provider: psm2 (110.0)
libfabric:144556:core:core:ofi_register_provider():417<info> registering provider: ofi_hook_noop (1.0)
libfabric:144556:core:core:fi_getinfo_():1082<info> Since ofi_hook_noop can be used, psm2 has been skipped. To use psm2, please, set FI_PROVIDER=psm2
```

This is the environment I'm using:

```
mpirun -genv I_MPI_FABRICS ofi -genv FI_PROVIDER_PATH /usr/lib64/libfabric -genv FI_PROVIDER psm2 -genv FI_LOG_LEVEL info -hosts phwfstl014 -n 2 -ppn 2 /nfs/site/home/mwheinz/mpi-benchmarks-IMB-v2019.6/IMB-MPI1 uniband -iter 1
```

Can someone tell me what I'm doing wrong?

**Comment by shefty** [comment]
```
Since ofi_hook_noop can be used, psm2 has been skipped
```
That doesn't make sense to me.   IMPI must have internal changes, as that's not in the upstream source code.

**Comment by mwheinz** [comment]
Okay. I'll keep exploring.
