### ISSUE TITLE
About the Proper Behaivor of fi_cancel when FI_DELIVERY_COMPLETE is Specified.

### ISSUE THREAD

**Issue by aolia-0303** [ofiwg/libfabric#6019]
Currently libfabric manual does not define the right thing to do for `fi_cancel` when `FI_DELIVERY_COMPLETE` is specified: https://ofiwg.github.io/libfabric/master/man/

To implement `FI_DELIVERY_COMPLETE`, the sender cannot write completion until it has received an ACK from the receiver. For the receiver, what is the proper time to send the ACK back to the sender when `fi_cancel` is called on it. Shall the sender write an error entry to Tx/Rx queue after receiving the ACK or not?

**Comment by rwespetal** [comment]
What do you mean by reuse the send and match with another receive? That doesn't seem right.

As Sean stated when `fi_cancel()` is called and a matching transfer is found one of two things happens: 1) the transfer is cancelled and an error entry is written to state that it's cancelled or 2) the transfer cannot be cancelled and a normal completion is written. `FI_DELIVERY_COMPLETE` doesn't change that semantic and any protocol related issues here are going to be provider specific.
