### ISSUE TITLE
Quick question about the OFI ABI...

### ISSUE THREAD

**Issue by mwheinz** [ofiwg/libfabric#6028]
Quick question... is there some document someplace that defines the changes in the OFI ABI?

We're evaluating whether it's possible to package some software with just a updated/customized OFI provider instead of packaging our own build of OFI. The problem is SLES 15 ships with OFI 1.5 and RHEL 8 ships with OFI 1.9 and the ABI changed 3 times between those two releases.

So now I'm wondering what features we would lose if we built our provider for just the version 1.1 ABI.

**Comment by shefty** [comment]
The changes are documented in the NEWS.md file.  Though, the information isn't collected into a single location.  ABI changes (should be additions) would be listed under the Core change section.

Trying to recall off the top of my head, we added collective APIs, NIC attributes, persistent memory support, quality of service.  There may be a couple of other items I'm not recalling at the moment.

**Comment by mwheinz** [comment]
Thanks, Sean.
