### ISSUE TITLE
psm2 provider failed on old machine does not support AVX2

### ISSUE THREAD

**Issue by Honggang-LI** [ofiwg/libfabric#6037]
$ fi_rdm_tagged_bw -I 5 -v -p "psm2"  -s 172.31.20.6
Illegal instruction (core dumped)

$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              20
On-line CPU(s) list: 0-19
Thread(s) per core:  1
Core(s) per socket:  10
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               62
Model name:          Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
Stepping:            4
CPU MHz:             2889.496
CPU max MHz:         3300.0000
CPU min MHz:         1200.0000
BogoMIPS:            4987.33
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            25600K
NUMA node0 CPU(s):   0-9
NUMA node1 CPU(s):   10-19
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

$ gdb -q /usr/bin/fi_rdm_tagged_bw core.fi_rdm_tagged_b.0.f9e54ef9b02c43918aca25008731721b.88984.1592535837000000
Reading symbols from /usr/bin/fi_rdm_tagged_bw...Reading symbols from /usr/lib/debug/usr/bin/fi_rdm_tagged_bw-1.10.0-1.el8.x86_64.debug...done.
done.

(gdb) disassemble 
Dump of assembler code for function psmi_mq_req_init:
   0x000014ced97e0e60 <+0>:	endbr64 
................
   0x000014ced97e0ede <+126>:	movl   $0x1,-0x60(%rbp)
=> 0x000014ced97e0ee5 <+133>:	vextracti128 $0x1,%ymm0,-0x4c(%rbp)
   0x000014ced97e0eec <+140>:	vmovups %xmm0,-0x5c(%rbp)
   0x000014ced97e0ef1 <+145>:	vzeroupper

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mm256_extracti128_si256&expand=2457

CPUID Flags: AVX2

**Comment by Honggang-LI** [comment]
FYI: https://github.com/intel/opa-psm2/issues/40

**Comment by shefty** [comment]
I'm not sure this is a libfabric issue.  It looks like there is an unusable library (libpsm2) that's been installed on the system, and libfabric has been built to use it.  IMO, libpsm2 should check for avx2 support as part of it's build and adjust accordingly.

Is libfabric being built with the psm2 code statically integrated?

**Comment by Honggang-LI** [comment]
>  IMO, libpsm2 should check for avx2 support as part of it's build and adjust accordingly.

Close this issue, as libfabric crashed because of a libpsm2 bug.

> Is libfabric being built with the psm2 code statically integrated?

No, dynamic linked with libpsm2.so .
