### ISSUE TITLE
FI_MULTI_RECV CQ event for multi-receive buffer release is not last, in those returned by fi_cq_read()

### ISSUE THREAD

**Issue by gbtitus** [ofiwg/libfabric#6038]
## Synopsis

I am using the libfabric 1.10.1 release tarball and the `verbs;ofi_rxm` provider.  I have a multi-receive buffer to capture incoming messages on an endpoint.  I read 5 CQ events associated with that endpoint and they are, in order:

- An event for a received message, whose `buf` member points near the end of the multi-receive buffer.
- An event for the multi-receive buffer having been released by the provider.
- 3 more events for received messages, whose `buf` members point earlier in the multi-receive buffer than the first event does.

The presence of those last 3 events puzzles me, because I've concluded from reading the man pages that when I get an event for the multi-receive buffer having been used up and released by the provider, it will always be the last one returned to me by the `fi_cq_read()` call.

## More Details

There is only one multi-receive buffer.  It is posted with `fi_recvmsg()` at the beginning of the program and then re-posted whenever a `FI_MULTI_RECV` CQ event is processed.  The program sets the following ordering requirements (for both receive and transmit endpoints) in the hints for its `fi_getinfo()` call:

```
  hints->rx_attr->op_flags = FI_COMPLETION;
  hints->rx_attr->msg_order = (  FI_ORDER_RMA_RAW
                               | FI_ORDER_SAS
                               | FI_ORDER_SAW);
```

I read the events like this:

```
  struct fi_cq_data_entry cqes[5];
  const size_t maxEvents = sizeof(cqes) / sizeof(cqes[0]);
  ssize_t ret = fi_cq_read(ofi_rxCQ, cqes, maxEvents);
```

Afterwards I have the following (via gdb, from a core file):

```
(gdb) p ret
$3 = 5
(gdb) p/x cqes
$4 = {{op_context = 0x0, flags = 0x402, len = 0x40, buf = 0x7f52f35fb8c8, data = 0x0},
      {op_context = 0x0, flags = 0x10000, len = 0x0, buf = 0x0, data = 0x0},
      {op_context = 0x0, flags = 0x402, len = 0x40, buf = 0x7f52f35babc8, data = 0x0},
      {op_context = 0x0, flags = 0x402, len = 0x40, buf = 0x7f52f35bac08, data = 0x0},
      {op_context = 0x0, flags = 0x402, len = 0x40, buf = 0x7f52f35bac48, data = 0x0}}
```

`flags=0x402` is `FI_RECV|FI_MSG`.  `flags=0x10000` is `FI_MULTI_RECV`.  The last 3 events' `buf` pointers are earlier in the multi-receive buffer than the first event's `buf` pointer.  But they're not anywhere near the beginning of the buffer, which is described by:

```
(gdb) p/x ofi_iov_reqs
$5 = {iov_base = 0x7f52f0e00000, iov_len = 0x2800000}
(gdb) p/x ofi_iov_reqs.iov_base + ofi_iov_reqs.iov_len
$6 = 0x7f52f3600000
```

The end of the buffer space occupied by the first event is at address `0x7f52f35fb908`, 18168 bytes from the end of the buffer.  The value set for `FI_OPT_MIN_MULTI_RECV` for the endpoint in question is 18176, so indeed that first event's message contents just pushed us over the release point for the multi-receive buffer.

**Comment by shefty** [comment]
Can you verify that v1.12.1 still shows the same problem?  I know there were updates to FI_MULTI_RECV, but I can't say that those impacting completion ordering for it.
