### ISSUE TITLE
FI_MULTI_RECV should maintain maximum alignment

### ISSUE THREAD

**Issue by hzhou** [ofiwg/libfabric#6041]
The documentation states for `FI_MULTI_RECV`: "The placement of received data into the buffer may be subjected to provider specific alignment restrictions." This makes certain use case very difficult. For example, in a typical active message system, the header often has alignment requirement while the data may be arbitrary bytes. With `FI_MULTI_RECV` when consecutive messages are packed one after another, the latter message may be packed at the wrong alignment and makes the header in-accessible. While the work around is not difficult -- the application need either pad the data or always `memcpy` the header before accessing -- it places a non-obvious burden to user. If libfabric demand all providers pad the multi-received message at maximum alignment (e.g. 16), this will make the usage much simpler at little performance cost.

**Comment by shefty** [comment]
I think there are two related issues here.

First, the provider alignment restriction is there to allow providers to start each new message at some reasonable alignment.  We can clarify that provider alignment, *if one exists*, will not be arbitrary, but will at least start on a boundary that aligns with the sizeof a pointer.

The other problem is that an application may have an alignment requirement on their data.  This should remain the responsibility of the app.  If the receiver is using a multi-recv buffer, and the provider does not add any alignment, it's possible for received messages to occur at any offset.

The provider, particularly the sender, should not add padding to the sending message, as that requires coordination with the receiver to ensure that the receiving buffer is not overrun.

**Comment by hzhou** [comment]
> First, the provider alignment restriction is there to allow providers to start each new message at some reasonable alignment.

Is this alignment exposed to the application? Anyway, the issues is really trying to suggest always do maximum alignment (but pointer size should be practically sufficient) since that greatly ease the application usage.

> The other problem is that an application may have an alignment requirement on their data. 

As library, since you can't pick applications, I think you have to assume there is always alignment requirement.

> The provider, particularly the sender, should not add padding to the sending message, as that requires coordination with the receiver to ensure that the receiving buffer is not overrun.

I was more thinking that the receiver side should always shift the destination address to the alignment.

**Comment by shefty** [comment]
The alignment is not exposed.  I'm not sure what an app would do with that anyway.  I also don't know what 'maximum alignment' means.  8-byte boundary? cache line? page size? hugepage size?

Requiring aligning to a specific boundary forces an implementation.  Allow providers to add alignment gives flexibility, forcing them is a different matter.  However, I'm okay with documenting that providers that do make alignment adjustments won't be insane about it.

Worst case, the user above libfabric needs to assume that messages are tightly packed, and are responsible for handling any alignment issues that may result.

**Comment by hzhou** [comment]
"maximum alignment" is typically means the maximum of the basic compiler supported types -- often that comes to 16, that of `long double`.

> the user above libfabric needs to assume that messages are tightly packed

I guess that's fine if that is the decision. Just thought that requiring provider always align the destination address to a certain alignment, e.g. 8, is relatively trivial to implement, and dramatically more convenient for the user (since they don't need worry).

The worst case without a clear clause is that some provider may arbitrarily insert extra padding between messages, in which case there is no way for a application to control the alignment at all.

**Comment by shefty** [comment]
It's trivial to implement changes when the multi-recv support is entirely in software.  For hardware support, it's not.  And we don't want to require a specific hardware implementation.

**Comment by hzhou** [comment]
Thanks for you explanation. I'll close this issue.
