### ISSUE TITLE
prov/tcp: possible deadlock from lock ordering

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#6046]
tcpx_conn_mgr_run() holds eq close_lock while calling process_cm_ctx().  That call can acquire the ep lock (e.g. in tcpx_ep_enable_transfer()).

It's possible for the reverse locking to occur.  tcpx_cq_progress() holds ep lock, which can acquire the eq close_lock in tcpx_ep_wait_fd_del() <- tcpx_ep_shutdown_report() <- process_tx_entry()

**Comment by aakefbs** [comment]
I will take a look, if I manage this week, otherwise next week.

**Comment by shefty** [comment]
Likely related to trace in issue #6189
