### ISSUE TITLE
Missing _ofi_process_vm_writev on macOS

### ISSUE THREAD

**Issue by Bo98** [ofiwg/libfabric#6089]
The dylib in libfabric 1.10 and later cannot be used in some situations due to a missing symbol:

```
dlopen(/usr/local/opt/libfabric/lib/libfabric.1.dylib, 0x0009): symbol '_ofi_process_vm_writev' not found, expected in flat namespace by '/usr/local/opt/libfabric/lib/libfabric.1.dylib'
```

This is a runtime error rather than one caught at link time. Due to certain quirks in dyld, it isn't necessarily fatal when loaded through regular linkage but will be fatal when opened (potentially indirectly) via `dlopen`, such as when it is linked to a Python module - which are loaded on demand.

**Comment by shefty** [comment]
Hopefully PR #6109 fixes this issue.

**Comment by shefty** [comment]
Issue should be resolved with current master.  Please re-open if not.
