### ISSUE TITLE
Can FI_ADDR_UNSPEC be equal to 0?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#609]
It's convenient for apps to use 0 to mean 'I don't care', rather than specifying a constant like FI_ADDR_UNSPEC.  (Zero is actually what the PSM provider checks for.)  FI_ADDR_UNSPEC is the only 'unspec' value that is non-zero.  The problem with changing it to 0 is that this removes the possibility of using index 0 for AV table.

**Comment by rfaucett** [comment]
My vote: leave FI_ADDR_UNSPEC non-zero.  Having 0 be an invalid index for AV_TABLE is weird.

I think your only other realistic choice is to add some translation layer between fi_addr_t from AV_TABLE and actual indices: fi_index_to_addr() and fi_addr_to_index() (could just set and clear a high-order bit, for example).  I think that's unpleasant , but it does prevent calloc()ed structs from containing valid fi_addr_ts.

**Comment by shefty** [comment]
FI_ADDR_UNSPEC is only used by apps that set the FI_DIRECTED_RECV cap bit.  Otherwise, the src_addr field of recv() calls is ignored.  So, I think it's fine to keep it as is.  Apps that want this capability (is there any other than MPI?) should be okay using FI_ADDR_UNSPEC.  Other apps can pass in 0 for the src_addr anyway.
