### ISSUE TITLE
fi_strerror could be more explicit about errors below FI_ERRNO_OFFSET

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#6093]
It would make debugging easier if 'system' errno values (those that are directly mapped from errno.h definitions) would have a more differentiated string description, at least for the ones that have a direct mapping in `fi_errno.h`, like `FI_ENOSYS`.

`fi_strerror` could either resort to `strerror` for them, or extend the `errstr` table at https://github.com/ofiwg/libfabric/blob/be94ff4567b7cfbdf4ab5f19a433373ffffea26f/src/fabric.c#L1218 . (The latter solution seems less maintainable/would require all `FI_ERRNO_OFFSET` entries to be populated to ensure clean access.)

**Comment by shefty** [comment]
Error values mapped directly from errno.h do use strerror().  The errstr table is for custom error values.

**Comment by u-u-h** [comment]
Sorry for not reading all the way down in `fabric.c`, I see it now. 
The issue came up for me because I accidentally used the negative return value as the argument to `fi_strerror(3)`. I see that the `fi_strerror(1)` utility program does accept negative values and prints the right value, while the library function does not.

Feel free to close this issue.
