### ISSUE TITLE
[Question: verbs] Multiple threads simultaneously calling the fi_write. Will there be thread safety issues?

### ISSUE THREAD

**Issue by CharlesJhonson** [ofiwg/libfabric#6094]
Hello, after testing a bit with libfabric I have not  find  examples about multi-thread.

Currently, I would like to develop  an multi-thread app.
In this application, multiple threads may simultaneously call the fi_write(RMA Semantic) function to write data to the remote memory（MR） in a thread on the server side. 
 In this case,：
     1） will the data of multiple fi_write operations get out of order when it reaches the server(remote)? 
           And, how does the server ensure that the order of receiving data is consistent with the sender in libfabric?
     2 )  will there be thread safety issues?

Thank you for taking the time to pay attention to this issue

**Comment by shefty** [comment]
Multi-threaded apps are supported.  See fi_domain_attr::threading to specify the desired synchronization needed.

Data ordering is specified through endpoint/tx/rx attributes.  The ordering of operations will depend on the order that the threads call into the API.  As a general flow, each fi_write call will acquire a lock, post the request to a queue, and release the lock.  The provider/hardware will process the queue in order and transmit to the network.

The data will be seen at the target in the same order as transmitted, unless message and data ordering is relaxed.  See fi_tx_attr::msg_order and fi_ep_attr::max_order_waw_size for your specific question.

I believe most providers will provide write-after-write ordering, with the write data within a single message also placed in order.

**Comment by CharlesJhonson** [comment]
Ok, thanks very much for your answer.
 Now I will close the issue.
