### ISSUE TITLE
All providers should implement fi_mr_attr_raw, as documented

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#6095]
Reading the documentation for `fi_mr_attr_raw` (see https://github.com/ofiwg/libfabric/blob/c199da31c1f029e7ec1566b665e1650c03bf533b/man/man3/fi_mr.3#L477) it would seem that user code can simply always work with attr_raw keys for memory registrations instead of checking FI_MR_RAW and choosing alternative code paths (ignoring that it may be suboptimal performancewise).

Looking at the code, however, most providers are not implementing it (I see `FI_GET_RAW_MR` in psmx2 and mrail), and there is not default implementation that simply produces the non-raw key (which I would have expected given the docs referenced above). Instead, `fi_mr_attr_raw` returns `-ENOSYS`.

**Comment by shefty** [comment]
Yes, all providers *should* implement this feature.  That was definitely the intent.

**Comment by u-u-h** [comment]
I think the pass-through implementation should not be difficult to do. 
Where would you consider to be a good place for providing a generic implementation that all providers could use in the `mr_control` dispatch -- and would you consider merging a patch that touches all providers for this?

**Comment by shefty** [comment]
I would accept a generic implementation.  It looks like the best fit would be prov/util/src/util_mr_map.c.
