### ISSUE TITLE
Convert ep:enable() ops into a control operation

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#612]
The idea was raised in an email of using ep::control(... FI_ENABLE ...) in place of ep::enable().  The interface (static inline call) to the user would remain unchanged.  This would reduce the number of entry points into the providers, and allow for enable to take additional control data, if that ever becomes needed.

**Comment by sayantansur** [comment]
Submitted PR #614 for this. Compile tested only. @jithinjosepkl @j-xiong @goodell, please review.

**Comment by jithinjosepkl** [comment]
Sockets provider changes look good.
