### ISSUE TITLE
HMEM Hooking Provider Details

### ISSUE THREAD

**Issue by iziemba** [ofiwg/libfabric#6139]
In OFIWG and various PRs, there has been discussions/comments around using a hooking provider to perform pointer queries to discover the corresponding HMEM iface type and perform memory registration. The end result is a util provider which enables the FI_HMEM capability without FI_MR_HMEM. I want to use this ticket as a forum for discussing some of the finer HMEM hooking provider details.

The following are some initial questions I have about the hooking provider:

- One thing which is unclear about the HMEM hooking provider is how it gets applied. Currently, hooking providers are applied through environment variables. Is this behavior going to extended to the HMEM hooking provider? Or, if middleware requests FI_HMEM without FI_MR_HMEM, will the hooking provider be automatically applied?

- Is there going to be a HMEM hooking provider for each HMEM iface type? Or will there be a single HMEM hooking provider which can handle all HMEM iface types?

**Comment by shefty** [comment]
The intent with the hooking provider is to allow applications to make use of HMEM without software changes.  The provider would expose support for HMEM, with any requirements that it has, including FI_MR_HMEM.  The hooking provider is not targeting applications that request FI_HMEM directly.

This requires enabling the hook through an environment variable.

In discussions the consensus is that there could be a single hooking provider implementation capable of supporting all iface types.  However, it would only need to enable hooking a single iface at a time.  The iface would be selected through an environment variable.

**Comment by iziemba** [comment]
Here is the use case I am dealing with. If an application/middleware sets FI_HMEM in the hints but does not set FI_MR_HMEM, how can it get the rxm;verbs provider?

**Comment by shefty** [comment]
I think the hooking provider could be adjusted to handle that case.  I think it just means that the app will always flag HMEM when registering memory as an RMA target.

**Comment by iziemba** [comment]
No other questions. Closing issue.
