### ISSUE TITLE
questions about deferring memory registration cleanup

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6157]
Currently in the master branch, upon receiving the notification from memory monitor that a memory region is about to be return to the OS, the MR cache will not immediately cleanup the corresponding memory registration. Instead, it will put the memory registration in ```mr_cache->flush_list```, and clean it up later when ```ofi_mr_cache_flush```.

This behavior was introduce by the following commit:

```
commit 3d01df7716d099ba222f99865345d6767ae9e686
Date:   Sat Jan 18 10:10:19 2020 -0800

    util/mr_cache: Defer MR cleanup to flush operation
    
    We cannot safely hold the monitor lock while freeing
    memory or deregistering a MR.  Doing so can result in
    hanging the local thread, as well as the uffd thread.
    When uncaching a region, instead of removing it
    immediately if the use_cnt is 0, instead queue it to
    a flush_list associated with the MR cache.
    
    When calling ofi_mr_cache_flush, always cleanup the
    flush_list, without holding the monitor lock.
```

As a result of deferring MR cleanup, memory  de-registration always happens after the related memory region has been returned to the OS, which can cause some issues.

For example, rdma-core's fork support would fail under such circumstance. To support fork, rdma-core maintains a rbtree to keep track of existing memory registration. The rbtree was updated after successful call to ```madvise```. It is implemented under the assumption that when application call ```ibv_dereg_mr``` the corresponding memory region has not been returned to the OS.  When application does not meet the assumption, the call to ```madvise(MADV_DOFORK)``` would fail and the rbtree was not updated correctly. As a result, following memory registration can fail or the memory region will not be madvised correctly, which can lead to correctness issue.

Another example would be GPU memory registration. There is a difference between CPU and GPU memory. When CPU pages are freed the kernel still holds a reference count on them because of the memory registration. GPU pages are not tracked by the kernel, so when the user frees the buffers the nvidia driver triggers its "free callback" and asks for its pages back, which would mean the GPU memory registration has to freed too. Hence, defer GPU memory de-registration can lead to the double free situation.

Because of the issues mentioned above, I want to know more about commit 3d01df7716d099ba2, which introduce the change.

Specifically, I am interested in:

1.  the statement "We cannot safely hold the monitor lock while freeing memory or deregistering a MR". It seems to be because freeing memory or de-registrering a MR can lead to the memory monitor being triggered again, and it would be great to understand the problem more.

2. Inside ```ofi_mr_cache_flush()```, MR cache is release lock before ```util_mr_cache_free_entry``` and obtaining the lock after it. so that when ```util_mr_cache_free_entry``` was called, it is not holding the lock. We wonder if we can do the same thing in ```util_mr_uncache_entry```? e.g. instead of put the entry in flush_list, we do: unlock, call util_mr_cache_free_entry, then lock again.

Thank you for your patience, and I would really appreciate your input on this matter!

**Comment by shefty** [comment]
> 1.	the statement "We cannot safely hold the monitor lock while freeing memory or
> deregistering a MR". It seems to be because freeing memory or de-registrering a MR can
> lead to the memory monitor being triggered again, and it would be great to understand
> the problem more.

This is exactly the problem.  For userfaultfd, when a thread calls alloc/free/mmap/etc., that thread _could_ be blocked by the OS.  It depends on whether the call adjusts the page tables, for example.  The thread remains blocked until some other thread reads the userfaultfd event.

The result is that we cannot make any calls which might make memory allocation related calls from the userfaultfd thread.  The handling must always be asynchronous in this case.

> 2.	Inside ofi_mr_cache_flush(), MR cache is release lock before
> util_mr_cache_free_entry and obtaining the lock after it. so that when
> util_mr_cache_free_entry was called, it is not holding the lock. We wonder if we can do
> the same thing in util_mr_uncache_entry? e.g. instead of put the entry in flush_list,
> we do: unlock, call util_mr_cache_free_entry, then lock again.

The hang isn't a locking issue.  It's a limitation placed on the thread.

A specific monitor could take other necessary actions, like performing the deregistration.  We could have the cache call back into the monitor for any entries flushed as a result of unsubscribe calls.  This could help in specific cases, but won't with the userfaultfd case.

- Sean

**Comment by wzamazon** [comment]
Thanks @shefty for your quick reply!

So this seems to an userfaultd problem. Would having multiple uffd threads help? Say when one threshold is blocked, other threads can keep reading userfaultd events and unblock it.

**Comment by shefty** [comment]
Multiple threads doesn't solve the problem.  The next thread could read an event that's unrelated, go to process it, and block as well.  Forcing the next thread to read an event, etc.  Only now locking could now be the cause of blocking the thread.

You basically need a thread that blocks on userfaultfd, and another thread to process the events.  And the userfaultfd assigned thread must be able to continue reading events.  That's what he have today.

**Comment by shefty** [comment]
I believe the questions for this issue have been answered, even if the answer wasn't what was wanted. :)
