### ISSUE TITLE
Open MPI OFI BTL segfault and FI_DELIVERY_COMPLETE

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#6169]
We have encountered issues utilizing the Open MPI OFI BTL with the Libfabric EFA provider. The OFI BTL requires (and requests) FI_DELIVERY_COMPLETE which EFA does not currently support. Before this, we did not encounter issues incorrectly advertising this capability, however, with this configuration MPI one-sided operations crash due to completions being written too early. This issue is due to the fact that the EFA provider uses bounce buffers when emulating one sided operations. The plan for EFA is to implement true FI_DELIVERY_COMPLETE semantics with a software ack and this resolves the issues we're seeing with the OFI BTL.

The Open MPI community is working on excluding providers that incorrectly advertise FI_DELIVERY_COMPLETE to work around this issue for some upcoming releases. I'd like to start a discussion on whether there are other providers that they will need to exclude. Longer term, I'd like to discuss whether we should consider changes to the Libfabric completion semantics so that we have a better story for MPI.

The Open MPI issue can be found here: https://github.com/open-mpi/ompi/issues/7982

**Comment by shefty** [comment]
I've had several discussions on this.  I don't believe that MPI actually requires delivery complete semantics.  If they did, then it wouldn't work with any existing network implementation.  Of the completion semantics that are defined by libfabric, they can all be met by various implementations.  And all implementations that I'm aware of map to one of the existing semantics.  I don't see a need to define other semantics.

The open MPI issue has been closed.  Is there a specific request here, or are we okay closing this?

**Comment by rwespetal** [comment]
Another semantic that comes to mind is `FI_DELIVERY_COMPLETE` for RMA operations only. Intel MPI uses the same Libfabric endpoint for both send/recv and RMA and so if it asks for delivery complete a provider will potentially have to do a software ack even if it's not needed for send/recv.

**Comment by rwespetal** [comment]
I see, thanks. We'll have to reach out to Intel MPI again to see if they can make this more fine grained so we don't take such a huge performance hit when the EFA provider implements DELIVERY_COMPLETE. I'm not sure they have confirmed yet whether DELIVERY_COMPLETE is actually needed for their RMA algorithms.

**Comment by shefty** [comment]
Well, this specific issue is related to OMPI.  My guess is that having all RMA use delivery complete makes barrier or something trivial.

**Comment by shefty** [comment]
Was EFA updated to support this semantic?  Can this issue be closed?  (The fact that verbs lies about this is a separate issue.)

I don't believe we need new semantics for OFI.

**Comment by rwespetal** [comment]
Yes, this can be closed. We've had a few discussions with the Intel MPI team and long term they plan to only request FI_DELIVERY_COMPLETE for RMA. In the short term, an EFA specific workaround is planned, so if other providers are in a similar situation as EFA (two sided delivery complete requires a software ack), we should see if there is another solution here.
