### ISSUE TITLE
Utility/core provider layering

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#6188]
There's a mechanism to only select core providers that utility providers use to prevent nested layering, but I don't think there is a mechanism for core providers to prevent utility providers from layering on them.

I noticed that there is a list in `ofi_layering_ok()` for shm and sockets. Is it okay if other core providers add themselves to that list? Or should we add a better mechanism in the selection logic?

**Comment by shefty** [comment]
We can expand the known list of providers that should not be layered over.  Is there a specific provider that you have in mind?

I'm not sure how easy it would be to handle this in a more generic fashion.  If there were a way to flag a provider, it could be skipped when a getinfo request was marked with a CORE_ONLY request.  I'm not sure how to flag such providers, since I think we're limited to using the name only.

**Comment by rwespetal** [comment]
Yes, we're considering adding EFA to that list as we aren't currently testing EFA with utility providers. For now, we'd like to eliminate the possibility that EFA is layered over (unless explicitly requested) to avoid the extensive testing required to verify utility providers are functional with EFA.

**Comment by shefty** [comment]
Will any utility provider layer over EFA today?

There is an extension that could be used to convey this information from the provider to libfabric.  When a provider registers with libfabric, there is a struct fi_context field that's passed in.  libfabric stores internal data there.  We could allow the provider to pass in data through the fi_context, but it would only apply if the fi_version were high enough.

Other information that could be useful is a priority value, to allow inserting the provider before others (such as tcp).

**Comment by rwespetal** [comment]
`efa;ofi_rxd` is a valid combination. Due to the provider ordering this option usually isn't selected, but we've encountered a few issues recently when this was selected.

The `fi_context` field during initialization looks good to me, thank you for the suggestion.

**Comment by rwespetal** [comment]
This was handled in PR #6210, closing this issue.
