### ISSUE TITLE
fi_bw fails with shm provider for large message size(30GB)

### ISSUE THREAD

**Issue by dipti-kothari** [ofiwg/libfabric#6203]
Im trying to run fi_bw for large message(30GB) over shm provider. It throw I/O error after some partial reads. Below is a stack trace of the failure

**Server side**:FI_LOG_LEVEL=debug fi_bw -S 32212254720 -e rdm -v -T 1 -p "shm" -s 127.0.0.1
Output:
```
..
<trunc>
libfabric:71294:shm:ep_ctrl:smr_progress_iov():283<warn> partial read occurred
libfabric:71294:shm:ep_ctrl:smr_progress_iov():283<warn> partial read occurred
libfabric:71294:shm:ep_ctrl:smr_progress_iov():283<warn> partial read occurred
libfabric:71294:shm:ep_ctrl:smr_progress_iov():283<warn> partial read occurred
libfabric:71294:shm:ep_ctrl:smr_progress_iov():283<warn> partial read occurred
[error] fabtests:common/shared.c:2494: cq_readerr (Provider errno: 5) : Input/output error

```
**Client side**:FI_LOG_LEVEL=debug fi_bw -S 32212254720 -e rdm -v -T 1 -p "shm" -s 127.0.0.1 127.0.0.1
```
Output:
[error] fabtests:common/shared.c:2494: cq_readerr (Provider errno: 5) : Input/output error
```

Libfaric: ofiwg/master

**Comment by aingerson** [comment]
@dipti-kothari Could you take a look at #6221 and see if it fixes the issue for you?

**Comment by aingerson** [comment]
For the record, I could only test W=1 and W=2 because of memory and time limits. Each 30GB transfer takes ~10 seconds

**Comment by dipti-kothari** [comment]
@aingerson Sure, I will test it. Thanks

**Comment by zhngaj** [comment]
I tested with 2GB and 30GB. But there seems to be a data validation issue.

```
[ec2-user@ip-172-31-9-184 ~]$ /fsx/libfabric/fabtests/install/bin/fi_bw -e rdm -v  -p "shm" -S 2147483648 -W 1 -s 127.0.0.1
Error at iteration=1 size=-2147483648 byte=0
```
```
[ec2-user@ip-172-31-9-184 ~]$ /fsx/libfabric/fabtests/install/bin/fi_bw -e rdm -v  -p "shm" -S 32212254720 -W 1 -s 127.0.0.1
Error at iteration=1 size=-2147483648 byte=0
```

The negative size above is because `ft_check_buf(void *buf, int size)` is using int for argument `size`. The change it to `unsigned long`, but still got the validation error. @aingerson do you have a quick idea?

```
[ec2-user@ip-172-31-9-184 ~]$ /fsx/libfabric/fabtests/install/bin/fi_bw -e rdm -v  -p "shm" -S 2147483648 -W 1 -s 127.0.0.1
Error at iteration=1 size=2147483648 byte=0
```

**Comment by aingerson** [comment]
@zhngaj Ah yes that looks like a bug with fabtests. The size (int both fill_buf and check_buf) should be a size_t and the int i for those as well should be a size_t as well. I will open up a PR for it tomorrow but changing those work for me. Thanks for spotting it!
