### ISSUE TITLE
prov/verbs, shm: libfabric v1.11.0 intel MPI 2020.2 fatal error/segfault

### ISSUE THREAD

**Issue by MatthAlex** [ofiwg/libfabric#6204]
When using Intel Parallel 2020.2 and libfabric v1.11.0 the following leads to a fatal error (or segfault sometimes): 
```bash
$ mpirun -np 2 IMB-MPI1
```
Other tested versions include v1.10.0 and Intel-provided 1.10.1-impi and tested fine. Verbose logs w/ `debug` build were enabled for v1.11.0.

Successful on `dn` node, v1.10 and `shm`: [libf1_10_Intel2020p2_dn_shm.txt](https://github.com/ofiwg/libfabric/files/5117717/libf1_10_Intel2020p2_dn_shm.txt)
Successful on `sdv` node, v1.10 and `shm`: [libf1_10_Intel2020p2_sdv_shm.txt](https://github.com/ofiwg/libfabric/files/5117718/libf1_10_Intel2020p2_sdv_shm.txt)
Successful on `sdv` node, v1.10 and `verbs`: [libf1_10_Intel2020p2_sdv_verbs.txt](https://github.com/ofiwg/libfabric/files/5117719/libf1_10_Intel2020p2_sdv_verbs.txt)

Failure (fatal error) on `dn` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_dn.txt](https://github.com/ofiwg/libfabric/files/5117720/libf1_11_Intel2020p2_dn.txt)
Failure (segfault) on `dn` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_dn2.txt](https://github.com/ofiwg/libfabric/files/5117721/libf1_11_Intel2020p2_dn2.txt)
Failure (fatal error) on `sdv` node, v1.11 and `shm,verbs`: [libf1_11_Intel2020p2_sdv.txt](https://github.com/ofiwg/libfabric/files/5117722/libf1_11_Intel2020p2_sdv.txt)

Environment used:
```bash
export FI_PROVIDER="shm,verbs"
export FI_VERBS_IFACE=ib0
export I_MPI_HYDRA_TOPOLIB=ipl
export FI_LOG_LEVEL=debug
export I_MPI_DEBUG=6
```

**Comment by aingerson** [comment]
The shm issue seems to be a problem with Intel MPI not properly filtering out unneeded capabilities. In 1.11 shm added FI_HMEM which is causing a mismatch in support. So it looks like until that's fixed in Intel MPI, the 1.11 OFI shm provider is not compatible with Intel MPI.
Not sure about the segfault/verbs issue but I'll look into it.
Could you confirm that the same issue is present when FI_PROVIDER="verbs" ? If so, could you provide the logs for that?
Thank you!

**Comment by aingerson** [comment]
Also could you clarify what "dn node" and "sdv node" mean?

**Comment by MatthAlex** [comment]
The nodes are just names for different architectures and configurations. Dn are older, shm-only, nodes, while sdv are connected over IB.
[dn cpuinfo.txt](https://github.com/ofiwg/libfabric/files/5193901/dn.cpuinfo.txt)
[sdv cpuinfo.txt](https://github.com/ofiwg/libfabric/files/5193939/sdv.cpuinfo.txt)

Interestingly, the segfault shows up on a dn node, after enabling both verbs and FI_LOG_LEVEL to any value.
[verbs-LOG_LEVEL=debug.txt](https://github.com/ofiwg/libfabric/files/5194022/verbs-LOG_LEVEL.debug.txt)
[verbs-LOG_LEVEL=info.txt](https://github.com/ofiwg/libfabric/files/5194023/verbs-LOG_LEVEL.info.txt)
[verbs-LOG_LEVEL=null.txt](https://github.com/ofiwg/libfabric/files/5194024/verbs-LOG_LEVEL.null.txt)
[shm-FI_LOG_LEVEL=debug.txt](https://github.com/ofiwg/libfabric/files/5194027/shm-FI_LOG_LEVEL.debug.txt)

**Comment by ddurnov** [comment]
@MatthAlex Thanks! Do you see the issues on the nodes with providers shipped as part of Intel MPI distribution? Right now Intel MPI 2019 U8 is aligned to libfarbic 1.10.1

**Comment by aingerson** [comment]
@ddurnov @MatthAlex I've opened a pull request with a fix for the shm issue here - #6257. I'll cherry-pick this into the v1.11.x branch once it's merged.
The verbs failure looks like a simple seg fault in the debug print which was added recently. I'll look into a workaround for that and reference it here once I have one.

**Comment by aingerson** [comment]
See #6258 for verbs fix

**Comment by aingerson** [comment]
This should be fixed in the master branch, but I just opened a PR for the 1.11.x branch with these fixes. @MatthAlex Could you give PR #6261 or my 1_11 branch (https://github.com/aingerson/libfabric/tree/1_11) a try to make sure it resolved your issues?
