### ISSUE TITLE
No fabtests seem to run out-of-the-box on the NetDirect provider

### ISSUE THREAD

**Issue by ericgross2** [ofiwg/libfabric#6213]
The Microsoft-provided NetDirect tests seem to be working perfectly on my system. However, when I try to run any of the tests with libfabric, they either fail due to them exercising code paths/modes not supported by the NetDirect provider, or I seem to get hangs spinning waiting on the completion queues (on both TX and RX sides). I haven't found any combination of arguments for the tests yet that allow any of them to work via NetDirect, so either the documentation could give some better hints, or there is a bug somewhere.

**Comment by shefty** [comment]
FWIW, we only ever run CI over the tcp, sockets, and udp providers on windows.  (My team does not have the HW/SW for this installed anywhere.)  Intel MPI will run over NetworkDirect, but I don't know if they try running fabtests.  I doubt it.

But I would have expected the tests to work.  Are you able to see the provider show up when running fi_info test?

What version of the library are you using?

**Comment by ericgrossNI** [comment]
Hi Shefty,

Thanks for the quick response! That's good to know that this isn't part of your normal testing. It seems unfortunate. I'd have hoped that if Intel is supporting using NetDirect via Intel MPI (presumably supporting RDMA on their own NICs) that they would have an interest in making sure libfabric's CI covers NetDirect as at this lower layer too.

Regarding your questions:

-I'm using the master branch from github. I pulled commit 60a1d74e32dde2fc3612650941c828cbdd9b4f3 from August 13th, so pretty recent.

-Yes, the provider shows up. Both "netdir" and "netdir;ofi_rxm". 

I can get some of the simple tests like "msg" (from fabtests) and "fi_pingpong" to sort of work, in that they will connect on both ends. However, they simple then spin on waiting for the CQs (both the TX and RX side). The callback for completion seems to never come in to unblock them. They both have a number of different options that control their behavior, and I know the netdir provider doesn't implement everything, so I was hoping that maybe there is some combination of settings I should be passing that would actually demonstrate it working.
