### ISSUE TITLE
Libfabric zero length memory registration

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#6245]
We're tracking a bug where Intel MPI tries to register a zero length buffer for [MPI_Win_create](https://www.mpich.org/static/docs/v3.2.x/www3/MPI_Win_create.html). The EFA device rejects this request and the collective operation fails. This is legal MPI behavior but I'm wondering if Libfabric has any rules around whether zero length registrations are allowed?

**Comment by shefty** [comment]
I don't think there's any formal rule defined for this.  There is an intent to support 0-length transfers, including RMA writes (carrying CQ data for example).  For that, I don't believe there are any statements indicating that the memory key needs to be valid or is ignored.

I remember this problem showing up before, but I can't recall the context or what was done.  I'll see if I can find some clue.

**Comment by rwespetal** [comment]
Thanks for taking a look. Right, an RMA write with CQ data seems like a legitimate use case.

**Comment by rwespetal** [comment]
If it helps we looked at what the behavior is for verbs. I'm not seeing anything in rdma-core to enforce that MR length is at least one byte, but the mlx5 driver does return an error when there are no pages backing an MR. In addition, the IB spec states: "11.2.8.2 REGISTER MEMORY REGION: Virtual Address - the address of the first byte of the region to be
registered. The Maximum size of a Virtual Address is 64 bits." which implies that registrations should be at least one byte.

Regardless, we could still decide to support this via the Libfabric API. Or follow up with Intel MPI on what the purpose of this registration is. We can handle this case within the EFA provider, especially since RMA writes are already emulated as the device doesn't support them. For devices that do support write with immediate it could still be possible to handle this in software but it might be tricky to deal with the ordering guarantees, if the provider advertises them.

**Comment by shefty** [comment]
I searched through the code, but couldn't figure out where this problem had come up in the past or how it was handled.  IMO, a 0-length registration is goofy.  I think we need to follow up with Intel MPI here, and figure out how they are working with other providers.

**Comment by rwespetal** [comment]
Thanks, that works for me. Let me know if you want me to reach out to that team or if you plan to do that.

**Comment by shefty** [comment]
I will reach out, but it will have more attention coming from a customer too.
