### ISSUE TITLE
prov/verbs: connection establishement with AF_IB requires IPoIB and IP links to be up

### ISSUE THREAD

**Issue by sydidelot** [ofiwg/libfabric#6247]
I have implemented the PR #5605, which provides a way to establish connections using native Infiniband addresses (AF_IB).
I wrote that PR based on the requirement to use Libfabric even if IPoIB is not available on the node. 

While testing the PR, I figured out that IPoIB is still required to establish connection using native Infiniband addresses.

I have a setup of 2 nodes connected with 1x `Mellanox Technologies MT27700 Family`. Both nodes run Ubuntu 18.04.04 with kernel `4.15.0-88-generic`.

If IPoIB is disabled on both nodes (`modprobe -r ib_ipoib`), libfabric/fabtest fails in the client with the following output:

**Server:**
```
$ fi_msg_bw -s [fe80::248a:703:1c:dc0d]:0xffff:0x13f:0x0 -e msg -p verbs -F fi_sockaddr_ib
```

**Client:**
```
$ fi_msg_bw -e msg -p verbs -F fi_sockaddr_ib [fe80::248a:703:1c:dc0d]:0xffff:0x13f:0x0
[error] fabtests:common/shared.c:2491: eq_readerr (Provider errno: -28) : Unknown error -28
```

The provider errno 28 reported by the client corresponds to the RDMACM error: `IB_CM_REJ_CONSUMER_DEFINED`.

If I enable IPoIB (`modprobe ib_ipoib`) and make sure that all the IP interfaces are UP (`for i in $(ip link list |grep ib |grep mtu |awk '{print $2}' |sed 's/://') ; do sudo ip link set $i up ; done`),  the client is able to connect and the test successfully completes:

**Client:**
```
$ fi_msg_bw -e msg -p verbs -F fi_sockaddr_ib [fe80::248a:703:1c:dc0d]:0xffff:0x13f:0x0
bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
64      20k     1.2m        0.02s     59.86       1.07       0.94
256     20k     4.8m        0.01s    536.41       0.48       2.10
1k      20k     19m         0.01s   2634.08       0.39       2.57
4k      20k     78m         0.01s   6925.35       0.59       1.69
64k     2k      125m        0.01s  11394.59       5.75       0.17
1m      200     200m        0.02s  10817.87      96.93       0.01
```

Another interesting finding is that the RDMACM error `IB_CM_REJ_CONSUMER_DEFINED` is also thrown when IPoIB is installed, but the corresponding IP interfaces are DOWN:

```
$ for i in $(ip link list |grep ib |grep mtu |awk '{print $2}' |sed 's/://') ; do sudo ip link set $i down ; done
$ fi_msg_bw -e msg -p verbs -F fi_sockaddr_ib [fe80::248a:703:1c:dc0d]:0xffff:0x13f:0x0
[error] fabtests:common/shared.c:2491: eq_readerr (Provider errno: -28) : Unknown error -28
```

The workaround that I found for the issue is to set the `ip_version` in the RDMACM header to 0 (CM REQ message). 
As long as the ip_version field is set to 6, the kernel seems to expect to find a valid IP interface that corresponds to the destination GID. 

I had a look at `drivers/infiniband/core/cma.c` in the kernel (I'm looking at master branch, whereas my setup is based on older 4.15 kernel but I believe that's a more generic problem that impacts all kernel versions). I'm not 100% sure but I think the following call chain seems to be executed when a connection request is received:
```
cma_ib_id_from_event()
    cma_get_net_dev()
        cma_save_ip_info()
            cma_get_ip_ver()
```

If `cma_save_ip_info()` detects IPv6, `cma_get_net_dev()` returns a valid `struct net_device *` but later expects that device to be UP: https://github.com/torvalds/linux/blob/master/drivers/infiniband/core/cma.c#L1685

If the IP version is != 4 and != 6, `cma_save_ip_info()` returns `-EAFNOSUPPORT` and `cma_ib_id_from_event()` later assumes that AF_IB is used: https://github.com/torvalds/linux/blob/master/drivers/infiniband/core/cma.c#L1654
In this case, `struct net_device *` is NULL and the code doesn't expect any IP interface to be UP.

Another point that makes me think that we shouldn't set the IP version in the CMA header is the function `cma_format_hdr()`: https://github.com/torvalds/linux/blob/master/drivers/infiniband/core/cma.c#L3741
That function doesn't set the CMA header if the address family is AF_IB.

@shefty, would you please provide your insights to that problem? I believe you are the best person to undersand and to figure out what is the best approach for that issue :)

Thanks for your help!

**Comment by shefty** [comment]
I would have though ip_version = 6 would work for a GID, since a GID is defined as an IPv6 address (even though it's really not).  Since there's no decent option for a GID, if 0 works, that seems like as good an option as any other for now.

**Comment by sydidelot** [comment]
@shefty Thanks for your reply and sorry for the long delay in my reply. I finally found the time to push the patch to Github.
