### ISSUE TITLE
[Question: verbs/domain/mr] Multiple nodes build chains in pairs, how to register memory to use WRITE mode?

### ISSUE THREAD

**Issue by CharlesJhonson** [ofiwg/libfabric#6259]
Hello:
I am building an RDMA network with multiple nodes (multiple machines), as shown in the figure:

![Snipaste_2020-09-18_17-45-43](https://user-images.githubusercontent.com/40120262/93583840-08413f00-f9d7-11ea-9491-745f70937060.jpg)

A, B, and C three nodes build a chain with each other, and each node is both a client and a server.
Node A has public data (public memory) that needs to be sent to nodes B and C at the same time. The current idea is to register public memory to two links (A<--->B, A<--->C), and execute Remote WRITE command.

Now, the question I want to ask is:
Can two connections (client or server) of node A share the memory region of a domain? In this case, there is no need to register the same block of memory (the memory of node A) to the domains of the two links (A<--->B, A<--->C).

I think that links with the same verbs behavior on the same RNIC should share the same domain, but I did not find a similar implementation code.

Thank you for taking the time to pay attention to this issue.

**Comment by shefty** [comment]
Yes, the same memory region can be used with multiple connections.  The connections need to be part of the same libfabric domain.

**Comment by CharlesJhonson** [comment]
> Yes, the same memory region can be used with multiple connections. The connections need to be part of the same libfabric domain.

@shefty  OK, thanks for your answer.
I don't know how to use libfabric to realize "client connection and server new connection share the same domain and MR". Are there any code examples  for relevant implementations? Thank you very much

**Comment by shefty** [comment]
What you show in your pseudo-code is correct.  As long as you maintain a single publicDomain, the MR can be used with any endpoints that are also associated with it.

**Comment by CharlesJhonson** [comment]
> What you show in your pseudo-code is correct. As long as you maintain a single publicDomain, the MR can be used with any endpoints that are also associated with it.

Ok, thank you very much, I will try to verification that. And, report the result in here.
