### ISSUE TITLE
Redefine FI_ENOKEY back to ENOKEY

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#628]
Commit fe95f6464813ce6161d76f57446aaced2e7ad932 change the definition of FI_ENOKEY from ENOKEY to a constant value.  On Linux, this results in two different errno values having the same meaning.  Rather than defining FI_ENOKEY to a constant, we could instead define it to ENOKEY, with BSD and OS-X defining ENOKEY.

@bturrubiates @jsquyres - If this makes sense, I can make this change.

**Comment by bturrubiates** [comment]
I'm not sure I follow. Do you mean defining FI_ENOKEY using ENOKEY provided by errno in a Linux environment and using a constant value for FI_ENOKEY on Mac/BSD?

**Comment by shefty** [comment]
I was wanting to add:

define ENOKEY 512

to osx/osd.h.  But thinking about this, this doesn't work as well as I would like.  fi_errno.h is exposed to the user, so the osd.h file would need to be exposed as well.

**Comment by shefty** [comment]
Dropping this.  I can't come up with a workable solution that's better than what we have.
