### ISSUE TITLE
EFA provider and rdma-core fork support

### ISSUE THREAD

**Issue by rwespetal** [ofiwg/libfabric#6332]
The Libfabric EFA provider currently does not support applications calling `fork()` when memory registrations are handled by the EFA provider. This is to prevent applications from encountering potential data corruption or crashes when operating in this mode. Most applications, including the majority of MPI and NCCL applications, will still function with this constraint. Some NCCL applications do require `fork()` support, however, these applications do not require memory registrations to be handled by the EFA provider. We plan to address this bug in a future release and will update this GitHub issue when a release is available where this is resolved.

If you are seeing this error message please refer to the scenarios below where you may encounter this error:

1) You are running an MPI application.

For all MPI implementations: verify that the environment variables to enable fork support are not set, for example `env | egrep 'IBV_FORK_SAFE|RDMAV_FORK_SAFE'` should return no matches.

If you are using Open MPI 4.x: your build may have verbs support enabled. Please add `--without-verbs` to your Open MPI configure flags when building Open MPI for use on Amazon EC2. If you are using a pre-compiled version of Open MPI please add `--mca btl ^openib` to your `mpirun` arguments or set the `OMPI_MCA_btl_base_exclude=openib` environment variable when running on Amazon EC2.

2) You are running a NCCL application. Please refer to the [EFA NCCL documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start-nccl.html) for more information.

**Comment by wzamazon** [comment]
We merged this https://github.com/ofiwg/libfabric/pull/6610 and back ported it to v1.12.x and  v1.11.x branch. With this change, EFA user can use fork by setting the environment variable FI_EFA_FORK_SAFE=1.
