### ISSUE TITLE
sockets provider: server gets invalid port number on client fi_getinfo(version, NULL, NULL, ...)

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#634]
If the client calls `fi_getinfo()` with:
```C
struct fi_hints hints;
memset(&hints, 0, sizeof(hints));
hints.caps = FI_MSG|FI_RMA|FI_REMOTE_CQ_DATA;
hints.mode = FI_LOCAL_MR|FI_PROV_MR_ATTR;
hints.ep_type = FI_EP_MSG;
hints.addr_format = FI_SOCKADDR;
hints.dest_addr = my_dest_addr;
hints.dest_addrlen = my_dest_addrlen;
ret = fi_getinfo(FI_VERSION(1, 0), NULL, NULL, 0, &hints, &info);
```

the hints structure comes back with `src_addr` containing a valid IP address but a port number of 0.  This is probably fine for the purposes of `fi_getinfo()`, but the 0 port number then gets propagated to the server, and then the server cannot map its connection back to the client when the server wants to start sending data on the connection.  Additionally, the result of `fi_getpeer()` on the server will also contain a port number of 0 (meanwhile, `fi_getname()` on the client gives the correct port number).  I expect that the server will receive the ephemeral port number that the client was assigned, not 0.

**Comment by shefty** [comment]
Can you clarify the problem more?  For fi_getinfo, it the app does not specify a port number, then none should be assigned by the provider.  This seems correct to me.  Once an endpoint has been allocated, fi_getname() should return the correct port information.  Is this not happening?  Is fi_getpeer() returning the incorrect peer address?

**Comment by patrickmacarthur** [comment]
It's `fi_getpeer()` on the remote side that is getting the incorrect address (with a port number of 0).

**Comment by patrickmacarthur** [comment]
Also, any attempt by the application to send data from the server to the client fails because the provider attempts to establish a connection to port 0 on the client.

**Comment by shefty** [comment]
I have pingpong tests working over connected endpoints.  So there is something else going on that I'm still not understanding.

**Comment by patrickmacarthur** [comment]
Are you setting node/service to NULL in your tests?  If that is the case, I'll have to take a closer look at it tomorrow and figure out what the difference is.

**Comment by shefty** [comment]
The tests likely do not.  It sounds like there may just be some missing implementation pieces in the sockets provider then.
