### ISSUE TITLE
Unconnected endpoint vs Connectionless endpoint

### ISSUE THREAD

**Issue by VoVAllen** [ofiwg/libfabric#6346]
Hi,

On the https://ofiwg.github.io/libfabric/v1.11.1/man/fi_endpoint.3.html, there's two phrase unconnected vs conectionless. Do they mean the same thing?

Thanks.

**Comment by shefty** [comment]
Yes - these are being used to refer to the same type of endpoints.  Though I will update the page to use connectionless, since the term unconnected could be used in reference to the state of a connected endpoint.

**Comment by VoVAllen** [comment]
Thanks!
