### ISSUE TITLE
prov/verbs: Issue with verbs provider fabric naming

### ISSUE THREAD

**Issue by lradeke** [ofiwg/libfabric#6365]
Libfabric uses ibv_query_gid() to define the verbs provider fabric name with the GID subnet prefix. Currently, the GID index is hardcoded to 0, and therefore only returns GID[0] subnet prefix. This results in fi_info only returning the following fabric attribute output, regardless of which device it queries:
```
fi_info -p 'verbs;ofi_rxm' | grep fabric
    fabric: IB-0xfe80000000000000
``` 
This implies that all devices queried reside on the same fabric, and may result in applications using the wrong endpoints during communication.

The following modifications to the verbs_info.c file replace the hardcoded 0 with `vrb_gl_data.gid_idx` and introduce a switch case to add a RoCEv1 or v2 prefix where appropriate:
```
switch (ctx->device->transport_type) {
case IBV_TRANSPORT_IB:
        if (ibv_query_gid(ctx, 1, vrb_gl_data.gid_idx, &gid)) {
                VERBS_INFO_ERRNO(FI_LOG_FABRIC,
                                 "ibv_query_gid", errno);
                ret = -errno;
                goto err;
        }

        if (ibv_query_gid_type(ctx, 1, vrb_gl_data.gid_idx, &gid_type)) {
                VERBS_INFO_ERRNO(FI_LOG_FABRIC,
                                 "ibv_query_gid_type", errno);
                ret = -errno;
                goto err;
        }
        switch (gid_type) {
        case IBV_GID_TYPE_IB_ROCE_V1:
                name_len = strlen(VERBS_ROCEV1_PREFIX) + INET6_ADDRSTRLEN;
                if (!(fi->fabric_attr->name = calloc(1, name_len + 1))) {
                        ret = -FI_ENOMEM;
                        goto err;
                }

                snprintf(fi->fabric_attr->name, name_len,
                         VERBS_ROCEV1_PREFIX "%" PRIx64,
                         be64toh(gid.global.subnet_prefix));
                break;
        case IBV_GID_TYPE_ROCE_V2:
                name_len = strlen(VERBS_ROCEV2_PREFIX) + INET6_ADDRSTRLEN;
                if (!(fi->fabric_attr->name = calloc(1, name_len + 1))) {
                        ret = -FI_ENOMEM;
                        goto err;
                }

                snprintf(fi->fabric_attr->name, name_len,
                         VERBS_ROCEV2_PREFIX "%" PRIx64,
                         be64toh(gid.global.subnet_prefix));
                break;
        default:
                name_len = strlen(VERBS_IB_PREFIX) + INET6_ADDRSTRLEN;
                if (!(fi->fabric_attr->name = calloc(1, name_len + 1))) {
                        ret = -FI_ENOMEM;
                        goto err;
                }

                snprintf(fi->fabric_attr->name, name_len,
                         VERBS_IB_PREFIX "%" PRIx64,
                         be64toh(gid.global.subnet_prefix));
        }
        break;
```
Now, the fi_info output for GID indices 0, 1, 2, and 3 respectively are as follows:
```
    fabric: RoCEv1-fe80000000000000
    fabric: RoCEv2-fe80000000000000
    fabric: RoCEv1-0
    fabric: RoCEv2-0
```
While this solves the main naming problem, it is desirable for the RoCEv2 output to print the IPv4 address. With Mellanox RoCE, this is GID[3]. The ideal fi_info output would be as follows:
```
    fabric: RoCEv1-fe80000000000000
    fabric: RoCEv2-fe80000000000000
    fabric: RoCEv1-0000000000000000
    fabric: RoCEv2-xx.xx.xx.xx/xx
```
Is there a way that I may be able to specifically reconstitute the last 4 bytes of the GID, from which I can translate the IPv4 address from?

**Comment by lradeke** [comment]
@jswaro @shefty @a-ilango

**Comment by shefty** [comment]
A global gid index will not work with multiple devices, or even multiple ports, and is not ideal anyway from the perspective of anyone trying to use the interface.

For IB/RoCEv1, the code could search the GIDs to pick the best option.  Maybe there's something better than 0xfe00:: to choose from.  Using RoCEv1 instead of IB for RoCE ports seems reasonable.

The query_gid_type function is not available on all versions of libibverbs.  For RoCEv2, we could use IP addresses directly.  I'm guessing the code already discovers the IP addresses in order to return a source address, and that it goes through a different path to obtain that data, rather than trying to read GIDs.
