### ISSUE TITLE
[fabtests] question about pre-posted receive buffer

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6372]
While reading the fabtest code, I noticed that on receive side there is an assumption that a receive buffer was posted at the beginning.

For example, in ```ft_rx```, the code will first wait for a rx completion, then call ft_post_rx() to post receive buffer.

in ```bw_rx_comp```  instead of waiting for all outstanding RX to complete, the code wait for ```rx_seq - 1``` and there is a comment  ```/* rx_seq is always one ahead */ ```

I wonder why the code is implemented this way, and whether this would cause problem?

For example, ```ft_sync``` call ```ft_rx``` to do syncing. For the purpose of syncing, the RX operation posted by ```ft_rx``` should be completed, but it is not.

**Comment by shefty** [comment]
The code assumes pre-posted buffers, which is how most apps are expected to behave.  The posting of the receive buffer in ft_rx() is the re-posting of the buffer after the incoming message was received.  (Without the pre-posting of the buffers, the tests would hit flow control with receiver not ready NAKs.)

I do not know the story behind bw_rx_comp() and the comment there.

**Comment by wzamazon** [comment]
I am not sure I understand why ft_rx() should assume pre-posted buffers. 

From the perspective of ft_sync, ft_rx should be a blocking receive (like ft_tx() implements blocking send), e.g. upon return of ```ft_rx```. The data has been received. But it is not that case, so is ft_sync not getting what it wants?

**Comment by shefty** [comment]
The tests all assume that receive buffers are pre-posted.  Otherwise, every send will race with posting the receive, resulting in flow control backing off the send, which can greatly impact measured latency.

**Comment by wzamazon** [comment]
Thank you! I understand now.
