### ISSUE TITLE
Question about fi_domain usage

### ISSUE THREAD

**Issue by VoVAllen** [ofiwg/libfabric#6403]
Hi,

Is domain different when calling `fi_domain` for the same `fid_fabric`? For example, if I created two domain from duplicated fi_info, will they be the same one or two duplicated one? 

If its hard to explain, could you use `udp` RDM endpoint as an example, does fi_domain/fi_endpoint mean a port or a nic? 

Thanks a lot!

**Comment by VoVAllen** [comment]
If I created two completion queues from two duplicates domain and bind to two endpoints, will the event be shared between two completion queues?

**Comment by shefty** [comment]
Calling fi_domain() opens a different instance of a domain.  There's not necessarily a 1:1 mapping from a domain to a specific hardware component, but it's most closely associated with a NIC.  However, even if 2 domains map to the same NIC, there are restrictions on trying to share resources between domains.  For example, to attach an endpoint to a CQ they must share domains.  Likewise, if you register memory on domain 1, endpoints on domain 2 cannot access the registered region.

For your second post, if you have 2 domains, and each domain has 1 endpoint and one completion queue, completion events will not be shared.  Endpoint 1 will write events to CQ 1, and endpoint 2 will write events to CQ 2.  Attempting to bind endpoint 1 to CQ 2 will fail.

In the case of udp, an endpoint maps to a socket.

**Comment by VoVAllen** [comment]
Thanks!
