### ISSUE TITLE
Question about completion queue and sending message

### ISSUE THREAD

**Issue by VoVAllen** [ofiwg/libfabric#6411]
Hi,

I found sometimes receiver cannot receive the data without doing `fi_cq_read` at the sender side. 
For example:
Sender: `fi_tsend(...)`
Receiver: `fi_trecv(...)` and `fi_cq_read` in another thread
The scenario above cannot deliver the message to the receiver successfully. Unless I add `fi_cq_read` at the sender side after the `fi_tsend` command. Is this expected? 
I'm using RDM endpoint and I found this problem exists for both `efa` and `udp`, but not for RDM over `tcp`. I suspect this is due to the unsuccessful sending at the first time, and the retrying would only be triggered by `fi_cq_read` at the transmit completion queue, am I right? 

Thanks in advance for your precious time!

**Comment by shefty** [comment]
This is expected, and usually deals with how progress is driven.

As an example, for EFA and UDP, large messages are broken up into mtu sized transfers.  A flow control mechanism layers over that to prevent flooding at the receiver.  Some number of packets will be transferred to the receiver, which will respond by sending credits for additional packets.  The sender will be blocked until it receives that credit message, allowing more packets to flow.

The fi_cq_read() is used to drive the progress in this case.  The application thread ends up reading the credit message and sending more packets.  The thread may also check for packets that have timed out and need to be retransmitted, as you mentioned.

rxm over tcp have a similar requirement when progress is set to manual.  However, in the case of tcp, this is a result of using different protocols to transfer large messages (e.g. > 128k), versus small.

**Comment by VoVAllen** [comment]
Thanks! I think this should be added to documentation also, because it's a bit counter intuitive for the newbie from using socket (such as me). I used to think the send will be done by the nic anyway once the send event is issued. 

Is `fi_cq_read` needed only for the first transmission or needed for every send event to drive the real send progress?

**Comment by VoVAllen** [comment]
Thanks a lot. The concept of progress is too abstract in the domain context (at least for me), that I cannot link it with send event until you pointed out. It's vague for a newbie to understand what's a progress mean, since there would be many progresses to be done in the whole procedure.
