### ISSUE TITLE
FI_DIRECTED_RECV with SEP

### ISSUE THREAD

**Issue by ztiffany** [ofiwg/libfabric#6429]
How should FI_DIRECTED_RECV work with Scalable Endpoints? Specifically, should a TX context ID be placed in the src_addr of a Receive operation and be used to match to a Send from a specific TX context? Or, is TX context ID ignored for the purposes of source address matching?

**Comment by shefty** [comment]
The matching is limited to the transport level address, which is what ends up being inserted into the AV.  The Tx ID is not part of the matching.

I don't believe there are any APIs that allow creating a src_addr such that it includes the Tx ID.  (Unlike the ability to create a dest_addr that does include the Rx ID).
