### ISSUE TITLE
fi_mr_reg failed, ret is:-12, Cannot allocate memory

### ISSUE THREAD

**Issue by CharlesJhonson** [ofiwg/libfabric#6437]
Hi,
I have a problem when using lbfabric. What are the reason?

//All return 0 whtn  get info, fabric, domian, buf failed when fi_reg_mr.  Error info is "fi_mr_reg failed, ret is:-12, Cannot allocate memory".
/// Satrt as a client, get the fi_info as follow
   caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [  ]
    addr_format: FI_SOCKADDR_IN
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: fi_sockaddr_in://192.168.100.61:0
    dest_addr: fi_sockaddr_in://192.168.100.62:7802
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_LOCAL_COMM, FI_REMOTE_COMM ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_STRICT ]
        inject_size: 256
        size: 384
        iov_limit: 4
        rma_iov_limit: 1
    fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_LOCAL_COMM, FI_REMOTE_COMM ]
        mode: [ FI_RX_CQ_DATA ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_RAS, FI_ORDER_WAW, FI_ORDER_WAS, FI_ORDER_SAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_STRICT, FI_ORDER_DATA ]
        total_buffered_recv: 0
        size: 384
        iov_limit: 4
    fi_ep_attr:
        type: FI_EP_MSG
        protocol: FI_PROTO_RDMA_CM_IB_RC
        protocol_version: 1
        max_msg_size: 1073741824
        msg_prefix_size: 0
        max_order_raw_size: 1073741824
        max_order_war_size: 0
        max_order_waw_size: 1073741824
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: mlx4_0
       threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_AUTO
        data_progress: FI_PROGRESS_AUTO
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 4
        cq_data_size: 0
        cq_cnt: 65408
        ep_cnt: 131000
        tx_ctx_cnt: 1024
        rx_ctx_cnt: 1024
        max_ep_tx_ctx: 1024
        max_ep_rx_ctx: 1024
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 65472
        cntr_cnt: 0
        mr_iov_limit: 1
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 255
        mr_cnt: 524032
    fi_fabric_attr:
        name: IB-0xfe80000000000000
        prov_name: verbs
        prov_version: 1.0
        api_version: 1.5
    fid_nic:
        fi_device_attr:
            name: mlx4_0
            device_id: 4103
            device_version: 0
            vendor_id: 713
            driver: (null)
            firmware: 2.42.5000
        fi_bus_attr:
            fi_bus_type: FI_BUS_UNKNOWN
        fi_link_attr:
            address: (null)
            mtu: 4096
            speed: 33554432
            state: FI_LINK_UP
            network_type: InfiniBand
///Hints
	fiHints->ep_attr->type = FI_EP_MSG;
	fiHints->caps = FI_MSG | FI_RMA;
	fiHints->mode = FI_CONTEXT;
	fiHints->domain_attr->mr_mode = FI_MR_LOCAL | FI_MR_ALLOCATED
			| FI_MR_PROV_KEY | FI_MR_VIRT_ADDR;
	fiHints->fabric_attr->prov_name = "verbs";

**Comment by shefty** [comment]
This is likely an error in the application.  Have you been able to resolve the issue?

**Comment by CharlesJhonson** [comment]
Not yet.

**Comment by j-xiong** [comment]
It could be system memlock limit. This can be checked with "ulimit -l" and can be set in /etc/security/limits.conf.
