### ISSUE TITLE
fi_mr_reg read-only region with verbs;ofi_rxm provider

### ISSUE THREAD

**Issue by svalat** [ofiwg/libfabric#6467]
Hi,
I would like to register a read-only region with only FI_REMOTE_READ by using the verbs;ofi_rxm provider.

```
int ret = fi_mr_reg(domain, ptr, size, FI_REMOTE_READ, flags,0, 0, &(region.mr), NULL);
LIBFABRIC_CHECK_STATUS("fi_mr_reg",ret);
```

In the current state I got an error -14 (Bad address).

```
Fatal : Libfabric get failure on command fi_mr_reg with status -14 : Bad address
```

I gdb and look in the libfabric code and found this :
https://github.com/ofiwg/libfabric/blob/v1.11.1/prov/verbs/src/verbs_mr.c#L221

```
	return vrb_mr_reg_common(md, IBV_ACCESS_LOCAL_WRITE |
			IBV_ACCESS_REMOTE_WRITE | IBV_ACCESS_REMOTE_ATOMIC |
			IBV_ACCESS_REMOTE_READ, entry->info.iov.iov_base,
			entry->info.iov.iov_len, NULL, entry->info.iface,
			entry->info.device);
```

So in the current state it ignores my protection flags and force read/write registration which explain my failure.

It there a way to proceed ?

Thanks in advance.

**Comment by svalat** [comment]
OK, this is related to the mr cache. There is another call on https://github.com/ofiwg/libfabric/blob/master/prov/verbs/src/verbs_mr.c#L156.

I tried to disable cache by using without much success I still get :

```
FI_MR_CACHE_MONITOR=disabled ./src/server/iocatcher-server 10.1.3.85
```

**Comment by svalat** [comment]
Ok, now it comes from local mr automation:
https://github.com/ofiwg/libfabric/blob/v1.11.1/prov/rxm/src/rxm_domain.c#L226

**Comment by shefty** [comment]
I need to understand the reason why rxm_mr_get_msg_access() is modifying the MR access.  At first look, my guess is that it's assuming that the user is registering for FI_SEND access, since send operations could be implemented using RMA read rendezvous.  If the user only specifies FI_REMOTE_READ, it looks like a bug to change it.

**Comment by svalat** [comment]
Ok, I made a mistake in my previous message, the issue comes from https://github.com/ofiwg/libfabric/blob/v1.11.1/prov/rxm/src/rxm_domain.c#L223 due to FI_READ being added to the access flags in any case. It explains why it didn't fix to use FI_LOCAL_MR on domain setup.

**Comment by shefty** [comment]
I was actually looking at the code in the master branch, which makes this problem worse.  Thanks for the references

**Comment by shefty** [comment]
PR #6472 is intended to fix this.  The PR is still under testing

**Comment by shefty** [comment]
Can you verify if PR #6472 fixes this problem for you?

**Comment by svalat** [comment]
Yes I will check, thanks. 
Sorry for the delay I didn't checked my emails.

**Comment by svalat** [comment]
I made a test this morning and it's working properly with your version and environnement variable `FI_MR_CACHE_MONITOR=disabled `. Thanks.

**Comment by shefty** [comment]
Thanks for reporting this.
