### ISSUE TITLE
define FI_ORDER_RECV

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#652]
The flag FI_ORDER_RECV is present in fabric.h, but not yet fully defined.

Sean said the following in an offline discussion:

> This is a placeholder at the moment to indicate that received message buffers are completed in the order that they are posted, or matched for tagged messages. The receive side has to know in what order, if any, their buffers will be consumed/completed.  E.g. existing apps rely on posted receives operating as a queue.  The multi-recv case needs clearer definition.

We need to put the definition in the man pages.

**Comment by shefty** [comment]
definition removed
