### ISSUE TITLE
rdm-rma-event test does not give completion on server side when using completion queues

### ISSUE THREAD

**Issue by upendrapatwardhan** [ofiwg/libfabric#6521]
In the rdm-rma-event.c the following change was done
-- opts.options = FT_OPT_SIZE | FT_OPT_RX_CNTR | FT_OPT_TX_CNTR;
++ opts.options = FT_OPT_SIZE | FT_OPT_RX_CQ | FT_OPT_TX_CQ;

After running the test, I was not able see the completion on the server side (for the FI_REMOTE_WRITE event).
Is this the expected behavior? Or do I need to have some additional configuration for getting the completion using the completion queues?

**Comment by shefty** [comment]
If I remember correctly, the API only defines FI_RMA_EVENT for RMA writes updating a counter at the target.  This limitation is based on expected use of the feature, which restricted what providers needed to implement.  For example, support for RMA reads is more difficult to implement and use correctly by applications.  For CQ based completions, RMA writes may be paired with remote CQ data, which will generate completions at the target.  That feature is available without FI_RMA_EVENT.

**Comment by nikitadanilov** [comment]
Do I understand it correctly, that if I want the target to know when RMA completes, I have to fi_send a separate completion message?

**Comment by shefty** [comment]
Existing hardware requires one of these sequences to notify the target that an RMA operation has completed:

- Use RMA write with CQ data (e.g. fi_writedata).  The CQ data will generate a completion at the target
- Use RMA write, followed by sending a message (e.g. fi_write + fi_send).  The send completion at the target will indicate that the RMA write has completed.
- Use RMA read, wait for it to complete, followed by sending a message (e.g. fi_read + fi_cq_read + fi_send).

The second option requires send-after-write message ordering (FI_ORDER_SAW).  That should be the case for most hardware/providers.  The send can be posted immediately after the write.

The third option assumes that send-after-read message ordering (FI_ORDER_SAR) is *not* supported by the provider, and that sends may pass reads.  This is the case for most hardware.  As a result, the read must complete locally first before the message is sent to the target.

It's worth noting that FI_RMA_EVENT support ends up implementing the second option under the API for the providers that do support it.

**Comment by nikitadanilov** [comment]
Thanks, @shefty, this clarifies things. I am coming from Sandia Portals/Lnet background where target notification is done under the hood.

**Comment by upendrapatwardhan** [comment]
Thank you for the clarification @shefty .
