### ISSUE TITLE
The motivation of using huge pages for av_entry_pool?

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6542]
I noticed that ```av_entry_pool``` was allocated with huge pages, 

https://github.com/ofiwg/libfabric/blob/a5ea18112d696a09b5d0cc70ba2a960da7ea2b51/prov/util/src/util_av.c#L464

and this is only public entry pool that is using HUGEPAGES.

I wonder what is the motivation of using huge pages for this particular pool. The reason is currently huge pages need to explicitly reserved. Once the memory is reserved for huge pages, it cannot be used by regular memory allocation. So we want to only use huge pages for performance critical places, and reserve as little as possible huge pages.

**Comment by shefty** [comment]
Reading the history, I don't think there was any specific reason hugepages were selected.  We went from no pools, to all pools, to selected pools.  This pool ends up storing address in an array.   RxD and smr store 64-bit values.  Hugepages seem like overkill there.  It definitely is for smr.  RxM ends up store socket addresses, so either, uhm, 8 or 28 bytes?  Hugepages still seem like overkill for anything but the largest systems.

**Comment by wzamazon** [comment]
Thank your for your reply!

Would you be open to remove the huge pages flags?

**Comment by shefty** [comment]
Go for it

**Comment by wzamazon** [comment]
https://github.com/ofiwg/libfabric/pull/6543 was merged, closing ....
