### ISSUE TITLE
Data placement ordering within a particular message

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#655]
Currently we do not define any data placement ordering between bytes that belong to the same message.

Over the years, there have been several MPIs that did relied on memory polling of the "last byte", and assumed that if the last byte was available, then the preceding bytes were also available.

How does an app request such ordering from OFI?

**Comment by shefty** [comment]
FI_ORDER_DATA flag defined.  Not sure if this is sufficient, but it's what we have now.  :)
