### ISSUE TITLE
default ordering is FI_ORDER_NONE

### ISSUE THREAD

**Issue by sayantansur** [ofiwg/libfabric#657]
Any app directly setting ep_attr structure must be very careful with how msg_order is specified, since the default is 0 == FI_ORDER_NONE.

How many apps are going to leave msg_order 0 and fail in unexpected ways? What's a good default?

**Comment by shefty** [comment]
I will define FI_ORDER_UNSPEC as 0, with a proposal for a new default order that we can debate.

**Comment by shefty** [comment]
The PSM provider can only support a default ordering of SAS.
I couldn't easily find a default msg_order for usnic.  It may only support none.
@jsquyres @goodell @j-xiong
We need a reasonable default, if one can exist.

**Comment by goodell** [comment]
For EP_DGRAM endpoints usnic can only support NONE.  For EP_MSG and EP_RDM it would probably be `STRICT` or `SAS` (they don't support read or write right now, so the other modes don't matter).

**Comment by shefty** [comment]
I think we need to leave this defined as it is.  The default ordering will be none.
