### ISSUE TITLE
DAOS: libfabric:41405:ofi_rxm:domain:rxm_mr_regv():340<warn> Unable to register MSG MR

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#6589]
When running IOR test suite over DAOS VOL interface, during the test (after some time) bulk/rdma registrations start failing with 
libfabric:41405:ofi_rxm:domain:rxm_mr_regv():340<warn> Unable to register MSG MR

The error code returned to rxm_mr_regv() ends up being -95.
This test suite fails on OpenSuse 15.2; the same test suite with the same ofi/daos stack works fine on RHEL-7

Other less intensive rdma tests that utilize rdma transfers/mem registrations appear to be passing on OpenSuse 15.2

Provider: verbs;ofi_rxm
OFI version: 1.11.1 and 1.12.0rc1
Mellanox OFED: 5.2-2.2.0.0 
Env: 
FI_MR_CACHE_MAX_COUNT=0
FI_UIVERSE_SIZE=2048
FI_OFI_RXM_USE_SRX=1

Corresponding DAOS ticket: DAOS-6768

**Comment by frostedcmos** [comment]
Additional finding from today:
After trying to run with FI_VERBS_USE_ODP=1 setting, the test passes, however the speed is greatly reduced; we are getting 1/10t of a bandwidth

**Comment by frostedcmos** [comment]
Additional info:
We've enabled mercury level NA logs and we seem to always hit the same registration # failure; test seems to perform first 56 registrations fine, and always fails on 57th:
03/04-17:48:16.13 daos20 DAOS[77468/77645] external ERR  # NA -- error -- /soft/storage/daos/sles/daos/build/external/release/mercury/src/na/na_ofi.c:4772
# na_ofi_mem_register(): fi_mr_regv() failed, rc: -95 (Operation not supported), mr_reg_count: 57

**Comment by j-xiong** [comment]
According to updated descriptions in the original DAOS ticket (https://daosio.atlassian.net/browse/DAOS-6768), it is related to  recent kernel changes w.r.t pmem backed memory. 

It has been fixed at DAOS side. Close it now.
