### ISSUE TITLE
psm3 breaks out of source tree builds

### ISSUE THREAD

**Issue by chuckcranor** [ofiwg/libfabric#6611]
libfabric no longer compiles with out of tree builds if psm3 is enabled.   (It still works if you configure with --disable-psm3.)

The build fails with:
<pre>
  CC       prov/psm3/src/libpsm3_la-psmx3_util.lo
  CC       prov/psm3/src/libpsm3_la-psmx3_wait.lo
  CC       prov/psm3/src/libpsm3_la-psm3_revision.lo
  CC       prov/psm3/psm3/libpsm3i_la-psm.lo
In file included from ../libfabric/prov/psm3/psm3/psm.c:58:0:
../libfabric/prov/psm3/psm3/psm2_hal.h:286:10: fatal error: psm2_hal_inlines_d.h: No such file or directory
 #include "psm2_hal_inlines_d.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:12402: recipe for target 'prov/psm3/psm3/libpsm3i_la-psm.lo' failed
make[1]: *** [prov/psm3/psm3/libpsm3i_la-psm.lo] Error 1
make[1]: Leaving directory '/tmp/try/build'
Makefile:4914: recipe for target 'all' failed
make: *** [all] Error 2
h0:try/build % 
</pre>

You can test this by doing:
<pre>
git clone https://github.com/ofiwg/libfabric.git
( cd libfabric  && ./autogen.sh )
mkdir build
cd build
../libfabric/configure 
make
</pre>

**Comment by shefty** [comment]
@acgoldma - please take a look at this.

**Comment by shefty** [comment]
The headers in question are auto-generated and should be marked as nodist.  The following patch allows an out of source tree build:
```
diff --git a/prov/psm3/Makefile.include b/prov/psm3/Makefile.include
index c0b5b5f42..514840d8b 100644
--- a/prov/psm3/Makefile.include
+++ b/prov/psm3/Makefile.include
@@ -235,9 +235,6 @@ libpsm3i_la_SOURCES = \
        prov/psm3/psm3/psm2_am.h \
        prov/psm3/psm3/psm2_hal.c \
        prov/psm3/psm3/psm2_hal.h \
-       prov/psm3/psm3/psm2_hal_inlines_i.h \
-       prov/psm3/psm3/psm2_hal_inlines_d.h \
-       prov/psm3/psm3/psm2_hal_inline_t.h \
        prov/psm3/psm3/psm2_mq.h \
        prov/psm3/psm3/ptl.h
 libpsm3i_la_CPPFLAGS = \
@@ -246,6 +243,11 @@ libpsm3i_la_CPPFLAGS = \
 libpsm3i_la_CFLAGS = \
        $(AM_CFLAGS) $(psm3_CFLAGS) $(_psm3_cflags)
 
+nodist_include_HEADERS = \
+       prov/psm3/psm3/psm2_hal_inlines_i.h \
+       prov/psm3/psm3/psm2_hal_inlines_d.h \
+       prov/psm3/psm3/psm2_hal_inline_t.h
+
 libpsm3i_la_LIBADD = \
        libopa.la \
        libuuid.la \
```
But isn't what we quite want, plus breaks make distcheck.

**Comment by acgoldma** [comment]
Still need some testing, but I have something that builds with both cases (distcheck and out of tree):

```
diff --git a/prov/psm3/Makefile.include b/prov/psm3/Makefile.include
index c0b5b5f42..48f7a1138 100644
--- a/prov/psm3/Makefile.include
+++ b/prov/psm3/Makefile.include
@@ -35,8 +35,11 @@ _psm3_files += \
        prov/psm3/src/psm3_revision.c
 chksum_srcs += \
        prov/psm3/src/psm3_revision.c
+
+# builddir is for nodist config headers: See nodist_libpsm3i_la_SOURCES
 _psm3_cppflags += \
        -I$(top_srcdir)/prov/psm3/psm3 \
+       -I$(top_builddir)/prov/psm3/psm3 \
        -I$(top_srcdir)/prov/psm3/psm3/ptl_ips/ \
        -I$(top_srcdir)/prov/psm3/psm3/include/ \
        -I$(top_srcdir)/prov/psm3/psm3/include/linux-i386/ \
@@ -235,8 +238,6 @@ libpsm3i_la_SOURCES = \
        prov/psm3/psm3/psm2_am.h \
        prov/psm3/psm3/psm2_hal.c \
        prov/psm3/psm3/psm2_hal.h \
-       prov/psm3/psm3/psm2_hal_inlines_i.h \
-       prov/psm3/psm3/psm2_hal_inlines_d.h \
        prov/psm3/psm3/psm2_hal_inline_t.h \
        prov/psm3/psm3/psm2_mq.h \
        prov/psm3/psm3/ptl.h
@@ -246,6 +247,10 @@ libpsm3i_la_CPPFLAGS = \
 libpsm3i_la_CFLAGS = \
        $(AM_CFLAGS) $(psm3_CFLAGS) $(_psm3_cflags)

+nodist_libpsm3i_la_SOURCES = \
+       prov/psm3/psm3/psm2_hal_inlines_i.h \
+       prov/psm3/psm3/psm2_hal_inlines_d.h
+                                                                                                                                                                        libpsm3i_la_LIBADD = \                                                                                                                                                         libopa.la \                                                                                                                                                             libuuid.la \
```

It is recommended in the [gnu automake manual](https://www.gnu.org/software/automake/manual/html_node/Headers.html) to use _SOURCES for a single convenience library.

The only other thing I needed to add was to point to the builddir in the include path for these 'built' files.
