### ISSUE TITLE
EFA: performance regression with 1.12.0 vs. 1.9.0

### ISSUE THREAD

**Issue by mkre** [ofiwg/libfabric#6615]
Hi,

We are seeing performance regressions on EFA with the latest release 1.12.0. Compared to our currently used version 1.9.0, spot tests are showing a 25% runtime increase on 10 c5n.18xlarge instances (360 cores). On #6565, @wzamazon mentioned that the regressions are already known, so I'm mostly opening this ticket for further reference and bookkeeping.

Also, I'm wondering if there is some known workaround for 1.12.0? We have to upgrade to 1.12.0 because we are seeing segmentation faults with 1.9.0 for other test cases.

Thanks,
Moritz

**Comment by wzamazon** [comment]
Hi Moritz,

We have released EFA installer 1.12.0, which contains a bunch of performance enhancement, with it I am seeing the performance of star ccm+ is back to 1.9 level.

**Comment by wzamazon** [comment]
EFA installer 1.12.0 has already been released. It contains: libfabric 1.11.2amzn1.0 (a special amazon release), rdma-core 32.1, EFA kernel module 1.12.0.
