### ISSUE TITLE
psm3 attempts to build even if infiniband/ib.h is missing

### ISSUE THREAD

**Issue by chuckcranor** [ofiwg/libfabric#6623]
The psm3 provider requires infiniband/ib.h to compile, but configure does not check for that file.  This may result in this failure:
<pre>
  CC       prov/psm3/psm3/libpsm3i_la-psm_sysbuf.lo
  CC       prov/psm3/psm3/libpsm3i_la-psm_timer.lo
  CC       prov/psm3/psm3/libpsm3i_la-psm_utils.lo
../libfabric/prov/psm3/psm3/psm_utils.c:62:10: fatal error: infiniband/ib.h: No such file or directory
 #include <infiniband/ib.h>  // for AF_IB structures
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:12538: recipe for target 'prov/psm3/psm3/libpsm3i_la-psm_utils.lo' failed
make[1]: *** [prov/psm3/psm3/libpsm3i_la-psm_utils.lo] Error 1
make[1]: Leaving directory '/tmp/build'
Makefile:4924: recipe for target 'all' failed
make: *** [all] Error 2
h0:/tmp/build %
</pre>

looking at the output of configure for psm3, we have:
<pre>
configure: *** Configuring psm3 provider
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
looking for library without search path
checking for shm_open in -lrt... yes
checking numa.h usability... yes
checking numa.h presence... yes
checking for numa.h... yes
looking for library without search path
checking for numa_node_of_cpu in -lnuma... yes
checking infiniband/verbs.h usability... yes
checking infiniband/verbs.h presence... yes
checking for infiniband/verbs.h... yes
looking for library without search path
checking for ibv_get_device_list in -libverbs... yes
checking for -msse4.2 support... yes
checking for -mavx support... yes
checking rdma/rv_user_ioctls.h usability... no
checking rdma/rv_user_ioctls.h presence... no
checking for rdma/rv_user_ioctls.h... no
checking rv/rv_user_ioctls.h usability... no
checking rv/rv_user_ioctls.h presence... no
checking for rv/rv_user_ioctls.h... no
configure: psm3 provider: include in libfabric
</pre>

You can see that it checks for infiniband/verbs.h, but not infiniband/ib.h.  On ubuntu these two files are in different packages:
<pre>
h0:/tmp/build % dpkg -S /usr/include/infiniband/verbs.h
libibverbs-dev:amd64: /usr/include/infiniband/verbs.h
h0:/tmp/build % dpkg -S /usr/include/infiniband/ib.h
librdmacm-dev:amd64: /usr/include/infiniband/ib.h
h0:/tmp/build %
</pre>

On my system I happen to have "libibverbs-dev" installed, but not "librdmacm-dev" ... so I have verbs.h but not ib.h.

It turns out that "librdmacm-dev" depends on "libibverbs-dev" ...
<pre>
h0:x/build % apt show librdmacm-dev |& fgrep Depends
Depends: libibverbs-dev, librdmacm1 (= 17.1-1ubuntu0.2)
h0:x/build % 
</pre>

So in the prov/psm3/configure.m4 "FI_CHECK_PACKAGE([psm3_ibv] ...)" call it should either check for both ib.h and verbs.h, or just ib.h (because if ib.h is present, then verbs.h will be there too due to the dependency).

**Comment by shefty** [comment]
My preference is to check for all needed header files.  But based on a quick look, ib.h is being used to pull in to obtain the AF_IB defines.  The needed definitions are likely available in ofi_net.h, which has them specifically to avoid needing to pull in those headers.  (The libfabric core needs these, but we don't want the core depending on the verbs headers).  From ofi_net.h:

```
#ifndef AF_IB
#define AF_IB 27
#endif

#define OFI_ADDRSTRLEN (INET6_ADDRSTRLEN + 50)

/*  values taken from librdmacm/rdma_cma.h */
#define OFI_IB_IP_PS_MASK   0xFFFFFFFFFFFF0000ULL
#define OFI_IB_IP_PORT_MASK   0x000000000000FFFFULL

struct ofi_sockaddr_ib {
	unsigned short int  sib_family; /* AF_IB */
	uint16_t            sib_pkey;
	uint32_t            sib_flowinfo;
	uint8_t             sib_addr[16];
	uint64_t            sib_sid;
	uint64_t            sib_sid_mask;
	uint64_t            sib_scope_id;
};

enum ofi_rdma_port_space {
	OFI_RDMA_PS_IPOIB = 0x0002,
	OFI_RDMA_PS_IB    = 0x013F,
	OFI_RDMA_PS_TCP   = 0x0106,
	OFI_RDMA_PS_UDP   = 0x0111,
};
```

Using that would likely remove the need to include ib.h and the extra package.

**Comment by acgoldma** [comment]
@shefty, is correct, we can transfer to use the internal ofi structs and be fine. 
However, it looks like this was a stub and we currently no longer need this code. I will remove it from this repo.
