### ISSUE TITLE
sockets provider: no remote completion for fi_writedata requests

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#663]
This just appears to be a missing feature in the sockets provider: sending data using fi_writedata appears to work but does not generate a completion event with the remote CQ data on the receiving side.

@shefty This brings up the related issue of whether or not a remote CQ data event consumes the equivalent of an IB recv WQE.  We had discussed early on in the requirements gathering phase that there is really no good reason for it to since there is no relationship between the remote CQ data and the receive WQE that it consumes.  OTOH, verbs requires immediate data to consume a receive WQE.  Is this something that should be exposed as a mode/capability flag? (I'd be fine with going with the verbs behavior for 1.0 and exposing this functionality via a mode/capability flag in some version > 1.0, since it's so late in the development cycle)

**Comment by jithinjosepkl** [comment]
Good catch. I will take care of this.

**Comment by shefty** [comment]
I'd like to handle this before the 1.0 release, if possible.  I need to think about how to best handle this and gather input from the OFIWG.  This could be a mode bit, or assumed by the completion context field, which would be NULL if the completion is not associated with a receive.  But something should be documented here.
