### ISSUE TITLE
Query regarding IOV_LIMIT values

### ISSUE THREAD

**Issue by upendrapatwardhan** [ofiwg/libfabric#6649]
Can the IOV_LIMIT values be changed for the providers ( tcp / verbs) ?
In version 1.12.0, for tcp, the max limit is set to 4 (_#define TCPX_IOV_LIMIT		(4)_)
and for verbs it is set to 1 (_#define VERBS_MR_IOV_LIMIT 1_).
Can this be increased or is there any limitation for keeping these values restricted to small numbers?

**Comment by shefty** [comment]
The TCP limit is just a hard-coded value.  That value could be changed by updating the define.  It should even be possible to change the code to allow the limit to be specified through some environment variable.  There are internal arrays that use this value, so the larger it is, the more memory that each connection would consume, and the greater the stride between elements (which can effect caching).  I don't know what the limit is, if any, of the socket API.

The verbs limit is a limitation of the verbs hardware interfaces.  That limit cannot be changed.

**Comment by upendrapatwardhan** [comment]
Thanks @shefty for the clarification
