### ISSUE TITLE
ofi_monitors_add_cache() ignore ENOSYS error of a monitor

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6659]
Function `ofi_monitors_add_cache` will start memory monitor. IF the monitor failed to start, and the error is -FI_ENOSYS, the error is ignored, as show in the following

https://github.com/ofiwg/libfabric/blob/3bf822fbf78632f474396585b45d877502ef7a8d/prov/util/src/util_mem_monitor.c#L221

```
	ret = monitor->start(monitor);
			if (ret == -FI_ENOSYS)
				continue;
			else if (ret)
				goto err;
```

I wonder why there is such a special handling for -FI_ENOSYS error?

**Comment by wzamazon** [comment]
@iziemba I would appreciate your opinion on this issue.

**Comment by wzamazon** [comment]
IMO, this error should not be ignored. If the caller specified a monitor and the monitor cannot be started, the function should return fail.

**Comment by shefty** [comment]
If the functionality is disabled, the error will be -FI_ENOSYS.  For example, if CUDA is not installed (compiled out), start() fails with ENOSYS.

**Comment by shefty** [comment]
The monitors are enabled by default.  It may be better to enable by default _only if it's available_.  Then if it's forced on, failing on ENOSYS would work.

**Comment by wzamazon** [comment]
> It may be better to enable by default only if it's available

Like specify cuda memory monitor only for cuda build (when it is available)?

**Comment by shefty** [comment]
Something like:
```
struct ofi_mr_cache_params cache_params = {
	.max_cnt = 1024,
	.cuda_monitor_enabled = HAVE_LIBCUDA
	.rocr_monitor_enabled = HAVE_ROCR
};
```
in util_mr_cache.c

**Comment by wzamazon** [comment]
Sure. That would work. I can open PR for that.

The motivation for this issue is that ENOSYS is also used to indicate a monitor is not supported on a system (like userfaultd monitor is not supported by ubuntu 16.04).

Currently on ubuntu 16, EFA's MR cache was initialized successfully, but the MR cache does not support system memory.

**Comment by wzamazon** [comment]
Opened https://github.com/ofiwg/libfabric/pull/6662 for it.

**Comment by iziemba** [comment]
@shefty is correct. The original intention was to handle device memory monitors which were compiled out. -ENOSYS would be returned and we did not want to have MR cache allocation fail. https://github.com/ofiwg/libfabric/pull/6662 is a much better approach. Thanks for making this change!

**Comment by wzamazon** [comment]
https://github.com/ofiwg/libfabric/pull/6662 was merged. closing
