### ISSUE TITLE
sockets provider: fi_shutdown not implemented for connected message endpoints

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#667]
Again, just a missing feature in the sockets provider required by UNH EXS.

**Comment by shefty** [comment]
Jithin is already aware of the issue and is working on it.

**Comment by patrickmacarthur** [comment]
Cool, just wanted to make sure it was tracked.

**Comment by jithinjosepkl** [comment]
Yeah, I'm preparing a PR with coverity fixes and couple of MSG-EP fixes.
I will add this one also in that PR.
