### ISSUE TITLE
FI_EVENT clarification

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#670]
Is the FI_EVENT flag bit to be used for fi_av_open to indicate that asynchronous handling of fi_av_insert is desired?  Its a little confusing if one is looking at some of the provider codes.  The sockets provider seems to be using this correctly, while the psm provider seems to be using it for a different reason.

**Comment by shefty** [comment]
I don't see where the PSM provider uses FI_EVENT.  It looks like the PSM provider just needs to be updated to return ENOSYS if the FI_EVENT flag is set.  @j-xiong

**Comment by hppritcha** [comment]
The psm provider is using FI_EVENT in its fi_ep_bind implementation when binding a CQ to an EP.  I think the provider should be using FI_COMPLETION at this point in the code instead.
