### ISSUE TITLE
prov/verbs: failed to open domain in second provider

### ISSUE THREAD

**Issue by mshiryaev** [ofiwg/libfabric#6702]
Trying to use multiple verbs;rxm providers which expose different IB cards.

On system with 2 IB cards fi_getinfo return list of providers mapped on different IB cards / different protocols (like rxm, rxd).

Initialization of verbs;rxm provider mapped on first IB card works well,
but attempt to open domain for verbs;rxm provider mapped on second IB card fails with error:

libfabric:986791:verbs:fabric:vrb_get_match_infos():1739<info> handling of the socket address fails - -22
libfabric:986791:verbs:core:vrb_get_match_infos():1759<info> Handling of the addresses fails, the getting infos is unsuccessful
libfabric:986791:core:core:fi_getinfo_():1021<warn> fi_getinfo: provider verbs returned -61 (No data available)

Reproducer is attached.
FI_PROVIDER=verbs PROV_LIST=1 ./prov_test

[prov_test.txt](https://github.com/ofiwg/libfabric/files/6347450/prov_test.txt)

**Comment by shefty** [comment]
I admit I find the logic in the reproducer confusing, particularly in where it calls fi_getinfo.  When I run it on a system with 2 NICs (iWarp in my case), I get this output:
```
./fi_getinfo_test 
use prov_list 1
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma0
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma1
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma0
domain is already used, skip
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma1
domain is already used, skip
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma0
domain is already used, skip
Using OFI device: verbs;ofi_rxm:Ethernet-iWARP:irdma1
domain is already used, skip
```
So both domains are opened.  I'm still looking to see if I have access to a system with multiple IB cards.

**Comment by mshiryaev** [comment]
@shefty - sorry for confusing with fi_getinfo logic, the intent for verbs provider is to call fi_getinfo once and then iterate over providers using prov->next. The logic with fi_getinfo is a bit complicated just because the same test was also used to reproduce issue in shm provider (https://github.com/ofiwg/libfabric/pull/6699), where iteration using prov->next was not required.

**Comment by shefty** [comment]
It looks like the problem is IB specific, and not verbs provider in general?

**Comment by mshiryaev** [comment]
I noticed that if verbs;rxm providers will be filtered in "is_prov_used" function and only verbs;rxd providers will be kept then test passes. So looks like it is verbs;rxm specific.

**Comment by hzhou** [comment]
This may or may not be related, but may be of interest. We are testing a new provider selection logic in MPICH. Testing on a node with 2 IB cards with `FI_PROVIDER=verbs;ofi_rxm` --
```
[0] Required minimum FI_VERSION: 0, current version: 1000a
[0] provider: verbs;ofi_rxm, score = 3, FI_SOCKADDR_IN [16] 192.168.0.1
[0] provider: verbs;ofi_rxm, score = 0, FI_SOCKADDR_IN6 [28] fe80::9a03:9b03:c:6b86
[0] provider: verbs;ofi_rxm, score = 2, FI_SOCKADDR_IN [16] 10.140.36.3
[0] provider: verbs;ofi_rxm, score = 0, FI_SOCKADDR_IN6 [28] fe80::ec4:7aff:fefc:3360
```
We get a list of providers using `NULL` hints, then compare each capability with a set of requirements and produce a matching score. As you see, both cards returned, but strangely, the second card returns less capability. Further probe shows it is missing `FI_TAGGED`. Is this expected?

A sidenode, we were told that two IB cards can't be placed into the same subnet, so maybe this is just peculiar issues with IB and its verbs driver.

**Comment by j-xiong** [comment]
I don't have access to a machine with 2 IB cards. But the mix of IB and RoCE works fine:

$ FI_PROVIDER=verbs PROV_LIST=1 ./prov_test                                                                                                                    
use prov_list 1
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:ibp177s0
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:rocep75s0f1
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:ibp177s0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:rocep75s0f1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:ibp177s0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:rocep75s0f1
prov is already used, skip
no more providers, exit loop

**Comment by j-xiong** [comment]
Got a node with 2 IB cards and the test passed:

 $ FI_PROVIDER=verbs PROV_LIST=1 ./prov_test                                                                                                                        
use prov_list 1
**Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0**
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
**Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1**
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_1
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip
Using OFI device: verbs;ofi_rxm:IB-0xfe80000000000000:mlx5_0
prov is already used, skip

The original issue is more likely related to system configuration.

**Comment by mshiryaev** [comment]
@j-xiong - yes, there was issue with configuration of second IB in my environment. Closing the issue.
Thanks for support!
