### ISSUE TITLE
Failed to receive wtih `verbs;ofi_rxm`

### ISSUE THREAD

**Issue by hzhou** [ofiwg/libfabric#6720]
We are seeing strange issues trying out `verbs;ofi_rxm` in MPICH. It appears that when a process (say P1) send a tagged message to P2, completes and exit before P2 post the `fi_trecv`, the message will get lost. When later P2 posts the corresponding `fi_trecv`, it will get stuck in progress. The issue goes away if we ensure P2 pre post recv.

Is this a known issue or should we look for usage errors?

**Comment by hzhou** [comment]
The code in MPICH that send the data is linked here: https://github.com/pmodels/mpich/blob/0b27373fa1232e4521e8880323572aed6191322a/src/mpid/ch4/netmod/ofi/ofi_dynproc.c#L108-L157
When it receives the `MPIDI_OFI_EVENT_DYNPROC_DONE` the `req` will be marked as done, that was what I meant the the send message is done.

For reference, the receive side of code is here https://github.com/pmodels/mpich/blob/0b27373fa1232e4521e8880323572aed6191322a/src/mpid/ch4/netmod/ofi/ofi_dynproc.c#L159-L189

We are seeing failures of different mode of `fi_send` as well resulting from sender process exits before receiver process post its buffer. As a temporary fix, we are adding an `MPI_Barrier` in `MPI_Finalize`, but that is certainly undesirable.

**Comment by shefty** [comment]
The requested completion semantic is FI_TRANSMIT_COMPLETE.  That guarantees that the data has reached the NIC at the peer.  If you're sending a message for disconnect, FI_DELIVERY_COMPLETE works better.  That guarantees that the message has arrived in the peer's process memory space.  The message could still be unexpected, but you know that the peer process has it, versus the message only having reached the NIC.

**Comment by hzhou** [comment]
I was reading this issue https://github.com/ofiwg/libfabric/issues/5601 and thought the conclusion is `FI_DELIVERY_COMPLETE` was not really supported. Is there updates on that?

Regardless, `FI_TRANSMIT_COMPLETE` is not supposed to lose the message, right?

**Comment by shefty** [comment]
FI_DELIVERY_COMPLETE is supported for sends.  It just isn't actually supported for RMA.  RMA maps directly to RDMA operations, and because of transport offload, verbs devices only support FI_TRANSMIT_COMPLETE.  Delivery complete requires a SW based ACK.

No, FI_TRANSMIT_COMPLETE doesn't guarantee that the message won't be lost if the connection is torn down before it can be delivered to memory.

**Comment by hzhou** [comment]
Interesting. We only use `FI_DELIVERY_COMPLETE` for RMA operations. If that is not working, I wonder how do we manage the synchronization.
