### ISSUE TITLE
If msg_prefix_size is specified, should caller include the prefix size in buffer length?

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6748]
When user opened an end point with a non-zero msg_prefix_size. The current document states that the buffer provide by the user should be pointing to the beginning of the prefix (not the payload). However, it did not say whether the buffer length provided by user should include the prefix size. So I want to get some clarification on this point?

**Comment by wzamazon** [comment]
Thanks! I agree with you.

Do you mind if I open a PR to add this point to the doc?

**Comment by shefty** [comment]
Not at all -- clearer documentation is always better.

**Comment by rajachan** [comment]
I was questioning this for a second when I saw your fixes yesterday, @wzamazon. FWIW, this is already covered in fi_msg()
> If an endpoint has been configured with FI_MSG_PREFIX, the application must include buffer space of size msg_prefix_size, as specified by the endpoint attributes. The prefix buffer must occur at the start of the data referenced by the buf parameter, or be referenced by the first IO vector. Message prefix space cannot be split between multiple IO vectors. The size of the prefix buffer should be included as part of the total buffer length.

**Comment by wzamazon** [comment]
Ah, @rajachan thanks!
