### ISSUE TITLE
Behavior of fi_shutdown

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#677]
Comment from @patrickmacarthur :

In verbs, after performing an rdma_disconnect(), all outstanding receive
operations complete with status IBV_WC_WR_FLUSH_ERR.

However, the behavior for fi_shutdown() with regard to outstanding
operations is not clear to me.  The man page for fi_shutdown() only
explicitly mentions that outstanding completions will continue to be
available, but says nothing about completions for operations that are
still outstanding.

What is the intention of the libfabric API here?  Should I expect to get
completions on operations that were outstanding when the connections was
shut down, or is this up to the provider (meaning that I have to come up
with a different strategy for shutting down the completion processing
thread)?

**Comment by goodell** [comment]
I'll check more definitively later on, but I'm pretty sure that the usnic provider does not currently support this flushing behavior.  We might be able to add it in a software layer, but the hardware doesn't do this natively.  Once the underlying queues are disabled (but not yet destroyed) we should be able to iterate over them and generate fake completions for each outstanding operation.  But I haven't looked at how we are generating completions yet to see what sort of impact this would have.

A related question is for pending send requests.  If the application has stuffed a TX queue full and then immediately closed that EP, are all send operations required to complete without error?  Are they required to issue completions (assuming a completion would have been issued if the EP were not closed).  Again, without having studied the usnic provider code in this area, my guess is that we currently just pause the queues and don't drain them in any way (either with successful completions or errors).

**Comment by patrickmacarthur** [comment]
Additionally, there is also the issue of whether or not an FI_SHUTDOWN event gets placed into the EQ associated with the local endpoint's CM (which, in EXS, is at this point being watched for the sole purpose of catching FI_SHUTDOWN events).  The man page only requires the event to be placed into the remote EQ, and the sockets provider does not place it into the local EQ (the verbs provider does place it into the local EQ since librdmacm generates the event in both places).  There is a similar issue here: if a thread is performing a blocking wait onto the event queue, there is nothing to wake that thread up when the connection terminates and no more events will be issued on that EQ.

**Comment by shefty** [comment]
See #692.  Though I doubt my proposal will make Patrick happy.  :/

The best I could come up with was to define the behavior as 'provider specific'.  The only guarantee is that any events that are written to the CQs must be written before shutdown/close return.  I guess we could expose the provider's behavior through some sort of attribute, but I'm not sure that really helps the app all that much.  It seems that the apps must be ready to handle canceled completions, but should not expect them.

As for unblocking a waiting thread, that is part of the intent of having CQ write.  I need to re-think having that support.  I'm not sure any provider will easily be able to support such a feature without introducing software overhead in the completion path.  Maybe it would be better to replace cq:write with cq:signal, or similar, that simply unblocks a thread blocking in sread.  That's an application level feature that I've seen many apps need to implement.
