### ISSUE TITLE
Is it possible to define a provider-specific errno?

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#6779]
Currently, fabric errno values are defined in `rdma/fi_errno.h`. 
I'm wondering is it possible or allowed to define a provider-specific errno? 
I couldn't find related specification on man page, so want to have the input from the community.

**Comment by shefty** [comment]
My initial response is to recommend against a provider doing that and instead look at expanding the existing errno values.  (I mean, we have a few billion values to work with here. :)  We could add a flag or reserve a range to indicate provider values, and I have no objection.  Are you wanting to return a provider error code with a function call or report a provider error code somewhere else, like a completion?

**Comment by wzamazon** [comment]
In `fi_cq_err_entry`, there is a field ` prov_errno`, we want to use it to return a provider specific error. And I thought that field is specific for this purpose?

**Comment by shefty** [comment]
Yes, that field is provider specific.  Some providers don't have any other error codes, so dump a standard errno there, but any value is acceptable.

**Comment by wzamazon** [comment]
We plan to use that field to return some internal error code. Can we define some macro like `FI_EFA_ERR_XXX` in the header file?

**Comment by wzamazon** [comment]
We are also open to the suggestion that 

```reserve a range to indicate provider values```

in standard error code. For that, we will also need to make change to header file too.

**Comment by shefty** [comment]
The app would need to check that the provider in question is in use as part of the prov_errno value check.  For what you're describing, I wouldn't reserve a range of errno values.  But I'd be okay adding provider specific error codes to fi_errno.h.  I never really anticipated an app wanting to do anything specific based on this value, as it ties the app closely with a HW implementation.

**Comment by zhngaj** [comment]
Maybe we just need to extend the current errno defined in fi_errno.h, if it's general enough to all providers, e.g., some RNR related errno.

**Comment by shefty** [comment]
General RNR errors would be fine.  We have a CRC errno, which while generic, only applies to some providers (probably one).

**Comment by wzamazon** [comment]
Thanks! We will add a new general error for RNR then.
