### ISSUE TITLE
Remove duplicate attribute fields

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#680]
Some attribute fields were defined in multiple structures with the intent of making things easier for a developer.  They could set only EP attribute, for example, and have the TX/RX attributes inherit the EP attributes.  This saved the user from allocating multiple structures and linking them together.  However, with fi_allocinfo() available, it's easier for the app to use that call, then set the fields that they need.  This eliminates some confusion regarding which attribute field has preference.

**Comment by shefty** [comment]
Duplicate comp_order and msg_order fields removed.

**Comment by patrickmacarthur** [comment]
@shefty Which commit/pull request removed these fields?

**Comment by shefty** [comment]
Apparently some lost commit
