### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#6842]
Looks like OSS repos using the .org endpoint will have to migrate to the .com one by June 15th:
> Hi! It seems there are still plenty of builds running. We're pushing back the shutdown date to June 15th. Please consider migrating to travis-ci.com.

(originally planned for May)

Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by shefty** [comment]
This was pointed to me a couple weeks ago.  I took steps to migrate to .com.  Our travis links still go to .org, so I must have missed some step to move over.

**Comment by rajachan** [comment]
I still see `https://notify.travis-ci.org/` for the webhook, that must be why. The .org builds have already stopped today ("_Since June 15th, 2021, the building on travis-ci.org is ceased._ "). New PRs won't fail, but just won't trigger a build.

**Comment by shefty** [comment]
Travis CI is no longer viable without funding.  Looking at alternative options (including getting funding from OFA).
