### ISSUE TITLE
Does `ofi_bufpool_grow` has to call `memset` to clear allocated area?

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6849]
Hi, I just noticed that `ofi_bufpool_grow` call `memset` to clear allocated area.

https://github.com/ofiwg/libfabric/blob/ad0b93c30d9ad4f7d214a8caba648897db6b0957/prov/util/src/util_buf.c#L89

This call can be quite expensive when the buf pool is large.

I wonder if `ofi_bufpool_grow` is obligated to do that, or just for convenience?

**Comment by shefty** [comment]
I believe the callers expect this.  We could check the callers and use the init() callback to remove this and force it on the callers (even providing a memset-0 init() callback that user's could reference).

**Comment by wzamazon** [comment]
Thanks for you reply! I think this is a good idea, but I think we can do that after 1.13.0 release
