### ISSUE TITLE
fi_param_get boolean parameter behavior clarification

### ISSUE THREAD

**Issue by PeterGottesman** [ofiwg/libfabric#6853]
Hi, I am looking for some clarification about the return value of `fi_param_get`. The comment on the function [1] defines three possible return values - `FI_SUCCESS`, `-FI_ENODATA`, and `-FI_ENOENT`, however it seems to also return `-FI_EINVAL` in a few cases [2]. I just want to confirm if this return value is intentional and can be relied on. If so, I can go ahead and submit a PR to update that comment.

[1] [include/rdma/providers/fi_prov.h#L91](https://github.com/ofiwg/libfabric/blob/b5289152c2ad6bfd36aebc9faaab219f3777fde5/include/rdma/providers/fi_prov.h#L91)

[2] [src/var.c#L256](https://github.com/ofiwg/libfabric/blob/8e2e2383156263035bdfece0924e0989fc894ced/src/var.c#L256)

**Comment by shefty** [comment]
I *just* added a man page for the APIs in fi_prov.h.  See man/fi_provider.3.md.  The man page is a work-in-progress and is incomplete.  Rather than updating the comment in the header file, it would be better to move the comments to the new man page instead, along with any updates.  EINVAL should be a valid return value.  Thanks!

**Comment by PeterGottesman** [comment]
Hey Sean, I am updating the man page and I notice this block of code which handles the result of boolean parsing deals with errors differently than the rest of the function:

https://github.com/ofiwg/libfabric/blob/8e2e2383156263035bdfece0924e0989fc894ced/src/var.c#L296-L302

The behavior of `fi_param_get` is generally that if the return value is not `FI_SUCCESS`, `*value` remains unchanged. For boolean parameters though, if there is an error returned `*value` will always be `-1`. I imagine in most cases this would mean a typo in a environment var would result in a config option being silently set to true, but I don't know the big picture here well enough to know if this is a real issue or not, nor if a change to that behavior would have unintended side effects for some provider.

**Comment by shefty** [comment]
Good catch, we shouldn't modify 'value' here.  An anticipated use is:
```
static bool default_value = <true_or_false>

init()
{
    fi_param_get(... &default_value);
    use default_value;
}
```

**Comment by PeterGottesman** [comment]
Alright, two PRs coming your way :+1:
