### ISSUE TITLE
running with FI_OFI_RXM_USE_SRX=0 can lead to OOM

### ISSUE THREAD

**Issue by bfaccini** [ofiwg/libfabric#6855]
Intel MPI forces the usage of FI_OFI_RXM_USE_SRX=0 and setting this parameter accordingly on DAOS Server side (if not, it causes crashes/SEGVs in vrb_add_credits() !) leads to OOM causing daos_engine process to be killed due to its huge memory footprint.
Some defensive code (with threshold ?) or garbage collection mechanism seems to be required in order to avoid such behaviour and allow FI_OFI_RXM_USE_SRX=0 to be used for servers or long time running client applications.

**Comment by shefty** [comment]
A known problem that we've seen dealing with OOM is the result of unexpected messages building up at the receiver.  There are recent changes to the rxm provider to help deal with this, but those may only be used when combined with the tcp provider.  I have additional ideas to help limit unexpected messages in the case of tcp, but verbs would need a separate solution.

*IF* unexpected messages are the issue, I think rxm + verbs could track this and stop reposting receive buffers in the non-SRX case.  That would back off the sender until the unexpected messages are consumed.

**Comment by j-xiong** [comment]
Is the follow statement related to #6712?
```
Intel MPI forces the usage of FI_OFI_RXM_USE_SRX=0 and setting this parameter accordingly on DAOS Server side (if not, it causes crashes/SEGVs in vrb_add_credits() !)
```

**Comment by shefty** [comment]
> Is the follow statement related to #6712
> <https://github.com/ofiwg/libfabric/issues/6712> ?
> 
> Intel MPI forces the usage of FI_OFI_RXM_USE_SRX=0 and setting this parameter
> accordingly on DAOS Server side (if not, it causes crashes/SEGVs in vrb_add_credits()
> !)

I believe these are the same issue.  And I think your fix allows the client and server to set these differently now.

**Comment by j-xiong** [comment]
Close this issue now since the parameter setting is no longer needed for DAOS server.
