### ISSUE TITLE
prov/rxm:  no vaild rx_buf->mr in rendezvous receive handler

### ISSUE THREAD

**Issue by hz-cheng** [ofiwg/libfabric#6871]
I met a problem when using libfabric, I think it is a bug.

The test I runned is fi_rdm_pingpong:

`Server: fi_rdm_pingpong -d dev-name -v`
`Client: fi_rdm_pingpong -d dev-name -v 192.168.198.2`

With `FI_OFI_RXM_USE_RNDV_WRITE=true` and `ep->rdm_mr_local == true`

When the data size increased to 1M,  I find the program hung up.
And if I enable debug, the client will report :

`
fi_rdm_pingpong: prov/rxm/src/rxm_cq.c:503: rxm_rndv_xfer: Assertion !total_len failed.
Aborted
`

After debuging, I find the reason is:
Server receives the client's rxm_ctrl_rndv_req, and then build a `rxm_pkt` in rx_buf.
Due to the server never initializes  `rx_buf->mr`, in `rxm_rndv_send_wr_data->rxm_rndv_hdr_init`:

	for (i = 0; i < count && mr[i]; i++) {
		rndv_hdr->iov[i].addr = RXM_MR_VIRT_ADDR(rxm_ep->msg_info) ?
			(uintptr_t)iov[i].iov_base : 0;
		rndv_hdr->iov[i].len = (uint64_t)iov[i].iov_len;
		rndv_hdr->iov[i].key = fi_mr_key(mr[i]);
	}
	rndv_hdr->count = (uint8_t)count;
The iov field in rndv_hdr is empty.
When the client parses this pkt, it goes wrong.

My solution is:
In rxm_handle_rndv:

	if (!rx_buf->ep->rdm_mr_local) {
                 ....................
	} else {
		struct rxm_mr *mr;

		for (i = 0; i < rx_buf->recv_entry->rxm_iov.count; i++) {
			mr = rx_buf->recv_entry->rxm_iov.desc[i];
			rx_buf->recv_entry->rxm_iov.desc[i] =
				fi_mr_desc(mr->msg_mr);
			rx_buf->mr[i] = mr;
		}
	}

**Comment by Seitran** [comment]
sorry, `rx_buf->mr[i] = mr;` should be `rx_buf->mr[i] = mr->msg_mr;`

**Comment by shefty** [comment]
Asking @ooststep to take a look into this.
