### ISSUE TITLE
Address vector corruption

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#6879]
### Discussed in https://github.com/ofiwg/libfabric/discussions/6859

<div type='discussions-op-text'>

<sup>Originally posted by **theWayofthecode** June 17, 2021</sup>
Hi,

we face a problem that roughly looks like this.
```c++
/* [initialize an endpoint and the relevant structures] */
fi_av_open(av, ...);
fi_av_insert(av, fi_addr, addr, ...);
fi_av_lookup(fi_addr, addr_read, ...); // double check that addr == add_read
/* [close the endpoint and other structures except fid_domain and fid_fabric] */
fi_close(av);
/* [close the remaining descriptors] */
```
For every function the  return code is checked and there are no errors.
If we run the above (pseudo)code twice (in a single process execution), then the second time the fi_av_lookup() returns garbage (`��?, len:2  instead of the correct data 63568:44335:0:, len:14`). _This problem is noticed only when executed with valgrind._

Any ideas what might be wrong?
The documentation mentions:

> Providers may implement AV’s using a variety of mechanisms. Specifically, a provider may begin resolving inserted addresses as soon as they have been added to an AV, even if asynchronous operation has been specified. Similarly, **a provider may lazily release resources from removed entries.**

Could it be that there is something funny going on with the valgrind sandbox and the clean up of the address vector by shm?

Some possibly relevant information:

* libfabric v1.12.0 statically linked 
* provider shm
* The av is the TABLE variant

PS: I am not sure if I should open an Issue, since there might be an assumption that we are not taking into account. If this is a bug, I will transfer the information into an issue ticket.

Let me know if you need further information.

Thanks

EDIT: There is a larger effect of making the `fi_writedata()` hang, but our investigation lead to the AV corruption this is why we focus to it at the moment.</div>

**Comment by theWayofthecode** [comment]
Hi. I checked the PR, and it solved the problem above. Thanks for taking care of it.
