### ISSUE TITLE
prov/rxm – DAOS “daos_test -m” segfaults immediately if RDMAV_HUGEPAGES_SAFE is not set.

### ISSUE THREAD

**Issue by krehm** [ofiwg/libfabric#6894]
@carns Apologies, I couldn’t find the ticket that you mentioned so I am opening
a fresh one.

DAOS is currently using libfabric:
#define FI_MAJOR_VERSION 1
#define FI_MINOR_VERSION 12
#define FI_REVISION_VERSION 0

The root of the problem is that routine rxm_cmap_free() frees all memory
associated with rxm_ep->cmap, but the callers of rxm_cmap_free() do not zero
the rxm_ep->cmap pointer.   The freed memory gets reused for something else,
and then (in this case) a second call to rxm_cmap_free() segfaults because it
tries to clean up cmap->handles_av a second time, which now happens to point 
to very low process memory.

While grepping through tickets I saw other references to problems with a stale
handles_av structure, maybe they are variants of this problem, just taking a
different path through the code?

Here is the backtrace, analysis follows:

[root@delphi-001 ~]# daos_test -m
external ERR  # NA -- error -- /home/daos/pre/build/external/debug/mercury/src/na/na_ofi.c:2309
 # na_ofi_basic_ep_open(): fi_enable() failed, rc: -12 (Cannot allocate memory)
external ERR  # NA -- error -- /home/daos/pre/build/external/debug/mercury/src/na/na_ofi.c:2227
 # na_ofi_endpoint_open(): na_ofi_basic_ep_open() failed
[delphi-001:430170:0:430170] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x5081)
==== backtrace (tid: 430170) ====
 0 0x00000000000534c9 ucs_debug_print_backtrace()  ???:0
 1 0x0000000000107d08 smr_handle_signal()  /home/daos/pre/build/external/debug/ofi/prov/shm/src/smr_signal.h:64
 2 0x0000000000012b20 .annobin_sigaction.c()  sigaction.c:0
 3 0x00000000000c078e rxm_cmap_clear_key()  /home/daos/pre/build/external/debug/ofi/prov/rxm/src/rxm_conn.c:108
 4 0x00000000000c309a rxm_cmap_free()  /home/daos/pre/build/external/debug/ofi/prov/rxm/src/rxm_conn.c:753
 5 0x00000000000ce506 rxm_ep_close()  /home/daos/pre/build/external/debug/ofi/prov/rxm/src/rxm_ep.c:2488
 6 0x000000000000caa4 fi_close()  /opt/daos/prereq/debug/ofi/include/rdma/fabric.h:595
 7 0x000000000000caa4 na_ofi_endpoint_close()  /home/daos/pre/build/external/debug/mercury/src/na/na_ofi.c:2374
 8 0x000000000000de14 na_ofi_endpoint_open()  /home/daos/pre/build/external/debug/mercury/src/na/na_ofi.c:2240
 9 0x000000000000423f NA_Initialize_opt()  /home/daos/pre/build/external/debug/mercury/src/na/na.c:310
10 0x000000000000f7bf hg_core_init()  /home/daos/pre/build/external/debug/mercury/src/mercury_core.c:913
11 0x0000000000015324 HG_Core_init_opt()  /home/daos/pre/build/external/debug/mercury/src/mercury_core.c:4221
12 0x0000000000005837 HG_Init_opt()  /home/daos/pre/build/external/debug/mercury/src/mercury.c:1008
13 0x000000000005dbbc crt_hg_class_init()  /home/daos/daos/src/cart/crt_hg.c:527
14 0x000000000005e68a crt_hg_ctx_init()  /home/daos/daos/src/cart/crt_hg.c:594
15 0x000000000001d896 crt_context_create()  /home/daos/daos/src/cart/crt_context.c:208
16 0x0000000000027a02 daos_eq_lib_init()  /home/daos/daos/src/client/api/event.c:80
17 0x000000000002e484 daos_init()  /home/daos/daos/src/client/api/init.c:170
18 0x00000000004ca2aa main()  /home/daos/daos/src/tests/suite/daos_test.c:377
19 0x00000000000237b3 __libc_start_main()  ???:0
20 0x0000000000405d5e _start()  ???:0

Mercury is attempting to create an endpoint, but that fails because of the
usual memory allocation errors you get when RDMAV_HUGEPAGES_SAFE is not set.
Specifically, routine na_ofi_endpoint_open() calls na_ofi_basic_ep_open()
which calls:

    rc = fi_enable(na_ofi_endpoint->fi_ep);
    NA_CHECK_ERROR(rc != 0, out, ret, NA_PROTOCOL_ERROR,
        "fi_enable() failed, rc: %d (%s)", rc, fi_strerror(-rc));

which fails.  When na_ofi_endpoint_open() receives the failed return from
na_ofi_basic_ep_open() it jumps to label out: and then executes:

    if (ret != NA_SUCCESS) {
        na_ofi_endpoint_close(na_ofi_endpoint);
        *na_ofi_endpoint_p = NULL;
    }

The segfault occurs in the na_ofi_endpoint_close() routine above.  The code is
trying to close an endpoint that was never fully opened, where cmap is
pointing to freed memory.

The cmap memory was first freed as follows:
The fi_enable() routine mentioned above called rxm_ep_ctrl(). That routine
called rxm_conn_cmap_alloc(), then eventually called rxm_prepost_recv() which
failed because of the hugepages issue.  The code then called rxm_cmap_free()
but did not clear the rxm_ep->cmap pointer.

                if (rxm_ep->srx_ctx) {
                        ret = rxm_prepost_recv(rxm_ep, rxm_ep->srx_ctx);
                        if (ret) {
                                rxm_cmap_free(rxm_ep->cmap);
                                FI_WARN(&rxm_prov, FI_LOG_EP_CTRL,
                                        "unable to prepost recv bufs\n");
                                goto err;
                        }
                }

Back in na_ofi_endpoint_open() after the failed na_ofi_basic_ep_open() call
routine na_ofi_endpoint_close(na_ofi_endpoint) is called, which calls
fi_close(), which calls rxm_ep_close(), which again calls rxm_cmap_free().
This time rxm_cmap_free() is trying to free garbage memory, and the segfault
occurs.

**Comment by shefty** [comment]
PR #6833 rewrites the rxm CM code, which eliminates the cmap and greatly simplifies the code.  That PR still needs debugging, but I expect it to help here.  The best path forward is to test and debug 6833.  (The PR was opened to share the changes, with minimal testing done, not because it was ready for merging.)

**Comment by shefty** [comment]
The rxm CM code is now in main.  The cmap is no more, so the original problem should be resolved in favor of new and improved issues.

**Comment by shefty** [comment]
This issue is reference code that has been replaced, with no additional activity in over 6 months.  Closing.  Please open a new issue if problem are seen using main of v1.14 release
