### ISSUE TITLE
ofi+verbs for openacc gpu pointer

### ISSUE THREAD

**Issue by Zhang690683220** [ofiwg/libfabric#6899]
Hello,

I'm trying to use mercury based on libfabric to do the data movement from a GPU memory to a remote CPU memory.

By using:
```
#pragma acc enter data create(gpu_data[0:size])

    #pragma acc parallel loop collapse(2)
    for(int i=0; i<dim0; i++) {
        for(int j=0; j<dim1; j++) {
            gpu_data[i*dim1+j] = DEFAULT_VALUE;
        }
    }

    #pragma acc host_data use_device(gpu_data)
    {
        send(gpu_data);
    }

#pragma acc exit data delete(gpu_data[0:size])
```

I got no errors. But how I can make sure the data is directly moved from GPU to the NIC and then to remote CPU memory instead of implicitly move the GPU data to host then do normal cpu-cpu communication?
Is there any debug msg can help me with it?

Thanks

**Comment by shefty** [comment]
I don't think there's any easy way to tell.  Do you know if you have a kernel driver installed that supports GPU transfers?  I'm assuming you're using a verbs based device.  Is that correct?

I don't know what your send(gpu_data) maps to relative to libfabric.  For smaller transfers (~16k), the rxm provider will usually copy through to bounce buffers for message/tagged sends.  RMA is always done directly.

**Comment by Zhang690683220** [comment]
We have done gpu-gpu communications with openmpi built via ibverbs, does it mean we have the kernel driver installed successfully?

From my understanding, bouncing buffers are network buffers for data sending and landing, so does it exists on cpu memory, gpu memory or NIC memory? Also in this simple example, I'm doing 1024x1024 doubles so it should be 8MB

**Comment by shefty** [comment]
8MB transfers will use the rendezvous protocol, which is RMA.  That path will not use bounce buffers.

I don't know how Open MPI supports GPU buffers.  It _could_ copy GPU buffers through the host, even over ibverbs.  If you're running with a later version of MOFED, there's a good chance that GPU-GPU transfers via P2P are supported, but that's hidden from libfabric completely.

One way I can think of that might work as a check is to see if the address passed into the send(gpu_data) call above is the same address that is passed into the libfabric data transfer call.  I'm going to guess that call is fi_tsend() or fi_tsendmsg(), but that is just a guess.

**Comment by Zhang690683220** [comment]
I did some performance test for the gpu-remote cpu and cpu-remote cpu, the result is kind of weird. The data size I send is 512 MB to make the difference large enough. The GPU send time is always around 500ms greater than CPU send. Does verbs make any optimizations for cpu transfer?
