### ISSUE TITLE
prov/sockets: FI_COMPLETION flag ignored on message operations

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#691]
The `FI_COMPLETION` flag on fi_sendmsg(), fi_writemsg(), etc. seems to be ignored.

Digging a little bit, it seems that this is checked in `sock_pe_report_tx_completion` (among other places), but the flags in the message header are still in network byte order, so `msg_hdr.flags & FI_COMPLETION` is false.  The end result is that if FI_COMPLETION were specified when binding the send CQ, no send completions are ever generated on the CQ.

**Comment by shefty** [comment]
@shantonu - Shantonu is going to start updating the sockets provider in place of Jithin.
