### ISSUE TITLE
Libfabric hmem support and runtime dependency on GPU libraries 

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#6915]
When libfabric is built with at least one non-system HMEM API enabled (HAVE_CUDA/HAVE_ROCR/HAVE_LIBZE is defined), the resulting runtime library will have dependency on the related GPU libraries. Such library can't be used on systems without the GPU libraries installed. 

Ideally, the GPU library dependencies can be isolated into a separate module and be loaded with dl_open(). This would allow building a single libfabric binary and using it on systems with or without GPU libraries installed.

**Comment by j-xiong** [comment]
@mshiryaev

**Comment by rajachan** [comment]
This is already supported. See the `--enable-cuda-dlopen`/`--enable-rocm-dlopen` configure options for instance:
https://github.com/ofiwg/libfabric/blob/main/configure.ac#L525

You just need to add the same for HAVE_LIBZE

**Comment by wzamazon** [comment]
Same for gdrcopy, there are two flags --with-gdrcopy and --enable-gdrcopy-dlopen.

**Comment by j-xiong** [comment]
@rajachan @wzamazon Thanks. That makes things simpler.
