### ISSUE TITLE
Memory corruption in ubertest (jsmn)

### ISSUE THREAD

**Issue by jlbyrne-hpe** [ofiwg/libfabric#6916]
Running ubertest built with clang+ASAN showed that heap corruption was taking place while parsing the test config files. The version of jsmn.c that was imported has a bug. The fix is simple (below), but the code has moved on. The question is whether to grab the current version of jsmn or just apply the patch.

`commit 824d9a769c38584c5aef9f6f12642645c66dc055
Author: Serge A. Zaitsev <zaitsev.serge@gmail.com>
Date:   Sat Oct 17 15:09:35 2015 +0200

    applied fix from wireshark
---
 jsmn.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/jsmn.c b/jsmn.c
index 0e3ad74..74a62d0 100644
--- a/jsmn.c
+++ b/jsmn.c
@@ -240,7 +240,7 @@ int jsmn_parse(jsmn_parser *parser, const char *js, size_t l\
en,
                                parser->toksuper = parser->toknext - 1;
                                break;
                        case ',':
-                               if (tokens != NULL &&
+                               if (tokens != NULL && parser->toksuper != -1 &&
                                                tokens[parser->toksuper].type !=\
 JSMN_ARRAY &&
                                                tokens[parser->toksuper].type !=\
 JSMN_OBJECT) {
 #ifdef JSMN_PARENT_LINKS
@@ -263,7 +263,7 @@ int jsmn_parse(jsmn_parser *parser, const char *js, size_t l\
en,
                        case '5': case '6': case '7' : case '8': case '9':
                        case 't': case 'f': case 'n' :
                                /* And they must not be keys of the object */
-                               if (tokens != NULL) {
+                               if (tokens != NULL && parser->toksuper != -1) {
                                        jsmntok_t *t = &tokens[parser->toksuper]\
;
                                        if (t->type == JSMN_OBJECT ||
                                                        (t->type == JSMN_STRING \
&& t->size != 0)) {

`

**Comment by j-xiong** [comment]
I would suggest grab the new version if the API is unchanged (i.e. no need to change files other than jsmn.[ch]).

**Comment by jlbyrne-hpe** [comment]
Opened #6922 to update jsmn
