### ISSUE TITLE
Why there is not a v1.13.x branch?

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#6933]
@j-xiong @rajachan 

After v1.13.0 release, I thought there should be a v1.13.x branch so we can back port patches to v1.13.x, but there does not seem to be one. Am I missing something here?

**Comment by j-xiong** [comment]
I think Sean just forgot to create the branch when the 1.13 was released. I will create one.

**Comment by j-xiong** [comment]
@wzamazon The v1.13.x branch has been created.

**Comment by wzamazon** [comment]
@j-xiong  

Thank you! Do we need to bump the version to 1.13.1-a1 or something?

**Comment by j-xiong** [comment]
@wzamazon Not necessary based on how other stable branches are handled.

**Comment by wzamazon** [comment]
Thank you!
