### ISSUE TITLE
EFA segfaults in 1.13.0, works in 1.12.0

### ISSUE THREAD

**Issue by mkre** [ofiwg/libfabric#6941]
Hi,

Our application segfaults on AWS/EFA with 576 cores (16 instances of c5n.18xlarge) after upgrading from Libfabric 1.12.0 to Libfabric 1.13.0. I have tried replacing the 1.13.0 `libefa-fi.so` with the version from 1.12.0 and the segfault is gone, so I assume it must be in the EFA provider.

Pinging @wzamazon.

**Comment by wzamazon** [comment]
@mkre 

Thanks for reporting this. Can you give some details? like error message, and what is the test case?

**Comment by mkre** [comment]
The error message is basically just a SIGSEGV in one of our routines which does MPI communication. I haven't yet checked with a debugger. The segfault is gone when only replacing the EFA provider library, so I assume the issue must be there. We are seeing this with several test cases. Let me know if I should enable some diagnostics output in Libfabric or EFA, or if I should try some environment variables which can be related to a change of behavior between 1.12.0 and 1.13.0.

**Comment by wzamazon** [comment]
@mkre 
If possible, can you do the follow:

1. compile libfabric with `./configure --enable-debug`, 
2. generate a core dump file when segfault happens
3. use debugger to get backtrace from the core dump,

This would be really helpful.

Meanwhile, we can try to reproduce. I assume the application is star ccm+? Can you provide the version and test case name?

**Comment by mkre** [comment]
Yes, the application is STAR-CCM+. It is a development version including Libfabric 1.13.0, but maybe the behavior can be reproduced by using a recent release version (shipping Libfabric 1.9.0) and using Libfabric 1.13.0 via special command line flags. I haven't checked this, though. We are seeing the segfault with the following test cases (not sure to which of these you have access): LeMans_104M.sim, lemans_poly_17m.amg.sim, VtmUhoodFanHeatx68m.sim, civil.sim

I'll try to gather the requested information. I just found out that the issue appears at 13 nodes (468 cores) and above.

**Comment by mkre** [comment]
I just saw this message instead of a segfault in one my runs:
```
Expected to receive 8868 objects in MPI_Recv, but received 8864 instead.
```

Maybe this helps. I'll try to dig deeper.

**Comment by mkre** [comment]
@wzamazon, I have a bit more information. The segfault is happening in on of our methods (rather than Libfabric), so it seems like the EFA provider might be messing with some memory buffers, which is causing the segfault downstream. Also, when using Libfabric with `--enable-debug`, I don't get a segfault but an `MPI_ERR_INTERN`. The message described in my latest comment (`Expected to receive...`) is what I get when running under Valgrind.

**Comment by wzamazon** [comment]
@mkre 

We have access to VtmUhood test case. I tested it with libfabric 1.13.0, but was not able to reproduce. I was using the following setting:

MPI type: Intel MPI 2019 U 7
Libfabric : 1.13.0
Number of nodes: 16
Number of ranks per node: 36
Parameter: `-preits 50 -nits 50`

**Comment by mkre** [comment]
@wzamazon, I just tested with Intel MPI and there is no segfault. I am only seeing it with Open MPI. Sorry for not testing and mentioning this in my initial report. I also just confirmed that I can see the segfault with the latest release version (16.04) using Libfabric 1.13.0 "through the backdoor". Here are the relevant parts of my command line:
```
FI_PROVIDER_PATH=/path/to/ofi/1.13.0/lib/libfabric starccm+ -mpi openmpi -bs slurm -batch step VtmUhoodFanHeatx68m.sim -xsystemlibfabric -ldlibpath /path/to/ofi/1.13.0/lib
```
I think you should see the same behavior with your 15.05.044 distribution. If not, let me know.

Thanks,
Moritz

**Comment by wzamazon** [comment]
@mkre 

Thank you! with you information, I was able to reproduce the error.

I was able to locate the issue, and opened the following PR to fix it.

https://github.com/ofiwg/libfabric/pull/6946

Can you please test whether it fixed the issue for you?

**Comment by mkre** [comment]
@wzamazon, I can confirm that the patch fixes the issue. Thanks for addressing it so quickly. Will the patch make it into 1.13.1, or do we have to wait for 1.14.0? I'm wondering because it has been merged to `main` but not the `v1.13.x` branch.

**Comment by wzamazon** [comment]
@mkre  Thank you for confirming the fix!

It will be back ported to v1.13.x and be part of v1.13.1. 

I just opened https://github.com/ofiwg/libfabric/pull/6949 to back port.

**Comment by wzamazon** [comment]
This bug was introduced in v1.13, so that is the only branch it needs to be back ported.

**Comment by mkre** [comment]
Thanks @wzamazon!

**Comment by mkre** [comment]
Just a quick follow-up question (maybe also to @shefty). Do you have a rough estimate about when we can expect 1.13.1 to be released? I'm asking because we need to decide if we can wait for the 1.13.1 release or if we need to upgrade to a patched 1.13.0 release. There is a general need for us to upgrade from 1.12.0 to 1.13.x because the latter shows much lower memory consumption.

**Comment by wzamazon** [comment]
@shefty is on vacation till Sep. I do not know the timeline of 1.13.1, maybe @j-xiong can answer this question?

**Comment by j-xiong** [comment]
The original plan was to wait until Sean returns. However, if there is urgent need we can make the change.

**Comment by mkre** [comment]
September could be a little late for us, as we will have to go through approval processes etc. before we can ship the new version. So it would be perfect if you could release 1.13.1 in the shorter term. Obviously, shipping a proper 1.13.1 release would be much preferred for us instead of shipping a patched 1.13.0.

**Comment by j-xiong** [comment]
@mkre would a release date around 8/20 work?

**Comment by mkre** [comment]
@j-xiong, yes that would work. Thanks for your commitment!

**Comment by wzamazon** [comment]
@mkre libfabric 1.13.1 was released on Aug 24.

**Comment by mkre** [comment]
Thanks @wzamazon. We have already adopted 1.13.1 and it is working fine!
