### ISSUE TITLE
Possible silent failure in smr_progress_ipc

### ISSUE THREAD

**Issue by PeterGottesman** [ofiwg/libfabric#6947]
Hey, I was looking at the implementation of `smr_progress_ipc` and I noticed the following snippet:
https://github.com/ofiwg/libfabric/blob/aaa8b8b3ebde73e8246643f8cf8a7597c8373166/prov/shm/src/smr_progress.c#L466-L467
At this point, `ret` is guaranteed to be zero, so this conditional will always execute, masking any failure of the immediately preceding memory copy. I don't have a great idea of how `total_len` is used after the progress function returns, so I am unsure if this is intentional or not.  If not, I would propose changing that conditional to something along the lines of:

```C
if (*total_len != cmd->msg.hdr.size)
{
     ret = -FI_EIO;
}
```

@aingerson Do you have input here?

edit:

looking closer at the return value of the memory copy, something like the following might make more sense:
```C
if (*total_len != cmd->msg.hdr.size)
{
     ret = *total_len < 0 ? *total_len : -FI_EIO;
}
```

**Comment by aingerson** [comment]
@PeterGottesman Thanks for finding this! Yeah this definitely looks wrong. The actual fix will have to be a little more finicky because we want to make sure we still close the handle and return the correct error even if close passes. Also, the error code should be FI_ETRUNC, not FI_EIO if it was truncated but still valid.
I can go ahead and fix this but you're more than welcome to if you want to take a stab at it.

**Comment by PeterGottesman** [comment]
:+1: I can go ahead and make a PR. Any opinion on returning the error value in `*total_len` as done in the second code block there? Also, I am unsure what is done with `total_len` down the line, should it be modified in any way in the error case?

**Comment by aingerson** [comment]
Definitely set ret to be the return value of *total_len (if negative) to get the correct error code.
If ret is set, total length should get ignored later so it shouldn't matter down the line in the error case.
While you're changing this, could you change the other protocols to return FI_ETRUNC, not FI_EIO for the truncated errors (in a separate patch but same PR is fine)? Thank you!
