### ISSUE TITLE
gh-pages: Stale link to fabtests man page since 1.10.1 

### ISSUE THREAD

**Issue by PeterGottesman** [ofiwg/libfabric#6950]
It looks like fabtests.7.md is missing from the website since 1.10.1, see the error message at https://ofiwg.github.io/libfabric/v1.10.1/man/fabtests.7.html. It looks like the fix is just a matter of copying `fabtests/man/fabtests.7.md` over for each release, but I am not sure if that should be done manually or by updating a script or something of the sorts.

**Comment by rajachan** [comment]
This is done during a release:
https://github.com/ofiwg/libfabric/wiki/Release-procedures#do-the-release

`fabtests/man/*.md` must have been missed.

**Comment by PeterGottesman** [comment]
👍 Thanks Raghu.

I can PR the missing pages this afternoon. All good if I update that release page as well? I would make the relevant line read the following, bolded section is added.

- Copy the `man/*.[0-9].md` **and `fabtests/man/*.[0-9].md`** files from _exactly_ the same Git hash that was used to make the official tarball to the `gh-pages` branch of the libfabric Git repo

**Comment by rajachan** [comment]
Go for it.

**Comment by j-xiong** [comment]
@PeterGottesman I updated the page a moment ago (before seeing your comments), please feel free to adjust.

**Comment by PeterGottesman** [comment]
Closed by #6951
