### ISSUE TITLE
Question regards to completion queue order

### ISSUE THREAD

**Issue by VoVAllen** [ofiwg/libfabric#6999]
Hi,

I'm trying to use libfabric with EFA. I'm wondering whether the order of the event in completion queue consistent with the recv event. For example, if I do `fi_send1(...); fi_send2(...)` and `fi_recv1(...); fi_recv2(...)`, I know EFA will preserve the order correctly, but my question is if I poll the completion queue at the receiver side by `fi_read_cq`, whether the first event is certainly `fi_recv1`? Is the order preserved at the sender side?
Or is there any flag I can used for EFA to guarantee this?

I'm trying to use EFA to implement kind of RPC system. I need to send non-fixed-size buffer, thus I need to send the size first and send the real buffer second. If the completion order is not guaranteed, how can I implement such things? Thanks a lot

**Comment by wzamazon** [comment]
When you call `fi_send`/`fi_recv`, there is an argument `context`, which will be included in the CQ entry you got. From the `context`, you identify which send/recv has completed
