### ISSUE TITLE
DAOS: verbs;rxm - failure to send rpc when client is using many contexets

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#7000]
In the test, a simple server is started.

On the client side, application creates 30 contexts, and in a loop sends RPC to the server from each of those contexts to the same server endpoint, 1 RPC at a time. 
RPC payload is just few bytes.
With verbs;ofi_rxm provider, when the client reaches context 28, the RPC to the server never arrives, and the loop hangs.

At that time, the client gets filled with libfabric warnings:
“libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool”

The same test passes for tcp;ofi_rxm and sockets.

With the same test if I modify and send thousands of rpcs from smaller number of source contexts, everything works fine. 
If I change and allocate more contexts on client side, for example 32, then failure happens on earlier context (context 22).

This failure is seen both in OFI v1.12.0 and v1.13.1rc1

To reproduce:
Pull daos from master and checkout https://github.com/daos-stack/daos/pull/6503/files
Build daos
In top of daos tree in one terminal run:
sh run_cart_server.sh

In another terminal in top of daos tree run:
sh run_cart_client.sh

Example run with verbs (client output):

CLI [rank=0 pid=30138]  rpc sent from context=0
CLI [rank=0 pid=30138]  response received

CLI [rank=0 pid=30138]  rpc sent from context=1
CLI [rank=0 pid=30138]  response received

CLI [rank=0 pid=30138]  rpc sent from context=2
CLI [rank=0 pid=30138]  response received

...

CLI [rank=0 pid=30138]  rpc sent from context=27
CLI [rank=0 pid=30138]  response received

CLI [rank=0 pid=30138]  rpc sent from context=28

libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool
libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool
....
libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool
libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool
libfabric:30138:ofi_rxm:ep_data:rxm_ep_send_common():1587<warn> Ran out of buffers from Eager buffer pool

cart_client: src/cart/crt_utils.c:584: crtu_sem_timedwait: Assertion `rc == 0' failed.

**Comment by j-xiong** [comment]
Was the hang happening for the first round of rpc? How many cores does the machine have?

**Comment by frostedcmos** [comment]
the Hang happens every time the client is ran. if server is left running and client reruns, next rerun it hangs at the same spot with same warnings printed.

System has 18 cores.

**Comment by j-xiong** [comment]
My first question was -- did the client only send one rpc per context and the hang happened?

**Comment by frostedcmos** [comment]
yes, client only sends one rpc per context, and moves to next context. when it reaches context=28 the rpc response never arrives and server does not receive the rpc.

**Comment by shefty** [comment]
What is a context in the context of daos sending an rpc from a context?  Verbs requires that eager buffers be registered with the HW, so there's a limit to the size of the pool.  Is DAOS checking for EAGAIN as a return value and processing completions prior to attempting to resend the transfer?

**Comment by soumagne** [comment]
A context maps to an endpoint + CQ when scalable endpoints is supported or they all share the same endpoint + CQ if it's not supported. We do register eager buffers. We also do check for EAGAIN and retry operations while making progress. The only difference I see here is that for each "context" we pre-post N tagged receives to receive incoming RPCs. So for context=28 I imagine there'd be N x (28 + 1) receives posted, where N is 256 by default.

**Comment by shefty** [comment]
This issue is stale.  The rxm buffer pools were reworked, with an updated implementation in v1.13.x branch and later releases.  The v1.12 buffer pools had a limited size, and all connections associated with a single CQ shared that pool.  Later versions switched to a single buffer pool, versus separate pools for different uses, that grows dynamically.
