### ISSUE TITLE
shm: fi_rdm_atomic performance fluctunation on AWS c6gn instance

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7002]
We have observed that that the fi_rdm_atomic test's run time has very large fluctunation on c6gn (which uses AWS gravton 2 CPU).

I ran fabtests on shm provider using the following command for 100 times

```
/home/ec2-user/fabtests/bin/runfabtests.sh -T 1800 \
        -vvv -R -f /home/ec2-user/fabtests/share/fabtests/test_configs/shm/shm.exclude -t all -N shm 127.0.0.1 127.0.0.1
```

98% of the time, the fi_rdm_atomic finish in 10 seconds. However, in 3 occassions, the test took > 20 seconds to finish. The run time is 20 seconds, 24 seconds, 154 seconds.

This happens to main and v1.13.x branch. I will test other branches such as v1.11.x and v1.12.x branch.

**Comment by wzhang313** [comment]
Keep alive
