### ISSUE TITLE
Can the generated man pages be moved into a different directory?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#702]
This is a personal request based on my workflow, but can the markdown man pages and generated man pages be placed in different directories?  It would greatly simplify my life getting to the correct markdown page for editing purposes.  Is there anything that would prevent this?

@jsquyres

**Comment by jsquyres** [comment]
Nope, can do.  I'm out for the night, but can do this tomorrow, unless @patrickmacarthur beats me to it...

**Comment by jsquyres** [comment]
BTW, do you have a preference where the two go?  E.g.:

* .md files stay in man
* .N files get generated in ...?

**Comment by shefty** [comment]
No preference -- maybe .md in man as you suggest and others in man/man3, man/man7... ?

**Comment by shefty** [comment]
thanks
