### ISSUE TITLE
shm provider fabtest random crash

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7022]
AWS CI has encountered random crash when running fabtest on shm provider.

For example, https://libfabric-ci.aws.a2z.com/job/single-node/2507/PROVIDER=shm,label=ubuntu/testReport/junit/(root)/7_172_31_24_26_fabtests/fi_rdm_atomic__I_5__o_all__U__p__shm_/

The error message from CI is:

```
Error Message

Fail

Stacktrace

"fi_rdm_atomic -I 5 -o all -U -p _shm_" failed

Standard Output

server_cmd: /home/ubuntu/libfabric/fabtests/install/bin/fi_rdm_atomic -I 5 -o all -U -p "shm" -s 127.0.0.1
server_stdout: |
client_cmd: /home/ubuntu/libfabric/fabtests/install/bin/fi_rdm_atomic -I 5 -o all -U -p "shm" -s 127.0.0.1 127.0.0.1
client_stdout: |
bash: line 1: 25839 Segmentation fault (core dumped) /home/ubuntu/libfabric/fabtests/install/bin/fi_rdm_atomic -I 5 -o all -U -p "shm" -s 127.0.0.1 127.0.0.1

    
```

**Comment by aingerson** [comment]
@wzamazon Is this a consistent failure when running runfabtests? I can't reproduce this. I can reproduce a consistent segfault if the client is started before the server but runfabtests should wait a second before running the client to make sure the server has started so I'm not sure if I'm hitting the same segfault.
I'm working on solving the one I can reproduce.

**Comment by aingerson** [comment]
@wzamazon If you are able to consistently reproduce this error, could you try the fix in PR #7051 for me? This fixes the issue I'm seeing if the client is started before the server but I can't verify if this fixes what you're seeing.

**Comment by wzamazon** [comment]
It is not consistent. It happened to AWS CI twice.

**Comment by wzamazon** [comment]
I will close it for now, and reopen if it happens again.
