### ISSUE TITLE
Jenkins CI down due to maintenance

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#7027]
All the nodes used for Jenkins CI at Intel are down due to lab maintenance.  Currently no PRs will be polled and the master branch daily run is also suspended for the time being. Once the work on these nodes is complete and the nodes are available again, the CI Jobs will be restarted. ETA is end of day, Wed 9/1.

**Comment by j-xiong** [comment]
Nodes are still down.

**Comment by shijin-aws** [comment]
Is it OK to merge PRs which pass all other CIs? It seems in recent PRs the Jenkins CI does not show up in the checks.

**Comment by j-xiong** [comment]
We are validating the CI nodes. After the Jenkins service is restored the CI tests will be triggered manually for existing PRs.

**Comment by shijin-aws** [comment]
I see. Thanks!

**Comment by j-xiong** [comment]
Back to normal now.
