### ISSUE TITLE
libfabric build failed in an internal version of Visual Studio

### ISSUE THREAD

**Issue by Cheney-W** [ofiwg/libfabric#7041]
I'm a member of Microsoft vcpkg team. In our latest internal test, libfabric installation failed with following error:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\include\yvals_core.h(23,1): fatal error C1189: #error:  STL1003: Unexpected compiler, expected C++ compiler.`

This issue occured due to the new change: https://github.com/microsoft/STL/pull/2148 of STL. This change will be released in VS 2022 17.1 Preview 1, the corresponding toolset is V143. More info please see: https://github.com/microsoft/STL/wiki/Changelog

If you want reproduce this issue, please download the latest yvals_core.h: https://github.com/microsoft/STL/blob/main/stl/inc/yvals_core.h and replace the local version.

I know the current toolsets used in libfabric are v140, v141 and v142, but if you have plans to support v143, you may need to make some changes to avoid the above error.

**Comment by j-xiong** [comment]
@Cheney-W  Thanks for the info. Do you have any suggestion on what changes are going to be needed?

**Comment by shefty** [comment]
I think the error comes from this line:

https://github.com/microsoft/STL/blob/d5feb03f320ccaa8e214e3010c40c9c5afd686e2/stl/inc/yvals_core.h#L23
```
#ifndef __cplusplus
#error STL1003: Unexpected compiler, expected C++ compiler.
#endif // __cplusplus
```

No idea what change is needed to move to v143.

**Comment by CaseyCarter** [comment]
Hi! STL maintainer here. We made this change _very_ recently in https://github.com/microsoft/STL/pull/2148 which forbids including standard library headers from C programs. We've had a couple of bug reports recently when changes to an STL header stopped some C program from compiling - which shouldn't have been including STL headers in the first place - and decided the best thing for the community in the long term was to loudly break C programs that include STL headers.

If you are seeing this error, it's very likely that you are including an STL header while compiling C: C++ compilers predefine the macro `__cplusplus`, C compilers do not. The suggested fix is "don't do that" =)

Is that a clear enough explanation for you to hunt down and eradicate the problem?

**Comment by wylliamh** [comment]
Hello,
I am trying to build an old C/C++ project on Visual Studio 2022 and struggling with this error: fatal error C1189: #error: STL1003: Unexpected compiler, expected C++ compiler.
As far as I can see, <cassert> is not used anywhere in the solution.
Any idea on how to solve the problem?

**Comment by shefty** [comment]
Are you building libfabric with the patch above (1a5731163075fa3d07bb85aa4467d327f8809d3c) from @CaseyCarter.  See PR #7050.
