### ISSUE TITLE
Add configure knob to use mutex in place of spinlock

### ISSUE THREAD

**Issue by songweijia** [ofiwg/libfabric#7053]
Our libfabric application uses a dedicated thread to poll the completion queue for low latency. We are using the verbs provider. The `fi_cq_read()` implementation for verbs provider will [lock the completion_queue](https://github.com/ofiwg/libfabric/blob/10941c1f241dae15fdaab0755b6ef3f3a5e65355/prov/verbs/src/verbs_cq.c#L322) before checking its contents, and [unlock it](https://github.com/ofiwg/libfabric/blob/10941c1f241dae15fdaab0755b6ef3f3a5e65355/prov/verbs/src/verbs_cq.c#L359) after finished. However, its `fi_sendmsg()` implementation, which calls `vrb_post_send()` did something similar [here](https://github.com/ofiwg/libfabric/blob/10941c1f241dae15fdaab0755b6ef3f3a5e65355/prov/verbs/src/verbs_ep.c#L119) and [here](https://github.com/ofiwg/libfabric/blob/10941c1f241dae15fdaab0755b6ef3f3a5e65355/prov/verbs/src/verbs_ep.c#L156).

Ideally, the pthread spinlock, which the 'fastlock' uses, should be efficient enough so that the sender can always grab it to send messages. However, pthread's spinlock is neither fair nor FIFO, sometimes resulting in a terrible situation where the polling thread acquires the spinlock again and again while the sender thread waits for it for a long time (milliseconds) to proceed. This situation is very common when the number of the sender threads is small. When I disabled spinlock in `config.h` by hard-wiring `PT_LOCK_SPIN` to 0. The end-to-end throughput of our system jumps from ~700MB/s to 5GB/s.

I argue that libfabric could provide a configuration knob to disable using spin lock for the completion queue.

**Comment by shefty** [comment]
The locking is provider specific, but libfabric defines threading models, which are exposed to the application via the domain attributes.  If the correct threading model is selected, locking can be converted into no-ops.  It is not safe to simply remove necessary locking.  There are states being managed that low-level verbs does not handle through its locking.

See fi_domain_attr::threading.

If locking cannot be removed because the threading model does not allow it, an alternative lock implementation would be an acceptable solution.

**Comment by songweijia** [comment]
Hi Sean, thank you for your prompt response. Actually, I didn't suggest removing that locking - of course, we need it to keep the critical resource (the completion queue) safe. In libfabric, the [`PT_LOCK_SPIN` macro](https://github.com/ofiwg/libfabric/blob/10941c1f241dae15fdaab0755b6ef3f3a5e65355/configure.ac#L202) controls which lock mode to use: spinlock or normal std::mutex. When I say "disable using spinlock", I mean set `PT_LOCK_SPIN` to 0, which will disable using spinlock but use normal std::mutex. This shouldn't be a difficult change to `configure.ac` to add a configuration option allowing a user to choose the type of lock.

**Comment by shefty** [comment]
I agree we could have a configure option to select different locking implementations.  I too have seen issues before with spinlock not allowing progress on other threads.

**Comment by songweijia** [comment]
Thanks! That would be a nice feature we can rely on. Moreover, I think an ideal solution to that is to use a fair spinlock, for example, a [ticket lock](https://en.wikipedia.org/wiki/Ticket_lock). I didn't find it in the pthread library. However, there are some 3rd party implementations out there on Github. It might be worth trying.

**Comment by songweijia** [comment]
To be specific, I recommend something like this for now:
```
diff --git a/configure.ac b/configure.ac
index 5f95b29f1..62cefb1c3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -186,9 +186,20 @@ dnl Checks for libraries
 AC_CHECK_LIB(pthread, pthread_mutex_init, [],
     AC_MSG_ERROR([pthread_mutex_init() not found.  libfabric requires libpthread.]))
 
-AC_CHECK_FUNC([pthread_spin_init],
-       [have_spinlock=1],
-       [have_spinlock=0])
+AC_ARG_ENABLE([spinlock],
+    [AS_HELP_STRING([--disable-spinlock],
+                    [Disable spinlock if available@<:@default=no@:>@])],
+    [],
+    [enable_spinlock=auto]
+)
+
+AS_IF([test x"$enable_spinlock" != x"no"],
+      [AC_CHECK_FUNCS([pthread_spin_init],
+                      [use_spinlock=1],
+                      [use_spinlock=0])
+      ],
+      [use_spinlock=0]
+)
 
 dnl shm_open not used in the common code on os-x
 
@@ -199,7 +210,7 @@ AC_CHECK_FUNC([shm_open],
         [AC_MSG_ERROR([shm_open() not found.  libfabric requires shm_open.])])])
 fi
 
-AC_DEFINE_UNQUOTED([PT_LOCK_SPIN], [$have_spinlock],
+AC_DEFINE_UNQUOTED([PT_LOCK_SPIN], [$use_spinlock],
        [Define to 1 if pthread_spin_init is available.])
 
 AC_ARG_ENABLE([epoll],

```

**Comment by shefty** [comment]
My preference would be to have a selection, such as --with-synchronization=spinlock or --with-synchronization=mutex.  --disable-spinlock suggests that it's disabling serialization, rather than replacing it with some other mechanism.

Thanks for the details @KenBirman

**Comment by KenBirman** [comment]
@songweijia was just in my office and had another idea, which is to just have LibFabrics shift to using a fair spinlock (based on Lamport's Bakery Algorithm).  I'm not sure which STL lock type this is, but he says there is a standard implementation that works with pthreads.

**Comment by songweijia** [comment]
Yeah, I agree with you that the `--with-synchronization` option sounds more precise than `--disable-spinlock`, @shefty. In the future, we probably could consider using the fair spinlock as Ken just mentioned. Unfortunately, I didn't find one for STL but Linux had one in its kernel.

**Comment by shefty** [comment]
Linking to another library shouldn't be a problem.  To include source code, the license would need to match the project -- BSD or MIT would work, GPL only would not.

**Comment by shefty** [comment]
Please see if PR #7267 fixes the issue for you.  That PR updates the code to use a mutex instead of a spin lock.  A simple configure update failed (because of a bug in the shm provider, which has now been fixed).  But after looking at that option, I think updating to a mutex is preferred over most places where spin locks were used.

**Comment by shefty** [comment]
Most uses of spin locks were replaced with mutex.
