### ISSUE TITLE
Linux leak in ofi_shm.h

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#7074]
Currently, `include/ofi_shm.h` depends on unix domain socket definition which is not available on Windows, like
`#include <sys/un.h>` and `#define SMR_SOCK_NAME_MAX sizeof(((struct sockaddr_un *)0)->sun_path)`. It also has declarations for functions that relies on `shm_open` and its friends that are not available on windows. Then if a provider uses some definitions in `ofi_shm.h` by including it, it could not be compiled on Windows. We are wondering what is the reason that `ofi_shm.h` is not friendly to Windows as a utility code and what is the best practice for provider developers who want to include this header file to make it work on both Linux and Windows?

**Comment by shefty** [comment]
The shm implementation only works on Linux.  I'm not aware of similar calls there.  So, ofi_shm.h wasn't written to be portable, since that would have been extra work with no benefit.  That doesn't mean we can't add portability.

If <sys/un.h> is not available on windows, the practice is to add a new header under include/windows/sys/un.h.  Then a definition for sockaddr_un can be added there.

**Comment by shijin-aws** [comment]
One point raised by a windows developer @gurusrik is that 

>Note that ofi_shm.h has declarations for functions that are not compiled on Windows (implementation is in util provider in files that are not included for compilation). The result of this is that when this header is included, IDEs like visual studio would suggest that these functions are usable on Windows only to result in unresolved external symbol errors at link time.

We would like to know if it makes sense to use stubs for those functions and returns `FI_ENOSYS`

**Comment by shefty** [comment]
@aingerson should chime in here.  Yes, we could create ENOSYS stubs, or separate ofi_shm.h into 2 files, one which is portable, and the other which depends on having a real implementation.  What definitions in ofi_shm.h are actually needed on windows?

**Comment by aingerson** [comment]
Yeah, like @shefty says. We can definitely separate these or create stubs. But I'm curious which definitions in ofi_shm.h are you looking to use? It's hard for me to see which of these would even be useful in Windows.

**Comment by shefty** [comment]
Hmm... maybe shm could be ported to windows:

https://docs.microsoft.com/en-us/windows/win32/memory/creating-named-shared-memory

though that doesn't seem to be the question here.  This issue sounds more like code X includes ofi_shm.h, and code X also compiles on windows.  So, should code X wrap the include with if LINUX?  Should ofi_shm.h wrap itself in if LINUX?  Or should we start down a path of making ofi_shm.h/shm portable?

Given that ofi_shm.h is in the general include area, one of the last two options seems to make sense.

**Comment by aingerson** [comment]
I think shm could definitely be ported to Windows in the future. The biggest restriction for shm and Windows was CMA but now that we have the fallback SAR protocol, anything is possible! That sounds like work though... so... I'd probably vote to wrap ofi_shm with if LINUX until we can dedicate time and people to do that...

**Comment by shijin-aws** [comment]
To share more context of the issue ...

We are working on EFA builds on Windows. In the past we removed all of the parts where we used SHM symbols in the EFA provider and our windows friends were able to get by editing only files under efa/src and a couple of Windows headers. But one of our recent commit https://github.com/ofiwg/libfabric/commit/b7346ee introduces a include of  `<ofi_shm.h>` to use the `SHM_MAX_NAME` macro in efa code that breaks the compilation on Windows because this header files pulls more symbols that are not available on windows.

**Comment by wzamazon** [comment]
The usage of "SHM_MAX_NAME" is to prepare a buffer to call `fi_setname` on shm provider.

In general, I wonder when calling fi_setname on shm provider, how the caller should set buffer len? For some provider, the address length is fixed, so it is easy. But for shm, the address length is not fixed.

**Comment by shefty** [comment]
Why wouldn't you pass in the size of the address being handed to fi_setname()?

**Comment by wzamazon** [comment]
I wanted to be sure the name is not too long for shm.

But I guess if so, the call to fi_setname would fail.

So I do not actually need SHM_MAX_NAME.

Thanks!

**Comment by rwespetal** [comment]
`smr_setname` doesn't enforce `SMR_NAME_MAX` and will set the endpoint name to a string longer than that. I haven't went through the code yet to see if other parts assume a fixed length and either fail or truncate the size of the name.

**Comment by shefty** [comment]
The problem should be fixed in shm though.  Callers should not need to know these internal details.  smr_setname calls strdup, so that call in isolation "looks" fine.  But based on a quick inspective, the code would truncate the name.

**Comment by aingerson** [comment]
I believe this can be closed? The setname truncation issue was fixed in commit f0d8ff05ae09dcb3779c081f8bdd94decf7b87db
And it seems like you were able to remove the header dependency?

**Comment by gurusrik** [comment]
Yes, we were able to remove the dependency on the header and get a Windows build.  `ofi_shm.h` remains Linux specific at the moment and can be addressed as part of porting SHM to Windows.

**Comment by aingerson** [comment]
Ok, I'm going to close this and create a new issue to track porting to windows.
