### ISSUE TITLE
prov/psm3: build failing after updating to latest main

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7079]
I'm guessing there's some missing cleanup in the build process:
```
ar: /home/mshefty/scm/libfabric/.libs/libuuid.a: No such file or directory
Makefile:6026: recipe for target 'libpsm3.la' failed
make[1]: *** [libpsm3.la] Error 9
make[1]: Leaving directory '/home/mshefty/scm/libfabric'
Makefile:4963: recipe for target 'all' failed
```
rebuilding does not help, nor does make clean / make distclean

disabling psm3 from my build does

**Comment by acgoldma** [comment]
`libuuid` src used to be internal to psm3, it was removed in favor of using the external lib (`.so`) included in the distro. Looks like some dependency that autotools makes did not clean up properly. Did you run `make clean` before updating git?

**Comment by shefty** [comment]
Yes, I tried make clean and make distclean.  I agree that this looks like some missing cleanup. I'll see if any other branches work.  I did have it building on a different system, though it's one that I rarely use, so the git update was rather large.

**Comment by acgoldma** [comment]
The only thing I can think of is there is a missing cleanup step by autotools for cleaning up dependancy tracking when autoconf is run again. If you grep all the files in the repo for "libuuid" you should only see that we (`psm3`) dynamically link the lib now.

`make clean` is not always enough when autotools files like `configure.ac` and `Makefile.am` are changed. When you update those, it is generally a good Idea to clean the git repo as well.

**Comment by j-xiong** [comment]
It is unlikely, but just in case -- did you run autogen.sh after updating git?

**Comment by shefty** [comment]
yes

**Comment by shefty** [comment]
I tried switching to v1.12.x, running make clean, rebuilding from there, then switching back to main and repeating.  That worked.
