### ISSUE TITLE
prov/shm: failing fi_rdm_rma_event test with commit cb4e2945a4c

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7156]
Recently, we merged commit

```
commit cb4e2945a4c06c6a5e396759d7fbb99e058a2fc6
Author: Juee Himalbhai Desai <juee.himalbhai.desai@intel.com>
Date:   Fri Oct 1 10:28:25 2021 -0700

    prov/shm: Fix RMA completion reporting
    
    CQ completions for RMA should only be written for operations carrying CQ data.
    
    Signed-off-by: Juee Himalbhai Desai <juee.himalbhai.desai@intel.com>

diff --git a/prov/shm/src/smr_progress.c b/prov/shm/src/smr_progress.c
index 8dcee52a9..f5cdd3b73 100644
--- a/prov/shm/src/smr_progress.c
+++ b/prov/shm/src/smr_progress.c
@@ -900,13 +900,16 @@ static int smr_progress_cmd_rma(struct smr_ep *ep, struct smr_cmd *cmd)
                err = -FI_EINVAL;
        }
 
-       ret = smr_complete_rx(ep, (void *) cmd->msg.hdr.msg_id,
-                             cmd->msg.hdr.op, cmd->msg.hdr.op_flags,
-                             total_len, iov_count ? iov[0].iov_base : NULL,
-                             cmd->msg.hdr.id, 0, cmd->msg.hdr.data, err);
-       if (ret) {
-               FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
-               "unable to process rx completion\n");
+       if (cmd->msg.hdr.op_flags & SMR_REMOTE_CQ_DATA) {
+               ret = smr_complete_rx(ep, (void *) cmd->msg.hdr.msg_id,
+                                     cmd->msg.hdr.op, cmd->msg.hdr.op_flags,
+                                     total_len, iov_count ? iov[0].iov_base :
+                                     NULL, cmd->msg.hdr.id, 0,
+                                     cmd->msg.hdr.data, err);
+               if (ret) {
+                       FI_WARN(&smr_prov, FI_LOG_EP_CTRL,
+                       "unable to process rx completion\n");
+               }
        }
 
        return ret;
```

which changed shm provider such that it will only write RMA completion on remote side if FI_REMOTE_CQ_DATA is on.

However, this change missed another case that RMA completion should be written on the target side, which is if application requested FI_RMA_EVENT capablity.

The following is the manual regarding FI_RMA_EVENT

```
FI_RMA_EVENT
    Requests that an endpoint support the generation of completion events when it is the target of an RMA and/or atomic operation. This flag requires that FI_REMOTE_READ and/or FI_REMOTE_WRITE be enabled on the endpoint.
```
shm provider do support it, so should write a completion

**Comment by shefty** [comment]
There's another issue in this code path.  Here:

https://github.com/ofiwg/libfabric/blob/main/prov/shm/src/smr_progress.c#L824

the check for the Rx CQ being full also relies on whether remote CQ data was transferred.  Commit cb4e294 aligned the 2 checks in the code.  So both will need to be updated.

**Comment by aingerson** [comment]
Agreed that the change should be reverted but I think the original change was added because @Juee14Desai found a failure with her changes with shm so we should take another look at that.
@Juee14Desai could you run the rebased upstream/main with the reverted change against your changes with shm, please?

I also think the man pages should be updated to reflect the fact that the capability is only defined for counters because it says " completion events" on the getinfo description of the RMA_EVENT bit and then the fi_cq page references the capability when talking about cq flags.

**Comment by Juee14Desai** [comment]
@aingerson I was able to run the test with my changes successfully without the shm fix.
