### ISSUE TITLE
prov/sockets: crashes running fi_msg

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#721]
Error in writing to EQ
fi_accept)_: 282, 8 (unknown error -8)
double free or corruption

**Comment by shefty** [comment]
Commit 992be4011aa1a075ddcbf981f615928151b4aed9 introduces the error.  The return value from sock_eq_report_event() was changed from 0 meaning success to size of entry meaning success.  Calling locations were not updated.

**Comment by shantonu** [comment]
I am working on a commit that updates all the tests that uses fi_eq_*

**Comment by shefty** [comment]
I already have a fix for this.
