### ISSUE TITLE
netdir / fi_endpoint uses maximum values to create queue pair (bug)

### ISSUE THREAD

**Issue by dshinaberry** [ofiwg/libfabric#7213]
I am working on bringing up code that will be transferring data via RoCE among Linux and Windows hosts equipped with Mellanox ConnectX-5 NICs.

We have Linux to Linux communication working fine with the verbs provider. I am encountering some issues with the netdir provider on Windows. I am using version 1.13.0 of libfabric at the moment.

I will do my best to limit each thread to a single issue so as not to confuse any follow on discussion.

So, the first place our code stumbled was with a call to fi_endpoint on the subscribing side. It returned FI_OTHER, which was not super helpful. Digging deeper into the netdir provider layer of the code, I could see that Network Direct call was returning ND_INSUFFICIENT_RESOURCES.

In searching for a reason, I stumbled across a known issue (https://docs.mellanox.com/display/winof2v27051000/Known+Issues) with the Mellanox NIC:

2690140 Description: Requests of QPs with a string of values set to "max" (e.g., Max Queue Depth + Max SGE counter + Max inline Data size) cannot be processed by the driver as their accumulative size overcomes the WQ maximum size.

I was hoping to find that I could control the values that were requested, but that appears not to be the case. I found the code in question, prov/netdir/src/netdir_ep.c:ofi_nd_ep_control, was simply passing in the maximum values it obtained from an earlier query.

When I just blindly cut the values for MaxReceiveQueueDepth and MaxInitiatorQueueDepth by 50%, the routine started returning FI_SUCCESS.

So, for now, I am just leaving that hack in place and building a locally modified version of libfabric in order to proceed.

It seems to me that since the values being utilized are maximums, that it would be reasonable to expect to be able to query them via fi_getopt and then choose something other than the default via fi_setopt. I am new to libfabric, so perhaps there is already some other mechanism in place to achieve this that I am unaware of.

**Comment by j-xiong** [comment]
`fi_info->tx_attr` and `fi_info->rx_attr` have the values needed. `size` can be used for the queue depth, and `iov_limit` can be used for sge.

**Comment by shefty** [comment]
I believe the issue is in netdir_ep.c, we have this:
```
	hr = ep->domain->adapter->lpVtbl->CreateQueuePair(
		ep->domain->adapter, &IID_IND2QueuePair,
		(IUnknown*)ep->domain->cq,
		(IUnknown*)ep->domain->cq,
		ep,
		ep->domain->ainfo.MaxReceiveQueueDepth,
		ep->domain->ainfo.MaxInitiatorQueueDepth,
		ep->domain->ainfo.MaxReceiveSge,
		ep->domain->ainfo.MaxInitiatorSge,
		0, (void**)&ep->qp);
```
The QP and CQ are both created using maximum values.  Those values are obtained in netdir_domain.c:
```
	domain->ainfo.InfoVersion = ND_VERSION_2;
	ULONG len = sizeof(domain->ainfo);
	hr = domain->adapter->lpVtbl->Query(domain->adapter, &domain->ainfo,
					    &len);
```
The provider needs to use some reasonable default instead of allocating the maximum size structures that the HW supports.  The verbs provider does this, for example.

**Comment by dshinaberry** [comment]
FYI, I have a local fix for this issue. 

We don't have an organizational presence on GitHub yet. So, our management needs to decide how they want to handle the details of joining GitHub. Then I can fork the repository and create a pull request for you to review.

**Comment by shefty** [comment]
@dshinaberry Are you able to submit the changes through this account?  FWIW, I work for Intel, but my account is just a normal, personal account.

**Comment by dshinaberry** [comment]
@shefty It isn't a technical issue, but rather an organizational one. The powers that be just want a minute to consider how they want our organization's contributions to open source to be handled since this is the first time it has come up in our little corner of the company.
