### ISSUE TITLE
prov/sockets: fi_rdm_shared_ctx test crashes

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#722]
Not sure if this is a provider or test issue.

Running fi_rdm_shared_ctx
Posting recv for ctx: 0
Posting recv for ctx: 1
Posting send to remote ctx: 0
Posting recv for ctx: 0
Posting recv for ctx: 1
Posting send to remote ctx: 1
Posting send to remote ctx: 0
Posting send to remote ctx: 1
/home/mshefty/bin/ft_runall: line 122:  2294 Segmentation fault      (core dumped) fi_rdm_shared_ctx 127.0.1.1
...done
/home/mshefty/bin/ft_runall: line 124:  2290 Segmentation fault      (core dumped) fi_rdm_shared_ctx

**Comment by shantonu** [comment]
Tested with the lastest libfabric and fabtests, it's working fine!
