### ISSUE TITLE
DAOS: SEGV in ofi_bufpool_get_ibuf() due to a passed index/fi_addr value causing to exceed current region_table[] number of entries (region_cnt)

### ISSUE THREAD

**Issue by bfaccini** [ofiwg/libfabric#7229]
The root cause for this problem (wrong/garbled fi_addr)) is still under investigations, but this issue is being opened to address the fact that some defensive code is missing to gracefully handle the cases where an index/fi_addr will be used.

Looks like at least `(0 < index / pool->attr.chunk_cnt < pool->region_cnt)` condition must be checked in ofi_bufpool_get_ibuf() or callers with error return, and associated error handling in callers.

**Comment by shefty** [comment]
The general policy is that fast path operations will only use asserts, not run time checks, to guard against coding errors.  This is  for performance reasons.

**Comment by kprantis** [comment]
This, however, causes our servers to then crash/segfault, rather than being able to recover. This is really an unacceptable user experience for services to just crash if there is some underlying issue happening in the network.

**Comment by shefty** [comment]
As mentioned, we will not inject coding error checks into the fast path operations.  Such checks aren't even possible with FI_AV_MAP.

**Comment by kprantis** [comment]
Then we should have a conversation about what our options may be forward, as our customers find it unacceptable for the services to segfault and crash due to such issues, versus a graceful exit, and question the entire architecture if these things cannot be protected against. I will bring this up at the upcoming DAOS/libfabric manager meeting.

**Comment by wzamazon** [comment]
I am confused, did not the application passed a non-existent index in the 1st place? Can you add a check passing the index to libfabric?
