### ISSUE TITLE
prov/verbs FI_WRITE access mode is not correctly translated

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#7236]
From latest main and `prov/verbs/src/verbs_mr.c` line 154:
```C
        if (ofi_access & FI_WRITE)
                ibv_access |= IBV_ACCESS_LOCAL_WRITE;
```
This is not correct according to the manpage definitions, which use FI RMA operation names instead:
```
       FI_WRITE
              The memory buffer may be used as the source buffer for RMA write and atomic  operations
              on  the  initiator side.  Note that from the viewpoint of the application, the endpoint
              is reading from the memory buffer and copying the data onto the network.
```
What that means is that the source buffer should be registered with `FI_WRITE` when doing an `fi_write()` operation. An `fi_write()` operation should not need local write access but only remote write access. The code should be corrected to be:
```C
        if (ofi_access & FI_WRITE)
                ibv_access |= IBV_ACCESS_LOCAL_READ;
```
This is creating problems for us when translating back to standard read only permissions, where we expect read only registrations to be used only for `FI_WRITE | FI_REMOTE_READ`.

**Comment by j-xiong** [comment]
The man page is correct.  That line can be simply removed -- local read permission is always enabled.

However, providers are allowed to set more permissions than asked for, for many reasons: internal protocol, mr cache, etc. Reverse translation may not work as expected.

**Comment by liuxuezhao** [comment]
Hi Jianxin, for some use cases that probably cause failure if the provider internally set more permissions.

An example use case -
Step1: on node-A, user provides a READ-ONLY buffer (for example a predefined const string like "data to be send...." which is in the .rodata segment) as the source buffer for RMA, so it register by calling fi_mr_regv(..., access, ...) which with "access = FI_REMOTE_READ | FI_WRITE". User send the returned MR descriptor to node-B.
Step2: on node-B it initiate RMA read (fi_read) to transfer the data from A to B.

From manpage, user's behavior in step1 seems correct, but the fi_mr_regv() will fail over verbs provider because calling ibv_reg_mr() to register a READ-ONLY memory with permission of “IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ”. The permission IBV_ACCESS_LOCAL_WRITE violates the READ-ONLY of .rodata segment, so it returns EFAULT (“Bad address”).

**Comment by liuxuezhao** [comment]
another use case maybe more appropriate.
Step 1: on node-A, user allocate buffer (RW) and register to OFI by calling fi_mr_regv(..., FI_REMOTE_WRITE | FI_READ, ...), send the MR descriptor to node B
Step 2: on node-B, user provides a READ-ONLY buffer (for example a predefined const string like "data to be send...." which is in the .rodata segment) as the source buffer for RMA, so it register the buffer by calling fi_mr_regv(..., FI_REMOTE_READ | FI_WRITE, ...). Then node-B initiates RMA write to node-A (read data from local MR descriptor and remotely write to node-A).

This usage seems fully follow manapge's description, but actually no step2, the fi_mr_regv will fail with EFAULT (“Bad address”).

**Comment by shefty** [comment]
I agree with Jianxin.  The line should be removed.  I checked git blame and didn't see any specific reason for it to be there.

RMA permissions usually (or should) map directly, particularly if the application is managing registration.  Permissions for FI_SEND/FI_RECV access frequently include additional permissions needed by the protocol.  For example, large sends are frequently converted into RMA operations.  I don't think that ever changes the read/write aspect of the buffers, however.

The function referenced here is not used in conjunction with mr caching.  But the mr cache does add extra permissions.  That's an implementation restriction of the cache, which doesn't handle entries with different permissions.

**Comment by soumagne** [comment]
Sounds good to me.

We have two sets of buffers that the application can interact with, the ones used for messages are registered with FI_SEND/FI_RECV, the ones that are used for RMA do not have those flags and only use the FI_WRITE / FI_REMOTE_WRITE etc set of flags.

Let us confirm then that removing that line will make @liuxuezhao's test pass.

**Comment by liuxuezhao** [comment]
Yes I have tested the change by removing the line can make my test pass.
I pushed a small ofi patch for it - https://github.com/ofiwg/libfabric/pull/7243 
please inspect at your convenient time, thank you all.
