### ISSUE TITLE
prov/sockets: completions for FI_INJECT flag

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#724]
The fi_msg(3) man page has the following to say about the FI_INJECT flag:

> Applies to `fi_sendmsg`. Indicates that the outbound data buffer should be returned to user immediately after the send call returns, even if the operation is handled asynchronously. This may require that the underlying provider implementation copy the data into a local buffer and transfer out of that buffer.

and the following to say about the fi_inject(3) operation:

> The send inject call is an optimized version of `fi_send`. The `fi_inject` function behaves as if the `FI_INJECT` transfer flag were set, and `FI_COMPLETION` were not. That is, the data buffer is available for reuse immediately on returning from from `fi_inject`, and no completion event will be generated for this send. The completion event will be suppressed even if the endpoint has not been configured with `FI_COMPLETION`. See the flags discussion below for more details.

This seems to me to imply that passing `FI_INJECT|FI_COMPLETION` as flags to `fi_sendmsg` should inject the data but still give me a completion event back.  However, the sockets provider still suppresses the completion in this case.

So either the wording of the man page needs to be changed to indicate that no completion will be generated if the `FI_INJECT` flag is supplied or the sockets provider needs to be fixed to generate a completion in this case.

@shefty @shantonu

**Comment by shefty** [comment]
The sockets provider sounds like it is in error.  The FI_INJECT flag should only return the buffer.

**Comment by jithinjosepkl** [comment]
I have a fix for this. May be we should update manpage also for clarity.
