### ISSUE TITLE
prov:psm2: The nic_fid struct is nil

### ISSUE THREAD

**Issue by flyingdown** [ofiwg/libfabric#7251]
When I use psm2 provider, the program cannot get the nic_fid in fi_getinfo function, and I use "fi_info -p psm2 -v", the output:

> fi_info:
    caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_LOCAL_COMM, FI_REMOTE_COMM, FI_SHARED_AV, FI_RMA_EVENT, FI_SOURCE, FI_NAMED_RX_CTX, FI_DIRECTED_RECV ]
    mode: [ FI_CONTEXT ]
    addr_format: FI_ADDR_PSMX2
    src_addrlen: 16
    dest_addrlen: 16
    src_addr: fi_addr_psmx2://ffff:ff02
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_SEND, FI_TRIGGER, FI_NAMED_RX_CTX ]
        mode: [ FI_CONTEXT ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAR, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAR, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        inject_size: 64
        size: 18446744073709551615
        iov_limit: 13
        rma_iov_limit: 1
    fi_rx_attr:
        caps: [ FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_RECV, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT, FI_SOURCE, FI_DIRECTED_RECV ]
        mode: [ FI_CONTEXT ]
        op_flags: [  ]
        msg_order: [ FI_ORDER_RAR, FI_ORDER_RAW, FI_ORDER_WAR, FI_ORDER_WAW, FI_ORDER_SAS, FI_ORDER_RMA_RAR, FI_ORDER_RMA_RAW, FI_ORDER_RMA_WAR, FI_ORDER_RMA_WAW, FI_ORDER_ATOMIC_RAR, FI_ORDER_ATOMIC_RAW, FI_ORDER_ATOMIC_WAR, FI_ORDER_ATOMIC_WAW ]
        comp_order: [ FI_ORDER_NONE ]
        total_buffered_recv: 0
        size: 18446744073709551615
        iov_limit: 1
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_PSMX2
        protocol_version: 513
        max_msg_size: 4294963200
        msg_prefix_size: 0
        max_order_raw_size: 4096
        max_order_war_size: 4096
        max_order_waw_size: 4096
        mem_tag_format: 0xaaaaaaaaaaaaaaaa
        tx_ctx_cnt: 1
        rx_ctx_cnt: 1
        auth_key_size: 16
    fi_domain_attr:
        domain: 0x0
        name: hfi1_1
        threading: FI_THREAD_SAFE
        control_progress: FI_PROGRESS_MANUAL
        data_progress: FI_PROGRESS_MANUAL
        resource_mgmt: FI_RM_ENABLED
        av_type: FI_AV_UNSPEC
        mr_mode: [  ]
        mr_key_size: 8
        cq_data_size: 0
        cq_cnt: 65535
        ep_cnt: 65535
        tx_ctx_cnt: 2048
        rx_ctx_cnt: 2048
        max_ep_tx_ctx: 2048
        max_ep_rx_ctx: 2048
        max_ep_stx_ctx: 2048
        max_ep_srx_ctx: 0
        cntr_cnt: 65535
        mr_iov_limit: 65535
    caps: [ FI_LOCAL_COMM, FI_REMOTE_COMM, FI_SHARED_AV ]
    mode: [  ]
        auth_key_size: 16
        max_err_data: 64
        mr_cnt: 65535
    fi_fabric_attr:
        name: psm2
        prov_name: psm2
        prov_version: 113.20
        api_version: 1.13
    nic_fid: (nil)

**Comment by shefty** [comment]
I do not see that psm2 implements NIC support.  I believe psm2 will use multiple NICs, so there may not be a direct mapping to a specific HW NIC in all cases.

I doubt psm2 will be updated to report NICs

**Comment by flyingdown** [comment]
> I do not see that psm2 implements NIC support. I believe psm2 will use multiple NICs, so there may not be a direct mapping to a specific HW NIC in all cases.
> 
> I doubt psm2 will be updated to report NICs

Thanks for your reply. I found it needs not get the nic from psm2 api info when use psm2 provider.
