### ISSUE TITLE
prov/shm: Shared locking is incorrect

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7274]
This problem shows up in the following PR:

https://github.com/ofiwg/libfabric/pull/7267

That PR converts the fastlock implementation from a spinlock to a mutex, which results in the shm provider hanging trying to acquire the smr_region::lock of a peer.  E.g.

```
#2  0x00007ffff7a5bfd5 in fastlock_acquire (lock=0x7ffff3c88018)
    at ./include/ofi_lock.h:108
#3  0x00007ffff7a5d74e in smr_send_name (ep=0x5555557a5950, id=0)
    at prov/shm/src/smr_ep.c:206
#4  0x00007ffff7a5da45 in smr_verify_peer (ep=0x5555557a5950, fi_addr=0)
    at prov/shm/src/smr_ep.c:250
```

The problem is that the pthread_mutex cannot be accessed by another process without first setting the PTHREAD_PROCESS_SHARED attribute.  See:

https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutexattr_setpshared.html
https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_09_09

Rewinding the PR, the smr provider currently uses a spinlock (requires it basically to avoid the hang).  However, the fastlock implementation uses this call to initialize the spinlock:

```
#define fastlock_init_(lock) pthread_spin_init(lock, PTHREAD_PROCESS_PRIVATE)
```

I have no idea how this is working because the spinlock is also set to process private and needs to be process shared.

I think the best solution here is for the smr provider to use the pthread calls directly for any locks that are shared between processes.  A mutex may be the best option, so that a peer process doesn't end up spinning its entire time quantum if the lock it is trying to acquire is being held by another process that has been swapped out.

**Comment by j-xiong** [comment]
Not sure why it is not closed automatically by the "fix" comment in #7275. Close it now.
