### ISSUE TITLE
hmem fails to compile when fabric direct mode is used.

### ISSUE THREAD

**Issue by mwheinz** [ofiwg/libfabric#7280]
I did a rebase today of my internal development branch and I can no longer enable fabric direct mode. I haven't identified the commit that introduces the problem, but normal builds build correctly.

The exact error is:

```
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -I./include -D_GNU_SOURCE -D__USE_XOPEN2K8 -DSYSCONFDIR=\"/usr/local/ofi-opx/etc\" -DRDMADIR=\"@rdmadir@\" -DPROVDLDIR=\"/usr/local/ofi-opx/lib/libfabric\"        -I./prov/hook/include   -I./prov/hook/hook_hmem/include  -I./prov/psm2/include   -Wall -O2 -DNDEBUG -g -O3 -MT prov/psm2/src/libpsmx2_la-psmx2_trx_ctxt.lo -MD -MP -MF prov/psm2/src/.deps/libpsmx2_la-psmx2_trx_ctxt.Tpo -c -o prov/psm2/src/libpsmx2_la-psmx2_trx_ctxt.lo `test -f 'prov/psm2/src/psmx2_trx_ctxt.c' || echo './'`prov/psm2/src/psmx2_trx_ctxt.c
prov/hook/hook_hmem/src/hook_hmem.c:1894:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
 ^
```

I've attached a sample configuration log as an example, it uses psm2 but I believe the same problem would occur for any use of fabric direct. [config.log](https://github.com/ofiwg/libfabric/files/7644891/config.log)

**Comment by shefty** [comment]
The hmem hook provider was just merged today, so you shouldn't need to look back very far. :)

**Comment by aingerson** [comment]
Yeah I'm sure this is related to my PR that was just merged. I will take a look.

**Comment by acgoldma** [comment]
Makefile.include has error in it.
https://github.com/ofiwg/libfabric/blob/e26333eef0ac16acc603a88c7f2ce13be70f3de1/prov/hook/hook_hmem/Makefile.include#L1
Should not have `#` at start

**Comment by shefty** [comment]
What @acgoldma just said -- beat me to it by a minute.  endif also needs the # removed

**Comment by aingerson** [comment]
Nice, thanks! I'll patch it
