### ISSUE TITLE
hmem with level-zero: -Werror=stringop-truncation in ze_hmem_init_fds()

### ISSUE THREAD

**Issue by nmerkulo** [ofiwg/libfabric#7292]
I've tried compiling HMEM part of libfabric with level-zero support enabled and all warnings treated as errors. What I get is Werror=stringop-truncation error for hmem_ze.c, line 336. Could we please fix this warning please? 
One possible way I could think of is adding "dev_name[sizeof(dev_name) - 1] = '\0';" after the line but before we ever use dev_name.

**Comment by aingerson** [comment]
@nmerkulo I understand the issue here but I can't reproduce it. I'm building with CFLAGS="-Werror" and it's not failing at that line. Can you provide your configure/CLFAGS so I can make sure we fix this issue for you?

**Comment by nmerkulo** [comment]
@aingerson CFLAGS="-Wall -DNDEBUG -O3 -g3 -Werror -mavx2 -fpic -fPIC -funwind-tables -Wformat -Wformat-security -Wno-address-of-packed-member". It's "-Wall" that is missing in your setup. My bad - didn't highlight that. And this is relatively new warning in gcc (ver >= 8). I am using (GCC) 8.4.1.

**Comment by aingerson** [comment]
@nmerkulo Can you verify #7299 fixes your problem?

**Comment by nmerkulo** [comment]
> @nmerkulo Can you verify #7299 fixes your problem?

@aingerson  Works fine for me. Thank you very much!
