### ISSUE TITLE
fabtests/CI: Add coverage to validate fi_info returned with FI_CONNREQ

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7303]
For background, see #7300.

The fi_getinfo_test will validate the fi_info structure returned by calling fi_getinfo.  However, there's a second way for apps to obtain an fi_info structure, which is when handling an FI_CONNREQ event.  There are no tests that validate such an fi_info
structure is correct.  For example, in #7300, the problem is that the returned fabric_attr::prov_name and abi_version fields were not set.  This was an existing issue which a recent change happened to expose.

**Comment by Juee14Desai** [comment]
This issue is resolved by PR #9355 which has been merged recently. This issue can be closed.
