### ISSUE TITLE
fi_eq.3 questions

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#733]
I see in fi_eq.3 two things that are different than rdma/fi_eq.h:

1. `struct fi_eq_entry`:
  * **Man page:** has a `uint32_t data` field.
  * **Header file:** has a `uint64_t data` field.
1. `struct fi_eq_err_entry`:
  * **Man page:** has no `data` field.
  * **Header file:** has a `uint64_t data` field.

Which is correct in both of these cases?

Also, the contents of the fi_eq_entry.data field is not described in the man page -- it is just labeled with a comment: `/* completion dependent data */`.  Should there be more of an explanation than that?  Or is it really a provider-specific value?

**Comment by jsquyres** [comment]
Just talked to @rfaucett about this; here's what we think:

* The man pages should list a `uint64_t data` in both structs.
* The `fi_eq.3` man page should probably have a sentence or two about the `data` fields, e.g., saying something to the effect of "go look in the other man pages to see what will be put in the data field" for both `fi_eq_entry` and `fi_eq_err_entry`.
* The `fi_av.3` man page should clarify in its description of **FI_EVENT** that the `data` field on the error eq entry will be where the index of the failed insertion will be placed.

I'll go work up a PR to this effect.

**Comment by bturrubiates** [comment]
Since there is already a ticket for questions about fi_eq.3: 
- Should there be a description for fi_eq_write? All of the other operations have lengthy descriptions specifying behavior but fi_eq_write seems to be missing.
