### ISSUE TITLE
prov/tcp: fabtests failed with tcp provider on ARM instance (`eq_readerr` and `cq_readerr`)

### ISSUE THREAD

**Issue by zhngaj** [ofiwg/libfabric#7336]
Hi,

We are seeing the following 3 fabtests failed with tcp provider (libfabric v1.13.x branch, [bbc9278b93eb4ee1681b2bf9daaa26fd3b8ee7ba](https://github.com/ofiwg/libfabric/commit/bbc9278b93eb4ee1681b2bf9daaa26fd3b8ee7ba)) on ARM instance (libfabric). 

Do you have any idea of what issue it could be?
 
```
172.31.9.77 - name:   fi_msg_pingpong -I 5 -v -p "tcp"
172.31.9.77   result: Fail
172.31.9.77   time:   4
172.31.9.77   server_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_pingpong -I 5 -v -p "tcp"  -s 172.31.9.77
172.31.9.77   server_stdout: |
172.31.9.77   client_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_pingpong -I 5 -v -p "tcp"  -s 172.31.5.118 172.31.9.77
172.31.9.77   client_stdout: |
172.31.9.77     [error] fabtests:common/shared.c:2546: eq_readerr (Provider errno: 0) : Success
```
```
172.31.9.77 - name:   fi_msg_epoll -p "tcp"
172.31.9.77   result: Fail
172.31.9.77   time:   3
172.31.9.77   server_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_epoll -p "tcp"  -s 172.31.9.77
172.31.9.77   server_stdout: |
172.31.9.77   client_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_epoll -p "tcp"  -s 172.31.5.118 172.31.9.77
172.31.9.77   client_stdout: |
172.31.9.77     [error] fabtests:common/shared.c:2546: eq_readerr (Provider errno: 0) : Success
```
```
172.31.9.77 - name:   fi_msg_bw -I 5 -p "tcp"
172.31.9.77   result: Fail
172.31.9.77   time:   1
172.31.9.77   server_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_bw -I 5 -p "tcp"  -s 172.31.9.77
172.31.9.77   server_stdout: |
172.31.9.77     Data check error (0!=�) at byte 0 for buffer size 64
172.31.9.77     s already in use)
172.31.9.77   client_cmd: /home/centos/libfabric/fabtests/install/bin//fi_msg_bw -I 5 -p "tcp"  -s 172.31.5.118 172.31.9.77
172.31.9.77   client_stdout: |
172.31.9.77     [error] fabtests:common/shared.c:2530: cq_readerr (Provider errno: 32) : Broken pipe
172.31.9.77     bytes   iters   total       time     MB/sec    usec/xfer   Mxfers/sec
172.31.9.77     64      5       320         0.00s      6.40      10.00       0.10
172.31.9.77     256     5       1.2k        0.00s     85.33       3.00       0.33
```

**Comment by shefty** [comment]
Fabtests is being dumb here.  In this case, there isn't a provider specific error number.  Fabtests should be showing the generic error number, not just the provider error number.  That is, there are 2 error values reported with an EQ error entry -- a generic error number, which maps to some FI_ERRNO value, and a provider specific number.  The print is only showing the latter.

**Comment by shefty** [comment]
PR #7344 updates the prints to show more information.

**Comment by shefty** [comment]
If you can re-run with master, it may provide more details in the error output.  I suspect the broken pipe error is correct, though, and for some reason the connection is being torn down.  I would need more information to determine why.

**Comment by zhngaj** [comment]
Thanks for updating the prints, @shefty. We are not able to reproduce the issue persistently. 
Close the issue for now. If we hit the issue in the future again, we will re-open this issue, and investigate further with the updated errno prints.
