### ISSUE TITLE
fi_cq_read behavior when count==0

### ISSUE THREAD

**Issue by jhh67** [ofiwg/libfabric#7348]
It isn't clear from the `fi_cq` man page if calling `fi_cq_read` with `count==0` is 1) legitimate, and 2) guaranteed to progress the corresponding endpoint. It appears to work for the two providers I've tested, but I'm unsure if I can rely on this behavior for all providers. It would be great if the man page could clarify the expected behavior in this scenario.

**Comment by shefty** [comment]
This is an intentionally undocumented method that is used to drive progress internally without pulling a completion of the CQ (which would require storing the completion somewhere).  For the providers that support this, I don't see it going away for that reason.  We would need to analyze the behavior of all providers to see if we can standardize this feature, which I think we want to do.

**Comment by shefty** [comment]
Man pages were updated to document that a count = 0 may be used to drive progress.
