### ISSUE TITLE
Should the shm provider support FI_PROGRESS_AUTO?

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#7349]
According to https://ofiwg.github.io/libfabric/v1.14.0/man/fi_domain.3.html  
> All providers are required to support FI_PROGRESS_AUTO. However, if a provider does not natively support automatic progress, forcing the use of FI_PROGRESS_AUTO may result in threads being allocated below the fabric interfaces.

It seems that this is not the case for `fi_shm`. The docs at https://ofiwg.github.io/libfabric/v1.14.0/man/fi_shm.7.html can be interpreted either way
> The SHM provider supports FI_PROGRESS_MANUAL. 

Of course an application should try to manage manual progress for performance, but if shm does not satisfy the `fi_domain` requirements the `fi_shm` docs should at least make it very explicit that it does not.

**Comment by shefty** [comment]
@aingerson can respond about the shm provider.

We may need to remove the requirement for auto progress from the man pages.  I think in the case of the shm provider it would result in the creation of a spinning thread on each domain or endpoint that is opened on the system.  If an app spawns 1 process per core, I doubt the resulting system would be usable.

**Comment by wzamazon** [comment]
> We may need to remove the requirement for auto progress from the man pages.

Agreed. EFA provider has the same issue, it does not support progress auto for RMA operations.

**Comment by aingerson** [comment]
Yes, correct. The shm provider would need to allocate a spinning thread and could result in horrible performance issues. I agree with removing the requirement.

**Comment by shefty** [comment]
The fi_domain man page was updated to remove the requirement that providers support auto-progress, with clarification text adding in its place.
