### ISSUE TITLE
prov/ndverbs: New NetworkDirect provider that will be interoperable with the existing verbs provider

### ISSUE THREAD

**Issue by dshinaberry** [ofiwg/libfabric#7351]
A use case for us is to be able to communicate between Windows and Linux hosts using endpoints of type FI_EP_MSG. The current netdir provider uses a wire protocol that differs from the verbs provider which makes this impossible.

This is a proposal to create a new provider, tentatively named ndverbs, that utilizes NetworkDirect and can live alongside the existing netdir provider.

There have been some threads on the mailing list regarding this. See:

- https://lists.openfabrics.org/pipermail/libfabric-users/2021-November/000892.html
- https://lists.openfabrics.org/pipermail/libfabric-users/2021-November/000895.html
- https://lists.openfabrics.org/pipermail/libfabric-users/2022-January/000912.html

A tentative burn down list towards this goal is:

1. Improve fabtests coverage on Windows
2. clone netdir provider to ndverbs provider to provide a known starting point
3. Modify ndverbs provider to use verbs compatible wire protocol for fi_ep_attr: type: FI_EP_MSG protocol: FI_PROTO_NETWORKDIRECT

**Comment by dshinaberry** [comment]
Can I see the results of the CI tests on Windows somewhere? I'd like to compare that with what I am seeing when I run fabtests\scripts\runfabtests.cmd. I am currently seeing 6 failed tests.

6 of 22 tests failed:
"eq_test"
"cq_data"
"rdm_rma_event"
"rdm_tagged_peek"
"bw -e msg -v -T 1"
"rdm_cntr_pingpong -I 5"

**Comment by shefty** [comment]
If the ndverbs provider supports the same protocol as the verbs provider, it should report the same protocol.  I.e. FI_PROTO_RDMA_CM_IB_RC.

To see CI results, look at any open pull request and check the appveyor results.  CI is only run on the sockets provider.  It should be able to run on tcp and udp, but I don't think those were ever setup and might hit into some portability issues that need to be resolved.

The udp provider is the simplest provider to look at as a guide.  The tcp provider is the simplest one supporting msg ep's.  And the verbs provider might be closest to ndverbs.  I would definitely look at those as they've been kept up to date with the common libfabric core code, and any of them might offer better starting points.  Or mix and match as needed?

Btw, after giving this more thought, I do think a separate ndverbs provider is the best path forward.

**Comment by dshinaberry** [comment]
Wanted to drop a note with an update on the approach I've been headed down and make sure it doesn't give anyone a serious case of heartburn.

After spelunking through the code for a while, it seemed like a way to make clear incremental progress was to simply start with the code for the verbs provider. I didn't want to tackle making a fully blown libibverbs/librdmacm for Windows. However, it seemed like it might be relatively straightforward to simply attempt to provide implementations of the libibverbs/librdmacm functions used by the verbs provider as a compatibility layer.  Basically, use the same API and data structures, with wrappers if necessary, but invoke ND API functions where needed.

This seems to be bearing fruit fairly quickly. I have happy path implementations, i.e. no real error handling or reporting, for enough functions that fi_info completes successfully and fi_pingpong makes it as far as completing the connection between the server and client.

So far, I've not had to make any consequential modifications to the verbs code to get things working. It could be feasible to simply use the verbs provider code for Windows with a few strategically placed conditional compilation sections. I have added a lot of headers to include/windows from Linux /usr/include/rdma and /usr/include/infiniband along with some lower level includes they depend upon. I'm guessing I can whittle them down a lot, but didn't want to start there not knowing exactly what would be needed.

Also be aware that I'm only tackling FI_EP_MSG functionality at the moment.

**Comment by shefty** [comment]
I have no objections to having a portable verbs provider.  Note that we try to avoid adding ifdef's into the code as much as possible.  They should definitely be avoided within a function.  As much as possible, isolate OS specific code into the OS files.  As an example, in several cases, we use linux function calls, then provide implementations of those calls on windows.  This is true for some pthread and socket functions.  In other cases, we have generic functions, with OS specific implementations for the different platforms -- e.g. mutex and spinlocks. This mostly just means structuring the code to make it readable and more maintainable.

**Comment by rajachan** [comment]
There was some work done by AWS @ofiwg/aws-efa-team to get the EFA provider, which is also based on rdma-core and the verbs API, running in Windows: https://github.com/aws/libfabric/commits/v1.9.x-cdi

There _might_ be some learnings there you can apply to your work.

**Comment by dshinaberry** [comment]
So, I've finally gotten to sending and receiving and am seeing behavior from the verbs provider that seems to blow up my assumptions regarding what libibverbs requires surrounding memory regions (MR) and and ibv_post_* functions.

I was working under the assumption that when posting buffers for both send and recv that the address of a buffer was required to be in a MR and furthermore that the lkey of the MR had to be supplied as part of the ibv_sge.

The verbs provider is clearly NOT doing this and it obviously works fine. So, is there a finer point about all this that I am missing? Is the documentation for ibv_reg_mr/ibv_post_* just flat out wrong?

Unfortunately, it appears that the ND API, or at least the implementation of it for Mellanox NICs, actually requires this sort of behavior. I was seeing ND_ACCESS_VIOLATION failures for IND2QueuePair::Send calls until I provided the MR lkey. And then, in fi_pingpong::pp_finalize there is a call to fi_sendmsg, in which the verbs provider copies the supplied buffer to an internally allocated one and uses that internal buffer in the call to ibv_post_send, which then fails when I call IND2QueuePair::Send  with the same ND_ACCESS_VIOLATION.

So, If I still want to keep the verbs code unchanged, I'm thinking that I might have to cache all MR creations in order to be able to lookup sge addresses to obtain the lkey before I call IND2QueuePair::Send. And if the sge address doesn't fall within a known MR, I'll have to create an MR especially for that case.

Does anyone have any background, guidance, advice they could provide that might help with this situation?

**Comment by shefty** [comment]
libibverbs requires that buffers passed to ibv_post_send/recv need to be registered with a valid lkey.  The exception is for what verbs calls 'inline data', which are smaller buffers (< 400 bytes or so) that don't need to be registered.  The OFI (mostly) equivalent to that are inject buffers.  Inline/inject buffers do not need to be registered, as they're copied directly into the underlying send command queue.

ND should have an equivalent setting.  You may be able to disable inline transfers by setting max_inline_data = 0.  I would look at having vrb_find_max_inline() return 0 to start with, and later updating it to return a usable value.

Transmit operations go through the vrb_post_send() call.  Non-inline transfers will call that from vrb_send_buf() or vrb_send_iov(), depending on whether an sgl is needed.  Those paths will set the lkey as needed.  (Those paths also support inline transfers, which is why you see checks where the lkey may not be set).

As a side note, there's a MR cache available in tree, but it only works on Linux.  I don't know if you can get events on windows about changes to the virtual to physical page mappings, which are needed to keep the cache in a consistent state.

**Comment by dshinaberry** [comment]
So, I've got something that's working for "fi_pingpong -e msg" and in the context of our application. Now, I'm starting to look into fabtests.

I figured that I'd try to achieve the same fabtests coverage that I see with the verbs provider on Linux. When I ran ```./runfabtests.sh -vvv -p /home/dshinaberry/bin -t all verbs 192.168.2.83 192.168.2.83```, I got the following output:

```
# ------------------------------------------------------------------------------
# Total Pass                                                29
# Total Notrun/Excluded                                     65
# Total Fail                                                 0
# Percentage of Pass                                       100
# ------------------------------------------------------------------------------
```

I wanted to check to see if this was accurate. It seemed odd that there were more excluded tests than tests run. I wasn't able to see any of the CI test output for PRs for Linux like I can for Windows as it appears all the links go to URLs that require authentication.

Of the 29 tests run on Linux, only 13 of them are actually built in the Windows context. And of those 13, 6 of them currently pass with 7 failing.


There are a handful of issues I encountered that required some changes to verbs or common code. I'm fairly certain the changes I needed to make to get things to work on Windows will be fine for Linux as well.

Would you like me to create separate issues for these things and start providing PRs with changes that address them or would you rather I wait until everything is finished including fabtests?


I guess the same question applies to the main effort. Should I tidy and polish things for a PR or do you want to wait until after the fabtests are working?

And a question about what your preference is for all the headers I needed to bring over from Linux and add under include/windows. I was completely unselective to start with and currently have around 250 header files, many of which are likely not really required. Not sure if you'd like me to winnow the wheat from the chaff to just have the minimum necessary or dump them all in as is.

**Comment by shefty** [comment]
This sounds great.

The number of excluded tests _may_ be reasonable.  Many of the fabtests make use of rdm endpoints, which verbs/tcp/netdirect will not support without also including rxm.  Plus there's maybe 10 tests that require shared receive or transmit queues, plus dgram endpoints.  I did a quick test on my system with the tcp provider, and I see 55 run/29 not run.  If you post the full output as to which tests ran, it may help identify if they were excluded intentionally or for a lack of features.

I would prefer to analyze and merge changes as soon as they are ready.  There's no need to wait until all tests pass, as long as current code does not break.  There's is also not a need to open a new issue before submitting a patch.  The issues are more to track work that needs to be done.  It's fine for a patch to describe the issue and changes made to handle it.  But feel free to open issues as needed.

We definitely don't want to dump in 250 new header files.

**Comment by dshinaberry** [comment]
I looked a little closer at the tests. The run I referred to was initiated from the fabtests/scripts directory and I think it picked up exclusions from the ../test_configs/verbs/verbs.exclude. When I ran it from the installation directory I saw:
```
# ------------------------------------------------------------------------------
# Total Pass                                                67
# Total Notrun/Excluded                                     26
# Total Fail                                                 1
# Percentage of Pass                                        98
# ------------------------------------------------------------------------------
```
The failure was on ```fi_multi_mr -e rdm -V -p "verbs"``` and I saw this even using the current main branch. I've attached the output if you care to look at it: [fabtests.log.log](https://github.com/ofiwg/libfabric/files/8218187/fabtests.log.log)

I did discover that I broke fi_eq_test with one of my changes. So, I'll make sure I figure that issue out before submitting a related patch.


With regard to the include files, I've managed to winnow it down to 19 new header files. Not sure whether that would be acceptable or not. Up to this point, I haven't had to make any major edits to any of the files. To get to any fewer will require some serious slicing and dicing. I'm happy to do that if you'd like. Here is the current list of new header files I have:

- include/windows/bits/byteswap-16.h
- include/windows/bits/byteswap.h
- include/windows/bits/endian.h
- include/windows/bits/types.h
- include/windows/bits/typesizes.h
- include/windows/bits/wordsize.h
- include/windows/endian.h
- include/windows/features.h
- include/windows/gnu/stubs.h
- include/windows/infiniband/ib.h
- include/windows/infiniband/ib_user_ioctl_verbs.h
- include/windows/infiniband/sa.h
- include/windows/infiniband/verbs.h
- include/windows/infiniband/verbs_api.h
- include/windows/linux/types.h
- include/windows/rdma/ib_user_verbs.h
- include/windows/rdma/rdma_cma.h
- include/windows/stdc-predef.h
- include/windows/sys/cdefs.h

I think a lot of the non-infiniband/rdma ones stem from needing endian.h because I lifted addrinfo.c directly from librdmacm. I could try to winnow those further.

**Comment by j-xiong** [comment]
> include/windows/linux/types.h

Kind of weird to see linux under windows path, maybe remove `linux` from the path?

**Comment by shefty** [comment]
Did you pull in the libibverbs and librdmacm source files from linux for the windows build?  Can you explain how you structured the implementation?  Are the headers just to get the build working, or did you layer the verb APIs over ND?

**Comment by dshinaberry** [comment]
I pulled in the infiniband/* and rdma/* header files from linux in order to simply reuse the structure definitions and function declarations and commented out inline function definitions.

Then I crafted implementations of just those libibverbs/librdmacm functions that the verbs provider currently uses. I did not start with the actual linux implementations for those functions, but consulted them to get some semantic information so that I could mimic the behaviors using ND as closely as possible.

When I got to the code that deals with getting address information and binding addresses, librdmacm had the file addrinfo.c that was independent enough that it made sense to just take that implementation in its entirety rather than write similar code from scratch.

So, functionally what exists now on windows is a very thin, not robust at all, implementation of many libibverbs/librdmacm functions. I don't want to call it a windows version of those libraries because it is not exhaustive in what functions are implemented but tightly focused on just what the verbs provider uses. So, in this sense the verb APIs are layered over ND.

It also isn't packaged as a library either. It's currently just a few new files located in prov/verbs/src that provide the function definitions for the rest of the verbs code to link against. I'm open to suggestions as to where exactly to place the new code in the directory tree to make clear that it isn't part of the linux verbs provider. The new files won't be part of the makefiles for linux; they will only be in the VS project along with the rest of the verbs provider files.

**Comment by shefty** [comment]
What you did with the headers sounds reasonable and wrappers sounds reasonable.  We'll just need to look at other details to verify that there's not some other structure of the code that makes sense.  FWIW, for the libfabric core, we have src/linux, src/windows, etc. to separate OS specific implementations.  We could consider the same for prov/verbs/src/windows for windows specific build files.

**Comment by dshinaberry** [comment]
I now have most of the 94 tests that run against verbs on Linux running on Windows. The only ones that are not running, but they are building, are the negated unit tests and the multinode tests. Also, the Windows runfabtests.cmd doesn't check the exit codes and categorize any tests as 'notrun' like the Linux runfabtests.sh does.

I'm assuming you don't mind if I attempt to make runfabtests.cmd more like runfabtests.sh in these areas? Is there anything I should know about the direction of fabtests before I undertake these changes? I've seen some activity related to using Python, so I'm not sure where things are going for the future.

Most of the tests that are failing are because of functionality that I haven't implemented on Windows. Specifically:
- modes other than IBV_WR_SEND in ibv_post_send;
- ibv_create_srq
- ibv_create_ah

I've got some questions about where to go for some other tests...

Four tests fail because they invoke code that is conditionally compiled based on the macro HAVE_EPOLL. It seemed to me that since there is the Windows wrapper that emulates epoll, we ought to be able to get these working. I naively tried just defining HAVE_EPOLL on Windows, but that didn't work. Any guidance or advice on whether/how to handle these?

cq_test uses 32k CQs by default. I ran into problems with resources and was seeing errors like ENOBUFS. I tweaked the registry to increase the number of ephemeral TCP ports based on [this](https://docs.microsoft.com/en-US/troubleshoot/windows-client/networking/connect-tcp-greater-than-5000-error-wsaenobufs-10055). Up to 8k works fine, but more than that starts to slow down significantly resulting in timeouts. 8k takes 12-20 seconds, while 16k took 1:48 (6-7x time for 2x CQs). I suppose we could just cut back on the number used by default either in the test code or by using the -L command line option when invoking it on Windows. I also wondered whether the performance would improve if we moved from AF_INET sockets to AF_UNIX sockets. I'd read about them becoming available on Windows although there still isn't a socketpair implementation. I came across an open source implementation of it using AF_UNIX sockets [here](https://gitlab.com/openconnect/openconnect/-/merge_requests/320/diffs).

rdm_rma_event would fail because ibv_create_ah is not implemented, but fails before that because the IB UD address is flagged as invalid. It selects verbs;^ofi_rxd in it's attempt and rejects verbs;^ofi_rxm which seems like it could work. It looks like it rejects rxm because that doesn't support the FI_RMA_EVENT flag. My naive reading of the FI_RMA_EVENT flag made me think that rxm could support that like rxd does. Why am I wrong about that?

**Comment by shefty** [comment]
I would prefer runfabtests.cmd to match runfabtests.sh as much as possible.  The python scrips should be viewed as an addition.

If we're missing functionality, we're okay skipping those tests on windows.

HAVE_EPOLL is problematic.  The fabtests in question request FI_WAIT_FD as a wait object.  That's only supportable if HAVE_EPOLL is defined, as the wait object must be an int fd.

The epoll abstraction that we use internally for libfabric defines an abstract data type, ofi_epoll_t, to use as the epoll 'fd'.  When epoll is available, ofi_epoll_t is an int fd.  When epoll is not available, that is a struct ofi_pollfds * pointer.  The latter is not something that can be exposed directly to apps.

Since those tests have been written, we've added an FI_WAIT_POLLFD object.  That would be usable in cases where HAVE_EPOLL is not available.  But it would require updating the tests, and possibly libfabric, to use that.

For the cq_test, I would go the route defining different default cq values for unix and windows, with a comment indicating why windows is lower.

rxm;verbs uses the native RDMA calls for RMA read/write operations.  The calls pass directly through.  So, the library at the peer does not know that an RMA operation has actually been performed.  rxd;verbs on the other hand emulates RMA read/write operations through packet segmentation and reassembly.  So, the target knows that an RMA has occurred and can generate an event 'free of charge'.  There's significant overhead involved if rxm;verbs attempts to do the same, as it requires the initiator to send a separate message after the RMA to indicate that an RMA has been performed.  And the initiator would need to do this without knowing if the target was even wanting those events.  So this is a feature that we'll not want to add to rxm.

**Comment by dshinaberry** [comment]
I think I'm down to just one more issue that needs handling related to fabtests before I can start creating some PRs for these changes. I wanted to get your input on how you'd like to handle it.

It's similar to the issue I created related to environment variables and how they exist inside of a runtime that is coupled with either the library or the executable. This issue is with memory allocation and the fact that malloc/free pairs cannot cross the executable/library boundary.

Lots of the tests take something like the provider as a command line argument, strdup it and put it in the hints fi_info structure that was obtained from fi_allocinfo. When fi_freeinfo is called, it calls the libfabric free on the provider name that was allocated by the application, which is invalid to do.

One approach would be to switch from statically linked runtimes to force all the modules to link to the runtime dynamically, which would then remove this issue according to the research I've done.

Another approach would be to add libfabric api(s) to allow an application to request the library use its malloc to put something into an fi_info so that everything that is later freed came from the same module.

**Comment by shefty** [comment]
A way to handle this would be for the app to reset the provider name to null prior to calling fi_freeinfo().  The app would then need to free the memory.

**Comment by dshinaberry** [comment]
Yeah, that's true; I should have mentioned that too. And that approach is not really any more or less awkward than adding a libfabric api.

It's an annoying and somewhat insidious issue because it only easily comes to light in debug builds because it causes an assert, but only happens if the allocated memory happens to be in the head or tail position of the list of all allocations that have occurred. In a release build, it would probably lead to corruption of the heap with a delay before things destabilize enough to lead to a crash.

So, is your preference that I update the tests so that they free any memory they allocated and placed into an fi_info structure?

**Comment by shefty** [comment]
Yes, I think that's preferable.  It's likely not too difficult given most of the cleanup code is common.

**Comment by dshinaberry** [comment]
I've a couple more questions on tests.

1. I wondered whether or not you have a more relaxed conditional compilation stance with tests. Apparently using SO_REUSEADDR in setsockopt has slightly different semantics on windows than on linux. In multinode/harness.c it uses this and relies on bind to fail for all but the first instance. However, on windows all three sockets successfully bind to the same port.
Removing the use of SO_REUSEADDR on windows solves this issue, but it still needs to be there on linux.
So, I wondered whether it would be acceptable to just wrap that code block with #ifndef _WIN32 or if you would prefer me to implement OS specific instances of the pm_conn_setup function.
2. I can't see the output from the linux CI tests in PRs, so I'm not sure whether the verbs provider is always tested or not and what the results are. Howwever, on my linux system I consistently get a failure for _fi_multi_mr -e rdm -V -p "verbs"_ The server instance exits with a ENOSYS for fi_bind_mr and the client exists with an ENODATA.
Not sure whether I need to dig deeper into that or not. It fails on my windows system with the same exit codes as for my linux system.

**Comment by shefty** [comment]
For 1, I would implement OS specific instances of the functions.  But I don't understand yet why there should need to be different implementations.  Why is SO_REUSEADDR needed on Linux?

For 2, it may help to look under fabtests/test_configs.  There's exclude files there that will indicate if a specific test is excluded from CI.  The fi_multi_mr test is excluded for verbs and ofi_rxm, so it looks like it's skipped.  Looking at the source code, the test uses counters and RMA events, which I don't think are supported by verbs (or most providers really).

**Comment by dshinaberry** [comment]
I think I understand what's going on now for 1.

On linux, bind will fail with EADDRINUSE if another socket has bound and listened on the same port even if SO_REUSEADDR has been set. So, the first instance will bind and then listen becoming the server and subsequent instances will fail at the bind and become clients. However, I think this would also be the behavior without SO_REUSEADDR.
On windows, all of the instances will successfully bind and listen when SO_REUSEADDR is set, which is a problem.

It appears that the purpose SO_REUSEADDR is serving on linux is to allow a multinode test to run again before the TCP TIME_WAIT duration has expired.
On windows, it would appear that a port being in the TIME_WAIT state doesn't preclude a new process binding to that port.

So, with the SO_REUSEADDR present, it won't work correctly on windows. And without the SO_REUSEADDR, it won't work correctly for back to back multinode tests on linux.

**Comment by shefty** [comment]
If you remove the setsockopt() call from windows, can the test run?  We could remove that call from linux as well and verify that things usually work.

**Comment by dshinaberry** [comment]
Removing the setsockopt call from windows will let everything work correctly as expected.

Removing that call from linux would allow any single run of a multinode test work correctly as expected. However, any automation that uses runfabtests to run the multinode test set will wind up having only the first test finish successfully and all the subsequent ones fail because they would be blocked from using the port due to it being in the TIME_WAIT state after the first test finished.

I suppose an alternative would be to modify the multinode tests so that they specify the destination address on the command line like the other client/server tests do. Then the underlying code wouldn't be needed to try and dynamically distinguish between which instance is going to be the server and which the clients.

**Comment by shefty** [comment]
Bah - what a pain.  Looking at the code, I honestly think the best option is to insert an ifdef into the middle of the function with a comment about how calling setsockopt on windows breaks things.  The reason for the code here is to handle the case where there are multiple instances of multinode running on the same system, and we're using a job launcher to start the tests.  So all instances receive the same command line args.

**Comment by dshinaberry** [comment]
Is it safe to assume that the new ndverbs provider will be available in release 1.16.0? Any idea when that might be?

**Comment by shefty** [comment]
Yes, everything should be in v1.16.  My guess is v1.16 would hit in August.  Is there a specific target date that you were hoping for?

**Comment by dshinaberry** [comment]
Nope, no specific date I was shooting for. My manager had been asking because he wants to schedule a demo of Linux/Windows interoperability for some internal groups, but wants to do it with a build of officially released software from the project repository.

**Comment by shefty** [comment]
The verbs provider support for network direct has been upstream for a while now.  Closing as done.
