### ISSUE TITLE
DAOS: tcp;ofi_rxm  ctrl+c out of client app during rdma transfer crashes server/mem corruption

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#7367]
This is a report similar to https://github.com/ofiwg/libfabric/issues/6665, but only affecting tcp;rxm using v1.14.0rc3

Corresponding DAOS ticket: https://daosio.atlassian.net/browse/DAOS-9168

Creating this ticket to track this issue, will add additional infomration as it becomes available.

Current reproduction reported for DAOS:
"using 2.0 release branch or master DAOS:
run the h5_partest_t_bigio test
then killed client test during its run causes a server segfault.
This happens with tcp provider only, so not a 2.0 blocker since tcp is not officially required for 2.0

1 server, 2 engines
on client, mkdir /tmp/user
run HDF5 VOL test:
export HDF5_PLUGIN_PATH=/home/mschaara/source/vol-daos/build/bin/; export HDF5_VOL_CONNECTOR=daos;
mpirun -wdir /tmp/user -np 10 --genvall /home/mschaara/source/vol-daos/build/bin/h5_partest_t_bigio
after running, kill the test during the second phase of the test:

Testing Dataset1 write by ROW

Testing Dataset2 write by COL
ctrl-c

server segfaults"

One of crash logs/mem corruptions:

boro-18: *** Error in `/home/mschaara/install/daos/bin/daos_engine': double free or corruption (out): 0x00007ef9a5d96140 ***
boro-18: ======= Backtrace: =========
boro-18: /lib64/libc.so.6(+0x81329)[0x7efc34c2f329]
boro-18: /home/mschaara/install/daos/bin/../lib64/../prereq/dev/mercury/lib/../../ofi/lib/libfabric.so.1(+0x23bf8)[0x7efc2f22ebf8]
boro-18: /home/mschaara/install/daos/bin/../lib64/../prereq/dev/mercury/lib/../../ofi/lib/libfabric.so.1(+0x76d21)[0x7efc2f281d21]
boro-18: /home/mschaara/install/daos/bin/../lib64/../prereq/dev/mercury/lib/../../ofi/lib/libfabric.so.1(+0x77eb0)[0x7efc2f282eb0]
boro-18: /home/mschaara/install/daos/bin/../lib64/../prereq/dev/mercury/lib/../../ofi/lib/libfabric.so.1(+0x78071)[0x7efc2f283071]
boro-18: /lib64/libpthread.so.0(+0x7ea5)[0x7efc35a7fea5]
boro-18: /lib64/libc.so.6(clone+0x6d)[0x7efc34cac9fd]

**Comment by shefty** [comment]
FWIW, see #7396.  There is an issue with tcp reporting error completions for 'inject' messages.  Those completions can result in rxm accessing invalid memory.  This may be related.

**Comment by frostedcmos** [comment]
We've retried with the latest OFI main today and still hitting similar mem corruption on server side when client is ctrl-c-ed out during rdma transfer.

Corruption at many times manifests itself in server receiving 'garbage' RPC payload with fields containing bad values and/or buffers being invalid. Other times we see double free/corruption message as above in ofi stack.

**Comment by shefty** [comment]
double free is a problem. Aborting an RMA transfer in the middle should result in the RMA simply stopping.  I'm not sure what you mean by the server receives garbage.  How does this issue relate to #7367 ?

**Comment by frostedcmos** [comment]
after the client abruptly exits while rdma is done from/to it, the next rpc that the server receives many times appears to have been corrupted. sometimes inline rpc fields are just all set to 0, other times input/output buffers end up being invalid/access violation when trying to dump them in gdb/coredump.

>How does this issue relate to https://github.com/ofiwg/libfabric/issues/7367 ?
not sure what you mean, this is that issue...

**Comment by shefty** [comment]
Sorry, I copied the wrong number.  I meant #7417

**Comment by frostedcmos** [comment]
Issue in 7417 seems to happen on the initial connect attempt based on the flow of the test. The test executes a client that sends a simple rpc payload to the server; that payload does not involve rdma/bulk. 

This current issue on the other hand seems to be hit when clients are killed/aborted while rdma is ongoing.

**Comment by shefty** [comment]
I suspect the underlying problem is the result of the killed connection.  #7457 restructured the locking in the endpoint cleanup code and has been merged.  Please try to reproduce with main with those changes included,

**Comment by shefty** [comment]
Also, maybe running with valgrind might help, if that's possible.  libfabric has a --with-valgrind build option.

**Comment by shefty** [comment]
See #7713 for a valgrind trace.  I believe the issue has been identified.  Working toward a fix, with a target to include into v1.15.0 release.

**Comment by shefty** [comment]
The problem identified with this issue should be fixed, with the fix available in v1.15.  Issue #7758 was opened to track a segfault which source is not yet identified.
