### ISSUE TITLE
prov/shm: fails ubertest with non-debug build

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7371]
Just noticed that shm provider will fail on uber test, with non-debug build.

To reproduce.

On server, run
```
fi_ubertest -x
```
On client, run
```
fi_ubertest -u /fsx/ALinux2/opt/fabtests/share/fabtests/test_configs/shm/all.test 127.0.0.1
```

On server, there is a segfault 
```
Starting test 426:
bw                                                16      5       80          0.00s      1.51      10.60       0.09
bw                                                192     5       960         0.00s     36.92       5.20       0.19
bw                                                768     5       3.7k        0.00s    101.05       7.60       0.13
bw                                                3k      5       15k         0.00s       inf       0.00        inf
bw                                                12k     5       60k         0.00s       inf       0.00        inf
bw                                                48k     5       240k        0.00s       inf       0.00        inf
bw                                                192k    5       960k        0.00s       inf       0.00        inf
bw                                                768k    5       3.7m        0.00s       inf       0.00        inf
bw                                                3m      5       15m         0.00s       inf       0.00        inf
Ending test 426, result: Success
Starting test 427:
Segmentation fault (core dumped)
```
Note, this error goes away with a debug build. So I guess it is related to memory alignment

**Comment by aingerson** [comment]
Looking into it, but I cannot reproduce this at all.

**Comment by wzamazon** [comment]
@aingerson 

What OS were you using?

From what I can tell, this error happens on amazon linux 2 and ubuntu 18.04, but not on rhel 8.

**Comment by aingerson** [comment]
ah I'm using rhel. I'll try on ubuntu. Thank you for the information!

**Comment by wzamazon** [comment]
I did a little debug on ubuntu, and I can confirm that error happens with INT128 with CSWAP. The segfault happened in `smr_do_atomic` when `src` and `cmp` is not aligned on 16 bytes boundary.

Further debug show that the segfault happens when `smr_do_atomic` is called by `smr_progress_inject_atomic`. In which `src` is pointing to `ep->region + inj_offset`, and `inj_offset` is `cmd->msg.hdr.src_data`. So the problem appears to be because `cmd->msg.hdr.src_data` is not always multiple of 16.

**Comment by shefty** [comment]
Do we just disable 128-bit atomic support from shm?

**Comment by wzamazon** [comment]
> Do we just disable 128-bit atomic support from shm?

EFA provider currently does that. An alternative is to `memcpy` data from pointer to a variable of type `int128_t`, which is not very efficient.

**Comment by shefty** [comment]
Do we know if the problem is alignment coming from ubertest buffers or is it the shm bounce buffer or cmd buffer?

**Comment by shefty** [comment]
Okay, shm does this:
```
	cmd_queue_offset = ofi_get_aligned_size(sizeof(struct smr_region), 16);
	resp_queue_offset = cmd_queue_offset + sizeof(struct smr_cmd_queue) +
			    sizeof(struct smr_cmd) * rx_size;
	inject_pool_offset = resp_queue_offset + sizeof(struct smr_resp_queue) +
			     sizeof(struct smr_resp) * tx_size;
	sar_pool_offset = inject_pool_offset + sizeof(struct smr_inject_pool) +
			  sizeof(struct smr_inject_pool_entry) * rx_size;
	peer_data_offset = sar_pool_offset + sizeof(struct smr_sar_pool) +
			   sizeof(struct smr_sar_pool_entry) * SMR_MAX_PEERS;
	ep_name_offset = peer_data_offset + sizeof(struct smr_peer_data) * SMR_MAX_PEERS;
```
There's no specific alignment applied to the various pools/queues, which may not be a bad thing to have anyway.  It'll take some time to analyze the structure sizes and figure out how to layout the data.  I'm more interested in cache size alignment than 128-bit atomics.

**Comment by aingerson** [comment]
The issue is in the alignment of the smr freestack header which misaligns the entry buffer. I have a patch that fixes the alignment for 128 bit atomics but it breaks some other use of the freestack in the tagged case. I'm looking into it.

**Comment by shefty** [comment]
Can we just disable 128-bit atomics as the short term fix and come back to this later?  Unless you're close to fixing this.

It seems that we might want every queue above to start at a given alignment, plus decide if every structure should be some aligned size.  Then adjust the allocation, so that it doesn't roundup to a power of 2 just to have a bunch of empty space that goes unused.  In short, it looks like the changes might be more involved.

**Comment by aingerson** [comment]
I'm not close to fixing it. I'm fine with just disabling it. I don't like the idea of having a lot of empty space just for the sake of adding 128 bit atomic support to shm.
