### ISSUE TITLE
re-enable coverity scans

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7372]
coverity was disabled when switching from travis to github actions.  (We lost travis due to newly imposed limits.)  PR #7370 adds coverity to the actions.   But the scan failed with too little code compiled.

```
Warning:  Emitted 181 C/C++ compilation units (28%) successfully
```

**Comment by rajachan** [comment]
I was just looking at this as well. Per https://community.synopsys.com/s/article/Coverity-fails-to-parse-system-header-cmathcalls-h, we need to configure the build with the flags suggested there. I'm testing the change locally now.

**Comment by rajachan** [comment]
For reference, there's a whole bunch of this in the coverity log (which I should add as a build artifact that can be looked at from the PR itself):

```
"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 55: error #1044:
          _Complex can only be used with floating-point types
  __MATHCALL (cacos, (_Mdouble_complex_ __z));
  ^

"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 55: error #1044:
          _Complex can only be used with floating-point types
  __MATHCALL (cacos, (_Mdouble_complex_ __z));
  ^

"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 55: error #1044:
          _Complex can only be used with floating-point types
  __MATHCALL (cacos, (_Mdouble_complex_ __z));
  ^

"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 55: error #1044:
          _Complex can only be used with floating-point types
  __MATHCALL (cacos, (_Mdouble_complex_ __z));
  ^

"/usr/include/x86_64-linux-gnu/bits/cmathcalls.h", line 57: error #1044:
          _Complex can only be used with floating-point types
  __MATHCALL (casin, (_Mdouble_complex_ __z));
  ^

Emit for file '/home/raghu/libfabric/prov/hook/hook_hmem/src/hook_hmem.c' complete.
[ERROR] 5 errors detected in the compilation of "prov/hook/hook_hmem/src/hook_hmem.c".
WARNING: cov-emit returned with code 1 for prov/hook/hook_hmem/src/hook_hmem.c
```

**Comment by rajachan** [comment]
Looks like https://github.com/ofiwg/libfabric/actions/runs/1694537647 failed the action. Running it for each PR is going to be problematic (the access tokens are not shared with PRs from forks of the repo). I'll switch it out to a cron job to prevent this.

**Comment by rajachan** [comment]
Your PR failed due to an auth issue:
```
Run wget https://scan.coverity.com/download/linux64 --post-data "token=&project=ofiwg%2Flibfabric" -O coverity_tool.tgz
--2022-01-13 19:52:38--  https://scan.coverity.com/download/linux64
Resolving scan.coverity.com (scan.coverity.com)... 45.60.34.99
Connecting to scan.coverity.com (scan.coverity.com)|45.60.34.99|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed
```

I'd seen this earlier when testing from a fork-based PR. Github intentionally doesn't allow public forks to access secrets (otherwise, anyone can then create a PR and read all our secret key-values). PR coming up to fix this...
