### ISSUE TITLE
Fix bugs reported by clang-analyzer

### ISSUE THREAD

**Issue by rajachan** [ofiwg/libfabric#7376]
I have attached a report of scan-build run against libfabric main branch [here](https://github.com/ofiwg/libfabric/files/7866474/libfabric-scanbuild.zip). There are over a 100 issues categorized as API, Dead stores, Logic errors, Memory errors, or Unix API errors. Extract the attachment and open index.html to view the report.

There are a handful of false-positives and duplicates, but there is a sizable number of fixable issues.

To generate this report locally:
- Install clang-tools (On an apt-based system, `sudo apt install clang-tools`)
- Run configure and make through scan-build:
  - `scan-build ./configure --prefix=$PWD/install --enable-debug`
  - `scan-build --keep-cc make -j32`
- View the generated report locally in a browser with scan-view:
  - `scan-view /tmp/scan-build-2022-01-13-210840-30869-1/`

**Comment by j-xiong** [comment]
Did #7387 fix all the non-false-positive issues or are there more work to do here?

**Comment by shefty** [comment]
I'm not sure.  I didn't install the clang-tools and run a new scan.  I only tried to address the issues in the report.
