### ISSUE TITLE
Return value when reading from empty event/error queue.

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#738]
The man page for fi_eq does not specify the behavior for reading from an empty event/error queue when using a non-blocking read. 

The usnic provider seems to return -FI_EAGAIN, while the sockets provider seems to return 0. libc read returns EAGAIN, is this the appropriate way to handle it? 

@jsquyres @goodell @sayantansur @jithinjosepkl

**Comment by shantonu** [comment]
The man page says fi_eq_read "returns the number of bytes read" in "Return Values" section. We discussed this issue in #708 and @shefty commented that both "-EGAIN" and "0" are valid but 0 is more reasonable. For sockets provider we decided to return 0 in case of empty event queue. But we need to be consistent with all the providers.

**Comment by bturrubiates** [comment]
Yes, consistency is good. After this discussion the man pages need to updated. I could do that. I'm of the opinion that for a non-blocking read we should return EAGAIN like the libc read call (note that on linux EWOULDBLOCK is also a valid return).

Also, I think it's important to discuss the semantics of the attr.size field for opening an EQ. The man page states "Specifies the minimum size of an event queue.". I hadn't noticed there was a test for overflow in the EQ test. I'm currently implementing EQs assumed that meant a lower bound on the guaranteed size but allowed for growing. 

@shefty, could we get some clarification?

**Comment by patrickmacarthur** [comment]
Just to throw my two cents in, I would rather see it return 0 in this case since it will most likely be used in a tight loop, and comparing against zero is most likely faster than comparing against `-FI_EAGAIN` to see if we have to loop around again.

But I agree that the most important thing is that all providers are consistent.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jsquyres** [comment]
I did not write this code (probably @rfaucett or @xuywang did...), but if I had to guess, I'd say we return -FI_EAGAIN for the following reasons:

* Any negative number can be assumed to be an error
* FI_EAGAIN (vs. EAGAIN ) to FI-ize the return code
* -FI_EAGAIN returns more semantic information than just plain 0
* EAGAIN is returned from regular read(2) in these kinds of cases

**Comment by shantonu** [comment]
@bturrubiates, regarding attr.size, the provider may choose to buffer events. In that case, underflow test should allow "write success" as a valid test result for fi_eq_write. In sockets provider, we don't restrict the eq size to the size attribute.

**Comment by bturrubiates** [comment]
@shantonu Thanks for the clarification. Seems that isn't an issue for me then. 

@jsquyres My phrasing was poor. I agree with the usnic provider returning -FI_EAGAIN. I think it provides more useful information. It depends on whether we considering reading from an empty queue an exceptional event or not. 

@patrickmacarthur Hmm, I hadn't considered the performance approach. I think it depends highly on the instruction set of the processor for whether or not it would actually be faster. I could see how comparing against zero could be quicker (xor vs cmp), but the real question is whether it is negligible or not.

**Comment by jsquyres** [comment]
@patrickmacarthur I'm not an assembly expert, but I'd guess that comparing against a nonzero integer constant is just as efficient as checking against 0...?

**Comment by shefty** [comment]
The X86 comparisons instructions are done by checking a "0"-bit in the flags register.  This was selected by the x86 architects for performance reasons.  It's been a while since I've dealt directly with assembly, but I think Patrick is correct.  Checking for 0 will mostly likely be more efficient.

The basic flow would end up being:

ret = read_eq(..)  <-- sets 0-flag based on whether return code is 0 or not
while (ret)        <-- checks 0-flag and jumps

versus

ret = read_eq(...)
while (ret == -FI_EAGAIN)  <--  performs comparison to set 0-flag
				   <--  checks 0-flag and jumps

**Comment by shefty** [comment]
Btw - I agree that we should have a consistent return code, regardless of it being 0 or EAGAIN.

The EQ size should be a minimum, not a max.

**Comment by goodell** [comment]
> The X86 comparisons instructions are done by checking a "0"-bit in the flags register.  This was selected by the x86 architects for performance reasons.  It's been a while since I've dealt directly with assembly, but I think Patrick is correct.  Checking for 0 will mostly likely be more efficient.

I disagree about this.  A comparison or some sort of test instruction must still be executed to set the flags register (simply returning from a function isn't sufficient to set the flags).  For example:

```c
static __attribute__((__noinline__)) int foo(void)
{
    volatile int ret = -EAGAIN;
    return ret;
}

int main(int argc, char **argv)
{
    while (foo() == -EAGAIN) {
        __asm__ __volatile__ ("nop // loop body 1");
    }   
    while (foo()) {
        __asm__ __volatile__ ("nop ; nop // loop body 2");
    }   
    
    return 0;
}   
```

Yields this `main` when compiled with clang on my Linux box (spacing added by me to me to clarify structure):
```
0000000000000000 <main>:
   0:   50                      push   %rax
   1:   eb 0e                   jmp    11 <main+0x11>
   3:   66 66 66 66 2e 0f 1f    data32 data32 data32 nopw %cs:0x0(%rax,%rax,1)
   a:   84 00 00 00 00 00 

  10:   90                      nop
  11:   e8 1a 00 00 00          callq  30 <foo>
  16:   83 f8 f5                cmp    $0xfffffffffffffff5,%eax
  19:   75 07                   jne    22 <main+0x22>
  1b:   eb f3                   jmp    10 <main+0x10>

  1d:   0f 1f 00                nopl   (%rax)

  20:   90                      nop
  21:   90                      nop
  22:   e8 09 00 00 00          callq  30 <foo>
  27:   85 c0                   test   %eax,%eax
  29:   75 f5                   jne    20 <main+0x20>

  2b:   31 c0                   xor    %eax,%eax
  2d:   5a                      pop    %rdx
  2e:   c3                      retq
  2f:   90                      nop
```

The only real difference between the two is the comparison instruction:
```
  16:   83 f8 f5                cmp    $0xfffffffffffffff5,%eax
[...]
  27:   85 c0                   test   %eax,%eax
```

I strongly suspect that the performance of `cmp` and `test` are very similar and that if they are different, it could depend on which particular processor model is being used.  So I'd say that we should pick whatever is clearest to the programmer and not worry too much about a performance myth.

**Comment by bturrubiates** [comment]
@goodell The difference is that cmp is implemented as subtraction while test is implemented as bitwise and. In my last comment I was trying to question the importance of the performance difference...I'm don't think it would make a noticable difference.

**Comment by goodell** [comment]
@bturrubiates wrote:
> The difference is that cmp is implemented as subtraction while test is implemented as bitwise and. In my last comment I was trying to question the importance of the performance difference...I don't think it would make a noticable difference.

Agreed, there should be no visible difference for our usages.

**Comment by patrickmacarthur** [comment]
I ran a simple performance test of returning `-FI_EAGAIN` vs. 0 in a tight loop and found no noticeable performance difference, so I rescind my previous statement.

**Comment by shefty** [comment]
Do we agreed that -FI_EAGAIN is preferred?

**Comment by patrickmacarthur** [comment]
I will support -FI_EAGAIN for the sake of moving this forward.

**Comment by goodell** [comment]
+1 for `-FI_EAGAIN`.  I can revert that part of ofiwg/fabtests@daba27c if we are in agreement.

**Comment by bturrubiates** [comment]
I'll also +1 -FI_EAGAIN.

**Comment by shefty** [comment]
And now to complicate the issue, what about sread()?  I would expect that sread() would return -FI_ETIMEDOUT if timeout > 0 and nothing was available.  But is this what we want?  What if timeout = 0?

**Comment by goodell** [comment]
I'm good with returning `-FI_ETIMEDOUT` when `sread()` times out and `timeout >= 0`.  There's a valid argument for returning 0 instead (matches `select`/`poll`, IIRC), but then we should probably reverse ourselves again on the behavior of `fi_eq_read()`.

**Comment by shefty** [comment]
I thought about the select/poll case as well.  At this point, I'd like to discount it.  sread() is more of a blocking read call, than select.  Looking at man pages, I see this for recv():
EAGAIN or EWOULDBLOCK
    The socket is marked nonblocking and the receive operation would block, or a receive timeout had been set and the timeout expired before data was received.
This is closer to what we want. It has the added advantage of matching sread() with read(), particularly for a timeout = 0.

**Comment by shefty** [comment]
See PR #789
