### ISSUE TITLE
assertion hit in socket provider: Assertion `conn->av_index == idx' failed.

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#7381]
I'm seeing
```
[application does fi_av_insert for the first time on the endpoint ]
libfabric:572509:1642491267:sockets:av:sock_check_table_in():269<debug> AV-INSERT: dst_addr family: 2, IP 127.0.0.1, port: 39493

[application starts an fi_read to that destination]

libfabric:572509:1642491267:sockets:ep_data:sock_comm_peek():200<debug> peek Resource temporarily unavailable
libfabric:572509:1642491267:sockets:ep_data:sock_pe_acquire_entry():228<debug> progress entry 0x7f081d81d1b0 acquired : 126
libfabric:572509:1642491267:sockets:ep_data:sock_pe_new_tx_entry():2137<debug> New TX on PE entry 0x7f081d81d1b0 (126)
libfabric:572509:1642491267:sockets:ep_data:sock_pe_new_tx_entry():2261<debug> Inserting TX-entry to PE entry 0x7f081d81d1b0, conn: 0xfef050
libfabric:572509:1642491267:sockets:ep_data:sock_pe_progress_tx_entry():1973<debug> Connection 0xfef050 grabbed by 0x7f081d81d1b0
libfabric:572509:1642491267:sockets:ep_data:sock_comm_send():122<debug> buffered 24
libfabric:572509:1642491267:sockets:ep_data:sock_comm_send():122<debug> buffered 24

[application does another fi_av_insert on the same endpoint]
libfabric:572509:1642491267:sockets:av:sock_check_table_in():269<debug> AV-INSERT: dst_addr family: 2, IP 127.0.0.1, port: 39493

[application does another fi_read]

libfabric:572509:1642491267:sockets:ep_data:sock_comm_peek():200<debug> peek Resource temporarily unavailable
simple_interlock_client_1: prov/sockets/src/sock_ep.c:1844: struct sock_conn *sock_ep_lookup_conn(struct sock_ep_attr *, fi_addr_t, union ofi_sock_ip *): Assertion `conn->av_index == idx' failed.
libfabric:571506:1642490964:sockets:av:sock_check_table_in():269<debug> AV-INSERT: dst_addr family: 2, IP 127.0.0.1, port: 35207
```

[note that the source location is off by 2 compared to https://github.com/ofiwg/libfabric/blame/v1.14.0/prov/sockets/src/sock_ep.c#L1842 due to debugging output I inserted on my end]

Checking with a debugger it turns out that `conn->av_index==1` while `idx==2` at this point.

This is not fully reproducible, but happens around 3 out of 4 times on my test case.

I've tried with both MANUAL and AUTO progress, just in case, but that makes no difference.

I wonder if it is wrong to do `fi_av_insert` with the same destination address twice on the same endpoint and do `fi_read` with the respective translated addresses?

**Comment by shefty** [comment]
An address should not be inserted into an AV more than once.  Doing so likely throws off the ability to provide source address matching.  Also, in some implementations, when AVs are mapped over connections, the AV indices may be exchanged during connection setup, so that the source address can quickly be determined.

As an example, assume ep1 is on node1, and ep2 is on node2.  ep2 is at AV index 2 on node 1.  ep1 is at AV index 1 on node 2.  When a message from ep1 is sent to ep2, that message will carry index 1 that ep1 may be found in the peer's AV.  This provides a fast lookup mechanism for the source address.

I believe the assert is checking that the index carried in the message matches the index in the AV where the actual address was found.

**Comment by u-u-h** [comment]
Hmm, ok. I would have expected that a second insert will return the same translated address, not try to create a new entry.

I realize that if may not be ideal to call av_insert more than necessary, but it would be much simpler for a user to rely on this being idempotent instead of keeping track of address inserts done in an application.

**Comment by shefty** [comment]
In the worst case, detecting duplicate insertions requires a linear search through the AV, which would need to be done for every address that is inserted.  For thousands or tens of thousands of entries, that's not feasible.  It's particularly difficult if the AV is offloaded to HW.

Additionally, while AV map can return the same fi_addr value, the behavior of AV table differs.

**Comment by u-u-h** [comment]
Ok, then it's hard to do an idempotent API.

I think it would be good to make a note about this in the `fi_av_insert` manpage. Maybe after the 3rd paragraph (when AV_MAP and AV_TABLE have been explained)?

Maybe something like:
```
Note that the same address should not be inserted twice into the same AV. While some providers may support this, for portable code the application needs to keep track of the addresses of communication partners that have already been inserted into a given AV.
```
at https://github.com/ofiwg/libfabric/blob/26606ca4aa9ef8ec80ae8c26abb58d1eb143ac57/man/fi_av.3.md?plain=1#L303

**Comment by shefty** [comment]
Thanks - I'll update the documentation.  FWIW, I know other apps have worked around this by emptying the AV then re-inserting a new set of addresses.  For example, clients may insert the address of the server into the AV in order to collect and exchange addresses.  They then remove the address and re-inserted a full list given back by the server.  Not sure this applies in your case.

**Comment by u-u-h** [comment]
Thanks for the hint. Unfortunately this does not apply for me: I'm in the situation that an incoming message may contain a reference to a as-yet unknown communication partner, and I need to dynamically do the av_insert for that. I then cache the translated address in a peer registry -- but this approach fails if concurrent messages trigger multiple such translations before the first one completes.

I'll work around it in the obvious way: queueing communication attempts on a 'peer-resolution-in-progress' state for the new peer in the registry.

**Comment by shefty** [comment]
See #7393 for updated man page.
