### ISSUE TITLE
GNI provider: free() on non-heap object

### ISSUE THREAD

**Issue by u-u-h** [ofiwg/libfabric#7382]
Cray clang version 13.0.1  (9128ea0dce8e670560aac33764073dfc97460e63) warns when compiling the libfabric 1.14.0 GNI provider:

```
prov/gni/src/gnix_buddy_allocator.c:290:8: warning: attempt to call free on non-heap object 'lists' [-Wfree-nonheap-object]
                free(&alloc_handle[0]->lists);
```

**Comment by u-u-h** [comment]
This is 'only' on an error path, but still seems to be a bug. Should I try to submit a merge request for this?

**Comment by u-u-h** [comment]
Any maintainer still interested in the GNI provider?

**Comment by shijin-aws** [comment]
AFAIK GNI provider is not actively maintained and removed in the main branch already. @j-xiong
