### ISSUE TITLE
fi_av_straddr() truncates IPv6 addresses

### ISSUE THREAD

**Issue by soumagne** [ofiwg/libfabric#7400]
When using `FI_SOCKADDR_IN6`, the address strings returned from `fi_av_straddr()` are not complete. This is because `ofi_straddr()` has the following issue, where `sizeof(str)` is too small to contain both the IPv6 address string and the `fi_sockaddr_in6://` string. It looks like the code should be modified accordingly to solve it:
```diff
diff --git a/src/common.c b/src/common.c
index 7110cc08d..2531e0464 100644
--- a/src/common.c
+++ b/src/common.c
@@ -324,10 +324,10 @@ sa_sin:
 sa_sin6:
                sin6 = addr;
                if (!inet_ntop(sin6->sin6_family, &sin6->sin6_addr, str,
-                              sizeof(str)))
+                              INET6_ADDRSTRLEN))
                        return NULL;
 
-               size = snprintf(buf, MIN(*len, sizeof(str)),
+               size = snprintf(buf, *len,
                                "fi_sockaddr_in6://[%s]:%" PRIu16, str,
                                ntohs(sin6->sin6_port));
                break;
```

**Comment by shefty** [comment]
It looks like the issue is the use of MIN() and removing that is the only change that's needed.  For good measure, it should also be removed from the FI_SOCKADDR_IN case as well.
