### ISSUE TITLE
fabtests: configure --help text needs updating

### ISSUE THREAD

**Issue by a-szegel** [ofiwg/libfabric#7411]
The README says to run configure with:
```
--with-libfabric=<directory>
```
which works correctly, but:
```
--with-libfabric <directory>
```
fails.  That surprised me because I was expecting it to work.  For instance, this configure in fabtests works as expected:
 ```
./configure --with-libfabric=/shared/libfabric/install/ --prefix ~/fabtests_install
```

And the `./configure --help` seems to also be missing the required equals sign:
``` 
  --with-libfabric        Use non-default libfabric location - default NO
  --with-cuda=DIR         Provide path to where the CUDA development and
                          runtime libraries are installed.
```

**Comment by shefty** [comment]
Re-opening to track changes needed to the --help option.  E.g.
```
--with-libfabric        Use non-default libfabric location - default NO
```
is incorrect.  The default --with option is actually 'yes'.  This should say something like use default library search path, and align with the syntax for --with-cuda to make more sense.
