### ISSUE TITLE
fi_writemsg with mismatched src/dst lengths should return -FI_EINVAL

### ISSUE THREAD

**Issue by gnuoyd** [ofiwg/libfabric#7418]
This issue affects the sockets provider, but it may also affect other providers.

If I pass `fi_writemsg` a `struct fi_msg_rma *msg` where the cumulative length of the source buffers described by (`msg->msg_iov`, `->iov_count`) is less than the cumulative length of buffers (`msg->rma_iov`, `->rma_iov_count`), then `fi_writemsg` returns 0 but no transfer takes place and libfabric produces neither a completion event nor an asynchronous error indication.

In `sock_ep_rma_writemsg`, it seems reasonable to compile the conditionally-compiled argument validation, always:

```C
#if ENABLE_DEBUG
        if (dst_len != src_len) {
                SOCK_LOG_ERROR("Buffer length mismatch\n");
                ret = -FI_EINVAL;
                goto err;
        }
#endif  
```

It would be helpful for both implementors and application programmers if the manual specifically mentioned that the cumulative length of the source and destination buffers must be identical or else -FI_EINVAL will be returned.

**Comment by shefty** [comment]
#7483 adds assertions to the tcp, verbs, and shm providers to check for this.
