### ISSUE TITLE
DSO build of EFA provider does not work in main branch (undefined symbol: log_prefix)

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7419]
Hi, our test of DSO build EFA provider does not work since Feb 1, 2022. 

We were able trace the problem back to the commit 26699856ec9f0eee8b01e341f987866364a6b07f.
```
    src/log: add utility provider log suffix to make logs easier to read
    
    Utility providers have to call fi_getinfo again to get core providers
    resulting in deceptive and confusing log lines where a core provider
    might return FI_ENODATA for a utility provider but FI_SUCCESS for the
    app. Extra log levels were added that say Begin/End ofi_get_core_info
    to make this clearer but these debug-only (not info) logs can get lost
    among the hundreds of lines of output.
    
    To make it easier to distinguish between log lines with and without a
    core provider, specifically during fi_getinfo, add a log_prefix to the
    log output which clarifies that the log line was outputed as part of
    the layered fi_getinfo call
    
    For example, the following log line sees changes as such:
    libfabric:53685:1643663041:verbs:fabric:vrb_get_matching_info():1514<info> checking domain: #1 mlx5_0
    libfabric:53685:1643663041:ofi_rxm:verbs:fabric:vrb_get_matching_info():1514<info> checking domain: #1 mlx5_0
```

This commit introduced a global variable `log_prefix` to `src/log.c`, and referenced the variable in `prov/util/src/util_attr.c`.

The problem is `src/log.c` is not part of `common_srcs` (probably for good reason). Thus the provider dso does not have the symbol `log_prefix`.

**Comment by wzamazon** [comment]
@aingerson Would you please take a look?

**Comment by shefty** [comment]
Of course log_prefix wasn't this easy.  Sigh...  We need to consider the case where rxm is being built as a DL provider.  In that case, the log_prefix would be local to that provider and not show up in log messages generated by a core provider. I don't know how we make that work without exporting something from the library API.

**Comment by wzamazon** [comment]
Like `fi_set_log_prefix`?

**Comment by shefty** [comment]
Yes, something like that.  But I don't know that I want to expose such a limited use function from the API that also isn't thread safe.

**Comment by wzamazon** [comment]
>But I don't know that I want to expose such a limited use function from the API that also isn't thread safe.
That would be my concern too.

Because the commit is not so critical (only improve logging), maybe just revert it?

**Comment by shefty** [comment]
It only improves logging, but the impact on the debugging is huge.  We have to get the DL providers working again, so the best compromise may be to simply move where the variable is defined.  The log won't quite work if rxm is built as a dl provider, but then who realistically does that?

**Comment by wzamazon** [comment]
Thanks! https://github.com/ofiwg/libfabric/pull/7420 does the move. I have verified that it get the DL providers working again. @aingerson would you please verify whether it still achieves the original commit does?

**Comment by raghupazl** [comment]
It might be worth extending the pr-ci jobs to include checks for a couple DSO provider builds to catch similar issues before merging a PR:
https://github.com/ofiwg/libfabric/blob/22fbc8867e13e7518c95ec8242cb643256abfea7/.github/workflows/pr-ci.yml#L39

We _might_ have had this check in  our Travis CI scripts originally.... another one of those things the migration to Github actions dropped.

**Comment by rajachan** [comment]
It might be worth extending the pr-ci jobs to include checks for a couple DSO provider builds to catch similar issues before merging a PR:
https://github.com/ofiwg/libfabric/blob/22fbc8867e13e7518c95ec8242cb643256abfea7/.github/workflows/pr-ci.yml#L39

We _might_ have had this check in  our Travis CI scripts originally.... another one of those things the migration to Github actions dropped.
