### ISSUE TITLE
RXM provider RMA operation keep returns -FI_EAGAIN after target being killed

### ISSUE THREAD

**Issue by liuxuezhao** [ofiwg/libfabric#7441]
In recent DAOS test, we hit a scenario cause DAOS/cart's bulk/RMA operation's completion losing in case of target process being killed. In the test only one server and one client involved, the below steps is what happened -

1. Initially both server and client are alive. DAOS submitted many concurrent RMA operations, some succeed, and some got "-FI_EAGAIN" from OFI due to temporary resource un-available. That is fine and mercury will queue those returned EAGAIN RMA operations and re-submit to OFI later within mercury's following progress loop. 
2. Some RMA OPs got completions from OFI normally, and some queued RMA OPs resubmitted successfully to OFI by mercury, test work in progress …
3. Client application being killed
4. OFI detects the connection broken and will cancel those unfinished RMA already submitted to it (generate FI_ECANCELED events, so mercury can complete them). But for those RMA OPs queued in mercury, OFI can do nothing.
5. Mercury keep retry those queued RAM OPs, but as the client target already killed, those retried RMA OPs can not success but also did not get an appropriate error code. Instead in that case OFI keeps returning “-FI_EAGAIN” to mercury, what mercury can do for that is still do the queue+retry again and again for those RMA OP.
6. DAOS cannot get those bulk/RMA’s completions forever and cause some other related issues (test hang, or pool cannot destroy due to refcount cannot released).

We can see the problem is in step 5, looks like that OFI should not always return “-FI_EAGAIN”  to upper layer when the target already being killed/non-existed.
I tested a workaround fix  -
diff --git a/prov/rxm/src/rxm_rma.c b/prov/rxm/src/rxm_rma.c
index 5a6e94f..5757ee5 100644
--- a/prov/rxm/src/rxm_rma.c
+++ b/prov/rxm/src/rxm_rma.c
@@ -78,8 +78,14 @@ rxm_ep_rma_common(struct rxm_ep *rxm_ep, const struct fi_msg_rma *msg,
        ofi_ep_lock_acquire(&rxm_ep->util_ep);
 
        ret = rxm_get_conn(rxm_ep, msg->addr, &rxm_conn);
-       if (OFI_UNLIKELY(ret))
+       if (OFI_UNLIKELY(ret)) {
+               if (ret == -FI_EAGAIN) {
+                       ret = -FI_ENOTCONN;
+                       FI_WARN(&rxm_prov, FI_LOG_EP_DATA, "rxm_get_conn failed, replace "
+                               "-FI_EAGAIN as -FI_ENOTCONN");
+               }
                goto unlock;
+       }
 
        rma_buf = rxm_get_tx_buf(rxm_ep);
        if (!rma_buf) {

It can fix the test's problem, but it is not a good fix. 

Some more ofi level logs in that case -
after client's killing -
_ERROR: daos_engine:0 libfabric:50076:1644805431::tcp:domain:tcpx_process_remote_read():364<warn> msg recv Failed ret = -107 
ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_process_shutdown():729<info> shutdown conn 0x7fd75755cb28 (state 3)
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_close_conn():64<debug> closing conn 0x7fd75755cb28  
libfabric:50076:1644805431::tcp:fabric:ofi_wait_del_fd():221<info> Given fd (59) not found in wait list - 0x7fd754042bf0
ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_free_conn():353<debug> free conn 0x7fd75755cb28
libfabric:50076:1644805431::ofi_rxm:cq:rxm_handle_comp_error():1719<warn> fi_cq_readerr: err: Transport endpoint is not connected (107), prov_err: Resource temporarily unavailable (11)libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_process_shutdown():729<info> shutdown conn 0x7fd75755cbe0 (state 3)
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_close_conn():64<debug> closing conn 0x7fd75755cbe0  
libfabric:50076:1644805431::tcp:fabric:ofi_wait_del_fd():221<info> Given fd (62) not found in wait list - 0x7fd720031120
ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_free_conn():353<debug> free conn 0x7fd75755cbe0_

Then with below ofi log that should be after mercury re-submit the RMA operation (previously returned as FI_EAGAIN), in the path of rxm_ep_rma_common()->rxm_get_conn() -> rxm_connect() returns "-FI_EAGAIN" as "conn->state" is "RXM_CM_CONNECTING" -
_ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_alloc_conn():423<debug> allocated conn 0x7fd75755cbe0
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_send_connect():287<debug> connecting 0x7fd75755cbe0 
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_open_conn():184<debug> open msg ep 0x7fd75755cbe0   
libfabric:50076:1644805431::tcp:core:ofi_check_rx_attr():798<info> Tx only caps ignored in Rx caps  
ERROR: daos_engine:0 libfabric:50076:1644805431::tcp:core:ofi_check_tx_attr():896<info> Rx only caps ignored in Tx caps
libfabric:50076:1644805431::tcp:core:ofi_check_rx_attr():798<info> Tx only caps ignored in Rx caps  
libfabric:50076:1644805431::tcp:core:ofi_check_tx_attr():896<info> Rx only caps ignored in Tx caps   
ERROR: daos_engine:0 lxz conn->state RXM_CM_CONNECTING, FI_EAGAIN                                                    
libfabric:50076:1644805431::ofi_rxm:ep_data:rxm_ep_rma_common():85<warn> rxm_get_conn failed, replace -FI_EAGAIN as -FI_ENOTCONN_

The last log above is added by the workaround patch pasted above, if without that change, mercury will keep retry the RMA which always get back FI_EAGAIN from OFI.

Besides that, even after that workaround patch, DAOS can get the bulk/RMA_OP's completion, but in following OFI log, there is still with lots of such logs reported that with connect request and refuse again and again that seems also abnormal -
_ERROR: daos_engine:0 libfabric:50076:1644805431::tcp:ep_ctrl:tcpx_cm_send_req():500<debug> client send connreq
ERROR: daos_engine:0 libfabric:50076:1644805431::tcp:ep_ctrl:tcpx_cm_send_req():509<warn> connection failure (sockerr -111)
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_handle_error():759<warn> fi_eq_readerr: err: Connection refused (111), prov_err: Success (0)
ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_process_reject():516<info> Processing reject for handle: 0x7fd75755cbe0
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_close_conn():64<debug> closing conn 0x7fd75755cbe0  
libfabric:50076:1644805431::tcp:fabric:ofi_wait_del_fd():221<info> Given fd (59) not found in wait list - 0x7fd720031b20
libfabric:50076:1644805431::tcp:fabric:ofi_wait_del_fd():221<info> Given fd (59) not found in wait list - 0x7fd720031b20
libfabric:50076:1644805431::tcp:fabric:ofi_wait_del_fd():221<info> Given fd (59) not found in wait list - 0x7fd720031120
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_free_conn():353<debug> free conn 0x7fd75755cbe0      
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_alloc_conn():423<debug> allocated conn 0x7fd75755cbe0
ERROR: daos_engine:0 libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_send_connect():287<debug> connecting 0x7fd75755cbe0
libfabric:50076:1644805431::ofi_rxm:ep_ctrl:rxm_open_conn():184<debug> open msg ep 0x7fd75755cbe0   
libfabric:50076:1644805431::tcp:core:ofi_check_rx_attr():798<info> Tx only caps ignored in Rx caps  
libfabric:50076:1644805431::tcp:core:ofi_check_tx_attr():896<info> Rx only caps ignored in Tx caps   
libfabric:50076:1644805431::tcp:core:ofi_check_rx_attr():798<info> Tx only caps ignored in Rx caps   
libfabric:50076:1644805431::tcp:core:ofi_check_tx_attr():896<info> Rx only caps ignored in Tx caps_                                                                          

@shefty or @j-xiong could you please help to take a look or assign to someone else when convenient? 
Looks like the problem is in RXM provider's connection management, would be great if an expert of that part can help on that. Thanks a lot.

**Comment by liuxuezhao** [comment]
BTW, if above analysis is correct, then not only the RMA operation but also the normal RPC request/reply message sending also possibly get that situation.

**Comment by shefty** [comment]
The proposed change is essentially reverting a change to the code that was made specifically for DAOS.

OFI does not know if a remote peer will ever be reachable, of if there's just a problem trying to send now.  (Peer is rebooting, switch is being reset, sun spots are flipping too many bits, etc.)  There are 2 higher-level behaviors that a provider may see.  One is that a send will never get a response.  The other is that the provider may get a response, but from some other entity on the target indicating that the peer isn't there.  These behaviors can map to UDP vs TCP semantics.  UDP goes direct to the peer, while TCP first goes through a kernel agent.

What's being discussed here is which software owns the policy for when to give up trying to communicate with the peer.  IMO, that belongs with the application.

**Comment by liuxuezhao** [comment]
@shefty Thanks for the explanations. We are trying to resolve it at upper layer.
