### ISSUE TITLE
Add interface to reserve port number

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#748]
As mentioned during my developer workshop talk, and discussed with @shefty, when implementing sockets atop libfabric, we don't have enough information to actually perform a bind when the user calls `bind()`.  The most we can currently do is stow away the source address to later provide as a hint to `fi_getinfo()`.  The problem is that if the user supplies a port number of 0, they are not assigned an ephemeral port number at that time.

The solution that we discussed would be to add a function (`fi_reserve_port`?) to reserve a port number in advance of `fi_getinfo()`.  Then, the port number could be officially bound when the endpoint is created.

My first stab at defining this would be something like:

```c
int fi_reserve_port(int ep_type, void *src_addr, size_t src_addrlen)
```
Reserves an ephemeral source port number on all providers for the given endpoint type which can bind the given src_addr (which does not specify a port number), which is reserved system-wide and cannot be used by any other process.  This function returns the port number that the application should use, or `-FI_EBUSY` if there are no available ephemeral port numbers.  This port number can be later used as a `src_addr` hint in an `fi_getinfo()` call (with `ep_attr->ep_type` set to the same value), and endpoints (active or passive) may be created via any number of the returned `fi_info` structures.  Each endpoint will be bound to the given source port number.  Providers may reserve the port number on additional endpoint types beyond that specified by the user, but must reserve the port number at least on the endpoint type specified by the user (this is meant to accomodate the case of a provider in which multiple endpoint types share a port space).

```c
int fi_unreserve_port(int ep_type, void *src_addr, size_t src_addrlen)
```
This removes the reservation for the port number in the given src_addr for the given endpoint type (and any endpoint types which share a port space for a given provider).  This function should be called once after all endpoints that are to use the given port number have been created, or if the reservation is no longer needed.  This is needed in case some`fi_info` entries do not get used to create endpoints, in order to remove the unneeded port reservation.

In the verbs provider, this could be implemented by creating a `cm_id` internally and binding it to that port, and storing it in an internal data structure.  This would be searched when an `fi_endpoint()` or `fi_passive_ep()` call is made with a specific port number, and that `cm_id` would be used for the endpoint.

Thoughts?

Is this something that would be possible in all providers? @jsquyres @j-xiong

**Comment by shefty** [comment]
To clarify the issue, there is a mismatch when attempting to layer the socket APIs over OFI.  The mismatch comes from sockets allowing a new socket to be either active or passive, but the determination is not made until later when connect or listen is called.  An app that calls this sequence has the issue:

socket()
bind()  <-- a source port needs to be returned from this call
connect() or listen()  <-- OFI now has the data to create the proper endpoint

The proposal Patrick is mentioning is one we tossed up in the air.  More thought is likely needed here, particularly on the release call and how to handle socket behavior such as reuse address.

As an alternative pseudo-solution, the sockets API implementation could assume that any call to bind() will be followed by listen() and allocate a passive endpoint.  If connect() is called instead, the passive endpoint would need to be released and an active endpoint allocated.  This does open a small window where the port is openly available.  But maybe we could address that gap instead?

At the moment, I'm not coming up with an elegant solution.  Does anyone know what the behavior is for an app that binds to wildcard IP + specific port, followed by a connect() call?  Does the port number remained unusable for all IP addresses, or only for the IP address assigned by connect?

**Comment by patrickmacarthur** [comment]
One other issue with the calls that I suggested is that they exist outside of the scope of `fi_info`, and don't get the API version protection of the version argument to `fi_getinfo()`.

Would it be possible to have an operation to transition a passive endpoint to an active endpoint prior to a listen (obviously once you call `fi_listen()` it's frozen forever as a passive endpoint)?  It's certainly an ugly way to do it, but maybe it's cleaner than my initial proposal.

**Comment by shefty** [comment]
I thought about this approach as well, but it is ugly.  Then again, socket semantics are somewhat ugly.  All that seems to be needed is a way to reserve the address, or migrate that from the passive endpoint to an active endpoint.

**Comment by goodell** [comment]
I need to think about this more.  I have a few concerns so far with the proposed interface:
- what about providers that are sharing the same address/port space (e.g., sockets+usnic)?  Is each provider expected to `socket()`+`bind()` internally, or will there be some shared infrastructure for this in libfabric?  Obviously there is a conflict here without some sort of shared infrastructure.
- how is the caller supposed to know what sort of address to stick into the `fi_reserve_port` function and how is the library supposed to know what type the caller passed in?  At least for `fi_av_insert` we know we can use the `addr_format` field from `fi_info`.

**Comment by shefty** [comment]
I don't know that even Patrick is leaning toward his proposal.  It was an idea I tossed out without any prior thought.  As long as everyone understands the problem, we just need to brainstorm to find an acceptable solution.

**Comment by patrickmacarthur** [comment]
@shefty @goodell How about the following?

```c
int fi_migrate_pep(struct fid_pep *pep, struct fid_ep **ep);
```
When called, this function moves the binding of the source address from the given passive endpoint to a newly constructed active endpoint.  This function will leave the passive endpoint in an implementation-defined state, and the only function that may safely be called on the passive endpoint is `fi_close()`.  Applications are still expected to call `fi_close()` on the passive endpoint [1].  This operation is provided only for the benefit of sockets-like middleware and applications that must be able to bind to a source address before knowing whether the endpoint is passive or active, and is not expected to be implemented efficiently.

It is an error to call this function if `fi_listen()` has already been called on the passive endpoint.  It is an error to call `fi_listen()` if this function has already been called on the passive endpoint.

EXS would do something like this (obviously way oversimplified):

```c
int exs_bind(int fd, const struct sockaddr *addr, socklen_t addrlen)
{
        struct exs_conn *conn = our_lookup_socket(fd);
        /* check connection state, etc. */
        conn->hints->src_addrlen = addrlen;
        memcpy(conn->hints->src_addr, addr, addrlen);
        fi_getinfo(EXS_FI_VERSION, NULL, NULL, 0, &hints, &info);
        fi_passive_ep(info->fabric_attr->fabric, info, &conn->pep, conn);
        return ret;
}

int exs_connect(int fd, const struct sockaddr *addr, socklen_t addrlen, ...)
{
        struct exs_conn *conn = our_lookup_socket(fd);
        switch (conn->state) {
        case EXS_CONN_UNBOUND:
                fi_getinfo(EXS_FI_VERSION, NULL, NULL, 0, &hints, &info);
                fi_endpoint(info->domain_attr->domain, info, &conn->ep, conn);
                break;
        case EXS_CONN_BOUND:
                fi_migrate_pep(conn->pep, &conn->ep);
                fi_close(conn->pep);
                break;
        }
        /* more setup */
        fi_connect(conn->ep, addr, addrlen);
}
```

This could be implemented by the verbs provider by simply moving the cm_id into the endpoint structure, NULLing it out of the pep structure, and then calling `rdma_resolve_addr` and `rdma_resolve_route` on the cm_id as part of `fi_connect()`.

[1] We could also define this function to implicitly close the passive endpoint, but that may be unfriendly to language bindings.

**Comment by shefty** [comment]
Not a bad idea.  I need to think about this more in the off case that there's a cleaner way of handling this.  (But I don't want to wait too long before settling on a solution.)

**Comment by goodell** [comment]
I think this will work for usNIC.

Our passive endpoints are backed by normal sockets and processed using the OS TCP/IP stack.  When we want to create an actual QP for an active endpoint we normally create a new socket and bind it to the given `info->src_addr`, then pass that socket down to the kernel as part of the QP construction call.  The kernel bumps the refcount on the socket to make sure user space can't close it and then installs a filter in the hardware to steer the packets to the right queues.

All we should have to do is use the socket we previously allocated+bound in `fi_passive_ep()` instead of allocating a brand new socket when the proposed `fi_migrate_pep()` is called.

**Comment by shefty** [comment]
I don't have a formal solution yet, but I was considering introducing a new FID type to deal with this.  Something like fid_socket, which is specifically designed to help support the socket API.  My thoughts are: sockets is so pervasive that we can justify a dedicated objects, and it may not be enough to migrate a PEP into an active EP.

For example, once a socket has been created, an app can issue any number of setsockopt or ioctl options against it.  Many of these may not make sense for what OFI wants to describe as a PEP.  We may even want fid_socket to have other features that would not be ideal to associate with a passive or active EP, such as associating it with an fd.

I don't want to try to rush what interfaces fid_socket would have, but at the very least it should support calls similar to open_pep() and open_ep().  These would behave like your fi_migrate_pep() call.  fid_socket would be defined similar to fid_stx, which only includes the base EP ops.  It would be allocated using a new fabric ops (socket_ep?) that could match the passive_ep ops.

**Comment by patrickmacarthur** [comment]
Prof. Russell and I discussed this yesterday and agreed that although it sounds like a good idea, we would like to see some simple pseudocode (like what I did above for my `fi_migrate_pep()` proposal) so we can see how this would be used and how it would fit in with `fi_getinfo()`, reserving an fd, endpoint creation, etc.

In particular, if one of the goals is to associate an fd with the fid_socket that could be usable as the fd of the socket, this would have to be at least partially provider independent, since it would have to be constructed at `socket()` time.  We also weren't sure where `fi_getinfo()` would be called.

**Comment by patrickmacarthur** [comment]
I'd like to see some forward progress on this and have a solution for rc5 if at all possible, since it most likely will require API changes which will need time for testing before the 1.0 final release.  

If it would be helpful we could arrange a call offline at some point later this week to go over your `fid_socket` proposal and come up with a concrete set of changes to the API.

**Comment by shefty** [comment]
I agree that this needs work.  I haven't had time yet to develop the idea further, but should within a couple of days.  If this is done using a fid_socket proposal, then it becomes a simple extension, which makes it easy to add post 1.0.  Getting it into 1.0 is ideal, but if we keep to time based releases, we would have this in about 3 months.  That would give us time to ensure that the details are aligned with what is needed.

**Comment by shefty** [comment]
quick update: I hope to have a more formal proposal for discussion within 1-2 days.

**Comment by shefty** [comment]
I won't have the proposal coded up for another day or so, but here is the general idea.  Conceptually, it is most similar to the idea of creating a passive EP and migrating it to an active one, though the mechanics are quite different. (The details may differ than what's shown here.)

1. Add a new fabric op to open an 'EP context' structure.
```c
	int	(*ep_context)(struct fid_fabric *fabric, struct fi_info *info,
			struct fid_ep_ctx **ep_ctx, void *context);
```
2. The structure is a base EP with new address functions:
```c
struct fi_ops_addr {
	size_t	size;
	int	(*setname)(fid_t fid, void *addr, size_t *addrlen);
	int	(*getname)(fid_t fid, void *addr, size_t *addrlen);
};

struct fid_ep_ctx {
	struct fid		fid;
	struct fi_ops_ep	*ops;
	struct fi_ops_addr	*addr;
};
```
3. The primary use of the EP context is to reserve an address, which is then passed to either an active or passive EP.  In order to associate the EP context with an active or passive EP, we make a small adjustment to struct fi_info:
```c
struct fi_info {
	...
-	fi_connreq_t		connreq;
+	fi_handle_t		handle;
```
4. The handle field should point to the fi_ep_ctx structure if the new EP should inherit the address and other values stored by the EP context.
5.  At this point, the fi_ep_ctx can be closed.

The general flow for the app would be:
```c
int socket(...)
{
    fi_getinfo();
    fi_fabric();
    fi_ep_context();   
    socket maps to struct fi_ep_ctx;
}

int bind(...)
{
    fi_setname(...)
}

int connect(...)
{
    fi_getinfo();  // or create by hand or store with socket
    fi_domain();
    fi_info->handle = ep_ctx;
    fi_endpoint(dom, fi_info, ...);
    fi_close(ep_ctx);
}
```
