### ISSUE TITLE
prov/upd;ofi_rxd: fi_ubertest hang with main branch

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#7499]
**Describe the bug**
Got a hang when running fi_ubertest with upd provider.

**To Reproduce**

server command:
`fi_ubertest -x`

client command
`fi_ubertest -u /xxx/fabtests/share/fabtests/test_configs/udp/all.test  c5n-st-c5n18xlarge-1`

Note that if I use the config file `quick.test`, the test would pass.

**Expected behavior**
Not hang

**Output**

Hang happened at 

```
Starting test 120 / 144:
[udp, bandwidth, inject--, FI_EP_DGRAM, FI_AV_MAP, eq_wait_fd, cq_wait_none, cntr_wait_none, comp_queue -- tx (bind-NONE, op-NONE), rx: (bind-NONE, op-NONE), [FI_CQ_FORMAT_MSG],  FI_PROGRESS_AUTO, FI_THREAD_SAFE (only hints), [], [], [FI_MSG, FI_RECV, FI_SEND]]
bw                                                16      0       0           0.02s      0.00        inf       0.00
bw                                                32      0       0           0.02s      0.00        inf       0.00
```

**Environment:**
amazon linux 2.

**Additional context**
I noticed this issue when trying to using `runfabtests.py` for AWS  CI. It is possible that the issue has existed for long, but was not picked up by AWS CI because the CI was using `runfabtests.sh` and did not pass the uber config file.

Now that `runfabtests.py` can find and use the correct ubertest config file, it started to show up.

I am not actually using upd provider.

**Comment by j-xiong** [comment]
Is this system specific? I was unable to reproduce the hang with local system (w/ SLES 15SP3) using the latest main branch (commit  0ee9395f9cb3a57caeec81959734ffe2cda6c10c).

**Comment by wzamazon** [comment]
I was using amazon linux 2. will try sles sp3.
