### ISSUE TITLE
prov/psm3: Tests hang intermittently and causing CI to fail

### ISSUE THREAD

**Issue by Juee14Desai** [ofiwg/libfabric#7550]
**Bug description**
While running CI for psm3, fi_rdm_tagged_peek and fi_cq_data were failing. Upon manually running these tests it was found that the tests hang intermittently waiting for data and once Ctrl-C is pressed to exit, data is sent.

**To Reproduce**
Need to run the following tests a few times manually and it will hang in one of those runs.
fi_rdm_tagged_peek -p "psm3" -s ci3
fi_rdm_tagged_peek -p "psm3" -s ci4 ci3

fi_cq_data -e rdm -p "psm3" -s ci3
fi_cq_data -e rdm -p "psm3" -s ci4 ci3

**Expected behavior**
Tests should pass without hanging

**Output**
The server hangs:
libfabric:1062046:1647552362::psm3:core:psmx3_trx_ctxt_alloc():303<info> ep_open_opts: unit=0 port=0
libfabric:1062046:1647552362::psm3:core:psmx3_trx_ctxt_alloc():326<info> epid: 00000002001b3d03 (tx+rx)
libfabric:1062046:1647552362::psm3:ep_ctrl:psmx3_ep_open_internal():577<info> skip initialization of op context list.
libfabric:1062046:1647552362::core:core:util_ns_process_cmd():227<info> Name server processed command - returned 0 (Success)
libfabric:1062046:1647552365::core:core:util_ns_process_cmd():227<info> Name server processed command - returned 0 (Success)
Waiting for CQ data from client

The client also hangs:
libfabric:894981:1647552365::psm3:core:psmx3_trx_ctxt_alloc():303<info> ep_open_opts: unit=0 port=0
libfabric:894981:1647552365::psm3:core:psmx3_trx_ctxt_alloc():326<info> epid: 0000000400fc0c03 (tx+rx)
libfabric:894981:1647552365::psm3:ep_ctrl:psmx3_ep_open_internal():577<info> skip initialization of op context list.
libfabric:894981:1647552365::core:core:util_ns_process_cmd():227<info> Name server processed command - returned 0 (Success)

and once Ctrl-C is pressed, the test proceeds, data is sent:
^CPosting send with CQ data: 0x89abcdef
Done

**Comment by acgoldma** [comment]
@Juee14Desai , Can you get a bit more info:

1. What is the hash/tag or version being built for libfabric? 
2. What are the build flags passed to configure/make?
3. What is the test env (OS, Hardware, NIC, etc.)?
4. Can you rerun with `FI_LOG_LEVEL=info` `PSM3_TRACEMASK=0xff` `PSM3_IDENTIFY=1` and attach full logs?
5. Can you reproduce if you start the server, wait a few seconds (2-3) then start the client?

**Comment by Juee14Desai** [comment]
@acgoldma  Here are some more details:
1. What is the hash/tag or version being built for libfabric?
>> I am using upstream libfabric so I think the psm3 version should be the one upstream.

2. What are the build flags passed to configure/make?
>> These are the flags passed while configuring:
--enable-debug --enable-psm2=no --enable-verbs=no --enable-tcp=yes --enable-sockets=yes --enable-udp=yes --enable-shm=yes --enable-psm3=yes --enable-usnic=no --enable-psm=no --enable-efa=no --enable-perf=no --enable-rstream=no --enable-hook_debug=no

3. What is the test env (OS, Hardware, NIC, etc.)?
>> I am running these tests on the CI cluster nodes ci3 and ci4. These nodes are mlx5-HDR nodes running redhat.

4. Can you rerun with FI_LOG_LEVEL=info PSM3_TRACEMASK=0xff PSM3_IDENTIFY=1 and attach full logs?
>> Full logs attached for failure case.
[Part_4_Logs.txt](https://github.com/ofiwg/libfabric/files/8306424/Part_4_Logs.txt)

5. Can you reproduce if you start the server, wait a few seconds (2-3) then start the client?
>> Yes it hangs. Logs attached.
[Part_5_Logs.txt](https://github.com/ofiwg/libfabric/files/8306426/Part_5_Logs.txt)

**Comment by Juee14Desai** [comment]
@acgoldma Similar behavior was seen with fi_dgram_waitset test as well. Is there a possibility for all tests to see this behavior?

**Comment by Juee14Desai** [comment]
Hi @acgoldma,

I used the latest psm3 version (IEFS 11.2.0.0) and ran tests but the tests that I have mentioned above are still hanging and ultimately failing. Please let me know if you need more info.

**Comment by acgoldma** [comment]
I have not been able to reproduce this using my teams CI or manual testing. 
I think we will have to work together when you get the chance to try and attach a gdb session to the hanging server and dump the threads.

Maybe you can modify the runfabtests.sh to when killing the process for timeout, it will do a gdb attach and dump before calling kill?

**Comment by mwheinz** [comment]
@Juee14Desai - I've identified a fix for your issue. It should be in our next update to the psm3 provider.

**Comment by shefty** [comment]
Please wait to close the issue until a fix is in tree.

**Comment by Juee14Desai** [comment]
@mwheinz Thank you Michael for fixing this quickly.

**Comment by acgoldma** [comment]
@Juee14Desai, we merged upstream can you please verify and if working, please close.

**Comment by Juee14Desai** [comment]
This can be closed now. I verified by running our CI and the two tests that were failing, fi_rdm_tagged_peek and fi_cq_data, are now passing. I also verified the that tests don't hang anymore manually.

Logs below from CI:

18:44:41 - name:   fi_rdm_tagged_peek -p "psm3"
18:44:41 timestamp: 20230215-004441+0000
18:44:41 result: Pass
18:44:41 time:   1
18:44:41 server_cmd:  /home/cstbuild/ofi-Install/libfabric/jdesai/main/157/reg/bin/fi_rdm_tagged_peek -p "psm3"   -s ci15-ib0
18:44:41 server_stdout: |
18:44:41 [error] fabtests:common/shared.c:2310: Tag mismatch!. Expected: 1, actual: 2748
18:44:41 ft_get_cq_comp(): common/shared.c:2429, ret=-256 (Unspecified error)
18:44:41 Sending 10 tagged messages
18:44:41 Waiting for messages to complete
18:44:41 client_cmd:  /home/cstbuild/ofi-Install/libfabric/jdesai/main/157/reg/bin/fi_rdm_tagged_peek -p "psm3"   -s ci16-ib0 ci15-ib0
18:44:41 client_stdout: |
18:44:41 Peek for a bad msg
18:44:41 Peek w/ claim for a bad msg
18:44:41 Peek msg 1
18:44:41 Receive msg 1
18:44:41 Peek w/ claim msg 2
18:44:41 Receive claimed msg 2
18:44:41 Peek & discard msg 3
18:44:41 Checking to see if msg 3 was discarded
18:44:41 Peek w/ claim msg 4
18:44:41 Claim and discard msg 4
18:44:41 Receive msg 5
18:44:41 Receive msg 6
18:44:41 Receive msg 10
18:44:41 Receive msg 9
18:44:41 Receive msg 8
18:44:41 Receive msg 7

18:44:28 - name:   fi_cq_data -e rdm -p "psm3"
18:44:28 timestamp: 20230215-004427+0000
18:44:28 result: Pass
18:44:28 time:   1
18:44:28 server_cmd:  /home/cstbuild/ofi-Install/libfabric/jdesai/main/157/reg/bin/fi_cq_data -e rdm -p "psm3"   -s ci15-ib0
18:44:28 server_stdout: |
18:44:28 Waiting for CQ data from client
18:44:28 remote_cq_data: success
18:44:28 client_cmd:  /home/cstbuild/ofi-Install/libfabric/jdesai/main/157/reg/bin/fi_cq_data -e rdm -p "psm3"   -s ci16-ib0 ci15-ib0
18:44:28 client_stdout: |
18:44:28 Posting send with CQ data: 0x89abcdef
18:44:28 Done

Thanks,

Juee
