### ISSUE TITLE
Question: fi_domain_bind()

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#757]
@shefty I see that the binding for fid_domain_bind() in the fi_eq(3) man page:

```c
int fi_domain_bind(struct fid_domain *domain, struct fid *eq, uint64_t flags);
```

Is the 2nd argument really only allowed to be an eq, or is it allowed to be any fid?

I suspect it's the latter, because in fi_eq.h, the prototype is:

```c
fi_domain_bind(struct fid_domain *domain, struct fid *fid, uint64_t flags);
```

Does the man page need to be updated?

**Comment by shefty** [comment]
Any fid can be used.  Though I don't think binding to anything other than an EQ is defined.
