### ISSUE TITLE
prov/efa: issues reported by coverity

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7590]
There are several outstanding issues reported by coverity.  Opening issue to track and raise awareness.

**Comment by wzamazon** [comment]
Where can I find the coverity report?

**Comment by shefty** [comment]
If you click on the ofiwg/libfabric and scroll down there's a button to link to the coverity report.

https://scan.coverity.com/projects/ofiwg-libfabric?tab=overview

I'm working on some of the non-efa related issues.

**Comment by wzamazon** [comment]
I see. working on it.

**Comment by wzamazon** [comment]
1st round: https://github.com/ofiwg/libfabric/pull/7607

**Comment by wzamazon** [comment]
2nd round: https://github.com/ofiwg/libfabric/pull/7614

**Comment by wzamazon** [comment]
both round merged.

There is only 1 issue left, which is about calling function `rand()`. I set it to ignore.
