### ISSUE TITLE
prov/opx: compile time for non-debug build takes several minutes

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7594]
The compile takes so long it appears to hang.  This significantly impacts CI testing, and I'm certain will lead to end users who build libfabric to report that the compile is hanging.

**Comment by timothom64** [comment]
Yea it takes about 7 minutes.  You can assign this to me

**Comment by timothom64** [comment]
Improved with 3e737652b525141b4d4218856c2c4b2ed04d5f67

**Comment by timothom64** [comment]
An upcoming PR should farther enhance this.  Current optimized builds of libfabric with Opx are down to 2.5 minutes of wall-clock time on a slower system in nfs.   Debug builds are less than a minute.
