### ISSUE TITLE
Question: fi_open_ops()

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#760]
@shefty fi_domain.3 has the following prototype for fi_open_ops:

```c
int fi_open_ops(struct fid *domain, const char *name, uint64_t flags, void **ops, void *context);
```

Is fi_open_ops() really only defined for domains?  Or does it just happen to be documented in fi_domain.3, and therefore the fid argument says `domain` (instead of, for example, `fid`)?

I suspect it's the latter, because fabric.h contains the following prototype:

```c
int fi_open_ops(struct fid *fid, const char *name, uint64_t flags, void **ops, void *context)
```

If it really is supposed to be any fid and not just the domain, should we move the documentation for fi_open_ops() out of fi_domain.3 and in to ...I'm not actually sure where it should go...

**Comment by shefty** [comment]
It is intended to work with any fid.  And I'm not sure where it goes either.  It's similar to fi_close(), if that helps.
