### ISSUE TITLE
SHM IPC needs to have checks around handle size to safeguard against handle sizes > 64 bytes.

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#7656]
I was reading through the hmem IPC handle code and found IPC_HANDLE_SIZE to be statically defined as 64 bytes for all devices. I'm rewriting some Open MPI code to create device agnostic API's, and I couldn't figure out if it was safe to assume that IPC handles would always be 64 bytes or smaller. What is the explanation on how this assumption was made?

**Comment by aingerson** [comment]
The IPC_HANDLE_SIZE was statically defined as 64 bytes because that is the space that we have leftover in the cmd for an IPC handle (SMR_MSG_DATA_LEN is 64 also). It's not really an assumption that all handles should fit into that size but rather the maximum handle size that the inline handle can support. The code should (but currently doesn't) have checks to make sure the handle fits in the payload. Any APIs that need more space need to be dealt with by either increasing the total cmd size (currently 128 bytes - 64 byte header) or by using multiple commands (like the RMA protocol).
That said, the code should probably be reworked to define that better (and include checks to safeguard this)

**Comment by wckzhang** [comment]
I'll change the issue name to reflect the code that needs to be reworked

**Comment by shijin-aws** [comment]
@aingerson maybe off topic, but may I know why currently `ipc_handle` and `offset` are in the same union? https://github.com/ofiwg/libfabric/blob/main/include/ofi_shm.h#L135-L140

Does that mean they cannot be used at the same time?

**Comment by aingerson** [comment]
@shijin-aws Correct, they cannot be used at the same time. The device/offset/fd_handle implementation is to support ZE which has an 64 bit handle. With CUDA, the handle (I believe) is 64 bytes which means that we cannot fit any additional information into the cmd to store the device or offset if needed (and it looks like CUDA also needs that information, correct?). We need to rework the IPC implementation to account for all information needed for each iface's IPC protocol. 2 possible solutions here - increase the cmd size to 256 or use an inject buffer (4k) to store any IPC information

**Comment by shijin-aws** [comment]
@aingerson Thanks. Yes I am trying to rework the `smr_ipc_info` object to make it work for CUDA IPC. CUDA IPC also need `offset`, and I also need to store the base and length of the allocation in the ipc_info when implementing the IPC cache. I hit a memory corruption in `ipc_handle` when running with non-zero `offset`.

I tried to move `ipc_handle` and `offset` outside of the `union`, and now my struct looks like this

```
struct ipc_info {
	uint64_t	iface;
	uintptr_t	base_address;
	size_t		base_length;
	size_t	        offset;
	uint8_t		ipc_handle[IPC_HANDLE_SIZE];
	union {
		struct {
			uint64_t	device;
			uint64_t	fd_handle;
		};
	};
};
```

But I am worried that this will break the size limit of the cmd. Maybe increasing the cmd size to 256 is an easier solution, but I am not sure whether there is a performance impact?

**Comment by aingerson** [comment]
I think increasing the size to 256 is reasonable. I would suggest restructuring the ipc_info to have iface and then a union of what each interface needs. For example ZE doesn't need the base address/length or ipc_handle, just the offset, device, and fd_handle. So something like this:

```
struct ipc_info {
	uint64_t	iface;
        union {
                struct cuda_ipc_info {
			uintptr_t	base_address;
			uint64_t	base_length;
			uint64_t	offset;
			uint8_t		ipc_handle[IPC_HANDLE_SIZE];
		};
		struct ze_ipc_info {
			uint64_t	device;
			uint64_t	offset;
			uint64_t	fd_handle;
		};
	};
};

```

**Comment by shijin-aws** [comment]
@aingerson if ze wants to benefit from using ipc cache in the future, should it have base addr/len as well? But this refactor should be a good start for https://github.com/ofiwg/libfabric/pull/7893 because I do not want to modify ze's behaior.

**Comment by aingerson** [comment]
Maybe a dumb question - can we not cache the handles instead of the addresses? Why do we have to send the base address in addition to the handle in order to cache it?

**Comment by shijin-aws** [comment]
because the handle can be different for the same address, at least for [CUDA](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g8a37f7dfafaca652391d0758b3667539)

>If a region of memory is freed with [cudaFree](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1ga042655cbbf3408f01061652a075e094) and a subsequent call to [cudaMalloc](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356) returns memory with the same device address, [cudaIpcGetMemHandle](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g8a37f7dfafaca652391d0758b3667539) will return a unique handle for the new memory.

So it is possible that receiver gets a different IPC handle for the same memory address (and length) from the sender. Then the mr entry with the same iov but the old IPC handle should be uncached, and the new mr entry that has the new IPC handle should be inserted to the cache.

**Comment by aingerson** [comment]
I see. Thanks for the explanation! ZE probably has similar behavior.
In which case I think we could probably drop the union entirely:
```
struct ipc_info {
	uint64_t	iface;
	uint64_t	device;
	uintptr_t	base_address;
	size_t		base_length;
	size_t	        offset;
	uint8_t		ipc_handle[IPC_HANDLE_SIZE];
};
```

**Comment by shijin-aws** [comment]
Is it safe to replace `fd_handle` to `ipc_handle`? Seems not hurt by doing code inspection.

**Comment by aingerson** [comment]
I think that should be fine. ZE can just only use the first 8 bytes.

**Comment by wckzhang** [comment]
Since we have extra cmdline space, should we reconsider IPC_HANDLE_SIZE being set at 64 rather than letting each device specify it? (It probably doesn't matter as the only existing IPC handle sizes are 64 bytes right now I think)

**Comment by aingerson** [comment]
I think we should declare the IPC_HANDLE_SIZE to be whatever the remaining size is to maximize the size if needed (even though they only go to 64 bytes right now). Ie something like this:
```
struct smr_ipc_hdr {
	uint64_t	iface;
	uint64_t	device;
	uintptr_t	base_address;
	size_t		base_length;
	size_t	        offset;
};

#define IPC_HANDLE_SIZE (SMR_MSG_DATA_LEN - sizeof(struct smr_ipc_hdr))
struct ipc_info {
	struct smr_ipc_hdr 	ipc_hdr;
	uint8_t			ipc_handle[IPC_HANDLE_SIZE];
};

```

**Comment by shijin-aws** [comment]
@aingerson Sure, I will make it part of https://github.com/ofiwg/libfabric/pull/7893. One thing blocks me now is that I need to update `ofi_mr_info` in `ofi_mr.h` to make `ipc_handle` part of it:

```
struct ofi_mr_info {
	struct iovec iov;
	enum fi_hmem_iface iface;
	uint64_t device;
	uint8_t ipc_handle[IPC_HANDLE_SIZE];
	void *ipc_mapped_addr;
};
```

Then I have to include `ofi_shm.h` in `ofi_mr.h`. But if I do that I the compilation will break as `prov/sockets/src/sock_fabric.c`, which includes `ofi_mr.h`,  has a conflict definition of `sock_list_lock` with the one in `ofi_shm.h`

```
prov/sockets/src/sock_fabric.c:72:20: error: conflicting types for 'sock_list_lock'
 static ofi_mutex_t sock_list_lock;
                    ^~~~~~~~~~~~~~
In file included from ./include/ofi_mr.h:47:0,
                 from ./prov/sockets/include/sock.h:55,
                 from prov/sockets/src/sock_fabric.c:45:
./include/ofi_shm.h:200:24: note: previous declaration of 'sock_list_lock' was here
 extern pthread_mutex_t sock_list_lock;
```

**Comment by shijin-aws** [comment]
>I think we should declare the IPC_HANDLE_SIZE to be whatever the remaining size is to maximize the size if needed (even though they only go to 64 bytes right now). Ie something like this:

@aingerson @wckzhang 

Thinking about it more, I do not think we should derive the IPC_HANDLE_SIZE from the shm msg data length. It should be large enough for available hmem ifaces, and we need to make sure the SMR_MSG_DATA_LEN is large enough.

**Comment by shefty** [comment]
I agree with @shijin-aws - the IPC_HANDLE_SIZE should be based on the IPC sizes, which is what it represents, and not a shm protocol buffer size.

**Comment by wckzhang** [comment]
Can this issue be closed? @shijin-aws did you submit a change to address this? Or have we decided we weren't going to do anything further here?

**Comment by shijin-aws** [comment]
@wckzhang currently it is still 64. There is a comment in the file says that if anyone wants to increase it, they need to bump smr protocol version.

https://github.com/ofiwg/libfabric/blob/main/include/ofi.h#L271-L289

**Comment by wckzhang** [comment]
I think this issue can be closed.
