### ISSUE TITLE
Peer provider addressing issues

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7658]
This is related to PR #7635.  The peer provider APIs need to exchange fi_addr_t data between the peer and owner provider.  We want a mechanism defined that minimizes address lookups.  Additionally, in a generic use case, there may be multiple AVs active in the peer.  The fi_addr_t value is not sufficient to determine which peer AV the address belongs to, making a reverse lookup basically impossible by the owner.

**Comment by shefty** [comment]
See #7670 for a proposed solution that allows associating a user-specified id with each address.

**Comment by wzamazon** [comment]
Thank you! The solution looks reasonable to me.

**Comment by shefty** [comment]
Proposed changes merged upstream.
