### ISSUE TITLE
fi_cq_sread contract broken at commit 0524e628d5a02e017106141bc97eb0a043c0de7d

### ISSUE THREAD

**Issue by gnuoyd** [ofiwg/libfabric#7668]
See my [commit comment](https://github.com/ofiwg/libfabric/commit/0524e628d5a02e017106141bc97eb0a043c0de7d#commitcomment-71028037) for the details.

**Comment by shefty** [comment]
The change was made knowing that it broke fi_cq_sread() for debug builds.  Without that change, we can't successfully use a debugger to debug libfabric in a variety of situations.  The behavior of the non-debug build is unaffected.
