### ISSUE TITLE
fi_domain(): are attributes like resource_mgmt INOUT parameters?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#771]
Can callers request a particular style of `resource_mgmt` in calls to `fi_domain`?  Or is this strictly an output parameter?

The same question could be asked about `data_progress`, `control_progress`, `threading`, and probably some other fields.

**Comment by shefty** [comment]
Apps should be able to request specific values, with the understanding that a provider may not support the value requested (or at least not as well as another value).

**Comment by goodell** [comment]
> Apps should be able to request specific values, with the understanding that a provider may not support the value requested (or at least not as well as another value).

That's still squishy.  If the provider does not support the (non-`FI_RM_UNSPEC`) value requested, can it return a different value than requested or should it return `-FI_ENOSYS`/`-FI_EOPNOTSUPPORTED`?

**Comment by shefty** [comment]
Most attributes have an 'UNSPEC' value that an app can use if it doesn't care what is provided.  Letting the provider modify the value from what an app requests is a pain for the app, as it now has to check a stream of attributes to see if it really got what it asked for.

In many cases, a provider can support the requested value, though it may be less performant.  I.e. the provider is cannot take advantage of an optimization that an app is prepared to handle.

So, I'm not fond of the idea that a provider can basically ignore the hints and return a different value from what was requested.  That makes the hints somewhat meaningless.

**Comment by shefty** [comment]
If a provider cannot support a requested fi_info hint value, I would expect the provider to return -FI_ENODATA from fi_getinfo.  I would expect the provider to return -FI_ENOSYS or FI_EINVAL or something else for other calls, with a preference for FI_ENOSYS.
