### ISSUE TITLE
prov/opx: provider is reported even when OPA hw is not present

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#7715]
**Describe the bug**
On machines w/o OPA hardware, fi_getinfo() still returns opx as a valid provider. 

**To Reproduce**
Run `fi_info -p opx` on systems w/o OPA hw and get the result:
```
provider: opx
    fabric: OPX-100
    domain: hfi1
    version: 115.0
    type: FI_EP_UNSPEC
    protocol: FI_PROTO_OPX
```
In addition, the opx provider is listed before the verbs provider so applications that use the first returned provider may end up not working properly.

**Expected behavior**
fi_getinfo returns -61

**Output**
n/a

**Environment:**
Linux

**Additional context**
Comment from DAOS issue https://github.com/daos-stack/libfabric/pull/56:

> [@frostedcmos](https://github.com/frostedcmos) , Lei discovered that `--disable-opx` is required on a cluster with Mellanox / IB for ofi to properly return that verbs is a provider that we can use. this is why i was having issues with using 1.15rc3 on thee io500 cluster. i just updated with ofi build without changing the configure options. I don't know if this is really the intention, but why would one need to explicitly disable opx on an IB cluster and why would it not report that verbs is an available provider? we don't even have opa on those nodes. sounds like a bug to me, but i don't know whether we should hold this patch for it.

**Comment by timothom64** [comment]
Yea this isn't right.  Will fix

**Comment by timothom64** [comment]
I will try

**Comment by timothom64** [comment]
In CI testing now

**Comment by timothom64** [comment]
Created pr
