### ISSUE TITLE
src/hmem_ze.c Question about ze_hmem_copy

### ISSUE THREAD

**Issue by wckzhang** [ofiwg/libfabric#7728]
Hello, I'm not very familiar with the ze Core API, so I don't quite understand the behavior of ze_hmem_copy functions.

What I know:

A command list with the command to perform a memory copy is created and the command queue is told to execute this list.

What I don't know:

The (optional) fence parameter was left NULL, I don't think ```zeCommandQueueExecuteCommandLists``` appears to be a blocking call (unless this is the behavior when fence is left NULL, I couldn't quite figure it out). So I'm not sure how we detect when  the command has finished executing. Perhaps @aingerson can shed some light here for me, thanks!

**Comment by j-xiong** [comment]
The command queue is created with `ZE_COMMAND_QUEUE_MODE_SYNCHRONOUS` mode. See https://github.com/ofiwg/libfabric/blob/main/src/hmem_ze.c#L62

**Comment by j-xiong** [comment]
See https://spec.oneapi.io/level-zero/latest/core/api.html#_CPPv423ze_command_queue_mode_t for reference.

**Comment by wckzhang** [comment]
Thank you very much j-xiong!
