### ISSUE TITLE
prov/psm3: psm3_rbtree.c missing from tarball

### ISSUE THREAD

**Issue by opoplawski** [ofiwg/libfabric#7735]
**Describe the bug**
```
+ /usr/bin/make -O -j4 V=1 VERBOSE=1
make: *** No rule to make target 'prov/psm3/psm3/include/psm3_rbtree.c', needed by 'prov/psm3/src/psm3_src_chksum.h'.  Stop.
```

**Environment:**
Fedora rawhide

**Additional context**
That file appears to be missing from the 1.15.0 tarball.

**Comment by j-xiong** [comment]
The following files are missing from the tarball:
```
libfabric-1.15.0/prov/psm3/psm3/hal_sockets: sockets_spio.c
libfabric-1.15.0/prov/psm3/psm3/hal_verbs: verbs_spio.c
libfabric-1.15.0/prov/psm3/psm3/include: psm3_rbtree.c
libfabric-1.15.0/prov/psm3/psm3/utils: utils_dwordcpy-x86_64-fast.S
libfabric-1.15.0/prov/psm3: VERSION
```
Strangely enough, when I ran the following command to create the tarball from the v1.15.x branch, those files are included.
```
$ ./autogen.sh
$ ./configure
......
*** Built-in providers: opx dmabuf_peer_mem hook_hmem hook_debug perf rstream shm rxd mrail rxm tcp udp usnic verbs sockets psm3
*** DSO providers:
***
$ make dist
```
@shefty What was done differently when the release tarball was created?

**Comment by j-xiong** [comment]
I think I have found the reason. These files are in the `EXTRA_DIST` list. Other source files are in the `libpsm3_la_SOURCES` list. Both are guarded by the `HAVE_PSM3` and `HAVE_PSM3_SRC` conditions. However, when running `make dist` the conditions are ignored for `libpsm3_la_SOURCES` but not for `EXTRA_DIST`. As the result, if the psm3 provider is not enabled these files will not be included in the tarball.

**Comment by shefty** [comment]
The tarfile should have been created using make distcheck, otherwise that's the same.

**Comment by j-xiong** [comment]
`make distcheck` would call `make dist` first and then do check. So they are equivalent in terms of tarball creation. If you check the `config.log` (if still there) I bet psm3 provider was not enabled.

**Comment by shefty** [comment]
Yeah, my config.log has been overwritten.  So, the work-around for now might be to use configure --disable-psm3.  And it sounds like I can regenerate a new tarball from the same git tag as an updated release, but I need to determine what's the best option here.

**Comment by j-xiong** [comment]
No, you want to use `--enable-psm3` option. That way you will know why psm3 failed the check.  With `disable-psm3` you will get the same tarball as the released one.

**Comment by j-xiong** [comment]
This is probably the reason:
```
checking infiniband/verbs.h usability... no
checking infiniband/verbs.h presence... no
checking for infiniband/verbs.h... no
```

**Comment by acgoldma** [comment]
> I don't know what caused psm3 to disable itself, but that explains why the problem wasn't caught.
 
> I think what I want to do is update the psm3 makefile, commit those changes, and generate a v1.15.1 release, so that we don't have 2 different tarballs posing as the v1.15.0 release.

**Comment by acgoldma** [comment]
Sorry, wrong button. Yes, psm3 needs verbs/rdma-core to build.

**Comment by acgoldma** [comment]
When I run `make distcheck` I am not seeing any issues with psm3. Is the issue that the `EXTRA_DIST` is within an `if` block?

**Comment by shefty** [comment]
@acgoldma - why?  I thought it was supposed to work over standard sockets.

If you configure with --disable-psm3, followed by make dist, that *might* show the issue.  But only if you try to build after creating the tarfile, this time with configure --enable-psm3.

**Comment by j-xiong** [comment]
@acgoldma The makefile generated with autotools would always include files in the `xxx_la_SOURCES` list in the dist tarball, even if it is in a `if` block. However, files in `EXTRA_DIST` are not.

I think the ultimate fix is to move the EXTRA_DIST definition out from the `if` block.

**Comment by acgoldma** [comment]
> @acgoldma - why? I thought it was supposed to work over standard sockets.

`psm3` supports multiple HALs: Verbs (UD and RC QPs) as well as Sockets (TCP/UDP). 

> If you configure with --disable-psm3, followed by make dist, that _might_ show the issue. But only if you try to build after creating the tarfile, this time with configure --enable-psm3.

Odd, the Makefile in the tarball show the files in the expected locations (in chksum_srcs and EXTRA_DIST).



> @acgoldma The makefile generated with autotools would always include files in the `xxx_la_SOURCES` list in the dist tarball, even if it is in a `if` block. However, files in `EXTRA_DIST` are not.
> 
> I think the ultimate fix is to move the EXTRA_DIST definition out from the `if` block.

Thanks, I will try this now.

**Comment by shefty** [comment]
Honestly, I don't know that a provider should be messing with the global EXTRA_DIST at all.

**Comment by j-xiong** [comment]
Those .c files are used as header files which is not a recommended practice. In short term, they can be renamed to use different suffix and added to the src file list. The .S file seems to be unused.

**Comment by acgoldma** [comment]
> Those .c files are used as header files which is not a recommended practice. In short term, they can be renamed to use different suffix and added to the src file list. The .S file seems to be unused.

I would like to solve the main issue here. Can you move this discussion of the extra files to new issue/discussion.

I have a patch that should work for this testing now.

**Comment by shefty** [comment]
Those files are part of the main issue here.  We need to fix the underlying problem.  They shouldn't be extra dist files, and an unused assembly file shouldn't be there at all.  That leaves the VERSION file as the only baggage.  Why is that file needed?

**Comment by acgoldma** [comment]
Including a C file is a valid and useful to for performance critical subsystems.
Using extra_dist is the autotools 'recommended/only' way of doing this.

The VERSION file is used to generate the unique provider version. We theoretically could just pull this into the `prov/psm3/configure.*` files.
