### ISSUE TITLE
prov/verbs: Missing FI_INJECT support

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#774]
@a-ilango @shefty

I have started working on patches for this; please let me know if you plan to add FI_INJECT support in the near term (i.e., this week) so I don't duplicate effort.

This was prompted by two things: (1) EXS uses this feature, and (2) the `fi_msg_pingpong` tool currently crashes on the verbs provider since it sets the `FI_INJECT` flag for the finalize message.

**Comment by a-ilango** [comment]
@patrickmacarthur Please go ahead if you have already started working on this. I have a few changes regarding this but it is not complete.
