### ISSUE TITLE
prov/sockets: fi_shutdown() does not always issue FI_SHUTDOWN event at remote endpoint

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#776]
The man page for `fi_shutdown` states that the remote endpoint will get an `FI_SHUTDOWN` event; however, in practice, the sockets provider appears to only issue this event if the remote endpoint also calls `fi_shutdown()`.

This prevents the following scenario from working:
1. Endpoint A calls `fi_shutdown()`.
2. Endpoint B receives an `FI_SHUTDOWN` event.
3. In response, endpoint B calls `fi_shutdown()`, then cleans up the endpoint and all associated state.
4. Endpoint A receives an `FI_SHUTDOWN` event.
5. In response, endpoint A cleans up the endpoint and all associated state.

@shantonu @jithinjosepkl

**Comment by jithinjosepkl** [comment]
There is no restriction that both endpoints need to call fi_shutdown.

The cmatose example does something similar to your test scenario.
Send me your test program, I can take a look at it.

**Comment by patrickmacarthur** [comment]
I pushed a branch to my fabtests fork:

   https://github.com/patrickmacarthur/fabtests.git reproduce-bug-776

If you run a simple test with full logging enabled, you will see something like the following at the client:
```
libfabric:sockets:sock_ep_cm_enqueue_msg():283<3> Enqueued CM Msg
libfabric:sockets:sock_pe_progress_tx_ctx():2131<3> [0x62d890] TX done
libfabric:sockets:sock_ep_cm_send_msg():296<3> Sending message to 10.1.0.32:9228
libfabric:sockets:sock_ep_cm_send_msg():300<3> Total Sent: 16
libfabric:sockets:sock_ep_cm_send_msg():296<3> Sending message to 10.1.0.32:9228
libfabric:sockets:sock_ep_cm_send_msg():300<3> Total Sent: 16
libfabric:sockets:sock_ep_cm_send_msg():296<3> Sending message to 10.1.0.32:9228
libfabric:sockets:sock_ep_cm_send_msg():300<3> Total Sent: 16
libfabric:sockets:sock_ep_cm_send_msg():296<3> Sending message to 10.1.0.32:9228
libfabric:sockets:sock_ep_cm_send_msg():300<3> Total Sent: 16
libfabric:sockets:sock_ep_cm_send_msg():296<3> Sending message to 10.1.0.32:9228
libfabric:sockets:sock_ep_cm_send_msg():300<3> Total Sent: 16
```

and then both the client and server hang forever, which seems to indicate that the server is not actually receiving the `fi_shutdown` control message.

**Comment by jithinjosepkl** [comment]
Can you check the address that your server is bound to?

The test does not have an option to specify the src_addr and it could be taking 127.0.0.1
And client seems to be sending message to a non-loopback address.

The test appears to work fine for me:

Server:
[jose@cstnh-3 fabtests]$ ./simple/fi_msg
Posting a recv...
Waiting for client...
Received data from client: Hello World!
[jose@cstnh-3 fabtests]$

Client:
[jose@cstnh-3 fabtests]$ ./simple/fi_msg 127.0.0.1
Posting a send...
Send completion received
[jose@cstnh-3 fabtests]$

**Comment by patrickmacarthur** [comment]
I guess I forgot to specify that the utility that I modified was `fi_msg_pingpong`.  Sorry about that.

The command lines that I am using are:

    FI_LOG_LEVEL=3 simple/fi_msg_pingpong -f sockets -s <server_addr> -S 100 -I 10
    FI_LOG_LEVEL=3 simple/fi_msg_pingpong -f sockets -S 100 -I 10 <server_addr>

The -S and -I (uppercase i) options aren't mandatory but significantly reduce the amount of time and output with all debug info printed.

**Comment by jithinjosepkl** [comment]
Works fine for me:

Are you on latest libfabric? If not, please try that.
Also, I had to update the test program to check for -FI_EAGAIN on empty cq-read.
I think fabtests need to be updated for this.

Server:
jose@cstnh-3 fabtests]$  ./simple/fi_msg_pingpong -f sockets -s 192.168.10.3 -S 100 -I 10
name      bytes   iters   total       time     Gb/sec    usec/xfer
100_lat   100     10      1.9k        0.00s      0.26       3.05

Client:
[jose@cstnh-4 fabtests]$  ./simple/fi_msg_pingpong -f sockets -S 100 -I 10 192.168.10.3
name      bytes   iters   total       time     Gb/sec    usec/xfer
100_lat   100     10      1.9k        0.00s      0.89       0.90
[jose@cstnh-4 fabtests]$

**Comment by patrickmacarthur** [comment]
Even with latest libfabric and test modified to look for -FI_EAGAIN, I'm still seeing the test hang on my test systems.

I've also verified that the server is in fact listening on the correct port.

Are you sure you are on the right branch of my fabtests?  You should see (note that I pushed an update to catch the -FI_EAGAIN return):

    $ git describe
    v1.0.0alpha-72-g815afe9
    $ git show --oneline
    815afe9 Temporary fix to allow -FI_EAGAIN return
    ...

If you still don't see the issue, I'll have to do some more poking at this issue tomorrow to see what the difference between your configuration and my configuration is.

**Comment by jithinjosepkl** [comment]
@shantonu  got this error on her test-setup. 
The error was because the CM message was sent to PEP and PEP was getting closed.
This should be fixed with latest pr/sockets.

**Comment by shantonu** [comment]
I am working on modifying all the fabtests with -EAGAIN change. This will fix the test issue in your branch. @patrickmacarthur

**Comment by jithinjosepkl** [comment]
The test issue in your branch is regarding the handling of -FI_EAGAIN.
The loop in recv_xfer exits if ret == -FI_EAGAIN.

**Comment by patrickmacarthur** [comment]
From my preliminary check running just a single short `fi_msg_pingpong` test, @jithinjosepkl's PR does appear fix this issue.  I will plan to rebase my branch on top of @shantonu's fabtests -EAGAIN changes once they are complete and retest using a full test run.
