### ISSUE TITLE
valid range (and precise meaning) of signaling_vector is unclear

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#778]
Looking at the fi_cq(3) man page (and others that I've checked so far), it's not clear what values are valid for `signaling_vector`:

```c
              struct fi_cq_attr {
                  size_t               size;      /* # entries for CQ */
                  uint64_t             flags;     /* operation flags */
                  enum fi_cq_format    format;    /* completion format */
                  enum fi_wait_obj     wait_obj;  /* requested wait object */
                  int                  signaling_vector; /* interrupt affinity */
                  enum fi_cq_wait_cond wait_cond; /* wait condition format */
                  struct fid_wait     *wait_set;  /* optional wait set */
              };
```

And further down the page:
```
       signaling_vector : Indicates which processor core interrupts associated
       with the EQ should target.
```

I didn't see another value in the other man pages that indicates what the valid range for this value is.  Is it intended to be something like verbs' 1..`context->num_comp_vectors`?  Or is a logical core number expected instead?  Are negative numbers allowed (e.g., to specify "choose the 'best' affinity for me")?

**Comment by shefty** [comment]
This was defined more as a placeholder than anything else.  I'm not sure what values are valid or how they relate to anything.

**Comment by shefty** [comment]
As a proposal, this could be removed as part of the ABI bump.  I'm not fond of this option, as it could require apps to change their code in order to recompile against a newer library.

**Comment by goodell** [comment]
We could just mark it as deprecated instead.
