### ISSUE TITLE
prov/psm3: leaks shared memory files

### ISSUE THREAD

**Issue by hzhou** [ofiwg/libfabric#7800]
**Is your feature request related to a problem? Please describe.**
Since we (mpich) switched to use psm3 provider in our CI testing, the `/dev/shm` has been quickly filled up by shared memory files with the names like `psm3_shm.996.0x8003b4103:fe80000000000000:98039b03000c56de.0`. 

**Describe the solution you'd like**
1. A clear documentation on how to ensure cleaning up of shared memory
2. A configure option and/or a runtime option to disable use of shared memory in `psm3`

**Comment by ToddRimmer** [comment]
Documentation for PSM3 and related software can be found here: https://www.intel.com/content/www/us/en/support/articles/000088090/ethernet-products/intel-ethernet-software.html

See the Host User Guide.

The shm is used for intra-node communications.  If the MPI layer above is handling intra-node communications, the PSM support for it can be disabled by setting PSM3_DEVICES=self,nic (the default is self,shm,nic)

Chapter 9 has more information on cleaning up the shm files.  These are automatically cleaned up for successful jobs, but when  jobs are killed or segfault PSM does not get a chance to cleanup these files.  Normally a customer will use a job scheduler and can have a post job cleanup which covers these files.

**Comment by hzhou** [comment]
> The shm is used for intra-node communications. If the MPI layer above is handling intra-node communications, the PSM support for it can be disabled by setting PSM3_DEVICES=self,nic (the default is self,shm,nic)

Thanks @ToddRimmer . That should work for us.
