### ISSUE TITLE
daos file system plug network cable timeout link can not

### ISSUE THREAD

**Issue by xqcool** [ofiwg/libfabric#7803]
**Describe the bug**
After unplugging the network cable of the engine port of daos file system, wait for 1 minute, plug in the network cable, the network has been timeout or unavailable

**To Reproduce**
1/ Start daos_server
2/ dmg storage format
3/ Unplug the network cable of an engine
4/ wait for 1 minute
5/ plug in the network cable
6/mercury timeout or transport layer error

**Expected behavior**
Plug in the network cable network recovery

**Output**
If applicable, add output to help explain your problem. (e.g. backtrace, debug logs)

**Environment:**
centos7.9

**Additional context**
![log](https://user-images.githubusercontent.com/32193768/172120953-b11b771a-f4dc-45d6-8682-5216a406f1d8.png)

**Comment by chien-intel** [comment]
When running over verbs, please be specific on type of network controller used in the test case.  This is relevant, especially with link events, the device driver for the network controller is handling that situation and may not work the same from drivers for other verbs capable device.
If possible, provide modinfo for the device driver or infiniband software installed in the system (from CentOS 7.0 or MOFED for example).

**Comment by xqcool** [comment]
> When running over verbs, please be specific on type of network controller used in the test case. This is relevant, especially with link events, the device driver for the network controller is handling that situation and may not work the same from drivers for other verbs capable device. If possible, provide modinfo for the device driver or infiniband software installed in the system (from CentOS 7.0 or MOFED for example).

mlx5

**Comment by xqcool** [comment]
Using 'ofi+sockets'   network type, the program works fine

**Comment by xqcool** [comment]
daos version 2.02

**Comment by xqcool** [comment]
> When running over verbs, please be specific on type of network controller used in the test case. This is relevant, especially with link events, the device driver for the network controller is handling that situation and may not work the same from drivers for other verbs capable device. If possible, provide modinfo for the device driver or infiniband software installed in the system (from CentOS 7.0 or MOFED for example).

![log](https://user-images.githubusercontent.com/32193768/172280824-ec5f63b0-e967-4109-987f-308904beff95.png)

**Comment by j-xiong** [comment]
1 minute is long enough for a Verbs op to time out. Does DAOS/Mercury retry after timeout?

**Comment by xqcool** [comment]
> 1 minute is long enough for a Verbs op to time out. Does DAOS/Mercury retry after timeout?

Always in timeout state, retry only dping message, but will time out, need special retry (similar to TCP reconnection)?

**Comment by xqcool** [comment]
But there is no problem with 'ofi + sockets'

**Comment by xqcool** [comment]
![image](https://user-images.githubusercontent.com/32193768/172600216-81b9c45e-c546-4bd5-ac55-4d1697b4dee7.png)

**Comment by xqcool** [comment]
> I need "modinfo mlx5" not ibstat. That info is necessary so I can look at the correct version of the source code to help you. Without correct and detailed issue description it is difficult to narrow down the problem.

Hi, checked the version information, daos version number: v2.0 (c45320fb33)
mercury version number: v2.1.0rc4 (43abc30462)
fabric version number: v1.14.0 (119622b630)
![1](https://user-images.githubusercontent.com/32193768/172749976-e91c51c8-ec96-4ea8-a6a2-5147e063e5ef.png)

**Comment by xqcool** [comment]
> 1 minute is long enough for a Verbs op to time out. Does DAOS/Mercury retry after timeout?

Unplugging the network cable will prompt a send error, and plugging the cable keeps prompting a timeout. There should be a retry, but sending is abnormal.

**Comment by chien-intel** [comment]
> But there is no problem with 'ofi + sockets'
Actually the behavior is the same if you wait long enough.  Disconnect the cable for 16 minutes and same thing should happen.
You are hitting retransmission timeout.  With verbs and mlx5, the retry_cnt attribute on the QP (connection) is set to 7 (max and default value) which according to the table in this webpage (https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html) is 25.4 seconds.  So vary the time to cable reconnection and see if this holds.

**Comment by chien-intel** [comment]
did you get the same behavior with "ofi+sockets" after waiting 16 minutes?

**Comment by xqcool** [comment]
> > But there is no problem with 'ofi + sockets'
> > Actually the behavior is the same if you wait long enough.  Disconnect the cable for 16 minutes and same thing should happen.
> > You are hitting retransmission timeout.  With verbs and mlx5, the retry_cnt attribute on the QP (connection) is set to 7 (max and default value) which according to the table in this webpage (https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html) is 25.4 seconds.  So vary the time to cable reconnection and see if this holds.

I changed the number of retries to be the same as tcp, the same operation can be recovered within 16 minutes, sockets can be recovered, but verbs; rxm can not be recovered

**Comment by xqcool** [comment]
> did you get the same behavior with "ofi+sockets" after waiting 16 minutes?

Using ofi+sockets mode, after more than 20 minutes, the service of plugging in the Internet cable will return to normal.

**Comment by wangzhuo1016** [comment]
Is there any progress about this issue? I'm also facing the same problem.

**Comment by liuxuezhao** [comment]
@wangzhuo1016 just confirm did you test with latest libfabric + mercury? (or use latest daos master branch code)

**Comment by frostedcmos** [comment]
@wangzhuo1016 Also did you try with ofi+tcp;ofi_rxm ?

**Comment by liuxuezhao** [comment]
@wangzhuo1016 for the OFI level issue, may need @chien-intel to confirm if can be refined.

On the other hand, at DAOS level, you may test if can workaround it by a few other steps, for your steps -
1/ Start daos_server
2/ dmg storage format
3/ Unplug the network cable of an engine
4/ wait for 1 minute
5/ plug in the network cable

add these steps after step 5,
"./dmg -o ./daos_control.yml  system query -v" should be able to show that server rank be excluded after swim detects the network broken and evict it.
stop and restart that server rank by command like -                                                         
./dmg -o ./daos_control.yml -d system stop --force --ranks=                                            
./dmg -o ./daos_control.yml -d system start --ranks=              
and then reintegrate it back to system                                     
./dmg -o ./daos_control.yml -d pool reintegrate --pool= --rank=

**Comment by wangzhuo1016** [comment]
> > But there is no problem with 'ofi + sockets'
> > Actually the behavior is the same if you wait long enough.  Disconnect the cable for 16 minutes and same thing should happen.
> > You are hitting retransmission timeout.  With verbs and mlx5, the retry_cnt attribute on the QP (connection) is set to 7 (max and default value) which according to the table in this webpage (https://pracucci.com/linux-tcp-rto-min-max-and-tcp-retries2.html) is 25.4 seconds.  So vary the time to cable reconnection and see if this holds.



> did you get the same behavior with "ofi+sockets" after waiting 16 minutes?

roce v2 , provider: ofi+verbs;ofi_rxm, when the network recovery from fault(ifdown/ifup network interface  ),  I call ibv_query_qp to get rdma qp'state , and find the state is IBV_QOS_ERR, but the libfabric level doesn't prevent  this case from  spreading .So when network recovery from fault,  qp is always in a error state,  and that causes mesages timeout  in mercury and daos cart level @chien-intel

**Comment by chien-intel** [comment]
I had to get @ldorau to help me recreate the issue with all 3 providers to get the complete picture not just verbs.  We are discussing the next step for this issue.

**Comment by chien-intel** [comment]
BTW, doing a ifdown/ifup on an interface is different from physically pulling the cable.  To a certain point, it is also different from how we are reproducing the issue with mlxlink utility (we don't have the luxury of being physically located with our DUT).  So exactly what are you doing?  Please be precise.

**Comment by wangzhuo1016** [comment]
> BTW, doing a ifdown/ifup on an interface is different from physically pulling the cable. To a certain point, it is also different from how we are reproducing the issue with mlxlink utility (we don't have the luxury of being physically located with our DUT). So exactly what are you doing? Please be precise.

1/ Start daos_server
2/ dmg storage format
3/ ifdown/ifup an interface of a rank A( can be both client and server)
4/mercury timeout or transport layer error
Actually, when network recovery from fault, communication between client and server is always abnormal.
e.g.  rank A  sends message to other normal ranks by using rxm_tsend, rxm_tsend doesn't return error, but rxm_ep_do_progress gets error work completion, and wc.status is 5(IBV_WC_WR_FLUSH_ERR )  or 12(IBV_WC_RETRY_EXC_ERR).

**Comment by wangzhuo1016** [comment]
> BTW, doing a ifdown/ifup on an interface is different from physically pulling the cable. To a certain point, it is also different from how we are reproducing the issue with mlxlink utility (we don't have the luxury of being physically located with our DUT). So exactly what are you doing? Please be precise.

Hi, if you don't  have extra devices to test these issues(ifdown/ifup interface and plug/unplug the network cable ), I can help you to reproduce and provide you with related information and logs @chien-intel

**Comment by wangzhuo1016** [comment]
> @wangzhuo1016 for the OFI level issue, may need @chien-intel to confirm if can be refined.
> 
> On the other hand, at DAOS level, you may test if can workaround it by a few other steps, for your steps - 1/ Start daos_server 2/ dmg storage format 3/ Unplug the network cable of an engine 4/ wait for 1 minute 5/ plug in the network cable
> 
> add these steps after step 5, "./dmg -o ./daos_control.yml system query -v" should be able to show that server rank be excluded after swim detects the network broken and evict it. stop and restart that server rank by command like - ./dmg -o ./daos_control.yml -d system stop --force --ranks= ./dmg -o ./daos_control.yml -d system start --ranks= and then reintegrate it back to system ./dmg -o ./daos_control.yml -d pool reintegrate --pool= --rank=

I'm sorry for the delay. I did test with the steps that you had requested, but communication between normal rank(as client) and reseted rank(as server).
 When server rank is reseted and joined to daos cluster，It seems that the other normal rank still send rpc to the reseted rank with old rxm conn, but rxm conn is unavailible @liuxuezhao

**Comment by liuxuezhao** [comment]
@wangzhuo1016 in your test, did you confirm that "./dmg -o ./daos_control.yml system query -v" show that server rank be excluded before restart the server rank?  
For "It seems that the other normal rank still send rpc to the reseted rank with old rxm conn, but rxm conn is unavailible", what you observed is RPC timeout? is the timeout RPC between client and server, or between two server ranks? and the daos version you used is latest 2.0 branch?

**Comment by wangzhuo1016** [comment]
> @wangzhuo1016 in your test, did you confirm that "./dmg -o ./daos_control.yml system query -v" show that server rank be excluded before restart the server rank? For "It seems that the other normal rank still send rpc to the reseted rank with old rxm conn, but rxm conn is unavailible", what you observed is RPC timeout? is the timeout RPC between client and server, or between two server ranks? and the daos version you used is latest 2.0 branch?

1. rank is excluded before I restart the server rank;
2. RPC is timeout between two server ranks;
3. daos version is release 2.0. And I also test daos release 2.0 with  mercury  2.2.0-3 libfabric  1.15.1, the same happens @liuxuezhao

**Comment by liuxuezhao** [comment]
@wangzhuo1016 probably the code you used with some difference, it should work if do exclude+restart+reint. Let me explain a little bit about how it works in daos code path - 1) swim detects the server down, pool service handles the RAS event "CRT_EVT_DEAD" handle_event() -> pool_svc_exclude_rank() -> ds_rsvc_request_map_dist(), then a daemon ULT called map_distd will invoke pool_svc_map_dist_cb to send the latest pool map to all members; each daos server will do ds_pool_tgt_map_update() -> update_pool_group() -> crt_group_secondary_modify() that will evict that DEAD rank's info from group. and 2) in re-integrate, the new rank will be added by similar code path - pool_svc_update_map() -> ds_rsvc_request_map_dist(), and then each server ds_pool_tgt_map_update() -> update_pool_group() -> crt_group_secondary_modify() to add the rank to group. 
So after the "exclude + restart + reint" the new RPC communication will establish new connection after restart, you may check if the code path works or broken at your code base. 
For DAOS-level problem we may discuss by Email, and let's keep this thread focus on OFI-level. Thanks.

**Comment by chien-intel** [comment]
I'm looking at this issue.  I do see an issue with verbs provider, but I really need you guys to confirm the TCP behavior.
Please run the test case with TCP provider after changing ipv4 tcp_retries2 value to 6.
You can change the value by running this command as root "sysctl -w net.ipv4.tcp_retries2=6" and verified the new value with "sysctl -n net.ipv4.tcp_retries2"
It would be helpful to have a simpler testcase without all the DAOS services.  In issue 8314, someone suggested hg_example_rpc_* but you can't switch providers easily with that one.  I've looked at hg_test_bw but so far I don't think it behaves the same.  Perhaps I need to use CaRT level tests?

**Comment by wangzhuo1016** [comment]
> I'm looking at this issue. I do see an issue with verbs provider, but I really need you guys to confirm the TCP behavior. Please run the test case with TCP provider after changing ipv4 tcp_retries2 value to 6. You can change the value by running this command as root "sysctl -w net.ipv4.tcp_retries2=6" and verified the new value with "sysctl -n net.ipv4.tcp_retries2" It would be helpful to have a simpler testcase without all the DAOS services. In issue 8314, someone suggested hg_example_rpc_* but you can't switch providers easily with that one. I've looked at hg_test_bw but so far I don't think it behaves the same. Perhaps I need to use CaRT level tests?

I'm sorry for delay reply. With these steps(including ifdown/ifup interface and plug/unplug the network cable), CaRT communication between daos ranks can recover.
Environment:
linux centos7, daos v2.0 release libfabric  v1.14.0 release, mercury 2.1.0,rc， provider: ofi+sockets
ifdown/ifup
1. sysctl -w net.ipv4.tcp_retries2=6
2. dmg sto format
3. ifdown the network interface of a daos_server rank;
4. after 1min, ifup the interface 

unplug/plug the network cable
1. sysctl -w net.ipv4.tcp_retries2=6
2. dmg sto format
3. unplug the network cable of a daos_server rank;
4. after 1min, plug the network cable 
@chien-intel

**Comment by chien-intel** [comment]
With PR 8858, when the verbs connection exceeds retry timeout, it will be close and on subsequent use of the RXM connection a new verbs QP will get created.
