### ISSUE TITLE
Update README for release

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#782]
@pmmccorm Has made the valid argument that we should put some provider-specific information in the README.

Right now, the README is quite empty -- it is 12 lines long.  It doesn't document the (usnic-specific) `--with-libnl` configure option, for example (that's documented in the man page, but you don't get the man page until after you configure/build).  Or even the `--with-<provider>[=dl]` options.

I guess there's a few options on what to do here (and this is by no means a comprehensive list):

1. Update README to include a bit more comprehensive build / install instructions (e.g., and pointers to the man pages, after installation completes).  But still keep it very short.
1. Have a more fleshed-out README -- e.g., have provider-specific sections in README (e.g., usnic can document `--with-libnl` in the usnic section of README).
1. Assemble the final README from something like `cat README.top prov/*/README README.bottom > README` during "make dist".
1. Point to somewhere online that has the build/install instructions.

I'm not personally in favor of the last option -- I think the tarball should be self-contained.

**Comment by shefty** [comment]
Does the provider specific man pages solve this issue?

**Comment by jsquyres** [comment]
@shefty No, because the man pages aren't (easily) available until you build/install libfabric.

A user *could* do something like this:

```shell
$ man man/man7/fi_sockets.7
$ man man/man7/fi_psm.7
$ man man/man7/fi_usnic.7
$ man man/man7/fi_verbs.7
```

But I think that's a bit unwieldy.
