### ISSUE TITLE
Error compiling libfabric with icc

### ISSUE THREAD

**Issue by smichnowicz** [ofiwg/libfabric#7879]
Dear Group
I go an error compiling libfabric with icc

./prov/opx/include/opx_shm.h(388): error: a value of type "ofi_atomic_int64_t" cannot be used to initialize an entity of type "size_t={unsigned long}"
  		size_t seq = packet->sequence_.val;
  		             ^

compilation aborted for prov/opx/src/fi_opx_atomic.c (code 2)
make[1]: *** [prov/opx/src/src_libfabric_la-fi_opx_atomic.lo] Error 1
make[1]: Leaving directory `/usr/local/libfabric/1.14.1-gcc11.2.0-iwmvypjxzfhxw2ejdwrfyksljfcrtoxp/lib/LIBFABRIC/libfabric-1.15.

I was using intel-oneapi-compilers/2022.0.
and libfabric-1.15.1

Is this error easily resolved?
thanks
Simon

**Comment by j-xiong** [comment]
@timothom64 Could you check this? atomic types should be accessed via ofi_atomic_get*() functions.

**Comment by charlesshereda** [comment]
This bug was fixed in https://github.com/ofiwg/libfabric/commit/b43d902b0f993de1610f502b021d18136ec01638.

We did verify that we can build the OPX provider with icx (new name for icc) now.

**Comment by charlesshereda** [comment]
I don't have the ability to close this myself, so @smichnowicz, can you verify that you can now build the opx provider in the 1.17 release or main with icx?

**Comment by shefty** [comment]
Issue should have been resolved starting with v1.17 release.
