### ISSUE TITLE
FI_NAME_MAX and addrlen values returned from fi_getname

### ISSUE THREAD

**Issue by hppritcha** [ofiwg/libfabric#7898]
**Question**

What is the purpose of the ```FI_NAME_MAX``` enum defined in rmda/libfabric.h?  Is this the maximum length of the string that  can be returned in the ```addr``` argument to ```fi_getname```?

I'm asking because I'm working with a provider which needs more the ```FI_NAME_MAX``` bytes for the ```addr```.

I don't see anything about this enum in the man page.  Rather it describes an approach to using the ```fi_getname``` function  wherein one first obtains the buffer length required, then calls  second time with an appropriately sized buffer in which the endpoint name is returned.  Is this the preferred way to use this function?

thanks for any clarification.

**Comment by shefty** [comment]
Looking at the code, that constant should *not* have been defined in fabric.h and exposed to users.  I see it used as the max length of the node and service parameters passed to the AV calls (fi_av_insertsym and fi_av_insertsvc).  It's used as an internal check that the values are within what the provider and util_av code can handle.

The value may have been exposed above libfabric so fabtests could use it as well.  That was a mistake.
