### ISSUE TITLE
prov/efa: rx_entry allocation failure handling in rxr_pkt_handle_longcts_rtw_recv()

### ISSUE THREAD

**Issue by gestionlin** [ofiwg/libfabric#7920]
### Discussed in https://github.com/ofiwg/libfabric/discussions/7919

<div type='discussions-op-text'>

<sup>Originally posted by **gestionlin** August  3, 2022</sup>
Hi, I am studying the implemtation of efa_rdm_protocol_v4 in efa provider. I have some question below:
When a requestor send a LONGCTS_RTR packet to a responder, the responder will try to allocate a rx_entry according to the LONGCTS_RTR packet, but the allocation of rx_entry may fail, the handling of the failure seems to log a error and report an eq error to this upper layer? see rxr_pkt_handle_longcts_rtw_recv(). And the requestor is not notified of the error, it seems the tx_entry for the LONGCTS_RTR in the requestor will be stuck untill the EP is freed?

Thanks.</div>

**Comment by wzamazon** [comment]
Not sure where the discussion we had yesterday went.

You are right, in case rx_entry cannot be allocated. The requester will stuck

**Comment by gestionlin** [comment]
> Not sure where the discussion we had yesterday went.

https://github.com/ofiwg/libfabric/discussions/7919

I created the issue out of the above discussion, sorry for the confusion.
