### ISSUE TITLE
Build fails on riskv64 architecture

### ISSUE THREAD

**Issue by yurivict** [ofiwg/libfabric#7925]
**Describe the bug**
configure fails with "Cannot continue":
```
checking for rdma/rdma_cma.h... no 
configure: verbs provider: disabled
configure: WARNING: verbs provider was requested, but cannot be compiled
configure: error: Cannot continue
===>  Script "configure" failed unexpectedly.
```

**Environment:**
clang-11
FreeBSD 13.0-RELEASE

**Comment by yurivict** [comment]
This was only happening with older versions, and doesn't happen with the latest release.

**Comment by yurivict** [comment]
This was happening only with older versions.

**Comment by clausecker** [comment]
This now happens again with libfabric-1.15.1 on armv7 FreeBSD 14.
