### ISSUE TITLE
Definition of fi_tx_attr::size and fi_rx_attr::size

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#793]
The man page for `fi_endpoint` currently states that these sizes are measured in bytes.  Are these supposed to be measured in "max size" operations, to be consistent with `fi_tx_size_left()` and `fi_rx_size_left()`?  This would make sense to me so that an application has an input parameter to use to tune the number of available credits with regard to the query functions.

~~This also raises the question of the semantics of the sockets provider in this case.  If I request a tx size 64 (for example) in `fi_getinfo()`, and the sockets provider can only handle a single maximum-size message, does this mean that the sockets provider will return `-FI_ENODATA`?  Or should we special-case the sockets provider in this instance (and then put more burden on the application to deal with that special case)?~~

**Comment by shefty** [comment]
These sizes are in terms of max size operations.  The man page is incorrect.

I didn't follow the question on the sockets provider.

**Comment by patrickmacarthur** [comment]
I looked at the code and my question on the sockets provider is irrelevant.  I had assumed that the sockets provider had a limit based on the use of the socket buffer, which would mean that a single large message would consume the entire buffer.  Looking at the code, this isn't the case.

So the only remaining part of this issue is to fix the description in the man page.

**Comment by shefty** [comment]
Man pages updated
