### ISSUE TITLE
prov/sockets: CM timeout not reported to application

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#794]
The sockets provider makes several attempts to send a CM message, and after all of these attempts time out, it drops the pending message without making any attempt to notify the application.  When trying to establish a reliable connection, applications will expect a notification that the connection attempt failed or timed out via the bound EQ.

**Comment by jithinjosepkl** [comment]
OK, good catch. I will add this.

**Comment by jithinjosepkl** [comment]
@shefty - 
We should generate a CM error entry for timeout in case of fi_accept/fi_connect/fi_reject.
But what about fi_shutdown?

The manpage says:
 Note that in the abrupt close case, an FI_SHUTDOWN event will only be generated if the peer system is reachable and a service or kernel agent on the peer system is able to notify the local endpoint that the connection has been aborted.

Does this indicate fi_shutdown CM message timeout can be ignored?

**Comment by shefty** [comment]
If shutdown times out, I would expect the provider to generate a local SHUTDOWN event to indicate that things are done and future messages from the remote side will be discarded.

I.e. an app that calls fi_shutdown should receive a SHUTDOWN event eventually.  An app that doesn't call shutdown may wait forever.

**Comment by jithinjosepkl** [comment]
OK, makes sense. 

For CM connection timeouts, the error code should be set as FI_ETIMEDOUT, am i right (not FI_EIO)?
I think we should indicate this in man page as well.

**Comment by shefty** [comment]
I agree with ETIMEDOUT
