### ISSUE TITLE
prov/verbs: fi_ibv_cq_sread possible race condition

### ISSUE THREAD

**Issue by dardok** [ofiwg/libfabric#796]
`ibv_get_cq_event(3)` example shows that its necessary to re-arm the cq notifier **before** polling for completions, and that the completions must be drained before re-arming.  In the current `fi_ibv_cq_sread` implementation I believe its possible that an event may arrive after `ibv_poll_cq` but before `ibv_req_notify_cq`.  If the app is waiting on the underlying wait object, it will not be signaled (I've seen this occur in development of other verbs applications).

**Comment by dardok** [comment]
Ok, the situation here is in fact much more complicated.

Here's the problem:

As noted, verbs **requires** that completions be drained from the queue upon re-arming the notifier.  The `fi_ops_cq` interface is insufficient in that there is no corresponding explicit re-arm concept.

If the `fi_cq_sread` caller does not provide enough completion buffers, the `ibv_cq` might not be drained.  The provider implementation **cannot** try and look at the queue and determine if its empty and whether or not it can re-arm via `ibv_req_notify_cq`, since there's a real chance of the race condition described above (I really have seen this happen, and its seriously hard to track down).

In another project whereby verbs was implemented under a simplified interface, there ended up being complicated mechanics involving exposing an epoll fd that tracked the comp_channel->fd as well as an internal eventfd that was kept "hot" as necessary.  I see that as the only real solution here as well, without extending the `fi_ops_cq` interface.  I'll give it a try, but its going to be ugly...

**Comment by dardok** [comment]
When I said it would get ugly, I had little idea of just how ugly:

https://github.com/ofiwg/libfabric/compare/master...dardok:pr/verbs-notify-fixes

The provider has to cache excess completions obtained during the drain but not returned to the caller.  It must then return these cached completions first, before going back to `ibv_poll_cq` for more.  All sorts of devilish details ensue.  My implementation is **really** ugly, but I'm not even seeing conceptually cleaner ways to handle this.

Maybe a real look at the `fi_ops_cq` interface is in order here?  Like add a `fi_cq_reset` interface (I suspect this was already considered, given the presence of the `fi_ibv_cq_reset` internal function), and specify that it must be called before `fi_cq_sread`, and that `fi_cq_sread` must be called until it returns 0 (or FI_EAGAIN) before calling `fi_cq_reset` again?  Pulling up something like this from a specific provider seems backwards to the libfabric ideal, but I can't think of any other "clean" way to  address the problem in this case.

I believe this a show-stopper - either the provider has to deal with this mess (perhaps there's another way?) or the interface has to change...

**Comment by shefty** [comment]
> As noted, verbs requires that completions be drained from the queue upon
> re-arming the notifier. The fi_ops_cq interface is insufficient in that
> there is no corresponding explicit re-arm concept.

There are 2 queues in play here.  The event queue, which deals with the rearm, and the completion queue, where the actual completions go.

It should be possible to fix the verbs provider sread call, such that it matches this behavior (defined in the librdmacm):

282 static inline int
283 rdma_get_recv_comp(struct rdma_cm_id *id, struct ibv_wc *wc)
284 {
285         struct ibv_cq *cq;
286         void *context;
287         int ret;
288
289         do {
290                 ret = ibv_poll_cq(id->recv_cq, 1, wc);
291                 if (ret)
292                         break;
293
294                 ret = ibv_req_notify_cq(id->recv_cq, 0);
295                 if (ret)
296                         return rdma_seterrno(ret);
297
298                 ret = ibv_poll_cq(id->recv_cq, 1, wc);
299                 if (ret)
300                         break;
301
302                 ret = ibv_get_cq_event(id->recv_cq_channel, &cq, &context);
303                 if (ret)
304                         return ret;
305
306                 assert(cq == id->recv_cq && context == id);
307                 ibv_ack_cq_events(id->recv_cq, 1);
308         } while (1);
309
310         return (ret < 0) ? rdma_seterrno(ret) : ret;
311 }

This code only returns a single completion, but the number of completions that can be returned can be adjusted.  It doesn't matter if the call returns with completions still left on the CQ, or if the event queue is left with events on it.  Extra events on the event queue will end up being cleared on the next call, and the code already needs to handle reading events but finding the CQ empty.

The current verbs provider code expects that a new event will be generated if the CQ is rearmed, and there are unreaped completions on it.  I know this isn't to spec, but I thought that this is what the HW did.  It sounds like this is not the case, and we just need to update the code to handle this.

One of the reason for putting this logic into the provider is that it is difficult to get correct.

- Sean

**Comment by dardok** [comment]
"One of the reason for putting this logic into the provider is that it is difficult to get correct."

This is an understatement ;)  100% concur about trying to absorb the complexity.

I found the suffering I went through on this, and it was indeed adapter-specific behavior:

https://github.com/Eyescale/Equalizer/issues/99#issuecomment-5648770

I never used the rdmacm wrapper, probably because I was always looking to request some arbitrary number of completions (> 1).  I'm also not totally sure the wrapper will work properly in the case of the user depending on the `comp_channel->fd` trigger status.  I do think we'll still find that extending this for multiple completions will be difficult, as you're bound by what the caller provides buffer-wise to `fi_cq_sread`, and if there isn't enough space I believe one has to play the "caching" game and do some trickery in order keep a notifier "hot" for the user (if you believe the spec, you simply **cannot** determine if the queue is empty and re-arm without draining it).

This brings back fond memories :|

**Comment by shefty** [comment]
Supporting > 1 completion should just require wrapping the functionality from the librdmacm inside a for loop.  There should be no need for the provider to cache anything.  Once X number of completions have been read from the CQ, the call should return.

In the worse case, either the CQ is left armed, when it shouldn't be.  This simply causes an extra interrupt and event to be generated, which will be read the next time sread is called.  Or, an event (not a completion!) is left on the kernel event queue.  This will be read the next time sread is called too.

**Comment by shefty** [comment]
Assigning to Arun to take a look at this.

**Comment by dardok** [comment]
Thanks, again.  FYI, relevant guru quote (don't recall what guru): "Some adapters (eg mthca, mlx4) will generate an event immediately if ibv_req_notify_cq() is called for a CQ that contains an unpolled CQE, while other adapters (eg ipath, ehca) will only generate an event when a CQE is added after the call to ibv_req_notify_cq()."

**Comment by goodell** [comment]
It looks like this thread is going in a good direction, but I wanted to make sure that everyone is aware that current usnic hardware does not have a direct analog to a Mellanox/IB event queue.  So an API that does not assume "arming" semantics like this is desirable for us.  We can do a certain amount of emulation of that behavior, but simple masking/unmasking is a much better fit for usnic.  I also think it's a bit simpler for users to get right.

**Comment by dardok** [comment]
Quick follow up comment - I think its important to note that, as I see it, libfabric is exposing an "edge-triggered" interface here.  This means that, similar to how `epoll(7)` recommends, the suggested way to use `FI_GETWAIT` + `fi_cq_sread` should be "by waiting for an event only after `fi_cq_sread` returns -FI_EAGAIN."  Edge-triggered semantics are not often expected by default (which is why epoll changed the default right out of the gate!)  Its quite possible that the wait fd is not "ready" even though there are completion events pending.

My nightmare scenario above presumed a "traditional" application that was not prepared for this and was relying on level-triggered semantics and no magic "EAGAIN" return code.  Its important that any libfabric user be clear on how this is implemented.  $0.02...
