### ISSUE TITLE
prov/{sockets,verbs,psm}: FI_REMOTE_CQ_DATA in caps tests?

### ISSUE THREAD

**Issue by dardok** [ofiwg/libfabric#797]
Unlike FI_REMOTE_SIGNAL, the `fi_rma(3)` man page isn't explicit that "the remote endpoint must be configured with" this capability in order to use it for RMA.  A couple fabtests (msg_rma & rdm_rma) might request this cap, and fail in that case since none of the providers' tests currently check and allow this bit.

So, is it a capability that must be requested and checked?  I have a feature branch that sticks it into the various providers' checks that appear to support it, if desired.

**Comment by shantonu** [comment]
FI_REMOTE_CQ_DATA is removed from capability and set by the provider(at least sockets). So the endpoints don't need to specify it in the capability. I have https://github.com/ofiwg/fabtests/pull/199 that fixs the tests. 

fi_rma(3) ma page needs to be updated, @shefty can you please take a look?

**Comment by shefty** [comment]
Support for FI_REMOTE_CQ_DATA can be requested/verified by using the fi_domain_attr::cq_data_size.  A non-zero value indicates support.  The attribute applies at the domain level, not the endpoint level, as support is required both by the endpoint and the corresponding completion queue.
