### ISSUE TITLE
prov/opx: build warnings

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#7972]
Building with latest main:

prov/opx/src/fi_opx_av.c:111:5: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
     posix_memalign((void**)&opx_av->table_addr, sizeof(union fi_opx_addr), sizeof(union fi_opx_addr) * opx_av->table_count);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prov/opx/src/fi_opx_av.c:123:5: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
     posix_memalign((void**)&opx_av->table_addr, sizeof(union fi_opx_addr), sizeof(union fi_opx_addr) * opx_av->table_count);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
prov/opx/src/fi_opx_av.c:167:5: warning: ignoring return value of ‘posix_memalign’, declared with attribute warn_unused_result [-Wunused-result]
     posix_memalign((void**)&output_ext, 32/*sizeof(struct fi_opx_extended_addr)*/,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      sizeof(struct fi_opx_extended_addr) * count);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Also, please see latest coverity report for new issues.

**Comment by shefty** [comment]
I still see the warnings.  Looking at the code, the return value from the call is not checked.

**Comment by charlesshereda** [comment]
We haven't upstreamed the fix yet.
