### ISSUE TITLE
How to programmatically query HMEM support?

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#7973]
When I run an application using libfabric with `FI_LOG_LEVEL=debug` I can see messages such as the following which identify unsupported HMEM ifaces:

  `libfabric:[PID]:[TIMESTAMP]:core:core:ofi_hmem_init():222<info> Hmem iface FI_HMEM_[API] not supported`

Where `[API]` can be `[CUDA]`, `[ROCR]` or `[ZE]` in the libfabric releases I've been working with (12.0.1 through 1.15.1, fwiw).

I am looking for the proper mechanisms to query this sort of information pragmatically, for two different use cases:

1) How does one use `fi_info` or similar command line tool(s) to determine the presence or absence of (for instance) `FI_HMEM_CUDA` support in a given provider (e.g. `verbs;ofi_rxm`)?  This would be for a check in a `configure` script or similar.

2) How does one use `fi_*()` library calls to determine at run time the presence or absence of (for instance) `FI_HMEM_CUDA` in the current provider?

**Comment by shefty** [comment]
For the providers that support FI_HMEM, with the exception of psm3, FI_HMEM indicates the provider handles all available APIs.  Internally, there's a common hmem abstraction that the providers interface with that abstracts using CUDA vs Ze vs RoCR.  The hmem APIs that are usable depend on which libraries were available when libfabric was built.  That information is not easily available.

You can specify the FI_HMEM capability as input into fi_getinfo().  Any providers that return information indicate that they support hmem, but the only way to know if libfabric was built with CUDA support is to register a memory region (fi_mr_regattr()) with a CUDA buffer (fi_mr_attr::iface = FI_HMEM_CUDA) and check for success or ENOSYS.  There's no higher-level flag or attribute that conveys this information.

**Comment by PHHargrove** [comment]
Thanks for your quick response, @shefty .

What you say in the text quoted bellow, is exactly what I was _expecting_ and I have attempted to use it as a probe for the support.  However, my tests seem to be showing success from `fi_mr_regattr()` even when the `iface` is an unsupported value.  I am rechecking my logic and preparing a distinct issue to report that discrepancy if/when I can confirm the error is not the product of my own mistake(s).  I am closing _this_ issue.

> the only way to know if libfabric was built with CUDA support is to register a memory region (fi_mr_regattr()) with a CUDA buffer (fi_mr_attr::iface = FI_HMEM_CUDA) and check for success or ENOSYS.
