### ISSUE TITLE
prov/verbs: fi_mr_regattr() ignores `iface = FI_HMEM_CUDA` when should fail

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#7977]
**Describe the bug**

I was surprised (and disappointed) to find that in an install of libfabric configured without `--with-cuda` my calls to `fi_mr_regattr()` with verbs provider and `attr.iface == FI_HMEM_CUDA` succeed!

When the resulting (non-NULL) `fi_mr_desc()` result is used in a call to `fi_write()` with the source in CUDA memory, I find "regular" `memcpy()` being used (as seen in the backtrace from the SIGSEGV which results).  I would have hoped to have the memory registration fail, instead of providing a `desc` that cannot be used for the intended purpose.

**To Reproduce**

The attached reproducer opens verbs provider and _successfully_ registers CUDA memory, regardless of whether HMEM CUDA support is present or absent.

The following will compile the attachment, assuming correct values for OFI_HOME and CUDA_HOME:
```
gcc hmem_test.c -o hmem_test -I$OFI_HOME/include -I$CUDA_HOME/include -L$OFI_HOME/lib -L$CUDA_HOME/lib -lfabric -lcuda
```

An example run is shown in the **Output**, below

**Expected behavior**

In a build of libfabric verbs provider, configured without `--with-cuda`, I would expect that calls to `fi_mr_regattr()` with `attr.iface == FI_HMEM_CUDA` would fail.  In issue #7973 @shefty has **also** stated that `ENOSYS` is the expected result.

**Output**

Below is an example run with `FI_LOG_LEVEL=debug` used to confirm that `FI_HMEM_CUDA` support is *absent*, yet the test runs to completion having *not* seen a `ENOSYS` (nor `-FI_ENOSYS`) return from `fi_mr_regattr()`.  This is with `verbs;ofi_rxm` provider in libfabric 1.15.1.

```
$ env FI_LOG_LEVEL=debug ./hmem_test |& grep -e CUDA -e FATAL
libfabric:15958:1662089396::core:core:ofi_hmem_init():229<info> Hmem iface FI_HMEM_CUDA not supported
libfabric:15958:1662089396::core:core:ofi_hmem_init():229<info> Hmem iface FI_HMEM_CUDA not supported
Done: "successfully" registered CUDA memory
```

This result is "wrong" because the expected result is an error return from the call to `fi_mr_regattr()`.

**Environment:**

Linux  
`verbs;ofi_rxm` provider in libfabric versions from 1.12.1 to 1.15.1  
RDM endpoint  

**Additional context**

Note that my experience and report are specific to `verbs` provider and `FI_HMEM_CUDA` because that is what I have reliable access to.  However, I don't have any reason to think this problem is limited to a specific provider or hmem iface value.

**Comment by shefty** [comment]
libfabric doesn't need to be configured using --with-cuda for it to build with cuda support.  By default, it will see if cuda is available and build in support for it if present.

Anyway, onto the problem.  Quickly tracing through the verbs provider, it looks like the code ends up in ```vrb_mr_reg_common```.  That call simply calls ibv_reg_mr().  The iface parameter is basically ignored (saved off).  I don't see any checks by the provider to verify that the iface passed in is actually supportable.

**Comment by PHHargrove** [comment]
> libfabric doesn't need to be configured using --with-cuda for it to build with cuda support. By default, it will see if cuda is available and build in support for it if present.

Thanks, @shefty , for that correction/clarification.  I have always needed `--with-cuda=[something]` on _my_ systems to find the CUDA libs.  So I made an incorrect extrapolation based on my own experience.

**Comment by PHHargrove** [comment]
Here is the reproducer attachment that seems to have been dropped (with an extra .txt suffix to get past github's filetype limits).
[hmem_test.c.txt](https://github.com/ofiwg/libfabric/files/9480749/hmem_test.c.txt)
