### ISSUE TITLE
CodeStyle

### ISSUE THREAD

**Issue by tschuett** [ofiwg/libfabric#8050]
**Is your feature request related to a problem? Please describe.**
I had some issues with indentation, spaces vs. tabs, and line length in my first PR.

**Describe the solution you'd like**
I read in one PR that libfabric follows the kernel style, but it is not documented. The kernel has a clang-format file at the root of the repository. Adding a clang-format file could enforce resp. document the code style.

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by tschuett** [comment]
rdma-core also has a clang-format file. It was copied from the kernel.

**Comment by j-xiong** [comment]
The reference for coding style is in the Wiki page: https://github.com/ofiwg/libfabric/wiki:

>* The coding style of this project resembles that of the [linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/coding-style.rst), please match your contributions to the prevailing style in the files.

Also pay attention to other items in that list. They help avoiding some common errors.
