### ISSUE TITLE
github actions: GH page updater and man page convertor not working after merge policy change 

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#8101]
**Describe the bug**
After we change the merge policy to "rebase and merge", the actions "GH man page updater" and "Man page convertor" failed to commit the changes back to the repo.

**To Reproduce**
Man page converter: compare the content of the generated man pages and corresponding markdown files. 
GH man page updater: compare the man pages at https://ofiwg.github.io/libfabric/main/man/ with the original markdown files.

A quick target to check is the "fi_peer" man page, which has been updated recently.

Also check the status of these actions since mid-June 2022, all of them were closed w/o merge.

**Expected behavior**
The man pages should match.

**Output**
n/a

**Environment:**
github.com

**Additional context**

**Comment by shefty** [comment]
gurgle -- we can revert to merge commits.

**Comment by shefty** [comment]
Merge commits was disabled.  I've re-enabled it.  I guess we need to touch each man page to trigger updates.?

**Comment by j-xiong** [comment]
I will try to run each action manually to see if it works.

**Comment by j-xiong** [comment]
Ok, I triggered the man page updater manually on main, v1.16.x and v1.15.x.  The commits were successfully applied to main and v1.16.x with updated man pages.  There was no changes on v1.15.x so no update was posted. All are as expected.

The GH man page updater is scheduled to run daily. Next time it runs the online man pages will be updated.

**Comment by j-xiong** [comment]
The GH man page updater is actually event triggered. So I manually run it and the changes was committed. 

The only thing we can't fix is that some of the man pages in the 1.16.0 and 1.16.1 release don't match the corresponding markdown file. I think we have live with it.
