### ISSUE TITLE
prov/verbs: ibv_create_cq: Invalid argument(22) 、ibv_create_qp: Cannot allocate memory(12)

### ISSUE THREAD

**Issue by AdjoiningCat** [ofiwg/libfabric#8256]
Hi,

I did a test on  a single node with 1 server and 4050 clients，found that only 4025 clients can establish a link with the server, the rest clients all report a -FI_ENODATA error while calling fi_getinfo. 
I opened the info log and then find out there was a earlier error while calling vrb_get_qp_cap:
    ibv_create_cq: Invalid argument(22)     or     ibv_create_qp: Cannot allocate memory(12) 
I am using the RXM endpoint, I wonder why I can't create queues? The current count of qp or cq are both not up to the limit, and the machine memory is sufficient, only 150g is used, more than 350g is available.

I also ran ib_send_lat after the clients were up, it told me to reduce the qp size by decreasing the tx size or inline size. My tx size is 1, so I adjusted FI_VERBS_INLINE_SIZE to 8, but it doesn't work, the inline size is still 236 when I ran ib_send_lat again. 
I wonder what other environments can be adjusted to make it work, or some value I gave to the environments are wrong?

Thanks in advance for your precious time!

> Version: 1.13.2

> Environment:

       FI_PROVIDER="verbs"
       FI_VERBS_IFACE=ens800f0
       FI_VERBS_DEVICE_NAME=mlx5_2
       FI_VERBS_GID_IDX=3
       FI_VERBS_TX_SIZE=2
       FI_VERBS_RX_SIZE=2
       FI_UNIVERSE_SIZE=4050
       FI_OFI_RXM_BUFFER_SIZE=4096
       FI_OFI_RXM_MSG_TX_SIZE=4       
       FI_OFI_RXM_MSG_RX_SIZE=4
       FI_OFI_RXM_TX_SIZE=1
       FI_OFI_RXM_RX_SIZE=1

 

>ibv_devinfo -v:

    hca_id: mlx5_2
        transport:                      InfiniBand (0)
        fw_ver:                         16.29.1436
        node_guid:                      043f:7203:00e2:f322
        sys_image_guid:                 043f:7203:00e2:f322
        vendor_id:                      0x02c9
        vendor_part_id:                 4121
        hw_ver:                         0x0
        board_id:                       ORC0000000003
        phys_port_cnt:                  1
        max_mr_size:                    0xffffffffffffffff
        page_size_cap:                  0xfffffffffffff000
        max_qp:                           131072
        max_qp_wr:                      32768
        device_cap_flags:               0xed721c36
                                        BAD_PKEY_CNTR
                                        BAD_QKEY_CNTR
                                        AUTO_PATH_MIG
                                        CHANGE_PHY_PORT
                                        PORT_ACTIVE_EVENT
                                        SYS_IMAGE_GUID
                                        RC_RNR_NAK_GEN
                                        MEM_WINDOW
                                        XRC
                                        MEM_MGT_EXTENSIONS
                                        MEM_WINDOW_TYPE_2B
                                        RAW_IP_CSUM
                                        MANAGED_FLOW_STEERING
                                        Unknown flags: 0xC8400000
        max_sge:                        30
        max_sge_rd:                   30
        max_cq:                         16777216
        max_cqe:                        4194303
        max_mr:                         16777216
        max_pd:                         16777216
        max_qp_rd_atom:                 16
        max_ee_rd_atom:                 0
        max_res_rd_atom:                2097152
        max_qp_init_rd_atom:          16
        max_ee_init_rd_atom:           0
        atomic_cap:                     ATOMIC_HCA (1)
        max_ee:                          0
        max_rdd:                        0
        max_mw:                         16777216
        max_raw_ipv6_qp:                0
        max_raw_ethy_qp:                0
        max_mcast_grp:                  2097152
        max_mcast_qp_attach:            240
        max_total_mcast_qp_attach:      503316480
        max_ah:                         2147483647
        max_fmr:                        0
        max_srq:                        8388608
        max_srq_wr:                     32767
        max_srq_sge:                    31
        max_pkeys:                      128
        local_ca_ack_delay:             16
        general_odp_caps:
                                        ODP_SUPPORT
                                        ODP_SUPPORT_IMPLICIT
        rc_odp_caps:
                                        SUPPORT_SEND
                                        SUPPORT_RECV
                                        SUPPORT_WRITE
                                        SUPPORT_READ
                                        SUPPORT_SRQ
        uc_odp_caps:           NO SUPPORT
        ud_odp_caps:          SUPPORT_SEND
        xrc_odp_caps:
                                        SUPPORT_SEND
                                        SUPPORT_WRITE
                                        SUPPORT_READ
                                        SUPPORT_SRQ
        completion timestamp_mask:                      0x7fffffffffffffff
        hca_core_clock:                 78125kHZ
        raw packet caps:
                                        C-VLAN stripping offload
                                        Scatter FCS offload
                                        IP csum offload
                                        Delay drop
        device_cap_flags_ex:            0x30000055ED721C36
                                        RAW_SCATTER_FCS
                                        PCI_WRITE_END_PADDING
                                        Unknown flags: 0x3000004100000000
        tso_caps:
                max_tso:                        262144
                supported_qp:                                   SUPPORT_RAW_PACKET
        rss_caps:
                max_rwq_indirection_tables:                     16777216
                max_rwq_indirection_table_size:                 256
                rx_hash_function:                               0x1
                rx_hash_fields_mask:                            0x800000FF
                supported_qp:
                                        SUPPORT_RAW_PACKET
        max_wq_type_rq:                 8388608
        packet_pacing_caps:
                qp_rate_limit_min:      1kbps
                qp_rate_limit_max:      100000000kbps
                supported_qp:
                                        SUPPORT_RAW_PACKET
        tag matching not supported
        cq moderation caps:
                max_cq_count:   65535
                max_cq_period:  4095 us
        maximum available device memory:        131072Bytes
        num_comp_vectors:               63
                port:   1
                        state:                  PORT_ACTIVE (4)
                        max_mtu:                4096 (5)
                        active_mtu:             4096 (5)
                        sm_lid:                 0
                        port_lid:               0
                        port_lmc:               0x00
                        link_layer:             Ethernet
                        max_msg_sz:             0x40000000
                        port_cap_flags:         0x04010000
                        port_cap_flags2:        0x0000
                        max_vl_num:             invalid value (0)
                        bad_pkey_cntr:          0x0
                        qkey_viol_cntr:         0x0
                        sm_sl:                  0
                        pkey_tbl_len:           1
                        gid_tbl_len:            256
                        subnet_timeout:         0
                        init_type_reply:        0
                        active_width:           4X (2)
                        active_speed:           25.0 Gbps (32)
                        phys_state:             LINK_UP (5)
                        GID[  0]:               fe80:0000:0000:0000:063f:72ff:fee2:f322, RoCE v1
                        GID[  1]:               fe80::63f:72ff:fee2:f322, RoCE v2
                        GID[  2]:               0000:0000:0000:0000:0000:ffff:c0a8:a801, RoCE v1
                        GID[  3]:               ::ffff:192.168.168.1, RoCE v2

**Comment by AdjoiningCat** [comment]
> 1、
ulimit -l
unlimited

> 2、udaddy test

server: udaddy 
udaddy: starting server
receiving data transfers
(no returned)

client: udaddy -s 192.168.168.1 -c 4050
udaddy: starting client
udaddy: connecting
udaddy: event: RDMA_CM_EVENT_UNREACHABLE, error: 2
test complete
return status 2

**Comment by AdjoiningCat** [comment]
> 1、ulimit -l

unlimited

> 2、udaddy test

server:  udaddy -b 192.168.168.1 -c 6000
udaddy: starting server
receiving data transfers
sending replies
data transfers complete
test complete
return status 0

client:  udaddy -s 192.168.168.1 -c 6000
udaddy: starting client
udaddy: connecting
initiating data transfers
receiving data transfers
data transfers complete
test complete
return status 0

**Comment by AdjoiningCat** [comment]
I also did tests after my clients were all up

> udaddy

server: udaddy -b 192.168.168.1 
udaddy: starting server

client: udaddy -s 192.168.168.1 
udaddy: starting client
udaddy: connecting
udaddy: unable to create CQ
test complete
return status -12

> rdma_server & rdma_client

server: rdma_server
rdma_server: start

client: rdma_client -s 192.168.168.1
rdma_client: start
rdma_create_ep: Cannot allocate memory
rdma_client: end -1

**Comment by chien-intel** [comment]
Please show the following after your clients are up:
ulimit -a
free -h
rdma res

If numbers are "normal" something else is limiting resource allocation.  So how is your server configured?

**Comment by AdjoiningCat** [comment]
Here are the results after my clients are up, but I don't understand about the "rdma res", you mean the result of ibv_create_qp? It returns NULL. Besides, the FI values of the server are all as the same as the values of clients which I mentioned at first.

> ulimit -a
```
ore file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2060178
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) unlimited
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

>  free -g
```
                total        used        free      shared  buff/cache   available
Mem:            503          92         409           0           0         408
Swap:             0           0           0
```

> fi_info -p verbs
```
libfabric:31825:core:core:fi_param_get_():281<info> variable perf_cntr=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable hook=<not set>
libfabric:31825:core:core:ofi_hmem_init():209<info> Hmem iface FI_HMEM_CUDA not supported
libfabric:31825:core:core:ofi_hmem_init():209<info> Hmem iface FI_HMEM_ROCR not supported
libfabric:31825:core:core:ofi_hmem_init():209<info> Hmem iface FI_HMEM_ZE not supported
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_cache_max_size=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_cache_max_count=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_cache_monitor=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_cuda_cache_monitor_enabled=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_rocr_cache_monitor_enabled=<not set>
libfabric:31825:core:core:fi_param_get_():281<info> variable mr_ze_cache_monitor_enabled=<not set>
libfabric:31825:core:mr:ofi_default_cache_size():78<info> default cache size=3751454976
libfabric:31825:core:core:fi_param_get_():313<info> read long var universe_size=4050
libfabric:31825:core:core:fi_param_get_():290<info> read string var provider=verbs
libfabric:31825:core:core:fi_param_get_():290<info> read string var provider_path=/opt/intel/oneapi/mpi/2021.6.0//libfabric/lib/prov:/usr/lib64/libfabric
libfabric:31825:shm:core:fi_param_get_():281<info> variable sar_threshold=<not set>
libfabric:31825:shm:core:fi_param_get_():281<info> variable tx_size=<not set>
libfabric:31825:shm:core:fi_param_get_():281<info> variable rx_size=<not set>
libfabric:31825:shm:core:fi_param_get_():281<info> variable disable_cma=<not set>
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: shm (113.20)
libfabric:31825:core:core:ofi_register_provider():493<info> "shm" filtered by provider include/exclude list, skipping
libfabric:31825:ofi_rxm:core:fi_param_get_():313<info> read long var buffer_size=4096
libfabric:31825:ofi_rxm:core:fi_param_get_():313<info> read long var tx_size=1
libfabric:31825:ofi_rxm:core:fi_param_get_():313<info> read long var rx_size=1
libfabric:31825:ofi_rxm:core:fi_param_get_():313<info> read long var msg_tx_size=4
libfabric:31825:ofi_rxm:core:fi_param_get_():313<info> read long var msg_rx_size=4
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable cm_progress_interval=<not set>
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable cq_eq_fairness=<not set>
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable data_auto_progress=<not set>
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable use_rndv_write=<not set>
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable def_wait_obj=<not set>
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable def_tcp_wait_obj=<not set>
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: ofi_rxm (113.20)
libfabric:31825:verbs:core:fi_param_get_():295<info> read int var tx_size=2
libfabric:31825:verbs:core:fi_param_get_():295<info> read int var rx_size=2
libfabric:31825:verbs:core:fi_param_get_():281<info> variable tx_iov_limit=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable rx_iov_limit=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable inline_size=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable min_rnr_timer=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable use_odp=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable prefer_xrc=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable xrcd_filename=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable cqread_bunch_size=<not set>
libfabric:31825:verbs:core:fi_param_get_():295<info> read int var gid_idx=3
libfabric:31825:verbs:core:fi_param_get_():290<info> read string var device_name=mlx5_2
libfabric:31825:verbs:core:fi_param_get_():290<info> read string var iface=ens800f0
libfabric:31825:verbs:core:fi_param_get_():281<info> variable dgram_use_name_server=<not set>
libfabric:31825:verbs:core:fi_param_get_():281<info> variable dgram_name_server_port=<not set>
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens300f0 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens300f1 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens800f1 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: docker0 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens300f0 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: docker0 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens300f0 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:vrb_getifaddrs():1152<info> skipping interface: ens300f1 for FI_EP_MSG as it doesn't match filter: ens800f0
libfabric:31825:verbs:fabric:verbs_devs_print():883<info> list of verbs devices found for FI_EP_MSG:
libfabric:31825:verbs:fabric:verbs_devs_print():887<info> #1 mlx5_2 - IPoIB addresses:
libfabric:31825:verbs:fabric:verbs_devs_print():897<info>       192.168.168.1
libfabric:31825:verbs:fabric:verbs_devs_print():897<info>       fe80::bace:f6ff:fe0b:3e2c
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_0 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_0 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_1 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_1 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:verbs:fabric:vrb_get_qp_cap():479<info> ibv_create_qp: Cannot allocate memory(12)
libfabric:31825:verbs:fabric:vrb_get_qp_cap():479<info> ibv_create_qp: Cannot allocate memory(12)
libfabric:31825:verbs:fabric:vrb_get_qp_cap():479<info> ibv_create_qp: Cannot allocate memory(12)
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_3 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:verbs:fabric:vrb_init_info():1391<info> skipping device: mlx5_3 for FI_EP_MSG, it may have a filtered IPoIB interface (FI_VERBS_IFACE) or it may not have a valid IP address configured
libfabric:31825:ofi_rxd:core:fi_param_get_():281<info> variable spin_count=<not set>
libfabric:31825:ofi_rxd:core:fi_param_get_():281<info> variable retry=<not set>
libfabric:31825:ofi_rxd:core:fi_param_get_():281<info> variable max_peers=<not set>
libfabric:31825:ofi_rxd:core:fi_param_get_():281<info> variable max_unacked=<not set>
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: ofi_rxd (113.20)
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: udp (113.20)
libfabric:31825:core:core:ofi_register_provider():493<info> "udp" filtered by provider include/exclude list, skipping
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: sockets (113.20)
libfabric:31825:core:core:ofi_register_provider():493<info> "sockets" filtered by provider include/exclude list, skipping
libfabric:31825:tcp:core:fi_param_get_():281<info> variable nodelay=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable staging_sbuf_size=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable prefetch_rbuf_size=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable zerocopy_size=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable port_high_range=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable port_low_range=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable tx_size=<not set>
libfabric:31825:tcp:core:fi_param_get_():281<info> variable rx_size=<not set>
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: tcp (113.20)
libfabric:31825:core:core:ofi_register_provider():493<info> "tcp" filtered by provider include/exclude list, skipping
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: ofi_hook_perf (113.20)
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: ofi_hook_debug (113.20)
libfabric:31825:core:core:ofi_register_provider():465<info> registering provider: ofi_hook_noop (113.20)
libfabric:31825:ofi_rxm:core:ofi_check_fabric_attr():404<info> Requesting provider verbs, skipping verbs
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable use_srx=<not set>
libfabric:31825:core:core:ofi_layering_ok():959<info> Need core provider, skipping ofi_rxd
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable use_srx=<not set>
libfabric:31825:core:core:ofi_layering_ok():959<info> Need core provider, skipping ofi_rxd
libfabric:31825:ofi_rxm:core:fi_param_get_():281<info> variable use_srx=<not set>
libfabric:31825:core:core:ofi_layering_ok():959<info> Need core provider, skipping ofi_rxd
libfabric:31825:core:core:fi_getinfo_():1065<warn> fi_getinfo: provider ofi_rxm returned -61 (No data available)
libfabric:31825:core:core:ofi_layering_ok():959<info> Need core provider, skipping ofi_rxm
libfabric:31825:core:core:fi_getinfo_():1065<warn> fi_getinfo: provider ofi_rxd returned -61 (No data available)
fi_getinfo: -61
```

**Comment by chien-intel** [comment]
rdma tool is part of iproute2.  It will show your rdma resource consumption with "rdma res".

**Comment by AdjoiningCat** [comment]
before clients up
```
0: mlx5_0: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 1 srq 2 
1: mlx5_1: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 1 srq 2 
2: mlx5_2: pd 4 cq 4 qp 1 cm_id 1 mr 2 ctx 1 srq 2 
3: mlx5_3: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 1 srq 2 
```

after clients up
```
0: mlx5_0: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 4027 srq 2 
1: mlx5_1: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 4027 srq 2 
2: mlx5_2: pd 8056 cq 4030 qp 8053 cm_id 12079 mr 16159 ctx 4027 srq 2 
3: mlx5_3: pd 2 cq 3 qp 1 cm_id 0 mr 0 ctx 4027 srq 2 
```

the number of successful clients is 4026 this time
the ctx count of mlx5_0\mlx5_1\mlx5_3 also increased, but I have set FI_VERBS_DEVICE_NAME=mlx5_2, is this normal?

**Comment by chien-intel** [comment]
# of ctx does not make sense.  You want to look into what your app is doing.  Overall the numbers are within adapter's capability.  Your system must be configured with some kind of limit to cause memory allocation/QP/CQ creation errors.  Make sure all security features are disabled, SELinux for example.

**Comment by AdjoiningCat** [comment]
OK, I'll check my configuration

**Comment by AdjoiningCat** [comment]
I checked my configuration, didn‘t find any restrictions.

it seems like reaching the device memory limit.  
here is a portion of the strace output before and after the call to ibv_create_qp.

```
...
open("/dev/infiniband/uverbs2", O_RDWR|O_CLOEXEC) = 10
fstat(10, {st_mode=S_IFCHR|0666, st_rdev=makedev(231, 194), ...}) = 0
brk(NULL)                               = 0x55da68b53000
brk(0x55da68bab000)                     = 0x55da68bab000
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4230) = -1 ENOSPC (No space left on device)
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d41b0) = 0
mmap(NULL, 4096, PROT_READ, MAP_SHARED, 10, 0x500000) = 0x14789f9c5000
mmap(NULL, 4096, PROT_READ, MAP_SHARED, 10, 0x700000) = 0x14789f9c4000
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d1da0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d1da0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d1b90) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d3f90) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d3f80) = 0
mmap(NULL, 4096, PROT_WRITE, MAP_SHARED, 10, 0x900000) = 0x14789f9c3000
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4390) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d2f70) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d42f0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4420) = 0
mmap(NULL, 4096, PROT_WRITE, MAP_SHARED, 10, 0x900000) = 0x14789f9c3000
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4390) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d2f70) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d42f0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4420) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4740) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4420) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4740) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d31e0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4530) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d4250) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d41c0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd60c0) = -1 ENOMEM (Cannot allocate memory)
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd64f0) = 0
write(2, "libfabric:32527:core:core:vrb_ge"..., 83libfabric:32527:core:core:vrb_get_qp_cap():477<warn> === before ibv_create_qp === 
) = 83
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6150) = -1 ENOMEM (Cannot allocate memory)
write(2, "libfabric:32527:core:core:vrb_ge"..., 82libfabric:32527:core:core:vrb_get_qp_cap():479<warn> === after ibv_create_qp === 
) = 82
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6580) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd65a0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd5190) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd64e0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6200) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6170) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd60c0) = -1 ENOMEM (Cannot allocate memory)
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd64f0) = 0
write(2, "libfabric:32527:core:core:vrb_ge"..., 83libfabric:32527:core:core:vrb_get_qp_cap():477<warn> === before ibv_create_qp === 
) = 83
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6150) = -1 ENOMEM (Cannot allocate memory)
write(2, "libfabric:32527:core:core:vrb_ge"..., 82libfabric:32527:core:core:vrb_get_qp_cap():479<warn> === after ibv_create_qp === 
) = 82
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6580) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd65a0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd5190) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd64e0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6200) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6170) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd60c0) = -1 ENOMEM (Cannot allocate memory)
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd64f0) = 0
write(2, "libfabric:32527:core:core:vrb_ge"..., 83libfabric:32527:core:core:vrb_get_qp_cap():477<warn> === before ibv_create_qp === 
) = 83
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffcaccd6150) = -1 ENOMEM (Cannot allocate memory)
write(2, "libfabric:32527:core:core:vrb_ge"..., 82libfabric:32527:core:core:vrb_get_qp_cap():479<warn> === after ibv_create_qp === 
) = 82
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d45d0) = 0
ioctl(10, RDMA_VERBS_IOCTL, 0x7ffdd20d45f0) = 0
...
```

**Comment by chien-intel** [comment]
Looks like it is ctx that's limiting your application.  You can ask Mellanox about the limit on their device.  On the libfabric side, make sure you are using the correct fi_info and freeing them appropriately via fi_freeinfo.  Most likely you are allocating one per thread when you just need one.
