### ISSUE TITLE
Documentation of sync/async behavior for copy_*_hmem functions

### ISSUE THREAD

**Issue by lrbison** [ofiwg/libfabric#8268]
I'm implementing emulated atomics for prov/efa and noticed a lack of documentation around the `copy_to_hmem` and `copy_from_hmem` functions in hmem.c, and likewise for `copy_to_hmem_iov` in `fi_hmem_override_ops` (although as I look at the source, I don't think the override ops are used anywhere).

Specifically I'm wondering if every single copy operation can be assumed synchronous (ie, blocks until writes are visible to other threads and devices), or if there is an expectation that providers should make an effort to synchronize the device before generating a completion event.  If so, perhaps an interface for such a synchronization should be exposed in the ofi_hmem_ops structure.

Is there a place to find the synchronization expectations for these hmem functions?

**Comment by shefty** [comment]
There is no place where these are documented.  I have a note to add documentation for hmem and the mr cache to a man page somewhere.  I think both of those are important enough internal APIs that they should be documented.

For now, we're left looking at the implementation and referring back to the documentation of the underlying HMEM APIs (cuda, ze, etc.)

**Comment by lrbison** [comment]
Thanks Sean!

**Comment by shefty** [comment]
re-opening to track this until we have man pages for the calls.
