### ISSUE TITLE
workflows: Need to update actions to support node.js v16

### ISSUE THREAD

**Issue by acgoldma** [ofiwg/libfabric#8294]
**Describe the bug**
Warnings are being generated by the GitHub workflows that are using old actions. Need to update the actions to a newer revision. 

**To Reproduce**
Run and GitHub workflow.

**Expected behavior**
No Warnings.

**Output**
From: https://github.com/ofiwg/libfabric/actions/runs/3583990114

>macos
>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Environment:**
GitHub Actions

**Additional context**
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Example fix: 
```diff
- uses: actions/checkout@v2
+ uses: actions/checkout@v3
```

**Comment by acgoldma** [comment]
@rajachan , @aingerson , not sure who maintains this, just noticed the warnings recently, quick look and it should be just updating the actions to a newer version.

**Comment by rajachan** [comment]
I can take a look

**Comment by shefty** [comment]
I haven't noticed any recent warnings about this.  But I went ahead and updated actions to v3 based on the suggestions.  See PR #8982
