### ISSUE TITLE
prov/rxm: verbs, when server poweroff(reboot -f), rdma client not get event, when server up fi_tsend use old conn and server not get pkg

### ISSUE THREAD

**Issue by ssbandjl** [ofiwg/libfabric#8314]
**Describe the bug**
prov/rxm: verbs, when server poweroff(reboot -f), rdma client not get event, when server up fi_tsend use old conn and server not get pkg

**To Reproduce**
ofi+verbs;ofi_rxm
1. client fi_tsend to server(like hg_example_rpc_client -> hg_example_rpc_server), client loop(while true...) send to server
2. poweroff server(reboot -f)
3. client  fi_tsend return success(0), first can get FIEIO(5)Input/output error, then get 125(FIEAGAIN), but the rxm_conn always RXM_CM_CONNECTED, so use this conn fi_tsend
4. server bootup, and start hg_example_rpc_server
5. client use old conn(state=RXM_CM_CONNECTED) send pkg, ibv_post_send can get success(0), but server not get the pkg
6. for test, i set the conn state=RXM_CM_IDLE force, let fi_tsend reconnect to server, then can sent pkg to server

**Expected behavior**
when server reboot -f , server can get client's pkg

**Output**
If applicable, add output to help explain your problem. (e.g. backtrace, debug logs)

**Environment:**
OS (if not Linux), provider, endpoint type, etc.
centos7, server1: hg_example_rpc_client, server2: hg_example_rpc_server

**Additional context**

**Comment by chien-intel** [comment]
Please add more detail to your issue report.  Hardware setup, software version, commandline parameters (both sides), etc.  Something one can use to reproduce the issue.

**Comment by chien-intel** [comment]
what version of libfabric are you using?  Same question for hg_example_rpc_[server,client] where can I find this?

**Comment by ssbandjl** [comment]
> what version of libfabric are you using? Same question for hg_example_rpc_[server,client] where can I find this?

libfabric v1.14.0, mercury 2.1.0,rc4(hg_example_rpc_client and server)

**Comment by chien-intel** [comment]
> i'm confuse about
> 
> 1. server is poweroff , why rdma client not get disconnect event(or other rdma_cm_event), if get the disconnect event, client can reset then rxm_conn, i hope when server is (reboot -f), client can auto reconnect to server

Trace through the system and see what actually takes place at the level below libfabric?

**Comment by ssbandjl** [comment]
we only use verbs now, we add fi_close_conn(*ep, dst_addr) api in fabric local, when daos cart timeout -> abot  -> hg cancel -> fi_close_conn, then fi_tsend can rebuild connection, and ibv_post_send success, also server can get request pkg, but worry about  this bring some other problem
