### ISSUE TITLE
prov/opx: Build error with proposed v1.17.0rc2 package

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8322]
I'm trying to build the rc2 package.  After building the package, I attempted to build from the package.

```
./configure --enable-debug
make -j

prov/opx/src/opa_proto.c: In function ‘opx_hfi_userinit_internal’:
prov/opx/src/opa_proto.c:532:29: error: ‘HFI1_CAP_TID_RDMA’ undeclared (first use in this function); did you mean ‘HFI1_CAP_TID_UNMAP’?
     cinfo->runtime_flags &  HFI1_CAP_TID_RDMA? "HFI1_CAP_TID_RDMA" : "!HFI1_CAP_TID_RDMA",(__u64)HFI1_CAP_TID_RDMA,
```

**Comment by charlesshereda** [comment]
Looking at it.

**Comment by charlesshereda** [comment]
This appears to be connected to an older version of the kernel-headers package in Sean's build environment. Given that OPX only supports a subset of the distros supported by libfabric, we agreed we'll leave as-is for now and address it if it comes up for anyone. If it does arise, the workaround is to disable building opx.

A longer term solution would be to change the configure script to exclude opx in this case. We will do this if the number of complaints is significant enough to warrant it.
