### ISSUE TITLE
fi_provider(7): FI_ADDR, FI_ADDR_INDEX, FI_AV?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#833]
The [fi_provider(7)](http://ofiwg.github.io/libfabric/master/man/fi_provider.7.html) man page has this snippet:

> Address vectors must support FI_ADDR, FI_ADDR_INDEX, and FI_AV output formats.

But these things aren't really documented anywhere, as far as I can tell.  They also don't seem to exist as constants in any header.  Is this stale?

FI_ADDR is mentioned in the `map_addr` section of [fi_av(3)](http://ofiwg.github.io/libfabric/master/man/fi_av.3.html), but it doesn't make these constants any clearer to me.

**Comment by shefty** [comment]
This description is out of date and can just be dropped.

**Comment by goodell** [comment]
From both man pages?  If so, I'll file a PR.

**Comment by shefty** [comment]
I think we can remove this.  The provider requirements were written very early in the development cycle.  We should update them to reflect reality.  :)

**Comment by jsquyres** [comment]
Sean: we're updating the fi_usnic.7 page based on fi_provider.7.  Do you want to update the fi_provider.7 page?


> On Mar 31, 2015, at 2:29 PM, Sean Hefty <notifications@github.com> wrote:
> 
> I think we can remove this. The provider requirements were written very early in the development cycle. We should update them to reflect reality. :) 
> —
> Reply to this email directly or view it on GitHub.
> 


-- 
Jeff Squyres
jsquyres@cisco.com
For corporate legal information go to: http://www.cisco.com/web/about/doing_business/legal/cri/

**Comment by shefty** [comment]
I will try to update the page, but I won't get to it until after I can complete testing of the current master and some outstanding patches.
