### ISSUE TITLE
FI_SOCKADDR_IN6 requirement in fi_provider(7)?

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#834]
The fi_provider(7) man page lists this requirement:

> Address vectors associated with domains that may be identified using IP addresses must support FI_SOCKADDR_IN and FI_SOCKADDR_IN6 input formats.

Is IPv6 addressing a real requirement here?  I ask because usNIC is an IPv4-only technology right now, so it doesn't make sense for us to support general IPv6 addresses.  Or in our case is this requirement only really asking us to support the IPv4-mapped-to-IPv6 addresses (e.g., `::ffff:10.20.30.40`)?

**Comment by jithinjosepkl** [comment]
Same for sockets provider; currently supports only FI_SOCKADDR_IN.

**Comment by shefty** [comment]
We can drop IPv6 as a requirement.  The sockets provider does not support this either.

**Comment by goodell** [comment]
I'll file a PR for the fi_provider(7) man page.
