### ISSUE TITLE
hmem: attr.device.ze issue wrt multiple drivers

### ISSUE THREAD

**Issue by PHHargrove** [ofiwg/libfabric#8344]
I have tried, but failed, searching for online docs which clarify the value of `attr.device.ze` passed to `fi_mr_regattr()` together with `attr.iface == FI_HMEM_ZE`.  If answers to my questions are documented somewhere, then please point me at the docs.

Here is what I *think* is true based on my reading of the code:

The value of `attr.device.ze` is the ordinal of a device enumerated by `zeDeviceGet()` with the **first** driver from `zeDriverGet()` (subject to the `ZE_INIT_FLAG_GPU_ONLY` flag passed to `zeInit()`).

Can somebody confirm that the above is correct?

If so, can you please comment on plans (if any) to support

- Subdevices other than via `ZE_AFFINITY_MASK`
- Drivers other than the first
- Multiple drivers simultaneously 

Thanks,
-Paul

**Comment by PHHargrove** [comment]
> I think the best reference we have in the documentation is in fi_mr: https://ofiwg.github.io/libfabric/v1.16.1/man/fi_mr.3.html
> 
> ```
> For FI_HMEM_ZE, this is equivalent to the ze_device_handle_t index (int).
> ```
> 
> Does that help?

Thanks, @shefty .  I believe that confirms _most_ of my "I think is true based on my reading ..." if one makes the reasonable assumption that "index" is relative to the `zeDeviceGet()` enumeration of devices as constrained by `ZE_AFFINITY_MASK` and the `ZE_INIT_FLAG_GPU_ONLY` flag passed to `zeInit()`.  The applicability of those constraints to the "index" might be obvious to a Level Zero developer, but for me required reading `src/hmem_ze.c`.

I'd appreciate explicit conformation with regards to the apparent only-the-first-driver limitation in `src/hmem_ze.c`.  I say "apparent" based on what I believe is the only call to `ofi_zeDriverGet()` passing a count of 1 and giving the address of the file-scope `static ze_driver_handle_t driver;` as the second argument.

My request for information about plans with respect to multiple drivers is still unanswered as well.

Thanks.

**Comment by shefty** [comment]
I have no idea what Ze is trying to do with drivers vs devices.  I'm sure it makes sense to someone working on the HW, but to SW it seems goofy.  Part of this may have come from working with an early version of Ze.  I think what libfabric should use is ```*ze_device_handle_t``` instead of an index.  @aingerson @j-xiong will have better input.

**Comment by PHHargrove** [comment]
@shefty 
> I have no idea what Ze is trying to do with drivers vs devices. I'm sure it makes sense to someone working on the HW, but to SW it seems goofy. [...]

Exactly the position I find myself in.

> [...] I think what libfabric should use is *ze_device_handle_t instead of an index.

That is what I am favoring at the moment in my design for GASNet-EX's interfaces for oneAPI Level Zero device memory.  It is not too burdensome for me to perform device enumeration to map a device handle back to an index when calling libfabric for memory registration.  However, that leaves some risk without knowing what your plans are for multiple drivers.

Fwiw:
While it is the case that `src/hmem_ze.c` currently opens a single driver, there is no reason why that could not be changed in the future.  If one were to make the "obvious" change to wrap the current loop over devices with an outer loop over drivers, then the use of an index would remain well defined.  So, I do believe that a libfabric change to take a `ze_device_handle_t` (which is already a pointer, fwiw) instead of an index is not strictly necessary.   I just need to know that you don't plan (for instance) to encode device index in the low 16-bit and driver index in the upper 16-bits to retain the current `int` member in the `attr.device` union type.

If you do want to purse accepting a device handle in `attr.device.ze` then I have some concern about the ABI-breaking implications.  However, since a valid index is "never" (famous last words?) going to exceed 4095, I can imagine libfabric looking at the magnitude of the value to "magically" accept both the index and handle (possibly as `ze` and `ze_handle` members in the union type) while retaining a single `FI_HMEM_ZE` enum value.  Just my thoughts on the matter, in case they help.

**Comment by shefty** [comment]
See #8630 as a starting point for a fix for this.

**Comment by shefty** [comment]
Fixed by #8630.  Man page was updated to help clarify how to set the ze device value, along with providing a macro in the header file for that purpose.
