### ISSUE TITLE
sockets: fi_getinfo(..., node=NULL, ..., FI_SOURCE, ...) selects 127.0.0.1 by default

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#845]
I feel like there was a previous issue about this, but I can't seem to find it now so I'm filing this for the moment.

```
FI_PROVIDER=sockets FI_LOG_LEVEL=info FI_LOG_SUBSYS=^ep_data ./simple/fi_msg_pingpong
libfabric:core:core:fi_register_provider():121<info> registering provider: usnic (1.0)
libfabric:core:core:fi_register_provider():138<info> "usnic" filtered by provider include/exclude list, skipping
libfabric:core:core:fi_register_provider():121<info> registering provider: verbs (1.0)
libfabric:core:core:fi_register_provider():138<info> "verbs" filtered by provider include/exclude list, skipping
libfabric:core:core:fi_register_provider():121<info> registering provider: sockets (1.0)
libfabric:sockets:fabric:sock_ep_getinfo():327<info> src_addr: 127.0.0.1
libfabric:sockets:ep_ctrl:sock_pep_create_listener_thread():1018<info> Listener thread bound to 127.0.0.1:9228
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():861<info> Starting listener thread for PEP: 0x606900
```

I find it surprising that when `fi_msg_pingpong` passes `node=NULL` and `FI_SOURCE` to `fi_getinfo` that it gets back an endpoint that is bound to `127.0.0.1` by default.  I don't see any logic in the sockets provider that is explicitly selecting this; it appears to just take the first address returned by `getaddrinfo`.  But it might be desirable to improve that logic to sort by some sort of priority or to have support for binding to a wildcard address.

**Comment by shefty** [comment]
It's somewhat surprising to me that getaddrinfo returns that address, rather than a wildcard IP address.  I agree that it would make more sense to return a wildcard address.

**Comment by jithinjosepkl** [comment]
Yeah agree, makes more sense to return a wildcard address.
Let me see how to improve this.

**Comment by goodell** [comment]
@jithinjosepkl There's always a chance that it's something about my system.  If you're having trouble reproducing, just let me know and I can get you more information about what's happening.  This was on a RHEL6.5 system with 8 `ethX` interfaces and a single `lo` interface.  I didn't spend a lot of time debugging the issue, I just took a look at the logs and skimmed the sockets code.

**Comment by jithinjosepkl** [comment]
@goodell - Thanks. I see it locally as well.
Let me check how to improve this.
