### ISSUE TITLE
prov/net: CI reported crash in fi_cq_test

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8453]
Capturing CI reported failure with net provider.
```
name:   fi_cq_test -p "net"
13:26:49    timestamp: 20230202-212648+0000
13:26:49    result: Fail
13:26:49    time:   0
13:26:49    server_cmd:  /home/cstbuild/ofi-Install/libfabric/ofi_libfabric/PR-8448/8/dbg/bin/fi_cq_test -p "net"
13:26:49    server_stdout: |
13:26:49      Testing CQs on fabric 192.168.20.0/24
13:26:49      Running cq_open_close_sizes [Test open and close of CQ for various sizes]...PASS!
13:26:49      Running cq_open_close_simultaneous [Test opening several CQs at a time]...[debug] fabtests:unit/cq_test.c:75: testing creation of up to 256 simultaneous CQs
13:26:49      
13:26:49      PASS!
13:26:49      Running cq_signal [Test fi_cq_signal]...[error] fabtests:common/shared.c:1660: fi_close: Device or resource busy(-16) fid 2
13:26:49      [error] fabtests:common/shared.c:1661: fi_close: Invalid argument(-22) fid 13
13:26:49      fi_cq_test: prov/net/src/xnet_fabric.c:61: xnet_fabric_close: Assertion `dlist_empty(&fabric->wait_eq_list)' failed.
```
Several attempts to reproduce manually failed.  Line 1660 of shared.c is a call to close the EQ, which fails.  That failure is the reason for the later assert.    Line 1661 is closing a wait_set -- don't know how that's related.

The EQ close failure points to ofi_eq_cleanup() failing because a reference is being held on the EQ.

**Comment by shefty** [comment]
Problem shows up in PR #8448, and actually could be related to changes from that PR, or the PR is exposing an existing issue.

**Comment by aingerson** [comment]
@shefty I can reproduce it but only through runfabtests.sh, not manually running that specific test. I see it consistently fail with the changes and consistently pass without them so it's definitely related. I'll look into it.

**Comment by shefty** [comment]
Well that's weird.  I've been looking at the code and trying to trace back where an extra reference would have been kept.  I'm guessing it's something in the progress list area, but haven't identified it yet.

**Comment by aingerson** [comment]
Ok so I found the trigger in the changes - if the domain->ref is incremented before the wait object is created, it works; that's how it was before. But if the domain->ref is incremented after the wait object is created, that is what triggers the failure. I moved it to the end to help with cleanup. Do you know why that would affect it?

**Comment by shefty** [comment]
Can you copy the before and after change here?  I'm assuming you're refering to the atomic_inc before the switch statement

**Comment by aingerson** [comment]
Sorry my comment from before was backwards - if it's incremented before it breaks, after it works

**Comment by shefty** [comment]
and we're not going through a failure path, correct?

**Comment by aingerson** [comment]
correct. it gets all the way to the end

**Comment by shefty** [comment]
This makes no sense.  Something in the net provider must be off, especially since it's the only one failing.

**Comment by shefty** [comment]
I tried applying a similar change against the tip of main and it worked.  I think we're seeing a symptom of some other problem.

**Comment by aingerson** [comment]
Yeah I think so too.

Also, it's one of the specific cq tests that triggers the issue - cq_open_close_simultaneous. The other two (cq_signal and cq_open_close_sizes) don't trigger it.

**Comment by aingerson** [comment]
Figured it out. It was my changes. It runs out fds after a certain point and then defaults to wait none on the last 3 CQs. Will fix

**Comment by aingerson** [comment]
Hmm, that's also fun. Well I updated the PR and that should fix this issue

**Comment by shefty** [comment]
Why is defaulting to wait none causing the issue?

**Comment by aingerson** [comment]
The test tries the default wait object and then goes to none if it fails which it does after 253 calls
```
	for (opened = 0; opened < count && !ret; opened++) {
		ret = create_cq(&cq_array[opened], 0, 0, FI_CQ_FORMAT_UNSPEC,
				FI_WAIT_UNSPEC);
		if (ret) {
			ret = create_cq(&cq_array[opened], 0, 0,
					FI_CQ_FORMAT_UNSPEC, FI_WAIT_NONE);
		}
	}
```

**Comment by shefty** [comment]
I understand that.  But the provider should handle that anyway.  What in the changes broke this?

**Comment by aingerson** [comment]
I "broke" it by not decrementing the reference counter on failure :)
It still runs out of fds without the change, fabtests just tries again with wait_none on failure to avoid the failing wait_open call.
net sets it's wait open call to ofi_wait_fd_open which fails on `ret = socketpair(AF_UNIX, SOCK_STREAM, 0, signal->fd);` when creating the signal because it ran out of fds. fabtests tries again with wait_none which bypasses the wait_open call 
```
	switch (attr->wait_obj) {
	case FI_WAIT_NONE:
		wait = NULL;
		break;
```
Are you saying that net/the util code should internally fallback to wait_yield if the user passed in wait_unspec?

**Comment by shefty** [comment]
No, the provider should not fallback to wait yield.  I was trying to understand what change was missing or wrong that broke the test.
