### ISSUE TITLE
A general question for shared receive context in fi_peer API

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#8464]
Hello, in the `EXAMPLE PEER SRX SETUP` in https://ofiwg.github.io/libfabric/main/man/fi_peer.3.html, applications need to call `fi_srx_context()` for the owner provider (provider A) to allocate an `srx_a`. However, I would like to know if this procedure can be purely performed in the owner provider if it is configured to use provider B as a peer provider (coded
   into provider A or set through an environment variable). There are middlewares like Open MPI and mpich that use libfabric do not call this API explicitly, and I would like to avoid modifying their code to make them use srx when they interact with the owner provider in the old way.

Reading the `shared.c` in fabtests, the references to `srx` beyond `fi_srx_context` are `fi_ep_bind` and `fi_close` only. So fabtests do not really interact with srx for send/receive/CQ operations. I would like to know if it is generally true for applications so the modifications mentioned above could be avoided.

Thanks for your help in advance!

**Comment by aingerson** [comment]
The use case I'm targeting right now is similar to what you describe (using shm as a peer withing an internode provider without the application being aware of this). In this case, the owner manages everything with the srx. shm doesn't do anything (other than having the support to be used as a peer) and the application (ie OMPI) doesn't know about it either. Is this the use case you're talking about? Can you provide more details on what you're trying to do/how you are you hoping to pass around the srx/ep fid?

**Comment by shefty** [comment]
The intent is that peer APIs are only ever used between providers.  We don't want applications to call those APIs.  It should all be handled internally.  But because providers could be external to libfabric, these APIs end up needing to be exposed, like the fi_log() function.  Sure, an application could call it, but, uhm, why?

**Comment by shijin-aws** [comment]
>shm doesn't do anything (other than having the support to be used as a peer) and the application (ie OMPI) doesn't know about it either. Is this the use case you're talking about?

Yes, @aingerson @shefty Your comments answer all of my questions. Thank you very much.
