### ISSUE TITLE
Does the len field in cq_data_entry apply to write with remote cq data?

### ISSUE THREAD

**Issue by wzamazon** [ofiwg/libfabric#8472]
**Is your feature request related to a problem? Please describe.**

currently, libfabric document states that the "len" field in "fi_cq_data_entry" apply only to fi_recv and fi_trecv.

https://ofiwg.github.io/libfabric/v1.17.0/man/fi_cq.3.html

However, fi_write with FI_REMOTE_CQ_DATA will generate a cq_entry on the responder side, and this field will be very useful under such case. With out this, there might need to be additional message  to exchange the write length.

As far as I know, at least EFA provider and SHM provider will set this field as the actual write length in the fi_cq_data_entry generated on the responder. 

**Describe the solution you'd like**
Make sure all providers write this field properly on responder side, for write with FI_REMOTE_CQ_DATA, then update the document to reflect that his field apply to write with FI_REMOTE_CQ_DATA on the responder side.

**Comment by j-xiong** [comment]
Remote CQ data can also happen with send. Associating len with the CQ data won't be consistent between write and send. In addition, the size of CQ data is fixed for a provider and thus doesn't need an extra setting for that.

**Comment by wzamazon** [comment]
Sorry, I did not mean the length of the CQ data (which is fixed). I meant the message size.

For example, when user call `fi_write` to write a 1 MB message

If the user also specify FI_REMOTE_CQ_DATA, the responder of the `fi_write` will get a CQ entry. I think it would be useful for the `len` field in the CQ entry to be `1048576`.  

Currently, some provider already do this. (like EFA and SHM).

**Comment by wzamazon** [comment]
The reason the field may be useful for application is that application often provide a large buffer for other to write to.

For example, application know that the maximum write size is 4MB, then it can prepare a 4MB buffer for others to write to.

But the writer does not always write 4MB, it may only write 1MB. so this field can be used for the write responder to know how many bytes has been written to it.

**Comment by j-xiong** [comment]
Ah, that makes sense. I agree this is useful.

**Comment by shefty** [comment]
Verbs cannot provide this.  CQ data is really orthogonal here.  More generically, the request is to generate a completion at the target of an RMA operation with information about the operation that just occurred.  This could be a read or write.  The current API requires the sender to convey this information in a separate message.

There are associated protocol and implementation issues here.  If an RMA write is processed at the target, when would a local completion entry be generated?  This matters relative to the sending of any ACK for the RMA write.  The ACK could be lost, even for all retried operations.  In that case, the target gets a completion entry for an operation that will fail at the initiator.

This is also possible for send-recv operations, but in that case the receive buffer is removed from being accessed further by the network.  For RMA buffers that's not the case.  This means that a local completion at the target cannot safely guarantee that some retry mechanism won't modify the target buffer.

**Comment by wzamazon** [comment]
I think CQ data matters because if FI_REMOTE_CQ_DATA is not specified, write will not generate a CQ entry. for this issue does not apply.

Similarly, this does not apply to read because read will not generate CQ entry on responder side.

> Verbs cannot provide this.

Can you elaborate on why verbs cannot provide this?

AFAIK, verbs use rdma-core and FI_REMOTE_CQ_DATA in many ways is similar to rdma-core's write with immediate data. 

In `ibv_wc` there is a field `byte_len`, which the manual says "Number of bytes transferred ". I am no rdma-core expert, but I think this apply to both receive and write with immmediate data?

>  If an RMA write is processed at the target, when would a local completion entry be generated?

I am not sure. requester should always get its own completion. If app want the completion to be after the data is delivered, app should specify delivery complete.

**Comment by shefty** [comment]
RMA operations *could* be defined to generate completions at the target.

I checked the IB spec: ```The number of bytes transferred is returned in Work Completions for Receive Work Requests for incoming Sends and RDMA Writes with Immediate Data. This does not include the length of any immediate data.```  So, verbs can support this semantic.

The point about completions is that the target completion doesn't mean that the operation will complete successfully at the initiator.

In any case, it looks like we could change this with a new release version, as long as the providers update to match.

**Comment by wzamazon** [comment]
I checked `verbs` code, and seems verbs support this semantic:

https://github.com/ofiwg/libfabric/blob/cfed80fe50b3cec7ac806092a3bcb10d78f11ac0/prov/verbs/src/verbs_cq.c#L90

**Comment by wzamazon** [comment]
I opened https://github.com/ofiwg/libfabric/pull/8488  to update `fi_cq` man page to extend `len` to write with FI_REMOTE_CQ_DATA

**Comment by shefty** [comment]
updates merged upstream
