### ISSUE TITLE
Fallback code needed for os_unfair_lock: it does not exist on macOS <10.12

### ISSUE THREAD

**Issue by barracuda156** [ofiwg/libfabric#8496]
The following commit has broken the build of `mpich` which uses `libfabric` on multiple versions of macOS: https://github.com/ofiwg/libfabric/commit/476c8aeab92652f9ee889fa51f8a466b2083c90a
In particular, it uses functions available only on 10.12+: https://developer.apple.com/documentation/os/os_unfair_lock
See also: https://trac.macports.org/ticket/66925

Fallback code is required to unbreak the build.

**Comment by kencu** [comment]
Probably something like this:

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/spinlock.3.html

**Comment by barracuda156** [comment]
> Probably something like this:
> https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/spinlock.3.html

Looks like it precisely is: https://developer.apple.com/documentation/os/1646466-os_unfair_lock_lock
I will try to build with this tomorrow and see if it works.

**Comment by barracuda156** [comment]
@shefty (Tagging you since you asked about opening an issue.)
