### ISSUE TITLE
fabtests: fi_msg_inject is a rdm test by default

### ISSUE THREAD

**Issue by j-xiong** [ofiwg/libfabric#8515]
**Describe the bug**
In general, tests starting with `fi_msg_` test *FI_EP_MSG*, and tests starting with `fi_rdm_` test *FI_EP_RDM*.  The `fi_msg_inject` is different from others in that it tests *FI_EP_RDM* by default and can test other EP types with the `-e` option. This causes confusion and inconvenience when trying to interpret the test results and/or to exclude test based on test name patterns. 

This test used to be called `fi_inj_complete` which didn't have the problem. Alternatively, simply calling it `fi_inject` would also be less confusing.

**Comment by shefty** [comment]
Agree - needs to be renamed.  maybe fi_inject_msg, fi_inject_tx, fi_inject_test?  not sure -- fi_inject duplicates the function name and may not be the call being used, so I'm hesitant to use that.
