### ISSUE TITLE
Should we require EPs be bound to an AV before AV insert is invoked?

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#856]
See if this restriction causes a hardship on apps.  In some cases, such as IB UD or MXM, it may be simpler for the provider to have all endpoints associated with an AV before addresses are inserted into it.  It may be that the resolution will differ based on the local EP address, or that multiple resolutions may be necessary, one for each EP.  By allowing late binding, there's no way to report delayed resolution failures, and such resolutions must be handled in the synchronous fi_bind call.

**Comment by goodell** [comment]
The usnic BTL in Open MPI would have no problem with this restriction.

**Comment by shefty** [comment]
It seems that this would cause issues for MPI handling dynamic communication, where it may want additional endpoints or endpoint capabilities to distribute data transfers.  We should be able to work around this with IB UD.  For OFI over MXM, there would be an issue, but we don't want to restrict OFI based on some other higher-level interface.  OFI over verbs would map well.

If and MXM provider wanted to note or recommend that all EPs be bound to an AV before addresses are inserted, that's reasonable.  But I will reject this request as a general requirement.
