### ISSUE TITLE
Clarification on the usage of fi_mr_bind when FI_MR_ENDPOINT is used

### ISSUE THREAD

**Issue by JiakunYan** [ofiwg/libfabric#8584]
When FI_MR_ENDPOINT is used, is a memory region allowed to be bound to multiple endpoints? I have gone through the relevant manpages but it is still not clear to me.

**Comment by shefty** [comment]
From the viewpoint of the API, the intent is yes.  Though I guess a provider may not be able to support that if it needs to generate a separate key for each endpoint.  The only way I can think of this restriction happening is if FI_MR_PROV_KEY is also set.  But having that mr_mode bit set doesn't mean that the provider must use a separate key per endpoint.

So, if FI_MR_PROV_KEY is not set, I can't think of why there would be a restriction.  If it is set, there *might* be a restriction, but that depends on the provider.
