### ISSUE TITLE
core: Allow input and/or output of additional hmem details

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8599]
See #8529 for discussion.  There's a need to allow more information about how a provider may need to use hmem APIs, or the restrictions that an app could place on the provider.

**Comment by wzamazon** [comment]
I think this is not limited to HMEM.

Utilimately, I think we need to be able to add new entry to `fi_info` object without breaking compatibility.

**Comment by shefty** [comment]
fi_info or any of the existing attributes can easily be extended without breaking anything.  That's not a problem.

**Comment by shefty** [comment]
See issue #8610, which contains an outline of a proposal for the current problem based on discussions in the ofiwg.
