### ISSUE TITLE
sockets provider sees significant delays when using spinlocks

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#863]
Commit b6241b49404814a14bdd849ea2a714a308036889 fixed the compile such that spinlocks are now usable.  However, when enabled the sockets provider experiences delays of several seconds when running fabtests.

**Comment by shefty** [comment]
@shantonu @jithinjosepkl - Has this problem been resolved with the latest socket changes?

**Comment by jithinjosepkl** [comment]
No, we still have to investigate this. 
But we have switched to pthread_mutex for the lock which causes delay. 
So current version does not show delays.

**Comment by shefty** [comment]
Closing this as the code has been modified such that these delays are no longer seen.  We can reopen if testing shows a continued problem.

**Comment by jithinjosepkl** [comment]
I think the second thread is not getting a lot of time to grab the lock (at least with spin-locks). One thought is to split the list lock into tx-list_lock and rx-list_lock. This way the second thread has more chance. 

@shantonu - can you try this approach?
