### ISSUE TITLE
prov/opx: need update to provider feature matrix

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8776]
Please update the provider feature matrix wiki page with details on the opx provider.  The main, v1.18.x, and possibly older pages need updating.

**Comment by shefty** [comment]
@timothom64 - Can someone from Cornelis update the provider matrix wiki page?

**Comment by timothom64** [comment]
Yeap, I'm on it.  I did this internally quite a while ago, I'll upstream the patch soon

**Comment by timothom64** [comment]
Updated here:
https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-Main

I changed it in main, hopefully this will trickle into future releases

**Comment by shefty** [comment]
Thanks - yes, I copy from main for each new release.
