### ISSUE TITLE
build: windows

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#8778]
Track requirements and possible updates for windows build.

AppVeyor CI runs tests using socket provider.

- [x] Enable tcp build
- [x] Enable fabtests over tcp provider
- [ ] Replace socket CI testing with tcp provider

AppVeyor builds for VS 2015, 2017, and 2019.

- [x] Is support for 2015 needed?  If not, remove
- [x] Is support for 2017 needed?  If not, remove
- [x] Is support for 2022 needed?  If so, add

Note that EFA is currently building with 2015 and 2017, but not 2019.

**Comment by shefty** [comment]
@wckzhang - Can the AWS team comment on what support they require for building on Windows?  I'm specifically interested in whether we can drop 2015 from the CI given its age.  It's also worth looking at 2017.

I don't expect any changes to break older VS versions from working, so this should only be considering the CI.

**Comment by shijin-aws** [comment]
@shefty We have dedicated Windows test in AWS CI, and should not be impacted by AppVeyor CI changes

**Comment by shijin-aws** [comment]
And we are using VS2019

**Comment by shefty** [comment]
appveyor.yml has these lines:
```
    - configuration: Debug-Efa-v142
      image: Visual Studio 2015
    - configuration: Debug-Efa-v142
      image: Visual Studio 2017
    - configuration: Release-Efa-v142
      image: Visual Studio 2015
    - configuration: Release-Efa-v142
      image: Visual Studio 2017
```
Are you saying that these aren't needed (except as a backward compatibility build check)?  The windows build takes forever, so if we can move to 2019 & 2022, that could be good.

**Comment by shijin-aws** [comment]
@shefty I haven't realized we contributed these in appveyor.yaml. Need to ask @gurugubs .
