### ISSUE TITLE
fabtests: fi_rma_bw using WRITE doesn't perform verification

### ISSUE THREAD

**Issue by lrbison** [ofiwg/libfabric#8784]
On main branch, while testing a development driver, we find that `fi_rma_bw -e rdm -o writedata -j 0 -p efa -v -E` is finding data validation errors that should also occur in ` fi_rma_bw -e rdm -o write -j 0 -p efa -v -E`, yet the write test passes without complaint.

Need to investigate and fix the missing validation for the write case.

**Comment by shefty** [comment]
It's possible the test itself is wrong.  A bw tests repeatedly sends writes back to back.  If the target is supposed to verify the data, each write needs to go to a separate target buffer.  I would first check that the test does this before assuming there is a problem in the provider.

**Comment by lrbison** [comment]
So the test does indeed overwrite the same same memory buffer over and over, and as you say Wei there is some difficulty in knowing when is a valid time to test for valid data arriving on the remote side.

The window size is a convenient break.  Right now for a window size of W, fabtest submits W writes, then gets all W completions.  I decided that rather than putting each write into a separate buffer or separate section of the buffer, I that I would just verify data during this completion phase.

For hardware accelerated RDMA this seems to work, after I add sufficient synchronization, but when I was testing emulated RDMA on reads, I find that the buffer is corrupt.  I think this might be because ft_sync is using the same buffers that RDMA is using, and in fact ft_sync sends 1-byte messages in these buffers, but it also takes the time to set them up with valid data.

I'm hopeful I can figure out a well-rounded approach tomorrow.

**Comment by aingerson** [comment]
@lrbison In case it is helpful - the common code already allocates a buffer big enough to hold window_size number of transfers (8M * 64 * 2 - one for tx and one for rx) so I think to make it use different parts of the buffer would be pretty simple. You can just change the remote that you pass into the rma call to use an offset.

**Comment by lrbison** [comment]
I have taken the advice of both @wzamazon and @aingerson in a PR I submitted which should address this issue: https://github.com/ofiwg/libfabric/pull/8798
