### ISSUE TITLE
prov/tcp: compilation failes because liburing is too old (IORING_CQE_F_MORE missing)

### ISSUE THREAD

**Issue by bsbernd** [ofiwg/libfabric#8883]
prov/tcp/src/xnet_progress.c:1137:22: error: ‘IORING_CQE_F_MORE’ undeclared (first use in this function); did you mean ‘IORING_CQE_F_BUFFER’?
  if (!(cqe ->flags & IORING_CQE_F_MORE))
                      ^~~~~~~~~~~~~~~~~
                      IORING_CQE_F_BUFFER
prov/tcp/src/xnet_progress.c:1137:22: note: each undeclared identifier is reported only once for each function it appears in

bschubert2@imesrv2 github.upstream>ll /usr/include/liburing.h 
-rw-r--r-- 1 root root 15K Apr 12  2021 /usr/include/liburing.h

bschubert2@imesrv2 github.upstream>grep -r IORING_CQE_F_MORE /usr/include/
bschubert2@imesrv2 github.upstream>

**Comment by bsbernd** [comment]
This is on rocky8.7 with 

bschubert2@imesrv2 github.upstream>rpm -qa |grep uring
liburing-devel-1.0.7-3.el8.x86_64
liburing-1.0.7-3.el8.x86_64

**Comment by bsbernd** [comment]
Do I see it right that FI_CHECK_PACKAGE does not allow to check for defined values? So a separate compile time test would need to be added? Btw, @sydidelot is out this week.

**Comment by chien-intel** [comment]
HEAD compiled for me just fine.  IORING_CQE_F_MORE is defined in include/ofi_net.h in 6622e176afcf

**Comment by bsbernd** [comment]
That is in the else branch of HAVE_LIBURING. The issue comes when an old version of liburing/liburing-devel is installed.

**Comment by chien-intel** [comment]
yeah, you are correct.  I was compiling on a system without liburing-devel installed.

**Comment by sydidelot** [comment]
Because of the "multishot" feature, the TCP provider requires liburing >= 2.1. Do you now if it's possible to check the version of a library with autoconf? If not, we could check for the presence of `IORING_CQE_F_MORE` (or the function `io_uring_prep_poll_multishot()`) as suggested by @shefty.

**Comment by shefty** [comment]
It is safer to check directly for the definition or function that's needed, instead of relying on the version.

**Comment by sydidelot** [comment]
Patch submitted for review: https://github.com/ofiwg/libfabric/pull/8911
