### ISSUE TITLE
Need to bump main branch libfabric version

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#8904]
https://github.com/ofiwg/libfabric/blob/main/configure.ac#L11

Should it be updated to 1.19.0 or newer? I am asking because I was seeing a bug caused by this PR https://github.com/ofiwg/libfabric/pull/8826 which only populate `hmem_data` for FI_VERSION >= 1.19, but the current libfabric version is 1.18.0rc1, which is even lower than the v1.18.x branch.

**Comment by shijin-aws** [comment]
@shefty

**Comment by shefty** [comment]
Yes, we can update the version in preparation for the next release.

**Comment by shijin-aws** [comment]
> Yes, we can update the version in preparation for the next release.

Does that mean the version in main branch is always lower than released branch before preparing a release? That sounds odd to me. 

The bug in https://github.com/ofiwg/libfabric/pull/8826 is that `cur_abi_attr->hmem_data = FI_VERSION_GE(user_version, FI_VERSION(1, 19))` is only populated for libfabric version >=1.19, but the mr attr flags `OFI_HMEM_DATA_GDRCOPY_HANDLE` was added in main branch in https://github.com/ofiwg/libfabric/blob/main/prov/efa/src/efa_mr.c#L268. And here we have an inconsistency.

So we either need to add a FI_VERSION check in https://github.com/ofiwg/libfabric/blob/main/prov/efa/src/efa_mr.c#L268, which is done in https://github.com/ofiwg/libfabric/pull/8902, 
Or we bump the libfabric version in main branch right now to 1.19.

Which solution do you prefer? I would prefer the latter one as having a main branch of 1.18* is kind of strange.

**Comment by shefty** [comment]
We updated the main branch to v1.18.0rc1, then created the v1.18.x branch.  The main branch simply hasn't been updated with a new version since then.  Updating the defines is trivial and can be done.  Updating the version in configure.ac is less trivial and either means waiting closer to the actual release or predicting whether there will be any changes in the public header files.

**Comment by shijin-aws** [comment]
>or predicting whether there will be any changes in the public header files.

I see, I think we should have updated the version as part of this PR https://github.com/ofiwg/libfabric/commit/49d1a767c882242b5531c3f2b1318e16310fede0, which changed the public header files.

**Comment by shefty** [comment]
The version should be MAJOR 1, MINOR 19, REVISION 0.  rc1 is a package number and part of configure.ac.

**Comment by shefty** [comment]
Btw, don't update configure to rc1.  You can update to a1 if needed, but I usually update configure as part of the release process.

**Comment by shijin-aws** [comment]
>Btw, don't update configure to rc1. You can update to a1 if needed, but I usually update configure as part of the release process.

I see, so I can just bump this line https://github.com/ofiwg/libfabric/blob/main/include/rdma/fabric.h#L87, is that good for you?

**Comment by shijin-aws** [comment]
https://github.com/ofiwg/libfabric/pull/8905

**Comment by shijin-aws** [comment]
PR is merged
