### ISSUE TITLE
libfabric-2.0: Remove unused features

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#9007]
These features have limited or no implementations by any providers:

- FI_PRIORITY - only used internally by rxm over verbs, move internal
- FI_PROV_SPECIFIC - not used and value isn't even correct for 64-bit flags
- FI_EP_SOCK_STREAM - for rstream provider, which isn't enabled
- FI_EP_SOCK_DGRAM - not implemented
- FI_XPU_TRIGGER - not implemented
- FI_VARIABLE_MSG - not implemented
- FI_RESTRICTED_COMP
- FI_ASYNC_IOV - HPE has a desire to use, but no current use
- FI_NOTIFY_FLAGS_ONLY - not implemented
- FI_BUFFERED_RECV - deprecated

**Comment by thomasgillis** [comment]
I have a question regarding the plan to remove `FI_XPU_TRIGGER`.
I had in mind that HPE has implemented the feature for their paper (https://arxiv.org/abs/2208.04817). Or is the deferred work queue a different approach?

**Comment by shefty** [comment]
If that is referring to the paper I remember, improvements were marginal.  General triggered operations (FI_TRIGGER) are still planned to be supported.

XPU triggered ops simply end up being limited in how they can be used to be of much value.  I don't see a feasible path forward without some industry standard mechanism defined for interacting between NICs and GPUs, and I'm skeptical any standards body would try to define this.  It forces some requirements on hardware implementation.

GPUs use proprietary back-end 'networks' (nvlink) to connect multiple GPUs together.  Those are mostly limited to GPUs controlled by a single OS.  If those networks are extended to multiple OS's, it makes XPU triggered functionality though libfabric unnecessary.

**Comment by shefty** [comment]
FI_ASYNC_IOV is in use by the opx provider.

**Comment by shefty** [comment]
@j-xiong, I see that FI_BUFFERED_RECV is coded into the mrail and rxm providers.  Does mrail rely on this feature?  I thought it negatively impacted performance relative to alternate mrail paths.  But I see this comment in mrail_cq.c: ```// TODO add regular process comp when FI_BUFFERED_RECV not set```.  The mrail_init.c code or's in FI_BUFFERED_RECV as a mode bit always, and the man page calls it out as a requirement.

**Comment by j-xiong** [comment]
Yes, the recv handling of the mrail provider assumes that FI_BUFFERED_RECV mode is enabled for the rails. The initialization lacks a mode bit checking after fi_getinfo(), though.

**Comment by j-xiong** [comment]
Mostly done in #9852.  FI_BUFFERED_RECV and FI_ASYNC_IOV stays. FI_BUFFERED_RECV is going to be moved internal flag.
