### ISSUE TITLE
libfabric-2.0: scalable endpoint adjustments

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#9008]
Support remains as defined.  Document that scalable endpoints pair best with either FI_THREAD_SAFE or FI_THREAD_COMPLETION multi-threading models.

Open question: Should FI_NAMED_RX_CTX be the default (i.e. required) for scalable endpoint support?

**Comment by j-xiong** [comment]
Documentation done in #9852. No change to FI_NAMED_RX_CTX.
