### ISSUE TITLE
libfabric-2.0: Remove deprecated providers

### ISSUE THREAD

**Issue by shefty** [ofiwg/libfabric#9018]
These have no active development, but will still be available in the 1.x releases:
- bgq
- usnic
- gni
- rstream
- sockets
- netdir (replaced with verbs)

**Comment by shefty** [comment]
Removing sockets provider needs another provider to fill the role of supporting direct provider builds.

**Comment by j-xiong** [comment]
bgq, gni, rstream, netdir have been removed.

sockets and usnic stay.
