### ISSUE TITLE
Libfabric 2.0: Should we remove fi_collective?

### ISSUE THREAD

**Issue by a-szegel** [ofiwg/libfabric#9022]
Do collectives belong in the libfabric API? 

Is there anything a high performance network provider can do better than a higher level library (MPI/NCCL/Others) with regards to collectives?

**Comment by shefty** [comment]
The collective API targets the use of offloaded collective support, such as switched-based collectives, or NIC accelerations.  It does not target replacing MPI/*CCL collective implementations.  In-network collectives end up being associated with some transport protocol, which moves the details further away from middleware.
