### ISSUE TITLE
ofi_consume_iov: inconsistent final consume

### ISSUE THREAD

**Issue by lrbison** [ofiwg/libfabric#9035]
In [iov.c: ofi_consume_iov_desc](https://github.com/ofiwg/libfabric/blob/main/src/iov.c#L63)

**Describe the bug**
The final consume of an iov has different behavior depending on if `*iov_count` is 1.
 - Typical case:
   - `*iov_count` is 1, the loop and memmove are skipped, and `*iov_count` remains 1, and that `iov_len` is now 0.
 - Alternate Case:
   - `*iov_count` is >1, but will be entirely consumed.  In this path the loop is executed, but the memove is a no-op because `i=*iov_count`.  `*iov_count` will be 0, but `iov[0].iov_len` can be non-zero.
   - Calling consume again ignores 0-size and modifies `iov_len` to be 0.

**Expected behavior**
Although in both cases consume_iov indicates fully-consumed iov with either `*iov_count = 0` or `iov_len = 0`, the fact that calling code must check both conditions is error-prone.  This function itself ignores `iov_count=0` case, suggesting that perhaps `iov_count=0` is not even a valid configuration..

What is the preferred behavior here?  Should I make this routine handle 0-sized iovs?  Should I ensure that if an iov is fully consumed that both "empty" conditions are set?  I suspect the iov_len=0 is the condition more commonly checked, or is the function OK as is and I should be careful to check both empty conditions?

**Comment by shefty** [comment]
Reading the code, I agree it can be improved.  I see that the tcp provider has both checks:
```
ofi_consume_iov(rx_entry->iov, &rx_entry->iov_cnt, len);
if (!rx_entry->iov_cnt || !rx_entry->iov[0].iov_len) {
```

I think ofi_consume_iov() makes these assertions:
```
assert(to_consume && *iov_count);
assert(to_consume <= ofi_total_iov_len(iov, *iov_count));
```

To make the code consistent, the iov_count = 1 case needs a check similar to the if statement inside the for-loop, which determines whether we fully consume iov[0] or not.
