### ISSUE TITLE
question: completion semantics `FI_INJECT_COMPLETE` vs `FI_TRANSMIT_COMPLETE` vs `FI_DELIVERY_COMPLETE`

### ISSUE THREAD

**Issue by thomasgillis** [ofiwg/libfabric#9072]
Hi all,

I am reaching out with two questions about the completion semantics.

In the `transmit_complete` semantics, the description is [the following](https://ofiwg.github.io/libfabric/v1.18.0/man/fi_cq.3.html)
> Indicates that a completion should be generated when the transmit operation has completed relative to the local provider. The exact behavior is dependent on the endpoint type.
> **For reliable endpoints:**
> Indicates that a completion should be generated when the operation has been delivered to the peer endpoint. A completion guarantees that the operation is no longer dependent on the fabric or local resources. The state of the operation at the peer endpoint is not defined.
> **For unreliable endpoints:**
> Indicates that a completion should be generated when the operation has been delivered to the fabric. A completion guarantees that the operation is no longer dependent on local resources. The state of the operation within the fabric is not defined.

*question 1*
From the implementation point of view, I think I understand the choice made here (if it's a reliable endpoint, the remote ack is free/cheap).
However, from the user point of view, the description seems reversed.
If my endpoint is reliable, I am assured it is going to be delivered. Therefore I don't care about the `ack`.
If the endpoint is unreliable, then I would like to know that it has reached the other side, and I can use `FI_DELIVERY_COMPLETE` for that purpose.
Is there a technical/implementation reason for the semantics to be the way it is in the API?

*question 2*
Also, as far as I understand, there is no "local" completion defined for reliable endpoints.
By local, I mean something that guarantees that no further progress/action from the origin of the communication is needed. From my understanding, the closest is `FI_INJECT_COMPLETE`, but it might require additional progress for the communication to happen. So even if the operation complete, I might have to read the `cq` to progress, which makes it hard to know when to stop reading the `cq`.
Would the wg consider to change the meaning of `FI_TRANSMIT_COMPLETE` for all endpoints to the current unreliable one?

**Comment by shefty** [comment]
_question 1_
The difference is at what point a failure can occur.  With transmit complete, an ack can be generated by the NIC itself prior to placing the message into host memory.  As a sender, you know that the data reached the remote NIC.  However, it's possible that an error can occur when writing the data from the NIC over PCIe to memory.  A failure there is not captured by transmit complete.

With delivery complete, the app is wanting to know that the data has made it into host memory.  This semantic disables certain optimizations that a provider could use.  For example, it may not be able to use transport offload, and could force the use of a SW ack generated by the CPU, to confirm that the message did get copied into host memory.

Note that a SW ack isn't technically required for delivery complete.  Transport offload could do this, however, the NIC must be designed to delay sending an ack back until after the NIC receive queues have successfully flushed all data into host memory and confirmed from the IO bus that the data is indeed available in memory and not buffered by some IO device.  In practice this requires some level of coordination between the platform and the NIC.

So, for most (maybe all) NICs, delivery complete requires a SW ack generated by the CPU.  However, many NICs support transmit complete semantics natively.

_question 2_
Transmit complete is the semantic that you're needing.  Once you get a completion for a send operation that corresponds to transmit complete, the operation is considered 'out of the network' and no longer dependent on local resources.  The reliability related definition is actually a strong semantic than that used for unreliable.

**Comment by thomasgillis** [comment]
Thanks for your detailed answer @shefty
I extrapolate that the reception of the `ack` requires some work on the origin side for reliable networks.
Which makes sense with the rest of your explanation and the overall completion semantics.
