### ISSUE TITLE
core/hmem: CUDA initialization failure on Debian using recommended CUDA installation

### ISSUE THREAD

**Issue by darrylabbate** [ofiwg/libfabric#9205]
On Debian 10/11 with the [recommended CUDA installation](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#prepare-debian), `cuda_hmem_dl_init()` fails after being unable to find `libnvidia-ml.so` (added by @qkoziol in fad962b8cb2cc7c0333e166a56b2e1144cd92869):

```
libfabric:650071:1691502038::core:core:cuda_hmem_dl_init():444<warn> Failed to dlopen libnvidia-ml.so
```

The `.so` file *is* included with the CUDA installation, but it doesn't seem to be in the standard search path for `dlopen()` (though a symlink to `libnvidia-ml.so.1` is). Obviously this can be mitigated on the user's end, but it'd make for a poor user experience. Likewise, a simple fix could be to change the `dlopen()` call to look for `libnvidia-ml.so.1`, but it's unclear how "safe" that is.

It's possible this issue is limited to the base Debian distribution we're testing against, but I wanted to file an issue here to be safe.

**Comment by qkoziol** [comment]
Working on a patch for this now.
