### ISSUE TITLE
[question] prov/ofi_rxm - atomic performance

### ISSUE THREAD

**Issue by thomasgillis** [ofiwg/libfabric#9253]
I am trying to estimate the performance of `fi_atomic` over `verbs;ofi_rxm` and from what I get, it's not great compared to tagged messages.

From looking at the code (if I am correct), `verbs` supports well atomics, but `rxm` re-implements atomics on top of `fi_msg`.
Is there an existing way to not do that and fallback on the base provider if it supports it?

Thanks for your time/help :-)

**Comment by shefty** [comment]
I'm not sure what sort of comparison you're doing between an atomic operation and sending/receiving a tagged message.  They're entirely different.

Verbs has *very limited* support for atomic operations - something like increment and compare-swap for a single u64 value.  rxm implements the libfabric set of atomics across an array of data types.  rxm uses cpu based atomics, while verbs is NIC based.

**Comment by thomasgillis** [comment]
for more details on the usage, I want to send acks across peers (uint32_t, summed at the target) and compare either tagged messages to do that or atomics to avoid the issue of unexpected messages.

From your answer, should I conclude that the `sum` in my atomic operation makes it hard to support efficiently (and is not available in verbs)?

**Comment by shefty** [comment]
What I think you want is an rxm setting that allows pass-thru atomic support.  That's doable, and probably wouldn't be that much work, but not an option with the current implementation.

I'm surprised rxm atomic support, even if it's all CPU based, would be that much slower than sending acks using tagged messages.  Btw, for acks, you may be able to use non-tagged messages with multi-recv support, if you're not using the fi_msg APIs for another purpose.  Maybe rxm atomic support could be improved here.

As another possibility, you could use a completion counter bound to an RMA write region.  Any write to the region would bump the counter, basically giving you similar functionality as using an atomic increment.  The writes could be 0-length in size.

**Comment by thomasgillis** [comment]
I haven't tried `msg` yet, only `tagged` for now but will def look into it.
The remote counter option is not ideal as in my ack I actually do care about the value that is in it, but I could work around that.
Thanks for the explanations!

PS: I will close this issue as I think it's not very relevant to keep it open
