### ISSUE TITLE
prov/cxi: CQ exhaustion during MPI calls on NERSC's Perlmutter

### ISSUE THREAD

**Issue by jjepson2** [ofiwg/libfabric#9286]
Since you guys are the pros on this (hopefully), I thought I would ask for clarification on this here. My program on Perlmutter at NERSC repeatedly hangs after about an hour of runtime (at an indeterministic location), with this consistent error message:

"PE 0: MPICH WARNING: OFI is failing to make progress on posting a receive. MPICH suspects a hang due to completion queue exhaustion. Setting environment variable FI_CXI_DEFAULT_CQ_SIZE to a higher number might circumvent this scenario. OFI retry continuing..."

I was wondering why I might get this error message, and what could be done to fix it.  For example, if changing FI_CXI_DEFAULT_CQ_SIZE is your recommended answer as suggested, what number should I set it too?  And how would I check default CQ size? Also, is there something I could try in my code that might help with this as well (that would not involve me changing this variable)?  How does the completion queue work exactly?

Thanks.

**Comment by j-xiong** [comment]
@iziemba Could you take a look?

**Comment by thomasgillis** [comment]
@jjepson2 I am not a `cxi` expert but out of curiosity how are you submitting your `MPI_Recv` and `MPI_Send`?

From my own experience, I suspect that the number of uncompleted recv is too large for some cxi queue restriction and mpich cannot add more to the queue. To "unblock" the situation you might want to issue the corresponding `MPI_Send`

**Comment by jjepson2** [comment]
@thomasgillis Yeah, I think it is freezing on some mpi call, hence the error message.  It's hard to know which mpi call in the code it's hanging on, because of the indeterminacy.  I've identified one such place, but there are many places with mpi calls in our code. The place I've identified is one where all processes are sending to the root process.  Wouldn't mpi_receive only return when the root process has received the data?  So there should in theory then be only one mpi_receive on the queue at a given time.  Could the queue be overun by too many mpi_sends at once?

**Comment by thomasgillis** [comment]
I was thinking along the lines of `MPI_Irecv` instead of the `MPI_Recv`. If you submit too many of them (something like >256), you will overrun the queue. But if you don't use `Irecv` then it's def not that.

**Comment by jjepson2** [comment]
@thomasgillis Ok, yeah, I'm not using mpi_ircev.  Just the regular one.

**Comment by thomasgillis** [comment]
can you share your code? it seems to be more of an MPICH issue, than an ofi issue then.
Is it cray-mpich? or open-source mpich?

**Comment by jjepson2** [comment]
It is cray-mpich.  I am checking on whether we are allowed to share the code or not.  It has some licensing restrictions currently.

**Comment by thomasgillis** [comment]
It seems to me (others may disagree?) that you have two options to move forward then:
- cray-mpich: go to the NERSC support. The code is closed and it's hard to know what is happening there.
- install mpich (the open-source one) and submit your problem on the mpich github repo (same with openmpi but I am biased towards MPICH and I am interested in this).

**Comment by jjepson2** [comment]
Ok.  I'll probably go to NERSC support for now.  But if I make any progress on this, or decide to try the open source mpich, I will let you know.

**Comment by jjepson2** [comment]
@thomasgillis While NERSC is working on diagnosing the cray-mpich implementation, I am trying to run with the regular mpich to see if I get the same error.  However, I am getting this error when I try to run on the CPU only nodes on perlmutter (the error occurs when calling mpi_init):

CUDA Error (yaksuri_cuda_init_hook:src/backend/cuda/hooks/yaksuri_cuda_init_hooks.c,173): no CUDA-capable device is detected

Any thoughts of what might be causing this?

**Comment by jjepson2** [comment]
@thomasgillis (or a workaround?)

**Comment by thomasgillis** [comment]
yes, but can we bring this to the mpich repo? (just to not pollute the ofi PRs)
feel free to submit an issue here: https://github.com/pmodels/mpich/issues

**Comment by jjepson2** [comment]
@thomasgillis Yes, I will do that.

**Comment by jjepson2** [comment]
This issue is now resolved, as there was a memory leak for a wrapper we were using for hdf5 dump file writeouts that was causing the completion queue exhaustion error messages when using cray-mpich.  Open-source mpich (at least the version installed on perlmutter which is slightly behind the version that has been published) still does not work, and has scores of other error messages.  I will at least close the issue here, and defer to the issue on mpich's page for further discussion of open-source mpich.
