### ISSUE TITLE
usnic: EP_DGRAM does not fully support flags given via endpoint configuration and *msg functions

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#941]
`usdf_dgram_recvmsg` is ignoring the `flags` parameter and simply passing through to `usdf_dgram_recvv`, which is arguably worse than simply returning `-FI_ENOSYS`.

**Comment by goodell** [comment]
@bturrubiates is looking into this at a low priority level

**Comment by goodell** [comment]
@bturrubiates points out offline that `usdf_dgram_sendmsg` is similarly misbehaving, but we don't appear to have a separate GH issue for it at the moment.  We can track it here for the moment and split it off later if needed.

**Comment by goodell** [comment]
note to self: this (specifically the `recvmsg` bit) was not fixed for the 1.1 release by the recent spate of DGRAM fixes in the usnic provider

**Comment by bturrubiates** [comment]
For receive side it looks the only flag we can actually support is `FI_MORE`. This is supported in the `recvmsg` variety, but not in `fi_recv` with `FI_MORE` configured on the endpoint.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
