### ISSUE TITLE
usnic: implement fi_shutdown()

### ISSUE THREAD

**Issue by goodell** [ofiwg/libfabric#946]
`usdf_cm_msg_shutdown` currently returns `-FI_ENOSYS`

**Comment by jsquyres** [comment]
This *might* get done in time for v1.4.0, but it's low priority.

**Comment by bturrubiates** [comment]
> This might get done in time for v1.4.0, but it's low priority.

I don't think there is sufficient time to implement and test this thoroughly. Deferring until the 1.5 release.

**Comment by shefty** [comment]
usnic is still supported, but has not been updated in several releases.  Closing very old issues.
