### ISSUE TITLE
Update aws-efa-team maintainership

### ISSUE THREAD

**Issue by a-szegel** [ofiwg/libfabric#9473]
Wei and Brian are maintainers.  Please remove Wei from being a maintainer, and make Shi a maintainer. Wei does not have permission to make this change. Thanks

**Comment by j-xiong** [comment]
I just checked, Shi is already a member of the `aws-efa-maintainers` group, which should have write access to the repo. I am not sure how the 'Maintainer' label is added. 

https://github.com/orgs/ofiwg/teams/aws-efa-maintainers

**Comment by shijin-aws** [comment]
>I just checked, Shi is already a member of the aws-efa-maintainers group, which should have write access to the repo. I am not sure how the 'Maintainer' label is added.

Yeah, I know I am in aws-efa-maintainers, but i couldn't modify the aws-efa-team roles for some reason

**Comment by j-xiong** [comment]
Ok, I was able to change Shi's role to 'maintainers'. However, Wei is the owner of the organization so the change role action doesn't work. Who should be changed to be the new owner of the organization?

**Comment by j-xiong** [comment]
It turns out the `owner` role is not needed. I was able to change Wei to `member` role and removed the `maintainer` label.

**Comment by shijin-aws** [comment]
I think Seth was talking about this team: https://github.com/orgs/ofiwg/teams/aws-efa-team. I couldn't modify any member because i am not the maintainer.

**Comment by j-xiong** [comment]
Now it should show the status as expected:

https://github.com/orgs/ofiwg/teams/aws-efa-team/members

**Comment by shijin-aws** [comment]
Oh nice it is updated now

**Comment by shijin-aws** [comment]
Thank you! @j-xiong
