### ISSUE TITLE
Allow different Inject Sizes for Different Libfabric Operations

### ISSUE THREAD

**Issue by a-szegel** [ofiwg/libfabric#9510]
I want to be able to inject the maximum size that my hardware allows for fi_inject.  I want to be able to use some of that inject space for RMA/Atomic headers when I do atomic_inject, or rma_inject.  Right now, the maximum inject size is shared between all operations, and we should split that out by operation.

**Comment by a-szegel** [comment]
While we are on this... we should clearly define HMEM + Inject capabilities.

**Comment by j-xiong** [comment]
implemented.
