### ISSUE TITLE
Libfabric over NAT not working

### ISSUE THREAD

**Issue by ziegenbalg** [ofiwg/libfabric#9611]
This is a continuation of a bug I filed for the DAOS filesystem. It appears that message passing does not work over NAT. Is this a known issue?

**To Reproduce**
Try to pass a message where both endpoints are behind a NAT.

**Expected behavior**
Connection works where client/server IP's are swapped for the NAT'ed address. Not the IP from behind the NAT.

**Output**
See wireshark output. Notice how eventually the server tries to reach out to the clients IP address from behind the NAT (I.e. 172.31.44.136, and not it's NAT'ed address of 18.219.144.132).
![screen](https://github.com/ofiwg/libfabric/assets/56849323/9784d150-ce05-4cef-9b03-3b5b90cb177d)

**Environment:**
Linux

**Additional context**
Libfabric across the internet without vpn. I.e. not a local-net setup.

**Comment by chien-intel** [comment]
It seems you are only capturing on one side of the traffic.  It would be more helpful to have both sides.  Anyhow, it looks like two sides were not in sync and 18.219.144.132 closed the connection while 192.168.50.10 continued to send packets.

* Check your setup for compatible version of software.
* Make sure you are using the same provider on DAOS clients and servers
* Check your NAT setup, make sure the external connection is capable of supporting all the connections behind the NAT.  TCP retransmission is a bit concerning not knowing your configuration.

**Comment by ziegenbalg** [comment]
When I print the address from the socket in: tcpx_cm_recv_req, I get the correct 18.219.144.132 IP address. Somewhere along the way to tcpx_cm_send_resp, the IP address gets switched to 172.31.44.136.

```
Starting process_cm_ctx:
	-> TCPX_CM_LISTENING
Starting tcpx_accept
Starting process_cm_ctx:
	-> TCPX_CM_WAIT_REQ
Starting tcpx_cm_recv_req
Starting rx_cm_data
+++++++++++++++++++++++
IPv4 address: 18.219.144.132
+++++++++++++++++++++++
Starting process_cm_ctx:
	-> TCPX_CM_RESP_READY
Starting tcpx_cm_send_resp
Unknown address family: 8265
Starting tx_cm_data
<Hangs here as it tries to SYN connect to 172.31.44.136>
````

**Comment by chien-intel** [comment]
> Long story short, where 10.35.0.110 tries to send a TCP SYN to 172..31.44.136, I would like that IP to be 18.219.144.132.

Would that solve your problem?  do you have any DAOS code running on 18.219.144.132 or do you have any network config that would route traffic from the internet to 172.31.44.136 where DAOS client is running?  You have opened up ports on the DAOS server side, you need to do the same on the DAOS client side.  In server.pcap, frame 19-23, 10.35.0.110 tried to initiate a connection to 172.31.44.36 (this is DAOS server connecting directly to DAOS client) and it couldn't get through.

**Comment by j-xiong** [comment]
I don't think such configuration is supported. The way OFI RDM endpoint works is that each end needs to know the endpoint address of the peer in order to send a message. The client can resolve the server endpoint address by passing known published name and port via the `node` and `service` parameter to the `fi_getinfo()` call. However, the server can only get the client's address from the request sent by the client. The client gets its own endpoint address via `fi_getname()`.  Such endpoint address contains the internal address not the NAT'ed public address. This info is part of the payload sent to the server and won't be translated by NAT.
