### ISSUE TITLE
Does local completion of fi_write imply remote completion?

### ISSUE THREAD

**Issue by JiakunYan** [ofiwg/libfabric#9651]
Just want a clarification: If a `fi_write` operation has been reported as completed locally through a completion queue, can we safely assume the data has been written to the remote memory?

**Comment by chien-intel** [comment]
If you are using verbs provider and device with proper support for RDMA write then yes, otherwise, you want to read up on fi_cq specifically FI_DELIVERY_COMPLETE

**Comment by shijin-aws** [comment]
> we safely assume the data has been written to the remote memory?

if you have `FI_DELIVERY_COMPLETE` in flags, in Libfabric's point of view, the data should be written to the remote memory when writing the completion.

**Comment by JiakunYan** [comment]
Thanks! `FI_DELIVERY_COMPLETE` is exactly what I want!
