### ISSUE TITLE
Clarification on the msg arguments of fi_*msg functions

### ISSUE THREAD

**Issue by JiakunYan** [ofiwg/libfabric#9653]
Apologies if this is a dumb question, but I failed to find sentences in the manpage that explicitly define the requirement.

In `fi_*msg` functions (for example, `fi_writemsg`), what is the lifetime requirement for the `const struct fi_msg_rma *msg` argument? Does it need to stay valid in the memory until the operation is reported completed through completion queues? How about the SGLs in the `msg` argument, namely `const struct iovec *msg_iov` and `const struct fi_rma_iov *rma_iov`? Do they need to stay valid until the operation completed?

**Comment by shijin-aws** [comment]
>what is the lifetime requirement for the const struct fi_msg_rma *msg argument? Does it need to stay valid in the memory until the operation is reported completed through completion queues?

I think when the transmission call returns, `msg` itself (not including the iov) doesn't need to stay valid.

>How about the SGLs in the msg argument, namely const struct iovec *msg_iov and const struct fi_rma_iov *rma_iov? Do they need to stay valid until the operation completed?

when you use inject calls like fi_inject, fi_tinject, and fi_inject_write, at call returns you can reuse the SGL. For non-inject path, it is usually required that SGL needs to be valid before you get a completion

>Do they need to stay valid until the operation completed?

This is the completion semantic of FI_INJECT_COMPLETE, which means when getting the completion, the send buffer can be reused. Usually providers implement a stronger completion semantic by default,  like FI_TRANSMIT_COMPLETE.

**Comment by aingerson** [comment]
To add to what Shi said, yes the msg itself does not need to stay valid after the call returns and that is also true for the struct iov as well. The data which the iov points to though has to stay valid until the operation completes (except for inject calls).

**Comment by JiakunYan** [comment]
Got it! Thanks for your answers!
