### ISSUE TITLE
sockets provider: Issues with fi_setname()

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#966]
There are at least two issues with the `fi_setname()` implementation in the sockets provider:

1. If I pass an address containing a port number of 0, I should get assigned an ephemeral port number and receive the ephemeral port number back if I immediately call `fi_getname()`.
2. There is a crash in the sockets provider in a simple test I was writing to try to track down the cause of the previous issue.  It's on the `setname-test` branch of my fabtests fork.  The server crashes when a client connects and these are the last log messages printed out:

```
libfabric:core:core:fi_register_provider():121<info> registering provider: sockets (1.0)
libfabric:sockets:fabric:sock_ep_getinfo():463<info> src_addr: 10.1.0.32
libfabric:sockets:fabric:sock_ep_getinfo():465<info> dest_addr: 172.16.10.90
libfabric:sockets:ep_ctrl:sock_pep_create_listener_thread():1110<info> Listener thread bound to 10.1.0.32:9228
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():941<info> Starting listener thread for PEP: 0x19b4950
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():991<info> Total received: 544
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():996<info> CM msg received: 544
libfabric:sockets:ep_ctrl:sock_ep_cm_send_ack():439<info> Total Sent: 16
libfabric:sockets:ep_ctrl:sock_pep_listener_thread():1009<info> Received SOCK_CONN_REQ
libfabric:sockets:fabric:sock_verify_info():264<info> no matching fabric
libfabric:sockets:ep_ctrl:sock_ep_msg_process_info():919<info> incoming conn_req not supported
```

@jithinjosepkl

**Comment by jithinjosepkl** [comment]
Please try with pr/sockets.
It would be great if you could add the test into the fabtests.

Btw, in the test both client and server create passive endpoint. Looks like a missing check here.
