### ISSUE TITLE
NEWS.md file out of date on main

### ISSUE THREAD

**Issue by lrbison** [ofiwg/libfabric#9687]
It seems the NEWS.md file on [main branch](https://github.com/ofiwg/libfabric/blob/main/NEWS.md) is not up to date with NEWS.md from [v1.20.0 branch](https://github.com/ofiwg/libfabric/blob/v1.20.0/NEWS.md).  The main-branch version doesn't have any content in the 1.20 release.

**Comment by j-xiong** [comment]
That's expected.

The content of NEWS.md on the main branch is the snapshot when the v1.20.x branch was created, at which point the detailed changes for 1.20 had not yet filled in. The latest change log from all stable branches (including v1.20.x) will be synched back to the main branch when the v1.21.x branch is created.

**Comment by lrbison** [comment]
Seems counter-intuitive to me if I want to find the latest updates 🤷
