### ISSUE TITLE
Verbs provider leaving verbs_info_lock locked upon error in fi_ibv_init_info()

### ISSUE THREAD

**Issue by jsquyres** [ofiwg/libfabric#977]
On one hand, leaving this mutex locked doesn't matter, because the provider will be returning no results.

But on the other hand, it's icky.

But on the third hand, what if an application fixes the error with the underlying verbs devices and then calls `fi_getinfo()` again?  `fi_ibv_init_info()` would then deadlock when it tries to lock the mutex again (yes, this would be unusual by today's applications, but it is certainly possible).

There's multiple cases where this routine can exit and leave the `verbs_info_lock` mutex locked:

* if `rdma_get_devices()` returns an error
* goto `err2` or `err1`

**Comment by shefty** [comment]
asking @a-ilango to look into this

**Comment by shefty** [comment]
nm - I'll look at this fix as part of avoiding the prints from the librdmacm

**Comment by a-ilango** [comment]
I have a fix for this in PR #983
