### ISSUE TITLE
[Question] How to specify an optional mr_mode flag in fi_getinfo(..) hints

### ISSUE THREAD

**Issue by wenduwan** [ofiwg/libfabric#9777]
**~~Describe the bug~~Question**
Hi community, I wonder if there is a recommended way to communicate to providers at fi_getinfo(...), that a specific mr_mode flag is optional instead of required?

**Additional context**
This question is related to Open MPI https://github.com/open-mpi/ompi/pull/12292

The idea is to make `FI_MR_PROV_KEY` optional, but as libfabric API currently stands, removing `FI_MR_PROV_KEY` will disqualify providers that requires `FI_MR_PROV_KEY`.

**Comment by j-xiong** [comment]
mr_mode is requirement by the provider, not by the application. An application sets the bits to indicate that it is ready to handle to such requirement. A provider should clear the bits if it doesn't have that requirement, and the application should check the bits returned from fi_getinfo() to ensure correct action is taken. From application point of view, the mode bits are always optional.

**Comment by wenduwan** [comment]
Thanks for your reply. I see you also commented on the PR. I will close this issue.
