### ISSUE TITLE
prov/cxi: configure failure - error codes undeclared

### ISSUE THREAD

**Issue by thomasgillis** [ofiwg/libfabric#9789]
**Describe the bug**
Hi all, 
I am trying to compile `cxi` from source, and I get a configure error with both `gcc-11.2.0` and `clang-14.0` (used the cray wrappers `cc` and `CC`):

```
./configure --enable-cxi --with-hip
[...]
configure: *** Configuring cxi provider
checking cxi_prov_hw.h usability... no
checking cxi_prov_hw.h presence... yes
configure: WARNING: cxi_prov_hw.h: present but cannot be compiled
configure: WARNING: cxi_prov_hw.h:     check for missing prerequisite headers?
configure: WARNING: cxi_prov_hw.h: see the Autoconf documentation
configure: WARNING: cxi_prov_hw.h:     section "Present But Cannot Be Compiled"
configure: WARNING: cxi_prov_hw.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------ ##
configure: WARNING:     ## Report this to ofiwg@lists.openfabrics.org ##
configure: WARNING:     ## ------------------------------------------ ##
checking for cxi_prov_hw.h... no
checking uapi/misc/cxi.h usability... no
checking uapi/misc/cxi.h presence... yes
configure: WARNING: uapi/misc/cxi.h: present but cannot be compiled
configure: WARNING: uapi/misc/cxi.h:     check for missing prerequisite headers?
configure: WARNING: uapi/misc/cxi.h: see the Autoconf documentation
configure: WARNING: uapi/misc/cxi.h:     section "Present But Cannot Be Compiled"
configure: WARNING: uapi/misc/cxi.h: proceeding with the compiler's result
configure: WARNING:     ## ------------------------------------------ ##
configure: WARNING:     ## Report this to ofiwg@lists.openfabrics.org ##
configure: WARNING:     ## ------------------------------------------ ##
checking for uapi/misc/cxi.h... no
checking libcxi/libcxi.h usability... yes
checking libcxi/libcxi.h presence... yes
checking for libcxi/libcxi.h... yes
```

When looking at the `config.log` it seems to be stuck on the undefined `ENOSPC` error code:
```
configure:34464: cc -c -O2 -DNDEBUG -fvisibility=hidden -Wall -Wundef -Wpointer-arith    conftest.c >&5
In file included from conftest.c:145:
/usr/include/cxi_prov_hw.h:805:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC;
                        ^
/usr/include/cxi_prov_hw.h:856:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC;
                        ^
/usr/include/cxi_prov_hw.h:939:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC; /* not possible */
                        ^
/usr/include/cxi_prov_hw.h:983:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC;
                        ^
/usr/include/cxi_prov_hw.h:1052:11: error: use of undeclared identifier 'EINVAL'
                return -EINVAL;
                        ^
/usr/include/cxi_prov_hw.h:1320:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC;
                        ^
/usr/include/cxi_prov_hw.h:1349:11: error: use of undeclared identifier 'ENOSPC'
                return -ENOSPC;
                        ^
7 errors generated.
```

I presume one of the file misses `#include "errno.h"`, but it's unclear to me which one should get it.
Do you have any guidance on how to fix the error?

**Comment by jswaro** [comment]
The problem lies in the two header files, not the provider. 

To work-around this problem, use the following patch applies to the configure.m4

```
diff --git a/prov/cxi/configure.m4 b/prov/cxi/configure.m4
index ec50e18f3..a73e86e31 100644
--- a/prov/cxi/configure.m4
+++ b/prov/cxi/configure.m4
@@ -46,11 +46,18 @@ AC_DEFUN([FI_CXI_CONFIGURE],[
                [
                        AC_CHECK_HEADER(cxi_prov_hw.h,
                                [],
-                               [cxi_happy=0])
+                               [cxi_happy=0],
+                               [AC_INCLUDES_DEFAULT
+                               #include <errno.h>])

                        AC_CHECK_HEADER(uapi/misc/cxi.h,
                                [],
-                               [cxi_happy=0])
+                               [cxi_happy=0],
+                               [AC_INCLUDES_DEFAULT
+                               #include <stdbool.h>
+                               #ifndef __user
+                               #define __user
+                               #endif])
```

In an upcoming release of the software, SHS 2.2.0, the compilation problem reported in this ticket will be fixed.

**Comment by thomasgillis** [comment]
the diff provided has been implemented successfully and is available at: https://github.com/thomasgillis/libfabric/tree/dev-cxi

**Comment by jain-jainendra** [comment]
> The problem lies in the two header files, not the provider.
> 
> To work-around this problem, use the following patch applied to the prov/cxi/configure.m4
> 
> ```
> diff --git a/prov/cxi/configure.m4 b/prov/cxi/configure.m4
> index ec50e18f3..a73e86e31 100644
> --- a/prov/cxi/configure.m4
> +++ b/prov/cxi/configure.m4
> @@ -46,11 +46,18 @@ AC_DEFUN([FI_CXI_CONFIGURE],[
>                 [
>                         AC_CHECK_HEADER(cxi_prov_hw.h,
>                                 [],
> -                               [cxi_happy=0])
> +                               [cxi_happy=0],
> +                               [AC_INCLUDES_DEFAULT
> +                               #include <errno.h>])
> 
>                         AC_CHECK_HEADER(uapi/misc/cxi.h,
>                                 [],
> -                               [cxi_happy=0])
> +                               [cxi_happy=0],
> +                               [AC_INCLUDES_DEFAULT
> +                               #include <stdbool.h>
> +                               #ifndef __user
> +                               #define __user
> +                               #endif])
> ```
> 
> In an upcoming release of the software, SHS 2.2.0, the compilation problem reported in this ticket will be fixed.

The main code still does not have this changes. If added manually it fails to build. Any solution for this?

**Comment by thomasgillis** [comment]
The full patch should be available here: https://github.com/thomasgillis/libfabric/tree/dev-cxi

Let me know if it doesn't work
