### ISSUE TITLE
Must endpoints for accepted connections inherit the port number of the listening endpoint?

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#981]
Just a question that came up as part of the discussion on PR #967.  Since that PR already looks good, I'm separating out this question into a separate issue.

In both POSIX sockets and verbs, an accepted connection inherits the port number of the listening socket.  The sockets provider does not have this behavior, since the listening port number is that of the "sockets CM", as I understand it.

@shefty Should the sockets provider be fixed to have the accepted connection return the port number of the corresponding listener to `fi_getname()`, or is this something that EXS and rsockets will have to work around?

**Comment by shefty** [comment]
Jithin and I were talking about this. I think this is something the ULP needs to work around, or we may end up restricting the implementation. But we can discuss if this is the right approach.

**Comment by shefty** [comment]
Are we okay closing this issue as, 'problem has been punted to the app'?

**Comment by goodell** [comment]
If there's a reasonable workaround for the app, then I have no strong preference.  If the app is stuck without us doing this, we should probably investigate a solution.

**Comment by shefty** [comment]
Well, in the case of IB, there isn't any port number associated with an accepted connection.  It's all pretend.  I don't think there's a huge burden on the ULP to maintain this.  The provider may not be able to without forcing it to be aware of socket semantics.

**Comment by patrickmacarthur** [comment]
I implemented a workaround for this in EXS, so this can be closed.
