### ISSUE TITLE
sockets: fi_getname()/fi_getpeer() set addrlen incorrectly

### ISSUE THREAD

**Issue by patrickmacarthur** [ofiwg/libfabric#985]
The man page for `fi_getname()` and `fi_getpeer()` states: 
> On output, addrlen is set to the size of the buffer needed to store the address, which may be larger than the input value.

The sockets provider instead sets addrlen to the number of bytes actually stored.  The sockets provider should be updated to match the description in the man page.

@jithinjosepkl

**Comment by patrickmacarthur** [comment]
While running regression tests against my UNH EXS libfabric branch, I ran into this issue again.  I don't think this issue was ever actually fixed.  The bugfix merged for this makes `fi_getpeer()` return `-FI_ETOOSMALL`, but it still does not set `*addrlen` to the length of the full address.

The fix should be relatively simple; the length passed to memset is correct but it shouldn't be put into `*addrlen`, which should be set instead to the length of the actual address.  Not sure if there is time to get this into 1.1.1 but I'd like to get a fix into master for the 1.2.0 release at the very least.

Unfortunately I do not believe that I have permission to re-open this issue.

**Comment by shefty** [comment]
Let's try to get this into 1.1.1.
