### ISSUE TITLE
[ofi 2.0] Make fabtests/benchmarks able to use single CQ per EP

### ISSUE THREAD

**Issue by shijin-aws** [ofiwg/libfabric#9899]
Currently, fabtests still use separate tx and rx cq per EP for benchmarks. 

For ofi 2.0, we propose to restrict binding 1 CQ per EP. The current fabtests should at least be configured to allow binding 1 CQ per EP for benchmarks.

**Comment by j-xiong** [comment]
Unrelated to the CQ change for 2.0.  More in line with current usage. Could be complicated to distinguish send/recv completions.

**Comment by j-xiong** [comment]
We no long limit single CQ for EP. This not no longer needed.
